Repository Sage/carbon, pull requests merged in 2018-06, with the labels that each got.

#1755 Prepare for v4.1.0
  package-lock.json
  package.json
Labels: No QA Required, Passed Review

#1710 Render the Menu component using semantic HTML
  .travis.yml
  CHANGELOG.md
  src/components/menu/menu-item/menu-item.js
  src/components/menu/menu-item/menu-item.scss
  src/components/menu/menu.js
  src/components/menu/menu.scss
Labels: Accessibility, Passed QA, Passed Review

#1760 removes hacks in demo site for components
  demo/views/pages/component/component-preview/component-preview.scss
Labels: No QA Required, No UX Review Required, Passed Review

#1768 upgraded carbon-factory to v4.2.2
  CHANGELOG.md
  package-lock.json
  package.json
  webpack.config.js
Labels: No QA Required, No UX Review Required, Passed Review

#1770 [1767] CustomDragLayer can now take className prop
  CHANGELOG.md
  src/components/drag-and-drop/custom-drag-layer/__spec__.js
  src/components/drag-and-drop/custom-drag-layer/custom-drag-layer.js
Labels: Passed QA, Passed Review

#1772 Add max workers to travis ci build
  .travis.yml
  CHANGELOG.md
Labels: Passed Review

#1765 Add blue background to table lines when selected
  CHANGELOG.md
  src/components/table/table--secondary-theme.scss
Labels: Passed QA, Passed Review, Resolve merge conflicts

#1762 Stop rendering a type attribute for the Icon's type prop
  CHANGELOG.md
  src/components/dialog-full-screen/__snapshots__/__spec__.js.snap
  src/components/icon/icon.js
  src/components/portal/__snapshots__/__spec__.js.snap
  src/utils/helpers/browser/__spec__.js
Labels: Passed QA, Passed Review

#1773 Remove Gulp from README and correct port
  README.md
Labels: No QA Required, Passed Review

#1771 Add redirectAfter method to Browser
  CHANGELOG.md
  src/utils/helpers/browser/__spec__.js
  src/utils/helpers/browser/browser.js
Labels: Passed QA, Passed Review

#1774 Remove gulp
  README.md
  docs/guides/getting-started.md
  docs/guides/setting-up-your-environment.md
  gulpfile.js
  package-lock.json
  package.json
Labels: Passed Review

#1775 Remove gulp
  CHANGELOG.md
  docs/guides/getting-started.md
  docs/guides/setting-up-your-environment.md
  gulpfile.js
  package-lock.json
  package.json
Labels: Passed Review
