Repository Sage/carbon, pull requests merged in 2018-04, with the labels that each got.

#1722 v3.2.0
  package-lock.json
  package.json
Labels: Passed Review

#1726 release v3_1_3
  package-lock.json
  package.json
Labels: Passed Review

#1728 Portal ie fix
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/dropdown/dropdown.js
Labels: Passed Review

#1736 Fixes the offset problem for error messages too
  CHANGELOG.md
  src/utils/decorators/input-validation/input-validation.js
Labels: Passed Review

#1731 Fix issue with hover styles on readonly and disabled inputs
  CHANGELOG.md
  src/utils/decorators/input/input.scss
Labels: On Backlog, Passed QA, Passed Review

#1732 Position textarea label at the top
  CHANGELOG.md
  src/components/textarea/textarea.scss
Labels: Passed QA, Passed Review

#1738 Merge release (3.2.3) to master
  CHANGELOG.md
  package-lock.json
  package.json
  src/utils/decorators/input-validation/input-validation.js
Labels: No QA Required, Passed Review

#1739 Bump version number for 3.2.4 release
  package.json
Labels: Passed Review

#1740 Merge master to release
  CHANGELOG.md
  package.json
  src/components/textarea/textarea.scss
  src/utils/decorators/input/input.scss
Labels: Passed Review

#1742 Fix Flash component not opening on initial render
  CHANGELOG.md
  src/components/flash/__spec__.js
  src/components/flash/flash.js
Labels: Passed QA, Passed Review

#1743 Bump version number to v3.2.5
  package-lock.json
  package.json
Labels: Passed Review
