Repository Sage/carbon, pull requests merged in 2018-09, with the labels that each got.

#1842 Release 4.7.0 mergeback
  change_log/v4_7_0/add-withCredentials-dropdownfilterajax.yml
  change_log/v4_7_0/component_docs.yml
  package-lock.json
  package.json
  release_notes/v4_7_0.html.md
Labels: Passed Review

#1843 Scroll on draggable
  change_log/next/1843.yml
  src/components/drag-and-drop/draggable-context/__definition__.js
  src/components/drag-and-drop/draggable-context/__spec__.js
  src/components/drag-and-drop/draggable-context/draggable-context.js
  src/components/portal/portal.js
  src/utils/helpers/scrollable-parent/__spec__.js
  src/utils/helpers/scrollable-parent/package.json
  src/utils/helpers/scrollable-parent/scrollable-parent.js
Labels: Enhancement, Passed QA, Passed Review, Passed UX Review

#1828 Icon Font Updates
  change_log/next/SOGUX-4675.yml
  demo/views/pages/style/icons/icon-list/icon-list.js
  src/components/icon/fonts/carbon-icons-webfont.ttf
  src/components/icon/fonts/carbon-icons-webfont.woff
  src/components/icon/icon.scss
Labels: Passed QA, Passed Review, Passed UX Review
