Repository Sage/carbon, pull requests merged in 2019-08, with the labels that each got.

#2215 FE-1761 fixed bug with pages not switching.
  change_log/v9_0_0/FE-1761-pages-switch-fix.yaml
  src/components/date/__snapshots__/date.spec.js.snap
  src/components/pages/pages.stories.js
Labels: Passed QA, Passed Review, Squad Front End

#2239 FE-1898 redundant knobs
  src/components/pill/pill.stories.js
Labels: Pending Review, Squad Front End

#2206 FE-1321 RadioButton & RadioButtonGroup DLS components
  change_log/next/FE-1321-dls-radio-button.yml
  demo/views/pages/component/component-api/component-api.js
  src/__experimental__/components/checkable-input/__snapshots__/hidden-checkable-input.spec.js.snap
  src/__experimental__/components/checkable-input/checkable-input-svg-wrapper.style.js
  src/__experimental__/components/checkable-input/checkable-input.component.js
  src/__experimental__/components/checkable-input/checkable-input.spec.js
  src/__experimental__/components/checkable-input/checkable-input.style.js
  src/__experimental__/components/checkable-input/hidden-checkable-input.component.js
  src/__experimental__/components/checkable-input/hidden-checkable-input.spec.js
  src/__experimental__/components/checkbox/__snapshots__/checkbox.spec.js.snap
  src/__experimental__/components/checkbox/checkbox-classic.style.js
  src/__experimental__/components/checkbox/checkbox-svg-wrapper.style.js
  src/__experimental__/components/checkbox/checkbox-svg.component.js
  src/__experimental__/components/checkbox/checkbox.component.js
  src/__experimental__/components/checkbox/checkbox.spec.js
  src/__experimental__/components/checkbox/checkbox.stories.js
  src/__experimental__/components/checkbox/checkbox.style.js
  src/__experimental__/components/form-field/form-field.component.js
  src/__experimental__/components/label/label.component.js
  src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap
  src/__experimental__/components/radio-button/documentation/index.js
  src/__experimental__/components/radio-button/documentation/info.js
  src/__experimental__/components/radio-button/documentation/notes.md
  src/__experimental__/components/radio-button/index.js
  src/__experimental__/components/radio-button/radio-button-classic.style.js
  src/__experimental__/components/radio-button/radio-button-group.component.js
  src/__experimental__/components/radio-button/radio-button-group.spec.js
  src/__experimental__/components/radio-button/radio-button-svg.component.js
  src/__experimental__/components/radio-button/radio-button.component.js
  src/__experimental__/components/radio-button/radio-button.spec.js
  src/__experimental__/components/radio-button/radio-button.stories.js
  src/__experimental__/components/radio-button/radio-button.style.js
  src/__experimental__/components/switch/__snapshots__/switch.spec.js.snap
  src/__experimental__/components/switch/switch.component.js
  src/__experimental__/components/switch/switch.spec.js
  src/__experimental__/components/switch/switch.stories.js
  src/components/checkbox/__definition__.js
  src/components/help/help.component.js
  src/components/radio-button/__definition__.js
  src/components/radio-button/__spec__.js
  src/components/radio-button/package.json
  src/components/radio-button/radio-button.js
  src/components/radio-button/radio-button.scss
  src/components/radio-button/radio-button.stories.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2240 removes fullstops from buttons
  src/components/pages/pages.stories.js
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2241 FE-1906 Pill close button
  src/components/pill/pill.style.js
Labels: Bug, Squad Front End

#2244 Fix failing carousel.feature tests
  cypress/features/regression/carousel.feature
  cypress/locators/carousel/locators.js
  cypress/support/step-definitions/carousel-steps.js
  src/components/carousel/carousel.component.js
Labels: Cypress, Passed Review, Squad Front End

#2248 Bumps lock version to rc2
  package-lock.json
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2213 FE-1655 updated styles for small, medium and large themes. Updated sp…
  change_log/v9_0_0/FE-1655.yaml
  src/__experimental__/components/select/select.style.js
  src/components/button/button.style.js
  src/components/pill/pill-classic.style.js
  src/components/pill/pill.component.js
  src/components/pill/pill.spec.js
  src/components/pill/pill.stories.js
  src/components/pill/pill.style.js
  src/utils/helpers/options-helper/options-helper.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2200 Theme Storybook to DLS
  .assets/carbon-by-sage-logo.png
  .storybook/__helpers__/components/app-layout/app-layout.js
  .storybook/config.js
  .storybook/sageTheme.js
  .storybook/style/story-root.scss
  .storybook/style/storybook-info.styles.js
  change_log/next/SOGUX-6133.yml
  package.json
  src/components/help/help.stories.js
  src/components/help/help.stories.scss
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2249 Mergeback of rc2 lock
  package-lock.json
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2238 FE-1845 responsive form footer
  change_log/next/FE-1845-make-sticky-footer-responsive$.yml
  src/__experimental__/components/form/__snapshots__/form.spec.js.snap
  src/__experimental__/components/form/form.component.js
  src/__experimental__/components/form/form.spec.js
  src/__experimental__/components/form/form.stories.js
  src/components/form/form.component.js
  src/components/form/form.spec.js
  src/components/form/form.stories.js
  src/components/form/form.style.js
  src/utils/helpers/element-resize/element-resize.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2251 Ensure storybook compiles correctly for deployment
  .storybook/sageTheme.js
  package.json
Labels: No QA Required, No UX QA Required, Passed Review

#2255 added new package to download on Ubuntu for cypress tests
  .travis.yml
Labels: Cypress, Squad Front End

#2254 fix memory leak
  cypress/plugins/index.js
Labels: Cypress, Squad Front End

#2257 fix for importing for docker
  Dockerfile-cypress
Labels: Cypress

#2243 adds passive config prop to table context
  change_log/next/add-isPassiveData-prop-to-table.yml
  src/components/table/__spec__.js
  src/components/table/table-cell/table-cell.scss
  src/components/table/table-row/table-row.js
  src/components/table/table.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2263 changes from release of v8.1.1
  change_log/v8_1_1/add-isPassiveData-prop-to-table.yml
  change_log/v8_1_1/tabs_new_prop.yml
  package-lock.json
  release_notes/v8_1_1.html.md
  src/components/table/table-row/table-row.component.js
  src/components/table/table.component.js
  src/components/table/table.spec.js
  src/components/tabs/__definition__.js
  src/components/tabs/tabs.component.js
  src/components/tabs/tabs.spec.js
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#2264 Add passive functionality to dls table
  change_log/next/FE-1948-update-table-to-support-passive-data.yml
  src/components/table/__snapshots__/table.spec.js.snap
  src/components/table/table-modern.style.js
  src/components/table/table-row/__snapshots__/table-row.spec.js.snap
  src/components/table/table-row/table-row-classic.style.js
  src/components/table/table-row/table-row-modern.style.js
  src/components/table/table.stories.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2194 Date component - The visible value is empty if the value is empty
  change_log/next/date_allows_empty_value.yml
  change_log/next/date_position_picker.yml
  src/components/date/__definition__.js
  src/components/date/__spec__.js
  src/components/date/date.js
Labels: Passed QA, Passed Review

#2270 Update release for v8.1.2
  change_log/v8_1_2/date_allows_empty_value.yml
  change_log/v8_1_2/date_position_picker.yml
  package-lock.json
  package.json
  release_notes/v8_1_2.html.md
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2272 New mergeback v8-1-2
  change_log/v8_1_2/date_allows_empty_value.yml
  change_log/v8_1_2/date_position_picker.yml
  package-lock.json
  release_notes/v8_1_2.html.md
  src/components/date/__definition__.js
  src/components/date/date.component.js
  src/components/date/date.spec.js
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#2279 Cypress - fix for stickyFormFooter, fix for Confirm component
  cypress/features/regression/confirm.feature
  cypress/features/regression/dialog.feature
  cypress/locators/dialog/locators.js
  cypress/support/step-definitions/confirm-steps.js
  cypress/support/step-definitions/dialog-steps.js
Labels: Cypress

#2284 Updates carbon-factory and bumps version with notes for release
  change_log/v8_1_3/update-to-latest-carbon-factory.yml
  package-lock.json
  package.json
  release_notes/v8_1_3.html.md
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2288 Merge back for v8.1.3
  change_log/v8_1_3/update-to-latest-carbon-factory.yml
  package-lock.json
  package.json
  release_notes/v8_1_3.html.md
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#2275 add test for carbon build
  .travis.yml
  package.json
Labels: No QA Required, Passed Review, Squad Front End

#2286 docs: add docs on how to override the theme FE-1901
  change_log/next/FE-1901-theme-overrides.yml
  src/style/themes/theme.stories.js
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2291 feat: add google analytics to storybook FE-1913
  .storybook/addons.js
  .storybook/google-analytics/register.js
  change_log/next/FE-1913-add-google-analytics.yml
  package-lock.json
  package.json
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2295 FE-1911 add missing index.js file to the Spinner Component
  demo/views/pages/document/document.js
  src/components/loader/loader.stories.js
  src/components/spinner/index.js
  src/components/table/table.component.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End
