Repository Sage/carbon, pull requests merged in 2019-12, with the labels that each got.

#2516 FE-2428 Enzyme Snapshot Helper
  src/__spec_helper__/enzyme-snapshot-helper.js
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2521 upgraded cypress version
  Dockerfile-cypress
  package-lock.json
  package.json
Labels: Cypress

#2518 refactor: removes title attribute from Tab StyledDiv to remove obtrusive tooltip
  change_log/next/FE-2281-remove-tabs-child-tooltip.yml
  src/components/tabs/tab/tab.component.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2529 Merge back v10.0.0
  change_log/v10_0_0/FE-1865-allow-empty-date-value.yml
  change_log/v10_0_0/FE-2022.yml
  change_log/v10_0_0/FE-2047-pager-i18n.yml
  change_log/v10_0_0/FE-2066-upgrade-react.yml
  change_log/v10_0_0/FE-2067-fix-help-icon-colour-wrong-for-classic.yml
  change_log/v10_0_0/FE-2068-fix-for-incorrect-Switch-label-position.yml
  change_log/v10_0_0/FE-2082-tables-wrong-pagination-behaviour.yml
  change_log/v10_0_0/FE-2093-ButtonToggleGroup-controlled-component.yml
  change_log/v10_0_0/FE-2124-fix-defects-with-experimental-date.yml
  change_log/v10_0_0/FE-2132-configurable-items-wrong-cursor.yml
  change_log/v10_0_0/FE-2153-button-icon-wrong-color.yml
  change_log/v10_0_0/FE-2159-link-component.yml
  change_log/v10_0_0/FE-2168-tie-label-to-input.yml
  change_log/v10_0_0/FE-2177-SimpleColorPicker-interface-refactor.yml
  change_log/v10_0_0/FE-2178-SimpleColorPicker-does-not-implement-legend.yml
  change_log/v10_0_0/FE-2179-SimpleColorPicker-does-not-work-when-uncontrolled.yml
  change_log/v10_0_0/FE-2217-select-list-loop.yml
  change_log/v10_0_0/FE-2233-action-popover-lack-of-attributes.yml
  change_log/v10_0_0/FE-2240-flash-component-id.yml
  change_log/v10_0_0/FE-2241-message-component-id.yml
  change_log/v10_0_0/FE-2263-textarea-fieldhelp-bugfix.yml
  change_log/v10_0_0/FE-2264-validations-icons-size.yml
  change_log/v10_0_0/FE-2265-date-input.yml
  change_log/v10_0_0/FE-2273-RadioButton-set-defaut-value-by-passing-defaultChecked.yml
  change_log/v10_0_0/FE-2274-unknown-component.yml
  change_log/v10_0_0/FE-2293_fixed_date_input.yml
  change_log/v10_0_0/FE-2296-fix-focus-and-blur-in-date-input.yml
  change_log/v10_0_0/FE-2307-select-onblur.yml
  change_log/v10_0_0/FE-2309-fix_child_button_submitting_form.yml
  change_log/v10_0_0/FE-2311-radiobutton-unknown-component-present-proptables.yml
  change_log/v10_0_0/FE-2312-switch-unknown-component-present-propTables.yml
  change_log/v10_0_0/FE-2313-demo-site-textbox-icon-position.yml
  change_log/v10_0_0/FE-2323-select-onBlur-fires-while-removing-option.yml
  change_log/v10_0_0/FE-2342-multi-select-onblur-ie11.yml
  change_log/v10_0_0/FE-2367-pages-backlink-label-misalignment.yml
  change_log/v10_0_0/FE-2394-add-hidden-input-to-date.yml
  change_log/v10_0_0/FE-2405-move-validation-array-out-of-render.yml
  change_log/v10_0_0/FE-2414-action-popover-prevent-propagation.yml
  change_log/v10_0_0/update-guides.yml
  package-lock.json
  package.json
  release_notes/v10_0_0.html.md
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2515 FE-2422 Select option mouse hover block
  change_log/next/FE-2422-select-option-mouse-hover-block.yml
  src/components/scrollable-list/scrollable-list.component.js
  src/components/scrollable-list/scrollable-list.spec.js
Labels: Passed QA, Passed Review, Squad Front End

#2514 FE-2306 - Fix sticky footer flickering issue
  .vscode/launch.json
  change_log/next/FE-2306-fix-sticky-footer-flickering.yml
  src/__experimental__/components/form/form.component.js
  src/__experimental__/components/form/form.spec.js
  src/__experimental__/components/form/form.stories.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2536 FE-2417 resolved missing border for componenets with readOnly prop se…
  change_log/next/FE-2417-read-only-border-fix.yml
  src/__experimental__/components/input/input-presentation.spec.js
  src/__experimental__/components/input/input-presentation.style.js
Labels: Passed QA, Passed Review, Squad Front End

#2513 feat: Decimal Improvements
  change_log/next/FE-2305-decimal-precision-issue.yml
  change_log/next/decimal-improvements.yml
  fixtures/src/components/chrome.js
  fixtures/src/components/controlled/decimal.js
  fixtures/src/components/log.js
  fixtures/src/components/uncontrolled/decimal.js
  package-lock.json
  package.json
  src/__deprecated__/components/grouped-character/__spec__.js
  src/__deprecated__/components/grouped-character/grouped-character.js
  src/__experimental__/components/decimal/decimal.component.js
  src/__experimental__/components/decimal/decimal.spec.js
  src/__experimental__/components/decimal/decimal.stories.js
  src/__experimental__/components/decimal/docgenInfo.json
  src/utils/helpers/events/__spec__.js
  src/utils/helpers/events/events.js
  src/utils/helpers/i18n/__spec__.js
  src/utils/helpers/i18n/i18n.js
  src/utils/validations/numeral/numeral.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2539 docs: update decimal stories FE-2460
  src/components/inline-inputs/inline-inputs.stories.js
  src/components/validations/textbox-validations.stories.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2533 Fe 2444 fix allowEmptyValue prop in every story
  change_log/next/FE-2444-remove-allowEmptyValue-knob-from-every-story.yml
  src/__experimental__/components/date/date.stories.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2527 FE-2433 - Select add a prop to prevent auto open on focus
  change_log/next/FE-2433-add-prevent-auto-open-prop.yml
  src/__experimental__/components/select/select.component.js
  src/__experimental__/components/select/select.spec.js
  src/__experimental__/components/select/select.stories.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2540 docs: update decimal story to support allow empty value knob FE-2462
  src/__experimental__/components/decimal/decimal.stories.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2488 FE-2308 SimpleColorPicker onBlur event is fired on every click onto the same colorPicker
  src/__experimental__/components/radio-button/radio-button-mapper.component.js
  src/__experimental__/components/simple-color-picker/__snapshots__/simple-color-picker.spec.js.snap
  src/__experimental__/components/simple-color-picker/simple-color-picker.component.js
  src/__experimental__/components/simple-color-picker/simple-color-picker.spec.js
  src/__experimental__/components/simple-color-picker/simple-color-picker.stories.js
  src/__experimental__/components/simple-color-picker/simple-color/simple-color.component.js
Labels: Passed QA, Passed Review, Squad Front End

#2543 Merge back v11.0.0
  change_log/v11_0_0/FE-2281-remove-tabs-child-tooltip.yml
  change_log/v11_0_0/FE-2305-decimal-precision-issue.yml
  change_log/v11_0_0/FE-2306-fix-sticky-footer-flickering.yml
  change_log/v11_0_0/FE-2363-fix-dateInput-alignment.yml
  change_log/v11_0_0/FE-2417-read-only-border-fix.yml
  change_log/v11_0_0/FE-2422-select-option-mouse-hover-block.yml
  change_log/v11_0_0/FE-2433-add-prevent-auto-open-prop.yml
  change_log/v11_0_0/FE-2443-Input-Integration-story.yml
  change_log/v11_0_0/FE-2444-remove-allowEmptyValue-knob-from-every-story.yml
  change_log/v11_0_0/decimal-improvements.yml
  change_log/v11_0_0/upgrade-carbon-factory-to-v9-0-1.yml
  package-lock.json
  package.json
  release_notes/v11_0_0.html.md
Labels: Passed Review, Squad Front End

#2545 Fix v11 after broken deploy
  change_log/v11_0_1/revert-carbon-factory.yml
  package-lock.json
  package.json
  release_notes/v11_0_1.html.md
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2496 FE-2269 - react-transition-group update
  demo/main.js
  demo/views/pages/document/document.js
  demo/views/pages/document/document.scss
  package-lock.json
  package.json
  src/components/animated-menu-button/animated-menu-button.js
  src/components/animated-menu-button/animated-menu-button.scss
  src/components/carousel/carousel.component.js
  src/components/carousel/carousel.spec.js
  src/components/carousel/carousel.stories.js
  src/components/carousel/slide.config.js
  src/components/carousel/slide/slide.component.js
  src/components/dialog-full-screen/dialog-full-screen.component.js
  src/components/dialog/dialog.component.js
  src/components/flash/__snapshots__/flash-legacy.spec.js.snap
  src/components/flash/flash-legacy.component.js
  src/components/flash/flash-legacy.style.js
  src/components/modal/__snapshots__/modal.spec.js.snap
  src/components/modal/modal.component.js
  src/components/modal/modal.style.js
  src/components/pages/page/page.component.js
  src/components/pages/page/page.spec.js
  src/components/pages/pages.component.js
  src/components/pages/pages.config.js
  src/components/pages/pages.spec.js
  src/components/show-edit-pod/show-edit-pod.js
  src/components/show-edit-pod/show-edit-pod.scss
  src/components/sidebar/sidebar.scss
  src/components/table/table.component.js
  src/components/toast/toast-classic.style.js
  src/components/toast/toast.component.js
  src/components/toast/toast.spec.js
  src/components/toast/toast.style.js
Labels: Passed QA, Passed Review, Squad Front End

#2534 FE-2408 fixed console errors and story crashing during onChange event…
  change_log/next/FE-2408-inline-input-error.yml
  src/__experimental__/components/input-icon-toggle/input-icon-toggle.component.js
  src/components/inline-inputs/inline-inputs.stories.js
  src/components/validations/validation-icon.component.js
  src/components/validations/validations.stories.js
Labels: Passed QA, Passed Review, Squad Front End

#2541 FE-2454 - Added wiggle animation to Decimal component
  change_log/next/FE-2454-decimal-wiggle-animation.yml
  src/__experimental__/components/decimal/decimal.component.js
  src/__experimental__/components/decimal/decimal.spec.js
  src/__experimental__/components/decimal/decimal.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2524 FE-2221 DateInput F6 copy control
  change_log/next/FE-2221-DateInput-F6-copy-control.yml
  fixtures/src/components/controlled/date.js
  fixtures/src/components/uncontrolled/date.js
  src/__experimental__/components/date/date.component.js
  src/__experimental__/components/date/date.spec.js
  src/__experimental__/components/date/date.stories.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2523 FE-2218 Select control F6 copy action
  change_log/next/FE-2218-select-F6-copy.yml
  fixtures/src/components/controlled/select.js
  fixtures/src/components/uncontrolled/select.js
  src/__experimental__/components/select/select.component.js
  src/__experimental__/components/select/select.spec.js
  src/__experimental__/components/select/select.stories.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2550 Mb for v11.0.1
  change_log/v11_0_1/revert-carbon-factory.yml
  package-lock.json
  package.json
  release_notes/v11_0_1.html.md
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#2531 FE-2421 no placeholder when select is read only
  change_log/next/FE-2421-remove_placeholder_when_select_is_read_only.yml
  src/__experimental__/components/select/select.spec.js
  src/__experimental__/components/textbox/textbox.component.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2548 FE-2468 - Fixed invalid animation behaviour on Decimal
  change_log/next/FE-2468-decimal-wiggle-readOnly-animation.yml
  src/__experimental__/components/decimal/decimal.component.js
  src/__experimental__/components/decimal/decimal.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2553 chore: updates carbon-factory dependency
  change_log/next/updates-carbon-factory-to-v10.yml
  package-lock.json
  package.json
  src/components/flash/flash.component.js
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2538 fix: adds invariant for init value to be iso format
  change_log/next/FE-2461-add-invariant-about-initial-date-value.yml
  fixtures/src/components/chrome.js
  fixtures/src/components/controlled/date-range.js
  fixtures/src/components/uncontrolled/date-range.js
  fixtures/src/components/uncontrolled/date.js
  src/__experimental__/components/date/date.component.js
  src/__experimental__/components/date/date.spec.js
  src/components/table/table-cell/table-cell.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2546 FE-2463 Fixes incorrect position of a label in relation to a text input when inline
  src/__experimental__/components/checkable-input/checkable-input.style.js
  src/__experimental__/components/checkbox/__snapshots__/checkbox-group.spec.js.snap
  src/__experimental__/components/checkbox/__snapshots__/checkbox.spec.js.snap
  src/__experimental__/components/checkbox/checkbox.style.js
  src/__experimental__/components/date/date.component.js
  src/__experimental__/components/input-icon-toggle/input-icon-toggle.style.js
  src/__experimental__/components/input/input-presentation.spec.js
  src/__experimental__/components/input/input-presentation.style.js
  src/__experimental__/components/input/input-sizes.style.js
  src/__experimental__/components/input/input.stories.js
  src/__experimental__/components/label/icon-wrapper.style.js
  src/__experimental__/components/label/label.style.js
  src/__experimental__/components/radio-button/__snapshots__/radio-button-group.spec.js.snap
  src/__experimental__/components/radio-button/__snapshots__/radio-button-mapper.spec.js.snap
  src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap
  src/__experimental__/components/radio-button/radio-button.spec.js
  src/__experimental__/components/radio-button/radio-button.style.js
  src/__experimental__/components/switch/__snapshots__/switch.spec.js.snap
  src/__experimental__/components/switch/switch.spec.js
  src/__experimental__/components/switch/switch.style.js
  src/__experimental__/components/textarea/__snapshots__/textarea.spec.js.snap
  src/__experimental__/components/textarea/textarea-input.component.js
  src/__experimental__/components/textarea/textarea.component.js
  src/__experimental__/components/textarea/textarea.spec.js
  src/__experimental__/components/textarea/textarea.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2535 FE-2449 - Fixed table header alignment and missing sort icon
  change_log/next/FE-2449-fix-table-header-alignment-and-missing-icon.yml
  src/components/table/table-classic.style.js
  src/components/table/table-header/__snapshots__/table-header.spec.js.snap
  src/components/table/table-header/table-header.component.js
  src/components/table/table-header/table-header.spec.js
  src/components/table/table-header/table-header.style.js
  src/components/table/table-modern.style.js
  src/components/table/table-row/__snapshots__/table-row.spec.js.snap
  src/components/table/table-row/table-row-modern.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2559 FE-2477 Incorrect cursor on focused link component
  change_log/next/FE-2477-wrong-cursor-type-link-component.yml
  src/components/dismiss-button/__snapshots__/dismiss-button.spec.js.snap
  src/components/link/__snapshots__/link.spec.js.snap
  src/components/link/link.style.js
Labels: Passed QA, Passed Review, Squad Front End

#2551 FE-2430 invalid date prevent.
  change_log/next/FE-2430-prevent-invalid-date.yml
  src/__experimental__/components/date/date-picker.component.js
  src/__experimental__/components/date/date-picker.spec.js
  src/utils/helpers/date/__spec__.js
  src/utils/helpers/date/date.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2557 FE-2471 - Fixed incorrect onBlur behaviour on checkable input
  change_log/next/FE-2471-checkable-input-onBlur-fired-3-times.yml
  src/__experimental__/components/checkable-input/checkable-input.component.js
  src/__experimental__/components/checkbox/__snapshots__/checkbox-group.spec.js.snap
  src/__experimental__/components/checkbox/__snapshots__/checkbox.spec.js.snap
  src/__experimental__/components/checkbox/checkbox.component.js
  src/__experimental__/components/checkbox/checkbox.stories.js
  src/__experimental__/components/radio-button/__snapshots__/radio-button-group.spec.js.snap
  src/__experimental__/components/radio-button/__snapshots__/radio-button-mapper.spec.js.snap
  src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap
  src/__experimental__/components/radio-button/radio-button.component.js
  src/__experimental__/components/switch/__snapshots__/switch.spec.js.snap
  src/__experimental__/components/switch/switch.component.js
  src/__experimental__/components/switch/switch.stories.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2563 FE-2474 upgrade to carbon factory v11
  change_log/next/FE-2474-upgrade-to-carbon-factory-v11.yml
  package-lock.json
  package.json
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2537 FE-2448 fixed validation icon alignment.
  change_log/next/FE-2448-date-validation-icon-fix.yml
  src/__deprecated__/components/date/date.scss
  src/__experimental__/components/date-range/__snapshots__/date-range.spec.js.snap
  src/__experimental__/components/date/__snapshots__/date.spec.js.snap
  src/__experimental__/components/date/date-classic.style.js
  src/__experimental__/components/date/date.style.js
  src/utils/decorators/input-icon/input-icon.scss
  src/utils/decorators/input/input.scss
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2560 fixes 2556 ActionPopover having conditional children
  change_log/next/issue-2556.yml
  src/components/action-popover/action-popover.component.js
  src/components/action-popover/action-popover.spec.js
Labels: Bug, Passed QA, Passed Review

#2555 feat: Add toggle open close to date FE-2219
  change_log/next/FE-2219-DateInput_toggle_open_close.yml
  src/__experimental__/components/date/date.component.js
  src/__experimental__/components/date/date.spec.js
Labels: Passed QA, Passed Review, Squad Front End

#2571 Update lint script
  .travis.yml
  change_log/next/npm-lint-script.yml
  package.json
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#2544 FE-2404 Fixed MountInApp unsupported element.child.remove() method in IE
  change_log/next/FE-2404-mount-in-app-ie11-unsupported-remove.yml
  src/components/mount-in-app/mount-in-app.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2562 FE-2450 adds support for src prop in Profile
  change_log/next/FE-2450-Add_src_prop_to_Profile_component.yml
  src/components/profile/docgenInfo.json
  src/components/profile/profile.component.js
  src/components/profile/profile.config.js
  src/components/profile/profile.spec.js
  src/components/profile/profile.stories.js
  src/components/profile/profile.style.js
Labels: Passed QA, Passed Review, Squad Front End

#2558 FE-2451: fixes #2500 renders a button as Link when onClick passed
  change_log/next/FE-2451-link-accessibility-with-onclick-prop.yml
  src/components/button/button.style.js
  src/components/create/__snapshots__/create.spec.js.snap
  src/components/dialog-full-screen/icon.style.js
  src/components/dismiss-button/__snapshots__/dismiss-button.spec.js.snap
  src/components/heading/__spec__.js
  src/components/heading/heading.js
  src/components/heading/heading.scss
  src/components/heading/heading.style.js
  src/components/help/help.style.js
  src/components/link/__snapshots__/link.spec.js.snap
  src/components/link/link.component.js
  src/components/link/link.spec.js
  src/components/link/link.stories.js
  src/components/link/link.style.js
  src/components/pages/page/page.style.js
  src/components/pages/pages.style.js
  src/components/table/table.spec.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2577 chore: add bug template FE-2023
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#2578 chore: feature request template FE-2023
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#2580 chore: capitalisation FE-2023
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#2579 Add missing event parameter in onChange type definitions
  change_log/next/onchange-type-definitions.yml
  src/__experimental__/components/checkbox/checkbox.d.ts
  src/__experimental__/components/radio-button/radio-button.d.ts
  src/__experimental__/components/switch/switch.d.ts
Labels: Enhancement, No QA Required, No UX QA Required, Passed Review

#2237 added autoFocus option to experimental input components
  change_log/next/auto-focus-on-experimental-fields.yml
  src/__experimental__/components/checkbox/checkbox.stories.js
  src/__experimental__/components/date/date.stories.js
  src/__experimental__/components/decimal/decimal.stories.js
  src/__experimental__/components/grouped-character/grouped-character.stories.js
  src/__experimental__/components/input/input.component.js
  src/__experimental__/components/input/input.spec.js
  src/__experimental__/components/number/number.stories.js
  src/__experimental__/components/select/select.stories.js
  src/__experimental__/components/textarea/textarea.stories.js
  src/__experimental__/components/textbox/textbox.stories.js
  src/utils/helpers/auto-focus/__spec__.js
  src/utils/helpers/auto-focus/auto-focus.js
  src/utils/helpers/auto-focus/package.json
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2581 chore: pull request template FE-2023
  .github/PULL_REQUEST_TEMPLATE.md
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2561 fix(date-component): allow null value when renderd with allowEmptyValue
  change_log/next/date-allow-null.yml
  src/__experimental__/components/date/date.component.js
  src/__experimental__/components/date/date.spec.js
Labels: Bug, No UX QA Required, Passed QA, Passed Review
