Repository Sage/carbon, pull requests merged in 2019-02, with the labels that each got.

#1900 InputDecoratorBridge component
  change_log/next/input-decorator-bridge.yml
  src/__experimental__/components/input-decorator-bridge/__snapshots__/input-decorator-bridge.spec.js.snap
  src/__experimental__/components/input-decorator-bridge/index.js
  src/__experimental__/components/input-decorator-bridge/input-decorator-bridge.component.js
  src/__experimental__/components/input-decorator-bridge/input-decorator-bridge.spec.js
Labels: Passed Review

#1904 presence validator supports arrays
  change_log/next/presence-arrays.yml
  src/utils/validations/presence/__spec__.js
  src/utils/validations/presence/presence.js
Labels: Passed Review

#1898 Fe 1197 adapt scrollable list component to accept different types of children
  change_log/next/selectable_list_component.yml
  demo/views/pages/sandbox/index.js
  package-lock.json
  package.json
  src/components/scrollable-list/__spec__.js
  src/components/scrollable-list/as-scrollable-list-item.wrapper.js
  src/components/scrollable-list/index.js
  src/components/scrollable-list/scrollable-list-item.component.js
  src/components/scrollable-list/scrollable-list.component.js
  src/components/scrollable-list/scrollable-list.context.js
  src/components/scrollable-list/scrollable-list.style.js
  src/components/scrollable-list/test-utils.js
  src/utils/helpers/events/events.js
Labels: Passed Review, Pending UX Review

#1903 Filterable component
  change_log/next/filterable.yml
  src/components/filterable/__snapshots__/filterable-item.spec.js.snap
  src/components/filterable/__snapshots__/filterable.spec.js.snap
  src/components/filterable/__snapshots__/with-filterable-item.spec.js.snap
  src/components/filterable/filterable-item.component.js
  src/components/filterable/filterable-item.spec.js
  src/components/filterable/filterable.component.js
  src/components/filterable/filterable.context.js
  src/components/filterable/filterable.spec.js
  src/components/filterable/index.js
  src/components/filterable/with-filterable-item.hoc.js
  src/components/filterable/with-filterable-item.spec.js
Labels: Passed Review

#1894 FE-1187 add delete state to pill component
  change_log/next/FE-1187.yml
  src/components/pill/__definition__.js
  src/components/pill/__spec__.js
  src/components/pill/pill.js
  src/components/pill/pill.scss
Labels: Passed Review, Pending QA, Pending UX Review

#1909 fix for "npm start" failing on windows
  package.json
Labels: Pending Review

#1910 Fe 1187 add delete state to pill component
  src/components/pill/pill.scss
Labels: Passed QA

#1911 Fe-1219 set up style themes
  change_log/next/FE-1183.yml
  change_log/next/FE-1219.yml
  src/style/__spec__.js
  src/style/color-config/index.js
  src/style/index.js
  src/style/palette/index.js
  src/style/themes/base/base-theme.config.js
  src/style/themes/base/index.js
  src/style/themes/classic/classic-theme.config.js
  src/style/themes/classic/classic-theme.spec.js
  src/style/themes/classic/index.js
  src/style/themes/large/index.js
  src/style/themes/large/large-theme.config.js
  src/style/themes/large/large.spec.js
  src/style/themes/medium/index.js
  src/style/themes/medium/medium-theme.config.js
  src/style/themes/medium/medium.spec.js
  src/style/themes/small/index.js
  src/style/themes/small/small-theme.config.js
  src/style/themes/small/small.spec.js
  src/style/themes/test-utils.js
  src/style/utils/add-hex-symbols.js
  src/style/utils/at-opacity.js
  src/style/utils/merge-deep.js
  src/style/utils/merge-deep.spec.js
  src/style/utils/mix.js
  src/style/utils/shade.js
  src/style/utils/tint.js
Labels: Pending QA, Pending Review, Pending UX Review

#1914 FE-1243 fixes for Windows
  change_log/next/demo-color-generation.yml
  change_log/next/development-on-windows.yml
  package-lock.json
  package.json
  script/generate-demo-colors.js
Labels: Enhancement, No UX Review Required, Passed Review

#1907 Add height styling to carousel to fix no scroll issue
  change_log/next/reports_no_scroll_issue.yml
  src/components/carousel/carousel.js
  src/components/carousel/carousel.scss
Labels: Passed QA, Passed Review

#1916 Fe 1219 set up style themes
  src/style/themes/large/large.spec.js
  src/style/themes/medium/medium.spec.js
  src/style/themes/small/small.spec.js
  src/style/utils/merge-deep.js
  src/style/utils/merge-deep.spec.js
Labels: Passed Review

#1905 select and option components
  change_log/next/select-component.yml
  demo/views/pages/sandbox/index.js
  package-lock.json
  src/__experimental__/components/input-decorator-bridge/__snapshots__/input-decorator-bridge.spec.js.snap
  src/__experimental__/components/input-decorator-bridge/input-decorator-bridge.component.js
  src/__experimental__/components/input-decorator-bridge/input-decorator-bridge.spec.js
  src/__experimental__/components/input/__snapshots__/input-presentation.spec.js.snap
  src/__experimental__/components/input/__snapshots__/input.spec.js.snap
  src/__experimental__/components/input/input-presentation.component.js
  src/__experimental__/components/input/input-presentation.spec.js
  src/__experimental__/components/input/input-presentation.style.scss
  src/__experimental__/components/input/input.component.js
  src/__experimental__/components/input/input.spec.js
  src/__experimental__/components/input/input.style.scss
  src/__experimental__/components/select/__snapshots__/option.spec.js.snap
  src/__experimental__/components/select/__snapshots__/select-list.spec.js.snap
  src/__experimental__/components/select/__snapshots__/select.spec.js.snap
  src/__experimental__/components/select/index.js
  src/__experimental__/components/select/option.component.js
  src/__experimental__/components/select/option.spec.js
  src/__experimental__/components/select/option.test.js
  src/__experimental__/components/select/select-list.component.js
  src/__experimental__/components/select/select-list.spec.js
  src/__experimental__/components/select/select.component.js
  src/__experimental__/components/select/select.spec.js
  src/__experimental__/components/select/select.style.scss
  src/__experimental__/components/textbox/__snapshots__/textbox.spec.js.snap
  src/__experimental__/components/textbox/textbox.component.js
  src/__experimental__/components/textbox/textbox.spec.js
  src/components/filterable/__snapshots__/filterable-item.spec.js.snap
  src/components/filterable/__snapshots__/filterable.spec.js.snap
  src/components/filterable/__snapshots__/with-filterable-item.spec.js.snap
  src/components/filterable/filterable-item.component.js
  src/components/filterable/filterable-item.spec.js
  src/components/filterable/filterable.component.js
  src/components/filterable/filterable.context.js
  src/components/filterable/filterable.spec.js
  src/components/filterable/index.js
  src/components/filterable/with-filterable-item.hoc.js
  src/components/filterable/with-filterable-item.spec.js
  src/components/pill/pill.scss
  src/components/scrollable-list/__spec__.js
  src/components/scrollable-list/scrollable-list-item.component.js
  src/components/scrollable-list/scrollable-list.component.js
  src/components/scrollable-list/scrollable-list.style.js
  src/components/scrollable-list/test-utils.js
  src/utils/decorators/input-label/input-label.scss
  src/utils/filter-children/__snapshots__/filter-children.spec.js.snap
  src/utils/filter-children/filter-children.spec.js
  src/utils/filter-children/filter-children.util.js
  src/utils/filter-children/index.js
Labels: Passed QA, Passed Review

#1908 Fe 1182 setup carbon for typescript
  babel.config.js
  change_log/next/FE-1182-setup-carbon-for-typescript.yml
  package-lock.json
  package.json
  src/components/button/__spec__.js
  src/components/button/button.d.ts
  src/components/button/index.d.ts
  src/components/button/index.js
  src/components/button/package.json
  src/components/link/index.d.ts
  src/components/link/index.js
  src/components/link/link.d.ts
  src/components/link/package.json
  tsconfig.json
  tslint.json
Labels: Enhancement, Pending Review

#1923 TS declaration for Flash component
  change_log/next/flash-typescript-declaration.yml
  src/components/flash/flash.d.ts
  src/components/link/link.d.ts
  src/utils/helpers/options-helper/option-helper.d.ts
Labels: Passed Review

#1912 FE-1244 - Setup 5 Components in Storybook
  .storybook/__helpers__/components/app-layout/app-layout.js
  .storybook/addons.js
  .storybook/config.js
  .storybook/webpack.config.js
  change_log/next/FE-1244-storybook.yml
  package-lock.json
  package.json
  src/components/alert/alert.stories.js
  src/components/alert/notes.md
  src/components/animated-menu-button/animated-menu-button.stories.js
  src/components/animated-menu-button/notes.md
  src/components/app-wrapper/app-wrapper.stories.js
  src/components/app-wrapper/notes.md
  src/components/button-toggle-group/button-toggle-group.stories.js
  src/components/button-toggle-group/notes.md
  src/components/button-toggle/button-toggle.stories.js
  src/components/button-toggle/notes.md
  src/components/button/button.js
  src/components/button/button.stories.js
  src/components/button/notes.md
Labels: Enhancement, Passed Review

#1927 fixed production assets for demo site
  package.json
Labels: Pending Review

#1913 FE-1241 new validator function
  change_log/next/FE-1241-new-validator-function.yml
  src/utils/validations/validator/index.js
  src/utils/validations/validator/validator.js
  src/utils/validations/validator/validator.spec.js
Labels: Enhancement, No UX Review Required, Passed QA, Passed Review

#1926 Type declarations for texbox, numeric and decimal components
  change_log/next/basic-input-type-declarations.yml
  src/components/button/button.d.ts
  src/components/decimal/decimal.d.ts
  src/components/flash/flash.d.ts
  src/components/input-definition.d.ts
  src/components/link/link.d.ts
  src/components/number/number.d.ts
  src/components/textbox/textbox.d.ts
  src/utils/helpers/options-helper/option-helper.d.ts
  src/utils/validations/validator.d.ts
Labels: Passed Review

#1938 Extend Table component for custom empty row
  change_log/next/S1T-1617.yml
  demo/utils/definition/table-definition/table-definition.js
  src/components/table/__spec__.js
  src/components/table/table.js
Labels: Enhancement, Passed QA, Passed Review

#1937 i18n peer dep
  change_log/next/FE-1279-i18n-peer-dep.yml
  package-lock.json
  package.json
Labels: No QA Required, No UX Review Required, Pending Review
