Repository Sage/carbon, pull requests merged in 2019-07, with the labels that each got.

#2145 FE-1646 core-js v3 support
  .storybook/addons.js
  .storybook/webpack.config.js
  babel.config.js
  change_log/v8_0_0/FE-1646-update-dependencies.yml
  package-lock.json
  package.json
  release_notes/v8_0_0.html.md
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2161 refactor of the bdd specs (cypress/FE-1738)
  cypress/features/regression/alert.feature
  cypress/features/regression/buttonToggle.feature
  cypress/features/regression/carousel.feature
  cypress/features/regression/confirm.feature
  cypress/features/regression/content.feature
  cypress/features/regression/dialog.feature
  cypress/features/regression/flash.feature
  cypress/features/regression/heading.feature
  cypress/features/regression/i18nComponent.feature
  cypress/features/regression/inlineInputs.feature
  cypress/features/regression/link.feature
  cypress/locators/flash/locators.js
  cypress/locators/inline-inputs/index.js
  cypress/locators/inline-inputs/locators.js
  cypress/locators/mount-in-app/locators.js
  cypress/support/helper.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/flash-steps.js
  cypress/support/step-definitions/inline-inputs-steps.js
Labels: Cypress, Squad Front End

#2169 Cypress/fe 1738 refactor second phase
  cypress/features/regression/pager.feature
  cypress/features/regression/radioButton.feature
  cypress/features/regression/showEditPod.feature
  cypress/features/regression/table.feature
  cypress/locators/pager/index.js
  cypress/locators/pager/locators.js
  cypress/locators/radio-button/index.js
  cypress/locators/radio-button/locators.js
  cypress/locators/table/index.js
  cypress/locators/table/locators.js
  cypress/support/step-definitions/confirm-steps.js
  cypress/support/step-definitions/pager-steps.js
  cypress/support/step-definitions/radio-button-steps.js
  cypress/support/step-definitions/show-edit-pod-steps.js
  cypress/support/step-definitions/step-sequence-steps.js
  cypress/support/step-definitions/table-steps.js
Labels: Cypress, Squad Front End

#2168 Mergeback v8.0.0
  .storybook/addons.js
  change_log/v8_0_0/FE-1646-update-dependencies.yml
  package-lock.json
  package.json
  release_notes/v8_0_0.html.md
  src/components/button/button.stories.js
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#2108 FE-1418 Pill DLS
  change_log/next/FE-1418-pill.yml
  src/__experimental__/components/select/__snapshots__/select.spec.js.snap
  src/components/pill/__spec__.js
  src/components/pill/documentation/index.js
  src/components/pill/documentation/info.js
  src/components/pill/documentation/notes.md
  src/components/pill/index.js
  src/components/pill/package.json
  src/components/pill/pill-classic.style.js
  src/components/pill/pill.component.js
  src/components/pill/pill.js
  src/components/pill/pill.spec.js
  src/components/pill/pill.stories.js
  src/components/pill/pill.style.config.js
  src/components/pill/pill.style.js
  src/style/themes/base/base-theme.config.js
  src/utils/helpers/options-helper/__spec__.js
  src/utils/helpers/options-helper/options-helper.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2174 Cypress/fe 1738 refactor for next components
  cypress/features/accessibility/accessibility.feature
  cypress/features/regression/decimal.feature
  cypress/features/regression/decimalPrecision.feature
  cypress/features/regression/help.feature
  cypress/features/regression/radioButton.feature
  cypress/features/regression/textarea.feature
  cypress/locators/configurable-items/index.js
  cypress/locators/configurable-items/locators.js
  cypress/locators/index.js
  cypress/locators/locators.js
  cypress/locators/radio-button/index.js
  cypress/locators/radio-button/locators.js
  cypress/support/helper.js
  cypress/support/step-definitions/radio-button-steps.js
  cypress/support/step-definitions/text-area-steps.js
Labels: Cypress, Squad Front End

#2135 Various CSS changes based on UX review
  change_log/next/S1T-1930.yml
  change_log/next/S1T-1941.yml
  src/components/dropdown-filter/dropdown-filter.scss
  src/utils/decorators/input/input.scss
Labels: Passed QA, Passed Review, Passed UX QA, Pending QA

#2045 DLS Switch
  change_log/next/FE-1323-switch-dls-component.yml
  src/__experimental__/components/checkable-input/__snapshots__/hidden-checkable-input.spec.js.snap
  src/__experimental__/components/checkable-input/checkable-input.component.js
  src/__experimental__/components/checkable-input/checkable-input.spec.js
  src/__experimental__/components/checkable-input/checkable-input.style.js
  src/__experimental__/components/checkable-input/hidden-checkable-input.style.js
  src/__experimental__/components/checkbox/__snapshots__/checkbox.spec.js.snap
  src/__experimental__/components/checkbox/checkbox.component.js
  src/__experimental__/components/checkbox/checkbox.spec.js
  src/__experimental__/components/checkbox/checkbox.style.js
  src/__experimental__/components/switch/__snapshots__/switch-slider-panel.spec.js.snap
  src/__experimental__/components/switch/__snapshots__/switch-slider.spec.js.snap
  src/__experimental__/components/switch/__snapshots__/switch.spec.js.snap
  src/__experimental__/components/switch/documentation/index.js
  src/__experimental__/components/switch/documentation/info.js
  src/__experimental__/components/switch/documentation/legacy-info.js
  src/__experimental__/components/switch/documentation/notes.md
  src/__experimental__/components/switch/index.js
  src/__experimental__/components/switch/switch-classic-loader-square.style.js
  src/__experimental__/components/switch/switch-classic.style.js
  src/__experimental__/components/switch/switch-slider-classic.style.js
  src/__experimental__/components/switch/switch-slider-panel-classic.style.js
  src/__experimental__/components/switch/switch-slider-panel.spec.js
  src/__experimental__/components/switch/switch-slider-panel.style.js
  src/__experimental__/components/switch/switch-slider.component.js
  src/__experimental__/components/switch/switch-slider.spec.js
  src/__experimental__/components/switch/switch-slider.style.js
  src/__experimental__/components/switch/switch.component.js
  src/__experimental__/components/switch/switch.spec.js
  src/__experimental__/components/switch/switch.stories.js
  src/__experimental__/components/switch/switch.style.js
  src/style/themes/base/base-theme.config.js
  src/style/themes/large/large-theme.config.js
  src/style/themes/medium/medium-theme.config.js
  src/style/themes/small/small-theme.config.js
Labels: Passed QA, Passed UX QA, Pending Review, Squad Front End

#2178 FE-1795 right border
  src/__experimental__/components/select/__snapshots__/select.spec.js.snap
  src/__experimental__/components/select/select.component.js
  src/style/themes/base/base-theme.config.js
Labels: No UX QA Required, Passed Review, Squad Front End

#2179 Fix delete for single select
  src/__experimental__/components/select/select.component.js
  src/__experimental__/components/select/select.spec.js
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2132 FE-1412 Portrait component
  change_log/next/FE-1412-portrait.yml
  cypress/features/accessibility/accessibility.feature
  cypress/features/build/build.feature
  cypress/features/regression/portrait.feature
  src/components/portrait/__spec__.js
  src/components/portrait/index.js
  src/components/portrait/package.json
  src/components/portrait/portrait-gravatar.component.js
  src/components/portrait/portrait-gravatar.spec.js
  src/components/portrait/portrait-initials.component.js
  src/components/portrait/portrait-initials.spec.js
  src/components/portrait/portrait-size.config.js
  src/components/portrait/portrait.component.js
  src/components/portrait/portrait.js
  src/components/portrait/portrait.scss
  src/components/portrait/portrait.spec.js
  src/components/portrait/portrait.stories.js
  src/components/portrait/portrait.style.js
  src/components/profile/__spec__.js
  src/components/profile/profile.js
  src/components/profile/profile.stories.js
  src/style/themes/base/base-theme.config.js
  src/utils/helpers/options-helper/options-helper.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2173 Docker setup for running cypress test suite
  .dockerignore
  Dockerfile-cypress
  docker-compose-cypress.yml
  package-lock.json
  package.json
  script/docker/README.md
  script/docker/cypress.sh
  script/docker/setup.sh
  script/docker/start.sh
Labels: Passed QA, Passed Review, Squad Front End

#2184 FE-1801 changed story naming to follow conventions
  src/__experimental__/components/select/select.stories.js
Labels: No UX QA Required, Passed Review, Pending QA, Squad Front End

#2185 FE-1810 select warning bug
  src/__experimental__/components/select/select.component.js
Labels: No UX QA Required, Pending QA, Pending Review, Squad Front End

#2183 Update release candidate with changes from master
  .dockerignore
  Dockerfile-cypress
  change_log/next/FE-1412-portrait.yml
  change_log/next/FE-1742-demo-site-bugs.yml
  cypress/features/accessibility/accessibility.feature
  cypress/features/build/build.feature
  cypress/features/regression/portrait.feature
  demo/components/get-code-buttons/get-code-buttons.js
  demo/components/selling-point-panel/selling-point-panel.scss
  demo/views/chrome/chrome.js
  demo/views/chrome/header/header.js
  demo/views/chrome/header/header.scss
  demo/views/chrome/menu/menu.scss
  demo/views/common/page-header-small/page-header-small.scss
  demo/views/pages/home/alert-banner/alert-banner.scss
  demo/views/pages/home/sage-loves-carbon/sage-loves-carbon.scss
  docker-compose-cypress.yml
  package-lock.json
  package.json
  script/docker/README.md
  script/docker/cypress.sh
  script/docker/setup.sh
  script/docker/start.sh
  src/components/portrait/__spec__.js
  src/components/portrait/index.js
  src/components/portrait/package.json
  src/components/portrait/portrait-gravatar.component.js
  src/components/portrait/portrait-gravatar.spec.js
  src/components/portrait/portrait-initials.component.js
  src/components/portrait/portrait-initials.spec.js
  src/components/portrait/portrait-size.config.js
  src/components/portrait/portrait.component.js
  src/components/portrait/portrait.js
  src/components/portrait/portrait.scss
  src/components/portrait/portrait.spec.js
  src/components/portrait/portrait.stories.js
  src/components/portrait/portrait.style.js
  src/components/profile/__spec__.js
  src/components/profile/profile.js
  src/components/profile/profile.stories.js
  src/style/themes/base/base-theme.config.js
  src/utils/helpers/options-helper/options-helper.js
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#2187 Generate Storybook Site
  .gitignore
  package.json
Labels: Passed Review, Squad Front End

#2180 FE-1729 validation stories for simple textbox components
  src/__experimental__/components/date/date.component.js
  src/__experimental__/components/input/__snapshots__/input.spec.js.snap
  src/__experimental__/components/input/input.component.js
  src/__experimental__/components/number/number.component.js
  src/__experimental__/components/number/number.spec.js
  src/__experimental__/components/select/__snapshots__/select.spec.js.snap
  src/__experimental__/components/textbox/textbox.component.js
  src/components/pager/__snapshots__/pager.spec.js.snap
  src/components/validations/__snapshots__/validation-icon.spec.js.snap
  src/components/validations/textbox-validations.stories.js
  src/components/validations/validation-icon.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2189 Bumps version, updates carbon-factory, generates release notes
  change_log/v8_1_0/update-to-carbon-factory-v801.yml
  package-lock.json
  package.json
  release_notes/v8_1_0.html.md
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2190 Merge back for v8.1.0
  change_log/v8_1_0/update-to-carbon-factory-v801.yml
  package-lock.json
  package.json
  release_notes/v8_1_0.html.md
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#2191 Merge back v810 into master
  change_log/v8_1_0/update-to-carbon-factory-v801.yml
  package-lock.json
  package.json
  release_notes/v8_1_0.html.md
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#2192 FE-1813 Select component - undefined values bug
  src/__experimental__/components/select/select.stories.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2195 FE-1807 apply error color to label
  src/__experimental__/components/form-field/form-field.component.js
  src/__experimental__/components/label/label.spec.js
  src/__experimental__/components/label/label.style.js
Labels: Passed Review, Squad Front End

#2193 [BUG] FE-1805 - Experimental Form - IE11 - Labels are not inline
  src/__experimental__/components/form-field/__snapshots__/form-field.spec.js.snap
  src/__experimental__/components/form-field/form-field.style.js
Labels: No UX QA Required, Passed Review, Squad Front End

#2196 FE-1806 implements axios post instead of fetch
  src/__experimental__/components/form/form.component.js
  src/__experimental__/components/form/form.spec.js
  src/__experimental__/components/form/form.stories.js
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2197 Cypress/update 3.4.0
  Dockerfile-cypress
  package-lock.json
  package.json
Labels: Passed Review, Squad Front End

#2198 adjust accessibility tests to docker
  cypress/features/accessibility/accessibility.feature
  cypress/locators/accessibility/index.js
  cypress/locators/accessibility/locators.js
  cypress/locators/index.js
  cypress/locators/locators.js
  cypress/support/helper.js
  cypress/support/step-definitions/accessibility-steps.js
  cypress/support/step-definitions/message-steps.js
Labels: Cypress, Squad Front End

#2199 fixes warnings for labeAlign
  src/__experimental__/components/select/select.stories.js
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2202 FE-1824 select - escape HTML
  src/__experimental__/components/select/select.stories.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2175 FE-1747 Experimental form
  src/__experimental__/components/form-field/__snapshots__/form-field.spec.js.snap
  src/__experimental__/components/form-field/form-field.component.js
  src/__experimental__/components/form-field/form-field.style.js
  src/__experimental__/components/form/__definition__.js
  src/__experimental__/components/form/documentation/Info.js
  src/__experimental__/components/form/documentation/notes.md
  src/__experimental__/components/form/form.component.js
  src/__experimental__/components/form/form.scss
  src/__experimental__/components/form/form.spec.js
  src/__experimental__/components/form/form.stories.js
  src/__experimental__/components/form/index.js
  src/__experimental__/components/label/label.spec.js
  src/__experimental__/components/label/label.style.js
  src/components/form/form-summary/__spec__.js
  src/components/form/save-button/__spec__.js
  src/components/validations/form-with-validations.hoc.js
  src/components/validations/with-validation.hoc.js
  src/components/validations/with-validation.spec.js
Labels: Passed QA, Passed Review, Squad Front End

#2163 FE-1420 remove InputDecoratorBridge from Select
  change_log/next/FE-1420-remove-decorator-bridge-from-select.yml
  src/__experimental__/components/input-icon-toggle/input-icon-toggle.style.js
  src/__experimental__/components/select-async/__snapshots__/select-async.spec.js.snap
  src/__experimental__/components/select/__snapshots__/select-list.spec.js.snap
  src/__experimental__/components/select/__snapshots__/select.spec.js.snap
  src/__experimental__/components/select/select-list.component.js
  src/__experimental__/components/select/select-list.spec.js
  src/__experimental__/components/select/select.component.js
  src/__experimental__/components/select/select.spec.js
  src/__experimental__/components/select/select.stories.js
  src/__experimental__/components/select/select.style.js
  src/__experimental__/components/select/select.style.scss
  src/__experimental__/components/textbox/textbox.component.js
  src/components/pill/pill.component.js
  src/components/scrollable-list/scrollable-list-item.component.js
  src/style/themes/base/base-theme.config.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2210 Cypress Docker Changes
  docker-compose-cypress.yml
Labels: No QA Required, No UX QA Required, Pending Review

#2211 Cypress/improve for docker
  cypress.json
  cypress/features/regression/buttonToggleChangeIconPart1.feature
  cypress/features/regression/buttonToggleChangeIconPart2.feature
  cypress/features/regression/detail.feature
  cypress/features/regression/detailIconTypePart1.feature
  cypress/features/regression/detailIconTypePart2.feature
  cypress/features/regression/iconTypePart1.feature
  cypress/features/regression/iconTypePart2.feature
  cypress/features/regression/linkIconTypePart1.feature
  cypress/features/regression/linkIconTypePart2.feature
  cypress/features/regression/simpleColorPicker.feature
  package.json
Labels: Cypress, Squad Front End

#2209 FE-1673 Portrait bug (transparent image backgrounds)
  change_log/next/FE-1673-portrait-bug.yml
  src/components/portrait/portrait-gravatar.component.js
  src/components/portrait/portrait-gravatar.spec.js
  src/components/portrait/portrait-initials.component.js
  src/components/portrait/portrait.component.js
  src/components/portrait/portrait.spec.js
  src/components/portrait/portrait.style.js
  src/components/profile/__snapshots__/profile.spec.js.snap
Labels: Passed QA, Passed Review, Squad Front End

#2188 Add a prop to enable/disable the setting of the selected tabId in the…
  change_log/next/tabs_new_prop.yml
  src/components/tabs/__definition__.js
  src/components/tabs/__spec__.js
  src/components/tabs/tabs.js
Labels: Passed QA, Passed Review

#2218 added .vscode/ directory to .gitignore file
  .gitignore
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#2216 FE-1835 RadioButton SVG bug on IE/Edge/Firefox
  src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap
  src/__experimental__/components/radio-button/radio-button-svg.component.js
Labels: Passed QA, Passed Review, Squad Front End

#2208 FE-1103 resolved propType error for Alert/Checkbox.
  change_log/next/EF-1103.yaml
  src/__experimental__/components/checkable-input/checkable-input.style.js
  src/components/checkbox/__spec__.js
  src/components/checkbox/checkbox.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2221 Cypress/fe 1774 adding validation story for select component
  cypress.env.json
  cypress/features/regression/selectMultiple.feature
  cypress/features/regression/selectValidations.feature
  cypress/support/step-definitions/common-steps.js
Labels: Cypress, Squad Front End

#2222 fix sizes for Docker in bdd specs
  cypress/features/regression/button.feature
  cypress/features/regression/buttonToggle.feature
  cypress/features/regression/buttonToggleGroup.feature
Labels: Cypress, Squad Front End

#2223 Cypress/fe 1718 updating the readme.md file for cypress
  cypress/README.md
Labels: Cypress, Squad Front End

#2228 fixes step for loader, renamed feature file
  cypress/features/regression/loader.feature
  cypress/support/step-definitions/loader-steps.js
Labels: Cypress, Squad Front End

#2230 update cypress cucumber and disable screenshots and reporting
  cypress/support/index.js
  package-lock.json
  package.json
Labels: Cypress, Squad Front End

#2229 FE-1830 / FE-1833 RadioButton Help accessibility and tabbing
  src/__experimental__/components/checkable-input/__snapshots__/hidden-checkable-input.spec.js.snap
  src/__experimental__/components/checkable-input/checkable-input.component.js
  src/__experimental__/components/checkable-input/checkable-input.spec.js
  src/__experimental__/components/checkable-input/hidden-checkable-input.component.js
  src/__experimental__/components/checkable-input/hidden-checkable-input.spec.js
  src/__experimental__/components/checkbox/__snapshots__/checkbox.spec.js.snap
  src/__experimental__/components/checkbox/checkbox.component.js
  src/__experimental__/components/checkbox/checkbox.spec.js
  src/__experimental__/components/checkbox/checkbox.stories.js
  src/__experimental__/components/form-field/form-field.component.js
  src/__experimental__/components/label/label.component.js
  src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap
  src/__experimental__/components/radio-button/radio-button-group.component.js
  src/__experimental__/components/radio-button/radio-button-group.spec.js
  src/__experimental__/components/radio-button/radio-button.component.js
  src/__experimental__/components/switch/__snapshots__/switch.spec.js.snap
  src/__experimental__/components/switch/switch.component.js
  src/__experimental__/components/switch/switch.spec.js
  src/__experimental__/components/switch/switch.stories.js
  src/components/help/help.component.js
Labels: Passed Review, Squad Front End
