Repository Sage/carbon, pull requests merged in 2019-04, with the labels that each got.

#1990 removed flux
  README.md
  __mocks__/carbon-react/lib/utils/logger/index.js
  change_log/v7_0_0/extend-tooltip-decorator.yml
  change_log/v7_0_0/remove-flux.yml
  demo/dispatcher/dispatcher.js
  demo/site-map.js
  demo/stores/browser/browser.js
  demo/stores/component/component.js
  demo/stores/demo/demo.js
  demo/stores/document/document.js
  demo/views/chrome/chrome.js
  demo/views/chrome/sub-page-chrome/sub-page-chrome.js
  demo/views/layout/inline-inputs-demo/inline-inputs-demo.js
  demo/views/pages/component/component.js
  demo/views/pages/document/document.js
  docs/guides/flux.md
  package-lock.json
  package.json
  release_notes/v7_0_0.html.md
  src/patterns/configurable-items/actions/__spec__.js
  src/patterns/configurable-items/actions/actions.js
  src/patterns/configurable-items/configurable-items.js
  src/patterns/configurable-items/store/store.js
  src/utils/flux/__spec__.js
  src/utils/flux/connect/__spec__.js
  src/utils/flux/connect/connect.js
  src/utils/flux/connect/package.json
  src/utils/flux/flux.js
  src/utils/flux/package.json
  src/utils/flux/store/__spec__.js
  src/utils/flux/store/package.json
  src/utils/flux/store/store.js
  webpack.config.js
Labels: Passed Review

#1987 Extend the tooltip decorator
  README.md
  __mocks__/carbon-react/lib/utils/logger/index.js
  change_log/v7_0_0/extend-tooltip-decorator.yml
  change_log/v7_0_0/remove-flux.yml
  demo/dispatcher/dispatcher.js
  demo/site-map.js
  demo/stores/browser/browser.js
  demo/stores/component/component.js
  demo/stores/demo/demo.js
  demo/stores/document/document.js
  demo/views/chrome/chrome.js
  demo/views/chrome/sub-page-chrome/sub-page-chrome.js
  demo/views/layout/inline-inputs-demo/inline-inputs-demo.js
  demo/views/pages/component/component.js
  demo/views/pages/document/document.js
  docs/guides/flux.md
  package-lock.json
  package.json
  release_notes/v7_0_0.html.md
  src/components/tooltip/__spec__.js
  src/components/tooltip/tooltip.js
  src/patterns/configurable-items/actions/__spec__.js
  src/patterns/configurable-items/actions/actions.js
  src/patterns/configurable-items/configurable-items.js
  src/patterns/configurable-items/store/store.js
  src/utils/decorators/tooltip-decorator/__spec__.js
  src/utils/decorators/tooltip-decorator/tooltip-decorator.js
  src/utils/flux/__spec__.js
  src/utils/flux/connect/__spec__.js
  src/utils/flux/connect/connect.js
  src/utils/flux/connect/package.json
  src/utils/flux/flux.js
  src/utils/flux/package.json
  src/utils/flux/store/__spec__.js
  src/utils/flux/store/package.json
  src/utils/flux/store/store.js
  webpack.config.js
Labels: Enhancement, Passed QA, Passed Review

#1991 merge back v7.0.0 into master
  README.md
  __mocks__/carbon-react/lib/utils/logger/index.js
  change_log/v7_0_0/extend-tooltip-decorator.yml
  change_log/v7_0_0/remove-flux.yml
  demo/dispatcher/dispatcher.js
  demo/site-map.js
  demo/stores/browser/browser.js
  demo/stores/component/component.js
  demo/stores/demo/demo.js
  demo/stores/document/document.js
  demo/views/chrome/chrome.js
  demo/views/chrome/sub-page-chrome/sub-page-chrome.js
  demo/views/layout/inline-inputs-demo/inline-inputs-demo.js
  demo/views/pages/component/component.js
  demo/views/pages/document/document.js
  docs/guides/flux.md
  package-lock.json
  package.json
  release_notes/v7_0_0.html.md
  src/components/tooltip/__spec__.js
  src/components/tooltip/tooltip.js
  src/patterns/configurable-items/actions/__spec__.js
  src/patterns/configurable-items/actions/actions.js
  src/patterns/configurable-items/configurable-items.js
  src/patterns/configurable-items/store/store.js
  src/utils/decorators/tooltip-decorator/__spec__.js
  src/utils/decorators/tooltip-decorator/tooltip-decorator.js
  src/utils/flux/__spec__.js
  src/utils/flux/connect/__spec__.js
  src/utils/flux/connect/connect.js
  src/utils/flux/connect/package.json
  src/utils/flux/flux.js
  src/utils/flux/package.json
  src/utils/flux/store/__spec__.js
  src/utils/flux/store/package.json
  src/utils/flux/store/store.js
  webpack.config.js
Labels: Passed Review

#1993 revert formatter
  change_log/v7_0_1/revert-date-formatter.yml
  package-lock.json
  package.json
  release_notes/v7_0_1.html.md
  src/utils/helpers/date/date.js
Labels: Pending Review

#1976 Fe 1277 testing continued
  change_log/next/FE-1277-continued.yml
  src/components/dialog/dialog.stories.js
  src/components/dropdown-filter-ajax/dropdown-filter-ajax.stories.js
  src/components/dropdown-filter/dropdown-filter.js
  src/components/dropdown-filter/dropdown-filter.stories.js
  src/components/dropdown/dropdown.stories.js
  src/components/flash/flash.stories.js
Labels: Passed QA, Passed Review

#1985 FE-1223 - Calendar popover
  change_log/next/FE-1223-calendar-popover.yml
  src/components/date/__snapshots__/date.spec.js.snap
  src/components/date/date.component.js
  src/components/date/date.scss
  src/components/date/date.spec.js
  src/components/date/date.stories.js
  src/components/date/day-picker-classic.style.js
  src/components/date/day-picker.style.js
  src/components/date/index.js
  src/components/date/navbar/__snapshots__/navbar.spec.js.snap
  src/components/date/navbar/button.style.js
  src/components/date/navbar/index.js
  src/components/date/navbar/navbar.component.js
  src/components/date/navbar/navbar.js
  src/components/date/navbar/navbar.scss
  src/components/date/navbar/navbar.spec.js
  src/components/date/navbar/navbar.style.js
  src/components/date/navbar/package.json
  src/components/date/package.json
  src/components/date/weekday/__snapshots__/weekday.spec.js.snap
  src/components/date/weekday/abbr.style.js
  src/components/date/weekday/index.js
  src/components/date/weekday/weekday-classic.style.js
  src/components/date/weekday/weekday.component.js
  src/components/date/weekday/weekday.spec.js
  src/components/date/weekday/weekday.style.js
  src/style/themes/base/base-theme.config.js
  src/style/themes/classic/classic-theme.config.js
Labels: Enhancement, Passed QA, Passed Review

#1997 FE 1425 - Provides Classic Theme by ThemeProvider to the Demo site.
  demo/views/pages/component/component-preview/component-preview.js
Labels: Passed QA, Passed Review

#2004 updated validation hocs
  src/components/validations/__snapshots__/form-with-validations.spec.js.snap
  src/components/validations/__snapshots__/validation-icon.spec.js.snap
  src/components/validations/__snapshots__/with-validation.spec.js.snap
  src/components/validations/form-with-validations.hoc.js
  src/components/validations/form-with-validations.spec.js
  src/components/validations/validation-icon.component.js
  src/components/validations/validation-icon.spec.js
  src/components/validations/validation-icon.style.js
  src/components/validations/validation-types.config.js
  src/components/validations/with-validation.hoc.js
  src/components/validations/with-validation.spec.js
  src/utils/validations/validator/validator.js
  src/utils/validations/validator/validator.spec.js
Labels: No QA Required, Passed Review

#2003 updated tooltip to support types and offscreen
  change_log/next/tooltip-update.yml
  src/components/tooltip/tooltip.js
  src/components/tooltip/tooltip.scss
  src/utils/decorators/tooltip-decorator/__spec__.js
  src/utils/decorators/tooltip-decorator/tooltip-decorator.js
Labels: No QA Required, Passed Review

#1992 Fe 1319
  change_log/next/message_component.yml
  src/components/date/__snapshots__/date.spec.js.snap
  src/components/link/__snapshots__/link.spec.js.snap
  src/components/message/__snapshots__/message.spec.js.snap
  src/components/message/__spec__.js
  src/components/message/close-icon/__snapshots__/close-icon.spec.js.snap
  src/components/message/close-icon/close-icon-classic.style.js
  src/components/message/close-icon/close-icon.component.js
  src/components/message/close-icon/close-icon.spec.js
  src/components/message/close-icon/close-icon.style.js
  src/components/message/documentation/notes.md
  src/components/message/index.js
  src/components/message/message-classic-theme-colors.js
  src/components/message/message-classic.style.js
  src/components/message/message-content/__snapshots__/message-content.spec.js.snap
  src/components/message/message-content/message-content-classic.style.js
  src/components/message/message-content/message-content.component.js
  src/components/message/message-content/message-content.spec.js
  src/components/message/message-content/message-content.style.js
  src/components/message/message.component.js
  src/components/message/message.js
  src/components/message/message.scss
  src/components/message/message.spec.js
  src/components/message/message.stories.js
  src/components/message/message.style.js
  src/components/message/package.json
  src/components/message/type-icon/__snapshots__/type-icon.spec.js.snap
  src/components/message/type-icon/type-icon-classic.style.js
  src/components/message/type-icon/type-icon.component.js
  src/components/message/type-icon/type-icon.spec.js
  src/components/message/type-icon/type-icon.style.js
  src/components/show-edit-pod/__snapshots__/__spec__.js.snap
  src/style/color-config/index.js
  src/style/themes/base/base-theme.config.js
  src/style/themes/classic/classic-theme.config.js
  src/utils/helpers/options-helper/options-helper.js
Labels: Passed QA, Passed Review, Passed UX Review

#1970 Fe 1280 decimal component
  change_log/next/FE-1280-decimal-component.yml
  package.json
  src/__experimental__/components/decimal/decimal.component.js
  src/__experimental__/components/decimal/decimal.spec.js
  src/__experimental__/components/decimal/decimal.stories.js
  src/__experimental__/components/decimal/documentation/index.js
  src/__experimental__/components/decimal/documentation/notes.md
  src/__experimental__/components/decimal/index.js
  src/__experimental__/components/field-help/field-help.spec.js
  src/__experimental__/components/field-help/field-help.style.js
  src/__experimental__/components/input/__snapshots__/input-presentation.spec.js.snap
  src/__experimental__/components/input/input-presentation.spec.js
  src/__experimental__/components/input/input-presentation.style.js
  src/__experimental__/components/input/input.spec.js
  src/__experimental__/components/input/input.style.js
  src/__experimental__/components/label/label.spec.js
  src/__experimental__/components/label/label.style.js
  src/__experimental__/components/select/__snapshots__/select.spec.js.snap
  src/__experimental__/components/textbox/textbox.stories.js
Labels: Passed QA, Passed Review

#2001 Fe 1283 fieldset component
  change_log/next/FE-1283-fieldset.yml
  src/__experimental__/components/fieldset/__snapshots__/fieldset.spec.js.snap
  src/__experimental__/components/fieldset/documentation/index.js
  src/__experimental__/components/fieldset/documentation/notes.md
  src/__experimental__/components/fieldset/fieldset-classic.style.js
  src/__experimental__/components/fieldset/fieldset.component.js
  src/__experimental__/components/fieldset/fieldset.spec.js
  src/__experimental__/components/fieldset/fieldset.stories.js
  src/__experimental__/components/fieldset/fieldset.style.js
  src/__experimental__/components/fieldset/index.js
  src/__experimental__/components/input/__snapshots__/input-presentation.spec.js.snap
  src/__experimental__/components/input/input-presentation-classic.style.js
  src/__experimental__/components/input/input-presentation.spec.js
  src/__experimental__/components/input/input-presentation.style.js
  src/__experimental__/components/label/label.style.js
  src/__experimental__/components/select/__snapshots__/select.spec.js.snap
  src/style/themes/base/base-theme.config.js
  src/utils/ether/__spec__.js
  src/utils/ether/ether.js
Labels: Passed QA, Passed UX Review, Pending Review

#2017 fixes vscode debugger
  .vscode/launch.json
Labels: No QA Required, No UX Review Required, Passed Review

#2028 Dialog_fix-sizes
  src/components/dialog/dialog.stories.js
  src/components/dialog/dialog.style.js
Labels: Passed QA, Passed Review

#2029 Generic theme in storybook
  .storybook/__helpers__/components/app-layout/app-layout.js
Labels: Passed QA, Passed Review

#2014 S1T-1852: Removes search text on multi select dropdown after selecting item
  change_log/next/S1T-1852.yml
  src/__experimental__/components/select/select.component.js
Labels: Passed QA, Passed Review

#2016 Fe 1424 - Google Analytics Double Counting
  change_log/next/FE-1424-google-analytics-bug.yml
  src/utils/router/__spec__.js
  src/utils/router/router.js
Labels: No QA Required, No UX Review Required, Passed Review

#2005 Validation integration
  src/__experimental__/components/fieldset/__snapshots__/fieldset.spec.js.snap
  src/__experimental__/components/form-field/form-field.component.js
  src/__experimental__/components/input-decorator-bridge/__snapshots__/input-decorator-bridge.spec.js.snap
  src/__experimental__/components/input-decorator-bridge/input-decorator-bridge.component.js
  src/__experimental__/components/input-decorator-bridge/input-decorator-bridge.spec.js
  src/__experimental__/components/input/__snapshots__/input-presentation.spec.js.snap
  src/__experimental__/components/input/input-presentation.component.js
  src/__experimental__/components/input/input-presentation.spec.js
  src/__experimental__/components/input/input-presentation.style.js
  src/__experimental__/components/input/input.component.js
  src/__experimental__/components/select/__snapshots__/select.spec.js.snap
  src/__experimental__/components/select/select.component.js
  src/__experimental__/components/textbox/__snapshots__/textbox.spec.js.snap
  src/__experimental__/components/textbox/textbox.component.js
  src/__experimental__/components/textbox/textbox.spec.js
  src/__experimental__/components/textbox/textbox.stories.js
  src/components/form/__spec__.js
  src/components/form/form.js
  src/components/link/__snapshots__/link.spec.js.snap
  src/components/message/__snapshots__/message.spec.js.snap
  src/components/message/close-icon/__snapshots__/close-icon.spec.js.snap
  src/components/message/type-icon/__snapshots__/type-icon.spec.js.snap
  src/components/show-edit-pod/__snapshots__/__spec__.js.snap
  src/components/validations/index.js
  src/components/validations/validations.stories.js
  src/style/color-config/index.js
  src/style/themes/classic/classic-theme.config.js
  src/utils/decorators/input-validation/__spec__.js
  src/utils/decorators/input-validation/input-validation.js
  src/utils/decorators/input/__spec__.js
Labels: No QA Required, Pending Review

#2034 Cypress/fe 1484 maitenance
  cypress/integration/alert.feature
  cypress/integration/animatedMenuButton.feature
  cypress/integration/appWrapper.feature
  cypress/integration/button.feature
  cypress/integration/buttonToggle.feature
  cypress/integration/buttonToggleGroup.feature
  cypress/integration/checkbox.feature
  cypress/integration/confirm.feature
  cypress/integration/content.feature
  cypress/integration/create.feature
  cypress/integration/detail.feature
  cypress/integration/dialog.feature
  cypress/integration/dialogFullScreen.feature
  cypress/integration/dropdown.feature
  cypress/integration/fieldset.feature
  cypress/integration/flash.feature
  cypress/locators/alert-dialog/index.js
  cypress/locators/alert-dialog/locators.js
  cypress/locators/alert/index.js
  cypress/locators/alert/locators.js
  cypress/locators/animated-menu-button/index.js
  cypress/locators/animated-menu-button/locators.js
  cypress/locators/confirm/index.js
  cypress/locators/confirm/locators.js
  cypress/locators/create/index.js
  cypress/locators/create/locators.js
  cypress/locators/dialog-full-screen/locators.js
  cypress/locators/dialog/index.js
  cypress/locators/dialog/locators.js
  cypress/locators/index.js
  cypress/locators/locators.js
  cypress/support/helper.js
  cypress/support/step-definitions/alert-dialog-steps.js
  cypress/support/step-definitions/alert-steps.js
  cypress/support/step-definitions/animated-menu-button-steps.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/confirm-steps.js
  cypress/support/step-definitions/create-steps.js
  cypress/support/step-definitions/dialog-full-screen-steps.js
  cypress/support/step-definitions/dialog-steps.js
Labels: Cypress

#2036 resolve @ignore tag for cypress
  cypress.json
  cypress/README.md
  cypress/integration/confirm.feature
Labels: Cypress

#2037 Adds Data Component Attribute to Decimal
  src/__experimental__/components/decimal/decimal.component.js
Labels: Pending Review

#2020 FE-1311: Alert Component
  change_log/next/FE-1311.yml
  src/components/alert/__snapshots__/alert.spec.js.snap
  src/components/alert/alert.component.js
  src/components/alert/alert.spec.js
  src/components/alert/alert.stories.js
  src/components/alert/documentation/index.js
  src/components/alert/documentation/info.js
  src/components/alert/documentation/notes.md
  src/components/alert/index.js
  src/components/alert/package.json
Labels: Passed QA, Passed Review, Passed UX Review

#2040 Fe 1514 no curlybraces in decimal
  src/__experimental__/components/decimal/decimal.component.js
  src/__experimental__/components/decimal/decimal.spec.js
Labels: Passed QA, Passed Review

#2038 PR for Cypress/fe 1508 decimal
  cypress/integration/decimal.feature
  cypress/locators/decimal/index.js
  cypress/locators/decimal/locators.js
  cypress/locators/dialog-full-screen/index.js
  cypress/locators/dialog-full-screen/locators.js
  cypress/locators/locators.js
  cypress/support/step-definitions/decimal-steps.js
  cypress/support/step-definitions/dialog-full-screen-steps.js
  src/__experimental__/components/decimal/decimal.component.js
Labels: Cypress

#2033 FE-1316 - Dialog Full Screen Component
  change_log/next/FE-1316 - dialog-full-screen.yml
  src/__experimental__/components/fieldset/__snapshots__/fieldset.spec.js.snap
  src/components/alert/__snapshots__/alert.spec.js.snap
  src/components/confirm/__snapshots__/__spec__.js.snap
  src/components/date/__snapshots__/date.spec.js.snap
  src/components/date/date.spec.js
  src/components/dialog-full-screen/__snapshots__/__spec__.js.snap
  src/components/dialog-full-screen/__snapshots__/dialog-full-screen.spec.js.snap
  src/components/dialog-full-screen/content-classic.style.js
  src/components/dialog-full-screen/content.style.js
  src/components/dialog-full-screen/dialog-full-screen-classic.style.js
  src/components/dialog-full-screen/dialog-full-screen-variables.scss
  src/components/dialog-full-screen/dialog-full-screen.component.js
  src/components/dialog-full-screen/dialog-full-screen.scss
  src/components/dialog-full-screen/dialog-full-screen.spec.js
  src/components/dialog-full-screen/dialog-full-screen.stories.js
  src/components/dialog-full-screen/dialog-full-screen.style.js
  src/components/dialog-full-screen/documentation/index.js
  src/components/dialog-full-screen/documentation/info.js
  src/components/dialog-full-screen/full-screen-heading/full-screen-heading-classic.style.js
  src/components/dialog-full-screen/full-screen-heading/full-screen-heading.component.js
  src/components/dialog-full-screen/full-screen-heading/full-screen-heading.scss
  src/components/dialog-full-screen/full-screen-heading/full-screen-heading.style.js
  src/components/dialog-full-screen/full-screen-heading/index.js
  src/components/dialog-full-screen/full-screen-heading/package.json
  src/components/dialog-full-screen/icon-classic.style.js
  src/components/dialog-full-screen/icon.style.js
  src/components/dialog-full-screen/index.js
  src/components/dialog-full-screen/package.json
  src/components/dialog/__snapshots__/dialog.spec.js.snap
  src/components/link/__snapshots__/link.spec.js.snap
  src/components/message/__snapshots__/message.spec.js.snap
  src/components/message/type-icon/__snapshots__/type-icon.spec.js.snap
  src/components/pages/page/page.scss
  src/components/pages/pages.stories.js
  src/components/show-edit-pod/__snapshots__/__spec__.js.snap
  src/style/themes/base/base-theme.config.js
Labels: Passed QA, Passed Review, Passed UX Review

#2042 Extend table ajax for post
  __mocks__/superagent.js
  change_log/next/extend-table-ajax-for-post-requests.yml
  src/components/table-ajax/__definition__.js
  src/components/table-ajax/__spec__.js
  src/components/table-ajax/table-ajax.js
Labels: Enhancement, Passed QA, Passed Review

#2039 Carbon Font Update - 2 New Icons
  change_log/next/SOGUX-5630.yml
  demo/views/pages/style/icons/icon-list/icon-list.js
  src/components/icon/fonts/carbon-icons-webfont.woff
  src/components/icon/icon.scss
  src/style-config/base-colors.scss
  src/utils/helpers/options-helper/__spec__.js
  src/utils/helpers/options-helper/option-helper.d.ts
  src/utils/helpers/options-helper/options-helper.d.ts
  src/utils/helpers/options-helper/options-helper.js
Labels: Pending QA, Pending Review
