Repository Sage/carbon, pull requests merged in 2019-05, with the labels that each got.

#2044 Enforce a body with post requests
  __mocks__/superagent.js
  src/components/table-ajax/__spec__.js
  src/components/table-ajax/table-ajax.js
Labels: Enhancement, Passed QA, Passed Review

#2043 S1T-1855: Fixed issue when no search term set
  change_log/next/S1T-1855.yml
  src/components/dropdown-filter/__spec__.js
  src/components/dropdown-filter/dropdown-filter.js
Labels: Bug, Passed QA, Passed Review

#2031 Fe 1322 - Sidebar Component
  change_log/next/FE-1322.yml
  src/__experimental__/components/fieldset/__snapshots__/fieldset.spec.js.snap
  src/components/alert/__snapshots__/alert.spec.js.snap
  src/components/confirm/__snapshots__/__spec__.js.snap
  src/components/dialog-full-screen/__snapshots__/dialog-full-screen.spec.js.snap
  src/components/dialog/__snapshots__/dialog.spec.js.snap
  src/components/link/__snapshots__/link.spec.js.snap
  src/components/message/__snapshots__/message.spec.js.snap
  src/components/message/type-icon/__snapshots__/type-icon.spec.js.snap
  src/components/show-edit-pod/__snapshots__/__spec__.js.snap
  src/components/sidebar/__snapshots__/__spec__.js.snap
  src/components/sidebar/__snapshots__/sidebar.spec.js.snap
  src/components/sidebar/__spec__.js
  src/components/sidebar/index.js
  src/components/sidebar/package.json
  src/components/sidebar/sidebar-classic.style.js
  src/components/sidebar/sidebar-header/__snapshots__/sidebar-header.spec.js.snap
  src/components/sidebar/sidebar-header/__spec__.js
  src/components/sidebar/sidebar-header/index.js
  src/components/sidebar/sidebar-header/package.json
  src/components/sidebar/sidebar-header/sidebar-header-classic.style.js
  src/components/sidebar/sidebar-header/sidebar-header.component.js
  src/components/sidebar/sidebar-header/sidebar-header.js
  src/components/sidebar/sidebar-header/sidebar-header.scss
  src/components/sidebar/sidebar-header/sidebar-header.spec.js
  src/components/sidebar/sidebar-header/sidebar-header.style.js
  src/components/sidebar/sidebar.component.js
  src/components/sidebar/sidebar.js
  src/components/sidebar/sidebar.scss
  src/components/sidebar/sidebar.spec.js
  src/components/sidebar/sidebar.stories.js
  src/components/sidebar/sidebar.style.js
  src/style/themes/base/base-theme.config.js
Labels: Passed QA, Passed Review, Passed UX Review

#1996 AC-4027 - re-introduces default line-height
  change_log/next/AC-4027-pill-line-height-bug.yml
  src/components/pill/pill.scss
Labels: Passed QA, Passed Review, Passed UX Review

#2013 S1T-1840 - Removed css height of the scrollable list item to fix item text overlapping
  change_log/next/scrollable-item-height.yml
  src/components/scrollable-list/scrollable-list-item.component.js
Labels: Passed QA, Passed Review

#2035 InputDecoratorBridge now applies any custom automation tags to the component wrapper
  change_log/next/decorator-bridge-attributes.yml
  src/__experimental__/components/input-decorator-bridge/input-decorator-bridge.component.js
  src/__experimental__/components/select/__snapshots__/select.spec.js.snap
  src/__experimental__/components/select/select.component.js
  src/__experimental__/components/select/select.spec.js
Labels: Passed Review

#2049 v7.1.0
  change_log/v7_1_0/AC-4027-pill-line-height-bug.yml
  change_log/v7_1_0/FE-1424-google-analytics-bug.yml
  change_log/v7_1_0/S1T-1852.yml
  change_log/v7_1_0/S1T-1855.yml
  change_log/v7_1_0/SOGUX-5630.yml
  change_log/v7_1_0/decorator-bridge-attributes.yml
  change_log/v7_1_0/dropdown-filter-visible-value-fix.yml
  change_log/v7_1_0/extend-table-ajax-for-post-requests.yml
  change_log/v7_1_0/scrollable-item-height.yml
  package-lock.json
  package.json
  release_notes/v7_1_0.html.md
Labels: No QA Required, No UX Review Required, Passed Review

#2050 V710 mergeback
  __mocks__/superagent.js
  change_log/v7_1_0/AC-4027-pill-line-height-bug.yml
  change_log/v7_1_0/FE-1424-google-analytics-bug.yml
  change_log/v7_1_0/S1T-1852.yml
  change_log/v7_1_0/S1T-1855.yml
  change_log/v7_1_0/SOGUX-5630.yml
  change_log/v7_1_0/decorator-bridge-attributes.yml
  change_log/v7_1_0/dropdown-filter-visible-value-fix.yml
  change_log/v7_1_0/extend-table-ajax-for-post-requests.yml
  change_log/v7_1_0/scrollable-item-height.yml
  demo/views/pages/style/icons/icon-list/icon-list.js
  package-lock.json
  package.json
  release_notes/v7_1_0.html.md
  src/__experimental__/components/date/__snapshots__/date-picker.spec.js.snap
  src/__experimental__/components/input-decorator-bridge/input-decorator-bridge.component.js
  src/__experimental__/components/select/__snapshots__/select.spec.js.snap
  src/__experimental__/components/select/select.component.js
  src/__experimental__/components/select/select.spec.js
  src/components/date/__snapshots__/date.spec.js.snap
  src/components/dropdown-filter/__spec__.js
  src/components/dropdown-filter/dropdown-filter.js
  src/components/icon/fonts/carbon-icons-webfont.woff
  src/components/icon/icon.scss
  src/components/pill/pill.scss
  src/components/scrollable-list/scrollable-list-item.component.js
  src/components/table-ajax/__definition__.js
  src/components/table-ajax/__spec__.js
  src/components/table-ajax/table-ajax.js
  src/style-config/base-colors.scss
  src/utils/helpers/options-helper/__spec__.js
  src/utils/helpers/options-helper/option-helper.d.ts
  src/utils/helpers/options-helper/options-helper.d.ts
  src/utils/helpers/options-helper/options-helper.js
  src/utils/router/__spec__.js
  src/utils/router/router.js
Labels: No QA Required, No UX Review Required, Pending Review

#2027 Fe 1287 date range
  change_log/next/date-range-experimental-component.yml
  src/__experimental__/components/date-range/__snapshots__/date-range.spec.js.snap
  src/__experimental__/components/date-range/date-range.component.js
  src/__experimental__/components/date-range/date-range.spec.js
  src/__experimental__/components/date-range/date-range.stories.js
  src/__experimental__/components/date-range/date-range.style.js
  src/__experimental__/components/date-range/documentation/index.js
  src/__experimental__/components/date-range/documentation/notes.md
  src/__experimental__/components/date-range/index.js
  src/__experimental__/components/date/__snapshots__/date-picker.spec.js.snap
  src/__experimental__/components/date/date-picker.component.js
  src/__experimental__/components/date/date-picker.spec.js
  src/__experimental__/components/date/date.component.js
  src/__experimental__/components/date/date.spec.js
  src/__experimental__/components/date/day-picker.style.js
  src/__experimental__/components/date/index.js
  src/__experimental__/components/form-field/__snapshots__/form-field.spec.js.snap
  src/__experimental__/components/form-field/form-field.component.js
  src/__experimental__/components/form-field/form-field.spec.js
  src/__experimental__/components/form-field/form-field.style.js
  src/__experimental__/components/input-icon-toggle/__snapshots__/input-icon-toggle.spec.js.snap
  src/__experimental__/components/input-icon-toggle/input-icon-toggle.style.js
  src/__experimental__/components/input/__snapshots__/input-presentation.spec.js.snap
  src/__experimental__/components/input/input-presentation.style.js
  src/__experimental__/components/label/__snapshots__/label.spec.js.snap
  src/__experimental__/components/label/label.spec.js
  src/__experimental__/components/label/label.style.js
  src/__experimental__/components/select/__snapshots__/select.spec.js.snap
  src/__experimental__/components/select/select.spec.js
Labels: Passed QA, Passed Review, Passed UX Review

#2052 Fixed wrong styling in experimental datepickers
  src/__experimental__/components/date/__snapshots__/date-picker.spec.js.snap
  src/__experimental__/components/date/date-picker.component.js
  src/__experimental__/components/date/day-picker-classic.style.js
  src/__experimental__/components/date/day-picker.style.js
  src/__experimental__/components/form-field/__snapshots__/form-field.spec.js.snap
  src/__experimental__/components/form-field/form-field.style.js
Labels: No UX Review Required, Passed QA, Passed Review

#2053 add heading component tests, improve tests using getKnobsInput() method
  cypress/.eslintrc.json
  cypress/integration/buttonToggle.feature
  cypress/integration/buttonToggleGroup.feature
  cypress/integration/carousel.feature
  cypress/integration/checkbox.feature
  cypress/integration/confirm.feature
  cypress/integration/decimal.feature
  cypress/integration/dialog.feature
  cypress/integration/dropdown.feature
  cypress/integration/heading.feature
  cypress/locators/button-toggle/index.js
  cypress/locators/carousel/index.js
  cypress/locators/carousel/locators.js
  cypress/locators/checkbox/index.js
  cypress/locators/checkbox/locators.js
  cypress/locators/confirm/index.js
  cypress/locators/confirm/locators.js
  cypress/locators/create/index.js
  cypress/locators/create/locators.js
  cypress/locators/decimal/index.js
  cypress/locators/decimal/locators.js
  cypress/locators/heading/index.js
  cypress/locators/heading/locators.js
  cypress/locators/index.js
  cypress/locators/locators.js
  cypress/support/step-definitions/alert-steps.js
  cypress/support/step-definitions/button-toggle-steps.js
  cypress/support/step-definitions/carousel-steps.js
  cypress/support/step-definitions/checkbox-steps.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/confirm-steps.js
  cypress/support/step-definitions/content-steps.js
  cypress/support/step-definitions/create-steps.js
  cypress/support/step-definitions/decimal-steps.js
  cypress/support/step-definitions/dialog-steps.js
  cypress/support/step-definitions/dropdown-steps.js
  cypress/support/step-definitions/heading-steps.js
Labels: Cypress, Passed QA

#2056 Automation tests for Storybook components
  cypress/integration/dateInput.feature
  cypress/integration/dateRange.feature
  cypress/locators/date-input/index.js
  cypress/locators/date-input/locators.js
  cypress/locators/date-range/index.js
  cypress/locators/date-range/locators.js
  cypress/support/step-definitions/date-input-steps.js
  cypress/support/step-definitions/date-range-steps.js
  cypress/support/step-definitions/detail-steps.js
Labels: Cypress

#2057 Fixed date changing to current on another input focus in date range
  src/__experimental__/components/date/date.component.js
  src/__experimental__/components/date/date.spec.js
Labels: Passed QA

#2059 Cypress/fe 1513
  cypress/integration/buttonToggleGroup.feature
  cypress/integration/checkbox.feature
  cypress/integration/confirm.feature
  cypress/integration/decimal.feature
  cypress/integration/dropdown.feature
  cypress/integration/heading.feature
  cypress/integration/help.feature
  cypress/integration/icon.feature
  cypress/integration/iconType.feature
  cypress/locators/detail/index.js
  cypress/locators/detail/locators.js
  cypress/locators/fieldset/index.js
  cypress/locators/fieldset/locators.js
  cypress/locators/heading/index.js
  cypress/locators/heading/locators.js
  cypress/locators/help/index.js
  cypress/locators/help/locators.js
  cypress/locators/index.js
  cypress/locators/locators.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/decimal-steps.js
  cypress/support/step-definitions/detail-steps.js
  cypress/support/step-definitions/fieldset-steps.js
  cypress/support/step-definitions/heading-steps.js
  cypress/support/step-definitions/help-steps.js
  cypress/support/step-definitions/icon-steps.js
Labels: Cypress

#2002 Applying Validations
  change_log/next/FE-1288-apply-new-validation.yml
  change_log/next/tooltip-update.yml
  src/__experimental__/components/fieldset/__snapshots__/fieldset.spec.js.snap
  src/__experimental__/components/form-field/form-field.component.js
  src/__experimental__/components/input-decorator-bridge/__snapshots__/input-decorator-bridge.spec.js.snap
  src/__experimental__/components/input-decorator-bridge/input-decorator-bridge.component.js
  src/__experimental__/components/input-decorator-bridge/input-decorator-bridge.spec.js
  src/__experimental__/components/input-icon-toggle/__snapshots__/input-icon-toggle.spec.js.snap
  src/__experimental__/components/input-icon-toggle/input-icon-toggle.component.js
  src/__experimental__/components/input-icon-toggle/input-icon-toggle.spec.js
  src/__experimental__/components/input-icon-toggle/input-icon-toggle.style.js
  src/__experimental__/components/input/__snapshots__/input-presentation.spec.js.snap
  src/__experimental__/components/input/input-presentation-classic.style.js
  src/__experimental__/components/input/input-presentation.component.js
  src/__experimental__/components/input/input-presentation.spec.js
  src/__experimental__/components/input/input-presentation.style.js
  src/__experimental__/components/input/input.component.js
  src/__experimental__/components/select/__snapshots__/select.spec.js.snap
  src/__experimental__/components/select/select.component.js
  src/__experimental__/components/textarea/__snapshots__/textarea.spec.js.snap
  src/__experimental__/components/textarea/character-count/__snapshots__/character-count.spec.js.snap
  src/__experimental__/components/textbox/__snapshots__/textbox.spec.js.snap
  src/__experimental__/components/textbox/textbox.component.js
  src/__experimental__/components/textbox/textbox.spec.js
  src/__experimental__/components/textbox/textbox.stories.js
  src/components/dialog-full-screen/__snapshots__/dialog-full-screen.spec.js.snap
  src/components/form/__spec__.js
  src/components/form/form.js
  src/components/form/form.stories.js
  src/components/link/__snapshots__/link.spec.js.snap
  src/components/message/__snapshots__/message.spec.js.snap
  src/components/message/close-icon/__snapshots__/close-icon.spec.js.snap
  src/components/message/type-icon/__snapshots__/type-icon.spec.js.snap
  src/components/show-edit-pod/__snapshots__/__spec__.js.snap
  src/components/sidebar/__snapshots__/sidebar.spec.js.snap
  src/components/tooltip/tooltip.js
  src/components/tooltip/tooltip.scss
  src/components/validations/__snapshots__/form-with-validations.spec.js.snap
  src/components/validations/__snapshots__/validation-icon.spec.js.snap
  src/components/validations/__snapshots__/with-validation.spec.js.snap
  src/components/validations/form-with-validations.hoc.js
  src/components/validations/form-with-validations.spec.js
  src/components/validations/index.js
  src/components/validations/validation-icon.component.js
  src/components/validations/validation-icon.spec.js
  src/components/validations/validation-icon.style.js
  src/components/validations/validation-types.config.js
  src/components/validations/validations.stories.js
  src/components/validations/with-validation.hoc.js
  src/components/validations/with-validation.spec.js
  src/style/color-config/index.js
  src/style/themes/classic/classic-theme.config.js
  src/utils/decorators/input-validation/__spec__.js
  src/utils/decorators/input-validation/input-validation.js
  src/utils/decorators/input/__spec__.js
  src/utils/decorators/tooltip-decorator/__spec__.js
  src/utils/decorators/tooltip-decorator/tooltip-decorator.js
  src/utils/validations/validator/validator.js
  src/utils/validations/validator/validator.spec.js
Labels: Passed QA, Passed Review

#2058 Fe 1503 - Create component
  src/__experimental__/components/fieldset/__snapshots__/fieldset.spec.js.snap
  src/__experimental__/components/select/__snapshots__/select.spec.js.snap
  src/__experimental__/components/textarea/__snapshots__/textarea.spec.js.snap
  src/__experimental__/components/textarea/character-count/__snapshots__/character-count.spec.js.snap
  src/components/alert/__snapshots__/alert.spec.js.snap
  src/components/confirm/__snapshots__/__spec__.js.snap
  src/components/create/__snapshots__/create.spec.js.snap
  src/components/create/__spec__.js
  src/components/create/create-classic.style.js
  src/components/create/create.component.js
  src/components/create/create.js
  src/components/create/create.scss
  src/components/create/create.spec.js
  src/components/create/create.stories.js
  src/components/create/create.style.js
  src/components/create/index.js
  src/components/create/package.json
  src/components/dialog-full-screen/__snapshots__/dialog-full-screen.spec.js.snap
  src/components/dialog/__snapshots__/dialog.spec.js.snap
  src/components/link/__snapshots__/link.spec.js.snap
  src/components/link/link-classic.style.js
  src/components/link/link.component.js
  src/components/link/link.spec.js
  src/components/link/link.style.js
  src/components/message/__snapshots__/message.spec.js.snap
  src/components/message/close-icon/__snapshots__/close-icon.spec.js.snap
  src/components/message/type-icon/__snapshots__/type-icon.spec.js.snap
  src/components/show-edit-pod/__snapshots__/__spec__.js.snap
  src/components/sidebar/__snapshots__/sidebar.spec.js.snap
  src/components/sidebar/sidebar-header/__snapshots__/sidebar-header.spec.js.snap
  src/style/themes/base/base-theme.config.js
Labels: Passed QA, Passed Review, Passed UX Review

#2021 Fe 1313 button group
  change_log/next/FE-1313-button-toggle.yml
  src/__experimental__/components/fieldset/__snapshots__/fieldset.spec.js.snap
  src/__experimental__/components/select/__snapshots__/select.spec.js.snap
  src/__experimental__/components/textarea/__snapshots__/textarea.spec.js.snap
  src/__experimental__/components/textarea/character-count/__snapshots__/character-count.spec.js.snap
  src/components/alert/__snapshots__/alert.spec.js.snap
  src/components/button-toggle-group/__definition__.js
  src/components/button-toggle-group/__snapshots__/button-toggle-group.spec.js.snap
  src/components/button-toggle-group/__spec__.js
  src/components/button-toggle-group/button-toggle-group.component.js
  src/components/button-toggle-group/button-toggle-group.js
  src/components/button-toggle-group/button-toggle-group.scss
  src/components/button-toggle-group/button-toggle-group.spec.js
  src/components/button-toggle-group/button-toggle-group.stories.js
  src/components/button-toggle-group/button-toggle-group.style.js
  src/components/button-toggle-group/documentation/index.js
  src/components/button-toggle-group/documentation/notes.md
  src/components/button-toggle-group/index.js
  src/components/button-toggle-group/package.json
  src/components/button-toggle/__definition__.js
  src/components/button-toggle/__snapshots__/button-toggle.spec.js.snap
  src/components/button-toggle/__spec__.js
  src/components/button-toggle/button-toggle-classic.style.js
  src/components/button-toggle/button-toggle-icon.component.js
  src/components/button-toggle/button-toggle-input.component.js
  src/components/button-toggle/button-toggle.component.js
  src/components/button-toggle/button-toggle.js
  src/components/button-toggle/button-toggle.scss
  src/components/button-toggle/button-toggle.spec.js
  src/components/button-toggle/button-toggle.stories.js
  src/components/button-toggle/button-toggle.style.js
  src/components/button-toggle/documentation/index.js
  src/components/button-toggle/documentation/notes.md
  src/components/button-toggle/index.js
  src/components/button-toggle/package.json
  src/components/confirm/__snapshots__/__spec__.js.snap
  src/components/create/__snapshots__/create.spec.js.snap
  src/components/dialog-full-screen/__snapshots__/dialog-full-screen.spec.js.snap
  src/components/dialog/__snapshots__/dialog.spec.js.snap
  src/components/message/__snapshots__/message.spec.js.snap
  src/components/message/type-icon/__snapshots__/type-icon.spec.js.snap
  src/components/show-edit-pod/__snapshots__/__spec__.js.snap
  src/components/sidebar/__snapshots__/sidebar.spec.js.snap
  src/components/sidebar/sidebar-header/__snapshots__/sidebar-header.spec.js.snap
  src/style/themes/base/base-theme.config.js
  src/style/themes/large/large-theme.config.js
  src/style/themes/medium/medium-theme.config.js
  src/style/themes/small/small-theme.config.js
Labels: Passed QA, Passed Review, Passed UX Review

#1978 FE-1224 DLS button
  change_log/next/FE-1224-button-for-dls.yml
  src/__experimental__/components/fieldset/__snapshots__/fieldset.spec.js.snap
  src/__experimental__/components/select/__snapshots__/select.spec.js.snap
  src/__experimental__/components/textarea/__snapshots__/textarea.spec.js.snap
  src/__experimental__/components/textarea/character-count/__snapshots__/character-count.spec.js.snap
  src/components/alert/__snapshots__/alert.spec.js.snap
  src/components/alert/alert.stories.js
  src/components/button-toggle/button-toggle.spec.js
  src/components/button/__definition__.js
  src/components/button/__snapshots__/button.spec.js.snap
  src/components/button/__spec__.js
  src/components/button/button-classic.style.js
  src/components/button/button-sizes.style.js
  src/components/button/button-types.style.js
  src/components/button/button.component.js
  src/components/button/button.d.ts
  src/components/button/button.js
  src/components/button/button.scss
  src/components/button/button.spec.js
  src/components/button/button.stories.js
  src/components/button/button.style.js
  src/components/button/documentation/index.js
  src/components/button/documentation/info-classic.js
  src/components/button/documentation/info.js
  src/components/button/documentation/notes.md
  src/components/button/index.js
  src/components/confirm/__snapshots__/__spec__.js.snap
  src/components/confirm/__spec__.js
  src/components/create/__snapshots__/create.spec.js.snap
  src/components/decimal/decimal.d.ts
  src/components/dialog-full-screen/__snapshots__/dialog-full-screen.spec.js.snap
  src/components/dialog/__snapshots__/dialog.spec.js.snap
  src/components/dialog/dialog.stories.js
  src/components/flash/flash.d.ts
  src/components/input-definition.d.ts
  src/components/message/__snapshots__/message.spec.js.snap
  src/components/message/type-icon/__snapshots__/type-icon.spec.js.snap
  src/components/multi-action-button/multi-action-button.stories.js
  src/components/pages/pages.stories.js
  src/components/show-edit-pod/__snapshots__/__spec__.js.snap
  src/components/show-edit-pod/__spec__.js
  src/components/sidebar/__snapshots__/sidebar.spec.js.snap
  src/components/sidebar/sidebar-header/__snapshots__/sidebar-header.spec.js.snap
  src/style/themes/base/base-theme.config.js
  src/utils/helpers/options-helper/__spec__.js
  src/utils/helpers/options-helper/option-helper.d.ts
  src/utils/helpers/options-helper/options-helper.d.ts
  src/utils/helpers/options-helper/options-helper.js
Labels: Passed QA, Passed Review, Passed UX Review

#2067 fix assets prefix
  .travis.yml
  webpack.config.js
Labels: Passed Review

#2064 add form component automation tests
  cypress/integration/form.feature
  cypress/locators/form/index.js
  cypress/locators/form/locators.js
  cypress/support/step-definitions/form-steps.js
Labels: Cypress

#2066 Automation tests for Storybook components
  cypress/integration/inlineInputs.feature
  cypress/integration/link.feature
  cypress/integration/linkIconType.feature
  cypress/integration/menu.feature
  cypress/integration/menuList.feature
  cypress/locators/inline-inputs/index.js
  cypress/locators/inline-inputs/locators.js
  cypress/locators/link/index.js
  cypress/locators/link/locators.js
  cypress/locators/menu-list/index.js
  cypress/locators/menu-list/locators.js
  cypress/locators/menu/index.js
  cypress/locators/menu/locators.js
  cypress/support/helper.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/confirm-steps.js
  cypress/support/step-definitions/inline-inputs-steps.js
  cypress/support/step-definitions/link-steps.js
  cypress/support/step-definitions/menu-list-steps.js
  cypress/support/step-definitions/menu-steps.js
Labels: Cypress

#2071 adds ternaries to set start and end index for pagination
  src/components/table/table.stories.js
Labels: No UX Review Required, Passed Review, Pending QA

#2063 new icon fonts added for ellipsis and remove SVG version where we hav…
  change_log/next/SOGUX-5735.yml
  demo/views/pages/style/icons/icon-list/icon-list.js
  src/components/icon/__spec__.js
  src/components/icon/fonts/carbon-icons-webfont.woff
  src/components/icon/icon.scss
  src/components/icon/icons/icons.js
  src/components/icon/icons/svgs/business/business.js
  src/components/icon/icons/svgs/business/package.json
  src/components/icon/icons/svgs/csv/csv.js
  src/components/icon/icons/svgs/csv/package.json
  src/components/icon/icons/svgs/key/key.js
  src/components/icon/icons/svgs/key/package.json
  src/components/icon/icons/svgs/message/message.js
  src/components/icon/icons/svgs/message/package.json
  src/components/icon/icons/svgs/mobile/mobile.js
  src/components/icon/icons/svgs/mobile/package.json
  src/components/icon/icons/svgs/pdf/package.json
  src/components/icon/icons/svgs/pdf/pdf.js
  src/components/icon/icons/svgs/phone/package.json
  src/components/icon/icons/svgs/phone/phone.js
  src/components/icon/icons/svgs/print/package.json
  src/components/icon/icons/svgs/print/print.js
  src/utils/helpers/options-helper/__spec__.js
  src/utils/helpers/options-helper/option-helper.d.ts
  src/utils/helpers/options-helper/options-helper.d.ts
  src/utils/helpers/options-helper/options-helper.js
Labels: Passed Review, Passed UX Review, Pending QA

#2074 Remove theme object from snapshots
  change_log/next/removes-theme-object-from-snapshots.yml
  src/__experimental__/components/fieldset/__snapshots__/fieldset.spec.js.snap
  src/__experimental__/components/fieldset/fieldset.spec.js
  src/__experimental__/components/select/__snapshots__/select.spec.js.snap
  src/__experimental__/components/select/select.spec.js
  src/__experimental__/components/textarea/__snapshots__/textarea.spec.js.snap
  src/__experimental__/components/textarea/character-count/__snapshots__/character-count.spec.js.snap
  src/__experimental__/components/textarea/character-count/character-count.spec.js
  src/__experimental__/components/textarea/textarea.spec.js
  src/components/alert/__snapshots__/alert.spec.js.snap
  src/components/alert/alert.spec.js
  src/components/confirm/__snapshots__/__spec__.js.snap
  src/components/confirm/__spec__.js
  src/components/create/__snapshots__/create.spec.js.snap
  src/components/create/create.spec.js
  src/components/dialog-full-screen/__snapshots__/dialog-full-screen.spec.js.snap
  src/components/dialog-full-screen/dialog-full-screen.spec.js
  src/components/dialog/__snapshots__/dialog.spec.js.snap
  src/components/dialog/dialog.spec.js
  src/components/message/__snapshots__/message.spec.js.snap
  src/components/message/message.spec.js
  src/components/message/type-icon/__snapshots__/type-icon.spec.js.snap
  src/components/message/type-icon/type-icon.spec.js
  src/components/show-edit-pod/__snapshots__/__spec__.js.snap
  src/components/show-edit-pod/__spec__.js
  src/components/sidebar/__snapshots__/sidebar.spec.js.snap
  src/components/sidebar/sidebar-header/__snapshots__/sidebar-header.spec.js.snap
  src/components/sidebar/sidebar-header/sidebar-header.spec.js
  src/components/sidebar/sidebar.spec.js
Labels: No QA Required, No UX Review Required, Pending Review

#2075 Automation tests for Storybook components
  cypress/integration/confirm.feature
  cypress/integration/menu.feature
  cypress/integration/message.feature
  cypress/integration/mountInApp.feature
  cypress/integration/multiActionButton.feature
  cypress/integration/navigationBar.feature
  cypress/locators/index.js
  cypress/locators/menu/index.js
  cypress/locators/menu/locators.js
  cypress/locators/message/index.js
  cypress/locators/message/locators.js
  cypress/locators/mount-in-app/index.js
  cypress/locators/mount-in-app/locators.js
  cypress/locators/multi-action-button/index.js
  cypress/locators/multi-action-button/locators.js
  cypress/locators/navigation-bar/index.js
  cypress/locators/navigation-bar/locators.js
  cypress/support/helper.js
  cypress/support/step-definitions/menu-steps.js
  cypress/support/step-definitions/message-steps.js
  cypress/support/step-definitions/mount-in-app-steps.js
  cypress/support/step-definitions/multi-action-button-steps.js
  cypress/support/step-definitions/navigation-bar-steps.js
Labels: Cypress

#2022 FE-1315 - Confirm component (styles)
  change_log/next/confirm-styles.yml
  src/components/confirm/confirm.classic.style.js
  src/components/confirm/confirm.component.js
  src/components/confirm/confirm.js
  src/components/confirm/confirm.scss
  src/components/confirm/confirm.spec.js
  src/components/confirm/confirm.stories.js
  src/components/confirm/confirm.style.js
  src/components/confirm/documentation/info.js
  src/components/confirm/index.js
  src/components/confirm/package.json
Labels: Passed QA, Passed Review, Passed UX Review

#2081 Cypress/fe 1608
  cypress.env.json
  cypress/integration/button.feature
  cypress/integration/buttonToggle.feature
  cypress/integration/buttonToggleChangeIcon.feature
  cypress/locators/button-toggle/index.js
  cypress/locators/button-toggle/locators.js
  cypress/locators/button/locators.js
  cypress/support/step-definitions/button-steps.js
  cypress/support/step-definitions/button-toggle-steps.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/pager-steps.js
Labels: Cypress

#2084 fixes uniqueID error
  src/components/table/table.stories.js
Labels: No QA Required, No UX Review Required, Passed Review

#2083 Cypress/fe 1607 Maintenance
  cypress/README.md
  cypress/integration/alert.feature
  cypress/integration/animatedMenuButton.feature
  cypress/integration/appWrapper.feature
  cypress/integration/buttonToggleGroup.feature
  cypress/integration/checkbox.feature
  cypress/integration/confirm.feature
  cypress/integration/content.feature
  cypress/integration/create.feature
  cypress/integration/dateInput.feature
  cypress/integration/dateRange.feature
  cypress/integration/decimal.feature
  cypress/integration/detail.feature
  cypress/integration/dialog.feature
  cypress/integration/dialogFullScreen.feature
  cypress/integration/dropdown.feature
  cypress/integration/fieldset.feature
  cypress/integration/iconType.feature
  cypress/integration/inlineInputs.feature
  cypress/integration/link.feature
  cypress/integration/linkIconType.feature
  cypress/integration/menu.feature
  cypress/integration/menuList.feature
  cypress/integration/multiActionButton.feature
  cypress/integration/navigationBar.feature
  cypress/integration/numberInput.feature
  cypress/locators/button-toggle-group/index.js
  cypress/locators/button-toggle-group/locators.js
  cypress/locators/create/index.js
  cypress/locators/create/locators.js
  cypress/locators/decimal/index.js
  cypress/locators/decimal/locators.js
  cypress/support/step-definitions/button-toggle-group-steps.js
  cypress/support/step-definitions/create-steps.js
  cypress/support/step-definitions/decimal-steps.js
  cypress/support/step-definitions/dialog-full-screen-steps.js
  cypress/support/step-definitions/multi-action-button-steps.js
Labels: Cypress

#2086 Sort props not surfaced in storybook
  src/components/table/draggable-table-cell/draggable-table-cell.component.js
  src/components/table/table.component.js
  src/components/table/table.stories.js
  src/components/table/table.style.js
Labels: No QA Required, No UX Review Required, Pending Review

#2088 adds sortable prop to code column
  src/components/table/table.stories.js
Labels: No QA Required, No UX Review Required, Pending Review

#2087 Adds props to wrapper to calc min height
  src/components/table/table-modern.style.js
  src/components/table/table-sizes.style.js
  src/components/table/table.component.js
  src/components/table/table.style.js
Labels: No QA Required, No UX Review Required, Passed Review

#2061 Fe 1324 tabs
  change_log/next/FE-1324-tabs.yml
  src/components/tabs/__definition__.js
  src/components/tabs/__spec__.js
  src/components/tabs/index.js
  src/components/tabs/package.json
  src/components/tabs/tab-title/__snapshots__/tab-title.spec.js.snap
  src/components/tabs/tab-title/tab-title-classic.style.js
  src/components/tabs/tab-title/tab-title.component.js
  src/components/tabs/tab-title/tab-title.spec.js
  src/components/tabs/tab-title/tab-title.style.js
  src/components/tabs/tab/__definition__.js
  src/components/tabs/tab/__spec__.js
  src/components/tabs/tab/package.json
  src/components/tabs/tab/tab.component.js
  src/components/tabs/tab/tab.js
  src/components/tabs/tab/tab.spec.js
  src/components/tabs/tab/tab.style.js
  src/components/tabs/tabs-header/__snapshots__/tabs-header.spec.js.snap
  src/components/tabs/tabs-header/tabs-header-classic.style.js
  src/components/tabs/tabs-header/tabs-header.component.js
  src/components/tabs/tabs-header/tabs-header.spec.js
  src/components/tabs/tabs-header/tabs-header.style.js
  src/components/tabs/tabs.component.js
  src/components/tabs/tabs.scss
  src/components/tabs/tabs.spec.js
  src/components/tabs/tabs.stories.js
  src/components/tabs/tabs.style.js
  src/style/themes/base/base-theme.config.js
  src/style/themes/large/large-theme.config.js
  src/style/themes/medium/medium-theme.config.js
  src/style/themes/small/small-theme.config.js
Labels: Passed QA, Passed Review, Passed UX Review

#2091 Ensure all table data is sorted not just active page
  src/components/table/table.stories.js
Labels: No QA Required, No UX Review Required, Passed Review, Squad Front End Eng

#2093 Add width prop to header component
  src/components/table/table-header/table-header.component.js
  src/components/table/table-header/table-header.spec.js
  src/components/table/table-header/table-header.style.js
  src/components/table/table.component.js
  src/components/table/table.spec.js
  src/components/table/table.stories.js
Labels: No QA Required, No UX Review Required, Passed Review, Squad Front End Eng

#2080 FE-1325 - Toast Component
  change_log/next/FE-1325.yml
  src/components/dismiss-button/__snapshots__/dismiss-button.spec.js.snap
  src/components/dismiss-button/dismiss-button-classic.style.js
  src/components/dismiss-button/dismiss-button.component.js
  src/components/dismiss-button/dismiss-button.spec.js
  src/components/dismiss-button/dismiss-button.style.js
  src/components/dismiss-button/index.js
  src/components/message/__snapshots__/message.spec.js.snap
  src/components/message/close-icon/close-icon-classic.style.js
  src/components/message/close-icon/close-icon.component.js
  src/components/message/close-icon/close-icon.spec.js
  src/components/message/close-icon/close-icon.style.js
  src/components/message/message-classic-theme-colors.js
  src/components/message/message-classic.style.js
  src/components/message/message-content/__snapshots__/message-content.spec.js.snap
  src/components/message/message-content/message-content-classic.style.js
  src/components/message/message-content/message-content.component.js
  src/components/message/message-content/message-content.spec.js
  src/components/message/message-content/message-content.style.js
  src/components/message/message.component.js
  src/components/message/message.spec.js
  src/components/message/message.stories.js
  src/components/message/message.style.js
  src/components/message/type-icon/__snapshots__/type-icon.spec.js.snap
  src/components/message/type-icon/type-icon-classic.style.js
  src/components/message/type-icon/type-icon.component.js
  src/components/message/type-icon/type-icon.spec.js
  src/components/message/type-icon/type-icon.style.js
  src/components/toast/__snapshots__/toast.spec.js.snap
  src/components/toast/__spec__.js
  src/components/toast/documentation/index.js
  src/components/toast/documentation/info.js
  src/components/toast/documentation/notes.md
  src/components/toast/index.js
  src/components/toast/package.json
  src/components/toast/toast-classic.style.js
  src/components/toast/toast.component.js
  src/components/toast/toast.js
  src/components/toast/toast.scss
  src/components/toast/toast.spec.js
  src/components/toast/toast.stories.js
  src/components/toast/toast.style.js
  src/utils/helpers/options-helper/options-helper.js
Labels: Passed QA, Passed Review, Passed UX Review, Squad Front End Eng

#2069 Fe 1414 step sequence
  change_log/next/FE-1414_step_sequence.yml
  src/components/step-sequence/__definition__.js
  src/components/step-sequence/__snapshots__/step-sequence.spec.js.snap
  src/components/step-sequence/index.js
  src/components/step-sequence/package.json
  src/components/step-sequence/step-sequence-classic.style.js
  src/components/step-sequence/step-sequence-item/__definition__.js
  src/components/step-sequence/step-sequence-item/__snapshots__/step-sequence-item.spec.js.snap
  src/components/step-sequence/step-sequence-item/index.js
  src/components/step-sequence/step-sequence-item/package.json
  src/components/step-sequence/step-sequence-item/step-sequence-item-classic.style.js
  src/components/step-sequence/step-sequence-item/step-sequence-item-content.style.js
  src/components/step-sequence/step-sequence-item/step-sequence-item-hidden-label.style.js
  src/components/step-sequence/step-sequence-item/step-sequence-item-indicator.style.js
  src/components/step-sequence/step-sequence-item/step-sequence-item.component.js
  src/components/step-sequence/step-sequence-item/step-sequence-item.js
  src/components/step-sequence/step-sequence-item/step-sequence-item.scss
  src/components/step-sequence/step-sequence-item/step-sequence-item.spec.js
  src/components/step-sequence/step-sequence-item/step-sequence-item.stories.js
  src/components/step-sequence/step-sequence-item/step-sequence-item.style.js
  src/components/step-sequence/step-sequence-orientation.scss
  src/components/step-sequence/step-sequence.component.js
  src/components/step-sequence/step-sequence.js
  src/components/step-sequence/step-sequence.scss
  src/components/step-sequence/step-sequence.spec.js
  src/components/step-sequence/step-sequence.stories.js
  src/components/step-sequence/step-sequence.style.js
  src/components/step-sequence/style-config.scss
  src/style/themes/base/base-theme.config.js
  src/style/themes/large/large-theme.config.js
  src/style/themes/medium/medium-theme.config.js
Labels: Passed QA, Passed Review, Passed UX Review, Squad Front End Eng

#2094 automated BDD test specs for Pill, Pod, Portrait, Preview
  .vscode/settings.json
  cypress/integration/pill.feature
  cypress/integration/pod.feature
  cypress/integration/portrait.feature
  cypress/integration/preview.feature
  cypress/locators/pill/index.js
  cypress/locators/pill/locators.js
  cypress/locators/pod/index.js
  cypress/locators/pod/locators.js
  cypress/locators/portrait/index.js
  cypress/locators/portrait/locators.js
  cypress/locators/preview/index.js
  cypress/locators/preview/locators.js
  cypress/support/step-definitions/pill-steps.js
  cypress/support/step-definitions/pod-steps.js
  cypress/support/step-definitions/portrait-steps.js
  cypress/support/step-definitions/preview-steps.js
Labels: Cypress

#2085 FE-1518 - Preview Component
  change_log/next/FE-1518.yml
  src/components/preview/__snapshots__/__spec__.js.snap
  src/components/preview/__snapshots__/preview.spec.js.snap
  src/components/preview/index.js
  src/components/preview/package.json
  src/components/preview/preview.component.js
  src/components/preview/preview.scss
  src/components/preview/preview.spec.js
  src/components/preview/preview.stories.js
  src/components/preview/preview.style.js
  src/style/themes/base/base-theme.config.js
Labels: Passed QA, Passed Review, Passed UX Review, Squad Front End Eng

#2095 S1T-1897 - Add withCredentials support to TableAjax
  change_log/next/S1T-1897.yml
  src/components/table-ajax/__definition__.js
  src/components/table-ajax/__spec__.js
  src/components/table-ajax/table-ajax.js
Labels: No UX Review Required, Passed QA, Passed Review

#2096 removes inline style, passes prop to styled wrap
  src/components/table/__snapshots__/table.spec.js.snap
  src/components/table/table-modern.style.js
  src/components/table/table-sizes.style.js
  src/components/table/table.component.js
  src/components/table/table.spec.js
  src/components/table/table.style.js
Labels: No QA Required, No UX Review Required, Passed Review, Squad Front End Eng

#2098 Updates axios and highcharts
  change_log/next/dependency-updates-for-v7-3-0.yml
  package-lock.json
  package.json
Labels: No QA Required, No UX Review Required, Passed Review, Squad Front End Eng

#2100 Mergeback v7 3 0
  change_log/v7_3_0/S1T-1897.yml
  change_log/v7_3_0/dependency-updates-for-v7-3-0.yml
  package-lock.json
  package.json
  release_notes/v7_3_0.html.md
  src/components/table-ajax/__definition__.js
  src/components/table-ajax/__spec__.js
  src/components/table-ajax/table-ajax.js
Labels: Pending Review

#2101 Cypress/fe 1598
  cypress/integration/profile.feature
  cypress/integration/radioButton.feature
  cypress/integration/rainbow.feature
  cypress/integration/row.feature
  cypress/locators/content/locators.js
  cypress/locators/dropdown/locators.js
  cypress/locators/index.js
  cypress/locators/profile/index.js
  cypress/locators/profile/locators.js
  cypress/locators/rainbow/index.js
  cypress/locators/rainbow/locators.js
  cypress/locators/row/index.js
  cypress/locators/row/locators.js
  cypress/support/step-definitions/profile-steps.js
  cypress/support/step-definitions/radio-button-steps.js
  cypress/support/step-definitions/rainbow-steps.js
  cypress/support/step-definitions/row-steps.js
Labels: Cypress
