Repository Sage/carbon, pull requests merged in 2019-10, with the labels that each got.

#2344 FE-2055 Switch component outline issue
  src/__experimental__/components/form-field/form-field.component.js
  src/__experimental__/components/label/label.component.js
  src/__experimental__/components/switch/__snapshots__/switch.spec.js.snap
  src/__experimental__/components/switch/index.d.ts
  src/__experimental__/components/switch/switch.component.js
  src/__experimental__/components/switch/switch.d.ts
  src/__experimental__/components/switch/switch.style.js
  src/components/help/help.component.js
  src/components/help/help.spec.js
  src/components/validations/__snapshots__/validation-icon.spec.js.snap
  src/components/validations/validation-icon.component.js
  src/components/validations/validation-icon.style.js
Labels: Passed QA, Passed Review, Squad Front End

#2376 FE-2085 - Console Error
  src/__experimental__/components/switch/switch.stories.js
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#2278 FE-1728 Switch with validation
  change_log/next/FE-1728-switch.yml
  src/__experimental__/components/checkable-input/__snapshots__/hidden-checkable-input.spec.js.snap
  src/__experimental__/components/checkable-input/checkable-input.component.js
  src/__experimental__/components/checkable-input/checkable-input.spec.js
  src/__experimental__/components/checkable-input/checkable-input.style.js
  src/__experimental__/components/checkable-input/hidden-checkable-input.component.js
  src/__experimental__/components/checkable-input/hidden-checkable-input.spec.js
  src/__experimental__/components/checkbox/__snapshots__/checkbox.spec.js.snap
  src/__experimental__/components/form-field/__snapshots__/form-field.spec.js.snap
  src/__experimental__/components/form-field/form-field.component.js
  src/__experimental__/components/label/__snapshots__/label.spec.js.snap
  src/__experimental__/components/label/index.d.ts
  src/__experimental__/components/label/label.component.js
  src/__experimental__/components/label/label.d.ts
  src/__experimental__/components/label/label.spec.js
  src/__experimental__/components/label/label.style.js
  src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap
  src/__experimental__/components/radio-button/radio-button-group.component.js
  src/__experimental__/components/radio-button/radio-button-group.spec.js
  src/__experimental__/components/switch/__snapshots__/switch.spec.js.snap
  src/__experimental__/components/switch/documentation/index.js
  src/__experimental__/components/switch/documentation/info-validations.js
  src/__experimental__/components/switch/index.d.ts
  src/__experimental__/components/switch/switch-classic.style.js
  src/__experimental__/components/switch/switch.component.js
  src/__experimental__/components/switch/switch.d.ts
  src/__experimental__/components/switch/switch.spec.js
  src/__experimental__/components/switch/switch.stories.js
  src/__experimental__/components/switch/switch.style.js
  src/components/help/help.component.js
  src/components/help/help.spec.js
  src/components/validations/__snapshots__/validation-icon.spec.js.snap
  src/components/validations/index.d.ts
  src/components/validations/validation-icon.component.js
  src/components/validations/validation-icon.spec.js
  src/components/validations/validation-icon.style.js
  src/components/validations/with-validation.d.ts
  src/components/validations/with-validation.hoc.js
  src/components/validations/with-validation.spec.js
  src/utils/ether/ether.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2379 FE-2062 fixed checkbox icon focus outline on modern theme
  src/components/validations/validation-icon.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2381 FE-2083-mouse-cursor-issue
  src/components/drag-and-drop/custom-drag-layer/custom-drag-layer.style.js
  src/components/table/draggable-table-cell/draggable-table-cell.style.js
  src/components/table/table-row/__snapshots__/table-row.spec.js.snap
  src/components/table/table-row/table-row.style.js
Labels: Passed QA, Passed Review, Squad Front End

#2380 Fe 2115 checkbox console errors
  src/__experimental__/components/checkbox/checkbox.stories.js
Labels: Passed QA, Passed Review, Squad Front End

#2377 FE-2083 - [Draggable Context]
  src/components/drag-and-drop/with-drop/__spec__.js
  src/components/drag-and-drop/with-drop/with-drop.js
  src/components/table/table-row/table-row-modern.style.js
  src/components/table/table-row/table-row.spec.js
  src/components/table/table-row/table-row.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2346 FE-1569 and FE-1327: ReactDnD and DraggableContext / draggable table rows
  package-lock.json
  package.json
  src/__deprecated__/components/checkbox/__spec__.js
  src/components/drag-and-drop/custom-drag-layer/__spec__.js
  src/components/drag-and-drop/custom-drag-layer/custom-drag-layer.js
  src/components/drag-and-drop/custom-drag-layer/custom-drag-layer.scss
  src/components/drag-and-drop/custom-drag-layer/custom-drag-layer.style.js
  src/components/drag-and-drop/draggable-context/__spec__.js
  src/components/drag-and-drop/draggable-context/draggable-context.js
  src/components/drag-and-drop/with-drag/with-drag.js
  src/components/drag-and-drop/with-drop/__spec__.js
  src/components/drag-and-drop/with-drop/with-drop.js
  src/components/table/__snapshots__/table.spec.js.snap
  src/components/table/draggable-table-cell/draggable-table-cell.component.js
  src/components/table/draggable-table-cell/draggable-table-cell.spec.js
  src/components/table/draggable-table-cell/draggable-table-cell.style.js
  src/components/table/table-classic.style.js
  src/components/table/table-header/__snapshots__/table-header.spec.js.snap
  src/components/table/table-modern.style.js
  src/components/table/table-row/__snapshots__/table-row.spec.js.snap
  src/components/table/table-row/table-row-classic.style.js
  src/components/table/table-row/table-row-modern.style.js
  src/components/table/table-row/table-row.component.js
  src/components/table/table-row/table-row.spec.js
  src/components/table/table-row/table-row.style.js
  src/components/table/table.style.js
  src/style/themes/base/base-theme.config.js
  src/utils/helpers/dnd/item-target/__spec__.js
  src/utils/helpers/dnd/item-target/item-target.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2394 Regression cypress fix
  docker-compose-cypress.yml
Labels: Cypress, No UX QA Required, Passed Review, Squad Front End

#2401 FE-2153 Focus on icon is visible after the third click tab button
  change_log/next/FE-2153-focus-icon-third-click.yml
  src/__experimental__/components/checkbox/__snapshots__/checkbox-group.spec.js.snap
  src/__experimental__/components/checkbox/__snapshots__/checkbox.spec.js.snap
  src/__experimental__/components/checkbox/checkbox-svg.component.js
Labels: Passed QA, Passed Review, Squad Front End

#2404 FE-2170 Support uncontrolled use of Decimal input
  change_log/next/FE-2170-decimal-uncontrolled-support.yml
  src/__experimental__/components/decimal/decimal.component.js
  src/__experimental__/components/decimal/decimal.spec.js
Labels: Passed Review, Pending QA, Squad Front End

#2411 FE-2228 add tags to flash
  change_log/next/fe-2228-add-tags-for-flash.yml
  cypress/features/build/build.feature
  src/components/flash/flash.component.js
  src/components/flash/flash.spec.js
  src/components/toast/toast.component.js
Labels: No UX QA Required, Passed QA, Pending Review, Squad Front End

#2414 Cypress/FE-2149 textarea and validations components
  cypress.env.json
  cypress/features/regression/validations/dateInputValidations.feature
  cypress/features/regression/validations/dateInputValidationsClassic.feature
  cypress/features/regression/validations/selectValidationClassic.feature
  cypress/features/regression/validations/selectValidations.feature
  cypress/features/regression/validations/switchValidations.feature
  cypress/features/regression/validations/switchValidationsClassic.feature
  cypress/features/regression/validations/textareaValidations.feature
  cypress/features/regression/validations/textareaValidationsClassic.feature
  cypress/features/regression/validations/textboxValidations.feature
  cypress/features/regression/validations/textboxValidationsClassic.feature
  cypress/features/regression/validations/validationsBasic.feature
  cypress/features/regression/validations/validationsBasicClassic.feature
  cypress/features/regression/validations/validationsTextboxBased.feature
  cypress/features/regression/validations/validationsTextboxBasedClassic.feature
  cypress/locators/index.js
  cypress/locators/locators.js
  cypress/locators/textarea/index.js
  cypress/locators/validations/index.js
  cypress/locators/validations/locators.js
  cypress/support/helper.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/text-area-steps.js
  cypress/support/step-definitions/validations-steps.js
Labels: Cypress, Squad Front End

#2386 Cypress/FE-2119 validation components
  cypress.env.json
  cypress/README.md
  cypress/features/regression/experimental/selectValidations.feature
  cypress/features/regression/validations/checkboxValidations.feature
  cypress/features/regression/validations/checkboxValidationsClassic.feature
  cypress/features/regression/validations/dateInputValidations.feature
  cypress/features/regression/validations/dateInputValidationsClassic.feature
  cypress/features/regression/validations/radioButtonValidations..feature
  cypress/features/regression/validations/radioButtonValidationsClassic.feature
  cypress/features/regression/validations/selectValidationClassic.feature
  cypress/features/regression/validations/selectValidations.feature
  cypress/features/regression/validations/switchValidations.feature
  cypress/features/regression/validations/switchValidationsClassic.feature
  cypress/features/regression/validations/textareaValidations.feature
  cypress/features/regression/validations/textareaValidationsClassic.feature
  cypress/features/regression/validations/textboxValidations.feature
  cypress/features/regression/validations/textboxValidationsClassic.feature
  cypress/features/regression/validations/validationsBasic.feature
  cypress/features/regression/validations/validationsBasicClassic.feature
  cypress/features/regression/validations/validationsTextboxBased.feature
  cypress/features/regression/validations/validationsTextboxBasedClassic.feature
  cypress/locators/checkbox/index.js
  cypress/locators/checkbox/locators.js
  cypress/locators/date-input/index.js
  cypress/locators/index.js
  cypress/locators/locators.js
  cypress/locators/radioButton/index.js
  cypress/locators/radioButton/locators.js
  cypress/locators/select/index.js
  cypress/locators/switch/index.js
  cypress/locators/switch/locators.js
  cypress/locators/textarea/index.js
  cypress/locators/validations/index.js
  cypress/locators/validations/locators.js
  cypress/support/helper.js
  cypress/support/step-definitions/checkbox-steps.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/date-input-steps.js
  cypress/support/step-definitions/detail-steps.js
  cypress/support/step-definitions/radio-button-steps.js
  cypress/support/step-definitions/select-steps.js
  cypress/support/step-definitions/switch-steps.js
  cypress/support/step-definitions/text-area-steps.js
  cypress/support/step-definitions/validations-steps.js
Labels: Cypress, Squad Front End

#2420 FE-2246 value is not optional.
  src/__experimental__/components/checkable-input/hidden-checkable-input.component.js
  src/__experimental__/components/checkbox/checkbox.component.js
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2405 FE-2175 GroupedCharacter - added uncontrolled support
  change_log/next/FE-2175-grouped-character-uncontrolled-support.yml
  src/__experimental__/components/grouped-character/grouped-character.component.js
  src/__experimental__/components/grouped-character/grouped-character.spec.js
  src/__experimental__/components/grouped-character/grouped-character.stories.js
  src/__experimental__/components/grouped-character/grouped-character.utils.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2418 FE-2242 fix for duplicate validation icon in textbox based components
  src/__experimental__/components/label/icon-wrapper.style.js
  src/__experimental__/components/textbox/__snapshots__/textbox.spec.js.snap
  src/__experimental__/components/textbox/textbox.component.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2419 fix: corrected handling of onBlur and onChange events FE-2232
  change_log/next/FE-2232-radiobutton-onchange.yml
  src/__experimental__/components/radio-button/__snapshots__/radio-button-group.spec.js.snap
  src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap
  src/__experimental__/components/radio-button/radio-button-group.component.js
  src/__experimental__/components/radio-button/radio-button-group.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2426 FE-2267 experimental docgeninfo updates
  src/__experimental__/components/decimal/decimal.stories.js
  src/__experimental__/components/decimal/docgenInfo.json
  src/__experimental__/components/form/docgenInfo.json
  src/__experimental__/components/radio-button/docgenInfo.json
  src/__experimental__/components/radio-button/index.js
  src/__experimental__/components/radio-button/radio-button-group.component.js
  src/__experimental__/components/radio-button/radio-button.component.js
  src/__experimental__/components/radio-button/radio-button.stories.js
  src/__experimental__/components/select/docgenInfo.json
  src/__experimental__/components/select/option.component.js
  src/__experimental__/components/switch/docgenInfo.json
  src/__experimental__/components/switch/switch.component.js
  src/__experimental__/components/textarea/docgenInfo.json
  src/__experimental__/components/textarea/textarea.component.js
  src/__experimental__/components/textbox/docgenInfo.json
  src/__experimental__/components/textbox/textbox.component.js
Labels: No UX QA Required, Squad Front End

#2429 FE-1987 - Remove Large Theme
  .storybook/theme-decorators.js
  .storybook/theme-selectors.js
  change_log/next/FE-1987-remove-large-theme.yml
  cypress/features/themes/themes.feature
  cypress/fixtures/themes/themes.json
  package-lock.json
  src/__experimental__/components/checkbox/checkbox.spec.js
  src/__experimental__/components/switch/__snapshots__/switch-slider.spec.js.snap
  src/__experimental__/components/switch/switch-slider-panel.spec.js
  src/__experimental__/components/switch/switch-slider.spec.js
  src/__experimental__/components/switch/switch.spec.js
  src/components/message/documentation/notes.md
  src/components/message/message.spec.js
  src/components/pill/pill.spec.js
  src/components/split-button/__snapshots__/split-button.spec.js.snap
  src/components/split-button/split-button.spec.js
  src/style/themes/large/index.js
  src/style/themes/large/large-theme.config.js
  src/style/themes/large/large.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2432 Merge back release candidate to master
  change_log/v9_0_0/mock-date-helper.yml
  package-lock.json
  package.json
  release_notes/v9_0_0.html.md
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End
