Repository Sage/carbon, pull requests merged in 2020-09, with the labels that each got.

#3187 test(navigation-bar/grid): apply new url approach
  cypress/features/regression/test/grid.feature
  cypress/features/regression/test/navigationBar.feature
  cypress/fixtures/test/grid.json
  cypress/fixtures/test/navigationBar.json
  cypress/locators/navigation-bar/index.js
  cypress/support/step-definitions/navigation-bar-steps.js
Labels: Cypress, Squad Front End

#3173 fix(modal, toast): esc key closes all modal elements
  cypress/features/regression/dialogFullScreen.feature
  cypress/features/regression/test/toast.feature
  cypress/support/step-definitions/common-steps.js
  src/components/alert/alert.spec.js
  src/components/dialog-full-screen/dialog-full-screen.spec.js
  src/components/dialog-full-screen/dialog-full-screen.stories.js
  src/components/dialog/dialog.spec.js
  src/components/icon-button/icon-button.component.js
  src/components/modal/__internal__/modal-manager.js
  src/components/modal/__internal__/modal-manager.spec.js
  src/components/modal/modal.component.js
  src/components/modal/modal.spec.js
  src/components/sidebar/sidebar.spec.js
  src/components/toast/toast.component.js
  src/components/toast/toast.spec.js
Labels: Passed QA, Passed UX QA, Pending Review, Squad Front End

#3186 test(simplecolorpicker): add a new test cases
  cypress/features/regression/experimental/simpleColorPicker.feature
  cypress/features/regression/experimental/simpleColorPickerAction.feature
  cypress/fixtures/experimental/simpleColorSelect.json
  cypress/locators/simple-color-picker/index.js
  cypress/support/step-definitions/simple-color-picker-steps.js
Labels: Cypress, Squad Front End

#3188 chore(sidebar): remove classic theme FE-3088
  src/components/sidebar/sidebar-classic.style.js
  src/components/sidebar/sidebar-header/sidebar-header-classic.style.js
  src/components/sidebar/sidebar-header/sidebar-header.spec.js
  src/components/sidebar/sidebar-header/sidebar-header.style.js
  src/components/sidebar/sidebar.spec.js
  src/components/sidebar/sidebar.stories.js
  src/components/sidebar/sidebar.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3114 feat(menu): add keyboard navigation - FE-2927
  src/components/card/card.stories.js
  src/components/heading/__spec__.js
  src/components/link/link.component.js
  src/components/link/link.spec.js
  src/components/link/link.stories.js
  src/components/menu/index.d.ts
  src/components/menu/menu-divider/menu-divider.component.js
  src/components/menu/menu-item/menu-item.component.js
  src/components/menu/menu-item/menu-item.d.ts
  src/components/menu/menu-item/menu-item.spec.js
  src/components/menu/menu-item/menu-item.style.js
  src/components/menu/menu.component.js
  src/components/menu/menu.d.ts
  src/components/menu/menu.spec.js
  src/components/menu/menu.stories.mdx
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3162 feat: add styled system to carbon
  package-lock.json
  package.json
  src/__experimental__/components/checkbox/checkbox.component.js
  src/__experimental__/components/checkbox/checkbox.style.js
  src/__experimental__/components/radio-button/radio-button.style.js
  src/style/themes/base/base-theme.config.js
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#3151 refactor: form alignment minor updates
  src/__experimental__/components/checkbox/__snapshots__/checkbox-group.spec.js.snap
  src/__experimental__/components/checkbox/__snapshots__/checkbox.spec.js.snap
  src/__experimental__/components/checkbox/checkbox.style.js
  src/__experimental__/components/radio-button/__snapshots__/radio-button-group.spec.js.snap
  src/__experimental__/components/radio-button/__snapshots__/radio-button-mapper.spec.js.snap
  src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap
  src/__experimental__/components/radio-button/radio-button-group.component.js
  src/__experimental__/components/radio-button/radio-button-group.d.ts
  src/__experimental__/components/radio-button/radio-button.component.js
  src/__experimental__/components/radio-button/radio-button.stories.mdx
  src/__experimental__/components/radio-button/radio-button.style.js
  src/__internal__/fieldset/fieldset.component.js
  src/__internal__/fieldset/fieldset.d.ts
  src/__internal__/fieldset/fieldset.spec.js
  src/__internal__/fieldset/fieldset.style.js
  src/components/button/button-sizes.style.js
  src/components/button/button.component.js
  src/components/button/button.d.ts
  src/components/button/button.spec.js
  src/components/button/button.stories.mdx
  src/components/button/button.style.js
  src/components/configurable-items/configurable-items.style.js
  src/components/draggable/draggable.stories.mdx
  src/components/flat-table/flat-table-checkbox/__snapshots__/flat-table-checkbox.spec.js.snap
  src/components/flat-table/flat-table-checkbox/flat-table-checkbox.component.js
  src/components/form/form.stories.mdx
  src/components/form/form.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3185 fix(button): update typescript definitions - FE-3039
  src/__experimental__/components/numeral-date/numeral-date.d.ts
  src/components/button/button.d.ts
Labels: No QA Required, Passed Review, Squad Front End, Squad Petrus

#3180 feat(drawer, tabs): add support for custom target overrides via context FE-2888
  src/components/drawer/__internal__/__snapshots__/drawer.spec.js.snap
  src/components/drawer/__internal__/drawer.component.js
  src/components/drawer/__internal__/drawer.d.ts
  src/components/drawer/__internal__/drawer.spec.js
  src/components/drawer/__internal__/drawer.stories.js
  src/components/drawer/__internal__/drawer.stories.mdx
  src/components/drawer/__internal__/drawer.style.js
  src/components/drawer/index.d.ts
  src/components/drawer/index.js
  src/components/flat-table/flat-table-row/flat-table-row.component.js
  src/components/flat-table/flat-table-row/flat-table-row.spec.js
  src/components/flat-table/flat-table.component.js
  src/components/flat-table/flat-table.spec.js
  src/components/tabs/__internal__/tab-title/tab-title.component.js
  src/components/tabs/__internal__/tab-title/tab-title.style.js
  src/components/tabs/__internal__/tab/tab.spec.js
  src/components/tabs/__internal__/tab/tab.style.js
  src/components/tabs/__internal__/tabs-header/tabs-header.component.js
  src/components/tabs/__internal__/tabs-header/tabs-header.spec.js
  src/components/tabs/__internal__/tabs-header/tabs-header.style.js
  src/components/tabs/__internal__/tabs.component.js
  src/components/tabs/__internal__/tabs.d.ts
  src/components/tabs/__internal__/tabs.spec.js
  src/components/tabs/__internal__/tabs.stories.mdx
  src/components/tabs/__internal__/tabs.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3195 chore(pager): update style file path to naming convention
  src/components/pager/__internal__/__snapshots__/pager.spec.js.snap
  src/components/pager/__internal__/pager-navigation-link.component.js
  src/components/pager/__internal__/pager-navigation.component.js
  src/components/pager/__internal__/pager-navigation.spec.js
  src/components/pager/__internal__/pager.component.js
  src/components/pager/__internal__/pager.d.ts
  src/components/pager/__internal__/pager.spec.js
  src/components/pager/__internal__/pager.stories.js
  src/components/pager/__internal__/pager.stories.mdx
  src/components/pager/__internal__/pager.style.js
  src/components/pager/index.d.ts
  src/components/pager/index.js
Labels: No UX QA Required, Passed QA, Pending Review, Squad Front End

#3205 chore(checkbox): remove classic theme support - FE-3128
  cypress/features/regression/experimental/checkbox.feature
  src/__experimental__/components/checkbox/__snapshots__/checkbox.spec.js.snap
  src/__experimental__/components/checkbox/checkbox-classic.style.js
  src/__experimental__/components/checkbox/checkbox.spec.js
  src/__experimental__/components/checkbox/checkbox.stories.js
  src/__experimental__/components/checkbox/checkbox.stories.mdx
  src/__experimental__/components/checkbox/checkbox.style.js
  src/__experimental__/components/checkbox/documentation/index.js
  src/__experimental__/components/checkbox/documentation/info.js
  src/__experimental__/components/checkbox/documentation/notes.md
  src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3199 ci: update cypress yml files
  .github/workflows/cypress-pr.yml
  .github/workflows/cypress-push.yml
Labels: Cypress, Squad Front End

#3182 feat(textbox): add prefix prop to display emphasized prefix (FE-2954)
  cypress/features/regression/experimental/textbox.feature
  cypress/features/regression/experimental/textboxMultiple.feature
  cypress/fixtures/experimental/textbox.json
  cypress/locators/textbox/index.js
  cypress/locators/textbox/locators.js
  cypress/support/step-definitions/select-steps.js
  cypress/support/step-definitions/text-area-steps.js
  cypress/support/step-definitions/textbox-steps.js
  src/__experimental__/components/input/__snapshots__/input-presentation.spec.js.snap
  src/__experimental__/components/input/__snapshots__/input.spec.js.snap
  src/__experimental__/components/input/input-presentation.style.js
  src/__experimental__/components/input/input.style.js
  src/__experimental__/components/select/__snapshots__/select.spec.js.snap
  src/__experimental__/components/simple-color-picker/__snapshots__/simple-color-picker.spec.js.snap
  src/__experimental__/components/textarea/__snapshots__/textarea.spec.js.snap
  src/__experimental__/components/textbox/__internal__/prefix.style.js
  src/__experimental__/components/textbox/textbox.component.js
  src/__experimental__/components/textbox/textbox.d.ts
  src/__experimental__/components/textbox/textbox.spec.js
  src/__experimental__/components/textbox/textbox.stories.js
  src/components/pager/__internal__/__snapshots__/pager.spec.js.snap
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3176 feat(definition list): create definition list component - FE-2885
  cypress/features/regression/test/tile.feature
  src/components/definition-list/dd.component.js
  src/components/definition-list/dd.d.ts
  src/components/definition-list/definition-list.spec.js
  src/components/definition-list/definition-list.stories.js
  src/components/definition-list/definition-list.style.js
  src/components/definition-list/dl.component.js
  src/components/definition-list/dl.d.ts
  src/components/definition-list/dt.component.js
  src/components/definition-list/dt.d.ts
  src/components/definition-list/index.d.ts
  src/components/definition-list/index.js
  src/components/tile/tile.stories.js
  src/components/tile/tile.stories.mdx
  src/style/themes/base/base-theme.config.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3189 feat: add spacing props to pill and icon components - FE-3090/FE-3091/FE-2561
  src/components/icon/docgenInfo.json
  src/components/icon/icon.component.js
  src/components/icon/icon.spec.js
  src/components/icon/icon.stories.js
  src/components/icon/icon.style.js
  src/components/pill/docgenInfo.json
  src/components/pill/pill.component.js
  src/components/pill/pill.spec.js
  src/components/pill/pill.stories.js
  src/components/pill/pill.style.js
  src/components/portal/__snapshots__/__spec__.js.snap
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3194 chore(loader): remove classic theme - FE-3092
  cypress/features/regression/test/loader.feature
  cypress/features/regression/themes/themes.feature
  src/components/loader/docgenInfo.json
  src/components/loader/documentation/index.js
  src/components/loader/documentation/info.js
  src/components/loader/documentation/notes.md
  src/components/loader/loader.stories.js
  src/components/loader/loader.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3209 chore(switch): remove classic theme support - FE-3133
  cypress/features/regression/experimental/switch.feature
  src/__experimental__/components/checkbox/checkbox.stories.mdx
  src/__experimental__/components/switch/__snapshots__/switch.spec.js.snap
  src/__experimental__/components/switch/docgenInfo.json
  src/__experimental__/components/switch/documentation/index.js
  src/__experimental__/components/switch/documentation/info.js
  src/__experimental__/components/switch/documentation/legacy-info.js
  src/__experimental__/components/switch/documentation/notes.md
  src/__experimental__/components/switch/switch-classic-loader-square.style.js
  src/__experimental__/components/switch/switch-classic.style.js
  src/__experimental__/components/switch/switch-slider-classic.style.js
  src/__experimental__/components/switch/switch-slider-panel-classic.style.js
  src/__experimental__/components/switch/switch-slider-panel.spec.js
  src/__experimental__/components/switch/switch-slider-panel.style.js
  src/__experimental__/components/switch/switch-slider.component.js
  src/__experimental__/components/switch/switch-slider.spec.js
  src/__experimental__/components/switch/switch-slider.style.js
  src/__experimental__/components/switch/switch.component.js
  src/__experimental__/components/switch/switch.d.ts
  src/__experimental__/components/switch/switch.spec.js
  src/__experimental__/components/switch/switch.stories.js
  src/__experimental__/components/switch/switch.stories.mdx
  src/__experimental__/components/switch/switch.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3216 fix(note): update inline control variant check constructor FE-3134
  src/components/note/__internal__/note.component.js
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#3211 docs(storybook): add classic removal warning
  .storybook/theme-selector/index.js
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#3136 feat(validations): display validations when field is readOnly
  src/__experimental__/components/date/date.stories.js
  src/__experimental__/components/form-field/form-field.component.js
  src/__experimental__/components/form-field/form-field.spec.js
  src/__experimental__/components/input-icon-toggle/input-icon-toggle.component.js
  src/__experimental__/components/input-icon-toggle/input-icon-toggle.spec.js
  src/__experimental__/components/input/input-presentation.spec.js
  src/__experimental__/components/input/input-presentation.style.js
  src/__experimental__/components/label/label.component.js
  src/__experimental__/components/select/select.stories.js
  src/__experimental__/components/switch/switch-slider.component.js
  src/__experimental__/components/switch/switch-slider.style.js
  src/__experimental__/components/switch/switch.component.js
  src/__experimental__/components/textarea/textarea.stories.js
  src/__experimental__/components/textbox/textbox.stories.js
Labels: Passed QA, Passed UX QA, Pending Review, Squad Front End

#3210 fix(button-toggle): no focus outline when a button-toggle is clicked on Safari or Firefox (FE-2862)
  cypress/features/regression/test/buttonToggleGroup.feature
  cypress/fixtures/test/buttonToggleGroup.json
  cypress/locators/button-toggle-group/index.js
  cypress/locators/button-toggle-group/locators.js
  cypress/support/step-definitions/button-toggle-group-steps.js
  src/components/button-toggle-group/__snapshots__/button-toggle-group.spec.js.snap
  src/components/button-toggle-group/button-toggle-group-validations.stories.mdx
  src/components/button-toggle-group/button-toggle-group.spec.js
  src/components/button-toggle-group/button-toggle-group.stories.js
  src/components/button-toggle-group/button-toggle-group.stories.mdx
  src/components/button-toggle/__snapshots__/button-toggle.spec.js.snap
  src/components/button-toggle/button-toggle-input.component.js
  src/components/button-toggle/button-toggle.component.js
  src/components/button-toggle/button-toggle.spec.js
  src/components/button-toggle/button-toggle.stories.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3215 feat: form input components adaptive behaviour
  src/__experimental__/components/checkbox/checkbox.component.js
  src/__experimental__/components/checkbox/checkbox.d.ts
  src/__experimental__/components/checkbox/checkbox.spec.js
  src/__experimental__/components/checkbox/checkbox.stories.js
  src/__experimental__/components/checkbox/docgenInfo.json
  src/__experimental__/components/date/date.component.js
  src/__experimental__/components/form-field/form-field.component.js
  src/__experimental__/components/form-field/form-field.spec.js
  src/__experimental__/components/numeral-date/numeral-date.component.js
  src/__experimental__/components/numeral-date/numeral-date.d.ts
  src/__experimental__/components/numeral-date/numeral-date.stories.mdx
  src/__experimental__/components/radio-button/radio-button-group.component.js
  src/__experimental__/components/radio-button/radio-button-group.d.ts
  src/__experimental__/components/radio-button/radio-button-group.spec.js
  src/__experimental__/components/radio-button/radio-button.stories.mdx
  src/__experimental__/components/switch/__snapshots__/switch.spec.js.snap
  src/__experimental__/components/switch/docgenInfo.json
  src/__experimental__/components/switch/switch.component.js
  src/__experimental__/components/switch/switch.d.ts
  src/__experimental__/components/switch/switch.spec.js
  src/__experimental__/components/switch/switch.style.js
  src/__experimental__/components/textarea/docgenInfo.json
  src/__experimental__/components/textarea/textarea.component.js
  src/__experimental__/components/textarea/textarea.stories.js
  src/__experimental__/components/textbox/docgenInfo.json
  src/__experimental__/components/textbox/textbox.component.js
  src/__experimental__/components/textbox/textbox.d.ts
  src/__experimental__/components/textbox/textbox.stories.js
  src/__spec_helper__/index.js
  src/__spec_helper__/mock-match-media.js
  src/__spec_helper__/test-utils.js
  src/components/button/__snapshots__/button.spec.js.snap
  src/components/button/button-sizes.style.js
  src/components/button/button.spec.js
  src/components/button/button.style.js
  src/components/form/form.stories.mdx
  src/components/form/form.style.js
  src/components/hr/hr.component.js
  src/components/hr/hr.d.ts
  src/components/hr/hr.spec.js
  src/components/hr/hr.stories.mdx
  src/components/hr/hr.style.js
  src/components/select/select-textbox/select-textbox.component.js
  src/components/select/simple-select/simple-select.stories.mdx
  src/hooks/__internal__/useIsAboveBreakpoint/index.d.ts
  src/hooks/__internal__/useIsAboveBreakpoint/index.js
  src/hooks/__internal__/useIsAboveBreakpoint/index.spec.js
  src/hooks/useMediaQuery/index.d.ts
  src/hooks/useMediaQuery/index.js
  src/hooks/useMediaQuery/index.spec.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3220 docs(tile): update vertical story
  src/components/tile/tile.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3227 test(chromatic): exclude propTypes from chromatic
  .storybook/preview.js
Labels: Chromatic, Squad Front End

#3217 chore(pill): remove classic theme
  cypress/features/regression/pill.feature
  cypress/features/regression/themes/themes.feature
  src/components/pill/docgenInfo.json
  src/components/pill/pill.component.js
  src/components/pill/pill.spec.js
  src/components/pill/pill.stories.js
  src/components/pill/pill.stories.mdx
  src/components/pill/pill.style.js
  src/utils/helpers/options-helper/__spec__.js
  src/utils/helpers/options-helper/options-helper.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3193 feat(confirm): add props (destructive and iconType) - FE-2952
  cypress/features/regression/confirm.feature
  cypress/fixtures/commonComponents/confirm.json
  cypress/support/step-definitions/confirm-steps.js
  src/components/confirm/__definition__.js
  src/components/confirm/confirm.component.js
  src/components/confirm/confirm.spec.js
  src/components/confirm/confirm.stories.js
  src/components/confirm/confirm.style.js
  src/components/confirm/docgenInfo.json
  src/components/dialog/dialog.component.js
  src/components/dialog/dialog.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End, Squad Petrus

#3218 feat(grid): add styled-system cusom padding and margin props (FE-3025)
  cypress/support/step-definitions/grid-steps.js
  src/components/grid/__snapshots__/grid.spec.js.snap
  src/components/grid/grid-container/grid-container.component.js
  src/components/grid/grid-container/grid-container.style.js
  src/components/grid/grid-container/index.d.ts
  src/components/grid/grid-item/grid-item.component.js
  src/components/grid/grid-item/grid-item.style.js
  src/components/grid/grid-item/index.d.ts
  src/components/grid/grid.spec.js
  src/components/grid/grid.stories.js
  src/components/grid/grid.stories.mdx
  src/components/tabs/__internal__/tabs.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3212 feat(hr): add styled-system spacing props
  .storybook/utils/styled-system-props.js
  docs/documentation-styleguide.md
  src/__spec_helper__/test-utils.js
  src/components/hr/hr.component.js
  src/components/hr/hr.d.ts
  src/components/hr/hr.spec.js
  src/components/hr/hr.stories.mdx
  src/components/hr/hr.style.js
  src/utils/helpers/options-helper/options-helper.d.ts
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3161 fix(help): navigate to URL when href is set
  src/components/help/help.component.js
  src/components/help/help.spec.js
  src/components/help/help.stories.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3228 chore(radio-button): remove classic theme support - FE-3132
  src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap
  src/__experimental__/components/radio-button/documentation/index.js
  src/__experimental__/components/radio-button/documentation/info.js
  src/__experimental__/components/radio-button/documentation/notes.md
  src/__experimental__/components/radio-button/radio-button-classic.style.js
  src/__experimental__/components/radio-button/radio-button.spec.js
  src/__experimental__/components/radio-button/radio-button.stories.mdx
  src/__experimental__/components/radio-button/radio-button.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3233 test(cypress): update version to 5.2.0
  package-lock.json
  package.json
Labels: Cypress, Squad Front End

#3235 refactor(test-utils): correct spacing util for defaults
  src/__spec_helper__/test-utils.js
Labels: No QA Required, No UX QA Required, Pending Review

#3238 test(accessibility): update for tests
  cypress.env.json
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/accessibility/accessibilityDesignSystem.feature
Labels: Accessibility, Cypress, Squad Front End

#3239 chore(styled-system): add spacing default value
  .storybook/utils/styled-system-props.js
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#3241 test: disable chromatic for classic theme
  src/components/step-sequence/step-sequence-item/step-sequence-item.stories.js
Labels: Chromatic, No UX QA Required, Squad Front End

#3243 ci(cypress): decrease amount of containers
  .github/workflows/cypress-pr.yml
  .github/workflows/cypress-push.yml
Labels: Cypress, Pending Review, Squad Front End

#3231 feat(vertical-divider): add new component FE-2999
  .storybook/utils/styled-system-props.js
  src/components/menu/menu-item/menu-item.style.js
  src/components/menu/menu.component.js
  src/components/menu/menu.spec.js
  src/components/menu/menu.style.js
  src/components/vertical-divider/index.d.ts
  src/components/vertical-divider/index.js
  src/components/vertical-divider/vertical-divider.component.js
  src/components/vertical-divider/vertical-divider.d.ts
  src/components/vertical-divider/vertical-divider.spec.js
  src/components/vertical-divider/vertical-divider.stories.mdx
  src/components/vertical-divider/vertical-divider.style.js
  src/style/themes/base/base-theme.config.js
  src/style/themes/base/index.js
  src/utils/helpers/options-helper/options-helper.d.ts
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3246 chore: remove classic theme from Carousel, Sidebar, Checkbox, Switch and Loader FE-3150
  cypress/features/regression/experimental/checkbox.feature
  cypress/features/regression/experimental/switch.feature
  cypress/features/regression/test/loader.feature
  cypress/features/regression/themes/themes.feature
  src/__experimental__/components/checkbox/__snapshots__/checkbox.spec.js.snap
  src/__experimental__/components/checkbox/checkbox-classic.style.js
  src/__experimental__/components/checkbox/checkbox.spec.js
  src/__experimental__/components/checkbox/checkbox.stories.js
  src/__experimental__/components/checkbox/checkbox.stories.mdx
  src/__experimental__/components/checkbox/checkbox.style.js
  src/__experimental__/components/checkbox/documentation/index.js
  src/__experimental__/components/checkbox/documentation/info.js
  src/__experimental__/components/checkbox/documentation/notes.md
  src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap
  src/__experimental__/components/switch/__snapshots__/switch.spec.js.snap
  src/__experimental__/components/switch/docgenInfo.json
  src/__experimental__/components/switch/documentation/index.js
  src/__experimental__/components/switch/documentation/info.js
  src/__experimental__/components/switch/documentation/legacy-info.js
  src/__experimental__/components/switch/documentation/notes.md
  src/__experimental__/components/switch/switch-classic-loader-square.style.js
  src/__experimental__/components/switch/switch-classic.style.js
  src/__experimental__/components/switch/switch-slider-classic.style.js
  src/__experimental__/components/switch/switch-slider-panel-classic.style.js
  src/__experimental__/components/switch/switch-slider-panel.spec.js
  src/__experimental__/components/switch/switch-slider-panel.style.js
  src/__experimental__/components/switch/switch-slider.component.js
  src/__experimental__/components/switch/switch-slider.spec.js
  src/__experimental__/components/switch/switch-slider.style.js
  src/__experimental__/components/switch/switch.d.ts
  src/__experimental__/components/switch/switch.spec.js
  src/__experimental__/components/switch/switch.stories.js
  src/__experimental__/components/switch/switch.stories.mdx
  src/__experimental__/components/switch/switch.style.js
  src/components/carousel/__definition__.js
  src/components/carousel/carousel-classic.style.js
  src/components/carousel/carousel.component.js
  src/components/carousel/carousel.spec.js
  src/components/carousel/carousel.stories.js
  src/components/carousel/carousel.style.js
  src/components/carousel/docgenInfo.json
  src/components/carousel/slide/slide.component.js
  src/components/carousel/slide/slide.style.js
  src/components/loader/docgenInfo.json
  src/components/loader/documentation/index.js
  src/components/loader/documentation/info.js
  src/components/loader/documentation/notes.md
  src/components/loader/loader.stories.js
  src/components/loader/loader.stories.mdx
  src/components/sidebar/sidebar-classic.style.js
  src/components/sidebar/sidebar-header/sidebar-header-classic.style.js
  src/components/sidebar/sidebar-header/sidebar-header.spec.js
  src/components/sidebar/sidebar-header/sidebar-header.style.js
  src/components/sidebar/sidebar.spec.js
  src/components/sidebar/sidebar.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End
