Repository Sage/carbon, pull requests merged in 2020-12, with the labels that each got.

#3437 chore(textarea): remove classic theme support - FE-3354
  cypress/features/regression/accessibility/accessibilityExperimental.feature
  cypress/features/regression/experimental/textarea.feature
  cypress/fixtures/experimental/textarea.json
  src/__experimental__/components/textarea/__snapshots__/textarea.spec.js.snap
  src/__experimental__/components/textarea/character-count/character-count.component.js
  src/__experimental__/components/textarea/character-count/character-count.spec.js
  src/__experimental__/components/textarea/character-count/classic-character-count.component.js
  src/__experimental__/components/textarea/character-count/classic-character-count.style.js
  src/__experimental__/components/textarea/docgenInfo.json
  src/__experimental__/components/textarea/documentation/index.js
  src/__experimental__/components/textarea/documentation/info.js
  src/__experimental__/components/textarea/documentation/notes.md
  src/__experimental__/components/textarea/textarea.component.js
  src/__experimental__/components/textarea/textarea.spec.js
  src/__experimental__/components/textarea/textarea.stories.js
  src/__experimental__/components/textarea/textarea.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3436 docs(message): add example of rich text content to stories FE-3139
  src/components/message/message.component.js
  src/components/message/message.stories.js
  src/components/message/message.stories.mdx
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3424 chore(date-range): remove classic theme support - FE-3346
  cypress.env.json
  cypress/features/regression/accessibility/accessibilityExperimental.feature
  cypress/features/regression/experimental/dateRange.feature
  cypress/fixtures/experimental/dateRange.json
  src/__experimental__/components/date-range/date-range.stories.js
  src/__experimental__/components/date-range/date-range.stories.mdx
  src/__experimental__/components/date-range/docgenInfo.json
  src/__experimental__/components/date-range/documentation/index.js
  src/__experimental__/components/date-range/documentation/info.js
  src/__experimental__/components/date-range/documentation/notes.md
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3441 chore: remove classic theme FieldHelp and FormField - FE-3358/FE-3359
  src/__experimental__/components/field-help/field-help.spec.js
  src/__experimental__/components/field-help/field-help.style.js
  src/__experimental__/components/form-field/__snapshots__/form-field.spec.js.snap
  src/__experimental__/components/form-field/form-field.spec.js
  src/__experimental__/components/form-field/form-field.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3440 chore(validation-icon): remove classic theme support - FE-3365
  src/components/validations/__snapshots__/validation-icon.spec.js.snap
  src/components/validations/docgenInfo.json
  src/components/validations/validation-icon.component.js
  src/components/validations/validation-icon.spec.js
  src/components/validations/validation-icon.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3427 chore(decimal): remove classic theme support - FE-3347
  cypress/features/regression/accessibility/accessibilityExperimental.feature
  cypress/features/regression/experimental/decimalInput.feature
  cypress/features/regression/experimental/decimalPrecision.feature
  cypress/fixtures/experimental/decimal.json
  src/__experimental__/components/decimal/decimal.stories.js
  src/__experimental__/components/decimal/decimal.stories.mdx
  src/__experimental__/components/decimal/docgenInfo.json
  src/__experimental__/components/decimal/documentation/index.js
  src/__experimental__/components/decimal/documentation/info.js
  src/__experimental__/components/decimal/documentation/notes.md
Labels: No UX QA Required, Passed Review, Pending QA, Squad Front End

#3426 chore(date): remove classic theme support - FE-3345
  cypress/features/regression/accessibility/accessibilityExperimental.feature
  cypress/features/regression/experimental/dateInput.feature
  cypress/fixtures/experimental/dateInput.json
  src/__experimental__/components/date/__snapshots__/date-picker.spec.js.snap
  src/__experimental__/components/date/date-classic.style.js
  src/__experimental__/components/date/date-picker.spec.js
  src/__experimental__/components/date/date.stories.js
  src/__experimental__/components/date/date.stories.mdx
  src/__experimental__/components/date/day-picker-classic.style.js
  src/__experimental__/components/date/day-picker.style.js
  src/__experimental__/components/date/docgenInfo.json
  src/__experimental__/components/date/documentation/index.js
  src/__experimental__/components/date/documentation/info.js
  src/__experimental__/components/date/documentation/notes.md
  src/__experimental__/components/date/navbar/navbar.spec.js
  src/__experimental__/components/date/weekday/__snapshots__/weekday.spec.js.snap
  src/__experimental__/components/date/weekday/weekday-classic.style.js
  src/__experimental__/components/date/weekday/weekday.spec.js
  src/__experimental__/components/date/weekday/weekday.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3451 chore(dismiss-button): remove dismiss-button component - FE-3364
  src/components/dismiss-button/__snapshots__/dismiss-button.spec.js.snap
  src/components/dismiss-button/dismiss-button-classic.style.js
  src/components/dismiss-button/dismiss-button.component.js
  src/components/dismiss-button/dismiss-button.spec.js
  src/components/dismiss-button/dismiss-button.style.js
  src/components/dismiss-button/index.js
Labels: No UX QA Required, Passed Review, Pending QA, Squad Front End

#3439 chore(simple-color-picker): remove classic theme support - FE-3353
  cypress/features/regression/accessibility/accessibilityExperimental.feature
  cypress/features/regression/experimental/simpleColorPicker.feature
  cypress/features/regression/experimental/simpleColorPickerAction.feature
  src/__experimental__/components/simple-color-picker/color-sample-box/color-sample-box-classic.style.js
  src/__experimental__/components/simple-color-picker/color-sample-box/color-sample-box.spec.js
  src/__experimental__/components/simple-color-picker/color-sample-box/color-sample-box.style.js
  src/__experimental__/components/simple-color-picker/docgenInfo.json
  src/__experimental__/components/simple-color-picker/documentation/index.js
  src/__experimental__/components/simple-color-picker/documentation/info.js
  src/__experimental__/components/simple-color-picker/documentation/notes.md
  src/__experimental__/components/simple-color-picker/simple-color-input/simple-color-input-classic.style.js
  src/__experimental__/components/simple-color-picker/simple-color-input/simple-color-input.spec.js
  src/__experimental__/components/simple-color-picker/simple-color-input/simple-color-input.style.js
  src/__experimental__/components/simple-color-picker/simple-color-picker.stories.js
  src/__experimental__/components/simple-color-picker/simple-color-picker.stories.mdx
  src/__experimental__/components/simple-color-picker/simple-color/simple-color.spec.js
  src/__experimental__/components/simple-color-picker/simple-color/simple-color.style.js
  src/__experimental__/components/simple-color-picker/tick-icon/tick-icon.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3454 chore(action-toolbar): remove classic theme FE-3362
  src/components/action-toolbar/README.md
  src/components/action-toolbar/action-toolbar.component.js
  src/components/action-toolbar/action-toolbar.spec.js
  src/components/action-toolbar/action-toolbar.style.js
  src/components/action-toolbar/package.json
Labels: No UX QA Required, Passed Review, Pending QA, Squad Front End

#3452 chore(textbox): remove classic theme - FE-3355
  cypress/features/regression/accessibility/accessibilityExperimental.feature
  cypress/features/regression/experimental/textbox.feature
  cypress/features/regression/experimental/textboxActions.feature
  cypress/features/regression/experimental/textboxMultiple.feature
  cypress/fixtures/experimental/textbox.json
  src/__experimental__/components/simple-color-picker/simple-color-picker.stories.mdx
  src/__experimental__/components/textarea/textarea.stories.mdx
  src/__experimental__/components/textbox/docgenInfo.json
  src/__experimental__/components/textbox/documentation/index.js
  src/__experimental__/components/textbox/documentation/info.js
  src/__experimental__/components/textbox/documentation/notes.md
  src/__experimental__/components/textbox/textbox.d.ts
  src/__experimental__/components/textbox/textbox.stories.js
  src/__experimental__/components/textbox/textbox.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3461 fix(action-popover): incorrect submenu TS type
  src/components/action-popover/action-popover-item.d.ts
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#3456 chore(dialog-full-screen/full-screen-heading): remove classic theme - FE-3633/FE-3361
  src/__internal__/full-screen-heading/full-screen-heading-classic.style.js
  src/__internal__/full-screen-heading/full-screen-heading.style.js
  src/components/dialog-full-screen/content-classic.style.js
  src/components/dialog-full-screen/content.style.js
  src/components/dialog-full-screen/dialog-full-screen-classic.style.js
  src/components/dialog-full-screen/dialog-full-screen.spec.js
  src/components/dialog-full-screen/dialog-full-screen.stories.js
  src/components/dialog-full-screen/dialog-full-screen.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3449 chore(input): remove classic theme support - FE-3360/FE-3350
  src/__experimental__/components/input/__snapshots__/input-presentation.spec.js.snap
  src/__experimental__/components/input/documentation/info.js
  src/__experimental__/components/input/input-presentation-classic.style.js
  src/__experimental__/components/input/input-presentation.spec.js
  src/__experimental__/components/input/input-presentation.style.js
  src/__experimental__/components/input/input.stories.js
  src/__experimental__/components/select/__snapshots__/select.spec.js.snap
  src/components/pager/__internal__/__snapshots__/pager.spec.js.snap
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3466 build: remove react-highlight dependency
  package-lock.json
  package.json
Labels: Passed QA, Passed Review, Squad Front End

#3469 chore(action-popover): remove support for classic theme FE-3356
  src/components/action-popover/__snapshots__/action-popover.spec.js.snap
  src/components/action-popover/action-popover-classic.style.js
  src/components/action-popover/action-popover.spec.js
  src/components/action-popover/action-popover.stories.js
  src/components/action-popover/action-popover.stories.mdx
  src/components/action-popover/action-popover.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3459 chore(select): delete experimental select and select async components - FE-2721/FE-2720/FE-3352/FE-2864
  .storybook/welcome-page/components-demo/demo/demo.component.js
  cypress/features/regression/accessibility/accessibilityExperimental.feature
  cypress/features/regression/experimental/select.feature
  cypress/features/regression/experimental/selectCustomFilter.feature
  cypress/features/regression/experimental/selectMultiple.feature
  cypress/fixtures/experimental/select.json
  cypress/locators/select/index.js
  cypress/locators/select/locators.js
  cypress/support/step-definitions/select-steps.js
  src/__experimental__/components/fieldset/fieldset-examples.stories.mdx
  src/__experimental__/components/fieldset/fieldset.stories.js
  src/__experimental__/components/select-async/__snapshots__/select-async.spec.js.snap
  src/__experimental__/components/select-async/index.js
  src/__experimental__/components/select-async/response-error.message.js
  src/__experimental__/components/select-async/select-async.component.js
  src/__experimental__/components/select-async/select-async.spec.js
  src/__experimental__/components/select/__snapshots__/option.spec.js.snap
  src/__experimental__/components/select/__snapshots__/select-list.spec.js.snap
  src/__experimental__/components/select/__snapshots__/select.spec.js.snap
  src/__experimental__/components/select/docgenInfo.json
  src/__experimental__/components/select/index.js
  src/__experimental__/components/select/option.component.js
  src/__experimental__/components/select/option.spec.js
  src/__experimental__/components/select/option.test.js
  src/__experimental__/components/select/select-list.component.js
  src/__experimental__/components/select/select-list.spec.js
  src/__experimental__/components/select/select.component.js
  src/__experimental__/components/select/select.spec.js
  src/__experimental__/components/select/select.stories.js
  src/__experimental__/components/select/select.style.js
  src/components/dialog/dialog.stories.js
  src/components/inline-inputs/inline-inputs.stories.mdx
  src/components/select/multi-select/multi-select.component.js
  src/components/select/multi-select/multi-select.style.js
  src/utils/filter-children/filter-children.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3463 chore(fieldset): remove classic theme support - FE-3348
  cypress/features/regression/accessibility/accessibilityExperimental.feature
  cypress/features/regression/experimental/fieldset.feature
  src/__experimental__/components/fieldset/docgenInfo.json
  src/__experimental__/components/fieldset/documentation/index.js
  src/__experimental__/components/fieldset/documentation/notes.md
  src/__experimental__/components/fieldset/fieldset-classic.style.js
  src/__experimental__/components/fieldset/fieldset.spec.js
  src/__experimental__/components/fieldset/fieldset.stories.js
  src/__experimental__/components/fieldset/fieldset.stories.mdx
  src/__experimental__/components/fieldset/fieldset.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3450 feat(sort): screen reader accessibility - FE-3291
  cypress/locators/flat-table/index.js
  src/components/drawer/__internal__/drawer.stories.mdx
  src/components/flat-table/flat-table.stories.js
  src/components/flat-table/sort/sort.component.js
  src/components/flat-table/sort/sort.d.ts
  src/components/flat-table/sort/sort.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3465 fix: prevent accidental form submission - FE-3336
  src/__experimental__/components/date/navbar/__snapshots__/navbar.spec.js.snap
  src/__experimental__/components/date/navbar/button.style.js
  src/__experimental__/components/date/navbar/navbar.component.js
  src/components/advanced-color-picker/advanced-color-picker-cell.style.js
  src/components/batch-selection/__snapshots__/batch-selection.spec.js.snap
  src/components/carousel/carousel.component.js
  src/components/carousel/carousel.style.js
  src/components/dialog-full-screen/__snapshots__/dialog-full-screen.spec.js.snap
  src/components/drawer/__internal__/drawer.style.js
  src/components/duelling-picklist/duelling-picklist.style.js
  src/components/duelling-picklist/picklist-item.component.js
  src/components/icon-button/icon-button.style.js
  src/components/pager/__internal__/__snapshots__/pager.spec.js.snap
  src/components/pager/__internal__/pager.style.js
  src/components/text-editor/__internal__/toolbar/toolbar-button/toolbar-button.component.js
  src/components/text-editor/__internal__/toolbar/toolbar-button/toolbar-button.style.js
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#3473 chore(major): update major dd with master
  CHANGELOG.md
  cypress/locators/flat-table/index.js
  package-lock.json
  package.json
  src/__experimental__/components/date/navbar/__snapshots__/navbar.spec.js.snap
  src/__experimental__/components/date/navbar/button.style.js
  src/__experimental__/components/date/navbar/navbar.component.js
  src/components/action-popover/action-popover-item.d.ts
  src/components/advanced-color-picker/advanced-color-picker-cell.style.js
  src/components/batch-selection/__snapshots__/batch-selection.spec.js.snap
  src/components/carousel/carousel.component.js
  src/components/carousel/carousel.style.js
  src/components/dialog-full-screen/__snapshots__/dialog-full-screen.spec.js.snap
  src/components/drawer/__internal__/drawer.stories.mdx
  src/components/drawer/__internal__/drawer.style.js
  src/components/duelling-picklist/duelling-picklist.style.js
  src/components/duelling-picklist/picklist-item.component.js
  src/components/flat-table/flat-table.stories.js
  src/components/flat-table/sort/sort.component.js
  src/components/flat-table/sort/sort.d.ts
  src/components/flat-table/sort/sort.spec.js
  src/components/icon-button/icon-button.style.js
  src/components/message/message.component.js
  src/components/message/message.stories.js
  src/components/message/message.stories.mdx
  src/components/pager/__internal__/__snapshots__/pager.spec.js.snap
  src/components/pager/__internal__/pager.style.js
  src/components/text-editor/__internal__/toolbar/toolbar-button/toolbar-button.component.js
  src/components/text-editor/__internal__/toolbar/toolbar-button/toolbar-button.style.js
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#3477 chore(classic-theme): remove classic theme batch from dd
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/content.feature
  cypress/features/regression/preview.feature
  cypress/fixtures/commonComponents/preview.json
  cypress/locators/index.js
  cypress/support/step-definitions/preview-steps.js
  src/__internal__/full-screen-heading/full-screen-heading-classic.style.js
  src/__internal__/full-screen-heading/full-screen-heading.style.js
  src/components/action-popover/__snapshots__/action-popover.spec.js.snap
  src/components/action-popover/action-popover-classic.style.js
  src/components/action-popover/action-popover.spec.js
  src/components/action-popover/action-popover.stories.js
  src/components/action-popover/action-popover.stories.mdx
  src/components/action-popover/action-popover.style.js
  src/components/action-toolbar/README.md
  src/components/action-toolbar/action-toolbar.component.js
  src/components/action-toolbar/action-toolbar.spec.js
  src/components/action-toolbar/action-toolbar.style.js
  src/components/action-toolbar/package.json
  src/components/content/README.md
  src/components/content/__definition__.js
  src/components/content/content.stories.js
  src/components/content/content.stories.mdx
  src/components/content/docgenInfo.json
  src/components/content/documentation/index.js
  src/components/content/documentation/notes.md
  src/components/dialog-full-screen/content-classic.style.js
  src/components/dialog-full-screen/content.style.js
  src/components/dialog-full-screen/dialog-full-screen-classic.style.js
  src/components/dialog-full-screen/dialog-full-screen.spec.js
  src/components/dialog-full-screen/dialog-full-screen.stories.js
  src/components/dialog-full-screen/dialog-full-screen.style.js
  src/components/dismiss-button/__snapshots__/dismiss-button.spec.js.snap
  src/components/dismiss-button/dismiss-button-classic.style.js
  src/components/dismiss-button/dismiss-button.component.js
  src/components/dismiss-button/dismiss-button.spec.js
  src/components/dismiss-button/dismiss-button.style.js
  src/components/dismiss-button/index.js
  src/components/preview/__definition__.js
  src/components/preview/docgenInfo.json
  src/components/preview/documentation/index.js
  src/components/preview/documentation/info.js
  src/components/preview/preview.component.js
  src/components/preview/preview.stories.js
  src/components/preview/preview.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3442 feat(select): add infinite scroll callback
  cypress.env.json
  cypress/features/regression/designSystem/filterableSelect.feature
  cypress/features/regression/designSystem/simpleSelect.feature
  cypress/locators/select/index.js
  cypress/locators/select/locators.js
  cypress/support/step-definitions/select-steps.js
  src/components/select/filterable-select/filterable-select.component.js
  src/components/select/filterable-select/filterable-select.stories.mdx
  src/components/select/filterable-select/index.d.ts
  src/components/select/multi-select/multi-select.component.js
  src/components/select/option-group-header/__snapshots__/option-group-header.spec.js.snap
  src/components/select/option-group-header/option-group-header.style.js
  src/components/select/option/__snapshots__/option.spec.js.snap
  src/components/select/option/option.style.js
  src/components/select/select-list/select-list-container.style.js
  src/components/select/select-list/select-list.component.js
  src/components/select/select-list/select-list.spec.js
  src/components/select/select-list/select-list.style.js
  src/components/select/simple-select/index.d.ts
  src/components/select/simple-select/simple-select.component.js
  src/components/select/simple-select/simple-select.stories.mdx
  src/components/select/utils/get-next-index-by-key.js
  src/components/select/utils/get-next-index-by-key.spec.js
  src/components/select/utils/get-next-option-by-key.js
  src/components/select/utils/get-next-option-by-key.spec.js
Labels: Passed QA, Pending Review, Pending UX QA, Squad Front End

#3479 test(accessibility): remove duplicate detail scenario
  cypress/features/regression/accessibility/accessibilityCommon.feature
Labels: Accessibility, Cypress, Squad Front End

#3467 fix(dialog): fix styling for pill close icon
  src/components/dialog/__snapshots__/dialog.spec.js.snap
  src/components/dialog/dialog.stories.mdx
  src/components/dialog/dialog.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3483 fix(alert): fix styling bug with close icon - FE-3416
  src/components/alert/__snapshots__/alert.spec.js.snap
  src/components/alert/alert.spec.js
  src/components/alert/alert.style.js
Labels: No UX QA Required, Passed Review, Pending QA, Squad Front End

#3488 docs(styleguide): add variant explanation
  docs/javascript-styleguide.md
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#3471 refactor(menu): rewrite component
  cypress/locators/menu/index.js
  cypress/locators/menu/locators.js
  cypress/locators/navigation-bar/index.js
  cypress/locators/navigation-bar/locators.js
  cypress/support/step-definitions/menu-steps.js
  src/components/menu/__internal__/keyboard-navigation/index.js
  src/components/menu/__internal__/keyboard-navigation/index.spec.js
  src/components/menu/__internal__/submenu/submenu.component.js
  src/components/menu/__internal__/submenu/submenu.spec.js
  src/components/menu/__internal__/submenu/submenu.style.js
  src/components/menu/menu-divider/menu-divider.component.js
  src/components/menu/menu-divider/menu-divider.spec.js
  src/components/menu/menu-item/index.js
  src/components/menu/menu-item/menu-item.component.js
  src/components/menu/menu-item/menu-item.spec.js
  src/components/menu/menu-item/menu-item.style.js
  src/components/menu/menu-segment-title/menu-segment-title.component.js
  src/components/menu/menu-segment-title/menu-segment-title.spec.js
  src/components/menu/menu.component.js
  src/components/menu/menu.spec.js
  src/components/menu/menu.stories.mdx
  src/components/menu/menu.style.js
  src/components/menu/submenu-block/submenu-block.component.js
  src/components/menu/submenu-block/submenu-block.spec.js
  src/components/menu/submenu-block/submenu-block.style.js
  src/components/menu/submenu-block/submenu.style.js
  src/components/navigation-bar/navigation-bar.component.js
  src/components/navigation-bar/navigation-bar.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3484 chore(classic-theme): remove classic theme leftovers - FE-3147
  .storybook/theme-selector/index.js
  .storybook/theme-selector/register.js
  .storybook/theme-selectors.js
  .storybook/welcome-page/welcome.stories.js
  src/__experimental__/components/checkbox/checkbox.stories.js
  src/__experimental__/components/date/__snapshots__/date.spec.js.snap
  src/__experimental__/components/date/date.spec.js
  src/__experimental__/components/switch/switch.stories.js
  src/components/accordion/accordion.stories.js
  src/components/alert/__snapshots__/alert.spec.js.snap
  src/components/alert/alert.stories.js
  src/components/anchor-navigation/anchor-navigation.stories.js
  src/components/card/card.stories.js
  src/components/carousel/carousel.stories.js
  src/components/configurable-items/configurable-items.stories.js
  src/components/confirm/confirm.stories.js
  src/components/dialog/dialog.stories.js
  src/components/duelling-picklist/duelling-picklist.stories.js
  src/components/icon-button/icon-button-classic.style.js
  src/components/icon-button/icon-button.spec.js
  src/components/icon-button/icon-button.style.js
  src/components/message/message.stories.js
  src/components/pill/README.md
  src/components/pill/__definition__.js
  src/components/pill/documentation/index.js
  src/components/pill/documentation/info.js
  src/components/pill/documentation/notes.md
  src/components/pill/pill-classic.style.js
  src/components/portrait/portrait.stories.js
  src/components/profile/profile.stories.js
  src/components/sidebar/sidebar.stories.js
  src/components/text-editor/__internal__/text-editor.style.js
  src/components/text-editor/__internal__/toolbar/toolbar-button/toolbar-button.style.js
  src/components/tile/tile.stories.mdx
  src/components/toast/toast-classic.style.js
  src/components/toast/toast.stories.js
  src/style/themes/classic/classic-theme.config.js
  src/style/themes/classic/classic-theme.spec.js
  src/style/themes/classic/index.js
  src/style/themes/index.js
  src/utils/helpers/style-helper/index.js
  src/utils/helpers/style-helper/style-helper.d.ts
  src/utils/helpers/style-helper/style-helper.js
  src/utils/helpers/style-helper/style-helper.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3492 refactor(tooltip-decorator): add deprecation warning FE-3437
  src/utils/decorators/tooltip-decorator/tooltip-decorator.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3491 chore(storybook): change viewport to align to dls FE-3427
  .storybook/preview.js
Labels: No UX QA Required, Passed Review, Pending QA, Squad Front End

#3486 feat(filterable-select): clear filter on close (FE-3368)
  cypress/features/regression/designSystem/filterableSelect.feature
  cypress/support/step-definitions/select-steps.js
  src/components/select/filterable-select/filterable-select.component.js
  src/components/select/filterable-select/filterable-select.spec.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3502 test: add --disable-gpu args
  .github/workflows/cypress-pr.yml
  .github/workflows/cypress-push.yml
  cypress/plugins/index.js
Labels: Cypress, Passed Review, Squad Front End

#3509 docs(menu): change NavBar to be NavigationBar
  src/components/menu/menu.stories.mdx
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#3494 fix(tooltip): change tooltip text-align to be always left
  src/components/text-editor/__internal__/text-editor.stories.mdx
  src/components/tooltip/__snapshots__/tooltip.spec.js.snap
  src/components/tooltip/tooltip.spec.js
  src/components/tooltip/tooltip.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3445 feat(search): add styling for dark theme - FE-3191
  src/__experimental__/components/search/search.component.js
  src/__experimental__/components/search/search.d.ts
  src/__experimental__/components/search/search.spec.js
  src/__experimental__/components/search/search.stories.js
  src/__experimental__/components/search/search.stories.mdx
  src/__experimental__/components/search/search.style.js
  src/components/alert/__snapshots__/alert.spec.js.snap
  src/style/themes/base/base-theme.config.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3478 feat(box): extend box to support scrollbar style
  src/components/alert/__snapshots__/alert.spec.js.snap
  src/components/box/box.component.js
  src/components/box/box.d.ts
  src/components/box/box.spec.js
  src/components/box/box.stories.mdx
  src/style/themes/base/base-theme.config.js
Labels: Passed QA, Passed Review, Pending UX QA, Squad Front End

#3493 fix(action-popover): close action popover when submenu item is clicked - FE-3237/FE-3343/FE-3414
  cypress/features/regression/test/actionPopoverNoIFrame.feature
  cypress/locators/action-popover/index.js
  cypress/support/step-definitions/action-popover-steps.js
  src/components/action-popover/action-popover-context.js
  src/components/action-popover/action-popover-item.component.js
  src/components/action-popover/action-popover-menu.component.js
  src/components/action-popover/action-popover.component.js
  src/components/action-popover/action-popover.spec.js
  src/components/action-popover/action-popover.stories.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3513 fix(navbar): remove old styling to allow full width
  src/components/navigation-bar/navigation-bar.stories.mdx
  src/components/navigation-bar/navigation-bar.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3518 fix(submenu): stop submenu width from flexing with parent
  src/components/menu/__internal__/submenu/submenu.style.js
  src/components/menu/menu.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3499 fix(menu): allow null children
  src/components/menu/__internal__/keyboard-navigation/index.js
  src/components/menu/__internal__/submenu/submenu.component.js
  src/components/menu/menu.spec.js
  src/components/menu/menu.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3504 docs(action-popover): add flat table story
  src/components/action-popover/action-popover.stories.mdx
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#3507 docs(multi-action-button): refactor multi-action-button stories - FE-3444
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/multiActionButton.feature
  cypress/features/regression/themes/themes.feature
  cypress/fixtures/commonComponents/multiActionButton.json
  cypress/support/step-definitions/multi-action-button-steps.js
  src/components/multi-action-button/README.md
  src/components/multi-action-button/__definition__.js
  src/components/multi-action-button/docgenInfo.json
  src/components/multi-action-button/documentation/index.js
  src/components/multi-action-button/documentation/info.js
  src/components/multi-action-button/documentation/notes.md
  src/components/multi-action-button/multi-action-button.component.js
  src/components/multi-action-button/multi-action-button.stories.js
  src/components/multi-action-button/multi-action-button.stories.mdx
Labels: No UX QA Required, Passed QA, Pending Review, Squad Front End

#3506 docs(split-button): refactor split-button stories to use csf and mdx - FE-3447
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/splitButton.feature
  cypress/features/regression/themes/themes.feature
  cypress/fixtures/commonComponents/splitButton.json
  cypress/locators/split-button/index.js
  cypress/support/step-definitions/button-steps.js
  cypress/support/step-definitions/split-button-steps.js
  src/components/split-button/__definition__.js
  src/components/split-button/docgenInfo.json
  src/components/split-button/documentation/index.js
  src/components/split-button/documentation/info.js
  src/components/split-button/documentation/notes.md
  src/components/split-button/split-button.component.js
  src/components/split-button/split-button.stories.js
  src/components/split-button/split-button.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3500 docs(profile): refactor profile stories to use csf and mdx - FE-3446
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/profile.feature
  cypress/fixtures/commonComponents/profile.json
  cypress/fixtures/initials/123.jpg
  cypress/fixtures/initials/A.jpg
  cypress/fixtures/initials/AZ.jpg
  cypress/fixtures/initials/BC.jpg
  cypress/fixtures/initials/DARK.jpg
  cypress/fixtures/initials/DEF.jpg
  cypress/fixtures/initials/KK.jpg
  cypress/fixtures/initials/OW.jpg
  cypress/fixtures/initials/TJH.jpg
  cypress/fixtures/initials/TJHGHIJ.jpg
  cypress/locators/profile/index.js
  cypress/locators/profile/locators.js
  cypress/support/step-definitions/profile-steps.js
  src/components/profile/docgenInfo.json
  src/components/profile/documentation/index.js
  src/components/profile/documentation/info.js
  src/components/profile/documentation/notes.md
  src/components/profile/profile.component.js
  src/components/profile/profile.stories.js
  src/components/profile/profile.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3496 docs(portrait): refactor stories to use csf and mdx - FE-3445
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/portrait.feature
  cypress/fixtures/commonComponents/portrait.json
  cypress/locators/portrait/index.js
  cypress/locators/portrait/locators.js
  cypress/support/step-definitions/portrait-steps.js
  src/components/portrait/README.md
  src/components/portrait/docgenInfo.json
  src/components/portrait/documentation/index.js
  src/components/portrait/documentation/info.js
  src/components/portrait/documentation/notes.md
  src/components/portrait/portrait.component.js
  src/components/portrait/portrait.stories.js
  src/components/portrait/portrait.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3512 fix(sidebar): fix sidebar crashing while closing with enableBackgroundUI - FE-3241
  src/components/sidebar/sidebar.component.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3498 docs(carousel): refactor carousel stories to use csf and mdx - FE-3442
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/carousel.feature
  src/components/carousel/README.md
  src/components/carousel/__definition__.js
  src/components/carousel/carousel.component.js
  src/components/carousel/carousel.stories.js
  src/components/carousel/carousel.stories.mdx
  src/components/carousel/docgenInfo.json
  src/components/carousel/documentation/index.js
  src/components/carousel/documentation/notes.md
  src/components/carousel/slide/__definition__.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3443 feat(menu): add icon only menu items for submenu
  src/__experimental__/components/date/__snapshots__/date-picker.spec.js.snap
  src/__experimental__/components/simple-color-picker/__snapshots__/simple-color-picker.spec.js.snap
  src/components/action-popover/__snapshots__/action-popover.spec.js.snap
  src/components/alert/__snapshots__/alert.spec.js.snap
  src/components/batch-selection/__snapshots__/batch-selection.spec.js.snap
  src/components/button/__snapshots__/button.spec.js.snap
  src/components/card/__snapshots__/card.spec.js.snap
  src/components/dialog-full-screen/__snapshots__/dialog-full-screen.spec.js.snap
  src/components/icon/icon.component.js
  src/components/icon/icon.d.ts
  src/components/icon/icon.style.js
  src/components/link/__snapshots__/link.spec.js.snap
  src/components/link/link.component.js
  src/components/link/link.d.ts
  src/components/link/link.spec.js
  src/components/link/link.style.js
  src/components/menu/__internal__/keyboard-navigation/index.js
  src/components/menu/__internal__/keyboard-navigation/index.spec.js
  src/components/menu/__internal__/submenu/submenu.component.js
  src/components/menu/menu-item/menu-item.component.js
  src/components/menu/menu-item/menu-item.d.ts
  src/components/menu/menu-item/menu-item.spec.js
  src/components/menu/menu-item/menu-item.style.js
  src/components/menu/menu.stories.mdx
  src/components/menu/menu.style.js
  src/components/multi-action-button/__snapshots__/multi-action-button.spec.js.snap
  src/components/pager/__internal__/__snapshots__/pager.spec.js.snap
  src/components/pod/__snapshots__/pod.spec.js.snap
  src/components/portal/__snapshots__/__spec__.js.snap
  src/components/select/list-action-button/__snapshots__/list-action-button.spec.js.snap
  src/components/select/option-group-header/__snapshots__/option-group-header.spec.js.snap
  src/components/split-button/__snapshots__/split-button.spec.js.snap
  src/utils/helpers/options-helper/__spec__.js
  src/utils/helpers/options-helper/options-helper.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3524 docs(storybook): correct typo
  src/components/dialog-full-screen/dialog-full-screen.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3480 feat(numeral-date): add date parts internal validation - FE-3184
  cypress/features/regression/designSystem/numeralDate.feature
  cypress/locators/index.js
  cypress/locators/locators.js
  cypress/support/step-definitions/numeral-date-steps.js
  src/__experimental__/components/numeral-date/numeral-date.component.js
  src/__experimental__/components/numeral-date/numeral-date.spec.js
  src/__experimental__/components/numeral-date/numeral-date.stories.js
  src/__experimental__/components/numeral-date/numeral-date.stories.mdx
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3529 test(cypress): remove flash accessibility test
  cypress/features/regression/accessibility/accessibilityCommon.feature
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End
