Repository Sage/carbon, pull requests merged in 2020-07, with the labels that each got.

#3037 test: add more accessibility tests
  cypress.env.json
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/accessibility/accessibilityCommonSecondPart.feature
  cypress/features/regression/accessibility/accessibilityDesignSystem.feature
  cypress/features/regression/accessibility/accessibilityExperimental.feature
  cypress/features/regression/accessibility/accessibilityTest.feature
  cypress/locators/accordion/index.js
  cypress/locators/animated-menu-button/index.js
  cypress/locators/animated-menu-button/locators.js
  cypress/locators/popover-container/index.js
  cypress/support/step-definitions/accordion-steps.js
  cypress/support/step-definitions/animated-menu-button-steps.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/popover-container-steps.js
Labels: Cypress, Squad Front End

#3038 fix(filter): add deprecation warning
  src/components/filter/filter.js
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#3039 docs: remove cypress badge
  README.md
Labels: Docs, No QA Required, No UX QA Required, Pending Review, Squad Front End

#3027 test(cypress.yml): remove spec, add quiet
  .github/workflows/cypress-pr.yml
  .github/workflows/cypress-push.yml
  package-lock.json
  package.json
Labels: Cypress, Pending Review

#3041 ci: build major branches
  .github/workflows/chromatic-push.yml
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#3043 docs: document long lived branches
  CONTRIBUTING.md
Labels: Docs, No QA Required, No UX QA Required, Pending Review, Squad Front End

#3045 ci(cypress): enable debug logging
  .github/workflows/cypress-pr.yml
Labels: Cypress, No UX QA Required, Pending QA, Pending Review, Squad Front End

#3042 docs(alert): remove classic theme stories
  src/components/alert/alert.stories.js
Labels: No UX QA Required, Passed QA, Passed Review

#3050 chore(rainbow): add deprecation warning - FE-2899
  src/components/rainbow/rainbow.component.js
Labels: No QA Required, No UX QA Required, Passed Review, Pending Review, Squad Front End

#3049 fix(switch): fix misaligned validation icon on large switch - FE-2863
  src/__experimental__/components/switch/__snapshots__/switch-slider.spec.js.snap
  src/__experimental__/components/switch/__snapshots__/switch.spec.js.snap
  src/__experimental__/components/switch/switch-slider.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3024 feat(navigation-bar): update component - [FE-1647]
  cypress/features/regression/navigationBar.feature
  cypress/features/regression/test/navigationBar.feature
  src/components/app-wrapper/app-wrapper.scss
  src/components/navigation-bar/__definition__.js
  src/components/navigation-bar/__spec__.js
  src/components/navigation-bar/docgenInfo.json
  src/components/navigation-bar/index.d.ts
  src/components/navigation-bar/index.js
  src/components/navigation-bar/navigation-bar.component.js
  src/components/navigation-bar/navigation-bar.d.ts
  src/components/navigation-bar/navigation-bar.js
  src/components/navigation-bar/navigation-bar.scss
  src/components/navigation-bar/navigation-bar.spec.js
  src/components/navigation-bar/navigation-bar.stories.js
  src/components/navigation-bar/navigation-bar.stories.mdx
  src/components/navigation-bar/navigation-bar.stories.scss
  src/components/navigation-bar/navigation-bar.style.js
  src/components/navigation-bar/notes.md
  src/components/navigation-bar/package.json
  src/style/themes/base/base-theme.config.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3059 ci(cypress): disable debug logging
  .github/workflows/cypress-pr.yml
Labels: Cypress, No QA Required, No UX QA Required, Passed Review, Squad Front End

#3058 fix(menu-item): fix `to` prop issue
  src/components/menu/menu-item/menu-item.component.js
  src/components/menu/menu-item/menu-item.spec.js
Labels: No UX QA Required, Passed QA, Passed Review

#3054 chore(storybook): set welcome page as default storybook page - FE-2914
  .storybook/preview.js
  .storybook/theme-selector/register.js
  .storybook/welcome-page/get-started/get-started.component.js
  .storybook/welcome-page/header/header.component.js
  README.md
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3035 docs(rfc): propose internal interfaces
  rfcs/text/internal-interfaces.md
Labels: Final Comments, RFC, Squad Front End

#3040 build(jest): upgrade to v26
  package-lock.json
  package.json
  src/__experimental__/components/date/date.spec.js
  src/__experimental__/components/form/form.spec.js
  src/__experimental__/components/input/input.spec.js
  src/__experimental__/components/simple-color-picker/simple-color-picker.spec.js
  src/components/accordion/accordion.spec.js
  src/components/action-popover/action-popover.spec.js
  src/components/anchor-navigation/anchor-navigation.spec.js
  src/components/duelling-picklist/duelling-picklist.spec.js
  src/components/popover-container/popover-container.spec.js
  src/components/show-edit-pod/__spec__.js
  src/components/split-button/split-button.spec.js
  src/components/tabs/tabs.spec.js
  src/utils/helpers/events/__spec__.js
  src/utils/helpers/events/events.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3064 chore(animated menu button): add deprecation warning
  src/components/animated-menu-button/animated-menu-button.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3051 feat(table-ajax): replace deprecated spinner with loader component - FE-2893
  src/components/table/table-classic.style.js
  src/components/table/table.component.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3063 chore: remove deprecated filter component
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/filterComponent.feature
  cypress/locators/filter/index.js
  cypress/locators/filter/locators.js
  cypress/support/step-definitions/filter-component-steps.js
  src/components/filter/README.md
  src/components/filter/__definition__.js
  src/components/filter/__spec__.js
  src/components/filter/docgenInfo.json
  src/components/filter/filter.js
  src/components/filter/filter.scss
  src/components/filter/filter.stories.js
  src/components/filter/package.json
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3029 feat(text-editor): add new text editor component FE-2814
  cypress.env.json
  cypress/features/regression/accessibility/accessibilityDesignSystem.feature
  cypress/features/regression/designSystem/textEditor.feature
  cypress/features/regression/designSystem/textEditorWithOptionalCharacterLimit.feature
  cypress/locators/text-editor/index.js
  cypress/locators/text-editor/locators.js
  cypress/support/step-definitions/text-editor-steps.js
  cypress/support/step-definitions/textbox-steps.js
  package-lock.json
  package.json
  src/components/text-editor/__internal__/decorators/index.js
  src/components/text-editor/__internal__/decorators/link-decorator.js
  src/components/text-editor/__internal__/editor-counter/editor-counter.component.js
  src/components/text-editor/__internal__/editor-counter/editor-counter.d.ts
  src/components/text-editor/__internal__/editor-counter/editor-counter.spec.js
  src/components/text-editor/__internal__/editor-counter/editor-counter.style.js
  src/components/text-editor/__internal__/editor-counter/index.d.ts
  src/components/text-editor/__internal__/editor-counter/index.js
  src/components/text-editor/__internal__/editor-link/editor-link.component.js
  src/components/text-editor/__internal__/editor-link/editor-link.d.ts
  src/components/text-editor/__internal__/editor-link/editor-link.spec.js
  src/components/text-editor/__internal__/editor-link/editor-link.style.js
  src/components/text-editor/__internal__/editor-link/index.d.ts
  src/components/text-editor/__internal__/editor-link/index.js
  src/components/text-editor/__internal__/text-editor.component.js
  src/components/text-editor/__internal__/text-editor.d.ts
  src/components/text-editor/__internal__/text-editor.spec.js
  src/components/text-editor/__internal__/text-editor.stories.mdx
  src/components/text-editor/__internal__/text-editor.style.js
  src/components/text-editor/__internal__/toolbar/index.d.ts
  src/components/text-editor/__internal__/toolbar/index.js
  src/components/text-editor/__internal__/toolbar/toolbar-button/index.d.ts
  src/components/text-editor/__internal__/toolbar/toolbar-button/index.js
  src/components/text-editor/__internal__/toolbar/toolbar-button/toolbar-button.component.js
  src/components/text-editor/__internal__/toolbar/toolbar-button/toolbar-button.d.ts
  src/components/text-editor/__internal__/toolbar/toolbar-button/toolbar-button.spec.js
  src/components/text-editor/__internal__/toolbar/toolbar-button/toolbar-button.style.js
  src/components/text-editor/__internal__/toolbar/toolbar.component.js
  src/components/text-editor/__internal__/toolbar/toolbar.d.ts
  src/components/text-editor/__internal__/toolbar/toolbar.spec.js
  src/components/text-editor/__internal__/toolbar/toolbar.style.js
  src/components/text-editor/__internal__/utils/index.js
  src/components/text-editor/__internal__/utils/utils.js
  src/components/text-editor/__internal__/utils/utils.spec.js
  src/components/text-editor/index.d.ts
  src/components/text-editor/index.js
  src/style/themes/base/base-theme.config.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3067 ci(cypress tests): add timeout before build will be canceled
  .github/workflows/cypress-pr.yml
  .github/workflows/cypress-push.yml
Labels: Cypress, Passed Review, Squad Front End

#2913 feat: add new SimpleSelect Component (FE-2646)
  cypress.env.json
  cypress/features/regression/accessibility/accessibilityDesignSystem.feature
  cypress/features/regression/designSystem/filterableSelectEvents.feature
  cypress/features/regression/designSystem/fiterableSelect.feature
  cypress/features/regression/designSystem/simpleSelect.feature
  cypress/features/regression/designSystem/simpleSelectEvents.feature
  cypress/locators/select/index.js
  cypress/locators/select/locators.js
  cypress/support/helper.js
  cypress/support/step-definitions/select-steps.js
  src/__experimental__/components/input-icon-toggle/input-icon-toggle.component.js
  src/components/select/filterable-select/filterable-select.component.js
  src/components/select/filterable-select/filterable-select.spec.js
  src/components/select/filterable-select/filterable-select.stories.mdx
  src/components/select/filterable-select/index.d.ts
  src/components/select/index.js
  src/components/select/option/__snapshots__/option.spec.js.snap
  src/components/select/option/index.d.ts
  src/components/select/option/option.component.js
  src/components/select/option/option.spec.js
  src/components/select/option/option.style.js
  src/components/select/select-list/select-list.component.js
  src/components/select/select-list/select-list.spec.js
  src/components/select/select-list/select-list.style.js
  src/components/select/select-list/update-list-scroll.js
  src/components/select/select-list/update-list-scroll.spec.js
  src/components/select/select-textbox/select-textbox.component.js
  src/components/select/select-textbox/select-textbox.spec.js
  src/components/select/select-textbox/select-textbox.style.js
  src/components/select/simple-select/index.d.ts
  src/components/select/simple-select/simple-select-sizes.stories.mdx
  src/components/select/simple-select/simple-select.component.js
  src/components/select/simple-select/simple-select.spec.js
  src/components/select/simple-select/simple-select.stories.mdx
  src/components/select/simple-select/simple-select.style.js
  src/components/select/utils/get-next-child-by-key.js
  src/components/select/utils/get-next-child-by-key.spec.js
  src/components/select/utils/get-next-child-by-text.js
  src/components/select/utils/get-next-child-by-text.spec.js
  src/components/select/utils/highlight-part-of-text.js
  src/components/select/utils/highlight-part-of-text.spec.js
  src/components/select/utils/matching-text.style.js
  src/components/select/utils/with-filter.hoc.js
  src/components/select/utils/with-filter.spec.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3065 chore: remove deprecated textbox
  cypress/locators/menu-list/locators.js
  src/__deprecated__/components/form/form.spec.js
  src/__deprecated__/components/form/form.stories.js
  src/__deprecated__/components/textbox/__definition__.js
  src/__deprecated__/components/textbox/__spec__.js
  src/__deprecated__/components/textbox/docgenInfo.json
  src/__deprecated__/components/textbox/documentation/index.js
  src/__deprecated__/components/textbox/documentation/info.js
  src/__deprecated__/components/textbox/documentation/notes.md
  src/__deprecated__/components/textbox/package.json
  src/__deprecated__/components/textbox/textbox.d.ts
  src/__deprecated__/components/textbox/textbox.js
  src/__deprecated__/components/textbox/textbox.scss
  src/__deprecated__/components/textbox/textbox.stories.js
  src/components/menu-list/__spec__.js
  src/components/menu-list/menu-list.js
  src/components/sidebar/sidebar-header/sidebar-header.spec.js
  src/components/sidebar/sidebar.spec.js
  src/components/tabs/tab/tab.spec.js
  src/components/tabs/tabs.spec.js
  src/utils/decorators/input-label/input-label.js
  src/utils/decorators/input-validation/input-validation.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3061 feat(menu): update visual appearance to match design system - FE-2315
  cypress.env.json
  cypress/features/regression/designSystem/menuDefaultDivider.feature
  cypress/features/regression/menu.feature
  cypress/locators/menu/index.js
  cypress/locators/menu/locators.js
  cypress/support/step-definitions/menu-steps.js
  src/components/menu/__definition__.js
  src/components/menu/docgenInfo.json
  src/components/menu/documentation/index.js
  src/components/menu/documentation/notes.md
  src/components/menu/index.js
  src/components/menu/menu-divider/menu-divider.component.js
  src/components/menu/menu-divider/menu-divider.spec.js
  src/components/menu/menu-divider/menu-divider.style.js
  src/components/menu/menu-item/__definition__.js
  src/components/menu/menu-item/docgenInfo.json
  src/components/menu/menu-item/menu-item.component.js
  src/components/menu/menu-item/menu-item.spec.js
  src/components/menu/menu-item/menu-item.style.js
  src/components/menu/menu.component.js
  src/components/menu/menu.spec.js
  src/components/menu/menu.stories.js
  src/components/menu/menu.stories.mdx
  src/components/menu/submenu-block/__definition__.js
  src/components/menu/submenu-block/docgenInfo.json
  src/components/menu/submenu-block/submenu-block.component.js
  src/components/menu/submenu-block/submenu-block.spec.js
  src/components/menu/submenu-block/submenu.style.js
  src/style/themes/base/base-theme.config.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2981 fix(tooltip): offscreen positioning - FE-2811
  src/components/help/help.stories.js
  src/components/link/link.stories.js
  src/utils/decorators/tooltip-decorator/__spec__.js
  src/utils/decorators/tooltip-decorator/tooltip-decorator.js
  src/utils/ether/__spec__.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3071 fix(text editor): update styling for lists
  src/components/text-editor/__internal__/text-editor.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3074 chore: remove deprecated rainbow component
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/rainbow.feature
  cypress/fixtures/rainbow.json
  cypress/locators/rainbow/index.js
  cypress/locators/rainbow/locators.js
  cypress/support/step-definitions/rainbow-steps.js
  package-lock.json
  package.json
  src/__spec_helper__/dependencies.js
  src/components/rainbow/__definition__.js
  src/components/rainbow/docgenInfo.json
  src/components/rainbow/documentation/index.js
  src/components/rainbow/documentation/info.js
  src/components/rainbow/documentation/notes.md
  src/components/rainbow/index.js
  src/components/rainbow/rainbow.component.js
  src/components/rainbow/rainbow.spec.js
  src/components/rainbow/rainbow.stories.js
  src/components/rainbow/rainbow.style.js
  src/style/themes/base/base-theme.config.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3066 feat(note): create component and tooltip status FE-2825
  cypress.env.json
  cypress/features/regression/accessibility/accessibilityDesignSystem.feature
  package-lock.json
  src/components/note/__internal__/note.component.js
  src/components/note/__internal__/note.d.ts
  src/components/note/__internal__/note.spec.js
  src/components/note/__internal__/note.stories.mdx
  src/components/note/__internal__/note.style.js
  src/components/note/__internal__/status-with-tooltip/index.js
  src/components/note/__internal__/status-with-tooltip/status.component.js
  src/components/note/__internal__/status-with-tooltip/status.spec.js
  src/components/note/__internal__/status-with-tooltip/status.style.js
  src/components/note/index.d.ts
  src/components/note/index.js
  src/style/themes/base/base-theme.config.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3055 fix(dialog): auto focus dialog when opened
  cypress/features/regression/alert.feature
  cypress/features/regression/dialogFullScreen.feature
  cypress/features/regression/sidebar.feature
  src/components/advanced-color-picker/__snapshots__/advanced-color-picker.spec.js.snap
  src/components/advanced-color-picker/advanced-color-picker.component.js
  src/components/advanced-color-picker/advanced-color-picker.spec.js
  src/components/dialog/__definition__.js
  src/components/dialog/dialog.component.js
  src/components/dialog/dialog.spec.js
  src/components/dialog/docgenInfo.json
  src/components/flash/__snapshots__/flash-legacy.spec.js.snap
  src/utils/helpers/focus-trap/focus-trap.js
  src/utils/helpers/focus-trap/focus-trap.spec.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3069 docs: create guide on draft js editorstate and contentstate FE-2943
  docs/getting-started.stories.mdx
  docs/using-draft-js.stories.mdx
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#3077 test(accessibility): update feature file TCs
  .github/workflows/cypress-pr.yml
  .github/workflows/cypress-push.yml
  cypress/features/regression/accessibility/accessibilityDesignSystem.feature
  cypress/support/helper.js
  cypress/support/step-definitions/common-steps.js
  package-lock.json
  package.json
Labels: Cypress, Passed Review, Squad Front End

#3088 chore: move test folder
  cypress.env.json
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/accessibility/accessibilityDesignSystem.feature
  cypress/features/regression/button.feature
  cypress/features/regression/buttonAsSibling.feature
  cypress/features/regression/test/accordion.feature
  cypress/features/regression/test/accordionGroupedNoIFrame.feature
  cypress/features/regression/test/actionPopoverEventsInIFrame.feature
  cypress/features/regression/test/actionPopoverNoIFrame.feature
  cypress/features/regression/test/actionPopoverStyleOverrideNoIFrame.feature
  cypress/features/regression/test/advancedColorPickerNoIFrame.feature
  cypress/features/regression/test/badge.feature
  cypress/features/regression/test/batchSelection.feature
  cypress/features/regression/test/buttonToggleGroup.feature
  cypress/features/regression/test/draggableNoIFrame.feature
  cypress/features/regression/test/flatTableIniFrame.feature
  cypress/features/regression/test/flatTableNoiFrame.feature
  cypress/features/regression/test/grid.feature
  cypress/features/regression/test/navigationBar.feature
  cypress/features/regression/test/popoverContainer.feature
  cypress/features/regression/test/search.feature
  cypress/features/regression/test/toast.feature
  cypress/features/regression/themes/themes.feature
  cypress/locators/flat-table/locators.js
  cypress/support/helper.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/themes-steps.js
  src/__experimental__/components/numeral-date/numeral-date.stories.js
  src/__experimental__/components/radio-button/radio-button.stories.mdx
  src/__experimental__/components/search/search.stories.js
  src/__experimental__/components/textbox/textbox.stories.mdx
  src/components/accordion/accordion.stories.js
  src/components/action-popover/action-popover.stories.js
  src/components/action-popover/action-popover.stories.mdx
  src/components/advanced-color-picker/advanced-color-picker.stories.js
  src/components/badge/badge.stories.js
  src/components/batch-selection/batch-selection.stories.js
  src/components/button-toggle-group/button-toggle-group.stories.js
  src/components/button/button.stories.js
  src/components/draggable/draggable.stories.js
  src/components/drawer/drawer.stories.js
  src/components/flat-table/flat-table.stories.js
  src/components/flat-table/flat-table.stories.mdx
  src/components/grid/grid.stories.js
  src/components/navigation-bar/navigation-bar.stories.js
  src/components/pager/pager.stories.js
  src/components/popover-container/popover-container.stories.js
  src/components/toast/toast.stories.js
Labels: Cypress, No UX QA Required, Passed QA, Passed Review, Pioneer Friday, Squad Front End

#3085 chore: remove deprecated animated-menu-button component
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/animatedMenuButton.feature
  cypress/locators/animated-menu-button/index.js
  cypress/locators/animated-menu-button/locators.js
  cypress/support/step-definitions/animated-menu-button-steps.js
  src/components/animated-menu-button/README.md
  src/components/animated-menu-button/__definition__.js
  src/components/animated-menu-button/__spec__.js
  src/components/animated-menu-button/animated-menu-button.js
  src/components/animated-menu-button/animated-menu-button.scss
  src/components/animated-menu-button/animated-menu-button.stories.js
  src/components/animated-menu-button/docgenInfo.json
  src/components/animated-menu-button/notes.md
  src/components/animated-menu-button/package.json
  src/components/menu-list/__definition__.js
  src/components/menu-list/documentation/notes.md
  src/components/tabs/__definition__.js
  src/components/tabs/documentation/notes.md
  src/utils/helpers/devices/__spec__.js
  src/utils/helpers/devices/devices.js
  src/utils/helpers/devices/package.json
Labels: No UX QA Required, Passed QA, Pending Review, Squad Front End

#3079 feat: add new props to accordion
  cypress/features/regression/accessibility/accessibilityDesignSystem.feature
  cypress/features/regression/designSystem/accordion.feature
  cypress/locators/accordion/index.js
  cypress/locators/accordion/locators.js
  cypress/support/step-definitions/accordion-steps.js
  src/components/accordion/accordion.component.js
  src/components/accordion/accordion.d.ts
  src/components/accordion/accordion.spec.js
  src/components/accordion/accordion.stories.js
  src/components/accordion/accordion.stories.mdx
  src/components/accordion/accordion.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3083 chore: remove deprecated spinner component
  cypress.env.json
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/loaderLegacySpinner.feature
  cypress/locators/spinner/index.js
  cypress/locators/spinner/locators.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/loader-steps.js
  docs/testing-styleguide.md
  src/__deprecated__/components/spinner/README.md
  src/__deprecated__/components/spinner/__definition__.js
  src/__deprecated__/components/spinner/__snapshots__/spinner.spec.js.snap
  src/__deprecated__/components/spinner/classicSpinnerConfig.js
  src/__deprecated__/components/spinner/docgenInfo.json
  src/__deprecated__/components/spinner/documentation/index.js
  src/__deprecated__/components/spinner/documentation/info.js
  src/__deprecated__/components/spinner/documentation/notes.md
  src/__deprecated__/components/spinner/index.js
  src/__deprecated__/components/spinner/spinner.component.js
  src/__deprecated__/components/spinner/spinner.spec.js
  src/__deprecated__/components/spinner/spinner.style.js
  src/components/loader/loader.stories.js
Labels: No UX QA Required, Passed QA, Pending Review, Squad Front End

#3092 test: convert intermittently failing cypress test to be a chromatic test
  cypress/features/regression/tableWithInputs.feature
  src/components/table/table.stories.js
Labels: Chromatic, Cypress, No UX QA Required, Passed QA, Passed Review, Squad Front End

#3086 test(helper): function to pass parameters via url
  cypress.env.json
  cypress/features/regression/alert.feature
  cypress/features/regression/alertActions.feature
  cypress/features/regression/test/badge.feature
  cypress/features/regression/test/badgeActions.feature
  cypress/fixtures/commonComponents/alert.json
  cypress/fixtures/test/badge.json
  cypress/locators/badge/index.js
  cypress/locators/confirm/index.js
  cypress/locators/dialog/index.js
  cypress/locators/index.js
  cypress/support/helper.js
  cypress/support/step-definitions/alert-steps.js
  cypress/support/step-definitions/badge-steps.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/confirm-steps.js
Labels: Cypress, Pending Review, Squad Front End

#3081 refactor(pager): update pager to use select component
  cypress/locators/pager/index.js
  cypress/locators/pager/locators.js
  cypress/locators/switch/index.js
  cypress/locators/switch/locators.js
  cypress/support/step-definitions/pager-steps.js
  src/components/pager/__snapshots__/pager.spec.js.snap
  src/components/pager/pager.component.js
  src/components/pager/pager.spec.js
  src/components/pager/pager.styles.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3095 docs(contributing): preventing unnecessary builds
  CONTRIBUTING.md
Labels: Docs, No QA Required, No UX QA Required, Passed Review, Squad Front End

#3098 test(decimal): update tests with new approach
  cypress/features/regression/experimental/dateInput.feature
  cypress/features/regression/experimental/decimalInput.feature
  cypress/features/regression/experimental/decimalPrecision.feature
  cypress/features/regression/experimental/fieldset.feature
  cypress/features/regression/experimental/form.feature
  cypress/fixtures/experimental/decimal.json
  cypress/fixtures/experimental/fieldset.json
  cypress/fixtures/experimental/form.json
  cypress/locators/fieldset/index.js
  cypress/locators/form/index.js
  cypress/locators/form/locators.js
  cypress/locators/index.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/decimal-steps.js
  cypress/support/step-definitions/form-steps.js
Labels: Cypress, Squad Front End

#3096 chore: remove deprecated dropdown component
  .storybook/preview.js
  cypress/locators/dropdown/index.js
  cypress/locators/dropdown/locators.js
  cypress/support/step-definitions/dropdown-steps.js
  src/__deprecated__/components/dropdown/__definition__.js
  src/__deprecated__/components/dropdown/__snapshots__/__spec__.js.snap
  src/__deprecated__/components/dropdown/__spec__.js
  src/__deprecated__/components/dropdown/docgenInfo.json
  src/__deprecated__/components/dropdown/documentation/Info.js
  src/__deprecated__/components/dropdown/documentation/notes.md
  src/__deprecated__/components/dropdown/dropdown.js
  src/__deprecated__/components/dropdown/dropdown.scss
  src/__deprecated__/components/dropdown/dropdown.stories.js
  src/__deprecated__/components/dropdown/package.json
  src/__experimental__/components/input-decorator-bridge/__snapshots__/input-decorator-bridge.spec.js.snap
  src/__experimental__/components/input-decorator-bridge/index.js
  src/__experimental__/components/input-decorator-bridge/input-decorator-bridge.component.js
  src/__experimental__/components/input-decorator-bridge/input-decorator-bridge.spec.js
  src/utils/decorators/input-label/__spec__.js
  src/utils/decorators/input-label/input-label.js
  src/utils/decorators/input-label/input-label.scss
  src/utils/decorators/input-label/package.json
  src/utils/decorators/input-validation/__spec__.js
  src/utils/decorators/input-validation/input-validation.js
  src/utils/decorators/input-validation/package.json
  src/utils/decorators/input/__spec__.js
  src/utils/decorators/input/input.js
  src/utils/decorators/input/input.scss
  src/utils/decorators/input/package.json
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3102 test(numeraldate,checkbox,dateinput,daterange): update tests with a new approach
  cypress/features/regression/designSystem/numeralDate.feature
  cypress/features/regression/experimental/checkbox.feature
  cypress/features/regression/experimental/dateInput.feature
  cypress/features/regression/experimental/dateRange.feature
  cypress/fixtures/experimental/checkbox.json
  cypress/fixtures/experimental/dateInput.json
  cypress/fixtures/experimental/dateRange.json
  cypress/fixtures/test/numeralDate.json
  cypress/locators/checkbox/index.js
  cypress/locators/date-input/index.js
  cypress/locators/date-range/index.js
  cypress/locators/date-range/locators.js
  cypress/locators/index.js
  cypress/locators/numeralDate/index.js
  cypress/locators/numeralDate/locators.js
  cypress/support/step-definitions/checkbox-steps.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/date-input-steps.js
  cypress/support/step-definitions/date-range-steps.js
  cypress/support/step-definitions/numeral-date-steps.js
Labels: Cypress, Squad Front End

#3099 feat(hr): add new hr component
  src/components/hr/hr.component.js
  src/components/hr/hr.d.ts
  src/components/hr/hr.spec.js
  src/components/hr/hr.stories.mdx
  src/components/hr/hr.style.js
  src/components/hr/index.d.ts
  src/components/hr/index.js
  src/style/themes/base/base-theme.config.js
  src/utils/helpers/options-helper/options-helper.d.ts
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3104 test(textarea): update with new approach
  cypress/features/regression/experimental/textarea.feature
  cypress/features/regression/experimental/textbox.feature
  cypress/features/regression/experimental/textboxActions.feature
  cypress/features/regression/experimental/textboxMultiple.feature
  cypress/fixtures/experimental/textarea.json
  cypress/fixtures/experimental/textbox.json
  cypress/locators/index.js
  cypress/locators/textarea/index.js
  cypress/locators/textbox/index.js
  cypress/support/step-definitions/button-toggle-group-steps.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/text-area-steps.js
  cypress/support/step-definitions/textbox-steps.js
Labels: Cypress, Squad Front End

#3105 docs(hr): move hr stories to design system folder
  src/components/hr/hr.stories.mdx
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#3084 feat: add form spacing options
  cypress/features/regression/experimental/textbox.feature
  cypress/features/regression/experimental/textboxMultiple.feature
  cypress/support/step-definitions/configurable-items-steps.js
  cypress/support/step-definitions/numner-input-steps.js
  src/__experimental__/components/checkable-input/checkable-input.component.js
  src/__experimental__/components/checkbox/checkbox-group.component.js
  src/__experimental__/components/checkbox/checkbox.component.js
  src/__experimental__/components/checkbox/docgenInfo.json
  src/__experimental__/components/form-field/__snapshots__/form-field.spec.js.snap
  src/__experimental__/components/form-field/form-field.component.js
  src/__experimental__/components/form-field/form-field.spec.js
  src/__experimental__/components/form-field/form-field.style.js
  src/__experimental__/components/label/label.component.js
  src/__experimental__/components/label/label.spec.js
  src/__experimental__/components/label/label.style.js
  src/__experimental__/components/radio-button/__snapshots__/radio-button-group.spec.js.snap
  src/__experimental__/components/radio-button/__snapshots__/radio-button-mapper.spec.js.snap
  src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap
  src/__experimental__/components/radio-button/docgenInfo.json
  src/__experimental__/components/radio-button/radio-button.component.js
  src/__experimental__/components/radio-button/radio-button.style.js
  src/__experimental__/components/switch/__snapshots__/switch.spec.js.snap
  src/__experimental__/components/textarea/docgenInfo.json
  src/__experimental__/components/textarea/textarea.component.js
  src/__experimental__/components/textbox/__snapshots__/textbox.spec.js.snap
  src/__experimental__/components/textbox/docgenInfo.json
  src/__experimental__/components/textbox/textbox.component.js
  src/__experimental__/components/textbox/textbox.spec.js
  src/components/button-toggle-group/button-toggle-group.component.js
  src/components/button-toggle-group/docgenInfo.json
  src/components/form/form.component.js
  src/components/form/form.d.ts
  src/components/form/form.stories.mdx
  src/components/form/form.style.js
  src/utils/helpers/options-helper/options-helper.d.ts
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3094 feat(tabs, tab): make components functional use new context api and usecontext in formfield FE-2788
  cypress/features/regression/tabs.feature
  cypress/features/regression/test/tabs.feature
  cypress/features/regression/themes/themes.feature
  cypress/fixtures/test/tabs.json
  cypress/locators/tabs/index.js
  cypress/support/helper.js
  cypress/support/step-definitions/themes-steps.js
  src/__experimental__/components/form-field/form-field.component.js
  src/__experimental__/components/form-field/form-field.spec.js
  src/components/tabs/README.md
  src/components/tabs/__definition__.js
  src/components/tabs/__internal__/tab-title/__snapshots__/tab-title.spec.js.snap
  src/components/tabs/__internal__/tab-title/index.js
  src/components/tabs/__internal__/tab-title/tab-title.component.js
  src/components/tabs/__internal__/tab-title/tab-title.spec.js
  src/components/tabs/__internal__/tab-title/tab-title.style.js
  src/components/tabs/__internal__/tab/index.d.ts
  src/components/tabs/__internal__/tab/index.js
  src/components/tabs/__internal__/tab/tab.component.js
  src/components/tabs/__internal__/tab/tab.d.ts
  src/components/tabs/__internal__/tab/tab.spec.js
  src/components/tabs/__internal__/tab/tab.style.js
  src/components/tabs/__internal__/tabs-header/__snapshots__/tabs-header.spec.js.snap
  src/components/tabs/__internal__/tabs-header/index.js
  src/components/tabs/__internal__/tabs-header/tabs-header.component.js
  src/components/tabs/__internal__/tabs-header/tabs-header.spec.js
  src/components/tabs/__internal__/tabs-header/tabs-header.style.js
  src/components/tabs/__internal__/tabs.component.js
  src/components/tabs/__internal__/tabs.d.ts
  src/components/tabs/__internal__/tabs.spec.js
  src/components/tabs/__internal__/tabs.stories.js
  src/components/tabs/__internal__/tabs.stories.mdx
  src/components/tabs/__internal__/tabs.style.js
  src/components/tabs/docgenInfo.json
  src/components/tabs/documentation/index.js
  src/components/tabs/documentation/info.js
  src/components/tabs/documentation/notes.md
  src/components/tabs/index.d.ts
  src/components/tabs/index.js
  src/components/tabs/tab-title/__snapshots__/tab-title.spec.js.snap
  src/components/tabs/tab-title/tab-title-classic.style.js
  src/components/tabs/tab-title/tab-title.component.js
  src/components/tabs/tab/__definition__.js
  src/components/tabs/tab/tab.component.js
  src/components/tabs/tabs-header/tabs-header-classic.style.js
  src/components/tabs/tabs.component.js
  src/components/tabs/tabs.spec.js
  src/components/tabs/tabs.stories.js
Labels: Passed QA, Passed UX QA, Pending Review, Squad Front End

#3109 chore: resolve major deprecated removal branch conflicts
  CHANGELOG.md
  cypress/features/regression/tabs.feature
  cypress/features/regression/test/tabs.feature
  cypress/features/regression/themes/themes.feature
  cypress/fixtures/test/tabs.json
  cypress/locators/tabs/index.js
  cypress/support/helper.js
  cypress/support/step-definitions/themes-steps.js
  package-lock.json
  package.json
  src/__experimental__/components/form-field/form-field.component.js
  src/__experimental__/components/form-field/form-field.spec.js
  src/components/tabs/README.md
  src/components/tabs/__definition__.js
  src/components/tabs/__internal__/tab-title/__snapshots__/tab-title.spec.js.snap
  src/components/tabs/__internal__/tab-title/index.js
  src/components/tabs/__internal__/tab-title/tab-title.component.js
  src/components/tabs/__internal__/tab-title/tab-title.spec.js
  src/components/tabs/__internal__/tab-title/tab-title.style.js
  src/components/tabs/__internal__/tab/index.d.ts
  src/components/tabs/__internal__/tab/index.js
  src/components/tabs/__internal__/tab/tab.component.js
  src/components/tabs/__internal__/tab/tab.d.ts
  src/components/tabs/__internal__/tab/tab.spec.js
  src/components/tabs/__internal__/tab/tab.style.js
  src/components/tabs/__internal__/tabs-header/__snapshots__/tabs-header.spec.js.snap
  src/components/tabs/__internal__/tabs-header/index.js
  src/components/tabs/__internal__/tabs-header/tabs-header.component.js
  src/components/tabs/__internal__/tabs-header/tabs-header.spec.js
  src/components/tabs/__internal__/tabs-header/tabs-header.style.js
  src/components/tabs/__internal__/tabs.component.js
  src/components/tabs/__internal__/tabs.d.ts
  src/components/tabs/__internal__/tabs.spec.js
  src/components/tabs/__internal__/tabs.stories.js
  src/components/tabs/__internal__/tabs.stories.mdx
  src/components/tabs/__internal__/tabs.style.js
  src/components/tabs/docgenInfo.json
  src/components/tabs/documentation/index.js
  src/components/tabs/documentation/info.js
  src/components/tabs/documentation/notes.md
  src/components/tabs/index.d.ts
  src/components/tabs/index.js
  src/components/tabs/tab-title/__snapshots__/tab-title.spec.js.snap
  src/components/tabs/tab-title/tab-title-classic.style.js
  src/components/tabs/tab-title/tab-title.component.js
  src/components/tabs/tab/__definition__.js
  src/components/tabs/tab/tab.component.js
  src/components/tabs/tabs-header/tabs-header-classic.style.js
  src/components/tabs/tabs.component.js
  src/components/tabs/tabs.spec.js
  src/components/tabs/tabs.stories.js
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End
