Repository Sage/carbon, pull requests merged in 2020-05, with the labels that each got.

#2907 docs(pr-template): add dls check to pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2908 docs(getting-started): add getting started guide
  README.md
  docs/getting-started.md
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2870 feat(button): add dashed button FE-2655
  cypress/features/regression/button.feature
  cypress/support/step-definitions/button-steps.js
  src/components/button/button-types.style.js
  src/components/button/button.d.ts
  src/components/button/button.spec.js
  src/components/button/button.stories.mdx
  src/style/themes/base/base-theme.config.js
  src/utils/helpers/options-helper/__spec__.js
  src/utils/helpers/options-helper/options-helper.js
Labels: Cypress, Passed QA, Passed Review, Passed UX QA, Squad Front End

#2909 test(jest): downgrade jest to 24.9.0
  package-lock.json
  package.json
  src/__spec_helper__/expect.js
  src/components/action-popover/__snapshots__/action-popover.spec.js.snap
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#2869 fix(checkbox): css styling fix for label width - Fe 2580 checkbox label
  src/__experimental__/components/checkbox/__snapshots__/checkbox-group.spec.js.snap
  src/__experimental__/components/checkbox/__snapshots__/checkbox.spec.js.snap
  src/__experimental__/components/checkbox/checkbox.style.js
  src/__experimental__/components/radio-button/__snapshots__/radio-button-group.spec.js.snap
  src/__experimental__/components/radio-button/__snapshots__/radio-button-mapper.spec.js.snap
  src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap
  src/__experimental__/components/switch/__snapshots__/switch.spec.js.snap
  src/__experimental__/components/switch/switch.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2841 fix(pager): new pager component - FE-2583
  cypress.env.json
  cypress/features/accessibility/accessibility.feature
  cypress/features/build/build.feature
  cypress/features/regression/test/pager.feature
  src/components/pager/__definition__.js
  src/components/pager/__snapshots__/pager.spec.js.snap
  src/components/pager/docgenInfo.json
  src/components/pager/documentation/Info.js
  src/components/pager/documentation/index.js
  src/components/pager/documentation/notes.md
  src/components/pager/pager-classic.styles.js
  src/components/pager/pager-navigation-link.component.js
  src/components/pager/pager-navigation.component.js
  src/components/pager/pager-navigation.spec.js
  src/components/pager/pager.component.js
  src/components/pager/pager.d.ts
  src/components/pager/pager.spec.js
  src/components/pager/pager.stories.js
  src/components/pager/pager.stories.mdx
  src/components/pager/pager.styles.js
  src/components/table/table-header/table-header.spec.js
  src/components/table/table-story-helpers/table-story-wrapper.component.js
  src/components/table/table.component.js
  src/components/table/table.spec.js
  src/style/themes/base/base-theme.config.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2912 fix(popover-container): fix displaying under other components
  src/components/popover-container/popover-container.style.js
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2911 chore: make styled-component a peer dependency
  docs/getting-started.md
  package-lock.json
  package.json
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2875 fix(inline-input): fix to input width that affects input icon - FE-2671
  cypress/features/build/build.feature
  cypress/features/regression/inlineInputs.feature
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/inline-inputs-steps.js
  src/components/inline-inputs/__definition__.js
  src/components/inline-inputs/docgenInfo.json
  src/components/inline-inputs/inline-inputs.spec.js
  src/components/inline-inputs/inline-inputs.stories.js
  src/components/inline-inputs/inline-inputs.stories.mdx
  src/components/inline-inputs/inline-inputs.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2914 feat(flat-table): add colspan and rowspan props (FE-2744)
  src/components/flat-table/__snapshots__/flat-table.spec.js.snap
  src/components/flat-table/flat-table-cell/flat-table-cell.component.d.ts
  src/components/flat-table/flat-table-cell/flat-table-cell.component.js
  src/components/flat-table/flat-table-cell/flat-table-cell.style.js
  src/components/flat-table/flat-table-header/flat-table-header.component.d.ts
  src/components/flat-table/flat-table-header/flat-table-header.component.js
  src/components/flat-table/flat-table.spec.js
  src/components/flat-table/flat-table.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2910 fix(drawer): make content overflow - FE-2783
  cypress/features/accessibility/accessibility.feature
  cypress/features/build/build.feature
  cypress/locators/drawer/locators.js
  cypress/support/step-definitions/common-steps.js
  src/components/drawer/__snapshots__/drawer.spec.js.snap
  src/components/drawer/drawer.component.js
  src/components/drawer/drawer.spec.js
  src/components/drawer/drawer.stories.mdx
  src/components/drawer/drawer.style.js
Labels: Passed QA, Passed Review, Squad Front End

#2928 ci: create cypress-parallel.yml
  .github/workflows/cypress-parallel.yml
  cypress/features/accessibility/accessibilityCommon.feature
  cypress/features/accessibility/accessibilityCommonSecondPart.feature
  cypress/features/regression/radioButtonMonthly.feature
  cypress/features/regression/radioButtonWeekly.feature
  cypress/features/regression/radioButtonYearly.feature
Labels: Cypress, Squad Front End

#2919 refactor: Add info about deprecated styleOverride - FE-2745
  src/__experimental__/components/fieldset/fieldset.component.js
  src/__experimental__/components/form-field/form-field.component.js
  src/__experimental__/components/input/input-presentation.component.js
  src/__experimental__/components/label/label.component.js
  src/__experimental__/components/radio-button/radio-button-group.component.js
  src/__experimental__/components/textbox/textbox.component.js
  src/components/accordion/accordion.component.js
  src/components/action-popover/action-popover.component.js
  src/components/anchor-navigation/anchor-navigation.component.js
  src/components/button/button.component.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2930 test(cypress): adjust to MDX examples FE-2743
  cypress.env.json
  cypress/features/accessibility/accessibilityDesignSystem.feature
  cypress/features/accessibility/accessibilityTest.feature
  cypress/features/regression/designSystem/accordion.feature
  cypress/features/regression/designSystem/advancedColorPicker.feature
  cypress/features/regression/designSystem/batchSelection.feature
  cypress/features/regression/designSystem/duellingPicklist.feature
  cypress/features/regression/designSystem/flatTable.feature
  cypress/features/regression/designSystem/numeralDate.feature
  cypress/features/regression/designSystem/popoverContainer.feature
  cypress/features/regression/designSystem/search.feature
  cypress/features/regression/drawer.feature
  cypress/features/regression/heading.feature
  cypress/features/regression/inlineInputs.feature
  cypress/features/regression/test/accordion.feature
  cypress/features/regression/test/accordionGroupedNoIFrame.feature
  cypress/features/regression/test/actionPopoverStyleOverrideNoIFrame.feature
  cypress/features/regression/test/advancedColorPickerNoIFrame.feature
  cypress/features/regression/test/anchorNavigationNoIFrame.feature
  cypress/features/regression/test/batchSelection.feature
  cypress/features/regression/test/flatTableIniFrame.feature
  cypress/features/regression/test/flatTableSortable.feature
  cypress/features/regression/test/grid.feature
  cypress/features/regression/test/numeralDate.feature
  cypress/features/regression/test/pager.feature
  cypress/features/regression/test/radioButtonGroupStyleOverrideNoIFrame.feature
  cypress/features/regression/test/search.feature
  cypress/features/regression/test/textboxStyleOverrideNoIFrame.feature
  cypress/locators/accordion/index.js
  cypress/locators/accordion/locators.js
  cypress/locators/batch-selection/index.js
  cypress/locators/batch-selection/locators.js
  cypress/locators/duelling-picklist/index.js
  cypress/locators/duelling-picklist/locators.js
  cypress/locators/flat-table/index.js
  cypress/locators/flat-table/locators.js
  cypress/locators/numeralDate/index.js
  cypress/locators/numeralDate/locators.js
  cypress/locators/popover-container/index.js
  cypress/locators/search/index.js
  cypress/locators/search/locators.js
  cypress/support/step-definitions/accordion-steps.js
  cypress/support/step-definitions/batch-selection-steps.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/duelling-picklist-steps.js
  cypress/support/step-definitions/flat-table-steps.js
  cypress/support/step-definitions/numeral-date-steps.js
  cypress/support/step-definitions/popover-container-steps.js
  cypress/support/step-definitions/search-steps.js
Labels: Cypress, Squad Front End

#2932 chore: update github config
  .github/PULL_REQUEST_TEMPLATE.md
  .github/wokflows/cypress-parallel.yml
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2935 docs: information about re-run
  cypress/README.md
Labels: Cypress, Squad Front End

#2939 ci: add specific docker container image
  .github/workflows/cypress-parallel.yml
Labels: Cypress, Squad Front End

#2926 fix(menu): add routerLink prop as no longer provided by link component
  src/components/link/link.component.js
  src/components/menu/docgenInfo.json
  src/components/menu/menu-item/__definition__.js
  src/components/menu/menu-item/__spec__.js
  src/components/menu/menu-item/docgenInfo.json
  src/components/menu/menu-item/menu-item.js
Labels: Passed QA, Passed Review, Squad Front End

#2940 test(action-popover): simplify tests
  src/__experimental__/components/decimal/decimal.spec.js
  src/components/action-popover/action-popover.spec.js
  src/components/advanced-color-picker/advanced-color-picker.spec.js
  src/components/table/table-row/table-row.spec.js
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2902 fix(search): fix height, width and background style bugs - FE 2596
  src/__experimental__/components/search/search.component.js
  src/__experimental__/components/search/search.d.ts
  src/__experimental__/components/search/search.spec.js
  src/__experimental__/components/search/search.stories.js
  src/__experimental__/components/search/search.stories.mdx
  src/__experimental__/components/search/search.style.js
Labels: Passed QA, Passed UX QA, Squad Front End

#2934 ci(applitools): integrate applitools into cypress tests
  .github/workflows/cypress-parallel.yml
  .travis.yml
  applitools.config.js
  cypress.env.json
  cypress.json
  cypress/README.md
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/accessibility/accessibilityCommonSecondPart.feature
  cypress/features/regression/accessibility/accessibilityDesignSystem.feature
  cypress/features/regression/accessibility/accessibilityExperimental.feature
  cypress/features/regression/accessibility/accessibilityTest.feature
  cypress/features/regression/themes/themes.feature
  cypress/features/visual/batchSelection.feature
  cypress/features/visual/buttonAllButtons.feature
  cypress/plugins/index.js
  cypress/support/eyes-index.d.ts
  cypress/support/helper.js
  cypress/support/index.js
  cypress/support/step-definitions/applitools-steps.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/themes-steps.js
  package-lock.json
  package.json
Labels: Cypress, Squad Front End

#2948 docs: update testing documentation
  .github/workflows/cypress-parallel.yml
  .travis.yml
  applitools.config.js
  cypress.env.json
  cypress/README.md
  cypress/features/visual/buttonAllButtons.feature
  cypress/features/visual/buttonDarkbackground.feature
  cypress/features/visual/buttonDashed.feature
  cypress/features/visual/buttonPrimary.feature
  cypress/features/visual/buttonSecondary.feature
  cypress/features/visual/buttonTertiary.feature
  cypress/support/helper.js
  cypress/support/step-definitions/themes-steps.js
  src/components/button/button.stories.js
Labels: Cypress, Squad Front End

#2943 feat(accordion): allow passing data-role prop to the root element - FE-2800
  src/components/accordion/accordion.component.js
  src/components/accordion/accordion.spec.js
Labels: Passed QA, Passed Review, Squad Front End

#2894 refactor(button): remove style override prop from component FE-2735
  cypress/support/step-definitions/action-popover-steps.js
  src/components/action-popover/__snapshots__/action-popover.spec.js.snap
  src/components/action-popover/action-popover-menu-button.component.js
  src/components/action-popover/action-popover.component.js
  src/components/action-popover/action-popover.spec.js
  src/components/action-popover/action-popover.stories.js
  src/components/action-popover/action-popover.stories.mdx
  src/components/action-popover/action-popover.style.js
  src/components/action-popover/index.js
  src/components/button/button.component.js
  src/components/button/button.d.ts
  src/components/button/button.spec.js
  src/components/button/button.stories.mdx
  src/components/button/button.style.js
Labels: No UX QA Required, Passed QA, Pending Review, Squad Front End

#2920 fix(inline-input): resolve accessibility violations - FE-2785
  src/components/inline-inputs/inline-inputs.component.js
Labels: Passed QA, Passed Review, Squad Front End

#2925 feat(flat-table-row): add new prop to apply styling when row is selected FE-2689
  src/components/batch-selection/batch-selection.component.d.ts
  src/components/batch-selection/batch-selection.component.js
  src/components/drawer/__snapshots__/drawer.spec.js.snap
  src/components/drawer/drawer.spec.js
  src/components/flat-table/__snapshots__/flat-table.spec.js.snap
  src/components/flat-table/flat-table-checkbox/__snapshots__/flat-table-checkbox.spec.js.snap
  src/components/flat-table/flat-table-checkbox/flat-table-checkbox.component.d.ts
  src/components/flat-table/flat-table-checkbox/flat-table-checkbox.component.js
  src/components/flat-table/flat-table-checkbox/flat-table-checkbox.spec.js
  src/components/flat-table/flat-table-checkbox/flat-table-checkbox.style.js
  src/components/flat-table/flat-table-checkbox/index.js
  src/components/flat-table/flat-table-head/flat-table-head.style.js
  src/components/flat-table/flat-table-row/flat-table-row.component.d.ts
  src/components/flat-table/flat-table-row/flat-table-row.component.js
  src/components/flat-table/flat-table-row/flat-table-row.spec.js
  src/components/flat-table/flat-table-row/flat-table-row.style.js
  src/components/flat-table/flat-table.spec.js
  src/components/flat-table/flat-table.stories.js
  src/components/flat-table/flat-table.stories.mdx
  src/components/flat-table/flat-table.style.js
  src/components/flat-table/index.js
  src/style/themes/base/base-theme.config.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2951 fix(button): add missing type declarations
  src/components/button/button.d.ts
  src/components/content/content.d.ts
  src/components/content/index.d.ts
  src/components/content/index.js
  src/components/content/package.json
Labels: No UX QA Required, Pending Review, Squad Front End

#2946 fix(date): allow to programatically set date as empty string - FE-2801
  src/__experimental__/components/date/date-picker.component.js
  src/__experimental__/components/date/date.component.js
  src/__experimental__/components/date/date.spec.js
  src/__experimental__/components/date/date.stories.js
Labels: Passed QA, Passed Review, Squad Front End

#2956 test: cypress vesion update
  package-lock.json
  package.json
Labels: Cypress, Squad Front End

#2949 docs: add javascript styleguide
  CONTRIBUTING.md
  docs/javascript-styleguide.md
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#2952 fix(portrait): portrait story not loading in storybook - FE-2789
  src/components/portrait/__definition__.js
  src/components/portrait/portrait-gravatar.component.js
  src/components/portrait/portrait-initials.component.js
  src/components/portrait/portrait-size.config.js
  src/components/portrait/portrait.component.js
  src/components/portrait/portrait.spec.js
  src/components/portrait/portrait.stories.js
  src/components/portrait/portrait.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2958 ci: bump cypress action version
  .github/workflows/cypress-parallel.yml
Labels: Cypress, Squad Front End

#2961 ci: update for cypress action version
  .github/workflows/cypress-parallel.yml
Labels: Cypress, Squad Front End

#2962 ci: remove firefox and safari
  applitools.config.js
Labels: Cypress, Squad Front End

#2916 fix(checkbox): update typescript definitions - FE-2681
  src/__experimental__/components/checkbox/checkbox.component.js
  src/__experimental__/components/checkbox/checkbox.d.ts
Labels: Passed QA, Passed Review, Squad Front End

#2959 fix(link): add target prop - FE-2793
  cypress/features/regression/link.feature
  cypress/support/step-definitions/link-steps.js
  src/components/link/docgenInfo.json
  src/components/link/link.component.js
  src/components/link/link.d.ts
  src/components/link/link.spec.js
  src/components/link/link.stories.js
Labels: Passed QA, Passed Review, Squad Front End

#2963 ci: remove unnecessary threads
  .github/workflows/cypress-parallel.yml
  .travis.yml
  package-lock.json
  package.json
Labels: Cypress, Squad Front End

#2906 fix(toast): enable toast stacking - FE-2670
  cypress/features/regression/accessibility/accessibilityCommonSecondPart.feature
  cypress/features/regression/accessibility/accessibilityDesignSystem.feature
  cypress/features/regression/designSystem/toast.feature
  cypress/features/regression/test/toast.feature
  cypress/features/regression/toast.feature
  cypress/features/visual/toast.feature
  cypress/locators/toast/index.js
  cypress/support/step-definitions/toast-steps.js
  src/components/portal/__snapshots__/__spec__.js.snap
  src/components/portal/__spec__.js
  src/components/portal/portal.js
  src/components/toast/README.md
  src/components/toast/__definition__.js
  src/components/toast/docgenInfo.json
  src/components/toast/documentation/index.js
  src/components/toast/documentation/info.js
  src/components/toast/documentation/notes.md
  src/components/toast/toast.component.js
  src/components/toast/toast.d.ts
  src/components/toast/toast.spec.js
  src/components/toast/toast.stories.js
  src/components/toast/toast.stories.mdx
  src/components/toast/toast.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2937 fix(drawer): update overflow behaviour - FE-2795
  cypress.env.json
  cypress/features/regression/accessibility/accessibilityDesignSystem.feature
  cypress/features/visual/drawer.feature
  cypress/support/step-definitions/common-steps.js
  src/components/drawer/__snapshots__/drawer.spec.js.snap
  src/components/drawer/drawer.component.js
  src/components/drawer/drawer.spec.js
  src/components/drawer/drawer.stories.js
  src/components/drawer/drawer.stories.mdx
  src/components/drawer/drawer.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2964 chore(fonts): add missing font faces for supported font weights FE-2821
  .storybook/assets/fonts/Lato-Black.eot
  .storybook/assets/fonts/Lato-Black.svg
  .storybook/assets/fonts/Lato-Black.ttf
  .storybook/assets/fonts/Lato-Black.woff
  .storybook/assets/fonts/Lato-Black.woff2
  .storybook/assets/fonts/Lato-BlackItalic.eot
  .storybook/assets/fonts/Lato-BlackItalic.svg
  .storybook/assets/fonts/Lato-BlackItalic.ttf
  .storybook/assets/fonts/Lato-BlackItalic.woff
  .storybook/assets/fonts/Lato-BlackItalic.woff2
  .storybook/assets/fonts/Lato-Bold.eot
  .storybook/assets/fonts/Lato-Bold.svg
  .storybook/assets/fonts/Lato-Bold.ttf
  .storybook/assets/fonts/Lato-Bold.woff
  .storybook/assets/fonts/Lato-Bold.woff2
  .storybook/assets/fonts/Lato-BoldItalic.eot
  .storybook/assets/fonts/Lato-BoldItalic.svg
  .storybook/assets/fonts/Lato-BoldItalic.ttf
  .storybook/assets/fonts/Lato-BoldItalic.woff
  .storybook/assets/fonts/Lato-BoldItalic.woff2
  .storybook/assets/fonts/Lato-Italic.eot
  .storybook/assets/fonts/Lato-Italic.svg
  .storybook/assets/fonts/Lato-Italic.ttf
  .storybook/assets/fonts/Lato-Italic.woff
  .storybook/assets/fonts/Lato-Italic.woff2
  .storybook/assets/fonts/Lato-Regular.eot
  .storybook/assets/fonts/Lato-Regular.svg
  .storybook/assets/fonts/Lato-Regular.ttf
  .storybook/assets/fonts/Lato-Regular.woff
  .storybook/assets/fonts/Lato-Regular.woff2
  .storybook/style/story-root.scss
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End
