Repository Sage/carbon, pull requests merged in 2020-03, with the labels that each got.

#2680 fix(checkbox): restore proper checkbox behaviour in validations story - FE-2579
  src/__experimental__/components/checkbox/checkbox.stories.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2687 ci(docker-compose-cypress): update script for run application
  cypress/README.md
  docker-compose-cypress.yml
Labels: Cypress, Squad Front End

#2688 docs: update ga id
  .storybook/manager.js
  .storybook/preview.js
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#2689 test: fix jsdom related console warnings (FE-2490)
  src/__deprecated__/components/form/form.spec.js
  src/__experimental__/components/form/form.spec.js
  src/utils/router/__spec__.js
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2679 fix(storybook): enable theme selector on Windows (FE-2573)
  .storybook/main.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2696 docs: remove old docs [skip ci]
  docs/guides/assets.md
  docs/guides/decorators.md
  docs/guides/getting-started.md
  docs/guides/immutable.md
  docs/guides/installing-unreleased-changes.md
  docs/guides/integrating-with-other-ui.md
  docs/guides/releasing.md
  docs/guides/services.md
  docs/guides/setting-up-your-environment.md
  docs/guides/storybook.md
  docs/guides/validations.md
  docs/styleguides/css/README.md
  docs/styleguides/react/README.md
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#2654 feat(flat-table): Keyboard Accessibility (FE-2456)
  cypress/features/regression/test/flatTableIniFrame.feature
  cypress/features/regression/test/flatTableNoiFrame.feature
  cypress/locators/flat-table/index.js
  cypress/locators/flat-table/locators.js
  cypress/support/helper.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/flat-table-steps.js
  src/components/flat-table/__snapshots__/flat-table.spec.js.snap
  src/components/flat-table/documentation/index.js
  src/components/flat-table/documentation/info.js
  src/components/flat-table/documentation/notes.md
  src/components/flat-table/flat-table-body/flat-table-body.component.d.ts
  src/components/flat-table/flat-table-body/flat-table-body.component.js
  src/components/flat-table/flat-table-cell/flat-table-cell.component.d.ts
  src/components/flat-table/flat-table-cell/flat-table-cell.component.js
  src/components/flat-table/flat-table-head/flat-table-head.component.d.ts
  src/components/flat-table/flat-table-head/flat-table-head.style.js
  src/components/flat-table/flat-table-header/flat-table-header.component.d.ts
  src/components/flat-table/flat-table-header/flat-table-header.component.js
  src/components/flat-table/flat-table-row-header/flat-table-row-header.component.d.ts
  src/components/flat-table/flat-table-row-header/flat-table-row-header.component.js
  src/components/flat-table/flat-table-row/__snapshots__/flat-table-row.spec.js.snap
  src/components/flat-table/flat-table-row/flat-table-row.component.d.ts
  src/components/flat-table/flat-table-row/flat-table-row.component.js
  src/components/flat-table/flat-table-row/flat-table-row.spec.js
  src/components/flat-table/flat-table-row/flat-table-row.style.js
  src/components/flat-table/flat-table.component.d.ts
  src/components/flat-table/flat-table.spec.js
  src/components/flat-table/flat-table.stories.js
  src/components/flat-table/flat-table.stories.mdx
  src/components/flat-table/flat-table.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2678 docs(button-toggle-group): update story to use csf
  cypress/features/accessibility/accessibility.feature
  cypress/features/build/build.feature
  cypress/features/build/buildClassic.feature
  cypress/features/regression/test/buttonToggleGroup.feature
  cypress/locators/button-toggle-group/index.js
  cypress/support/step-definitions/button-toggle-group-steps.js
  package-lock.json
  src/components/button-toggle-group/button-toggle-group.stories.js
Labels: No UX QA Required, Passed Review, Pending QA, Squad Front End

#2686 test(table-row, table-cell, table-header): fix `validationDOMNesting` error log - FE-2493
  src/components/table/table-cell/table-cell.spec.js
  src/components/table/table-header/table-header.spec.js
  src/components/table/table-row/table-row.spec.js
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2648 test(buttontoggle, buttontogglegroup, carousel): add missing tests and default feature
  cypress/features/build/build.feature
  cypress/features/regression/buttonToggle.feature
  cypress/features/regression/buttonToggleClassic.feature
  cypress/features/regression/carousel.feature
  cypress/features/regression/carouselClassic.feature
  cypress/features/regression/test/buttonToggleGroup.feature
  cypress/features/regression/test/buttonToggleGroupClassic.feature
  cypress/locators/button-toggle-group/index.js
  cypress/locators/carousel/index.js
  cypress/locators/carousel/locators.js
  cypress/support/step-definitions/button-toggle-group-steps.js
  cypress/support/step-definitions/button-toggle-steps.js
  cypress/support/step-definitions/carousel-steps.js
  src/components/button-toggle-group/button-toggle-group.stories.js
Labels: Cypress, Pending Review, Squad Front End

#2701 chore(stale): adds configuration for github stale app
  .github/stale.yml
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#2706 docs(readme): remove broken links to guides fixes #2704
  README.md
Labels: No QA Required, No UX QA Required, Passed Review, Pending Review, Squad Front End

#2708 refactor(icon-button, message): position update - FE-2606
  src/components/icon-button/icon-button.style.js
  src/components/message/__snapshots__/message.spec.js.snap
  src/components/message/message.style.js
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2707 test(showeditpod): fix for regression FE-2605
  cypress/features/regression/showEditPod.feature
  cypress/features/regression/showEditPodClassic.feature
  cypress/locators/show-edit-pod/index.js
  cypress/locators/show-edit-pod/locators.js
  cypress/support/step-definitions/show-edit-pod-steps.js
Labels: Cypress, Squad Front End

#2690 fix(dialog): close button styling
  cypress/features/regression/dialog.feature
  cypress/features/regression/dialogClassic.feature
  cypress/features/regression/message.feature
  cypress/locators/confirm/locators.js
  cypress/locators/locators.js
  cypress/support/step-definitions/common-steps.js
  src/components/dialog/__snapshots__/dialog.spec.js.snap
  src/components/dialog/dialog.component.js
  src/components/dialog/dialog.spec.js
  src/components/dialog/dialog.style.js
  src/components/icon/icon.spec.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2709 test(draggable): cypress tests
  cypress/features/accessibility/accessibility.feature
  cypress/features/build/build.feature
  cypress/features/regression/test/draggableNoIFrame.feature
  cypress/features/regression/test/search.feature
  cypress/locators/draggable/index.js
  cypress/locators/draggable/locators.js
  cypress/support/helper.js
  cypress/support/step-definitions/draggable-steps.js
Labels: Cypress, Squad Front End

#2710 test: add missing tests for accessibility suite
  cypress/features/accessibility/accessibility.feature
Labels: Cypress, Squad Front End

#2659 feat(draggable): add new component - FE-2499
  cypress/features/accessibility/accessibility.feature
  cypress/features/build/build.feature
  cypress/features/regression/test/draggableNoIFrame.feature
  cypress/features/regression/test/search.feature
  cypress/locators/draggable/index.js
  cypress/locators/draggable/locators.js
  cypress/support/helper.js
  cypress/support/step-definitions/draggable-steps.js
  package-lock.json
  package.json
  src/components/drag-and-drop/custom-drag-layer/custom-drag-layer.js
  src/components/drag-and-drop/draggable-context/draggable-context.js
  src/components/drag-and-drop/with-drag/__spec__.js
  src/components/drag-and-drop/with-drag/with-drag.js
  src/components/drag-and-drop/with-drop/__spec__.js
  src/components/drag-and-drop/with-drop/with-drop.js
  src/components/draggable/draggable-container.component.js
  src/components/draggable/draggable-container.d.ts
  src/components/draggable/draggable-item.component.js
  src/components/draggable/draggable-item.d.ts
  src/components/draggable/draggable-item.style.js
  src/components/draggable/draggable.spec.js
  src/components/draggable/draggable.stories.js
  src/components/draggable/draggable.stories.mdx
  src/components/draggable/index.js
  src/style/themes/base/base-theme.config.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2672 feat(radio-button): add support for inline radio buttons
  cypress/features/regression/experimental/radioButtonGroup.feature
  cypress/features/regression/experimental/radioButtonGroupClassic.feature
  cypress/locators/radioButton/index.js
  cypress/locators/radioButton/locators.js
  cypress/support/step-definitions/radio-button-steps.js
  src/__experimental__/components/fieldset/__snapshots__/fieldset.spec.js.snap
  src/__experimental__/components/fieldset/docgenInfo.json
  src/__experimental__/components/fieldset/fieldset.component.js
  src/__experimental__/components/fieldset/fieldset.spec.js
  src/__experimental__/components/fieldset/fieldset.style.js
  src/__experimental__/components/radio-button/__snapshots__/radio-button-group.spec.js.snap
  src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap
  src/__experimental__/components/radio-button/docgenInfo.json
  src/__experimental__/components/radio-button/radio-button-group.component.js
  src/__experimental__/components/radio-button/radio-button-group.spec.js
  src/__experimental__/components/radio-button/radio-button-group.style.js
  src/__experimental__/components/radio-button/radio-button.spec.js
  src/__experimental__/components/radio-button/radio-button.stories.js
  src/__experimental__/components/radio-button/radio-button.style.js
  src/__experimental__/components/simple-color-picker/__snapshots__/simple-color-picker.spec.js.snap
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2691 fix(dialog-full-screen): close button styling
  cypress/features/regression/dialogFullScreen.feature
  src/components/dialog-full-screen/dialog-full-screen.component.js
  src/components/dialog-full-screen/dialog-full-screen.spec.js
  src/components/dialog-full-screen/dialog-full-screen.stories.js
  src/components/dialog-full-screen/dialog-full-screen.style.js
  src/components/dialog-full-screen/icon-classic.style.js
  src/components/dialog-full-screen/icon.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2711 chore: package-lock update for npm install
  package-lock.json
Labels: Passed Review, Squad Front End

#2660 feat: add new anchor navigation component - FE-2335
  cypress.env.json
  cypress/features/accessibility/accessibility.feature
  cypress/features/build/build.feature
  cypress/features/regression/test/anchorNavigation.feature
  cypress/locators/anchor-navigation/index.js
  cypress/locators/anchor-navigation/locators.js
  cypress/locators/index.js
  cypress/support/helper.js
  cypress/support/step-definitions/anchor-navigation-steps.js
  cypress/support/step-definitions/common-steps.js
  src/components/anchor-navigation/anchor-navigation-item.component.js
  src/components/anchor-navigation/anchor-navigation-item.d.ts
  src/components/anchor-navigation/anchor-navigation.component.js
  src/components/anchor-navigation/anchor-navigation.d.ts
  src/components/anchor-navigation/anchor-navigation.spec.js
  src/components/anchor-navigation/anchor-navigation.stories.js
  src/components/anchor-navigation/anchor-navigation.stories.mdx
  src/components/anchor-navigation/anchor-navigation.style.js
  src/components/anchor-navigation/anchor-section-divider.component.js
  src/components/anchor-navigation/anchor-section-divider.d.ts
  src/components/anchor-navigation/index.d.ts
  src/components/anchor-navigation/index.js
  src/style/themes/base/base-theme.config.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2714 ci(travis): only build on master branch
  .travis.yml
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2612 feat: add new Popover Container FE-2500
  cypress/features/accessibility/accessibility.feature
  cypress/features/build/build.feature
  cypress/features/regression/test/popoverContainer.feature
  cypress/locators/popover-container/index.js
  cypress/locators/popover-container/locators.js
  cypress/support/step-definitions/popover-container-steps.js
  src/components/icon-button/icon-button.component.js
  src/components/icon-button/icon-button.style.js
  src/components/message/message.style.js
  src/components/popover-container/index.js
  src/components/popover-container/popover-container.component.js
  src/components/popover-container/popover-container.d.ts
  src/components/popover-container/popover-container.spec.js
  src/components/popover-container/popover-container.stories.js
  src/components/popover-container/popover-container.stories.mdx
  src/components/popover-container/popover-container.style.js
  src/style/themes/base/base-theme.config.js
  src/utils/helpers/events/__spec__.js
  src/utils/helpers/events/events.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2713 feat(button): add destructive prop FE-2615
  .storybook/welcome-page/components-demo/demo/demo.component.js
  src/components/button/button-types.style.js
  src/components/button/button.component.js
  src/components/button/button.spec.js
  src/components/button/button.stories.js
  src/components/button/button.stories.mdx
  src/components/button/button.style.js
  src/components/button/documentation/info.js
  src/utils/helpers/options-helper/__spec__.js
  src/utils/helpers/options-helper/options-helper.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2715 chore: remove carbon factory dependency
  package-lock.json
  package.json
  webpack.config.js
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#2716 chore: remove cdn font import and add local font for storybook
  .storybook/assets/fonts/Lato-Regular.eot
  .storybook/assets/fonts/Lato-Regular.svg
  .storybook/assets/fonts/Lato-Regular.ttf
  .storybook/assets/fonts/Lato-Regular.woff
  .storybook/assets/fonts/OFL.txt
  .storybook/main.js
  .storybook/style/story-root.scss
  README.md
  src/utils/css/modules/text-styles.scss
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2717 docs(storybook): load lato from cdn and remove url loader
  .storybook/main.js
  .storybook/style/story-root.scss
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2703 ci(dockerfile): update for Dockerfile-cypress
  Dockerfile-cypress
  cypress.json
  cypress/features/regression/alert.feature
  cypress/features/regression/button.feature
  cypress/features/regression/buttonAsSibling.feature
  cypress/features/regression/buttonAsSiblingClassic.feature
  cypress/features/regression/buttonClassic.feature
  cypress/features/regression/card.feature
  cypress/features/regression/create.feature
  cypress/features/regression/createClassic.feature
  cypress/features/regression/dialog.feature
  cypress/features/regression/experimental/textarea.feature
  cypress/features/regression/loader.feature
  cypress/features/regression/message.feature
  cypress/features/regression/pages.feature
  cypress/features/regression/pod.feature
  cypress/features/regression/validations/checkboxValidations.feature
  cypress/features/regression/validations/checkboxValidationsClassic.feature
  cypress/features/regression/validations/radioButtonValidations..feature
  cypress/features/regression/validations/radioButtonValidationsClassic.feature
  cypress/features/regression/validations/switchValidations.feature
  cypress/features/regression/validations/switchValidationsClassic.feature
  cypress/plugins/index.js
  cypress/support/index.js
  cypress/support/step-definitions/textbox-steps.js
  package-lock.json
  package.json
  script/docker/README.md
  script/docker/cypress.sh
Labels: Cypress, Squad Front End

#2692 fix(toast): close button styling
  cypress/features/regression/toast.feature
  cypress/features/regression/toastClassic.feature
  src/components/toast/toast.component.js
  src/components/toast/toast.spec.js
  src/components/toast/toast.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2720 test(menulist, message): minor changes related to BDD steps FE-2352
  cypress/features/regression/alert.feature
  cypress/features/regression/alertClassic.feature
  cypress/features/regression/dialog.feature
  cypress/features/regression/dialogClassic.feature
  cypress/features/regression/dialogFullScreen.feature
  cypress/features/regression/menu.feature
  cypress/features/regression/menuList.feature
  cypress/features/regression/message.feature
  cypress/support/step-definitions/common-steps.js
Labels: Cypress, Squad Front End

#2669 fix(multi-action-button): change button text position (FE-2081)
  src/components/multi-action-button/__snapshots__/multi-action-button.spec.js.snap
  src/components/multi-action-button/multi-action-button-classic.style.js
  src/components/multi-action-button/multi-action-button.component.js
  src/components/multi-action-button/multi-action-button.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2721 test: add new tests for help component
  cypress/features/regression/help.feature
  cypress/features/regression/helpClassic.feature
  cypress/support/step-definitions/help-steps.js
Labels: Cypress, Squad Front End

#2685 feat(simple-color-picker): keyboard accessbility, up and down navigation - FE-2578
  cypress/features/regression/actionPopoverIFrame.feature
  cypress/features/regression/experimental/simpleColorPicker.feature
  cypress/fixtures/simpleColorPicker.json
  cypress/fixtures/simpleColorPickerNew.json
  cypress/locators/simple-color-picker/index.js
  cypress/locators/simple-color-picker/locators.js
  cypress/support/step-definitions/action-popover-steps.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/simple-color-picker-steps.js
  src/__experimental__/components/radio-button/radio-button-mapper.component.js
  src/__experimental__/components/simple-color-picker/__snapshots__/simple-color-picker.spec.js.snap
  src/__experimental__/components/simple-color-picker/simple-color-picker.component.js
  src/__experimental__/components/simple-color-picker/simple-color-picker.spec.js
  src/__experimental__/components/simple-color-picker/simple-color-picker.stories.js
  src/__experimental__/components/simple-color-picker/simple-color-picker.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2693 fix(sidebar): close button styling
  cypress/features/regression/sidebar.feature
  src/components/sidebar/sidebar-classic.style.js
  src/components/sidebar/sidebar.component.js
  src/components/sidebar/sidebar.spec.js
  src/components/sidebar/sidebar.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2694 fix(alert): close button styling
  cypress/features/regression/alert.feature
  cypress/features/regression/alertClassic.feature
  src/components/alert/alert.component.js
  src/components/alert/alert.spec.js
  src/components/alert/alert.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2726 feat(switch): add i18n support
  src/__experimental__/components/switch/documentation/notes.md
  src/__experimental__/components/switch/switch-slider.component.js
  src/__experimental__/components/switch/switch.spec.js
  src/__experimental__/components/switch/switch.stories.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2723 fix(fonts): add support for consumer adding font
  .storybook/style/story-root.scss
  README.md
  src/components/button/button.style.js
  src/utils/css/modules/base-text.scss
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2724 fix(icon-button): remove firefox focus-inner border FE-2622
  src/components/icon-button/icon-button.style.js
  src/components/message/__snapshots__/message.spec.js.snap
  src/components/message/message.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2668 feat(grid): add responsive grid component
  cypress/features/accessibility/accessibility.feature
  cypress/features/build/build.feature
  cypress/features/regression/test/grid.feature
  cypress/locators/grid/index.js
  cypress/locators/grid/locators.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/grid-steps.js
  src/components/grid/__snapshots__/grid.spec.js.snap
  src/components/grid/grid-container/grid-container.component.js
  src/components/grid/grid-container/grid-container.style.js
  src/components/grid/grid-container/index.d.ts
  src/components/grid/grid-container/index.js
  src/components/grid/grid-item/grid-item.component.js
  src/components/grid/grid-item/grid-item.style.js
  src/components/grid/grid-item/index.d.ts
  src/components/grid/grid-item/index.js
  src/components/grid/grid.spec.js
  src/components/grid/grid.stories.js
  src/components/grid/grid.stories.mdx
  src/components/grid/index.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2719 docs(rfc): remove classic theme
  rfcs/text/remove-classic.md
Labels: Final Comments, RFC, Squad Front End

#2712 feat: add new BatchSelection component (FE-2457)
  cypress/features/accessibility/accessibility.feature
  cypress/features/build/build.feature
  cypress/features/regression/test/batchSelection.feature
  cypress/locators/batch-selection/index.js
  cypress/locators/batch-selection/locators.js
  cypress/support/step-definitions/batch-selection-steps.js
  src/components/batch-selection/__snapshots__/batch-selection.spec.js.snap
  src/components/batch-selection/batch-selection.component.d.ts
  src/components/batch-selection/batch-selection.component.js
  src/components/batch-selection/batch-selection.spec.js
  src/components/batch-selection/batch-selection.stories.js
  src/components/batch-selection/batch-selection.stories.mdx
  src/components/batch-selection/batch-selection.style.js
  src/components/batch-selection/index.js
  src/style/themes/base/base-theme.config.js
  src/utils/helpers/options-helper/options-helper.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2729 feat(icon): add icons
  cypress/features/regression/button.feature
  cypress/features/regression/buttonAsSibling.feature
  cypress/features/regression/buttonAsSiblingIconPart1.feature
  cypress/features/regression/buttonAsSiblingIconPart2.feature
  cypress/features/regression/buttonIconPart1.feature
  cypress/features/regression/buttonIconPart2.feature
  cypress/features/regression/buttonToggle.feature
  cypress/features/regression/buttonToggleChangeIconPart1.feature
  cypress/features/regression/buttonToggleChangeIconPart2.feature
  cypress/features/regression/detail.feature
  cypress/features/regression/detailIconTypePart1.feature
  cypress/features/regression/detailIconTypePart2.feature
  cypress/features/regression/iconClassic.feature
  cypress/features/regression/iconTypePart1.feature
  cypress/features/regression/iconTypePart2.feature
  cypress/features/regression/link.feature
  cypress/features/regression/linkIconTypePart1.feature
  cypress/features/regression/linkIconTypePart2.feature
  cypress/support/step-definitions/button-steps.js
  cypress/support/step-definitions/button-toggle-steps.js
  cypress/support/step-definitions/detail-steps.js
  cypress/support/step-definitions/link-steps.js
  src/components/icon/fonts/carbon-icons-webfont.woff
  src/components/icon/icon-unicodes.js
  src/style/fonts/carbon-icons-webfont.woff
  src/utils/helpers/options-helper/__spec__.js
  src/utils/helpers/options-helper/options-helper.d.ts
  src/utils/helpers/options-helper/options-helper.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2740 test: remove unnecesary viewport in beforeEach
  cypress/support/step-definitions/anchor-navigation-steps.js
  cypress/support/step-definitions/simple-color-picker-steps.js
Labels: Cypress, Squad Front End

#2727 fix(pill): close button styling - FE-2623
  src/components/pill/pill.component.js
  src/components/pill/pill.spec.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2741 docs(search): update id path for search story docs
  src/__experimental__/components/search/search.stories.mdx
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2619 feat(action-popover): add support for popover items to have a submenu
  .storybook/docs-helpers/components/iframe-wrapper/iframe-wrapper.style.js
  .storybook/docs-helpers/components/iframe-wrapper/index.js
  cypress/features/build/build.feature
  cypress/features/build/buildClassic.feature
  cypress/features/regression/actionPopoverEvents.feature
  cypress/features/regression/actionPopoverIFrame.feature
  cypress/features/regression/actionPopoverIFrameClassic.feature
  cypress/features/regression/test/actionPopoverEventsInIFrame.feature
  cypress/features/regression/test/actionPopoverNoIFrame.feature
  cypress/locators/action-popover/index.js
  cypress/locators/action-popover/locators.js
  cypress/support/step-definitions/action-popover-steps.js
  cypress/support/step-definitions/common-steps.js
  src/__experimental__/components/date/date-picker.component.js
  src/components/action-popover/__snapshots__/action-popover.spec.js.snap
  src/components/action-popover/action-popover-classic.style.js
  src/components/action-popover/action-popover-item.component.js
  src/components/action-popover/action-popover-item.d.ts
  src/components/action-popover/action-popover-menu.component.js
  src/components/action-popover/action-popover-menu.d.ts
  src/components/action-popover/action-popover.component.js
  src/components/action-popover/action-popover.spec.js
  src/components/action-popover/action-popover.stories.js
  src/components/action-popover/action-popover.stories.mdx
  src/components/action-popover/action-popover.style.js
  src/components/action-popover/docgenInfo.json
  src/components/action-popover/documentation/index.js
  src/components/action-popover/documentation/info.js
  src/components/action-popover/documentation/notes.md
  src/components/action-popover/index.d.ts
  src/style/themes/classic/classic-theme.config.js
Labels: Failed QA, Passed Review, Passed UX QA, Pending QA, Squad Front End

#2725 feat(duelling-picklist): create duelling-picklist component - FE-2483
  cypress/features/accessibility/accessibility.feature
  cypress/features/build/build.feature
  cypress/features/regression/test/duellingPicklistNoIFrame.feature
  cypress/locators/checkbox/index.js
  cypress/locators/duelling-picklist/index.js
  cypress/locators/duelling-picklist/locators.js
  cypress/locators/search/index.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/duelling-picklist-steps.js
  cypress/support/step-definitions/search-steps.js
  src/components/duelling-picklist/duelling-picklist.component.js
  src/components/duelling-picklist/duelling-picklist.d.ts
  src/components/duelling-picklist/duelling-picklist.spec.js
  src/components/duelling-picklist/duelling-picklist.stories.js
  src/components/duelling-picklist/duelling-picklist.stories.mdx
  src/components/duelling-picklist/duelling-picklist.style.js
  src/components/duelling-picklist/index.d.ts
  src/components/duelling-picklist/index.js
  src/components/duelling-picklist/picklist-divider.component.js
  src/components/duelling-picklist/picklist-divider.d.ts
  src/components/duelling-picklist/picklist-item.component.js
  src/components/duelling-picklist/picklist-item.d.ts
  src/components/duelling-picklist/picklist-placeholder.component.js
  src/components/duelling-picklist/picklist-placeholder.d.ts
  src/components/duelling-picklist/picklist.component.js
  src/components/duelling-picklist/picklist.d.ts
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2728 feat(badge): add new component - FE-2627
  cypress/features/accessibility/accessibility.feature
  cypress/features/build/build.feature
  cypress/features/regression/test/badge.feature
  cypress/locators/badge/index.js
  cypress/locators/badge/locators.js
  cypress/support/step-definitions/badge-steps.js
  src/components/badge/badge.component.js
  src/components/badge/badge.d.ts
  src/components/badge/badge.spec.js
  src/components/badge/badge.stories.js
  src/components/badge/badge.stories.mdx
  src/components/badge/badge.style.js
  src/components/badge/index.d.ts
  src/components/badge/index.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2735 fix(select): resolved error when only one option child is set - FE-2547
  src/__experimental__/components/select/select.component.js
  src/__experimental__/components/select/select.spec.js
Labels: Passed QA, Passed Review, Squad Front End

#2731 feat(select): add transparent variant (FE-2630)
  cypress/features/regression/experimental/select.feature
  cypress/support/step-definitions/select-steps.js
  src/__experimental__/components/select/select.component.js
  src/__experimental__/components/select/select.spec.js
  src/__experimental__/components/select/select.stories.js
  src/__experimental__/components/select/select.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2739 feat(textbox): add override styles functionality (FE-2631)
  cypress.env.json
  cypress/features/regression/test/textboxStyleOverrideNoIFrame.feature
  cypress/locators/index.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/textbox-steps.js
  src/__experimental__/components/form-field/form-field.component.js
  src/__experimental__/components/form-field/form-field.style.js
  src/__experimental__/components/input/input-presentation.component.js
  src/__experimental__/components/input/input-presentation.style.js
  src/__experimental__/components/input/input.style.js
  src/__experimental__/components/label/label.component.js
  src/__experimental__/components/label/label.d.ts
  src/__experimental__/components/label/label.style.js
  src/__experimental__/components/textbox/__snapshots__/textbox.spec.js.snap
  src/__experimental__/components/textbox/textbox.component.js
  src/__experimental__/components/textbox/textbox.spec.js
  src/__experimental__/components/textbox/textbox.stories.mdx
Labels: Passed QA, Passed Review, Squad Front End

#2746 feat(simple-color-picker): adds transparent color - FE-2645
  cypress/fixtures/simpleColorPicker.json
  cypress/fixtures/simpleColorPickerNew.json
  src/__experimental__/components/simple-color-picker/color-sample-box/color-sample-box.component.js
  src/__experimental__/components/simple-color-picker/color-sample-box/color-sample-box.spec.js
  src/__experimental__/components/simple-color-picker/color-sample-box/color-sample-box.style.js
  src/__experimental__/components/simple-color-picker/simple-color-picker.stories.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2747 test(mountinapp, multiactionbutton,navigationbar): add cyress tests FE-2353
  cypress/features/regression/mountInApp.feature
  cypress/features/regression/multiActionButton.feature
  cypress/features/regression/multiActionButtonClassic.feature
  cypress/features/regression/navigationBar.feature
  cypress/locators/multi-action-button/index.js
  cypress/locators/multi-action-button/locators.js
  cypress/locators/table/index.js
  cypress/support/step-definitions/multi-action-button-steps.js
Labels: Cypress, Squad Front End

#2751 test: remove all classic test (except deprecated)
  cypress.env.json
  cypress/README.md
  cypress/features/accessibility/accessibility.feature
  cypress/features/build/buildClassic.feature
  cypress/features/regression/button.feature
  cypress/features/regression/buttonAsSibling.feature
  cypress/features/regression/buttonAsSiblingClassic.feature
  cypress/features/regression/buttonClassic.feature
  cypress/features/regression/buttonToggleClassic.feature
  cypress/features/regression/carouselClassic.feature
  cypress/features/regression/createClassic.feature
  cypress/features/regression/dialogClassic.feature
  cypress/features/regression/experimental/checkboxClassic.feature
  cypress/features/regression/experimental/dateInputClassic.feature
  cypress/features/regression/experimental/dateRangeClassic.feature
  cypress/features/regression/experimental/decimalInputClassic.feature
  cypress/features/regression/experimental/fieldsetClassic.feature
  cypress/features/regression/experimental/formClassic.feature
  cypress/features/regression/experimental/groupedCharacterClassic.feature
  cypress/features/regression/experimental/numberInputClassic.feature
  cypress/features/regression/experimental/radioButtonGroupClassic.feature
  cypress/features/regression/experimental/selectClassic.feature
  cypress/features/regression/experimental/textareaClassic.feature
  cypress/features/regression/experimental/textboxClassic.feature
  cypress/features/regression/flashClassic.feature
  cypress/features/regression/helpClassic.feature
  cypress/features/regression/iconClassic.feature
  cypress/features/regression/pagerClassic.feature
  cypress/features/regression/pillClassic.feature
  cypress/features/regression/showEditPodClassic.feature
  cypress/features/regression/splitButtonClassic.feature
  cypress/features/regression/tableAjaxClassic.feature
  cypress/features/regression/tableClassic.feature
  cypress/features/regression/tabsClassic.feature
  cypress/features/regression/test/buttonToggleGroupClassic.feature
  cypress/features/regression/toast.feature
  cypress/features/regression/toastClassic.feature
  cypress/features/regression/validations/checkboxValidationsClassic.feature
  cypress/features/regression/validations/dateInputValidationsClassic.feature
  cypress/features/regression/validations/radioButtonValidationsClassic.feature
  cypress/features/regression/validations/selectValidationClassic.feature
  cypress/features/regression/validations/switchValidationsClassic.feature
  cypress/features/regression/validations/textareaValidationsClassic.feature
  cypress/features/regression/validations/textboxValidationsClassic.feature
  cypress/features/regression/validations/validationsBasicClassic.feature
  cypress/features/regression/validations/validationsTextboxBasedClassic.feature
  cypress/locators/carousel/index.js
  cypress/locators/carousel/locators.js
  cypress/support/step-definitions/carousel-steps.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/configurable-items-steps.js
  cypress/support/step-definitions/numner-input-steps.js
  cypress/support/step-definitions/pager-steps.js
  cypress/support/step-definitions/pages-steps.js
  cypress/support/step-definitions/show-edit-pod-steps.js
  cypress/support/step-definitions/split-button-steps.js
  cypress/support/step-definitions/text-area-steps.js
  cypress/support/step-definitions/textbox-steps.js
  package.json
Labels: Cypress, Squad Front End

#2742 chore(button): drop classic support FE-2629
  src/components/button/README.md
  src/components/button/__definition__.js
  src/components/button/__snapshots__/button.spec.js.snap
  src/components/button/button-classic.style.js
  src/components/button/button.component.js
  src/components/button/button.d.ts
  src/components/button/button.spec.js
  src/components/button/button.stories.js
  src/components/button/button.stories.mdx
  src/components/button/button.style.js
  src/components/button/documentation/index.js
  src/components/button/documentation/info-classic.js
  src/components/multi-action-button/__snapshots__/multi-action-button.spec.js.snap
  src/components/multi-action-button/multi-action-button-classic.style.js
  src/components/multi-action-button/multi-action-button.spec.js
  src/components/multi-action-button/multi-action-button.stories.js
  src/components/multi-action-button/multi-action-button.style.js
  src/components/split-button/__snapshots__/split-button.spec.js.snap
  src/components/split-button/split-button-children.style.js
  src/components/split-button/split-button-classic.style.js
  src/components/split-button/split-button-toggle.style.js
  src/components/split-button/split-button.spec.js
  src/components/split-button/split-button.stories.js
  src/components/split-button/split-button.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2749 chore(button): remove destructive button type
  cypress/features/regression/button.feature
  cypress/features/regression/buttonAsSibling.feature
  src/components/button/button.component.js
  src/components/button/button.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2752 feat(button): add destructive secondary buttons FE-2553
  src/components/button/button-types.style.js
  src/components/button/button.spec.js
  src/components/button/button.stories.mdx
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2753 docs(fieldset): add address fieldset examples (FE-2633)
  src/__experimental__/components/fieldset/fieldset-examples.stories.mdx
Labels: No QA Required, Passed Review, Passed UX QA, Squad Front End

#2758 ci: add codesandbox configuration
  .codesandbox/ci.json
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#2757 fix(icon-button): hover background over focus outline (FE-2634)
  src/components/batch-selection/__snapshots__/batch-selection.spec.js.snap
  src/components/icon-button/icon-button.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2756 fix(input): add null check to input focus handler
  src/__experimental__/components/input/input.component.js
  src/__experimental__/components/input/input.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End, Squad X3

#2760 feat(button): add support for style override object
  src/__deprecated__/components/form/__snapshots__/form.spec.js.snap
  src/__experimental__/components/form/__snapshots__/form.spec.js.snap
  src/components/button/__snapshots__/button.spec.js.snap
  src/components/button/button.component.js
  src/components/button/button.d.ts
  src/components/button/button.spec.js
  src/components/button/button.stories.mdx
  src/components/button/button.style.js
  src/components/button/docgenInfo.json
  src/components/multi-action-button/__snapshots__/multi-action-button.spec.js.snap
  src/components/split-button/__snapshots__/split-button.spec.js.snap
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2750 docs(readme): update steps in readme
  cypress/README.md
Labels: Docs in repo, Squad Front End

#2766 test(profile, portrait): add ignore tag
  cypress/features/regression/portrait.feature
  cypress/features/regression/profile.feature
Labels: Cypress, Squad Front End

#2762 docs(batch-selection): fix button outline over link part (FE-2653)
  src/components/batch-selection/batch-selection.stories.mdx
Labels: Passed QA, Passed Review, Squad Front End

#2768 ci(travis): build x.x.x branches
  .travis.yml
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#2765 feat(action-popover): support for aligning menu to right of button
  src/components/action-popover/__snapshots__/action-popover.spec.js.snap
  src/components/action-popover/action-popover.component.js
  src/components/action-popover/action-popover.d.ts
  src/components/action-popover/action-popover.spec.js
  src/components/action-popover/action-popover.stories.mdx
  src/components/action-popover/action-popover.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2769 chore: merge 12.4.x into master
  CHANGELOG.md
  src/__experimental__/components/input/input.component.js
  src/__experimental__/components/input/input.spec.js
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#2655 feat(advanced-color-picker): dialog popup colour picker FE-2334
  cypress/features/regression/test/accordionGrouped.feature
  cypress/features/regression/test/actionPopoverNoIFrame.feature
  cypress/features/regression/test/advancedColorPicker.feature
  cypress/features/regression/test/advancedColorPickerNoIFrame.feature
  cypress/locators/advanced-color-picker/index.js
  cypress/locators/advanced-color-picker/locators.js
  cypress/support/step-definitions/advanced-color-picker-steps.js
  cypress/support/step-definitions/common-steps.js
  jest.conf.json
  src/__experimental__/components/simple-color-picker/color-sample-box/checker-board.svg
  src/__experimental__/components/simple-color-picker/color-sample-box/color-sample-box.spec.js
  src/__experimental__/components/simple-color-picker/color-sample-box/color-sample-box.style.js
  src/components/advanced-color-picker/__snapshots__/advanced-color-picker.spec.js.snap
  src/components/advanced-color-picker/advanced-color-picker-cell.style.js
  src/components/advanced-color-picker/advanced-color-picker.component.js
  src/components/advanced-color-picker/advanced-color-picker.d.ts
  src/components/advanced-color-picker/advanced-color-picker.spec.js
  src/components/advanced-color-picker/advanced-color-picker.stories.js
  src/components/advanced-color-picker/advanced-color-picker.stories.mdx
  src/components/advanced-color-picker/advanced-color-picker.style.js
  src/components/advanced-color-picker/index.js
  src/components/dialog/dialog.component.js
  src/components/dialog/dialog.style.js
  src/components/modal/modal.component.js
  src/utils/helpers/focus-trap/focus-trap.js
  src/utils/helpers/focus-trap/focus-trap.spec.js
  svgTransform.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End
