Repository Sage/carbon, pull requests merged in 2020-06, with the labels that each got.

#2955 feat(drawer, flat-table, flat-table-row): add sidebar context
  cypress.env.json
  cypress/features/regression/test/flatTableIniFrame.feature
  cypress/features/regression/test/flatTableSortable.feature
  cypress/features/visual/flatTable.feature
  cypress/locators/flat-table/index.js
  cypress/support/step-definitions/flat-table-steps.js
  src/components/drawer/__snapshots__/drawer.spec.js.snap
  src/components/drawer/drawer.component.js
  src/components/drawer/index.d.ts
  src/components/drawer/index.js
  src/components/flat-table/__snapshots__/flat-table.spec.js.snap
  src/components/flat-table/flat-table-body/flat-table-body.d.ts
  src/components/flat-table/flat-table-body/index.d.ts
  src/components/flat-table/flat-table-cell/flat-table-cell.d.ts
  src/components/flat-table/flat-table-cell/index.d.ts
  src/components/flat-table/flat-table-checkbox/flat-table-checkbox.d.ts
  src/components/flat-table/flat-table-checkbox/index.d.ts
  src/components/flat-table/flat-table-head/flat-table-head.d.ts
  src/components/flat-table/flat-table-head/index.d.ts
  src/components/flat-table/flat-table-header/flat-table-header.d.ts
  src/components/flat-table/flat-table-header/index.d.ts
  src/components/flat-table/flat-table-row-header/flat-table-row-header.d.ts
  src/components/flat-table/flat-table-row-header/index.d.ts
  src/components/flat-table/flat-table-row/flat-table-row.component.js
  src/components/flat-table/flat-table-row/flat-table-row.d.ts
  src/components/flat-table/flat-table-row/flat-table-row.spec.js
  src/components/flat-table/flat-table-row/flat-table-row.style.js
  src/components/flat-table/flat-table-row/index.d.ts
  src/components/flat-table/flat-table.component.js
  src/components/flat-table/flat-table.d.ts
  src/components/flat-table/flat-table.spec.js
  src/components/flat-table/flat-table.stories.js
  src/components/flat-table/flat-table.stories.mdx
  src/components/flat-table/flat-table.style.js
  src/components/flat-table/index.d.ts
  src/components/flat-table/sort/index.d.ts
  src/style/themes/base/base-theme.config.js
Labels: Passed Review, Passed UX QA, Pending QA, Squad Front End

#2922 refactor: add zIndex object to base theme - FE-2765
  cypress/support/step-definitions/action-popover-steps.js
  src/__experimental__/components/search/search.style.js
  src/components/action-popover/__snapshots__/action-popover.spec.js.snap
  src/components/action-popover/action-popover.style.js
  src/components/dialog-full-screen/dialog-full-screen.style.js
  src/components/dialog/dialog.spec.js
  src/components/dialog/dialog.style.js
  src/components/flat-table/__snapshots__/flat-table.spec.js.snap
  src/components/flat-table/flat-table-head/flat-table-head.style.js
  src/components/flat-table/flat-table-row/flat-table-row.spec.js
  src/components/flat-table/flat-table-row/flat-table-row.style.js
  src/components/flat-table/flat-table.spec.js
  src/components/flat-table/flat-table.style.js
  src/components/multi-action-button/__snapshots__/multi-action-button.spec.js.snap
  src/components/multi-action-button/multi-action-button.style.js
  src/components/popover-container/popover-container.style.js
  src/components/sidebar/sidebar.spec.js
  src/components/sidebar/sidebar.style.js
  src/components/split-button/__snapshots__/split-button.spec.js.snap
  src/components/split-button/split-button-children.style.js
  src/components/split-button/split-button.spec.js
  src/components/tooltip/__snapshots__/tooltip.spec.js.snap
  src/components/tooltip/tooltip.spec.js
  src/components/tooltip/tooltip.style.js
  src/style/themes/base/base-theme.config.js
Labels: Passed QA, Passed Review, Squad Front End

#2966 fix(profile): profile story not loading in storybook - FE-2822
  src/components/content/content.d.ts
  src/components/profile/__definition__.js
  src/components/profile/__snapshots__/profile.spec.js.snap
  src/components/profile/docgenInfo.json
  src/components/profile/profile.component.js
  src/components/profile/profile.spec.js
  src/components/profile/profile.stories.js
  src/components/profile/profile.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2967 test(toast): add visual story
  cypress/features/visual/toast.feature
  cypress/support/step-definitions/common-steps.js
  src/components/toast/toast.stories.js
Labels: Passed QA, Passed Review, Squad Front End

#2968 feat(tile-select): create tile-select component - FE-2667
  cypress.env.json
  cypress/features/regression/designSystem/tileSelect.feature
  cypress/features/visual/tileSelect.feature
  cypress/locators/tileSelect/index.js
  cypress/locators/tileSelect/locators.js
  cypress/support/helper.js
  cypress/support/step-definitions/themes-steps.js
  cypress/support/step-definitions/tile-select-step.js
  src/components/tile-select/index.js
  src/components/tile-select/tile-select-group.component.js
  src/components/tile-select/tile-select-group.d.ts
  src/components/tile-select/tile-select.component.js
  src/components/tile-select/tile-select.d.ts
  src/components/tile-select/tile-select.spec.js
  src/components/tile-select/tile-select.stories.mdx
  src/components/tile-select/tile-select.style.js
  src/style/themes/base/base-theme.config.js
Labels: Passed QA, Passed UX QA, Pending Review, Squad Front End

#2965 feat(grid-item): add align and justify props - FE-2764
  cypress/features/regression/test/grid.feature
  cypress/features/visual/grid.feature
  cypress/support/step-definitions/grid-steps.js
  src/components/grid/__snapshots__/grid.spec.js.snap
  src/components/grid/grid-item/grid-item.component.js
  src/components/grid/grid-item/grid-item.style.js
  src/components/grid/grid-item/index.d.ts
  src/components/grid/grid.spec.js
  src/components/grid/grid.stories.js
  src/components/grid/grid.stories.mdx
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2953 docs: add documentation on webfontloader
  docs/getting-started.md
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2954 fix(drawer): drawer update - FE-2798
  cypress/features/regression/designSystem/drawer.feature
  cypress/features/regression/drawer.feature
  cypress/locators/drawer/index.js
  cypress/locators/drawer/locators.js
  cypress/support/step-definitions/drawer-steps.js
  src/components/drawer/__snapshots__/drawer.spec.js.snap
  src/components/drawer/drawer.component.js
  src/components/drawer/drawer.d.ts
  src/components/drawer/drawer.spec.js
  src/components/drawer/drawer.stories.js
  src/components/drawer/drawer.stories.mdx
  src/components/drawer/drawer.style.js
  src/style/themes/base/base-theme.config.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2972 test: update testing dependencies
  .dockerignore
  cypress/locators/index.js
  package-lock.json
  package.json
Labels: Cypress, Squad Front End

#2971 docs(dev environment): add documentation for initial setup
  CONTRIBUTING.md
  docs/dev-environment-setup.md
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2974 docs: add more details to the pr template comments
  .github/PULL_REQUEST_TEMPLATE.md
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2975 docs: amend codesandbox template link
  docs/getting-started.md
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2978 fix(storybook): fix alignment of theme selector FE-2832
  .storybook/theme-selector/register.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2980 fix(button-toggle): onBlur not being passed on button toggle input - FE-2860
  src/components/button-toggle/button-toggle-input.component.js
  src/components/button-toggle/button-toggle.component.js
  src/components/button-toggle/button-toggle.spec.js
  src/components/button-toggle/button-toggle.stories.js
  src/components/button-toggle/docgenInfo.json
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2984 chore: remove deprecated checkbox
  src/__deprecated__/components/checkbox/README.md
  src/__deprecated__/components/checkbox/__definition__.js
  src/__deprecated__/components/checkbox/__spec__.js
  src/__deprecated__/components/checkbox/checkbox.js
  src/__deprecated__/components/checkbox/checkbox.scss
  src/__deprecated__/components/checkbox/checkbox.stories.js
  src/__deprecated__/components/checkbox/docgenInfo.json
  src/__deprecated__/components/checkbox/documentation/index.js
  src/__deprecated__/components/checkbox/documentation/info.js
  src/__deprecated__/components/checkbox/documentation/notes.md
  src/__deprecated__/components/checkbox/package.json
  src/components/configurable-items/configurable-item-row/configurable-item-row.component.js
  src/components/configurable-items/configurable-item-row/configurable-item-row.style.js
  src/components/configurable-items/configurable-item-row/configurable-items-row.spec.js
  src/components/configurable-items/configurable-items.component.js
  src/components/configurable-items/configurable-items.spec.js
  src/components/configurable-items/configurable-items.stories.js
  src/components/dialog/dialog.stories.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2988 docs: update document and image paths to relative
  CONTRIBUTING.md
  README.md
  cypress/README.md
  docs/testing-styleguide.MD
Labels: Docs, Passed Review, Squad Front End

#2989 chore: remove deprecated decimal component
  src/__deprecated__/components/decimal/__definition__.js
  src/__deprecated__/components/decimal/__spec__.js
  src/__deprecated__/components/decimal/decimal.d.ts
  src/__deprecated__/components/decimal/decimal.js
  src/__deprecated__/components/decimal/decimal.stories.js
  src/__deprecated__/components/decimal/docgenInfo.json
  src/__deprecated__/components/decimal/documentation/index.js
  src/__deprecated__/components/decimal/documentation/info.js
  src/__deprecated__/components/decimal/documentation/notes.md
  src/__deprecated__/components/decimal/package.json
Labels: No UX QA Required, Passed QA, Pending Review

#2990 docs: rename testing-styleguide
  docs/testing-styleguide.md
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2991 chore: remove deprecated number component
  src/__deprecated__/components/number/__definition__.js
  src/__deprecated__/components/number/__spec__.js
  src/__deprecated__/components/number/docgenInfo.json
  src/__deprecated__/components/number/notes.md
  src/__deprecated__/components/number/number.d.ts
  src/__deprecated__/components/number/number.js
  src/__deprecated__/components/number/number.stories.js
  src/__deprecated__/components/number/package.json
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2992 chore: remove deprecated textarea component
  src/__deprecated__/components/textarea/__definition__.js
  src/__deprecated__/components/textarea/__spec__.js
  src/__deprecated__/components/textarea/docgenInfo.json
  src/__deprecated__/components/textarea/documentation/index.js
  src/__deprecated__/components/textarea/documentation/info.js
  src/__deprecated__/components/textarea/documentation/notes.md
  src/__deprecated__/components/textarea/package.json
  src/__deprecated__/components/textarea/textarea.js
  src/__deprecated__/components/textarea/textarea.scss
  src/__deprecated__/components/textarea/textarea.stories.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2993 chore: remove deprecated grouped-character component
  src/__deprecated__/components/grouped-character/__definition__.js
  src/__deprecated__/components/grouped-character/__spec__.js
  src/__deprecated__/components/grouped-character/docgenInfo.json
  src/__deprecated__/components/grouped-character/grouped-character.js
  src/__deprecated__/components/grouped-character/grouped-character.stories.js
  src/__deprecated__/components/grouped-character/package.json
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2983 feat(icon): added 15 new icons
  cypress.env.json
  cypress/features/regression/iconTypePart1.feature
  cypress/features/regression/iconTypePart2.feature
  cypress/features/visual/buttonDarkbackground.feature
  cypress/features/visual/buttonDarkbackgroundIconsAfter.feature
  cypress/features/visual/buttonDarkbackgroundIconsBefore.feature
  cypress/features/visual/buttonDashed.feature
  cypress/features/visual/buttonDashedIconsAfter.feature
  cypress/features/visual/buttonDashedIconsBefore.feature
  cypress/features/visual/buttonPrimary.feature
  cypress/features/visual/buttonPrimaryIconsAfter.feature
  cypress/features/visual/buttonPrimaryIconsBefore.feature
  cypress/features/visual/buttonSecondary.feature
  cypress/features/visual/buttonSecondaryIconsAfter.feature
  cypress/features/visual/buttonSecondaryIconsBefore.feature
  cypress/features/visual/buttonTertiary.feature
  cypress/features/visual/buttonTertiaryIconsAfter.feature
  cypress/features/visual/buttonTertiaryIconsBefore.feature
  src/components/button/button.stories.js
  src/components/icon/fonts/carbon-icons-webfont.woff
  src/components/icon/icon-unicodes.js
  src/style/fonts/carbon-icons-webfont.woff
  src/utils/helpers/options-helper/__spec__.js
  src/utils/helpers/options-helper/options-helper.d.ts
  src/utils/helpers/options-helper/options-helper.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2994 test(package.json): update cypress and cucumber preprocessor
  package-lock.json
  package.json
Labels: Cypress, Squad Front End

#2986 docs(validations): add carbon validations and formik guide
  .storybook/main.js
  docs/getting-started.stories.mdx
  docs/validations.stories.mdx
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2979 test: enable chromatic
  .github/workflows/ci.yml
  .github/workflows/cypress-parallel.yml
  .github/workflows/semantic-release.yml
  .github/workflows/storybook.yml
  .storybook/preview.js
  .travis.yml
  CONTRIBUTING.md
  README.md
  applitools.config.js
  cypress.env.json
  cypress.json
  cypress/README.md
  cypress/features/visual/batchSelection.feature
  cypress/features/visual/buttonDarkbackgroundIconsAfter.feature
  cypress/features/visual/buttonDarkbackgroundIconsBefore.feature
  cypress/features/visual/buttonDashedIconsAfter.feature
  cypress/features/visual/buttonDashedIconsBefore.feature
  cypress/features/visual/buttonPrimaryIconsAfter.feature
  cypress/features/visual/buttonPrimaryIconsBefore.feature
  cypress/features/visual/buttonSecondaryIconsAfter.feature
  cypress/features/visual/buttonSecondaryIconsBefore.feature
  cypress/features/visual/buttonTertiaryIconsAfter.feature
  cypress/features/visual/buttonTertiaryIconsBefore.feature
  cypress/features/visual/checkboxValidations.feature
  cypress/features/visual/dateInputValidations.feature
  cypress/features/visual/drawer.feature
  cypress/features/visual/flatTable.feature
  cypress/features/visual/grid.feature
  cypress/features/visual/numeralDate.feature
  cypress/features/visual/radioButtonGroupStyleOverrideNoIFrame.feature
  cypress/features/visual/radioButtonValidations.feature
  cypress/features/visual/selectValidations.feature
  cypress/features/visual/switchValidations.feature
  cypress/features/visual/textareaValidations.feature
  cypress/features/visual/textboxValidations.feature
  cypress/features/visual/tileSelect.feature
  cypress/features/visual/toast.feature
  cypress/plugins/index.js
  cypress/support/eyes-index.d.ts
  cypress/support/index.js
  cypress/support/step-definitions/applitools-steps.js
  docs/images/applitools_accept_new_snapshot.png
  docs/images/applitools_differences_identified.png
  docs/testing-styleguide.md
  package-lock.json
  package.json
  src/components/carousel/carousel.stories.js
  src/components/grid/grid.stories.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2997 ci: update chromatic baselines
  .github/workflows/chromatic-branch.yml
  .github/workflows/chromatic-release.yml
  .github/workflows/ci.yml
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2998 ci: run chromatic on all branches
  .github/workflows/chromatic-branch.yml
  .github/workflows/chromatic.yml
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#3003 ci: run workflows on pr where possible
  .github/workflows/chromatic-pr.yml
  .github/workflows/chromatic-push.yml
  .github/workflows/ci.yml
  .github/workflows/cypress-pr.yml
  .github/workflows/cypress-push.yml
  CONTRIBUTING.md
  README.md
Labels: No QA Required, No UX QA Required, Passed Review, Pending Review, Squad Front End

#3006 docs: prevent guid changing in chromatic
  src/__experimental__/components/checkbox/checkbox.stories.js
  src/__experimental__/components/select/select.stories.js
  src/__experimental__/components/textarea/textarea.stories.js
  src/__experimental__/components/textbox/textbox.stories.js
Labels: Chromatic, No QA Required, No UX QA Required, Passed Review, Squad Front End

#3002 test(cypress): remove no needed test cases and comments
  cypress/features/regression/button.feature
  cypress/features/regression/create.feature
  cypress/features/regression/designSystem/drawer.feature
  cypress/features/regression/designSystem/duellingPicklist.feature
  cypress/features/regression/designSystem/tileSelect.feature
  cypress/features/regression/help.feature
  cypress/features/regression/showEditPod.feature
  cypress/features/regression/test/accordion.feature
  cypress/features/regression/test/actionPopoverStyleOverrideNoIFrame.feature
  cypress/features/regression/test/badge.feature
  cypress/features/regression/test/batchSelection.feature
  cypress/features/regression/test/search.feature
Labels: Cypress, Squad Front End

#3012 chore: remove deprecated radio-button component
  src/__deprecated__/components/radio-button/__definition__.js
  src/__deprecated__/components/radio-button/__spec__.js
  src/__deprecated__/components/radio-button/docgenInfo.json
  src/__deprecated__/components/radio-button/documentation/index.js
  src/__deprecated__/components/radio-button/documentation/info.js
  src/__deprecated__/components/radio-button/documentation/notes.md
  src/__deprecated__/components/radio-button/notes.md
  src/__deprecated__/components/radio-button/package.json
  src/__deprecated__/components/radio-button/radio-button.js
  src/__deprecated__/components/radio-button/radio-button.scss
  src/__deprecated__/components/radio-button/radio-button.stories.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3011 chore: prevent chromatic false positives
  src/__experimental__/components/date/date.stories.js
  src/__experimental__/components/select/select.stories.js
  src/components/portrait/portrait.stories.js
  src/components/rainbow/rainbow.stories.js
  src/components/table-ajax/table-ajax.stories.js
Labels: Chromatic, No UX QA Required, Passed QA, Pending Review, Squad Front End

#3013 chore: remove deprecated fieldset component
  src/__deprecated__/components/fieldset/__definition__.js
  src/__deprecated__/components/fieldset/__spec__.js
  src/__deprecated__/components/fieldset/docgenInfo.json
  src/__deprecated__/components/fieldset/documentation/notes.md
  src/__deprecated__/components/fieldset/fieldset.js
  src/__deprecated__/components/fieldset/fieldset.scss
  src/__deprecated__/components/fieldset/fieldset.stories.js
  src/__deprecated__/components/fieldset/package.json
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3014 ci: prevent credentials being stored from checkout
  .github/workflows/semantic-release.yml
  src/__deprecated__/components/fieldset/__definition__.js
  src/__deprecated__/components/fieldset/__spec__.js
  src/__deprecated__/components/fieldset/docgenInfo.json
  src/__deprecated__/components/fieldset/documentation/notes.md
  src/__deprecated__/components/fieldset/fieldset.js
  src/__deprecated__/components/fieldset/fieldset.scss
  src/__deprecated__/components/fieldset/fieldset.stories.js
  src/__deprecated__/components/fieldset/package.json
  src/__deprecated__/components/radio-button/__definition__.js
  src/__deprecated__/components/radio-button/__spec__.js
  src/__deprecated__/components/radio-button/docgenInfo.json
  src/__deprecated__/components/radio-button/documentation/index.js
  src/__deprecated__/components/radio-button/documentation/info.js
  src/__deprecated__/components/radio-button/documentation/notes.md
  src/__deprecated__/components/radio-button/notes.md
  src/__deprecated__/components/radio-button/package.json
  src/__deprecated__/components/radio-button/radio-button.js
  src/__deprecated__/components/radio-button/radio-button.scss
  src/__deprecated__/components/radio-button/radio-button.stories.js
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#3016 chore: update changelog
  CHANGELOG.md
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#3017 ci(chromatic): ignore npm badge
  .storybook/welcome-page/header/header.component.js
Labels: Chromatic, No QA Required, No UX QA Required, Pending Review, Squad Front End

#3007 docs: add documentation styleguide
  docs/documentation-styleguide.md
Labels: Docs, Pending Review, Squad Front End

#3021 test(chromatic): make the date static in dialog stories
  src/components/dialog/dialog.stories.js
Labels: Chromatic, No QA Required, No UX QA Required, Pending Review, Squad Front End

#3018 fix: increase width on validation labels
  src/__experimental__/components/date-range/date-range.component.js
  src/__experimental__/components/date-range/date-range.stories.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2969 docs(drawer): create `side view navigation` example - FE-2331
  src/components/drawer/drawer.stories.mdx
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3005 refactor(menu): refactor component - [FE-2816] - [FE-2572] - [FE-2844]
  cypress/features/regression/menu.feature
  cypress/locators/menu/index.js
  cypress/support/step-definitions/menu-steps.js
  src/components/menu/__spec__.js
  src/components/menu/index.js
  src/components/menu/menu-item/__spec__.js
  src/components/menu/menu-item/index.js
  src/components/menu/menu-item/menu-item.component.js
  src/components/menu/menu-item/menu-item.js
  src/components/menu/menu-item/menu-item.scss
  src/components/menu/menu-item/menu-item.spec.js
  src/components/menu/menu-item/menu-item.style.js
  src/components/menu/menu-item/package.json
  src/components/menu/menu.component.js
  src/components/menu/menu.js
  src/components/menu/menu.scss
  src/components/menu/menu.spec.js
  src/components/menu/menu.stories.js
  src/components/menu/menu.style.js
  src/components/menu/package.json
  src/components/menu/submenu-block/__definition__.js
  src/components/menu/submenu-block/__spec__.js
  src/components/menu/submenu-block/index.js
  src/components/menu/submenu-block/package.json
  src/components/menu/submenu-block/submenu-block.component.js
  src/components/menu/submenu-block/submenu-block.js
  src/components/menu/submenu-block/submenu-block.scss
  src/components/menu/submenu-block/submenu-block.spec.js
  src/components/menu/submenu-block/submenu.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3019 chore(dependancies): upgrade packages to resolve vulnerabilities
  package-lock.json
  package.json
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3015 test(axe): re-implement the accessibility tests
  .storybook/preview.js
  cypress.env.json
  cypress.json
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/accessibility/accessibilityCommonSecondPart.feature
  cypress/features/regression/accessibility/accessibilityDesignSystem.feature
  cypress/features/regression/accessibility/accessibilityExperimental.feature
  cypress/features/regression/accessibility/accessibilityTest.feature
  cypress/features/regression/buttonAsSibling.feature
  cypress/features/regression/experimental/textarea.feature
  cypress/features/regression/iconTypePart1.feature
  cypress/features/regression/iconTypePart2.feature
  cypress/features/regression/test/textboxStyleOverrideNoIFrame.feature
  cypress/locators/accessibility/index.js
  cypress/locators/index.js
  cypress/locators/locators.js
  cypress/support/helper.js
  cypress/support/index.js
  cypress/support/step-definitions/accessibility-steps.js
  cypress/support/step-definitions/common-steps.js
  package-lock.json
  package.json
  src/components/icon/icon.stories.js
Labels: Chromatic, Cypress

#3020 refactor: add deprecation notice to create
  cypress/features/regression/create.feature
  src/components/create/create.component.js
  src/components/create/create.stories.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3033 fix(anchor-navigation): add missing target prop definition
  src/components/anchor-navigation/anchor-navigation-item.component.js
  src/components/anchor-navigation/anchor-navigation-item.d.ts
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End
