Repository Sage/carbon, pull requests merged in 2020-10, with the labels that each got.

#3248 test: update cypress tests from DS to open it in noIframe - FE-3176
  cypress.env.json
  cypress/features/regression/alertActions.feature
  cypress/features/regression/designSystem/accordion.feature
  cypress/features/regression/designSystem/advancedColorPicker.feature
  cypress/features/regression/designSystem/batchSelection.feature
  cypress/features/regression/designSystem/drawer.feature
  cypress/features/regression/designSystem/filterableSelect.feature
  cypress/features/regression/designSystem/filterableSelectEvents.feature
  cypress/features/regression/designSystem/flatTable.feature
  cypress/features/regression/designSystem/multiSelect.feature
  cypress/features/regression/designSystem/multiSelectEvents.feature
  cypress/features/regression/designSystem/popoverContainer.feature
  cypress/features/regression/designSystem/search.feature
  cypress/features/regression/designSystem/simpleSelect.feature
  cypress/features/regression/designSystem/simpleSelectEvents.feature
  cypress/features/regression/designSystem/tileSelect.feature
  cypress/features/regression/designSystem/toast.feature
  cypress/features/regression/dialogActions.feature
  cypress/features/regression/test/actionPopoverNoIFrame.feature
  cypress/features/regression/test/flatTableEventIniFrame.feature
  cypress/locators/accordion/index.js
  cypress/locators/advanced-color-picker/index.js
  cypress/locators/advanced-color-picker/locators.js
  cypress/locators/batch-selection/index.js
  cypress/locators/drawer/index.js
  cypress/locators/flat-table/index.js
  cypress/locators/flat-table/locators.js
  cypress/locators/locators.js
  cypress/locators/popover-container/index.js
  cypress/locators/popover-container/locators.js
  cypress/locators/search/index.js
  cypress/locators/search/locators.js
  cypress/locators/select/index.js
  cypress/locators/tileSelect/index.js
  cypress/locators/tileSelect/locators.js
  cypress/locators/toast/index.js
  cypress/support/step-definitions/accordion-steps.js
  cypress/support/step-definitions/advanced-color-picker-steps.js
  cypress/support/step-definitions/batch-selection-steps.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/flat-table-steps.js
  cypress/support/step-definitions/popover-container-steps.js
  cypress/support/step-definitions/search-steps.js
  cypress/support/step-definitions/select-steps.js
  cypress/support/step-definitions/simple-color-picker-steps.js
  cypress/support/step-definitions/toast-steps.js
Labels: Cypress, Squad Front End

#3250 chore(dependencies): upgrade multiple dependencies - FE-3178
  package-lock.json
  package.json
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3251 test: update cypress version to 5.3.0 & cypress-cucumber-preprocessor to 3.0.0
  package-lock.json
  package.json
Labels: Cypress, Squad Front End

#3242 fix(definition-list): display as grid to enable content wrapping FE-3160
  src/components/accordion/accordion.component.js
  src/components/accordion/accordion.d.ts
  src/components/accordion/accordion.spec.js
  src/components/accordion/accordion.stories.mdx
  src/components/accordion/accordion.style.js
  src/components/definition-list/dd.component.js
  src/components/definition-list/definition-list.spec.js
  src/components/definition-list/definition-list.style.js
  src/components/definition-list/dl.component.js
  src/components/grid/grid.stories.mdx
  src/components/tile/tile.stories.mdx
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3245 feat(dialog full screen): added reference to scrollable content
  src/components/dialog-full-screen/__snapshots__/dialog-full-screen.spec.js.snap
  src/components/dialog-full-screen/dialog-full-screen.component.js
  src/components/dialog-full-screen/dialog-full-screen.spec.js
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#3232 feat: add button and select spacing props
  src/components/badge/badge.style.js
  src/components/button/__snapshots__/button.spec.js.snap
  src/components/button/button-sizes.style.js
  src/components/button/button.component.js
  src/components/button/button.d.ts
  src/components/button/button.spec.js
  src/components/button/button.stories.mdx
  src/components/button/button.style.js
  src/components/dialog-full-screen/__snapshots__/dialog-full-screen.spec.js.snap
  src/components/multi-action-button/__snapshots__/multi-action-button.spec.js.snap
  src/components/pager/__internal__/__snapshots__/pager.spec.js.snap
  src/components/select/simple-select/index.d.ts
  src/components/select/simple-select/simple-select.component.js
  src/components/select/simple-select/simple-select.spec.js
  src/components/select/simple-select/simple-select.stories.mdx
  src/components/select/simple-select/simple-select.style.js
  src/components/split-button/__snapshots__/split-button.spec.js.snap
  src/components/text-editor/__internal__/toolbar/toolbar.spec.js
  src/components/text-editor/__internal__/toolbar/toolbar.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3252 chore(detail): remove classic theme
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/detail.feature
  src/components/detail/README.md
  src/components/detail/__definition__.js
  src/components/detail/detail.stories.js
  src/components/detail/detail.stories.mdx
  src/components/detail/docgenInfo.json
  src/components/detail/documentation/index.js
  src/components/detail/documentation/notes.md
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3234 chore(pod): remove classic theme - FE-3118
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/pod.feature
  cypress/fixtures/commonComponents/pod.json
  cypress/locators/pod/index.js
  cypress/support/step-definitions/pod-steps.js
  src/components/grid/grid.stories.js
  src/components/grid/grid.stories.mdx
  src/components/pod/README.md
  src/components/pod/__definition__.js
  src/components/pod/__snapshots__/pod.spec.js.snap
  src/components/pod/docgenInfo.json
  src/components/pod/notes.md
  src/components/pod/pod-classic.style.js
  src/components/pod/pod.component.js
  src/components/pod/pod.spec.js
  src/components/pod/pod.stories.js
  src/components/pod/pod.stories.mdx
  src/components/pod/pod.style.js
  src/components/show-edit-pod/__spec__.js
  src/components/show-edit-pod/show-edit-pod.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3253 chore(app-wrapper): remove classic theme
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/appWrapper.feature
  src/components/app-wrapper/README.md
  src/components/app-wrapper/app-wrapper.stories.js
  src/components/app-wrapper/app-wrapper.stories.mdx
  src/components/app-wrapper/docgenInfo.json
  src/components/app-wrapper/notes.md
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3259 fix(search): address alignment styling bug with search button - FE-3193
  src/__experimental__/components/search/docgenInfo.json
  src/__experimental__/components/search/documentation/index.js
  src/__experimental__/components/search/documentation/info.js
  src/__experimental__/components/search/documentation/notes.md
  src/__experimental__/components/search/search.component.js
  src/__experimental__/components/search/search.stories.mdx
  src/__experimental__/components/search/search.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3267 test: remove cypress tests covered by chromatic - FE-3204
  cypress/features/regression/experimental/checkbox.feature
  cypress/features/regression/experimental/switch.feature
  cypress/features/regression/test/pager.feature
  cypress/features/regression/test/tabs.feature
  cypress/fixtures/experimental/checkbox.json
  cypress/fixtures/experimental/switch.json
  cypress/fixtures/test/pager.json
  cypress/fixtures/test/tabs.json
  cypress/locators/checkbox/index.js
  cypress/locators/checkbox/locators.js
  cypress/locators/switch/index.js
  cypress/locators/tabs/index.js
  cypress/locators/tabs/locators.js
  cypress/support/step-definitions/checkbox-steps.js
  cypress/support/step-definitions/switch-steps.js
  cypress/support/step-definitions/tabs-steps.js
Labels: Cypress, Squad Front End

#3268 fix(select): destructure spacing props into style wrapper
  src/components/select/simple-select/simple-select.component.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3288 ci(cypress): update the steps timeout
  .github/workflows/cypress-pr.yml
  .github/workflows/cypress-push.yml
Labels: Cypress

#3275 refactor(action-popover): simplify custom theme FE-3219
  src/components/action-popover/action-popover.stories.mdx
  src/components/action-popover/action-popover.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3276 chore(tooltip): remove classic theme support - FE-3127
  src/components/tooltip/__definition__.js
  src/components/tooltip/docgenInfo.json
  src/components/tooltip/documentation/index.js
  src/components/tooltip/documentation/info.js
  src/components/tooltip/documentation/notes.md
  src/components/tooltip/tooltip.spec.js
  src/components/tooltip/tooltip.stories.js
  src/components/tooltip/tooltip.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3255 fix(validation): renders tooltip in 'top' position when validation is on label and label is inline
  src/__experimental__/components/label/label.component.js
  src/__experimental__/components/label/label.spec.js
  src/__experimental__/components/textbox/textbox.stories.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3266 feat(flat-table): add possibility to set column width and cell paddings
  cypress/features/regression/designSystem/flatTable.feature
  cypress/locators/flat-table/index.js
  src/__spec_helper__/test-utils.js
  src/components/flat-table/__snapshots__/flat-table.spec.js.snap
  src/components/flat-table/flat-table-cell/flat-table-cell.component.js
  src/components/flat-table/flat-table-cell/flat-table-cell.d.ts
  src/components/flat-table/flat-table-cell/flat-table-cell.spec.js
  src/components/flat-table/flat-table-cell/flat-table-cell.style.js
  src/components/flat-table/flat-table-head/flat-table-head.style.js
  src/components/flat-table/flat-table-header/flat-table-header.component.js
  src/components/flat-table/flat-table-header/flat-table-header.d.ts
  src/components/flat-table/flat-table-header/flat-table-header.spec.js
  src/components/flat-table/flat-table-header/flat-table-header.style.js
  src/components/flat-table/flat-table-row-header/flat-table-row-header.component.js
  src/components/flat-table/flat-table-row-header/flat-table-row-header.d.ts
  src/components/flat-table/flat-table-row-header/flat-table-row-header.spec.js
  src/components/flat-table/flat-table-row-header/flat-table-row-header.style.js
  src/components/flat-table/flat-table-row/__snapshots__/flat-table-row.spec.js.snap
  src/components/flat-table/flat-table-row/flat-table-row.style.js
  src/components/flat-table/flat-table.stories.js
  src/components/flat-table/flat-table.stories.mdx
  src/components/flat-table/flat-table.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3270 chore(show-edit-pod): remove classic theme support - FE-3122
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/showEditPod.feature
  cypress/features/regression/themes/themes.feature
  cypress/fixtures/commonComponents/showEditPod.json
  src/components/pod/pod.stories.js
  src/components/pod/pod.stories.mdx
  src/components/show-edit-pod/__definition__.js
  src/components/show-edit-pod/docgenInfo.json
  src/components/show-edit-pod/documentation/index.js
  src/components/show-edit-pod/documentation/info.js
  src/components/show-edit-pod/documentation/notes.md
  src/components/show-edit-pod/index.js
  src/components/show-edit-pod/package.json
  src/components/show-edit-pod/show-edit-pod.component.js
  src/components/show-edit-pod/show-edit-pod.spec.js
  src/components/show-edit-pod/show-edit-pod.stories.js
  src/components/show-edit-pod/show-edit-pod.stories.mdx
  src/components/show-edit-pod/show-edit-pod.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3287 chore: merge remove_classic_theme_jamie into remove_classic_theme_mkordas
  cypress/features/regression/pill.feature
  cypress/features/regression/themes/themes.feature
  src/components/pill/docgenInfo.json
  src/components/pill/pill.component.js
  src/components/pill/pill.spec.js
  src/components/pill/pill.stories.js
  src/components/pill/pill.stories.mdx
  src/components/pill/pill.style.js
  src/utils/helpers/options-helper/__spec__.js
  src/utils/helpers/options-helper/options-helper.js
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#3284 fix(select): value cannot be cleared (FE-3188)
  src/components/select/filterable-select/filterable-select.component.js
  src/components/select/filterable-select/filterable-select.spec.js
  src/components/select/filterable-select/filterable-select.stories.mdx
  src/components/select/simple-select/simple-select.component.js
  src/components/select/simple-select/simple-select.spec.js
  src/components/select/simple-select/simple-select.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3291 chore(confirm): remove classic theme confirm
  src/components/confirm/confirm.classic.style.js
  src/components/confirm/confirm.spec.js
  src/components/confirm/confirm.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3273 chore(icon): remove classic theme - FE-3112
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/themes/themes.feature
  src/components/icon/__definition__.js
  src/components/icon/docgenInfo.json
  src/components/icon/documentation/Info.js
  src/components/icon/documentation/index.js
  src/components/icon/documentation/notes.md
  src/components/icon/icon-classic-config.js
  src/components/icon/icon-classic.style.js
  src/components/icon/icon.component.js
  src/components/icon/icon.spec.js
  src/components/icon/icon.stories.js
  src/components/icon/icon.stories.mdx
  src/components/icon/icon.style.js
  src/components/portal/__snapshots__/__spec__.js.snap
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3294 fix(label): remove margin from label when input in form
  src/__experimental__/components/label/label.spec.js
  src/__experimental__/components/label/label.style.js
  src/components/form/form.stories.mdx
Labels: No UX QA Required, Passed QA, Pending Review, Squad Front End

#3283 chore(step-sequence): remove classic theme support - FE-3123/FE-3124
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/stepSequence.feature
  cypress/features/regression/stepSequenceItem.feature
  cypress/features/regression/themes/themes.feature
  cypress/fixtures/commonComponents/stepSequence.json
  cypress/locators/step-sequence/index.js
  cypress/locators/step-sequence/locators.js
  cypress/support/step-definitions/step-sequence-steps.js
  src/components/step-sequence/__definition__.js
  src/components/step-sequence/__snapshots__/step-sequence.spec.js.snap
  src/components/step-sequence/docgenInfo.json
  src/components/step-sequence/step-sequence-classic.style.js
  src/components/step-sequence/step-sequence-item/__definition__.js
  src/components/step-sequence/step-sequence-item/__snapshots__/step-sequence-item.spec.js.snap
  src/components/step-sequence/step-sequence-item/step-sequence-item-classic.style.js
  src/components/step-sequence/step-sequence-item/step-sequence-item.spec.js
  src/components/step-sequence/step-sequence-item/step-sequence-item.stories.js
  src/components/step-sequence/step-sequence-item/step-sequence-item.style.js
  src/components/step-sequence/step-sequence.spec.js
  src/components/step-sequence/step-sequence.stories.js
  src/components/step-sequence/step-sequence.stories.mdx
  src/components/step-sequence/step-sequence.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3274 feat(accordion): add support to rendering validation icon beside heading FE-3031
  cypress.env.json
  cypress/features/regression/designSystem/accordion.feature
  cypress/support/step-definitions/accordion-steps.js
  src/components/accordion/accordion.component.js
  src/components/accordion/accordion.d.ts
  src/components/accordion/accordion.spec.js
  src/components/accordion/accordion.stories.mdx
  src/components/accordion/accordion.style.js
  src/components/validations/index.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3261 docs(action-popover): add new example to mdx
  src/components/action-popover/action-popover.stories.mdx
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3297 docs(form): change radio button ids
  src/components/form/form.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3293 chore(button-toggle): remove classic theme (FE-3102)
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/buttonToggle.feature
  cypress/features/regression/themes/themes.feature
  cypress/fixtures/commonComponents/buttonToggle.json
  src/components/button-toggle-group/__snapshots__/button-toggle-group.spec.js.snap
  src/components/button-toggle-group/button-toggle-group.spec.js
  src/components/button-toggle-group/docgenInfo.json
  src/components/button-toggle/README.md
  src/components/button-toggle/__definition__.js
  src/components/button-toggle/__snapshots__/button-toggle.spec.js.snap
  src/components/button-toggle/button-toggle-classic.style.js
  src/components/button-toggle/button-toggle.component.js
  src/components/button-toggle/button-toggle.spec.js
  src/components/button-toggle/button-toggle.stories.js
  src/components/button-toggle/button-toggle.stories.mdx
  src/components/button-toggle/button-toggle.style.js
  src/components/button-toggle/docgenInfo.json
  src/components/button-toggle/documentation/index.js
  src/components/button-toggle/documentation/notes.md
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3258 chore(heading): remove classic theme
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/heading.feature
  src/components/dialog-full-screen/__snapshots__/dialog-full-screen.spec.js.snap
  src/components/heading/__definition__.js
  src/components/heading/__spec__.js
  src/components/heading/docgenInfo.json
  src/components/heading/documentation/index.js
  src/components/heading/documentation/notes.md
  src/components/heading/heading.scss
  src/components/heading/heading.stories.js
  src/components/heading/heading.stories.mdx
  src/components/heading/heading.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3310 docs: remove allure reports data
  .gitignore
Labels: Cypress, Passed Review, Squad Front End

#3299 fix(tabs): tabs position left in sidebar and remove set target callback
  src/components/drawer/__internal__/__snapshots__/drawer.spec.js.snap
  src/components/drawer/__internal__/drawer.component.js
  src/components/drawer/__internal__/drawer.spec.js
  src/components/drawer/__internal__/drawer.stories.mdx
  src/components/tabs/__internal__/tab-title/tab-title.component.js
  src/components/tabs/__internal__/tab-title/tab-title.style.js
  src/components/tabs/__internal__/tab/tab.style.js
  src/components/tabs/__internal__/tabs-header/tabs-header.component.js
  src/components/tabs/__internal__/tabs-header/tabs-header.spec.js
  src/components/tabs/__internal__/tabs-header/tabs-header.style.js
  src/components/tabs/__internal__/tabs.component.js
  src/components/tabs/__internal__/tabs.spec.js
  src/components/tabs/__internal__/tabs.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3309 chore(flat-table): update test story
  src/components/flat-table/flat-table.stories.js
Labels: Passed QA, Passed Review, Squad Front End

#3298 feat(text-editor): allow to focus editor after label clicked
  src/components/text-editor/__internal__/label-wrapper/index.d.ts
  src/components/text-editor/__internal__/label-wrapper/index.js
  src/components/text-editor/__internal__/label-wrapper/label-wrapper.component.js
  src/components/text-editor/__internal__/label-wrapper/label-wrapper.d.ts
  src/components/text-editor/__internal__/label-wrapper/label.spec.js
  src/components/text-editor/__internal__/text-editor.component.js
  src/components/text-editor/__internal__/text-editor.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3302 chore(styled-system-props): add object to prop type for of prop
  .storybook/utils/styled-system-props.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3303 chore(help): remove classic theme - FE-3110
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/help.feature
  cypress/fixtures/commonComponents/help.json
  src/components/help/README.md
  src/components/help/__definition__.js
  src/components/help/docgenInfo.json
  src/components/help/documentation/index.js
  src/components/help/documentation/notes.md
  src/components/help/help.spec.js
  src/components/help/help.stories.js
  src/components/help/help.stories.mdx
  src/components/help/help.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3324 fix(tests): fix accessibility tests on major branch
  cypress/features/regression/accessibility/accessibilityCommon.feature
Labels: Squad Front End

#3322 chore(classic-theme): merge remove classic theme dipper - FE-3251
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/appWrapper.feature
  cypress/features/regression/detail.feature
  cypress/features/regression/heading.feature
  cypress/features/regression/help.feature
  cypress/fixtures/commonComponents/help.json
  src/components/app-wrapper/README.md
  src/components/app-wrapper/app-wrapper.stories.js
  src/components/app-wrapper/app-wrapper.stories.mdx
  src/components/app-wrapper/docgenInfo.json
  src/components/app-wrapper/notes.md
  src/components/confirm/confirm.classic.style.js
  src/components/confirm/confirm.spec.js
  src/components/confirm/confirm.style.js
  src/components/detail/README.md
  src/components/detail/__definition__.js
  src/components/detail/detail.stories.js
  src/components/detail/detail.stories.mdx
  src/components/detail/docgenInfo.json
  src/components/detail/documentation/index.js
  src/components/detail/documentation/notes.md
  src/components/dialog-full-screen/__snapshots__/dialog-full-screen.spec.js.snap
  src/components/heading/__definition__.js
  src/components/heading/__spec__.js
  src/components/heading/docgenInfo.json
  src/components/heading/documentation/index.js
  src/components/heading/documentation/notes.md
  src/components/heading/heading.scss
  src/components/heading/heading.stories.js
  src/components/heading/heading.stories.mdx
  src/components/heading/heading.style.js
  src/components/help/README.md
  src/components/help/__definition__.js
  src/components/help/docgenInfo.json
  src/components/help/documentation/index.js
  src/components/help/documentation/notes.md
  src/components/help/help.spec.js
  src/components/help/help.stories.js
  src/components/help/help.stories.mdx
  src/components/help/help.style.js
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#3323 fix(radiobutton): check for onchange passed in
  src/__experimental__/components/radio-button/radio-button-mapper.component.js
  src/__experimental__/components/radio-button/radio-button-mapper.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3285 feat(dialogfullscreen): allow content in headers
  src/__internal__/full-screen-heading/full-screen-heading-classic.style.js
  src/__internal__/full-screen-heading/full-screen-heading.component.js
  src/__internal__/full-screen-heading/full-screen-heading.style.js
  src/__internal__/full-screen-heading/index.js
  src/components/dialog-full-screen/__snapshots__/dialog-full-screen.spec.js.snap
  src/components/dialog-full-screen/content.style.js
  src/components/dialog-full-screen/dialog-full-screen.component.js
  src/components/dialog-full-screen/dialog-full-screen.spec.js
  src/components/dialog-full-screen/dialog-full-screen.stories.mdx
  src/components/dialog-full-screen/dialog-full-screen.style.js
  src/components/dialog-full-screen/full-screen-heading/full-screen-heading.component.js
  src/components/form/form.stories.mdx
  src/components/pages/page/page.component.js
  src/components/pages/page/page.spec.js
  src/components/pages/pages.stories.js
  src/components/pages/pages.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3315 docs(toast): fix logic with stacked-delayed example
  src/components/toast/toast.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3307 feat(text-editor): add support for validation icon and error styles FE-3186
  src/components/text-editor/__internal__/editor-counter/editor-counter.component.js
  src/components/text-editor/__internal__/editor-counter/editor-counter.d.ts
  src/components/text-editor/__internal__/editor-counter/editor-counter.spec.js
  src/components/text-editor/__internal__/editor-counter/editor-counter.style.js
  src/components/text-editor/__internal__/text-editor.component.js
  src/components/text-editor/__internal__/text-editor.d.ts
  src/components/text-editor/__internal__/text-editor.spec.js
  src/components/text-editor/__internal__/text-editor.stories.mdx
  src/components/text-editor/__internal__/text-editor.style.js
  src/components/text-editor/__internal__/toolbar/toolbar-button/toolbar-button.component.js
  src/components/validations/validation-icon.component.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3331 fix(inputs): show input icon if info validation is empty string
  src/__experimental__/components/input-icon-toggle/input-icon-toggle.component.js
  src/__experimental__/components/input-icon-toggle/input-icon-toggle.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3314 feat(box): add new box component
  .storybook/utils/styled-system-props.js
  src/__spec_helper__/test-utils.js
  src/components/box/box.component.js
  src/components/box/box.d.ts
  src/components/box/box.spec.js
  src/components/box/box.stories.mdx
  src/components/box/index.d.ts
  src/components/box/index.js
  src/utils/helpers/options-helper/options-helper.d.ts
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3311 fix(grid-container): margins are not counted in scrollHeight (FE-3061)
  cypress/features/regression/test/grid.feature
  cypress/support/step-definitions/grid-steps.js
  src/components/grid/__snapshots__/grid.spec.js.snap
  src/components/grid/grid-container/grid-container.component.js
  src/components/grid/grid-container/grid-container.style.js
  src/components/grid/grid-container/index.d.ts
  src/components/grid/grid.spec.js
  src/components/grid/grid.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3301 chore(draggable-context): remove classic theme support - FE-3107
  cypress.env.json
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/draggableContext.feature
  cypress/support/step-definitions/draggable-context-steps.js
  src/components/configurable-items/configurable-item-row/configurable-item-row.component.js
  src/components/configurable-items/configurable-items.component.js
  src/components/drag-and-drop/custom-drag-layer/__definition__.js
  src/components/drag-and-drop/custom-drag-layer/custom-drag-layer.js
  src/components/drag-and-drop/custom-drag-layer/docgenInfo.json
  src/components/drag-and-drop/custom-drag-layer/index.js
  src/components/drag-and-drop/custom-drag-layer/package.json
  src/components/drag-and-drop/documentation/Info.js
  src/components/drag-and-drop/documentation/notes.md
  src/components/drag-and-drop/drag-and-drop.stories.js
  src/components/drag-and-drop/drag-and-drop.stories.mdx
  src/components/drag-and-drop/draggable-context/__definition__.js
  src/components/drag-and-drop/draggable-context/docgenInfo.json
  src/components/drag-and-drop/draggable-context/index.js
  src/components/drag-and-drop/draggable-context/package.json
  src/components/drag-and-drop/index.js
  src/components/drag-and-drop/package.json
  src/components/drag-and-drop/with-drag/__definition__.js
  src/components/drag-and-drop/with-drag/docgenInfo.json
  src/components/drag-and-drop/with-drag/index.js
  src/components/drag-and-drop/with-drag/package.json
  src/components/drag-and-drop/with-drag/with-drag.js
  src/components/drag-and-drop/with-drop/__definition__.js
  src/components/drag-and-drop/with-drop/docgenInfo.json
  src/components/drag-and-drop/with-drop/index.js
  src/components/drag-and-drop/with-drop/package.json
  src/components/drag-and-drop/with-drop/with-drop.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3320 feat(typography): create typography component FE-3068, FE-3002
  .eslintrc
  .storybook/utils/styled-system-props.js
  docs/colors.stories.mdx
  src/components/box/box.component.js
  src/components/dialog-full-screen/__snapshots__/dialog-full-screen.spec.js.snap
  src/components/typography/index.d.ts
  src/components/typography/index.js
  src/components/typography/list.component.js
  src/components/typography/list.d.ts
  src/components/typography/typography.component.js
  src/components/typography/typography.d.ts
  src/components/typography/typography.spec.js
  src/components/typography/typography.stories.mdx
  src/style/__spec__.js
  src/style/index.js
  src/style/themes/aegean/aegean-theme.config.js
  src/style/themes/base/base-theme.config.js
  src/style/themes/base/index.js
  src/style/utils/color.js
  src/style/utils/color.spec.js
  src/utils/helpers/options-helper/options-helper.d.ts
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3271 feat(filterable-select): add list action button (FE-3034)
  cypress.env.json
  cypress/features/regression/designSystem/filterableSelect.feature
  cypress/locators/pages/index.js
  cypress/support/step-definitions/dialog-steps.js
  cypress/support/step-definitions/select-steps.js
  src/components/button/button.component.js
  src/components/select/filterable-select/filterable-select.component.js
  src/components/select/filterable-select/filterable-select.spec.js
  src/components/select/filterable-select/filterable-select.stories.mdx
  src/components/select/filterable-select/index.d.ts
  src/components/select/list-action-button/__snapshots__/list-action-button.spec.js.snap
  src/components/select/list-action-button/list-action-button.component.js
  src/components/select/list-action-button/list-action-button.spec.js
  src/components/select/list-action-button/list-action-button.style.js
  src/components/select/select-list/select-list-container.style.js
  src/components/select/select-list/select-list.component.js
  src/components/select/select-list/select-list.spec.js
  src/components/select/select-list/select-list.style.js
  src/components/select/simple-select/simple-select.spec.js
  src/components/select/simple-select/simple-select.stories.mdx
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3325 fix(date): datepicker weekdays not translated (FE-3027)
  src/__experimental__/components/date/__snapshots__/date-picker.spec.js.snap
  src/__experimental__/components/date/date-picker.component.js
  src/__experimental__/components/date/date-picker.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3335 ci: set success dependency for chromatic
  .github/workflows/chromatic-pr.yml
  .github/workflows/chromatic-push.yml
  .github/workflows/cypress-pr.yml
  .github/workflows/cypress-push.yml
Labels: Chromatic, Cypress, Pending Review, Squad Front End

#3332 fix(theme): update base/none theme primary color FE-1634
  cypress/fixtures/themes/themes.json
  src/__experimental__/components/date/__snapshots__/date-picker.spec.js.snap
  src/components/button/__snapshots__/button.spec.js.snap
  src/components/card/__snapshots__/card.spec.js.snap
  src/components/dialog-full-screen/__snapshots__/dialog-full-screen.spec.js.snap
  src/components/dismiss-button/__snapshots__/dismiss-button.spec.js.snap
  src/components/icon/icon.spec.js
  src/components/link/__snapshots__/link.spec.js.snap
  src/components/multi-action-button/__snapshots__/multi-action-button.spec.js.snap
  src/components/pod/__snapshots__/pod.spec.js.snap
  src/components/select/list-action-button/__snapshots__/list-action-button.spec.js.snap
  src/components/split-button/__snapshots__/split-button.spec.js.snap
  src/style/themes/base/base-theme.config.js
  src/style/utils/color.spec.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3254 feat(tile, accordion): add styled-system - FE-2993
  cypress/features/regression/test/tile.feature
  cypress/fixtures/commonComponents/tile.json
  cypress/support/step-definitions/tile-steps.js
  src/components/accordion/accordion.component.js
  src/components/accordion/accordion.d.ts
  src/components/accordion/accordion.spec.js
  src/components/accordion/accordion.stories.mdx
  src/components/accordion/accordion.style.js
  src/components/tile/__snapshots__/tile.spec.js.snap
  src/components/tile/docgenInfo.json
  src/components/tile/documentation/index.js
  src/components/tile/documentation/info.js
  src/components/tile/documentation/notes.md
  src/components/tile/index.d.ts
  src/components/tile/tile.component.js
  src/components/tile/tile.d.ts
  src/components/tile/tile.spec.js
  src/components/tile/tile.stories.js
  src/components/tile/tile.stories.mdx
  src/components/tile/tile.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3339 test: Verify and ignore unnecessary stories for chromatic run -FE-3274
  cypress/features/regression/designSystem/popoverContainer.feature
  cypress/support/step-definitions/popover-container-steps.js
  src/__experimental__/components/numeral-date/numeral-date.stories.js
  src/__experimental__/components/numeral-date/numeral-date.stories.mdx
  src/__experimental__/components/search/search.stories.js
  src/__experimental__/components/search/search.stories.mdx
  src/__experimental__/components/textarea/textarea.stories.js
  src/components/accordion/accordion.stories.js
  src/components/accordion/accordion.stories.mdx
  src/components/action-popover/action-popover.stories.mdx
  src/components/advanced-color-picker/advanced-color-picker.stories.js
  src/components/badge/badge.stories.js
  src/components/batch-selection/batch-selection.stories.js
  src/components/drawer/__internal__/drawer.stories.mdx
  src/components/flat-table/flat-table.stories.js
  src/components/flat-table/flat-table.stories.mdx
  src/components/grid/grid.stories.mdx
  src/components/help/help.stories.mdx
  src/components/menu/menu.stories.mdx
  src/components/pager/__internal__/pager.stories.js
  src/components/popover-container/popover-container.stories.js
  src/components/popover-container/popover-container.stories.mdx
  src/components/select/multi-select/multi-select.stories.mdx
  src/components/select/simple-select/simple-select.stories.mdx
  src/components/show-edit-pod/show-edit-pod.stories.mdx
  src/components/tabs/__internal__/tabs.stories.js
  src/components/text-editor/__internal__/text-editor.stories.mdx
  src/components/tile/tile.stories.js
  src/components/toast/toast.stories.mdx
  src/components/vertical-divider/vertical-divider.stories.mdx
Labels: Chromatic, Passed Review, Squad Front End

#3328 chore(i18n): remove classic theme - FE-3111
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/i18nComponent.feature
  src/components/i18n/__definition__.js
  src/components/i18n/__spec__.js
  src/components/i18n/docgenInfo.json
  src/components/i18n/documentation/Info.js
  src/components/i18n/documentation/index.js
  src/components/i18n/documentation/notes.md
  src/components/i18n/i18n.stories.js
  src/components/i18n/i18n.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3330 fix(date/select): add option to disable portal - FE-2673/FE-3062
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/text-area-steps.js
  cypress/support/step-definitions/textbox-steps.js
  src/__experimental__/components/date/__snapshots__/date-picker.spec.js.snap
  src/__experimental__/components/date/date-picker.component.js
  src/__experimental__/components/date/date-picker.spec.js
  src/__experimental__/components/date/date.component.js
  src/__experimental__/components/date/date.spec.js
  src/__experimental__/components/date/date.stories.js
  src/__experimental__/components/date/day-picker.style.js
  src/__experimental__/components/input/__snapshots__/input-presentation.spec.js.snap
  src/__experimental__/components/input/input-presentation.component.js
  src/__experimental__/components/input/input-presentation.spec.js
  src/__experimental__/components/input/input-presentation.style.js
  src/__experimental__/components/select/__snapshots__/select.spec.js.snap
  src/__experimental__/components/textarea/__snapshots__/textarea.spec.js.snap
  src/__experimental__/components/textbox/textbox.component.js
  src/__experimental__/components/textbox/textbox.spec.js
  src/components/form/form.stories.mdx
  src/components/pager/__internal__/__snapshots__/pager.spec.js.snap
  src/components/portal/__spec__.js
  src/components/select/filterable-select/filterable-select.component.js
  src/components/select/filterable-select/filterable-select.spec.js
  src/components/select/filterable-select/filterable-select.stories.mdx
  src/components/select/filterable-select/index.d.ts
  src/components/select/multi-select/index.d.ts
  src/components/select/multi-select/multi-select.component.js
  src/components/select/multi-select/multi-select.spec.js
  src/components/select/multi-select/multi-select.stories.mdx
  src/components/select/select-list/select-list-container.style.js
  src/components/select/select-list/select-list.component.js
  src/components/select/select-list/select-list.spec.js
  src/components/select/simple-select/index.d.ts
  src/components/select/simple-select/simple-select.component.js
  src/components/select/simple-select/simple-select.spec.js
  src/components/select/simple-select/simple-select.stories.mdx
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End
