Repository Sage/carbon, pull requests merged in 2020-11, with the labels that each got.

#3312 feat(accordion): add tertiary button heading styling option
  src/__experimental__/components/date/__snapshots__/date-picker.spec.js.snap
  src/__experimental__/components/date/date-picker.spec.js
  src/components/accordion/accordion.component.js
  src/components/accordion/accordion.spec.js
  src/components/accordion/accordion.stories.mdx
  src/components/accordion/accordion.style.js
  src/components/dialog-full-screen/dialog-full-screen.stories.mdx
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3329 chore(link): remove classic theme - FE-3113
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/link.feature
  cypress/features/regression/themes/themes.feature
  cypress/support/step-definitions/help-steps.js
  src/components/link/__definition__.js
  src/components/link/__snapshots__/link.spec.js.snap
  src/components/link/docgenInfo.json
  src/components/link/documentation/Info.js
  src/components/link/documentation/index.js
  src/components/link/documentation/notes.md
  src/components/link/link-classic.style.js
  src/components/link/link.spec.js
  src/components/link/link.stories.js
  src/components/link/link.stories.mdx
  src/components/link/link.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3337 feat(icon/pill): add custom color support - FE-3056
  package-lock.json
  package.json
  src/__experimental__/components/simple-color-picker/__snapshots__/simple-color-picker.spec.js.snap
  src/components/icon/icon.component.js
  src/components/icon/icon.spec.js
  src/components/icon/icon.stories.js
  src/components/icon/icon.stories.mdx
  src/components/icon/icon.style.js
  src/components/pill/pill.component.js
  src/components/pill/pill.spec.js
  src/components/pill/pill.stories.js
  src/components/pill/pill.stories.mdx
  src/components/pill/pill.style.js
  src/components/portal/__snapshots__/__spec__.js.snap
  src/style/utils/color.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3318 fix(search): work in controlled mode - FE-2817
  src/__experimental__/components/search/search.component.js
  src/__experimental__/components/search/search.spec.js
  src/__experimental__/components/search/search.stories.js
  src/__experimental__/components/search/search.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Pending QA, Squad Front End

#3349 test: update cypress/cucumber version
  package-lock.json
  package.json
Labels: Cypress, Squad Front End

#3334 chore(menu-list): remove classic theme
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/menuList.feature
  cypress/locators/menu-list/locators.js
  src/components/menu-list/__definition__.js
  src/components/menu-list/__spec__.js
  src/components/menu-list/docgenInfo.json
  src/components/menu-list/documentation/index.js
  src/components/menu-list/documentation/notes.md
  src/components/menu-list/menu-list-item/__definition__.js
  src/components/menu-list/menu-list-item/__spec__.js
  src/components/menu-list/menu-list.stories.js
  src/components/menu-list/menu-list.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3346 fix(radio-button): warning when react node passed in label prop
  src/__experimental__/components/radio-button/radio-button.component.js
  src/__experimental__/components/radio-button/radio-button.d.ts
  src/__experimental__/components/radio-button/radio-button.stories.mdx
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#3347 feat(navigation-bar): add support for custom spacing props
  src/components/navigation-bar/navigation-bar.component.js
  src/components/navigation-bar/navigation-bar.d.ts
  src/components/navigation-bar/navigation-bar.spec.js
  src/components/navigation-bar/navigation-bar.stories.mdx
  src/components/navigation-bar/navigation-bar.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3341 feat(dialog-full-screen): add prop `disableContentPadding` - FE-3281
  src/components/dialog-full-screen/__snapshots__/dialog-full-screen.spec.js.snap
  src/components/dialog-full-screen/content.style.js
  src/components/dialog-full-screen/dialog-full-screen.component.js
  src/components/dialog-full-screen/dialog-full-screen.spec.js
  src/components/dialog-full-screen/dialog-full-screen.stories.js
  src/components/dialog-full-screen/dialog-full-screen.stories.mdx
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3340 feat(menu-item): add support for alternate background color variant FE-3190
  src/components/dialog-full-screen/__snapshots__/dialog-full-screen.spec.js.snap
  src/components/dialog-full-screen/dialog-full-screen.spec.js
  src/components/menu/index.d.ts
  src/components/menu/index.js
  src/components/menu/menu-divider/index.d.ts
  src/components/menu/menu-divider/menu-divider.component.js
  src/components/menu/menu-divider/menu-divider.d.ts
  src/components/menu/menu-divider/menu-divider.spec.js
  src/components/menu/menu-divider/menu-divider.style.js
  src/components/menu/menu-item/index.d.ts
  src/components/menu/menu-item/menu-item.component.js
  src/components/menu/menu-item/menu-item.d.ts
  src/components/menu/menu-item/menu-item.spec.js
  src/components/menu/menu-item/menu-item.style.js
  src/components/menu/menu-segment-title/index.d.ts
  src/components/menu/menu-segment-title/menu-segment-title.component.js
  src/components/menu/menu-segment-title/menu-segment-title.d.ts
  src/components/menu/menu-segment-title/menu-segment-title.spec.js
  src/components/menu/menu-segment-title/menu-segment-title.style.js
  src/components/menu/menu.component.js
  src/components/menu/menu.spec.js
  src/components/menu/menu.stories.mdx
  src/components/menu/submenu-block/index.d.ts
  src/components/menu/submenu-block/submenu-block.component.js
  src/components/menu/submenu-block/submenu-block.d.ts
  src/style/themes/base/base-theme.config.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3345 docs(dialog): add editable fields example FE-3006
  src/components/dialog/dialog.stories.mdx
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3355 fix(menu-item): add height when onclick passed and button renders
  src/components/menu/menu-item/menu-item.spec.js
  src/components/menu/menu-item/menu-item.style.js
  src/components/menu/menu.stories.mdx
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3353 docs(toast): fix bug with stacked example
  src/components/toast/toast.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3350 chore(mount-in-app): remove classic theme
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/mountInApp.feature
  src/components/mount-in-app/README.md
  src/components/mount-in-app/__definition__.js
  src/components/mount-in-app/docgenInfo.json
  src/components/mount-in-app/mount-in-app.stories.js
  src/components/mount-in-app/mount-in-app.stories.mdx
  src/components/mount-in-app/notes.md
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3368 docs: update the button name
  src/components/dialog-full-screen/dialog-full-screen.stories.mdx
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#3367 fix(menu-divider): add default cursor to passive submenu elements
  src/components/menu/menu-divider/menu-divider.spec.js
  src/components/menu/menu-divider/menu-divider.style.js
  src/components/menu/menu-segment-title/menu-segment-title.spec.js
  src/components/menu/menu-segment-title/menu-segment-title.style.js
Labels: No UX QA Required, Pending QA, Pending Review, Squad Front End

#3371 refactor: fix storybook warnings
  package-lock.json
  package.json
  src/components/button/button.stories.js
  src/components/flat-table/flat-table-cell/flat-table-cell.component.js
  src/components/flat-table/flat-table-row-header/flat-table-row-header.component.js
  src/components/link/link.stories.js
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#3348 fix(radio-button): align legend with first radio-button FE-3213
  src/__experimental__/components/radio-button/__snapshots__/radio-button-group.spec.js.snap
  src/__experimental__/components/radio-button/__snapshots__/radio-button-mapper.spec.js.snap
  src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap
  src/__experimental__/components/radio-button/radio-button-group.component.js
  src/__experimental__/components/radio-button/radio-button.component.js
  src/__experimental__/components/radio-button/radio-button.stories.mdx
  src/__experimental__/components/radio-button/radio-button.style.js
  src/__experimental__/components/simple-color-picker/__snapshots__/simple-color-picker.spec.js.snap
  src/__internal__/fieldset/fieldset.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3344 chore(pages): remove classic theme
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/pages.feature
  cypress/features/regression/pagesActions.feature
  cypress/fixtures/commonComponents/pages.json
  cypress/locators/pages/index.js
  cypress/support/step-definitions/pages-steps.js
  src/components/pages/__definition__.js
  src/components/pages/docgenInfo.json
  src/components/pages/documentation/index.js
  src/components/pages/documentation/info.js
  src/components/pages/page/__definition__.js
  src/components/pages/page/page.style.js
  src/components/pages/pages.spec.js
  src/components/pages/pages.stories.js
  src/components/pages/pages.stories.mdx
  src/components/pages/pages.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3370 feat(flat-table): add support for rendering table footer FE-3268
  cypress/features/regression/test/flatTableNoiFrame.feature
  cypress/support/step-definitions/flat-table-steps.js
  src/components/drawer/__internal__/drawer.stories.mdx
  src/components/flat-table/__snapshots__/flat-table.spec.js.snap
  src/components/flat-table/flat-table-head/flat-table-head.d.ts
  src/components/flat-table/flat-table.component.js
  src/components/flat-table/flat-table.d.ts
  src/components/flat-table/flat-table.spec.js
  src/components/flat-table/flat-table.stories.mdx
  src/components/flat-table/flat-table.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3313 chore(flash): remove flash component - FE-3108/FE-3253
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/flash.feature
  cypress/fixtures/commonComponents/flash.json
  cypress/locators/flash/index.js
  cypress/locators/flash/locators.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/flash-steps.js
  src/components/alert/alert.stories.mdx
  src/components/confirm/confirm.stories.mdx
  src/components/flash/README.md
  src/components/flash/__definition__.js
  src/components/flash/__snapshots__/flash-legacy.spec.js.snap
  src/components/flash/docgenInfo.json
  src/components/flash/documentation/Info.js
  src/components/flash/documentation/notes.md
  src/components/flash/flash-legacy.component.js
  src/components/flash/flash-legacy.spec.js
  src/components/flash/flash-legacy.style.js
  src/components/flash/flash.component.js
  src/components/flash/flash.d.ts
  src/components/flash/flash.spec.js
  src/components/flash/flash.stories.js
  src/components/flash/index.js
  src/components/message/message.stories.mdx
  src/components/toast/toast.component.js
  src/components/toast/toast.d.ts
  src/components/toast/toast.spec.js
  src/components/toast/toast.stories.js
  src/components/toast/toast.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3376 fix(flat-table): fix incorrect type definitions
  src/components/flat-table/flat-table-body/flat-table-body.d.ts
  src/components/flat-table/flat-table-cell/flat-table-cell.d.ts
  src/components/flat-table/flat-table-header/flat-table-header.d.ts
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#3384 test: upgrade chromatic version
  package-lock.json
  package.json
  src/components/accordion/accordion.stories.mdx
  src/components/portrait/portrait.stories.js
  src/components/profile/profile.stories.js
Labels: Chromatic, Pending Review, Squad Front End

#3380 ci(semantic-release): gpg sign commits
  .github/workflows/semantic-release.yml
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#3390 docs(dev-environment-setup): add GPG signing instructions
  docs/dev-environment-setup.md
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3396 chore(major): update dev-environment with master
  docs/dev-environment-setup.md
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#3395 chore(classic-theme): remove classic theme - FE-3324
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/i18nComponent.feature
  cypress/features/regression/link.feature
  cypress/features/regression/menuList.feature
  cypress/features/regression/mountInApp.feature
  cypress/features/regression/pages.feature
  cypress/features/regression/pagesActions.feature
  cypress/features/regression/themes/themes.feature
  cypress/fixtures/commonComponents/pages.json
  cypress/locators/menu-list/locators.js
  cypress/locators/pages/index.js
  cypress/support/step-definitions/help-steps.js
  cypress/support/step-definitions/pages-steps.js
  src/components/i18n/__definition__.js
  src/components/i18n/__spec__.js
  src/components/i18n/docgenInfo.json
  src/components/i18n/documentation/Info.js
  src/components/i18n/documentation/index.js
  src/components/i18n/documentation/notes.md
  src/components/i18n/i18n.stories.js
  src/components/i18n/i18n.stories.mdx
  src/components/link/__definition__.js
  src/components/link/__snapshots__/link.spec.js.snap
  src/components/link/docgenInfo.json
  src/components/link/documentation/Info.js
  src/components/link/documentation/index.js
  src/components/link/documentation/notes.md
  src/components/link/link-classic.style.js
  src/components/link/link.spec.js
  src/components/link/link.stories.js
  src/components/link/link.stories.mdx
  src/components/link/link.style.js
  src/components/menu-list/__definition__.js
  src/components/menu-list/__spec__.js
  src/components/menu-list/docgenInfo.json
  src/components/menu-list/documentation/index.js
  src/components/menu-list/documentation/notes.md
  src/components/menu-list/menu-list-item/__definition__.js
  src/components/menu-list/menu-list-item/__spec__.js
  src/components/menu-list/menu-list.stories.js
  src/components/menu-list/menu-list.stories.mdx
  src/components/mount-in-app/README.md
  src/components/mount-in-app/__definition__.js
  src/components/mount-in-app/docgenInfo.json
  src/components/mount-in-app/mount-in-app.stories.js
  src/components/mount-in-app/mount-in-app.stories.mdx
  src/components/mount-in-app/notes.md
  src/components/pages/__definition__.js
  src/components/pages/docgenInfo.json
  src/components/pages/documentation/index.js
  src/components/pages/documentation/info.js
  src/components/pages/page/__definition__.js
  src/components/pages/page/page.style.js
  src/components/pages/pages.spec.js
  src/components/pages/pages.stories.js
  src/components/pages/pages.stories.mdx
  src/components/pages/pages.style.js
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#3378 fix(accordion): update headings grid to allow subtitle to span columns FE-3313
  src/components/accordion/accordion.spec.js
  src/components/accordion/accordion.stories.mdx
  src/components/accordion/accordion.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3383 fix(textarea): align label with input text
  src/__experimental__/components/textarea/textarea.spec.js
  src/__experimental__/components/textarea/textarea.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3404 test: increase chromatic delay
  src/components/accordion/accordion.stories.mdx
  src/components/portrait/portrait.stories.js
  src/components/profile/profile.stories.js
Labels: Chromatic, Passed QA, Squad Front End

#3381 chore(table/table-ajax): remove classic theme support - FE-3125/FE-3126
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/table.feature
  cypress/features/regression/tableActions.feature
  cypress/features/regression/tableAjax.feature
  cypress/features/regression/tableWithInputs.feature
  cypress/fixtures/commonComponents/table.json
  cypress/support/step-definitions/table-steps.js
  src/components/table-ajax/__definition__.js
  src/components/table-ajax/docgenInfo.json
  src/components/table-ajax/documentation/index.js
  src/components/table-ajax/documentation/info.js
  src/components/table-ajax/documentation/notes.md
  src/components/table-ajax/index.js
  src/components/table-ajax/package.json
  src/components/table-ajax/table-ajax.component.js
  src/components/table-ajax/table-ajax.spec.js
  src/components/table-ajax/table-ajax.stories.js
  src/components/table-ajax/table-ajax.stories.mdx
  src/components/table/README.md
  src/components/table/__definition__.js
  src/components/table/__snapshots__/table.spec.js.snap
  src/components/table/docgenInfo.json
  src/components/table/documentation/index.js
  src/components/table/documentation/info.js
  src/components/table/documentation/notes.md
  src/components/table/draggable-table-cell/draggable-table-cell.component.js
  src/components/table/draggable-table-cell/draggable-table-cell.spec.js
  src/components/table/table-cell/README.md
  src/components/table/table-cell/__definition__.js
  src/components/table/table-cell/table-cell.spec.js
  src/components/table/table-cell/table-cell.style.js
  src/components/table/table-classic.style.js
  src/components/table/table-header/README.md
  src/components/table/table-header/__definition__.js
  src/components/table/table-header/table-header.spec.js
  src/components/table/table-header/table-header.style.js
  src/components/table/table-row/README.md
  src/components/table/table-row/__definition__.js
  src/components/table/table-row/__snapshots__/table-row.spec.js.snap
  src/components/table/table-row/table-row-classic.style.js
  src/components/table/table-row/table-row-modern.style.js
  src/components/table/table-row/table-row.spec.js
  src/components/table/table-row/table-row.style.js
  src/components/table/table-story-helpers/table-story-wrapper.component.js
  src/components/table/table-subheader/__definition__.js
  src/components/table/table.component.js
  src/components/table/table.spec.js
  src/components/table/table.stories.js
  src/components/table/table.stories.mdx
  src/components/table/table.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3391 feat(definition-list): add support for spacing props - FE-3322
  src/components/definition-list/dd.component.js
  src/components/definition-list/dd.d.ts
  src/components/definition-list/definition-list.spec.js
  src/components/definition-list/definition-list.style.js
  src/components/definition-list/dl.component.js
  src/components/definition-list/dl.d.ts
  src/components/definition-list/dt.component.js
  src/components/definition-list/dt.d.ts
  src/components/tile/tile.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3382 chore(message): remove classic theme support - FE-3115/FE-3142
  src/components/content/content.js
  src/components/message/__snapshots__/message.spec.js.snap
  src/components/message/message-classic-theme-colors.js
  src/components/message/message-classic.style.js
  src/components/message/message-content/__snapshots__/message-content.spec.js.snap
  src/components/message/message-content/message-content-classic.style.js
  src/components/message/message-content/message-content.component.js
  src/components/message/message-content/message-content.spec.js
  src/components/message/message-content/message-content.style.js
  src/components/message/message.component.js
  src/components/message/message.spec.js
  src/components/message/message.stories.js
  src/components/message/message.stories.mdx
  src/components/message/message.style.js
  src/components/message/type-icon/__snapshots__/type-icon.spec.js.snap
  src/components/message/type-icon/type-icon-classic.style.js
  src/components/message/type-icon/type-icon.component.js
  src/components/message/type-icon/type-icon.spec.js
  src/components/message/type-icon/type-icon.style.js
Labels: No UX QA Required, Passed QA, Pending Review, Squad Front End

#3354 feat(select): add option group headers
  src/components/select/index.js
  src/components/select/option-group-header/__snapshots__/option-group-header.spec.js.snap
  src/components/select/option-group-header/index.d.ts
  src/components/select/option-group-header/option-group-header.component.js
  src/components/select/option-group-header/option-group-header.spec.js
  src/components/select/option-group-header/option-group-header.style.js
  src/components/select/select-list/select-list.component.js
  src/components/select/select-list/select-list.spec.js
  src/components/select/simple-select/simple-select.component.js
  src/components/select/simple-select/simple-select.stories.mdx
  src/components/select/utils/get-next-child-by-key.spec.js
  src/components/select/utils/get-next-child-by-text.js
  src/components/select/utils/get-next-child-by-text.spec.js
  src/components/select/utils/get-next-option-by-key.js
  src/components/select/utils/get-next-option-by-key.spec.js
  src/style/themes/base/base-theme.config.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3389 chore(settings-row): remove classic theme support - FE-3121
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/settingsRow.feature
  cypress/locators/settings-row/locators.js
  cypress/support/step-definitions/settings-row-steps.js
  src/components/settings-row/__definition__.js
  src/components/settings-row/__spec__.js
  src/components/settings-row/docgenInfo.json
  src/components/settings-row/documentation/index.js
  src/components/settings-row/documentation/info.js
  src/components/settings-row/documentation/notes.md
  src/components/settings-row/index.js
  src/components/settings-row/package.json
  src/components/settings-row/settings-row.component.js
  src/components/settings-row/settings-row.js
  src/components/settings-row/settings-row.spec.js
  src/components/settings-row/settings-row.stories.js
  src/components/settings-row/settings-row.stories.mdx
  src/components/settings-row/settings-row.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3402 docs(button, link): add router to router link stories
  src/components/button/button.stories.js
  src/components/link/link.stories.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3388 feat(action-popover): add support to place menu above button FE-2956
  src/components/action-popover/action-popover-item.component.js
  src/components/action-popover/action-popover-menu.component.js
  src/components/action-popover/action-popover.component.js
  src/components/action-popover/action-popover.d.ts
  src/components/action-popover/action-popover.spec.js
  src/components/action-popover/action-popover.stories.mdx
  src/components/action-popover/action-popover.style.js
  src/components/flat-table/flat-table.stories.mdx
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3407 feat(menu-item): add prop to hide dropdown arrow for items with submenu FE-3233
  src/components/menu/menu-item/menu-item.component.js
  src/components/menu/menu-item/menu-item.d.ts
  src/components/menu/menu-item/menu-item.spec.js
  src/components/menu/menu-item/menu-item.style.js
  src/components/menu/menu.stories.mdx
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3408 chore(row): remove classic theme support - FE-3120/FE-3075
  cypress/features/regression/row.feature
  cypress/fixtures/commonComponents/row.json
  cypress/locators/row/locators.js
  cypress/support/step-definitions/row-steps.js
  src/components/dialog/dialog.spec.js
  src/components/inline-inputs/inline-inputs.component.js
  src/components/inline-inputs/inline-inputs.spec.js
  src/components/inline-inputs/inline-inputs.style.js
  src/components/row/__definition__.js
  src/components/row/__snapshots__/__spec__.js.snap
  src/components/row/__snapshots__/row.spec.js.snap
  src/components/row/__spec__.js
  src/components/row/column/__definition__.js
  src/components/row/column/__snapshots__/__spec__.js.snap
  src/components/row/column/__spec__.js
  src/components/row/column/column.component.js
  src/components/row/column/column.d.ts
  src/components/row/column/column.js
  src/components/row/column/column.spec.js
  src/components/row/column/column.style.js
  src/components/row/column/package.json
  src/components/row/docgenInfo.json
  src/components/row/documentation/index.js
  src/components/row/documentation/info.js
  src/components/row/documentation/notes.md
  src/components/row/index.d.ts
  src/components/row/index.js
  src/components/row/package.json
  src/components/row/row.component.js
  src/components/row/row.d.ts
  src/components/row/row.js
  src/components/row/row.scss
  src/components/row/row.spec.js
  src/components/row/row.stories.js
  src/components/row/row.stories.mdx
  src/components/row/row.style.js
  src/components/table/__snapshots__/table.spec.js.snap
  src/components/table/table-row/__snapshots__/table-row.spec.js.snap
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3417 refactor: improve validprops documentation
  src/utils/ether/__spec__.js
  src/utils/ether/ether.js
Labels: No UX QA Required, Passed QA, Pending Review, Squad Front End

#3423 feat(textbox): add space props - FE-3306
  src/__experimental__/components/form-field/form-field.component.js
  src/__experimental__/components/form-field/form-field.style.js
  src/__experimental__/components/radio-button/__snapshots__/radio-button-group.spec.js.snap
  src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap
  src/__experimental__/components/textbox/docgenInfo.json
  src/__experimental__/components/textbox/textbox.component.js
  src/__experimental__/components/textbox/textbox.d.ts
  src/__experimental__/components/textbox/textbox.spec.js
  src/components/flat-table/flat-table-checkbox/__snapshots__/flat-table-checkbox.spec.js.snap
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3366 feat(select): async select loader (FE-2647)
  src/components/select/filterable-select/filterable-select.component.js
  src/components/select/filterable-select/filterable-select.spec.js
  src/components/select/filterable-select/filterable-select.stories.mdx
  src/components/select/filterable-select/index.d.ts
  src/components/select/index.d.ts
  src/components/select/multi-select/multi-select.component.js
  src/components/select/multi-select/multi-select.spec.js
  src/components/select/option/option.component.js
  src/components/select/option/option.spec.js
  src/components/select/option/option.style.js
  src/components/select/select-list/select-list.component.js
  src/components/select/select-list/select-list.spec.js
  src/components/select/select-list/select-list.style.js
  src/components/select/simple-select/index.d.ts
  src/components/select/simple-select/simple-select.component.js
  src/components/select/simple-select/simple-select.spec.js
  src/components/select/simple-select/simple-select.stories.mdx
  src/components/select/utils/with-filter.hoc.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3428 refactor(navigation-bar): replace appwrapper styles with box FE-3296
  src/components/navigation-bar/navigation-bar.component.js
  src/components/navigation-bar/navigation-bar.stories.mdx
  src/components/navigation-bar/navigation-bar.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3386 feat(card, tile): consistent footer - FE-2883
  cypress.env.json
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/accessibility/accessibilityDesignSystem.feature
  cypress/features/regression/card.feature
  cypress/features/regression/designSystem/card.feature
  cypress/fixtures/commonComponents/card.json
  cypress/support/step-definitions/card-steps.js
  src/components/card/__snapshots__/card.spec.js.snap
  src/components/card/card-column/docgenInfo.json
  src/components/card/card-footer/card-footer.component.js
  src/components/card/card-footer/card-footer.style.js
  src/components/card/card-footer/docgenInfo.json
  src/components/card/card-row/docgenInfo.json
  src/components/card/card.spec.js
  src/components/card/card.stories.js
  src/components/card/card.stories.mdx
  src/components/card/docgenInfo.json
  src/components/card/documentation/index.js
  src/components/card/documentation/info.js
  src/components/card/documentation/notes.md
  src/components/tile/tile-footer/index.d.ts
  src/components/tile/tile-footer/index.js
  src/components/tile/tile-footer/tile-footer.component.js
  src/components/tile/tile-footer/tile-footer.d.ts
  src/components/tile/tile-footer/tile-footer.spec.js
  src/components/tile/tile-footer/tile-footer.style.js
  src/components/tile/tile.stories.mdx
  src/style/themes/base/base-theme.config.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3416 build: replace cpx with cpy-cli - FE-3344
  package-lock.json
  package.json
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3400 chore(content): remove classic theme - FE-3105
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/content.feature
  src/components/content/README.md
  src/components/content/__definition__.js
  src/components/content/content.stories.js
  src/components/content/content.stories.mdx
  src/components/content/docgenInfo.json
  src/components/content/documentation/index.js
  src/components/content/documentation/notes.md
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3403 chore(preview): remove classic theme - FE-3119
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/preview.feature
  cypress/fixtures/commonComponents/preview.json
  cypress/locators/index.js
  cypress/support/step-definitions/preview-steps.js
  src/components/preview/__definition__.js
  src/components/preview/docgenInfo.json
  src/components/preview/documentation/index.js
  src/components/preview/documentation/info.js
  src/components/preview/preview.component.js
  src/components/preview/preview.stories.js
  src/components/preview/preview.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3435 chore: remove highlight.js package
  package-lock.json
  package.json
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3432 chore(grouped-character): remove classic theme support
  cypress/features/regression/accessibility/accessibilityExperimental.feature
  cypress/features/regression/experimental/groupedCharacter.feature
  cypress/fixtures/experimental/groupedCharacter.json
  src/__experimental__/components/grouped-character/docgenInfo.json
  src/__experimental__/components/grouped-character/documentation/index.js
  src/__experimental__/components/grouped-character/documentation/info.js
  src/__experimental__/components/grouped-character/grouped-character.component.js
  src/__experimental__/components/grouped-character/grouped-character.stories.js
  src/__experimental__/components/grouped-character/grouped-character.stories.mdx
Labels: No UX QA Required, Passed Review, Pending QA, Squad Front End

#3446 test: disable chromatic for delayed stories
  src/components/accordion/accordion.stories.mdx
  src/components/portrait/portrait.stories.js
  src/components/profile/profile.stories.js
Labels: Chromatic, Passed Review, Squad Front End

#3447 test: update validation tests for experimental
  cypress/features/regression/accessibility/accessibilityExperimental.feature
  src/__experimental__/components/checkbox/checkbox.stories.js
  src/__experimental__/components/checkbox/checkbox.stories.mdx
  src/__experimental__/components/radio-button/radio-button.stories.mdx
  src/__experimental__/components/switch/switch.stories.js
  src/__experimental__/components/switch/switch.stories.mdx
Labels: Cypress, Passed Review, Squad Front End

#3433 chore(number): remove classic theme support - FE-3351
  cypress/features/regression/accessibility/accessibilityExperimental.feature
  cypress/features/regression/experimental/numberInput.feature
  cypress/features/regression/experimental/numberInputActions.feature
  cypress/fixtures/experimental/numberInput.json
  src/__experimental__/components/number/documentation/info.js
  src/__experimental__/components/number/documentation/notes.md
  src/__experimental__/components/number/number.stories.js
  src/__experimental__/components/number/number.stories.mdx
  src/__experimental__/components/textbox/textbox.component.js
Labels: No UX QA Required, Pending QA, Pending Review, Squad Front End
