Repository Sage/carbon, pull requests merged in 2020-04, with the labels that each got.

#2744 fix(date): allow passing custom validation icon type prop to component - FE-2640
  src/__experimental__/components/date/date.component.js
  src/__experimental__/components/date/date.spec.js
  src/__experimental__/components/date/date.stories.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2767 fix(search): close icon persists when field is empty (FE-2638)
  cypress/features/regression/test/search.feature
  src/__experimental__/components/search/search.component.js
  src/__experimental__/components/search/search.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2738 docs(collaboration): update collaboration
  CONTRIBUTING.md
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2699 feat(select): add value to custom filter function
  cypress.env.json
  cypress/features/regression/experimental/selectCustomFilter.feature
  cypress/support/step-definitions/common-steps.js
  src/__experimental__/components/select/docgenInfo.json
  src/__experimental__/components/select/option.component.js
  src/__experimental__/components/select/select-list.component.js
  src/__experimental__/components/select/select-list.spec.js
  src/__experimental__/components/select/select.component.js
  src/__experimental__/components/select/select.stories.js
  src/__experimental__/components/textbox/textbox.component.js
  src/components/validations/with-validation.d.ts
  src/components/validations/with-validation.hoc.js
  src/utils/filter-children/filter-children.spec.js
  src/utils/filter-children/filter-children.util.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End, Squad SBC Germany

#2771 docs(pod): add address pod example (FE-2632)
  src/components/pod/pod.stories.mdx
Labels: No QA Required, Passed Review, Passed UX QA, Squad Front End

#2810 feat(radio-button-group): add style override
  cypress/features/regression/test/radioButtonGroupStyleOverrideNoIFrame.feature
  cypress/locators/radioButton/index.js
  cypress/locators/radioButton/locators.js
  cypress/support/step-definitions/radio-button-steps.js
  src/__experimental__/components/fieldset/fieldset.component.js
  src/__experimental__/components/fieldset/fieldset.style.js
  src/__experimental__/components/radio-button/radio-button-group.component.js
  src/__experimental__/components/radio-button/radio-button-group.d.ts
  src/__experimental__/components/radio-button/radio-button-group.spec.js
  src/__experimental__/components/radio-button/radio-button-group.style.js
  src/__experimental__/components/radio-button/radio-button.stories.mdx
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2794 test(pod, switch, checkbox, button): fix ignored TC FE-2658
  cypress/features/regression/button.feature
  cypress/features/regression/buttonAsSibling.feature
  cypress/features/regression/card.feature
  cypress/features/regression/create.feature
  cypress/features/regression/dialog.feature
  cypress/features/regression/experimental/checkbox.feature
  cypress/features/regression/experimental/decimalPrecision.feature
  cypress/features/regression/experimental/textarea.feature
  cypress/features/regression/message.feature
  cypress/features/regression/pod.feature
  cypress/features/regression/portrait.feature
  cypress/features/regression/profile.feature
  cypress/features/regression/test/flatTableIniFrame.feature
  cypress/features/regression/validations/checkboxValidations.feature
  cypress/features/regression/validations/switchValidations.feature
  cypress/locators/card/locators.js
  cypress/locators/checkbox/index.js
  cypress/locators/checkbox/locators.js
  cypress/locators/pod/index.js
  cypress/locators/pod/locators.js
  cypress/support/step-definitions/button-steps.js
  cypress/support/step-definitions/checkbox-steps.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/create-steps.js
  cypress/support/step-definitions/flat-table-steps.js
  cypress/support/step-definitions/pod-steps.js
Labels: Cypress, Squad Front End

#2814 docs(button): add a story with all button options
  cypress.env.json
  cypress/features/build/build.feature
  cypress/features/regression/button.feature
  cypress/support/step-definitions/button-steps.js
  cypress/support/step-definitions/common-steps.js
  src/components/button/button.stories.js
  src/components/button/docgenInfo.json
  src/components/button/documentation/index.js
  src/components/button/documentation/info.js
  src/components/button/documentation/notes.md
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2773 feat(action-popover): add support for custom menu button override FE-2329
  cypress/features/regression/test/actionPopoverStyleOverrideNoIFrame.feature
  cypress/locators/button/index.js
  cypress/support/step-definitions/action-popover-steps.js
  src/components/action-popover/__snapshots__/action-popover.spec.js.snap
  src/components/action-popover/action-popover-item.d.ts
  src/components/action-popover/action-popover-menu.component.js
  src/components/action-popover/action-popover.component.js
  src/components/action-popover/action-popover.d.ts
  src/components/action-popover/action-popover.spec.js
  src/components/action-popover/action-popover.stories.js
  src/components/action-popover/action-popover.stories.mdx
  src/components/action-popover/action-popover.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2842 test(grid, simplecolorpicker): fix cypress tests
  cypress/features/regression/experimental/simpleColorPicker.feature
  cypress/features/regression/heading.feature
  cypress/features/themes/themes.feature
  cypress/locators/grid/index.js
  cypress/support/helper.js
  cypress/support/step-definitions/heading-steps.js
  cypress/support/step-definitions/simple-color-picker-steps.js
  cypress/support/step-definitions/themes-steps.js
Labels: Cypress, Squad Front End

#2840 test(grid): update test to remove internal styled comp from snapshot
  src/components/advanced-color-picker/__snapshots__/advanced-color-picker.spec.js.snap
  src/components/advanced-color-picker/advanced-color-picker.spec.js
  src/components/grid/__snapshots__/grid.spec.js.snap
  src/components/grid/grid.spec.js
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2858 test(accessibility): update for button knob accessility test
  cypress/features/accessibility/accessibility.feature
Labels: Cypress, Squad Front End

#2824 fix(select): allow passing custom validation icon type prop to component - FE-2639
  src/__experimental__/components/select/select.component.js
  src/__experimental__/components/select/select.spec.js
  src/__experimental__/components/select/select.stories.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2865 chore(dependency): revert react day picker upgrade
  package-lock.json
  package.json
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2867 fix(action-popover): add top position when menu right aligned in safari
  src/components/action-popover/__snapshots__/action-popover.spec.js.snap
  src/components/action-popover/action-popover.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2864 chore(deps-dev): bump jest cli and some other deps to remove warnings
  package-lock.json
  package.json
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2876 chore(codeowners): add a codeowner file for carbon repo
  .github/CODEOWNERS
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#2871 chore(deps-dev): move react router to dev dependency
  fixtures/src/main.js
  package-lock.json
  package.json
  src/components/button/button.component.js
  src/components/button/button.d.ts
  src/components/button/button.spec.js
  src/components/button/button.stories.js
  src/components/link/__snapshots__/link.spec.js.snap
  src/components/link/link.component.js
  src/components/link/link.d.ts
  src/components/link/link.spec.js
  src/components/link/link.stories.js
  src/utils/router/__spec__.js
  src/utils/router/package.json
  src/utils/router/router.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2878 chore(fixtures): remove the fixtures test bed FE-2698
  fixtures/.eslintrc
  fixtures/index.html
  fixtures/src/components/chrome.js
  fixtures/src/components/controlled/checkbox-group.js
  fixtures/src/components/controlled/checkbox.js
  fixtures/src/components/controlled/date-range.js
  fixtures/src/components/controlled/date.js
  fixtures/src/components/controlled/decimal.js
  fixtures/src/components/controlled/grouped-character.js
  fixtures/src/components/controlled/multi-select.js
  fixtures/src/components/controlled/number.js
  fixtures/src/components/controlled/radio-button.js
  fixtures/src/components/controlled/search.js
  fixtures/src/components/controlled/select.js
  fixtures/src/components/controlled/simple-color-picker.js
  fixtures/src/components/controlled/switch.js
  fixtures/src/components/controlled/textarea.js
  fixtures/src/components/controlled/textbox.js
  fixtures/src/components/index.js
  fixtures/src/components/log.js
  fixtures/src/components/uncontrolled/checkbox-group.js
  fixtures/src/components/uncontrolled/checkbox.js
  fixtures/src/components/uncontrolled/date-range.js
  fixtures/src/components/uncontrolled/date.js
  fixtures/src/components/uncontrolled/decimal.js
  fixtures/src/components/uncontrolled/grouped-character.js
  fixtures/src/components/uncontrolled/multi-select.js
  fixtures/src/components/uncontrolled/number.js
  fixtures/src/components/uncontrolled/radio-button.js
  fixtures/src/components/uncontrolled/search.js
  fixtures/src/components/uncontrolled/select.js
  fixtures/src/components/uncontrolled/simple-color-picker.js
  fixtures/src/components/uncontrolled/switch.js
  fixtures/src/components/uncontrolled/textarea.js
  fixtures/src/components/uncontrolled/textbox.js
  fixtures/src/main.js
  fixtures/webpack.config.js
  package.json
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#2702 feat(numeral date): create numeral date component
  cypress/features/accessibility/accessibility.feature
  cypress/features/build/build.feature
  cypress/features/regression/test/numeralDate.feature
  cypress/features/regression/validations/dateInputValidations.feature
  cypress/features/regression/validations/radioButtonValidations.feature
  cypress/features/regression/validations/selectValidations.feature
  cypress/features/regression/validations/textareaValidations.feature
  cypress/features/regression/validations/textboxValidations.feature
  cypress/features/regression/validations/validationsBasic.feature
  cypress/locators/numeralDate/index.js
  cypress/locators/numeralDate/locators.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/numeral-date-steps.js
  src/__experimental__/components/numeral-date/index.d.ts
  src/__experimental__/components/numeral-date/index.js
  src/__experimental__/components/numeral-date/numeral-date.component.js
  src/__experimental__/components/numeral-date/numeral-date.d.ts
  src/__experimental__/components/numeral-date/numeral-date.spec.js
  src/__experimental__/components/numeral-date/numeral-date.stories.js
  src/__experimental__/components/numeral-date/numeral-date.stories.mdx
  src/__experimental__/components/numeral-date/numeral-date.style.js
  src/style/themes/base/base-theme.config.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2879 chore: correct scope for carbon code owners
  .github/CODEOWNERS
Labels: Passed Review, Squad Front End

#2877 ci(package.json): update for cucumber-preprocessor dependency
  Dockerfile-cypress
  cypress/features/regression/radioButtonMonthly.feature
  cypress/features/regression/radioButtonWeekly.feature
  cypress/features/regression/radioButtonYearly.feature
  cypress/support/index.js
  package-lock.json
  package.json
Labels: Cypress, Squad Front End

#2881 fix(action-popover): remove display style attribute and add width to menu button
  cypress/support/step-definitions/action-popover-steps.js
  src/components/action-popover/__snapshots__/action-popover.spec.js.snap
  src/components/action-popover/action-popover.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2863 fix(tabs): align with DLS #2862
  src/components/tabs/tab-title/tab-title.spec.js
  src/components/tabs/tab-title/tab-title.style.js
  src/utils/helpers/style-helper/index.js
  src/utils/helpers/style-helper/style-helper.d.ts
  src/utils/helpers/style-helper/style-helper.js
  src/utils/helpers/style-helper/style-helper.spec.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End, Squad X3

#2861 feat(form): create new form component - FE-2530
  src/components/dialog/__snapshots__/dialog.spec.js.snap
  src/components/dialog/dialog.spec.js
  src/components/dialog/dialog.style.js
  src/components/form/form-summary.component.js
  src/components/form/form-summary.d.ts
  src/components/form/form-summary.style.js
  src/components/form/form.component.js
  src/components/form/form.d.ts
  src/components/form/form.spec.js
  src/components/form/form.stories.mdx
  src/components/form/form.style.js
  src/components/form/index.d.ts
  src/components/form/index.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2884 fix(flat-table): update hover color for flat table row and cell
  src/components/flat-table/flat-table-row/flat-table-row.spec.js
  src/components/flat-table/flat-table-row/flat-table-row.style.js
  src/style/themes/base/base-theme.config.js
Labels: No QA Required, Passed Review, Passed UX QA, Squad Front End

#2873 fix(row): allow number prop type for columns, columnSpan, columnOffset
  src/components/row/column/column.d.ts
  src/components/row/column/column.js
  src/components/row/row.d.ts
  src/components/row/row.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End, Squad X3

#2886 test: update version for cucumber preprocessor
  package-lock.json
  package.json
Labels: Cypress, Squad Front End

#2866 feat(flat-table): add new component <Sort /> - FE-2482
  cypress.env.json
  cypress/features/regression/test/flatTableSortable.feature
  cypress/locators/flat-table/index.js
  cypress/locators/flat-table/locators.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/flat-table-steps.js
  src/components/flat-table/__snapshots__/flat-table.spec.js.snap
  src/components/flat-table/flat-table-cell/flat-table-cell.component.js
  src/components/flat-table/flat-table-header/flat-table-header.component.js
  src/components/flat-table/flat-table-row-header/flat-table-row-header.component.js
  src/components/flat-table/flat-table-row/flat-table-row.spec.js
  src/components/flat-table/flat-table-row/flat-table-row.style.js
  src/components/flat-table/flat-table.component.js
  src/components/flat-table/flat-table.spec.js
  src/components/flat-table/flat-table.stories.js
  src/components/flat-table/flat-table.stories.mdx
  src/components/flat-table/flat-table.style.js
  src/components/flat-table/index.js
  src/components/flat-table/sort/index.js
  src/components/flat-table/sort/sort.component.js
  src/components/flat-table/sort/sort.d.ts
  src/components/flat-table/sort/sort.spec.js
  src/components/flat-table/sort/sort.style.js
  src/style/themes/base/base-theme.config.js
  src/utils/helpers/options-helper/options-helper.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2896 fix(date): allow to open date picker by clicking on calendar icon - FE-2680
  cypress/features/regression/experimental/dateInput.feature
  cypress/support/step-definitions/date-input-steps.js
  src/__experimental__/components/date/date.component.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2888 fix(accordion): lack of accordion resize when content size changes
  src/components/accordion/accordion.component.js
  src/components/accordion/accordion.spec.js
  src/components/accordion/accordion.stories.mdx
  src/components/accordion/accordion.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#2772 feat(drawer): create drawer component
  cypress.env.json
  cypress/features/regression/drawer.feature
  cypress/locators/drawer/index.js
  cypress/locators/drawer/locators.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/drawer-steps.js
  src/components/drawer/drawer.component.js
  src/components/drawer/drawer.d.ts
  src/components/drawer/drawer.stories.mdx
  src/components/drawer/drawer.style.js
  src/components/drawer/index.js
  src/style/themes/base/base-theme.config.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2897 test(batchselection, flattablesortable): fix regression failed tests
  cypress/features/regression/test/batchSelection.feature
  cypress/locators/flat-table/index.js
  cypress/support/step-definitions/flat-table-steps.js
Labels: Cypress, Squad Front End

#2895 ci(cypress.sh): split for run script and generate results
  script/docker/cypress.sh
Labels: Cypress, Squad Front End

#2898 docs(contributing): update pr guide
  CONTRIBUTING.md
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#2868 fix(input): improved css style of autofill state for chrome - FE-2090
  src/__experimental__/components/input/__snapshots__/input-presentation.spec.js.snap
  src/__experimental__/components/input/__snapshots__/input.spec.js.snap
  src/__experimental__/components/input/input-presentation.style.js
  src/__experimental__/components/input/input.style.js
  src/__experimental__/components/select/__snapshots__/select.spec.js.snap
  src/__experimental__/components/simple-color-picker/__snapshots__/simple-color-picker.spec.js.snap
  src/__experimental__/components/textarea/__snapshots__/textarea.spec.js.snap
  src/components/pager/__snapshots__/pager.spec.js.snap
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2893 fix(anchor-navigation): incorrect scroll animation in firefox - FE-2611
  src/components/anchor-navigation/anchor-navigation.component.js
  src/components/anchor-navigation/anchor-navigation.spec.js
Labels: No QA Required, Passed QA, Passed Review, Squad Front End

#2901 fix(card-footer): update the footer non interactive text colour to black
  src/components/card/__snapshots__/card.spec.js.snap
  src/components/card/card-footer/card-footer.style.js
  src/components/card/card.spec.js
  src/style/themes/base/base-theme.config.js
Labels: No QA Required, Passed Review, Passed UX QA, Squad Front End

#2764 feat(popover-container): support to be controlled and uncontrolled
  cypress.env.json
  cypress/features/regression/designSystem/popoverContainerDS.feature
  cypress/features/regression/test/popoverContainer.feature
  cypress/locators/popover-container/index.js
  cypress/locators/popover-container/locators.js
  cypress/support/helper.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/popover-container-steps.js
  src/components/popover-container/index.js
  src/components/popover-container/popover-container.component.js
  src/components/popover-container/popover-container.d.ts
  src/components/popover-container/popover-container.spec.js
  src/components/popover-container/popover-container.stories.js
  src/components/popover-container/popover-container.stories.mdx
  src/components/popover-container/popover-container.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#2904 fix(popover-container): revert previous release due to breaking change
  cypress.env.json
  cypress/features/regression/designSystem/popoverContainerDS.feature
  cypress/features/regression/test/popoverContainer.feature
  cypress/locators/popover-container/index.js
  cypress/locators/popover-container/locators.js
  cypress/support/helper.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/popover-container-steps.js
  src/components/popover-container/index.js
  src/components/popover-container/popover-container.component.js
  src/components/popover-container/popover-container.d.ts
  src/components/popover-container/popover-container.spec.js
  src/components/popover-container/popover-container.stories.js
  src/components/popover-container/popover-container.stories.mdx
  src/components/popover-container/popover-container.style.js
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#2905 feat(popover-container): add render props and support controlled usage
  cypress.env.json
  cypress/features/regression/designSystem/popoverContainerDS.feature
  cypress/features/regression/test/popoverContainer.feature
  cypress/locators/popover-container/index.js
  cypress/locators/popover-container/locators.js
  cypress/support/helper.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/popover-container-steps.js
  src/components/popover-container/index.js
  src/components/popover-container/popover-container.component.js
  src/components/popover-container/popover-container.d.ts
  src/components/popover-container/popover-container.spec.js
  src/components/popover-container/popover-container.stories.js
  src/components/popover-container/popover-container.stories.mdx
  src/components/popover-container/popover-container.style.js
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End
