Repository Sage/carbon, pull requests merged in 2021-05, with the labels that each got.

#3860 refactor(menu): rewrite keyboard nav - FE-3695
  cypress/features/regression/designSystem/menu.feature
  cypress/locators/menu/index.js
  cypress/locators/menu/locators.js
  cypress/support/helper.js
  cypress/support/step-definitions/menu-steps.js
  src/components/menu/__internal__/keyboard-navigation/index.js
  src/components/menu/__internal__/keyboard-navigation/index.spec.js
  src/components/menu/__internal__/spec-helper/index.js
  src/components/menu/__internal__/submenu/submenu.component.js
  src/components/menu/__internal__/submenu/submenu.spec.js
  src/components/menu/menu-divider/menu-divider.spec.js
  src/components/menu/menu-item/menu-item.component.js
  src/components/menu/menu-item/menu-item.d.ts
  src/components/menu/menu-item/menu-item.spec.js
  src/components/menu/menu-item/menu-item.style.js
  src/components/menu/menu-segment-title/menu-segment-title.spec.js
  src/components/menu/menu.component.js
  src/components/menu/menu.spec.js
  src/components/menu/menu.stories.mdx
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3964 feat(detail): add styled-system margin support - FE-3539
  src/components/detail/detail.component.js
  src/components/detail/detail.spec.js
  src/components/detail/detail.stories.mdx
  src/components/detail/detail.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3972 refactor(search): update styled system implementation - FE-3519
  src/__experimental__/components/search/search.component.js
  src/__experimental__/components/search/search.d.ts
  src/__experimental__/components/search/search.spec.js
  src/__experimental__/components/search/search.stories.mdx
  src/__experimental__/components/search/search.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3967 feat(image): create new component to support rendering images
  .storybook/utils/styled-system-props.js
  cypress/features/regression/accessibility/accessibilityDesignSystem.feature
  src/__spec_helper__/test-utils.js
  src/components/image/image.component.js
  src/components/image/image.d.ts
  src/components/image/image.spec.js
  src/components/image/image.stories.mdx
  src/components/image/index.d.ts
  src/components/image/index.js
  src/utils/helpers/options-helper/options-helper.d.ts
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3975 refactor(fieldset): update styled system implementation - FE-3511
  src/__experimental__/components/fieldset/__snapshots__/fieldset.spec.js.snap
  src/__experimental__/components/fieldset/fieldset.component.js
  src/__experimental__/components/fieldset/fieldset.d.ts
  src/__experimental__/components/fieldset/fieldset.spec.js
  src/__experimental__/components/fieldset/fieldset.stories.mdx
  src/__experimental__/components/fieldset/fieldset.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3952 fix(search): fix outline appearing onClick around the X icon - FE-3999
  src/__experimental__/components/search/search.component.js
  src/__experimental__/components/search/search.d.ts
  src/__experimental__/components/search/search.spec.js
  src/__experimental__/components/textbox/textbox.component.js
  src/components/select/filterable-select/filterable-select.component.js
  src/components/select/multi-select/multi-select.component.js
Labels: Passed QA, Passed Review, Passed UX QA, Passed a11y Review

#3966 feat(draggable): add styled-system props support - FE-3541
  src/components/draggable/draggable-container.component.js
  src/components/draggable/draggable-item.component.js
  src/components/draggable/draggable-item.style.js
  src/components/draggable/draggable.spec.js
  src/components/draggable/draggable.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3977 refactor(fieldset): update styled system implementation - FE-3512
  src/__experimental__/components/checkbox/__snapshots__/checkbox-group.spec.js.snap
  src/__experimental__/components/radio-button/__snapshots__/radio-button-group.spec.js.snap
  src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap
  src/__experimental__/components/simple-color-picker/__snapshots__/simple-color-picker.spec.js.snap
  src/__internal__/fieldset/fieldset.component.js
  src/__internal__/fieldset/fieldset.d.ts
  src/__internal__/fieldset/fieldset.spec.js
  src/__internal__/fieldset/fieldset.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3988 chore(scripts): remove docgeninfo
  package.json
  script/generate-docgeninfo.sh
  src/utils/helpers/docgen-info/docgen-info.js
  src/utils/helpers/docgen-info/docgen-info.spec.js
  src/utils/helpers/docgen-info/package.json
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#3992 feat(switch): add styled system margin - FE-3521
  src/__experimental__/components/switch/__snapshots__/switch.spec.js.snap
  src/__experimental__/components/switch/switch-slider.component.js
  src/__experimental__/components/switch/switch.d.ts
  src/__experimental__/components/switch/switch.spec.js
  src/__experimental__/components/switch/switch.stories.mdx
  src/__experimental__/components/switch/switch.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3974 refactor(advanced-color-picker): update styled system implementation - FE-3527
  src/components/advanced-color-picker/__snapshots__/advanced-color-picker.spec.js.snap
  src/components/advanced-color-picker/advanced-color-picker.component.js
  src/components/advanced-color-picker/advanced-color-picker.d.ts
  src/components/advanced-color-picker/advanced-color-picker.spec.js
  src/components/advanced-color-picker/advanced-color-picker.stories.mdx
  src/components/advanced-color-picker/advanced-color-picker.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3998 chore(deps): update commitizen
  package-lock.json
  package.json
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#3991 fix(dialog-full-screen): fix content ref forwarding - FE-4062
  src/components/dialog-full-screen/dialog-full-screen.component.js
  src/components/dialog-full-screen/dialog-full-screen.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3983 refactor(select-list): move scroll box on multi column lists
  src/components/select/select-list/select-list.component.js
  src/components/select/select-list/select-list.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3985 chore(deps): remove unused dependencies
  jest.conf.json
  package-lock.json
  package.json
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#3732 refactor(decimal): allow the user to input any value - FE-3705
  cypress/features/regression/experimental/decimalInput.feature
  cypress/features/regression/experimental/decimalPrecision.feature
  cypress/support/step-definitions/decimal-steps.js
  src/__experimental__/components/decimal/decimal.component.js
  src/__experimental__/components/decimal/decimal.spec.js
  src/__experimental__/components/decimal/decimal.stories.js
  src/__experimental__/components/decimal/decimal.stories.mdx
  src/__experimental__/components/decimal/decimal.style.js
  src/utils/helpers/i18n/__spec__.js
  src/utils/helpers/i18n/i18n.js
Labels: Passed QA, Passed Review, Passed UX QA, Passed a11y Review, Squad Front End

#3976 refactor(date-range): update styled system implementation - FE-3509
  src/__experimental__/components/date-range/__snapshots__/date-range.spec.js.snap
  src/__experimental__/components/date-range/date-range.component.js
  src/__experimental__/components/date-range/date-range.d.ts
  src/__experimental__/components/date-range/date-range.spec.js
  src/__experimental__/components/date-range/date-range.stories.mdx
  src/__experimental__/components/date-range/date-range.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4002 feat(simple-color-picker): add styled system margin - FE-3520
  src/__experimental__/components/simple-color-picker/simple-color-picker.component.js
  src/__experimental__/components/simple-color-picker/simple-color-picker.d.ts
  src/__experimental__/components/simple-color-picker/simple-color-picker.spec.js
  src/__experimental__/components/simple-color-picker/simple-color-picker.stories.mdx
Labels: No UX QA Required, Passed Review, Pending QA, Squad Front End

#3973 feat(button-toggle-group): add styled-system props - FE-3533
  src/components/accordion/accordion-group.component.js
  src/components/button-toggle-group/button-toggle-group.component.js
  src/components/button-toggle-group/button-toggle-group.spec.js
  src/components/button-toggle-group/button-toggle-group.stories.mdx
  src/components/duelling-picklist/duelling-picklist.component.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3956 feat(dialog, dialog-full-screen): add help and and fix text wrapping - [ FE-4025 | FE-4026 ]
  cypress/features/regression/experimental/simpleColorPickerAction.feature
  cypress/features/regression/test/advancedColorPickerNoIFrame.feature
  cypress/support/step-definitions/simple-color-picker-steps.js
  src/__internal__/focus-trap/focus-trap.component.js
  src/__internal__/focus-trap/focus-trap.spec.js
  src/components/advanced-color-picker/advanced-color-picker.spec.js
  src/components/dialog-full-screen/dialog-full-screen.component.js
  src/components/dialog-full-screen/dialog-full-screen.spec.js
  src/components/dialog-full-screen/dialog-full-screen.stories.mdx
  src/components/dialog-full-screen/dialog-full-screen.style.js
  src/components/dialog/dialog.component.js
  src/components/dialog/dialog.spec.js
  src/components/dialog/dialog.stories.mdx
  src/components/dialog/dialog.style.js
  src/components/modal/__snapshots__/modal.spec.js.snap
  src/components/modal/modal.component.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#4014 build: upgrade to node 14 lts
  .github/workflows/chromatic-pr.yml
  .github/workflows/chromatic-push.yml
  .github/workflows/ci.yml
  .github/workflows/cypress-pr.yml
  .github/workflows/cypress-push.yml
  .github/workflows/semantic-release.yml
  .github/workflows/storybook.yml
  .nvmrc
  babel.config.js
  check_version.js
  docs/dev-environment-setup.md
  package-lock.json
  package.json
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#4012 feat(date): add styled-system margin support - FE-3508
  src/__experimental__/components/date-range/__snapshots__/date-range.spec.js.snap
  src/__experimental__/components/date/__snapshots__/date.spec.js.snap
  src/__experimental__/components/date/date.component.js
  src/__experimental__/components/date/date.spec.js
  src/__experimental__/components/date/date.stories.mdx
  src/__experimental__/components/date/date.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Pending QA, Squad Front End

#4000 feat(textarea): add styled-system margin prop support - FE-3522
  src/__experimental__/components/textarea/__snapshots__/textarea.spec.js.snap
  src/__experimental__/components/textarea/textarea.component.js
  src/__experimental__/components/textarea/textarea.d.ts
  src/__experimental__/components/textarea/textarea.spec.js
  src/__experimental__/components/textarea/textarea.stories.mdx
  src/__experimental__/components/textarea/textarea.style.js
Labels: No UX QA Required, Passed QA, Pending Review, Squad Front End

#4008 feat(menu-item): add max width prop for truncation
  src/components/menu/__internal__/submenu/submenu.component.js
  src/components/menu/menu-item/menu-item.component.js
  src/components/menu/menu-item/menu-item.spec.js
  src/components/menu/menu-item/menu-item.style.js
  src/components/menu/menu.stories.mdx
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#4006 fix(portrait): fix portrait tooltip error - FE-4057
  cypress/support/step-definitions/portrait-steps.js
  src/components/portrait/portrait-gravatar.component.js
  src/components/portrait/portrait-initials.component.js
  src/components/portrait/portrait.component.js
  src/components/portrait/portrait.spec.js
  src/components/portrait/portrait.stories.mdx
  src/components/portrait/portrait.style.js
  src/components/profile/__snapshots__/profile.spec.js.snap
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3760 refactor(styleoverride): remove styleOverride props from carbon (FE-3776)
  cypress/features/regression/accessibility/accessibilityDesignSystem.feature
  cypress/features/regression/test/actionPopoverStyleOverrideNoIFrame.feature
  src/__experimental__/components/fieldset/fieldset-examples.stories.mdx
  src/__experimental__/components/fieldset/fieldset.component.js
  src/__experimental__/components/fieldset/fieldset.spec.js
  src/__experimental__/components/fieldset/fieldset.stories.mdx
  src/__experimental__/components/fieldset/fieldset.style.js
  src/__experimental__/components/form-field/form-field.component.js
  src/__experimental__/components/form-field/form-field.style.js
  src/__experimental__/components/input/input-presentation.component.js
  src/__experimental__/components/input/input-presentation.style.js
  src/__experimental__/components/input/input.style.js
  src/__experimental__/components/label/label.component.js
  src/__experimental__/components/label/label.d.ts
  src/__experimental__/components/label/label.style.js
  src/__experimental__/components/radio-button/radio-button-group.component.js
  src/__experimental__/components/radio-button/radio-button-group.d.ts
  src/__experimental__/components/radio-button/radio-button-group.spec.js
  src/__experimental__/components/radio-button/radio-button-group.style.js
  src/__experimental__/components/radio-button/radio-button.stories.mdx
  src/__experimental__/components/textbox/__snapshots__/textbox.spec.js.snap
  src/__experimental__/components/textbox/textbox.component.js
  src/__experimental__/components/textbox/textbox.spec.js
  src/__experimental__/components/textbox/textbox.stories.js
  src/__internal__/fieldset/fieldset.component.js
  src/__internal__/fieldset/fieldset.d.ts
  src/__internal__/fieldset/fieldset.style.js
  src/components/accordion/accordion.component.js
  src/components/accordion/accordion.d.ts
  src/components/accordion/accordion.spec.js
  src/components/accordion/accordion.stories.mdx
  src/components/accordion/accordion.style.js
  src/components/action-popover/action-popover.stories.js
  src/components/anchor-navigation/anchor-navigation-item.component.js
  src/components/anchor-navigation/anchor-navigation-item.d.ts
  src/components/anchor-navigation/anchor-navigation.component.js
  src/components/anchor-navigation/anchor-navigation.d.ts
  src/components/anchor-navigation/anchor-navigation.spec.js
  src/components/anchor-navigation/anchor-navigation.stories.js
  src/components/anchor-navigation/anchor-navigation.stories.mdx
  src/components/anchor-navigation/anchor-navigation.style.js
  src/components/anchor-navigation/anchor-section-divider.component.js
  src/components/anchor-navigation/index.d.ts
  src/components/anchor-navigation/index.js
  src/components/pod/pod.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Pioneer Friday, Squad Front End

#4017 refactor(tabs): add missing customLayout prop to propTypes (FE-4089)
  src/components/tabs/tab/tab.component.js
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#4023 refactor(button): add missing props to propTypes
  src/components/button/button.component.js
  src/components/button/button.d.ts
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#4016 feat(icon): 7 new icons, carets directions and larger size
  src/components/icon/fonts/carbon-icons-webfont.woff
  src/components/icon/icon-unicodes.js
  src/style/fonts/carbon-icons-webfont.woff
  src/utils/helpers/options-helper/__spec__.js
  src/utils/helpers/options-helper/options-helper.d.ts
  src/utils/helpers/options-helper/options-helper.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4004 fix(date-range): fix incorrect gaps between date fields - FE-4058
  src/__experimental__/components/date-range/__snapshots__/date-range.spec.js.snap
  src/__experimental__/components/date-range/date-range.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#4022 ci: disable unnecessary chromatic snapshots
  src/components/dialog-full-screen/dialog-full-screen.stories.mdx
Labels: Chromatic, Passed Review, Squad Front End

#3931 refactor(navigation-bar): update styled system navigation bar (FE-3560)
  src/components/navigation-bar/navigation-bar.component.js
  src/components/navigation-bar/navigation-bar.spec.js
  src/components/navigation-bar/navigation-bar.stories.mdx
  src/components/navigation-bar/navigation-bar.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#4030 refactor: change propTypes to be more specific
  src/__experimental__/components/checkbox/checkbox.d.ts
  src/__experimental__/components/form-field/form-field.d.ts
  src/__experimental__/components/switch/switch.component.js
  src/__experimental__/components/switch/switch.d.ts
  src/__experimental__/components/textarea/textarea.d.ts
  src/__experimental__/components/textbox/textbox.d.ts
  src/components/flat-table/flat-table-checkbox/flat-table-checkbox.style.js
  src/components/icon/icon.d.ts
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#4028 fix(pill): fix text wrap if there are multiple words - FE-4076
  src/components/pill/pill.spec.js
  src/components/pill/pill.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4011 feat(decimal): add styled-system margin props
  src/__experimental__/components/decimal/decimal.component.js
  src/__experimental__/components/decimal/decimal.d.ts
  src/__experimental__/components/decimal/decimal.spec.js
  src/__experimental__/components/decimal/decimal.stories.mdx
  src/__experimental__/components/textbox/textbox.component.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4019 feat(container-components): allow null children in containers - FE-4085
  src/__experimental__/components/simple-color-picker/simple-color-picker.component.js
  src/__experimental__/components/simple-color-picker/simple-color-picker.d.ts
  src/__experimental__/components/simple-color-picker/simple-color-picker.spec.js
  src/components/accordion/accordion-group.component.js
  src/components/accordion/accordion-group.d.ts
  src/components/accordion/accordion.spec.js
  src/components/draggable/draggable-container.component.js
  src/components/draggable/draggable-container.d.ts
  src/components/draggable/draggable.spec.js
  src/components/grid/grid-container/grid-container.component.js
  src/components/grid/grid-container/grid-container.d.ts
  src/components/grid/grid-item/grid-item.component.js
  src/components/grid/grid.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4029 fix(checkable-inputs): fix name prop forwarding - FE-3743
  src/__experimental__/components/checkbox/__snapshots__/checkbox-group.spec.js.snap
  src/__experimental__/components/checkbox/__snapshots__/checkbox.spec.js.snap
  src/__experimental__/components/checkbox/checkbox.component.js
  src/__experimental__/components/radio-button/radio-button.d.ts
  src/__experimental__/components/switch/__snapshots__/switch.spec.js.snap
  src/__experimental__/components/switch/switch.component.js
  src/__internal__/checkable-input/checkable-input.d.ts
  src/components/flat-table/flat-table-checkbox/__snapshots__/flat-table-checkbox.spec.js.snap
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4033 refactor(field-help): move to internal folder
  src/__experimental__/components/checkbox/checkbox.spec.js
  src/__experimental__/components/checkbox/checkbox.style.js
  src/__experimental__/components/field-help/__snapshots__/field-help.spec.js.snap
  src/__experimental__/components/field-help/field-help.component.js
  src/__experimental__/components/form-field/form-field.component.js
  src/__experimental__/components/form-field/form-field.spec.js
  src/__experimental__/components/radio-button/radio-button.spec.js
  src/__experimental__/components/radio-button/radio-button.style.js
  src/__experimental__/components/switch/switch.spec.js
  src/__experimental__/components/switch/switch.style.js
  src/__internal__/checkable-input/checkable-input.spec.js
  src/__internal__/checkable-input/checkable-input.style.js
  src/__internal__/field-help/field-help.component.js
  src/__internal__/field-help/field-help.d.ts
  src/__internal__/field-help/field-help.spec.js
  src/__internal__/field-help/field-help.style.js
  src/__internal__/field-help/index.d.ts
  src/__internal__/field-help/index.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4042 docs: remove ambiguity in internal interfaces RFC - FE-4106
  rfcs/text/internal-interfaces.md
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#4035 feat(grouped-character): add styled-system margin support - FE-3514
  src/__experimental__/components/grouped-character/grouped-character.component.js
  src/__experimental__/components/grouped-character/grouped-character.spec.js
  src/__experimental__/components/grouped-character/grouped-character.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4032 feat(drawer): add sticky header and footer options
  cypress/features/regression/designSystem/drawer.feature
  src/__internal__/sticky-footer/index.js
  src/__internal__/sticky-footer/sticky-footer.component.js
  src/__internal__/sticky-footer/sticky-footer.spec.js
  src/__internal__/sticky-footer/sticky-footer.style.js
  src/components/dialog-full-screen/dialog-full-screen.stories.mdx
  src/components/drawer/__internal__/drawer.stories.mdx
  src/components/drawer/__snapshots__/drawer.spec.js.snap
  src/components/drawer/drawer.component.js
  src/components/drawer/drawer.d.ts
  src/components/drawer/drawer.spec.js
  src/components/drawer/drawer.stories.js
  src/components/drawer/drawer.stories.mdx
  src/components/drawer/drawer.style.js
  src/components/drawer/index.d.ts
  src/components/drawer/index.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#4045 fix(sidebar): make close button css more specific
  src/components/sidebar/sidebar.component.js
  src/components/sidebar/sidebar.spec.js
  src/components/sidebar/sidebar.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4043 refactor(search): make experimental search component a regular one - FE-2719
  src/components/drawer/__internal__/drawer.stories.mdx
  src/components/duelling-picklist/duelling-picklist.stories.js
  src/components/menu/__internal__/submenu/submenu.spec.js
  src/components/menu/__internal__/submenu/submenu.style.js
  src/components/menu/menu-item/menu-item.component.js
  src/components/menu/menu.stories.mdx
  src/components/search/index.d.ts
  src/components/search/index.js
  src/components/search/search.component.js
  src/components/search/search.d.ts
  src/components/search/search.spec.js
  src/components/search/search.stories.js
  src/components/search/search.stories.mdx
  src/components/search/search.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4083 ci: update actions and browser
  .github/workflows/cypress-pr.yml
Labels: Cypress, Squad Front End

#4088 test: disable chrome update
  cypress/plugins/index.js
Labels: Cypress, Squad Front End

#3865 feat(tabs): remove internal support for history and url manipulation - FE-3484
  docs/usage-with-routing.stories.mdx
  src/components/tabs/__internal__/tab-title/tab-title.style.js
  src/components/tabs/tabs.component.js
  src/components/tabs/tabs.d.ts
  src/components/tabs/tabs.spec.js
  src/components/tabs/tabs.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4027 fix(date-range): fix react-testing-library errors - FE-4081
  src/__experimental__/components/date-range/date-range.component.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4046 fix(duelling-picklist): add error if children do not have 2 picklist FE-4059
  src/components/duelling-picklist/duelling-picklist.component.js
  src/components/duelling-picklist/duelling-picklist.context.js
  src/components/duelling-picklist/duelling-picklist.spec.js
  src/components/duelling-picklist/picklist-group/picklist-group.component.js
  src/components/duelling-picklist/picklist-group/picklist-group.spec.js
  src/components/duelling-picklist/picklist-group/picklist-group.style.js
  src/components/duelling-picklist/picklist-item/picklist-item.component.js
  src/components/duelling-picklist/picklist-item/picklist-item.spec.js
  src/components/duelling-picklist/picklist/picklist.component.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#4051 feat(portrait): adds prop to specify fallback icon
  cypress/features/regression/portrait.feature
  cypress/fixtures/commonComponents/portrait.json
  cypress/support/step-definitions/portrait-steps.js
  src/components/portrait/portrait.component.js
  src/components/portrait/portrait.spec.js
  src/components/portrait/portrait.stories.js
  src/components/portrait/portrait.stories.mdx
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#4055 fix(date-range): fix incorrect date picker positioning - FE-4101
  src/__experimental__/components/date/__snapshots__/date-picker.spec.js.snap
  src/__experimental__/components/date/date-picker.component.js
  src/__experimental__/components/date/date-picker.spec.js
  src/__experimental__/components/date/date.component.js
  src/__experimental__/components/date/date.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4056 docs(search): update stories with default values to not have same text used for placeholder FE-4069
  src/__experimental__/components/search/search.spec.js
  src/__experimental__/components/search/search.stories.mdx
  src/__experimental__/components/search/search.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4065 fix(tabs): add missing colon to tab-title styles FE-4112
  src/components/tabs/__internal__/tab-title/tab-title.style.js
  src/components/tabs/tab/tab.d.ts
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4058 fix(decimal): fix not working inputs in stories -FE-4100
  src/__experimental__/components/decimal/decimal.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4092 chore(deps): add browserslist as workaround
  package-lock.json
  package.json
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#4066 fix(simple-color-picker): add guard to prevent calling onBlur when undefined FE-4124
  src/__experimental__/components/simple-color-picker/simple-color-picker.component.js
  src/__experimental__/components/simple-color-picker/simple-color-picker.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4099 docs: add cypress and docker documentation - FE-4129
  .gitignore
  cypress/README.md
  cypress/docker-compose.yml
  package.json
Labels: Cypress, Docs, No UX QA Required, Pending QA, Pending Review, Squad Front End

#4020 refactor(checkbox): update styled system implementation - FE-3507
  src/__experimental__/components/checkbox/__snapshots__/checkbox.spec.js.snap
  src/__experimental__/components/checkbox/checkbox-group.component.js
  src/__experimental__/components/checkbox/checkbox-group.d.ts
  src/__experimental__/components/checkbox/checkbox-group.spec.js
  src/__experimental__/components/checkbox/checkbox-validations.stories.mdx
  src/__experimental__/components/checkbox/checkbox.component.js
  src/__experimental__/components/checkbox/checkbox.d.ts
  src/__experimental__/components/checkbox/checkbox.spec.js
  src/__experimental__/components/checkbox/checkbox.stories.mdx
  src/__experimental__/components/checkbox/checkbox.style.js
  src/components/flat-table/flat-table-checkbox/__snapshots__/flat-table-checkbox.spec.js.snap
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4089 fix(tile-select): incorrect ts type definitions (FE-4108)
  src/components/tile-select/tile-select-group.d.ts
  src/components/tile-select/tile-select.d.ts
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#4104 chore: update major/styled-system... with changes from master
  .gitignore
  CHANGELOG.md
  cypress/README.md
  cypress/docker-compose.yml
  cypress/features/regression/portrait.feature
  cypress/fixtures/commonComponents/portrait.json
  cypress/plugins/index.js
  cypress/support/step-definitions/portrait-steps.js
  docs/usage-with-routing.stories.mdx
  package-lock.json
  package.json
  src/__experimental__/components/date-range/date-range.component.js
  src/__experimental__/components/date/__snapshots__/date-picker.spec.js.snap
  src/__experimental__/components/date/date-picker.component.js
  src/__experimental__/components/date/date-picker.spec.js
  src/__experimental__/components/date/date.component.js
  src/__experimental__/components/date/date.spec.js
  src/__experimental__/components/decimal/decimal.stories.mdx
  src/__experimental__/components/search/search.spec.js
  src/__experimental__/components/search/search.stories.mdx
  src/__experimental__/components/search/search.style.js
  src/__experimental__/components/simple-color-picker/simple-color-picker.component.js
  src/__experimental__/components/simple-color-picker/simple-color-picker.stories.mdx
  src/components/duelling-picklist/duelling-picklist.component.js
  src/components/duelling-picklist/duelling-picklist.context.js
  src/components/duelling-picklist/duelling-picklist.spec.js
  src/components/duelling-picklist/picklist-group/picklist-group.component.js
  src/components/duelling-picklist/picklist-group/picklist-group.spec.js
  src/components/duelling-picklist/picklist-group/picklist-group.style.js
  src/components/duelling-picklist/picklist-item/picklist-item.component.js
  src/components/duelling-picklist/picklist-item/picklist-item.spec.js
  src/components/duelling-picklist/picklist/picklist.component.js
  src/components/portrait/portrait.component.js
  src/components/portrait/portrait.spec.js
  src/components/portrait/portrait.stories.js
  src/components/portrait/portrait.stories.mdx
  src/components/tabs/__internal__/tab-title/tab-title.style.js
  src/components/tabs/tab/tab.d.ts
  src/components/tabs/tabs.component.js
  src/components/tabs/tabs.d.ts
  src/components/tabs/tabs.spec.js
  src/components/tabs/tabs.stories.mdx
  src/components/tile-select/tile-select-group.d.ts
  src/components/tile-select/tile-select.d.ts
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#4093 fix(step-sequence): fix incorrect item alignment - FE-4072
  cypress/locators/step-sequence/locators.js
  cypress/support/step-definitions/step-sequence-steps.js
  src/components/step-sequence/__snapshots__/step-sequence.spec.js.snap
  src/components/step-sequence/step-sequence-item/__snapshots__/step-sequence-item.spec.js.snap
  src/components/step-sequence/step-sequence-item/step-sequence-item.component.js
  src/components/step-sequence/step-sequence-item/step-sequence-item.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End
