Repository Sage/carbon, pull requests merged in 2021-07, with the labels that each got.

#4192 fix(fieldset): fix incorrect html structure in internal fieldset - FE-4177
  cypress/locators/simple-color-picker/index.js
  src/__experimental__/components/checkbox/__snapshots__/checkbox-group.spec.js.snap
  src/__experimental__/components/checkbox/checkbox.style.js
  src/__experimental__/components/radio-button/__snapshots__/radio-button-group.spec.js.snap
  src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap
  src/__experimental__/components/radio-button/radio-button-group.style.js
  src/__experimental__/components/simple-color-picker/__snapshots__/simple-color-picker.spec.js.snap
  src/__experimental__/components/simple-color-picker/simple-color-picker.spec.js
  src/__internal__/fieldset/fieldset.component.js
  src/__internal__/fieldset/fieldset.spec.js
  src/__internal__/fieldset/fieldset.style.js
  src/components/validations/validation-icon.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4184 docs(image): fix incorrect image urls - FE-4180
  .assets/brush.svg
  .assets/collaborate.svg
  .assets/flexible.svg
  .assets/hammer.svg
  .assets/plug.svg
  .assets/point.svg
  .storybook/welcome-page/selling-points/selling-point-panel.component.js
  src/components/image/image.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4186 feat(pod): add height prop support - FE-4157
  src/components/pod/__snapshots__/pod.spec.js.snap
  src/components/pod/pod-manager.component.js
  src/components/pod/pod.component.js
  src/components/pod/pod.spec.js
  src/components/pod/pod.stories.mdx
  src/components/pod/pod.style.js
Labels: DO NOT MERGE, No UX QA Required, Passed QA, Passed Review, Squad Front End

#4189 feat(switch): change hover behaviour
  src/__experimental__/components/switch/__snapshots__/switch.spec.js.snap
  src/__experimental__/components/switch/switch.spec.js
  src/__experimental__/components/switch/switch.style.js
  src/style/themes/base/base-theme.config.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#4202 feat(tabs): add headerWidth prop (FE-4161)
  src/components/tabs/__internal__/tabs-header/tabs-header.style.js
  src/components/tabs/tabs.component.js
  src/components/tabs/tabs.d.ts
  src/components/tabs/tabs.spec.js
  src/components/tabs/tabs.stories.js
  src/components/tabs/tabs.stories.mdx
  src/components/tabs/tabs.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#4210 fix(date): provide proper focus outline color - FE-2325
  src/__experimental__/components/date/__snapshots__/date-picker.spec.js.snap
  src/__experimental__/components/date/day-picker.style.js
  src/__experimental__/components/date/navbar/__snapshots__/navbar.spec.js.snap
  src/__experimental__/components/date/navbar/button.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4215 fix(flat-table-row): add support for setting tabindex on subrows with onclick handler passed FE-4202
  src/components/flat-table/flat-table-expandable.stories.mdx
  src/components/flat-table/flat-table-row/flat-table-row.component.js
  src/components/flat-table/flat-table-row/flat-table-row.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4221 fix(note): removes required constraint from name prop type FE-4208
  src/components/note/note.component.js
  src/components/note/note.d.ts
  src/components/note/note.spec.js
  src/components/note/note.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4223 fix(note): ensure date aligns when no edited status
  src/components/note/note.spec.js
  src/components/note/note.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4181 feat(button-toggle): enhance button toggle visuals - FE-4166
  cypress/fixtures/themes/themes.json
  src/components/button-toggle-group/__snapshots__/button-toggle-group.spec.js.snap
  src/components/button-toggle/__snapshots__/button-toggle.spec.js.snap
  src/components/button-toggle/button-toggle.component.js
  src/components/button-toggle/button-toggle.d.ts
  src/components/button-toggle/button-toggle.spec.js
  src/components/button-toggle/button-toggle.stories.mdx
  src/components/button-toggle/button-toggle.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#4212 fix(flat-table): scrolling content in table header - FE-4193
  src/components/flat-table/__snapshots__/flat-table.spec.js.snap
  src/components/flat-table/flat-table-head/flat-table-head.style.js
  src/components/flat-table/flat-table.spec.js
  src/components/flat-table/flat-table.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4224 fix(numeral-date): update size prop type to have correct oneOf syntax
  src/__experimental__/components/numeral-date/numeral-date.component.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4132 fix(flat-table): fix incorrect row outline in safari - FE-4000
  src/components/flat-table/__snapshots__/flat-table.spec.js.snap
  src/components/flat-table/flat-table-row/__snapshots__/flat-table-row.spec.js.snap
  src/components/flat-table/flat-table-row/flat-table-row.spec.js
  src/components/flat-table/flat-table-row/flat-table-row.style.js
  src/components/flat-table/flat-table.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4225 fix(button-toggle): fix hover styling on disabled state - FE-4214
  src/components/button-toggle-group/__snapshots__/button-toggle-group.spec.js.snap
  src/components/button-toggle/__snapshots__/button-toggle.spec.js.snap
  src/components/button-toggle/button-toggle.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4197 feat(flat-table): add new extra-large size
  src/components/flat-table/__snapshots__/flat-table.spec.js.snap
  src/components/flat-table/cell-sizes.style.js
  src/components/flat-table/flat-table-cell/flat-table-cell.component.js
  src/components/flat-table/flat-table-checkbox/flat-table-checkbox.style.js
  src/components/flat-table/flat-table-expandable.stories.mdx
  src/components/flat-table/flat-table-row-header/flat-table-row-header.component.js
  src/components/flat-table/flat-table-row/flat-table-row.component.js
  src/components/flat-table/flat-table-row/flat-table-row.spec.js
  src/components/flat-table/flat-table-row/flat-table-row.style.js
  src/components/flat-table/flat-table.component.js
  src/components/flat-table/flat-table.d.ts
  src/components/flat-table/flat-table.stories.mdx
  src/components/flat-table/flat-table.style.js
  src/components/icon/icon-config.js
  src/components/icon/icon.component.js
  src/components/icon/icon.d.ts
  src/components/icon/icon.style.js
  src/utils/helpers/options-helper/options-helper.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#4172 fix(menu): focus search using arrow keys - FE-4038
  cypress/features/regression/designSystem/menu.feature
  cypress/features/regression/test/search.feature
  cypress/locators/menu/index.js
  cypress/locators/search/index.js
  cypress/support/step-definitions/menu-steps.js
  cypress/support/step-definitions/search-steps.js
  src/__experimental__/components/search/search.component.js
  src/__experimental__/components/search/search.d.ts
  src/__experimental__/components/textbox/textbox.component.js
  src/__experimental__/components/textbox/textbox.d.ts
  src/components/menu/__internal__/submenu/submenu.component.js
  src/components/menu/__internal__/submenu/submenu.spec.js
  src/components/menu/menu-item/menu-item.component.js
  src/components/menu/menu-item/menu-item.spec.js
Labels: Passed QA, Passed Review, Passed UX QA, Passed a11y Review, Squad Front End

#4191 feat(typography): add support for white-space styling and truncation - FE-4158
  src/components/typography/typography.component.js
  src/components/typography/typography.d.ts
  src/components/typography/typography.spec.js
  src/components/typography/typography.stories.mdx
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#4208 feat(carbon-provider): add carbon-provider component - FE-2063
  docs/getting-started.stories.mdx
  src/components/carbon-provider/carbon-provider.component.js
  src/components/carbon-provider/carbon-provider.d.ts
  src/components/carbon-provider/carbon-provider.spec.js
  src/components/carbon-provider/carbon-provider.stories.mdx
  src/components/carbon-provider/index.d.ts
  src/components/carbon-provider/index.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4222 fix(input): remove background on input when required
  src/__experimental__/components/input/__snapshots__/input.spec.js.snap
  src/__experimental__/components/input/input.style.js
  src/__experimental__/components/simple-color-picker/__snapshots__/simple-color-picker.spec.js.snap
  src/__experimental__/components/textarea/__snapshots__/textarea.spec.js.snap
Labels: Passed QA, Passed Review, Squad Front End

#4232 feat(button): add target and rel props
  src/components/button/button.component.js
  src/components/button/button.d.ts
  src/components/button/button.spec.js
  src/components/button/button.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4204 fix(radio-button, checkable-input): fix invalid values in ARIA attributes - FE-1700
  src/__experimental__/components/checkbox/__snapshots__/checkbox-group.spec.js.snap
  src/__experimental__/components/checkbox/__snapshots__/checkbox.spec.js.snap
  src/__experimental__/components/radio-button/__snapshots__/radio-button-group.spec.js.snap
  src/__experimental__/components/radio-button/__snapshots__/radio-button-mapper.spec.js.snap
  src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap
  src/__experimental__/components/radio-button/radio-button-group.component.js
  src/__experimental__/components/switch/__snapshots__/switch.spec.js.snap
  src/__internal__/checkable-input/checkable-input.component.js
  src/__internal__/checkable-input/checkable-input.spec.js
Labels: Passed QA, Passed Review, Passed a11y Review, Squad Front End

#4235 fix(flat-table-row): reduce z-index value when onclick passed to row
  src/components/flat-table/flat-table-row/flat-table-row.spec.js
  src/components/flat-table/flat-table-row/flat-table-row.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4175 fix(filterable-select, multi-select): filter text fixes (FE-4163)
  cypress/features/regression/designSystem/filterableSelect.feature
  src/components/select/filterable-select/filterable-select.component.js
  src/components/select/filterable-select/filterable-select.d.ts
  src/components/select/filterable-select/filterable-select.spec.js
  src/components/select/filterable-select/filterable-select.stories.mdx
  src/components/select/multi-select/multi-select.component.js
  src/components/select/multi-select/multi-select.d.ts
  src/components/select/multi-select/multi-select.spec.js
  src/components/select/multi-select/multi-select.stories.mdx
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#4229 fix(sidebar): Support for Form with stickyFooter FE-4205
  src/components/drawer/drawer.component.js
  src/components/drawer/drawer.d.ts
  src/components/drawer/index.d.ts
  src/components/drawer/index.js
  src/components/flat-table/flat-table-row/flat-table-row.component.js
  src/components/flat-table/flat-table-row/flat-table-row.spec.js
  src/components/flat-table/flat-table.component.js
  src/components/flat-table/flat-table.spec.js
  src/components/flat-table/flat-table.stories.mdx
  src/components/form/form.component.js
  src/components/form/form.spec.js
  src/components/form/form.style.js
  src/components/sidebar/index.js
  src/components/sidebar/sidebar.component.js
  src/components/sidebar/sidebar.d.ts
  src/components/tabs/tabs.component.js
  src/components/tabs/tabs.spec.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#4239 docs(flat-table): improve custom cell padding example - FE-4187
  src/components/flat-table/flat-table.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4233 fix(tile-select): prevent focus outline when tile select is disabled
  src/components/tile-select/tile-select.component.js
  src/components/tile-select/tile-select.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4203 fix(toolbar): add missing focus trigger when right key press and last button focused FE-2823
  cypress/features/regression/accessibility/accessibilityDesignSystem.feature
  cypress/features/regression/designSystem/linkPreview.feature
  cypress/locators/link-preview/index.js
  cypress/support/index.js
  cypress/support/step-definitions/link-preview-steps.js
  cypress/tsconfig.json
  jest.conf.json
  package-lock.json
  package.json
  src/components/link-preview/__internal__/placeholder.component.js
  src/components/link-preview/index.d.ts
  src/components/link-preview/index.js
  src/components/link-preview/link-preview.component.js
  src/components/link-preview/link-preview.d.ts
  src/components/link-preview/link-preview.spec.js
  src/components/link-preview/link-preview.stories.js
  src/components/link-preview/link-preview.stories.mdx
  src/components/link-preview/link-preview.style.js
  src/components/note/index.d.ts
  src/components/note/note.component.js
  src/components/note/note.d.ts
  src/components/note/note.spec.js
  src/components/note/note.stories.mdx
  src/components/note/note.style.js
  src/components/text-editor/__internal__/editor-link/editor-link.component.js
  src/components/text-editor/__internal__/editor-link/editor-link.spec.js
  src/components/text-editor/__internal__/toolbar/toolbar.component.js
  src/components/text-editor/text-editor.component.js
  src/components/text-editor/text-editor.d.ts
  src/components/text-editor/text-editor.spec.js
  src/components/text-editor/text-editor.stories.mdx
  src/components/text-editor/text-editor.style.js
  src/style/themes/base/base-theme.config.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#4246 test(select): add new tests for filterable and multi select FE-4230
  cypress/features/regression/designSystem/filterableSelectEvents.feature
  cypress/features/regression/designSystem/multiSelectEvents.feature
Labels: Cypress, Passed Review, Squad Front End

#4241 fix(simple-color-picker): set cursor to not-allowed when component is disabled - FE-4198
  src/__experimental__/components/simple-color-picker/__snapshots__/simple-color-picker.spec.js.snap
  src/__experimental__/components/simple-color-picker/simple-color-input/simple-color-input.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#4243 fix(search): correct onClick prop ts type
  src/__experimental__/components/search/search.d.ts
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4251 chore: update issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#4256 chore: update issue template
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#4228 fix(tabs): remove default margins and paddings - FE-4215
  src/components/tabs/__internal__/tabs-header/tabs-header.spec.js
  src/components/tabs/__internal__/tabs-header/tabs-header.style.js
  src/components/tabs/tab/tab.component.js
  src/components/tabs/tab/tab.spec.js
  src/components/tabs/tabs.component.js
  src/components/tabs/tabs.spec.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#4238 chore(menu): add truncation to menu in navbar demo FE-4167
  src/components/menu/__internal__/submenu/submenu.component.js
  src/components/menu/__internal__/submenu/submenu.spec.js
  src/components/menu/__internal__/submenu/submenu.style.js
  src/components/menu/index.js
  src/components/menu/menu-divider/menu-divider.component.js
  src/components/menu/menu-divider/menu-divider.spec.js
  src/components/menu/menu-full-screen/index.d.ts
  src/components/menu/menu-full-screen/index.js
  src/components/menu/menu-full-screen/menu-full-screen.component.js
  src/components/menu/menu-full-screen/menu-full-screen.d.ts
  src/components/menu/menu-full-screen/menu-full-screen.spec.js
  src/components/menu/menu-full-screen/menu-full-screen.style.js
  src/components/menu/menu-item/menu-item.component.js
  src/components/menu/menu-item/menu-item.spec.js
  src/components/menu/menu-item/menu-item.style.js
  src/components/menu/menu-segment-title/menu-segment-title.component.js
  src/components/menu/menu-segment-title/menu-segment-title.spec.js
  src/components/menu/menu.component.js
  src/components/menu/menu.context.js
  src/components/menu/menu.stories.mdx
  src/components/menu/menu.style.js
  src/components/menu/scrollable-block/scrollable-block.component.js
  src/components/menu/scrollable-block/scrollable-block.spec.js
  src/components/menu/submenu-block/submenu-block.component.js
  src/components/menu/submenu-block/submenu-block.spec.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#4230 fix(checkable-input): fix invalid aria formats - FE 1980
  src/components/flat-table/flat-table-expandable.stories.mdx
  src/components/flat-table/flat-table.stories.mdx
  src/components/icon-button/icon-button.component.js
Labels: Passed QA, Passed Review, Passed a11y Review, Squad Front End

#4253 chore(flat-table): fix story name typo - FE-4196
  cypress/features/regression/designSystem/flatTable.feature
  src/components/flat-table/flat-table-expandable.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4252 fix(textbox): added missing labeAlign propType definition - FE-2278
  src/__experimental__/components/textbox/textbox.component.js
  src/__experimental__/components/textbox/textbox.d.ts
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4265 fix(dependency): move cypress-real-events to dev dependency
  package-lock.json
  package.json
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#4267 chore: update major/move-experimental-components branch with master
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  CHANGELOG.md
  cypress/features/regression/designSystem/filterableSelectEvents.feature
  cypress/features/regression/designSystem/flatTable.feature
  cypress/features/regression/designSystem/multiSelectEvents.feature
  package-lock.json
  package.json
  src/components/flat-table/flat-table-expandable.stories.mdx
  src/components/flat-table/flat-table.stories.mdx
  src/components/icon-button/icon-button.component.js
  src/components/menu/__internal__/submenu/submenu.component.js
  src/components/menu/__internal__/submenu/submenu.spec.js
  src/components/menu/__internal__/submenu/submenu.style.js
  src/components/menu/index.js
  src/components/menu/menu-divider/menu-divider.component.js
  src/components/menu/menu-divider/menu-divider.spec.js
  src/components/menu/menu-full-screen/index.d.ts
  src/components/menu/menu-full-screen/index.js
  src/components/menu/menu-full-screen/menu-full-screen.component.js
  src/components/menu/menu-full-screen/menu-full-screen.d.ts
  src/components/menu/menu-full-screen/menu-full-screen.spec.js
  src/components/menu/menu-full-screen/menu-full-screen.style.js
  src/components/menu/menu-item/menu-item.component.js
  src/components/menu/menu-item/menu-item.spec.js
  src/components/menu/menu-item/menu-item.style.js
  src/components/menu/menu-segment-title/menu-segment-title.component.js
  src/components/menu/menu-segment-title/menu-segment-title.spec.js
  src/components/menu/menu.component.js
  src/components/menu/menu.context.js
  src/components/menu/menu.stories.mdx
  src/components/menu/menu.style.js
  src/components/menu/scrollable-block/scrollable-block.component.js
  src/components/menu/scrollable-block/scrollable-block.spec.js
  src/components/menu/submenu-block/submenu-block.component.js
  src/components/menu/submenu-block/submenu-block.spec.js
  src/components/search/search.d.ts
  src/components/simple-color-picker/__snapshots__/simple-color-picker.spec.js.snap
  src/components/simple-color-picker/simple-color-input/simple-color-input.style.js
  src/components/tabs/__internal__/tabs-header/tabs-header.spec.js
  src/components/tabs/__internal__/tabs-header/tabs-header.style.js
  src/components/tabs/tab/tab.component.js
  src/components/tabs/tab/tab.spec.js
  src/components/tabs/tabs.component.js
  src/components/tabs/tabs.spec.js
  src/components/textbox/textbox.component.js
  src/components/textbox/textbox.d.ts
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#4266 fix(sidebar): fix header not respecting container width - FE-4232
  src/components/sidebar/__internal__/sidebar-header/sidebar-header.spec.js
  src/components/sidebar/__internal__/sidebar-header/sidebar-header.style.js
  src/components/sidebar/sidebar.component.js
  src/components/sidebar/sidebar.stories.js
  src/components/sidebar/sidebar.stories.mdx
Labels: No UX QA Required, Passed Review, Pending QA, Squad Front End

#4258 chore: update storybook to v6.3.4 - FE-4237
  package-lock.json
  package.json
  src/components/card/card.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4250 feat(multi-select): add pill color override functionality - FE-4226
  src/components/pill/pill.stories.mdx
  src/components/select/multi-select/multi-select.component.js
  src/components/select/multi-select/multi-select.spec.js
  src/components/select/multi-select/multi-select.stories.mdx
  src/components/select/option/index.d.ts
  src/components/select/option/option.component.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#4264 fix(tile-select): disabled prop is not working correctly - FE-4233
  src/components/tile-select/tile-select.component.js
  src/components/tile-select/tile-select.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4263 chore(menu): add test story for automation and visual regression testing fullscreen view
  cypress/features/regression/designSystem/menu.feature
  cypress/locators/menu/index.js
  cypress/locators/menu/locators.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/menu-steps.js
  src/components/menu/menu-full-screen/menu-full-screen.component.js
  src/components/menu/menu.stories.js
Labels: No UX QA Required, Passed QA, Pending Review, Squad Front End

#4260 refactor(drawer): add default value to DrawerSidebarContext - FE-4224
  src/components/drawer/drawer.component.js
  src/components/flat-table/flat-table-row/flat-table-row.component.js
  src/components/flat-table/flat-table.component.js
  src/components/tabs/tabs.component.js
  src/components/tabs/tabs.spec.js
Labels: No UX QA Required, Passed Review, Pending QA, Squad Front End
