Repository Sage/carbon, pull requests merged in 2021-04, with the labels that each got.

#3859 feat(validation-icon): surface ml and mr props to adjust icon spacing FE-3812
  src/components/accordion/accordion.component.js
  src/components/accordion/accordion.spec.js
  src/components/validations/validation-icon.component.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3867 build(npm): add a warning i18n-js will be removed soon
  package.json
  postinstall.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3853 fix(flat-table-row): ensure any cells preceding row headers are also positioned sticky FE-3763
  src/components/flat-table/__snapshots__/flat-table.spec.js.snap
  src/components/flat-table/flat-table-cell/flat-table-cell.component.js
  src/components/flat-table/flat-table-cell/flat-table-cell.style.js
  src/components/flat-table/flat-table-checkbox/flat-table-checkbox.component.js
  src/components/flat-table/flat-table-checkbox/flat-table-checkbox.style.js
  src/components/flat-table/flat-table-header/flat-table-header.component.js
  src/components/flat-table/flat-table-header/flat-table-header.style.js
  src/components/flat-table/flat-table-row-header/flat-table-row-header.component.js
  src/components/flat-table/flat-table-row-header/flat-table-row-header.style.js
  src/components/flat-table/flat-table-row/flat-table-row.component.js
  src/components/flat-table/flat-table-row/flat-table-row.spec.js
  src/components/flat-table/flat-table-row/flat-table-row.style.js
  src/components/flat-table/flat-table.component.js
  src/components/flat-table/flat-table.stories.mdx
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3868 fix(search): stop event propagation for characters and numbers
  src/__experimental__/components/search/search.component.js
  src/__experimental__/components/search/search.spec.js
  src/components/menu/__internal__/submenu/submenu.component.js
  src/components/menu/__internal__/submenu/submenu.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3834 docs(definition-list): add action popover and icon example - FE-3004
  src/components/definition-list/definition-list.stories.mdx
  src/components/tile/tile.stories.mdx
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3856 fix(simple-select): update icon position - 3824
  src/__experimental__/components/input-icon-toggle/input-icon-toggle.style.js
  src/components/select/multi-select/multi-select.component.js
  src/components/select/multi-select/multi-select.spec.js
  src/components/select/multi-select/multi-select.style.js
  src/components/select/select.style.js
  src/components/select/simple-select/simple-select.spec.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3870 feat(icon-button): add styled-system
  src/components/icon-button/icon-button.component.js
  src/components/icon-button/icon-button.spec.js
  src/components/icon-button/icon-button.stories.mdx
  src/components/icon-button/icon-button.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3873 fix(filterable-select): check event has a data element attribute before checking the value FE-3802
  src/components/select/filterable-select/filterable-select.component.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3871 fix(FlatTable): fix gap between table content and sticky footer - FE-3986
  src/components/flat-table/__snapshots__/flat-table.spec.js.snap
  src/components/flat-table/flat-table.component.js
  src/components/flat-table/flat-table.d.ts
  src/components/flat-table/flat-table.spec.js
  src/components/flat-table/flat-table.stories.mdx
  src/components/flat-table/flat-table.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3884 chore(row and column): add deprecation notice to row and column - FE-4003
  src/components/row/column/column.component.js
  src/components/row/row.component.js
  src/components/row/row.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3880 feat(loader): add styled-system - FE-3556
  src/components/loader/loader.component.js
  src/components/loader/loader.spec.js
  src/components/loader/loader.stories.mdx
  src/components/loader/loader.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3878 feat(tabs, tab): surface styled system margin interface in tabs and padding interface in tab FE-3577
  src/components/tabs/__internal__/tabs-header/tabs-header.spec.js
  src/components/tabs/__internal__/tabs-header/tabs-header.style.js
  src/components/tabs/tab/tab.component.js
  src/components/tabs/tab/tab.d.ts
  src/components/tabs/tab/tab.spec.js
  src/components/tabs/tab/tab.style.js
  src/components/tabs/tabs.component.js
  src/components/tabs/tabs.d.ts
  src/components/tabs/tabs.spec.js
  src/components/tabs/tabs.stories.mdx
  src/components/tabs/tabs.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3893 feat(text-editor): surface styled system margin props FE-3578
  src/components/text-editor/text-editor.component.js
  src/components/text-editor/text-editor.d.ts
  src/components/text-editor/text-editor.spec.js
  src/components/text-editor/text-editor.stories.mdx
  src/components/text-editor/text-editor.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3888 feat(note): add styled-system margin props - FE-3561
  src/components/note/__internal__/note.component.js
  src/components/note/__internal__/note.d.ts
  src/components/note/__internal__/note.spec.js
  src/components/note/__internal__/note.stories.mdx
  src/components/note/__internal__/note.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3890 feat(profile): add styled-system margin props - FE-3568
  src/components/profile/profile.component.js
  src/components/profile/profile.spec.js
  src/components/profile/profile.stories.mdx
  src/components/profile/profile.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3785 feat(textbox): change labelHelp type to ReactNode
  src/__experimental__/components/label/label.component.js
  src/__experimental__/components/label/label.d.ts
  src/__experimental__/components/numeral-date/numeral-date.component.js
  src/__experimental__/components/numeral-date/numeral-date.d.ts
  src/__experimental__/components/switch/switch.component.js
  src/__experimental__/components/switch/switch.d.ts
  src/__experimental__/components/textarea/textarea.component.js
  src/__experimental__/components/textarea/textarea.d.ts
  src/__experimental__/components/textbox/textbox.component.js
  src/__experimental__/components/textbox/textbox.d.ts
  src/components/button-toggle-group/button-toggle-group.component.js
  src/components/input-definition.d.ts
  src/components/select/filterable-select/index.d.ts
  src/components/select/multi-select/index.d.ts
  src/components/select/select-textbox/select-textbox.component.js
  src/components/select/simple-select/index.d.ts
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End, Squad Nebula

#3900 feat: add styled system margin to Pod and ShowEditPod - FE-3564 - v3
  src/components/pod/pod.component.js
  src/components/pod/pod.spec.js
  src/components/pod/pod.stories.js
  src/components/pod/pod.stories.mdx
  src/components/pod/pod.style.js
  src/components/show-edit-pod/show-edit-pod.component.js
  src/components/show-edit-pod/show-edit-pod.spec.js
  src/components/show-edit-pod/show-edit-pod.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3903 docs: add info about chromatic for major branch
  docs/testing-styleguide.md
Labels: Chromatic, No QA Required, Passed Review, Squad Front End

#3885 refactor(hr): update styled system implementation
  src/components/hr/hr.component.js
  src/components/hr/hr.d.ts
  src/components/hr/hr.spec.js
  src/components/hr/hr.stories.mdx
  src/components/hr/hr.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3901 feat(split-button): surface styled system margin props
  src/components/split-button/__snapshots__/split-button.spec.js.snap
  src/components/split-button/split-button.component.js
  src/components/split-button/split-button.spec.js
  src/components/split-button/split-button.stories.mdx
  src/components/split-button/split-button.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3883 refactor(tile-footer): remove support for styled system margin props FE-3579
  cypress/features/regression/test/tile.feature
  cypress/fixtures/commonComponents/tile.json
  src/components/detail/detail.stories.mdx
  src/components/heading/heading.stories.mdx
  src/components/tile/tile-footer/tile-footer.component.js
  src/components/tile/tile-footer/tile-footer.d.ts
  src/components/tile/tile-footer/tile-footer.spec.js
  src/components/tile/tile-footer/tile-footer.style.js
  src/components/tile/tile.component.js
  src/components/tile/tile.d.ts
  src/components/tile/tile.spec.js
  src/components/tile/tile.stories.js
  src/components/tile/tile.stories.mdx
  src/components/tile/tile.style.js
  src/components/vertical-divider/vertical-divider.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3872 fix(flat-table-cell, flat-table-header): raise specificity of spacing styles FE-3838
  src/components/flat-table/__snapshots__/flat-table.spec.js.snap
  src/components/flat-table/flat-table-cell/flat-table-cell.component.js
  src/components/flat-table/flat-table-cell/flat-table-cell.d.ts
  src/components/flat-table/flat-table-cell/flat-table-cell.spec.js
  src/components/flat-table/flat-table-cell/flat-table-cell.style.js
  src/components/flat-table/flat-table-expandable.stories.mdx
  src/components/flat-table/flat-table-header/flat-table-header.spec.js
  src/components/flat-table/flat-table-header/flat-table-header.style.js
  src/components/flat-table/flat-table-row-header/flat-table-row-header.component.js
  src/components/flat-table/flat-table-row-header/flat-table-row-header.d.ts
  src/components/flat-table/flat-table-row-header/flat-table-row-header.spec.js
  src/components/flat-table/flat-table-row-header/flat-table-row-header.style.js
  src/components/flat-table/flat-table-row/__snapshots__/flat-table-row.spec.js.snap
  src/components/flat-table/flat-table.stories.mdx
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3896 feat(form, form-summary): Add margin and padding with styled-system, move form-summary to __internal__ folder - FE-3545
  src/components/form/__internal__/form-summary.component.js
  src/components/form/__internal__/form-summary.d.ts
  src/components/form/__internal__/form-summary.style.js
  src/components/form/form.component.js
  src/components/form/form.d.ts
  src/components/form/form.spec.js
  src/components/form/form.stories.mdx
  src/components/form/form.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3877 refactor(multi-select): hide select list on blur
  cypress/features/regression/designSystem/simpleSelectEvents.feature
  src/components/select/filterable-select/filterable-select.component.js
  src/components/select/filterable-select/filterable-select.spec.js
  src/components/select/multi-select/multi-select.component.js
  src/components/select/multi-select/multi-select.spec.js
  src/components/select/simple-select/simple-select.component.js
  src/components/select/simple-select/simple-select.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3906 docs(row and column): add a link to grid component in deprecation warning
  src/components/row/row.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3897 refactor(menu): replace box with styled system
  cypress/locators/menu/locators.js
  src/components/menu/index.d.ts
  src/components/menu/menu-item/menu-item.component.js
  src/components/menu/menu-item/menu-item.d.ts
  src/components/menu/menu-item/menu-item.spec.js
  src/components/menu/menu.component.js
  src/components/menu/menu.d.ts
  src/components/menu/menu.spec.js
  src/components/menu/menu.stories.mdx
  src/components/menu/menu.style.js
  src/components/menu/scrollable-block/index.d.ts
  src/components/menu/scrollable-block/scrollable-block.component.js
  src/components/menu/scrollable-block/scrollable-block.d.ts
  src/components/menu/scrollable-block/scrollable-block.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3886 feat(message): add styled-system margin props - FE-3558
  src/components/message/message-content/message-content.style.js
  src/components/message/message.component.js
  src/components/message/message.spec.js
  src/components/message/message.stories.mdx
  src/components/message/message.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3898 feat(tile-select, tile-select-group): surface styled system margin props FE-3580
  src/components/tile-select/tile-select-group.component.js
  src/components/tile-select/tile-select-group.d.ts
  src/components/tile-select/tile-select.component.js
  src/components/tile-select/tile-select.d.ts
  src/components/tile-select/tile-select.spec.js
  src/components/tile-select/tile-select.stories.mdx
  src/components/tile-select/tile-select.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3907 refactor(scrollable-list): add deprecation warning - FE-4004
  src/components/scrollable-list/scrollable-list.component.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3899 feat(popover-container): surface styled system padding props FE-3565
  src/components/popover-container/popover-container.component.js
  src/components/popover-container/popover-container.d.ts
  src/components/popover-container/popover-container.spec.js
  src/components/popover-container/popover-container.stories.mdx
  src/components/popover-container/popover-container.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3908 fix(day-picker): fix bottom of focus border is cut off by the date picker
  src/__experimental__/components/input/__snapshots__/input.spec.js.snap
  src/__experimental__/components/input/input.style.js
  src/__experimental__/components/simple-color-picker/__snapshots__/simple-color-picker.spec.js.snap
  src/__experimental__/components/textarea/__snapshots__/textarea.spec.js.snap
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3904 feat(settings-row): add support for styled system margin props FE-3572
  src/components/settings-row/settings-row.component.js
  src/components/settings-row/settings-row.spec.js
  src/components/settings-row/settings-row.stories.mdx
  src/components/settings-row/settings-row.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3910 feat(step-sequence): add styled system margin props to StepSequence - FE-3576
  src/components/step-sequence/step-sequence.component.js
  src/components/step-sequence/step-sequence.spec.js
  src/components/step-sequence/step-sequence.stories.mdx
  src/components/step-sequence/step-sequence.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3919 build: run builds on all commits to master FE-4029
  docs/testing-styleguide.md
  package.json
Labels: No UX QA Required, Passed Review, Pending QA, Squad Front End

#3881 feat(preview): add styled system margin props to Preview - FE-3567
  src/components/preview/__snapshots__/preview.spec.js.snap
  src/components/preview/preview.component.js
  src/components/preview/preview.d.ts
  src/components/preview/preview.spec.js
  src/components/preview/preview.stories.mdx
  src/components/preview/preview.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3905 feat(portrait): add styled-system margin - FE-3566
  src/components/portrait/portrait-gravatar.component.js
  src/components/portrait/portrait-initials.component.js
  src/components/portrait/portrait.component.js
  src/components/portrait/portrait.spec.js
  src/components/portrait/portrait.stories.mdx
  src/components/portrait/portrait.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3812 feat(grid-container): use prop-types from styled-system
  src/components/grid/__snapshots__/grid.spec.js.snap
  src/components/grid/grid-container/grid-container.component.js
  src/components/grid/grid-container/grid-container.style.js
  src/components/grid/grid-container/index.d.ts
  src/components/grid/grid-item/grid-item.component.js
  src/components/grid/grid-item/grid-item.style.js
  src/components/grid/grid.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End, Squad Nebula

#3912 refactor(multi-step-wizard): add deprecation warning - FE-4011
  src/components/multi-step-wizard/multi-step-wizard.js
  src/components/multi-step-wizard/multi-step-wizard.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3913 fix(flat-table): fix an alignment gap between the colapse icon and the text
  src/components/flat-table/__snapshots__/flat-table.spec.js.snap
  src/components/flat-table/flat-table-cell/flat-table-cell.style.js
  src/components/flat-table/flat-table-head/flat-table-head.style.js
  src/components/flat-table/flat-table-row-header/flat-table-row-header.component.js
  src/components/flat-table/flat-table-row-header/flat-table-row-header.spec.js
  src/components/flat-table/flat-table-row-header/flat-table-row-header.style.js
  src/components/flat-table/flat-table-row/flat-table-row.spec.js
  src/components/flat-table/flat-table-row/flat-table-row.style.js
  src/components/flat-table/flat-table.spec.js
  src/components/flat-table/flat-table.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3915 refactor(multi-action-button): convert to functional component FE-4018
  src/components/multi-action-button/__snapshots__/multi-action-button.spec.js.snap
  src/components/multi-action-button/multi-action-button.component.js
  src/components/multi-action-button/multi-action-button.spec.js
  src/components/multi-action-button/multi-action-button.stories.mdx
  src/components/multi-action-button/multi-action-button.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3929 chore(deps): remove sass dependencies
  package-lock.json
  package.json
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#3869 build: update storybook to latest version (6.2.8)
  .storybook/main.js
  .storybook/utils/xhr/xhr-mock.js
  cypress/features/regression/carousel.feature
  cypress/features/regression/experimental/groupedCharacter.feature
  cypress/features/regression/test/pager.feature
  cypress/fixtures/experimental/groupedCharacter.json
  cypress/fixtures/groupedCharacter.json
  cypress/locators/pager/index.js
  cypress/locators/pager/locators.js
  cypress/locators/select/index.js
  cypress/locators/select/locators.js
  cypress/support/helper.js
  cypress/support/step-definitions/grouped-character-steps.js
  cypress/support/step-definitions/select-steps.js
  package-lock.json
  package.json
  postcss.config.js
  src/__experimental__/components/date/date.stories.js
  src/__experimental__/components/grouped-character/grouped-character.stories.js
  src/__experimental__/components/number/number.stories.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3902 refactor(flat-table): update styled system implementation
  src/components/flat-table/__snapshots__/flat-table.spec.js.snap
  src/components/flat-table/flat-table-cell/flat-table-cell.component.js
  src/components/flat-table/flat-table-cell/flat-table-cell.d.ts
  src/components/flat-table/flat-table-cell/flat-table-cell.style.js
  src/components/flat-table/flat-table-header/flat-table-header.component.js
  src/components/flat-table/flat-table-header/flat-table-header.d.ts
  src/components/flat-table/flat-table-header/flat-table-header.spec.js
  src/components/flat-table/flat-table-header/flat-table-header.style.js
  src/components/flat-table/flat-table-row-header/flat-table-row-header.component.js
  src/components/flat-table/flat-table-row-header/flat-table-row-header.d.ts
  src/components/flat-table/flat-table-row-header/flat-table-row-header.spec.js
  src/components/flat-table/flat-table-row-header/flat-table-row-header.style.js
  src/components/flat-table/flat-table-row/__snapshots__/flat-table-row.spec.js.snap
  src/components/flat-table/flat-table.component.js
  src/components/flat-table/flat-table.d.ts
  src/components/flat-table/flat-table.spec.js
  src/components/flat-table/flat-table.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3914 refactor(configurable-items): remove component - FE-4013
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/configurableItems.feature
  cypress/features/regression/configurableItemsEvents.feature
  cypress/locators/configurable-items/index.js
  cypress/locators/configurable-items/locators.js
  cypress/support/step-definitions/configurable-items-steps.js
  package-lock.json
  package.json
  src/components/configurable-items/configurable-item-row/configurable-item-row.component.js
  src/components/configurable-items/configurable-item-row/configurable-item-row.style.js
  src/components/configurable-items/configurable-item-row/configurable-items-row.spec.js
  src/components/configurable-items/configurable-item-row/index.js
  src/components/configurable-items/configurable-items.component.js
  src/components/configurable-items/configurable-items.spec.js
  src/components/configurable-items/configurable-items.stories.js
  src/components/configurable-items/configurable-items.stories.mdx
  src/components/configurable-items/configurable-items.style.js
  src/components/configurable-items/index.js
  src/patterns/configurable-items/README.md
  src/patterns/configurable-items/__definition__.js
  src/patterns/configurable-items/__spec__.js
  src/patterns/configurable-items/actions/__spec__.js
  src/patterns/configurable-items/actions/actions.js
  src/patterns/configurable-items/actions/package.json
  src/patterns/configurable-items/configurable-items-content/__spec__.js
  src/patterns/configurable-items/configurable-items-content/configurable-items-content.js
  src/patterns/configurable-items/configurable-items-content/package.json
  src/patterns/configurable-items/configurable-items.js
  src/patterns/configurable-items/constants/constants.js
  src/patterns/configurable-items/constants/package.json
  src/patterns/configurable-items/package.json
  src/patterns/configurable-items/store/__spec__.js
  src/patterns/configurable-items/store/package.json
  src/patterns/configurable-items/store/store.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3917 fix(flat-table): ensure all th elements are sticky when sticky head prop is set FE-4008
  src/components/flat-table/flat-table.spec.js
  src/components/flat-table/flat-table.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3927 refactor(should-component-update): add deprecation warning to helper and decorator - FE-4012
  src/utils/decorators/should-component-update/should-component-update.js
  src/utils/helpers/scrollable-parent/scrollable-parent.js
  src/utils/helpers/should-component-update/should-component-update.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3928 refactor(should-component-update): remove helper and decorator
  src/utils/decorators/should-component-update/__spec__.js
  src/utils/decorators/should-component-update/package.json
  src/utils/decorators/should-component-update/should-component-update.js
  src/utils/helpers/should-component-update/__spec__.js
  src/utils/helpers/should-component-update/package.json
  src/utils/helpers/should-component-update/should-component-update.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3920 refactor(heading): remove className prop
  src/components/heading/heading.component.js
  src/components/heading/heading.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3933 refactor(menu): deprecate submenu block
  src/components/menu/__internal__/submenu/submenu.component.js
  src/components/menu/__internal__/submenu/submenu.spec.js
  src/components/menu/index.d.ts
  src/components/menu/index.js
  src/components/menu/menu-item/menu-item.component.js
  src/components/menu/menu-item/menu-item.spec.js
  src/components/menu/menu.stories.mdx
  src/components/menu/submenu-block/index.d.ts
  src/components/menu/submenu-block/index.js
  src/components/menu/submenu-block/submenu-block.component.js
  src/components/menu/submenu-block/submenu-block.d.ts
  src/components/menu/submenu-block/submenu-block.spec.js
  src/components/menu/submenu-block/submenu-block.style.js
  src/components/vertical-divider/vertical-divider.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3921 refactor: remove MultiStepWizard component - FE-4010
  src/components/multi-step-wizard/README.md
  src/components/multi-step-wizard/__spec__.js
  src/components/multi-step-wizard/multi-step-wizard.js
  src/components/multi-step-wizard/multi-step-wizard.stories.mdx
  src/components/multi-step-wizard/multi-step-wizard.style.js
  src/components/multi-step-wizard/package.json
  src/components/multi-step-wizard/step/__spec__.js
  src/components/multi-step-wizard/step/package.json
  src/components/multi-step-wizard/step/step.js
  src/components/multi-step-wizard/step/step.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3916 fix(flat-table-row): add support for controlling expanded rows externally FE-4007
  cypress/features/regression/designSystem/flatTable.feature
  cypress/features/regression/dialogFullScreen.feature
  cypress/support/step-definitions/common-steps.js
  src/components/flat-table/flat-table-expandable.stories.mdx
  src/components/flat-table/flat-table-row/flat-table-row.component.js
  src/components/flat-table/flat-table-row/flat-table-row.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3924 chore(babel): update config
  README.md
  babel.config.js
  package-lock.json
  package.json
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#3934 refactor(scrollable-list): component removal - FE-3570
  src/components/scrollable-list/as-scrollable-list-item.wrapper.js
  src/components/scrollable-list/index.js
  src/components/scrollable-list/scrollable-list-item.component.js
  src/components/scrollable-list/scrollable-list.component.js
  src/components/scrollable-list/scrollable-list.context.js
  src/components/scrollable-list/scrollable-list.spec.js
  src/components/scrollable-list/scrollable-list.style.js
  src/components/scrollable-list/test-utils.js
  src/components/select/select-list/select-list.component.js
Labels: No UX QA Required, Passed QA, Passed Review, Pending QA, Squad Front End

#3925 feat(tile-select): expand prop types for title, subtitle and description to node FE-4005
  src/components/tile-select/tile-select.component.js
  src/components/tile-select/tile-select.spec.js
  src/components/tile-select/tile-select.stories.mdx
  src/components/tile-select/tile-select.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3918 fix(select-list): fix bottom of focus border is cut off by the select - FE-4022
  cypress/features/regression/designSystem/simpleSelect.feature
  cypress/features/regression/test/simpleSelectNoIFrame.feature
  cypress/fixtures/test/simpleSelect.json
  cypress/support/step-definitions/select-steps.js
  src/components/select/select-list/select-list.component.js
  src/components/select/select-list/select-list.spec.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3942 build: removing POST-CSS from our project and dependencies - FE-4050
  .storybook/main.js
  package-lock.json
  package.json
  postcss.config.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3874 refactor: refactor modal based components - FE-3828
  cypress/features/regression/alert.feature
  cypress/features/regression/confirm.feature
  cypress/features/regression/dialog.feature
  cypress/features/regression/dialogActions.feature
  cypress/features/regression/dialogFullScreen.feature
  cypress/fixtures/commonComponents/alert.json
  cypress/fixtures/commonComponents/confirm.json
  cypress/fixtures/commonComponents/dialog.json
  cypress/fixtures/commonComponents/dialogFullScreen.json
  cypress/support/step-definitions/alert-steps.js
  cypress/support/step-definitions/confirm-steps.js
  cypress/support/step-definitions/dialog-steps.js
  src/__internal__/focus-trap/focus-trap.component.js
  src/__internal__/focus-trap/focus-trap.spec.js
  src/components/alert/alert.component.js
  src/components/alert/alert.spec.js
  src/components/alert/alert.stories.js
  src/components/alert/alert.style.js
  src/components/confirm/confirm.component.js
  src/components/confirm/confirm.spec.js
  src/components/confirm/confirm.stories.js
  src/components/dialog-full-screen/__snapshots__/dialog-full-screen.spec.js.snap
  src/components/dialog-full-screen/content.style.js
  src/components/dialog-full-screen/dialog-full-screen.component.js
  src/components/dialog-full-screen/dialog-full-screen.spec.js
  src/components/dialog-full-screen/dialog-full-screen.stories.js
  src/components/dialog-full-screen/dialog-full-screen.stories.mdx
  src/components/dialog-full-screen/dialog-full-screen.style.js
  src/components/dialog/__snapshots__/dialog.spec.js.snap
  src/components/dialog/dialog.component.js
  src/components/dialog/dialog.spec.js
  src/components/dialog/dialog.stories.js
  src/components/dialog/dialog.style.js
  src/components/form/form.component.js
  src/components/form/form.spec.js
  src/components/form/form.style.js
  src/components/modal/__internal__/modal-manager.spec.js
  src/components/modal/__snapshots__/modal.spec.js.snap
  src/components/modal/modal.component.js
  src/components/modal/modal.spec.js
  src/components/modal/modal.style.js
  src/components/sidebar/sidebar.component.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3941 fix(flat-table-row-header): add zIndex to styles - FE-4028
  src/components/flat-table/__snapshots__/flat-table.spec.js.snap
  src/components/flat-table/flat-table-row-header/flat-table-row-header.style.js
Labels: No UX QA Required, Passed QA, Pending Review, Squad Front End

#3949 feat(duelling-picklist): add support for styled-system margin interface FE-3543
  src/components/duelling-picklist/duelling-picklist.component.js
  src/components/duelling-picklist/duelling-picklist.d.ts
  src/components/duelling-picklist/duelling-picklist.spec.js
  src/components/duelling-picklist/duelling-picklist.stories.mdx
  src/components/duelling-picklist/duelling-picklist.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3944 fix(definition-list): fix dl focused elements outline cut by "overflow: hidden" - FE-3211
  src/components/definition-list/definition-list.spec.js
  src/components/definition-list/definition-list.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3948 feat(card): add styled-system margin support - FE-3534
  src/components/card/card-footer/card-footer.component.js
  src/components/card/card.component.js
  src/components/card/card.spec.js
  src/components/card/card.stories.mdx
  src/components/card/card.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3816 feat: add tooltip and onClick to Portrait component - FE-3502
  src/components/portrait/index.d.ts
  src/components/portrait/portrait-gravatar.d.ts
  src/components/portrait/portrait-initials.d.ts
  src/components/portrait/portrait.component.js
  src/components/portrait/portrait.d.ts
  src/components/portrait/portrait.spec.js
  src/components/portrait/portrait.stories.js
  src/components/portrait/portrait.stories.mdx
  src/components/portrait/portrait.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End, Squad Nebula

#3947 feat(action-popover): add styled-system margin support - FE-3526
  src/components/action-popover/action-popover.component.js
  src/components/action-popover/action-popover.d.ts
  src/components/action-popover/action-popover.spec.js
  src/components/action-popover/action-popover.stories.mdx
  src/components/action-popover/action-popover.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3939 fix(select): fix not resizing list during window resize - FE-3799
  src/components/select/select-list/select-list.component.js
  src/components/select/select-list/select-list.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3951 feat(icon): add support for styled-system margin interface FE-3550
  src/components/accordion/accordion.spec.js
  src/components/help/help.component.js
  src/components/help/help.d.ts
  src/components/help/help.spec.js
  src/components/help/help.stories.mdx
  src/components/help/help.style.js
  src/components/icon/icon.component.js
  src/components/icon/icon.d.ts
  src/components/icon/icon.spec.js
  src/components/icon/icon.stories.mdx
  src/components/icon/icon.style.js
  src/components/portal/__snapshots__/portal.spec.js.snap
  src/components/validations/validation-icon.component.js
  src/components/validations/validation-icon.spec.js
  src/components/validations/validation-icon.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3938 fix(filterable-select): call onChange when value is deleted or not matched - FE-3985
  src/components/select/filterable-select/filterable-select.component.js
  src/components/select/filterable-select/filterable-select.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3950 feat(dialog-full-screen): add auto focus functionality - FE-3968
  src/__internal__/full-screen-heading/full-screen-heading.component.js
  src/__internal__/full-screen-heading/full-screen-heading.style.js
  src/components/alert/alert.component.js
  src/components/confirm/confirm.component.js
  src/components/dialog-full-screen/dialog-full-screen.component.js
  src/components/dialog-full-screen/dialog-full-screen.spec.js
  src/components/dialog-full-screen/dialog-full-screen.style.js
  src/components/dialog/dialog.component.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3954 feat(accordion-group): add styled-system margin support - FE-3525
  src/components/accordion/accordion-group.component.js
  src/components/accordion/accordion-group.d.ts
  src/components/accordion/accordion.spec.js
  src/components/accordion/accordion.stories.js
  src/components/accordion/accordion.stories.mdx
  src/components/accordion/accordion.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3970 chore(mount-in-app): add deprecation warning FE-4060
  src/components/mount-in-app/mount-in-app.js
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#3962 feat(heading): add styled-system margin support - FE-3547
  src/components/heading/heading.component.js
  src/components/heading/heading.spec.js
  src/components/heading/heading.stories.mdx
  src/components/heading/heading.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3965 feat(content): add margin props
  src/components/content/content.component.js
  src/components/content/content.d.ts
  src/components/content/content.spec.js
  src/components/content/content.stories.mdx
  src/components/content/content.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3971 chore(deps): upgrade eslint to latest version
  .eslintrc
  package-lock.json
  package.json
  src/components/table-ajax/table-ajax.spec.js
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End
