Repository Sage/carbon, pull requests merged in 2021-10, with the labels that each got.

#4389 feat(simple-select): add prop to specify the open direction of a select list - FE-4316
  src/components/select/filterable-select/filterable-select.component.js
  src/components/select/filterable-select/filterable-select.d.ts
  src/components/select/filterable-select/filterable-select.spec.js
  src/components/select/filterable-select/filterable-select.stories.mdx
  src/components/select/multi-select/multi-select.component.js
  src/components/select/multi-select/multi-select.d.ts
  src/components/select/multi-select/multi-select.spec.js
  src/components/select/multi-select/multi-select.stories.mdx
  src/components/select/select-list/select-list-container.style.js
  src/components/select/select-list/select-list.component.js
  src/components/select/select-list/select-list.spec.js
  src/components/select/simple-select/simple-select-test.stories.js
  src/components/select/simple-select/simple-select.component.js
  src/components/select/simple-select/simple-select.d.ts
  src/components/select/simple-select/simple-select.spec.js
  src/components/select/simple-select/simple-select.stories.mdx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4439 docs: storybook improvements - FE-4369
  .github/workflows/storybook.yml
  .storybook/main.js
  .storybook/preview.js
  .storybook/welcome-page/welcome.stories.js
  src/components/multi-step-wizard/multi-step-wizard-test.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4447 fix(pager): resolve typing for pageSizeSelectionOptions to be an array of objects
  src/components/pager/pager.d.ts
Labels: Passed Review, No QA Required, No UX QA Required

#4403 feat(storybook): add locale switcher - FE-4251
  .storybook/locale-selector/index.js
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  src/components/i18n-provider/i18n-provider.d.ts
  src/locales/index.d.ts
  src/locales/locale.d.ts
  src/locales/pl-pl.d.ts
  src/locales/pl-pl.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4448 fix(icon): add missing sage_coin to type definition
  src/components/icon/icon.component.js
  src/components/icon/icon.d.ts
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#4392 refactor(form): rewrite sticky footer and add height prop
  cypress/features/regression/dialog.feature
  cypress/locators/dialog/index.js
  cypress/locators/dialog/locators.js
  cypress/support/step-definitions/dialog-steps.js
  src/components/dialog-full-screen/content.style.js
  src/components/dialog-full-screen/dialog-full-screen.component.js
  src/components/dialog/dialog.spec.js
  src/components/dialog/dialog.stories.mdx
  src/components/dialog/dialog.style.js
  src/components/form/form.component.js
  src/components/form/form.d.ts
  src/components/form/form.spec.js
  src/components/form/form.stories.mdx
  src/components/form/form.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End
