Repository Sage/carbon, pull requests merged in 2021-12, with the labels that each got.

#4599 docs(date range): add start and end labels to allow empty value example - FE-4478
  src/components/date-range/date-range.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4602 fix(search): fix incorrect tabindex behaviour - FE-4412
  src/components/search/search.component.js
  src/components/search/search.d.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4601 feat(link): make skip link possible to be translated
  src/components/link/link.component.js
  src/components/link/link.stories.mdx
  src/locales/en-gb.js
  src/locales/pl-pl.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4610 docs(flat-table): fix accessibility violations - FE-4255
  src/components/flat-table/flat-table-expandable.stories.mdx
Labels: Pending Review, Passed QA, No UX QA Required, Squad Front End

#4576 fix(date): date formatting when locale overriden (FE-4391)
  src/__internal__/date/date.js
  src/__internal__/date/date.spec.js
  src/components/date/date.component.js
  src/components/date/date.spec.js
  src/components/date/date.stories.mdx
  src/components/form/form.stories.mdx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4619 fix(tile select): apply opacity to prefixAdornment when component is disabled - FE-4489
  src/components/tile-select/tile-select.component.js
  src/components/tile-select/tile-select.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4575 fix(radio-button): when `labelHelp` prop is provided, ensure help tooltip is displayed on focus - FE-4442
  src/__internal__/label/label.component.js
  src/__internal__/label/label.spec.js
  src/__internal__/validations/validation-icon.component.js
  src/__internal__/validations/validation-icon.style.js
  src/components/help/help.component.js
  src/components/help/help.d.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4598 refactor(design-tokens): move tokens to global class for usage in pop…
  src/__internal__/popover/popover.component.js
  src/__internal__/popover/popover.spec.js
  src/components/portal/__snapshots__/portal.spec.js.snap
  src/components/portal/portal.js
  src/components/portal/portal.spec.js
  src/style/design-tokens/carbon-scoped-tokens-provider/__snapshots__/carbon-scoped-tokens-provider.component.spec.js.snap
  src/style/design-tokens/carbon-scoped-tokens-provider/carbon-scoped-tokens-provider.component.js
  src/style/design-tokens/carbon-scoped-tokens-provider/carbon-scoped-tokens-provider.component.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad DS Alignment

#4545 refactor(decimal): convert class to functional component - FE-3640
  src/components/decimal/decimal-test.stories.mdx
  src/components/decimal/decimal.component.js
  src/components/decimal/decimal.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4592 test: add react tests
  .github/workflows/cypress.yml
  cypress.json
  cypress/README.md
  cypress/fixtures/commonComponents/appWrapper.json
  cypress/fixtures/commonComponents/decimal.json
  cypress/integration/common/appWrapper.feature
  cypress/integration/common/decimalInput.feature
  cypress/integration/common/decimalLocale.feature
  cypress/integration/common/decimalPrecision.feature
  cypress/locators/app-wrapper/index.js
  cypress/locators/app-wrapper/locators.js
  cypress/plugins/index.js
  cypress/support/helper.js
  cypress/support/step-definitions/app-wrapper-steps.js
  cypress/support/step-definitions/decimal-steps.js
  cypress/tsconfig.json
  package-lock.json
  package.json
  src/components/app-wrapper/app-wrapper.test.js
  src/components/decimal/decimal.test.js
Labels: Passed Review, Passed QA, Cypress, Squad Front End

#4608 fix(toggle-button): add missing ARIA and data props (FE-4446)
  src/components/button-toggle-group/__snapshots__/button-toggle-group.spec.js.snap
  src/components/button-toggle-group/button-toggle-group.component.js
  src/components/button-toggle/__snapshots__/button-toggle.spec.js.snap
  src/components/button-toggle/button-toggle-input.component.js
  src/components/button-toggle/button-toggle.component.js
  src/components/button-toggle/button-toggle.d.ts
  src/components/button-toggle/button-toggle.spec.js
  src/components/button-toggle/button-toggle.stories.mdx
  src/components/button-toggle/button-toggle.style.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4624 ci(cypress): use cypress-io gh action for component tests
  .github/workflows/cypress.yml
  cypress/README.md
  package.json
Labels: Passed Review, Pending QA, Cypress, Squad Front End

#4516 feat(label): describe label using design tokens
  src/__internal__/label/__snapshots__/label.spec.js.snap
  src/__internal__/label/icon-wrapper.style.js
  src/__internal__/label/label.spec.js
  src/__internal__/label/label.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4589 feat(radio-button): describe RadioButton component using design tokens
  src/components/radio-button/__snapshots__/radio-button-group.spec.js.snap
  src/components/radio-button/__snapshots__/radio-button-mapper.spec.js.snap
  src/components/radio-button/__snapshots__/radio-button.spec.js.snap
  src/components/radio-button/radio-button.spec.js
  src/components/radio-button/radio-button.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4565 feat(link): describe link component using design tokens
  src/components/card/__snapshots__/card.spec.js.snap
  src/components/link/link.spec.js
  src/components/link/link.stories.mdx
  src/components/link/link.style.js
  src/components/pod/__snapshots__/pod.spec.js.snap
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4574 feat(message): describe Message component using design tokens
  src/components/message/message.spec.js
  src/components/message/message.style.js
  src/components/message/type-icon/__snapshots__/type-icon.spec.js.snap
  src/components/message/type-icon/type-icon.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4648 fix(dismissible-box): remove minWidth from component - FE-4633
  src/components/dismissible-box/dismissible-box.component.js
  src/components/dismissible-box/dismissible-box.d.ts
  src/components/dismissible-box/dismissible-box.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4617 fix(flat-table-cell): ensure that pl prop is correctly applied to a sub row - FE-4306
  cypress/fixtures/commonComponents/flatTable.json
  cypress/integration/common/flatTable.feature
  cypress/locators/flat-table/index.js
  cypress/support/step-definitions/flat-table-steps.js
  src/components/flat-table/__snapshots__/flat-table.spec.js.snap
  src/components/flat-table/flat-table-cell/flat-table-cell.spec.js
  src/components/flat-table/flat-table-cell/flat-table-cell.style.js
  src/components/flat-table/flat-table-expandable.stories.mdx
  src/components/flat-table/flat-table-row/__snapshots__/flat-table-row.spec.js.snap
  src/components/flat-table/flat-table-test.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4653 docs(date): ensure with custom date format example has a code example - FE-4697
  src/components/date/date.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4656 fix(checkbox-group): remove incorrect margin in form (FE-4634)
  src/components/checkbox/checkbox-group.spec.js
  src/components/checkbox/checkbox.style.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4660 test: refactor for AnchorNav component
  cypress/integration/common/anchorNavigation.feature
  cypress/support/step-definitions/anchor-navigation-steps.js
  src/components/anchor-navigation/anchor-navigation.test.js
Labels: Passed Review, Passed QA, Cypress, Squad Front End

#4655 test: refactor test for Alert component
  cypress/fixtures/commonComponents/alert.json
  cypress/integration/common/alert.feature
  cypress/locators/dialog/index.js
  cypress/locators/dialog/locators.js
  cypress/locators/index.js
  cypress/support/step-definitions/alert-steps.js
  src/components/alert/alert.test.js
Labels: Passed Review, Passed QA, Cypress, Squad Front End

#4664 test: update cypress version
  package-lock.json
  package.json
Labels: Passed Review, Cypress, Squad Front End
