Repository Sage/carbon, pull requests merged in 2021-01, with the labels that each got.

#3515 feat(menu): add scrollable block component
  cypress/features/regression/designSystem/menu.feature
  cypress/locators/menu/index.js
  cypress/locators/menu/locators.js
  cypress/support/step-definitions/menu-steps.js
  src/components/menu/__internal__/submenu/submenu.component.js
  src/components/menu/__internal__/submenu/submenu.context.js
  src/components/menu/__internal__/submenu/submenu.spec.js
  src/components/menu/__internal__/submenu/submenu.style.js
  src/components/menu/index.js
  src/components/menu/menu-item/menu-item.component.js
  src/components/menu/menu-item/menu-item.spec.js
  src/components/menu/menu.stories.mdx
  src/components/menu/scrollable-block/index.js
  src/components/menu/scrollable-block/scrollable-block.component.js
  src/components/menu/scrollable-block/scrollable-block.spec.js
  src/components/menu/scrollable-block/scrollable-block.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3530 chore(deps): update dependencies
  .storybook/main.js
  package-lock.json
  package.json
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#3546 docs(menu): correct story examples for icon menuitems
  src/components/menu/menu.stories.mdx
Labels: No UX QA Required, Pending QA, Pending Review, Squad Front End

#3547 docs: update i18n-js peer dependency range
  docs/getting-started.stories.mdx
  package.json
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#3539 fix(tabs): prevent padding override for large tabs with siblings
  src/components/tabs/__internal__/tab-title/tab-title.spec.js
  src/components/tabs/__internal__/tab-title/tab-title.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3544 chore(deps): upgrade jest
  package-lock.json
  package.json
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#3543 refactor(app-wrapper): replace scss with styled component
  src/components/app-wrapper/__definition__.js
  src/components/app-wrapper/app-wrapper.component.js
  src/components/app-wrapper/app-wrapper.spec.js
  src/components/app-wrapper/app-wrapper.stories.js
  src/components/app-wrapper/app-wrapper.style.js
  src/components/app-wrapper/index.js
  src/components/app-wrapper/package.json
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3542 fix(menuitem): check for null children
  src/components/menu/menu-item/menu-item.component.js
  src/components/menu/menu-item/menu-item.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3538 test(package.json): update cypress version
  cypress/support/step-definitions/drawer-steps.js
  cypress/support/step-definitions/heading-steps.js
  cypress/support/step-definitions/pager-steps.js
  cypress/support/step-definitions/select-steps.js
  cypress/support/step-definitions/switch-steps.js
  package-lock.json
  package.json
Labels: Cypress, Squad Front End

#3548 refactor(menulist): replace sass with styled component
  cypress/features/regression/menuList.feature
  cypress/locators/menu-list/locators.js
  cypress/support/step-definitions/menu-list-steps.js
  src/components/menu-list/index.js
  src/components/menu-list/menu-list-item/index.js
  src/components/menu-list/menu-list-item/menu-list-item.component.js
  src/components/menu-list/menu-list-item/menu-list-item.scss
  src/components/menu-list/menu-list-item/menu-list-item.spec.js
  src/components/menu-list/menu-list-item/menu-list-item.style.js
  src/components/menu-list/menu-list-item/package.json
  src/components/menu-list/menu-list.component.js
  src/components/menu-list/menu-list.scss
  src/components/menu-list/menu-list.spec.js
  src/components/menu-list/menu-list.stories.js
  src/components/menu-list/menu-list.stories.mdx
  src/components/menu-list/menu-list.style.js
  src/components/menu-list/package.json
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3553 refactor(inputicon): remove whole decorator
  src/utils/decorators/input-icon/__spec__.js
  src/utils/decorators/input-icon/input-icon.js
  src/utils/decorators/input-icon/input-icon.scss
  src/utils/decorators/input-icon/package.json
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3558 refactor(sidebar): remove redundant transition classes (FE-3078)
  src/components/sidebar/sidebar.component.js
  src/components/sidebar/sidebar.scss
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#3516 feat(flat-table): Migrate dls table styles (FE-2690)
  cypress/features/regression/designSystem/flatTable.feature
  cypress/features/regression/test/flatTableNoiFrame.feature
  cypress/fixtures/designSystem/flatTable.json
  cypress/locators/flat-table/index.js
  cypress/support/step-definitions/flat-table-steps.js
  src/components/flat-table/__snapshots__/flat-table.spec.js.snap
  src/components/flat-table/cell-sizes.style.js
  src/components/flat-table/flat-table-cell/flat-table-cell.component.js
  src/components/flat-table/flat-table-cell/flat-table-cell.spec.js
  src/components/flat-table/flat-table-head/flat-table-head.style.js
  src/components/flat-table/flat-table-header/flat-table-header.component.js
  src/components/flat-table/flat-table-header/flat-table-header.spec.js
  src/components/flat-table/flat-table-header/flat-table-header.style.js
  src/components/flat-table/flat-table-row/__snapshots__/flat-table-row.spec.js.snap
  src/components/flat-table/flat-table-row/flat-table-row.spec.js
  src/components/flat-table/flat-table-row/flat-table-row.style.js
  src/components/flat-table/flat-table-themes.stories.mdx
  src/components/flat-table/flat-table.component.js
  src/components/flat-table/flat-table.d.ts
  src/components/flat-table/flat-table.spec.js
  src/components/flat-table/flat-table.stories.js
  src/components/flat-table/flat-table.stories.mdx
  src/components/flat-table/flat-table.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3533 fix(dialog): dialog centering with dynamic content - FE-3405
  src/__experimental__/components/search/search.d.ts
  src/components/action-popover/action-popover.d.ts
  src/components/dialog/dialog.component.js
  src/components/dialog/dialog.stories.mdx
  src/components/flat-table/flat-table-cell/flat-table-cell.d.ts
  src/components/flat-table/flat-table-header/flat-table-header.d.ts
  src/components/select/option-group-header/index.d.ts
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3565 chore(alert): remove snapshot with theme object in it
  src/components/alert/__snapshots__/alert.spec.js.snap
  src/components/alert/alert.spec.js
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#3545 feat(search): added keyboard navigation to clear text button (FE-3449)
  cypress/features/regression/designSystem/search.feature
  cypress/support/helper.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/search-steps.js
  src/__experimental__/components/input-icon-toggle/input-icon-toggle.component.js
  src/__experimental__/components/input-icon-toggle/input-icon-toggle.d.ts
  src/__experimental__/components/input-icon-toggle/input-icon-toggle.spec.js
  src/__experimental__/components/input-icon-toggle/input-icon-toggle.style.js
  src/__experimental__/components/numeral-date/numeral-date.spec.js
  src/__experimental__/components/search/search.component.js
  src/__experimental__/components/search/search.spec.js
  src/__experimental__/components/textbox/textbox.component.js
  src/components/pager/__internal__/__snapshots__/pager.spec.js.snap
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3555 refactor(detail): replace scss with styled component
  cypress/locators/detail/locators.js
  src/components/detail/__spec__.js
  src/components/detail/detail.component.js
  src/components/detail/detail.scss
  src/components/detail/detail.spec.js
  src/components/detail/detail.stories.js
  src/components/detail/detail.stories.mdx
  src/components/detail/detail.style.js
  src/components/detail/index.js
  src/components/detail/package.json
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3526 refactor(checkbox-group): refactor checkbox group to use fieldset - FE-3412
  cypress/features/regression/accessibility/accessibilityExperimental.feature
  src/__experimental__/components/checkbox/__snapshots__/checkbox-group.spec.js.snap
  src/__experimental__/components/checkbox/checkbox-group.component.js
  src/__experimental__/components/checkbox/checkbox-group.d.ts
  src/__experimental__/components/checkbox/checkbox-group.spec.js
  src/__experimental__/components/checkbox/checkbox-validations.stories.mdx
  src/__experimental__/components/checkbox/checkbox.stories.mdx
  src/__experimental__/components/checkbox/checkbox.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3567 chore(menulist): remove component
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/menuList.feature
  cypress/fixtures/commonComponents/menuList.json
  cypress/locators/menu-list/index.js
  cypress/locators/menu-list/locators.js
  cypress/locators/menu/index.js
  cypress/locators/menu/locators.js
  cypress/support/step-definitions/menu-list-steps.js
  src/components/menu-list/index.js
  src/components/menu-list/menu-list-item/index.js
  src/components/menu-list/menu-list-item/menu-list-item.component.js
  src/components/menu-list/menu-list-item/menu-list-item.spec.js
  src/components/menu-list/menu-list-item/menu-list-item.style.js
  src/components/menu-list/menu-list.component.js
  src/components/menu-list/menu-list.spec.js
  src/components/menu-list/menu-list.stories.js
  src/components/menu-list/menu-list.stories.mdx
  src/components/menu-list/menu-list.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3556 refactor(portal): replace scss with styled-component
  src/__experimental__/components/date/date-picker.component.js
  src/components/modal/__snapshots__/modal.spec.js.snap
  src/components/modal/modal.component.js
  src/components/portal/__snapshots__/__spec__.js.snap
  src/components/portal/index.js
  src/components/portal/package.json
  src/components/portal/portal.js
  src/components/portal/portal.scss
  src/components/portal/portal.style.js
  src/components/select/select-list/select-list.component.js
  src/components/table/__snapshots__/table.spec.js.snap
  src/components/table/table-row/__snapshots__/table-row.spec.js.snap
  src/components/toast/toast.style.js
  src/utils/decorators/tooltip-decorator/tooltip-decorator.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3510 docs(configurable-items): refactor configurable items stories - FE-3443
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/configurableItems.feature
  cypress/features/regression/configurableItemsEvents.feature
  cypress/support/helper.js
  cypress/support/step-definitions/configurable-items-steps.js
  src/components/configurable-items/README.md
  src/components/configurable-items/__definition__.js
  src/components/configurable-items/configurable-item-row/__definition__.js
  src/components/configurable-items/configurable-items.component.js
  src/components/configurable-items/configurable-items.stories.js
  src/components/configurable-items/configurable-items.stories.mdx
  src/components/configurable-items/docgenInfo.json
  src/components/configurable-items/documentation/index.js
  src/components/configurable-items/documentation/notes.md
  src/components/drag-and-drop/drag-and-drop.stories.mdx
  src/components/drag-and-drop/draggable-context/draggable-context.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3583 docs(link): update onclick story to remove incorrect prop usage
  src/components/link/link.stories.mdx
Labels: No QA Required, No UX QA Required, Pending QA, Squad Front End

#3562 feat: add new `pod-manager` component- FE-2940
  cypress/features/regression/pod.feature
  cypress/locators/pod/index.js
  cypress/support/step-definitions/pod-steps.js
  src/components/pod/index.d.ts
  src/components/pod/pod-context.js
  src/components/pod/pod-manager.component.js
  src/components/pod/pod-manager.d.ts
  src/components/pod/pod-manager.spec.js
  src/components/pod/pod.component.js
  src/components/pod/pod.d.ts
  src/components/pod/pod.spec.js
  src/components/pod/pod.stories.mdx
  src/components/pod/pod.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3580 refactor(multi-step-wizard): rewirite scss to styled components (FE-3083, FE-3084)
  src/components/multi-step-wizard/__spec__.js
  src/components/multi-step-wizard/multi-step-wizard.js
  src/components/multi-step-wizard/multi-step-wizard.scss
  src/components/multi-step-wizard/multi-step-wizard.stories.mdx
  src/components/multi-step-wizard/multi-step-wizard.style.js
  src/components/multi-step-wizard/step/__spec__.js
  src/components/multi-step-wizard/step/step.js
  src/components/multi-step-wizard/step/step.scss
  src/components/multi-step-wizard/step/step.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3579 refactor(text-editor): allow user to render toolbar action controls (FE-3368)
  src/components/text-editor/__internal__/text-editor.component.js
  src/components/text-editor/__internal__/text-editor.d.ts
  src/components/text-editor/__internal__/text-editor.stories.mdx
  src/components/text-editor/__internal__/toolbar/toolbar.component.js
  src/components/text-editor/__internal__/toolbar/toolbar.d.ts
  src/components/text-editor/__internal__/toolbar/toolbar.spec.js
  src/components/text-editor/__internal__/toolbar/toolbar.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3594 docs: update naming for buttons
  src/components/button-toggle-group/button-toggle-group-validations.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3587 fix(focus-trap): filter disabled inputs in query selector FE-3382
  src/components/dialog/dialog.stories.mdx
  src/utils/helpers/focus-trap/focus-trap.js
  src/utils/helpers/focus-trap/focus-trap.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3597 fix(date): fix date crashing when allowEmptyValue is set - FE-3471
  src/__experimental__/components/date/date-picker.component.js
  src/__experimental__/components/date/date-picker.spec.js
  src/__experimental__/components/date/date.component.js
  src/__experimental__/components/date/date.spec.js
Labels: No UX QA Required, Passed QA, Pending Review, Squad Front End

#3605 chore(deps): upgrade chromatic
  package-lock.json
  package.json
Labels: No QA Required, No UX QA Required, Pending Review, Squad Front End

#3508 feat: add popper.js to action-popover - FE-3265
  cypress.env.json
  cypress/features/regression/designSystem/actionPopover.feature
  cypress/features/regression/test/actionPopoverNoIFrame.feature
  cypress/support/step-definitions/action-popover-steps.js
  package-lock.json
  package.json
  src/__internal__/popover/index.js
  src/__internal__/popover/popover.component.js
  src/__internal__/popover/popover.spec.js
  src/components/action-popover/__snapshots__/action-popover.spec.js.snap
  src/components/action-popover/action-popover-item.component.js
  src/components/action-popover/action-popover-menu.component.js
  src/components/action-popover/action-popover.component.js
  src/components/action-popover/action-popover.spec.js
  src/components/action-popover/action-popover.stories.mdx
  src/components/action-popover/action-popover.style.js
Labels: Passed QA, Passed Review, Squad Front End

#3585 refactor(content): refactor content to be functional - FE-3079
  cypress/features/regression/accessibility/accessibilityCommon.feature
  cypress/features/regression/accessibility/accessibilityDesignSystem.feature
  cypress/features/regression/content.feature
  cypress/locators/content/locators.js
  cypress/locators/message/locators.js
  cypress/support/step-definitions/content-steps.js
  cypress/support/step-definitions/message-steps.js
  src/components/content/__spec__.js
  src/components/content/content.component.js
  src/components/content/content.d.ts
  src/components/content/content.js
  src/components/content/content.scss
  src/components/content/content.spec.js
  src/components/content/content.stories.js
  src/components/content/content.stories.mdx
  src/components/content/content.style.js
  src/components/content/index.js
  src/components/message/message-content/__snapshots__/message-content.spec.js.snap
  src/components/message/message-content/message-content.component.js
  src/components/tile/__snapshots__/tile.spec.js.snap
  src/style/themes/base/base-theme.config.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3574 feat: add popover to split button - FE-3331
  cypress/features/regression/multiActionButton.feature
  cypress/features/regression/splitButton.feature
  cypress/support/step-definitions/multi-action-button-steps.js
  cypress/support/step-definitions/split-button-steps.js
  src/components/multi-action-button/multi-action-button.component.js
  src/components/multi-action-button/multi-action-button.spec.js
  src/components/multi-action-button/multi-action-button.stories.mdx
  src/components/split-button/__snapshots__/split-button.spec.js.snap
  src/components/split-button/split-button-children.style.js
  src/components/split-button/split-button.component.js
  src/components/split-button/split-button.spec.js
  src/components/split-button/split-button.stories.mdx
Labels: No UX QA Required, Passed QA, Pending Review, Squad Front End

#3611 docs(dev): update gpg docs
  CONTRIBUTING.md
  docs/dev-environment-setup.md
Labels: Pending Review, Squad Front End

#3595 chore(button): remove sibling styling for button - FE-3330
  .storybook/welcome-page/get-started/get-started.component.js
  .storybook/welcome-page/header/header.component.js
  src/__experimental__/components/date/date.stories.mdx
  src/__experimental__/components/search/search.stories.mdx
  src/components/accordion/accordion.stories.mdx
  src/components/button/__snapshots__/button.spec.js.snap
  src/components/button/button.stories.js
  src/components/button/button.stories.mdx
  src/components/button/button.style.js
  src/components/card/card.stories.mdx
  src/components/confirm/confirm.component.js
  src/components/dialog-full-screen/__snapshots__/dialog-full-screen.spec.js.snap
  src/components/form/form.stories.mdx
  src/components/multi-action-button/__snapshots__/multi-action-button.spec.js.snap
  src/components/popover-container/popover-container.stories.mdx
  src/components/select/list-action-button/__snapshots__/list-action-button.spec.js.snap
  src/components/sidebar/sidebar.stories.js
  src/components/sidebar/sidebar.stories.mdx
  src/components/split-button/__snapshots__/split-button.spec.js.snap
  src/components/text-editor/__internal__/text-editor.stories.mdx
  src/components/tile/tile.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3596 fix(sidebar): disable scroll on document if sidebar is open
  src/components/sidebar/sidebar.component.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3593 feat(select): object option comparison tweak (FE-3421)
  cypress.env.json
  cypress/features/regression/designSystem/simpleSelect.feature
  cypress/locators/select/index.js
  cypress/support/step-definitions/select-steps.js
  src/components/select/filterable-select/filterable-select.component.js
  src/components/select/filterable-select/filterable-select.stories.mdx
  src/components/select/multi-select/index.d.ts
  src/components/select/multi-select/multi-select.component.js
  src/components/select/multi-select/multi-select.spec.js
  src/components/select/multi-select/multi-select.stories.mdx
  src/components/select/select-textbox/select-textbox.component.js
  src/components/select/simple-select/simple-select.component.js
  src/components/select/simple-select/simple-select.stories.mdx
  src/components/select/utils/is-expected-option.js
  src/components/select/utils/is-expected-option.spec.js
  src/components/select/utils/is-expected-value.js
  src/components/select/utils/is-expected-value.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3613 docs(flat-table): fix pagination examples - FE-3341
  src/components/flat-table/flat-table.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3619 test: remove duplicated chromatic in parameters
  src/__experimental__/components/numeral-date/numeral-date.stories.js
  src/__experimental__/components/search/search.stories.js
  src/components/accordion/accordion.stories.js
  src/components/action-popover/action-popover.stories.js
  src/components/advanced-color-picker/advanced-color-picker.stories.js
  src/components/alert/alert.stories.js
  src/components/anchor-navigation/anchor-navigation.stories.js
  src/components/anchor-navigation/anchor-navigation.stories.mdx
  src/components/app-wrapper/app-wrapper.stories.js
  src/components/badge/badge.stories.js
  src/components/batch-selection/batch-selection.stories.js
  src/components/button-toggle/button-toggle.stories.js
  src/components/button/button.stories.js
  src/components/card/card.stories.js
  src/components/configurable-items/configurable-items.stories.js
  src/components/confirm/confirm.stories.js
  src/components/content/content.stories.js
  src/components/definition-list/definition-list.stories.js
  src/components/detail/detail.stories.js
  src/components/dialog-full-screen/dialog-full-screen.stories.js
  src/components/dialog/dialog.stories.js
  src/components/draggable/draggable.stories.js
  src/components/duelling-picklist/duelling-picklist.stories.js
  src/components/duelling-picklist/duelling-picklist.stories.mdx
  src/components/flat-table/flat-table.stories.js
  src/components/heading/heading.stories.js
  src/components/help/help.stories.js
  src/components/i18n/i18n.stories.js
  src/components/icon/icon.stories.js
  src/components/link/link.stories.js
  src/components/loader/loader.stories.js
  src/components/loader/loader.stories.mdx
  src/components/message/message.stories.js
  src/components/mount-in-app/mount-in-app.stories.js
  src/components/navigation-bar/navigation-bar.stories.js
  src/components/pages/pages.stories.js
  src/components/pill/pill.stories.js
  src/components/pod/pod.stories.js
  src/components/popover-container/popover-container.stories.js
  src/components/preview/preview.stories.js
  src/components/row/row.stories.js
  src/components/settings-row/settings-row.stories.js
  src/components/show-edit-pod/show-edit-pod.stories.js
  src/components/sidebar/sidebar.stories.js
  src/components/table-ajax/table-ajax.stories.js
  src/components/table/table.stories.js
  src/components/tabs/__internal__/tabs.stories.js
  src/components/tile/tile.stories.js
  src/components/toast/toast.stories.js
  src/components/tooltip/tooltip.stories.js
Labels: Chromatic, Passed QA, Passed Review, Squad Front End
