Repository Sage/carbon, pull requests merged in 2021-11, with the labels that each got.

#4459 fix(tabs): remove extra grey border on warning and info
  src/components/tabs/__internal__/tab-title/tab-title.style.js
  src/components/tabs/__internal__/tabs-header/tabs-header.spec.js
  src/components/tabs/__internal__/tabs-header/tabs-header.style.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4530 test(cypress): fix date input min and max date tests FE-4438
  cypress/features/regression/dateInput.feature
  cypress/fixtures/commonComponents/dateInput.json
  cypress/support/helper.js
  cypress/support/step-definitions/date-input-steps.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4529 fix(tabs): enable validations when renderHiddenTabs set
  src/components/tabs/tabs.component.js
  src/components/tabs/tabs.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4527 chore(scripts): add rfc and version postinstall scripts FE-4169
  .env
  package-lock.json
  package.json
  scripts/check_carbon_version.js
  scripts/check_node_version.js
  scripts/check_rfcs.js
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#4525 fix(multi-select): prevent re-renders from setting selectedValue to undefined FE-4396
  src/components/select/filterable-select/filterable-select.component.js
  src/components/select/filterable-select/filterable-select.spec.js
  src/components/select/multi-select/multi-select.component.js
  src/components/select/multi-select/multi-select.spec.js
  src/components/select/simple-select/simple-select.component.js
  src/components/select/simple-select/simple-select.d.ts
  src/components/select/simple-select/simple-select.spec.js
  src/components/select/utils/is-expected-option.js
  src/components/select/utils/is-expected-option.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4528 refactor(show-edit-pod): refactor from class based to a functional component - FE-3663
  src/components/pod/pod.d.ts
  src/components/show-edit-pod/show-edit-pod-test.stories.js
  src/components/show-edit-pod/show-edit-pod.component.js
  src/components/show-edit-pod/show-edit-pod.d.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4534 ci(chromatic): screenshot all themes - FE-4444
  .storybook/theme-selector/index.js
  .storybook/theme-selector/register.js
  docs/testing-styleguide.md
  package-lock.json
  package.json
  src/components/button-toggle-group/button-toggle-group.stories.mdx
  src/components/button/button-test.stories.mdx
  src/components/date/date.stories.mdx
  src/components/popover-container/popover-container.stories.mdx
  src/components/search/search.stories.mdx
  src/components/vertical-divider/vertical-divider.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4514 feat(multi-action-button): add support for tertiary buttonType FE-4399
  src/components/multi-action-button/multi-action-button.component.js
  src/components/multi-action-button/multi-action-button.config.js
  src/components/multi-action-button/multi-action-button.d.ts
  src/components/multi-action-button/multi-action-button.spec.js
  src/components/multi-action-button/multi-action-button.stories.mdx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4294 docs(date): rfc proposing new date component
  rfcs/text/refactoring-date-component.md
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End, RFC, Final Comments

#4541 docs(dev-roadmap): add row and column to deprecation list FE-4398
  docs/development-roadmap.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4521 refactor(textarea): refactor from class based to a functional component - FE-3632
  src/components/textarea/textarea-test.stories.js
  src/components/textarea/textarea.component.js
  src/components/textarea/textarea.d.ts
Labels: Pending Review, Passed QA, No UX QA Required, Squad Front End

#4548 chore(deps): update design tokens package to the last version
  package-lock.json
  package.json
Labels: Passed Review, No QA Required, No UX QA Required, Squad DS Alignment

#4539 refactor(toast): refactor from class based to a functional component (FE-3665)
  src/components/toast/toast.component.js
  src/components/toast/toast.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4407 refactor(portrait): convert class to functional component (FE-3659)
  cypress/support/step-definitions/portrait-steps.js
  jest.conf.json
  package-lock.json
  package.json
  src/components/portrait/portrait-gravatar.component.js
  src/components/portrait/portrait-gravatar.spec.js
  src/components/portrait/portrait-initials.component.js
  src/components/portrait/portrait-initials.spec.js
  src/components/portrait/portrait.component.js
  src/components/portrait/portrait.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4556 test(cypress): resolve test location
  .github/workflows/cypress-axe-accessibility.yml
  .github/workflows/cypress.yml
  .github/workflows/forked-ci.yml
  .github/workflows/pr.yml
  cypress.json
  cypress/README.md
  cypress/support/accessibility/a11y-utils.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4546 fix(search): correct tabbing order when searchButton true and no search value - FE-4390
  src/components/search/search.component.js
  src/components/search/search.spec.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4554 refactor(detail): refactor to a functional component (FE-3653)
  src/components/detail/detail.component.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4536 fix(loader-bar): change width of loader
  src/components/loader-bar/loader-bar.spec.js
  src/components/loader-bar/loader-bar.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4513 feat(progress-tracker): create new component FE-4367
  src/components/progress-tracker/index.d.ts
  src/components/progress-tracker/index.js
  src/components/progress-tracker/progress-tracker-test.stories.js
  src/components/progress-tracker/progress-tracker.component.js
  src/components/progress-tracker/progress-tracker.config.js
  src/components/progress-tracker/progress-tracker.d.ts
  src/components/progress-tracker/progress-tracker.spec.js
  src/components/progress-tracker/progress-tracker.stories.mdx
  src/components/progress-tracker/progress-tracker.style.js
  src/style/themes/base/base-theme.config.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4563 refactor(date-range): convert component from class-based to functional FE-3639
  src/components/date-range/date-range.component.js
  src/components/date-range/date-range.d.ts
  src/components/date-range/date-range.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4544 feat(focus-trap): add flag to trigger refocus of either last focused element first element FE-4422
  src/__internal__/focus-trap/focus-trap.component.js
  src/__internal__/focus-trap/focus-trap.spec.js
  src/components/modal/__internal__/modal-manager.js
  src/components/modal/__internal__/modal-manager.spec.js
  src/components/modal/modal.component.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4572 fix(page): export page correctly from pages interface
  src/components/pages/index.d.ts
  src/components/pages/index.js
  src/components/pages/pages-test.stories.mdx
  src/components/pages/pages.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4559 docs(storybook): add version switcher
  .github/workflows/semantic-release.yml
  .github/workflows/storybook.yml
  .storybook/manager.js
  .storybook/version-picker/constants.js
  .storybook/version-picker/fetch-data.js
  .storybook/version-picker/index.js
  __mocks__/fs.js
  jest.conf.json
  package-lock.json
  package.json
  scripts/generate_metadata/generate_metadata.mjs
  scripts/generate_metadata/generate_metadata.spec.js
  scripts/generate_metadata/index.mjs
  src/__spec_helper__/index.js
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#4580 build(metadata): use semver gt function to filter versions
  scripts/generate_metadata/generate_metadata.mjs
  scripts/generate_metadata/generate_metadata.spec.js
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#4582 test: update tests for anchorNav
  cypress/integration/common/anchorNavigation.feature
Labels: Pending QA, Cypress, Squad Front End

#4540 fix: fix tokens provider implementation - FE-4443
  .storybook/theme-selector/index.js
  .storybook/theme-selector/register.js
  cypress/locators/step-sequence/index.js
  cypress/locators/step-sequence/locators.js
  cypress/support/step-definitions/grid-steps.js
  src/components/button-toggle/__snapshots__/button-toggle.spec.js.snap
  src/components/carbon-provider/carbon-provider.component.js
  src/components/carbon-provider/carbon-provider.stories.mdx
  src/style/design-tokens/carbon-global-tokens-provider/carbon-global-tokens-provider.component.js
  src/style/design-tokens/carbon-global-tokens-provider/carbon-global-tokens-provider.stories.mdx
  src/style/design-tokens/carbon-global-tokens-provider/index.js
  src/style/design-tokens/carbon-scoped-story-provider/carbon-scoped-tokens-provider.stories.mdx
  src/style/design-tokens/carbon-scoped-tokens-provider/__snapshots__/carbon-scoped-tokens-provider.component.spec.js.snap
  src/style/design-tokens/carbon-scoped-tokens-provider/carbon-scoped-tokens-provider.component.js
  src/style/design-tokens/carbon-scoped-tokens-provider/carbon-scoped-tokens-provider.component.spec.js
  src/style/design-tokens/carbon-scoped-tokens-provider/index.js
  src/style/design-tokens/generate-css-variables.util.spec.js
  src/style/design-tokens/theme-compatibility.util.js
  src/style/themes/aegean/__snapshots__/aegean-theme.spec.js.snap
  src/style/themes/aegean/aegean-theme.config.js
  src/style/themes/aegean/aegean-theme.spec.js
  src/style/themes/base/base-theme.config.js
  src/style/themes/base/index.js
  src/style/themes/mint/__snapshots__/mint-theme.spec.js.snap
  src/style/themes/mint/mint-theme.config.js
  src/style/themes/mint/mint-theme.spec.js
  src/style/themes/none/__snapshots__/none.spec.js.snap
  src/style/themes/none/none.spec.js
  src/style/themes/sage/index.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad DS Alignment

#4573 fix(select): render wrapped text correctly in SelectList - FE-4044
  cypress/integration/common/simpleSelect.feature
  src/components/select/select-list/select-list.component.js
  src/components/select/select-list/select-list.spec.js
  src/components/select/simple-select/simple-select-test.stories.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4590 chore(deps): relsolve semantic release unmet peer dependencies
  package-lock.json
  package.json
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#4577 fix(textbox): change fieldHelp sizing to match input width (FE-4456)
  src/__internal__/field-help/field-help.spec.js
  src/__internal__/field-help/field-help.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4591 fix(design-tokens): fix providing transparency design tokens - FE-4480
  src/style/design-tokens/carbon-scoped-tokens-provider/__snapshots__/carbon-scoped-tokens-provider.component.spec.js.snap
  src/style/design-tokens/debug-theme.util.js
  src/style/themes/aegean/__snapshots__/aegean-theme.spec.js.snap
  src/style/themes/base/base-theme.config.js
  src/style/themes/mint/__snapshots__/mint-theme.spec.js.snap
  src/style/themes/none/__snapshots__/none.spec.js.snap
  src/style/themes/sage/index.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad DS Alignment

#4588 fix(text-editor): replace regex used to format web links
  src/components/text-editor/__internal__/decorators/link-decorator.js
  src/components/text-editor/text-editor.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4569 feat(multi-select): add keyboard accessibility - FE-3294
  cypress/integration/common/multiSelect.feature
  cypress/integration/common/simpleSelect.feature
  cypress/support/helper.js
  cypress/support/step-definitions/select-steps.js
  src/components/select/multi-select/multi-select.component.js
  src/components/select/multi-select/multi-select.spec.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4571 feat(tooltip-provider): add additional props to control tooltip behaviours of wrapped children FE-4457
  src/__internal__/tooltip-provider/index.d.ts
  src/__internal__/tooltip-provider/index.js
  src/components/icon-button/icon-button.component.js
  src/components/icon-button/icon-button.d.ts
  src/components/icon-button/icon-button.spec.js
  src/components/icon-button/icon-button.stories.mdx
  src/components/icon/icon.component.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4578 fix(flat-table): make scrollable content accessible via keyboard
  cypress/integration/common/flatTable.feature
  src/components/flat-table/__snapshots__/flat-table.spec.js.snap
  src/components/flat-table/flat-table.component.js
  src/components/flat-table/flat-table.spec.js
  src/components/flat-table/flat-table.stories.mdx
  src/components/flat-table/flat-table.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4568 docs(tabs): update headerWidth story to use unique id for each tab child FE-4440
  cypress/support/step-definitions/tabs-steps.js
  src/components/tabs/__internal__/tab-title/index.d.ts
  src/components/tabs/__internal__/tab-title/tab-title.component.js
  src/components/tabs/__internal__/tab-title/tab-title.d.ts
  src/components/tabs/__internal__/tab-title/tab-title.spec.js
  src/components/tabs/__internal__/tab-title/tab-title.style.js
  src/components/tabs/__internal__/tabs-header/index.d.ts
  src/components/tabs/__internal__/tabs-header/tab-header.d.ts
  src/components/tabs/__internal__/tabs-header/tabs-header.style.js
  src/components/tabs/tabs.component.js
  src/components/tabs/tabs.stories.mdx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4594 docs: disable version switcher in dev mode
  .github/workflows/semantic-release.yml
  .storybook/manager.js
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#4596 ci(codesandbox): add typescript template for pr generation
  .codesandbox/ci.json
Labels: Passed Review, No QA Required, No UX QA Required, Squad DS Alignment

#4583 fix(inputs): make validation messages readable by voiceover - FE-4380
  src/__internal__/checkable-input/__snapshots__/hidden-checkable-input.spec.js.snap
  src/__internal__/checkable-input/checkable-input.component.js
  src/__internal__/checkable-input/checkable-input.d.ts
  src/__internal__/checkable-input/checkable-input.spec.js
  src/__internal__/checkable-input/hidden-checkable-input.component.js
  src/__internal__/checkable-input/hidden-checkable-input.d.ts
  src/__internal__/checkable-input/hidden-checkable-input.spec.js
  src/__internal__/form-field/__snapshots__/form-field.spec.js.snap
  src/__internal__/form-field/form-field.component.js
  src/__internal__/form-field/form-field.d.ts
  src/__internal__/form-field/form-field.spec.js
  src/__internal__/input-icon-toggle/input-icon-toggle.component.js
  src/__internal__/input-icon-toggle/input-icon-toggle.d.ts
  src/__internal__/input-icon-toggle/input-icon-toggle.spec.js
  src/__internal__/label/label.component.js
  src/__internal__/label/label.d.ts
  src/__internal__/label/label.spec.js
  src/__internal__/validations/validation-icon.component.js
  src/__internal__/validations/validation-icon.d.ts
  src/__internal__/validations/validation-icon.spec.js
  src/components/help/help.component.js
  src/components/help/help.d.ts
  src/components/help/help.spec.js
  src/components/icon/icon.component.js
  src/components/icon/icon.d.ts
  src/components/icon/icon.spec.js
  src/components/radio-button/__snapshots__/radio-button-group.spec.js.snap
  src/components/radio-button/__snapshots__/radio-button-mapper.spec.js.snap
  src/components/radio-button/__snapshots__/radio-button.spec.js.snap
  src/components/radio-button/radio-button.stories.mdx
  src/components/textarea/textarea.component.js
  src/components/textarea/textarea.spec.js
  src/components/textbox/__snapshots__/textbox.spec.js.snap
  src/components/textbox/textbox.component.js
  src/components/textbox/textbox.spec.js
  src/hooks/__internal__/useInputAccessibility/index.d.ts
  src/hooks/__internal__/useInputAccessibility/index.js
  src/hooks/__internal__/useInputAccessibility/index.spec.js
  src/hooks/__internal__/useInputAccessibility/useInputAccessibility.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End
