Repository Sage/carbon, pull requests merged in 2021-09, with the labels that each got.

#4347 ci: update chrome version for CI
  .github/workflows/cypress-pr.yml
  .github/workflows/cypress-push.yml
  cypress/support/step-definitions/anchor-navigation-steps.js
  cypress/tsconfig.json
  package-lock.json
  package.json
Labels: Passed Review, Passed QA, No UX QA Required, Cypress, Squad Front End

#4272 docs(card): add draggable examples to Card documentation - FE-1611
  cypress/features/regression/designSystem/card.feature
  cypress/locators/card/index.js
  cypress/support/step-definitions/card-steps.js
  package.json
  src/components/card/card-test.stories.mdx
  src/components/card/card.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4302 feat(button): make icon only buttons squares - FE-4121
  src/components/button/__snapshots__/button.spec.js.snap
  src/components/button/button.spec.js
  src/components/button/button.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4338 refactor: replace element-resize with useResizeObserver - FE-4290
  package-lock.json
  package.json
  src/components/dialog/dialog.component.js
  src/components/dialog/dialog.spec.js
  src/components/form/form.component.js
  src/components/form/form.spec.js
  src/hooks/__internal__/useResizeObserver/index.d.ts
  src/hooks/__internal__/useResizeObserver/index.js
  src/hooks/__internal__/useResizeObserver/index.spec.js
  src/utils/helpers/element-resize/__spec__.js
  src/utils/helpers/element-resize/element-resize.js
  src/utils/helpers/element-resize/package.json
Labels: Passed Review, Pending QA, No UX QA Required, Squad Front End

#4337 feat(definition-list): add support for rendering component as single column
  src/components/definition-list/__internal__/dl.context.js
  src/components/definition-list/dd.component.js
  src/components/definition-list/definition-list.spec.js
  src/components/definition-list/definition-list.stories.mdx
  src/components/definition-list/definition-list.style.js
  src/components/definition-list/dl.component.js
  src/components/definition-list/dl.d.ts
  src/components/definition-list/dt.component.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4345 refactor(help): change the children proptype from string to node - FE-4280
  .storybook/welcome-page/loves-carbon/loves-carbon.style.js
  src/components/help/help-test.stories.mdx
  src/components/help/help.component.js
  src/components/help/help.d.ts
  src/components/help/help.spec.js
  src/components/help/help.stories.mdx
  src/components/icon/icon.component.js
  src/components/icon/icon.d.ts
  src/components/icon/icon.spec.js
  src/components/icon/icon.stories.mdx
  src/components/link/link.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4358 fix(tile): address spelling mistake with horizontal in the options for orientation prop
  src/components/tile/tile.d.ts
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#4359 docs(security-policy): add security policy
  SECURITY.md
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#4354 fix(sidebar): add a type of children in interface, update the position and the size prop types - FE-4301
  src/components/sidebar/sidebar.component.js
  src/components/sidebar/sidebar.d.ts
Labels: Passed Review, Passed QA, No QA Required, Squad Front End

#4330 fix(tile-select): ensure title, subtitle and adornment wrap at smaller screen resolution FE-4275
  src/components/menu/menu.stories.mdx
  src/components/tile-select/tile-select.component.js
  src/components/tile-select/tile-select.d.ts
  src/components/tile-select/tile-select.spec.js
  src/components/tile-select/tile-select.stories.mdx
  src/components/tile-select/tile-select.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4365 ci(github-actions): create forked pr workflow - FE-4298
  .github/workflows/chromatic-fork.yml
  .github/workflows/cypress-push.yml
  CONTRIBUTING.md
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#4366 chore(deps): upgrade chromatic
  package-lock.json
  package.json
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#4367 chore(deps): upgrade chromatic to 5.9.2
  package-lock.json
  package.json
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#4368 ci: always use latest chromatic verson
  .github/workflows/chromatic-fork.yml
  package-lock.json
  package.json
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#4369 ci(github-actions): prevent escape chars
  .github/workflows/chromatic-fork.yml
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#4370 ci(github-actions): use branch name from check output
  .github/workflows/chromatic-fork.yml
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#4297 feat(button-bar): create button-bar component - FE-4259
  cypress/features/regression/accessibility/accessibilityDesignSystem.feature
  src/components/button-bar/button-bar-test.stories.mdx
  src/components/button-bar/button-bar.component.js
  src/components/button-bar/button-bar.config.js
  src/components/button-bar/button-bar.d.ts
  src/components/button-bar/button-bar.spec.js
  src/components/button-bar/button-bar.stories.mdx
  src/components/button-bar/button-bar.style.js
  src/components/button-bar/index.d.ts
  src/components/button-bar/index.js
  src/components/button/button.spec.js
  src/components/button/button.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4373 ci(forked): add cypress and rename workflow
  .github/workflows/chromatic-fork.yml
  .github/workflows/forked-ci.yml
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#4374 ci(forked): only run cypress after check
  .github/workflows/forked-ci.yml
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#4375 docs(contributing): add forked ci info
  CONTRIBUTING.md
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#4357 fix(pager): update show select value when page size prop is changed
  src/components/pager/pager.component.js
  src/components/pager/pager.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4342 feat(inline-inputs): add labelWidth and inputWidth props (FE-4279)
  src/__internal__/input/input-presentation.style.js
  src/components/form/form.stories.mdx
  src/components/form/form.style.js
  src/components/inline-inputs/inline-inputs.component.js
  src/components/inline-inputs/inline-inputs.d.ts
  src/components/inline-inputs/inline-inputs.spec.js
  src/components/inline-inputs/inline-inputs.style.js
  src/components/table/__snapshots__/table.spec.js.snap
  src/components/table/table-row/__snapshots__/table-row.spec.js.snap
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4353 feat(link): render an anchor element whenever a href prop is passed - FE-4130
  docs/usage-with-routing.stories.mdx
  src/components/link/link.component.js
  src/components/link/link.spec.js
  src/components/table/table.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4371 refactor(decimal): get locale from i18n provider if not passed in props - FE-4318
  src/components/decimal/decimal.component.js
  src/components/decimal/decimal.spec.js
  src/components/decimal/decimal.stories.mdx
  src/components/switch/switch.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4382 ci(cypress): set up single manually triggered workflow
  .github/workflows/cypress-pr.yml
  .github/workflows/cypress.yml
  .github/workflows/forked-ci.yml
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#4383 ci(forked-ci): fix number input
  .github/workflows/forked-ci.yml
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#4306 feat(loader-bar): create loader-bar - FE-4119
  cypress/features/regression/accessibility/accessibilityDesignSystem.feature
  cypress/features/regression/test/loader.feature
  cypress/features/regression/test/loaderBar.feature
  cypress/features/regression/themes/themes.feature
  cypress/fixtures/commonComponents/loader.json
  cypress/fixtures/commonComponents/loaderBar.json
  cypress/fixtures/themes/themes.json
  cypress/locators/loader-bar/index.js
  cypress/locators/loader-bar/locators.js
  cypress/locators/loader/index.js
  cypress/locators/themes/index.js
  cypress/support/step-definitions/loader-bar-steps.js
  cypress/support/step-definitions/loader-steps.js
  cypress/support/step-definitions/select-steps.js
  cypress/support/step-definitions/themes-steps.js
  src/components/loader-bar/index.d.ts
  src/components/loader-bar/index.js
  src/components/loader-bar/loader-bar-test.stories.mdx
  src/components/loader-bar/loader-bar.component.js
  src/components/loader-bar/loader-bar.config.js
  src/components/loader-bar/loader-bar.d.ts
  src/components/loader-bar/loader-bar.spec.js
  src/components/loader-bar/loader-bar.stories.mdx
  src/components/loader-bar/loader-bar.style.js
  src/components/loader/loader-square.spec.js
  src/components/loader/loader-square.style.js
  src/components/loader/loader.component.js
  src/components/loader/loader.config.js
  src/components/loader/loader.d.ts
  src/style/themes/aegean/aegean-theme.config.js
  src/style/themes/base/base-theme.config.js
  src/style/themes/mint/mint-theme.config.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4360 refactor(carousel): change class component to functional (FE-3650)
  src/components/carousel/carousel-test.stories.mdx
  src/components/carousel/carousel.component.js
  src/components/carousel/carousel.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4163 docs(design-tokens): rfc for implementing design tokens in carbon
  rfcs/text/design-tokens.md
Labels: Passed Review, RFC, Final Comments, Squad DS Alignment

#4376 refactor(pages): convert to function FE-3657
  src/components/pages/pages.component.js
  src/components/pages/pages.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4386 test: add an alias to make test stable
  cypress/support/step-definitions/anchor-navigation-steps.js
Labels: Passed QA, Cypress, Squad Front End

#4399 chore(pr template): add extra checks
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4400 chore(github): add JIRA ticket to bug template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#4364 refactor(form-summary): change the design of the validation message - FE-4262
  src/components/form/__internal__/form-summary.component.js
  src/components/form/__internal__/form-summary.style.js
  src/components/form/form.spec.js
  src/components/form/form.stories.mdx
  src/components/i18n-provider/i18n-provider.d.ts
  src/locales/en-gb.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4398 fix(textbox): fix incorrect styling when required and in error state - FE-4286
  src/__internal__/input/__snapshots__/input-presentation.spec.js.snap
  src/__internal__/input/__snapshots__/input.spec.js.snap
  src/__internal__/input/input-presentation.style.js
  src/__internal__/input/input.style.js
  src/components/simple-color-picker/__snapshots__/simple-color-picker.spec.js.snap
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4397 feat(menu-item): add callback for submenu toggle
  src/components/menu/__internal__/submenu/submenu.component.js
  src/components/menu/__internal__/submenu/submenu.spec.js
  src/components/menu/menu-item/menu-item.component.js
  src/components/menu/menu-item/menu-item.d.ts
  src/components/menu/menu-item/menu-item.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4381 feat(textbox): add a character counter - FE-4265
  src/__internal__/character-count/character-count.component.js
  src/__internal__/character-count/character-count.spec.js
  src/__internal__/character-count/character-count.style.js
  src/__internal__/character-count/index.js
  src/components/textarea/textarea.component.js
  src/components/textarea/textarea.spec.js
  src/components/textbox/textbox-test.stories.mdx
  src/components/textbox/textbox.component.js
  src/components/textbox/textbox.d.ts
  src/components/textbox/textbox.spec.js
  src/components/textbox/textbox.stories.mdx
  src/hooks/__internal__/useCharacterCount/index.js
  src/hooks/__internal__/useCharacterCount/index.spec.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4314 feat(flat-table): add drag and drop functionality to table rows - FE-4103
  src/components/flat-table/__snapshots__/flat-table.spec.js.snap
  src/components/flat-table/flat-table-body-draggable/flat-table-body-draggable.component.js
  src/components/flat-table/flat-table-body-draggable/flat-table-body-draggable.d.ts
  src/components/flat-table/flat-table-body-draggable/flat-table-body-draggable.spec.js
  src/components/flat-table/flat-table-body-draggable/index.d.ts
  src/components/flat-table/flat-table-body-draggable/index.js
  src/components/flat-table/flat-table-body/flat-table-body.component.js
  src/components/flat-table/flat-table-row/__internal__/flat-table-row-draggable.component.js
  src/components/flat-table/flat-table-row/__internal__/flat-table-row-draggable.d.ts
  src/components/flat-table/flat-table-row/__snapshots__/flat-table-row.spec.js.snap
  src/components/flat-table/flat-table-row/flat-table-row.component.js
  src/components/flat-table/flat-table-row/flat-table-row.spec.js
  src/components/flat-table/flat-table-row/flat-table-row.style.js
  src/components/flat-table/flat-table.stories.mdx
  src/components/flat-table/index.d.ts
  src/components/flat-table/index.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4377 feat(navigation-bar): add sticky position - FE-4268
  src/components/navigation-bar/navigation-bar.component.js
  src/components/navigation-bar/navigation-bar.d.ts
  src/components/navigation-bar/navigation-bar.spec.js
  src/components/navigation-bar/navigation-bar.stories.mdx
  src/components/navigation-bar/navigation-bar.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4391 feat(tile-select): surface new additonalInformation prop FE-4282
  src/components/tile-select/tile-select.component.js
  src/components/tile-select/tile-select.d.ts
  src/components/tile-select/tile-select.spec.js
  src/components/tile-select/tile-select.stories.mdx
  src/components/tile-select/tile-select.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4396 refactor(profile): convert from class to functional component - FE-3661
  src/components/profile/__snapshots__/profile.spec.js.snap
  src/components/profile/profile.component.js
  src/components/profile/profile.d.ts
  src/components/profile/profile.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4385 refactor(pod): convert class component to functional (FE-3660)
  src/components/pod/__snapshots__/pod.spec.js.snap
  src/components/pod/pod-context.js
  src/components/pod/pod-manager.component.js
  src/components/pod/pod-manager.d.ts
  src/components/pod/pod-manager.spec.js
  src/components/pod/pod-test.stories.mdx
  src/components/pod/pod.component.js
  src/components/pod/pod.spec.js
  src/components/pod/pod.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4405 feat(tile-select): add support for rendering accordion footer FE-4283
  src/components/tile-select/__internal__/accordion/accordion.component.js
  src/components/tile-select/__internal__/accordion/accordion.d.ts
  src/components/tile-select/__internal__/accordion/accordion.spec.js
  src/components/tile-select/__internal__/accordion/accordion.style.js
  src/components/tile-select/__internal__/accordion/index.js
  src/components/tile-select/tile-select.component.js
  src/components/tile-select/tile-select.d.ts
  src/components/tile-select/tile-select.spec.js
  src/components/tile-select/tile-select.stories.mdx
  src/components/tile-select/tile-select.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4420 chore(deps): update eslint plugins
  .eslintrc
  package-lock.json
  package.json
  src/__internal__/input/input.component.js
  src/__spec_helper__/mock-date-helper.js
  src/components/action-popover/action-popover.spec.js
  src/components/action-toolbar/action-toolbar.component.js
  src/components/app-wrapper/app-wrapper.component.js
  src/components/configurable-items/configurable-item-row/configurable-item-row.component.js
  src/components/configurable-items/configurable-items.component.js
  src/components/date-range/date-range.component.js
  src/components/date/date.component.js
  src/components/decimal/decimal.component.js
  src/components/detail/detail.component.js
  src/components/drag-and-drop/custom-drag-layer/custom-drag-layer.js
  src/components/drag-and-drop/draggable-context/draggable-context.js
  src/components/drag-and-drop/with-drag/with-drag.js
  src/components/drag-and-drop/with-drop/with-drop.js
  src/components/flat-table/flat-table-row/flat-table-row.component.js
  src/components/heading/heading.component.js
  src/components/icon/icon.component.js
  src/components/mount-in-app/mount-in-app.js
  src/components/multi-step-wizard/multi-step-wizard.js
  src/components/multi-step-wizard/step/step.js
  src/components/scrollable-list/scrollable-list.component.js
  src/components/show-edit-pod/show-edit-pod.component.js
  src/components/sidebar/sidebar.component.js
  src/components/table/table.component.js
  src/components/text-editor/text-editor.component.js
  src/components/textarea/textarea.component.js
  src/patterns/configurable-items/configurable-items-content/configurable-items-content.js
  src/patterns/configurable-items/configurable-items.js
  src/utils/ether/__spec__.js
  src/utils/helpers/with-unique-id-props/with-unique-id-props.hoc.js
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#4415 feat(i18n): add types for the base locale file - FE-4291
  src/components/i18n-provider/i18n-provider.d.ts
  src/components/pager/pager.spec.js
  src/locales/en-gb.d.ts
  src/locales/en-gb.js
  src/locales/index.d.ts
  src/locales/locale.d.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4410 feat(content): change a string type of the title prop to a node type - FE-4320
  src/components/content/content.component.js
  src/components/content/content.d.ts
  src/components/content/content.spec.js
  src/components/content/content.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4423 fix(vertical-divider): change tint type to number
  src/components/vertical-divider/vertical-divider.d.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4411 fix(simple-select): change the test story format from mdx to js - FE-4332
  src/components/drag-and-drop/drag-and-drop-test.stories.js
  src/components/select/simple-select/simple-select-test.stories.js
  src/components/select/simple-select/simple-select-test.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4424 chore: add csb details in pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4402 refactor(split-button): rewrite class component to functional
  src/components/split-button/split-button-test.stories.mdx
  src/components/split-button/split-button.component.js
  src/components/split-button/split-button.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4430 ci(forked): use input number instead of pr
  .github/workflows/forked-ci.yml
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#4429 fix(i18n-provider): fix type definition
  src/locales/locale.d.ts
Labels: Passed Review, No QA Required, No UX QA Required

#4409 fix(menu): incorrect menu aria role (FE-4327)
  src/components/menu/__internal__/submenu/submenu.component.js
  src/components/menu/menu-divider/menu-divider.component.js
  src/components/menu/menu-item/menu-item.component.js
  src/components/menu/menu.component.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4441 ci(chromatic): run workflow on push
  .github/workflows/chromatic-push.yml
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End
