Repository Sage/carbon, pull requests merged in 2021-08, with the labels that each got.

#4242 feat(pod): added softDelete, onDelete and onUndo functionalities - FE-4165
  src/components/pod/__snapshots__/pod.spec.js.snap
  src/components/pod/pod.component.js
  src/components/pod/pod.d.ts
  src/components/pod/pod.spec.js
  src/components/pod/pod.stories.js
  src/components/pod/pod.stories.mdx
  src/components/pod/pod.style.js
  src/components/show-edit-pod/show-edit-pod.component.js
  src/components/show-edit-pod/show-edit-pod.d.ts
  src/components/show-edit-pod/show-edit-pod.spec.js
  src/components/show-edit-pod/show-edit-pod.stories.mdx
  src/components/show-edit-pod/show-edit-pod.style.js
  src/style/themes/base/base-theme.config.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#4199 refactor(pod): remove collapse functionality (FE-1762)
  cypress/features/regression/pod.feature
  cypress/fixtures/commonComponents/pod.json
  cypress/locators/pod/index.js
  cypress/locators/pod/locators.js
  cypress/support/step-definitions/pod-steps.js
  src/components/pod/pod.component.js
  src/components/pod/pod.d.ts
  src/components/pod/pod.spec.js
  src/components/pod/pod.stories.js
  src/components/pod/pod.stories.mdx
  src/components/pod/pod.style.js
Labels: Passed QA, Passed Review, Pending UX QA, Squad Front End

#4281 fix(search): incorrect margin when used in Form
  src/components/form/form.spec.js
  src/components/form/form.style.js
Labels: No UX QA Required, Pending QA, Pending Review, Squad Front End

#4280 fix(card): wrong props on not-interactive card - FE-4243
  src/components/card/card.component.js
  src/components/card/card.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4285 fix(flat-table-row): remove hover state for rows within drawer sidebar and no onclick FE-4246
  src/components/flat-table/flat-table-row/flat-table-row.spec.js
  src/components/flat-table/flat-table-row/flat-table-row.style.js
  src/components/icon/icon.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4261 fix(flat-table): ensure correct z-index is applied to flat-table-header - FE-4225
  src/components/flat-table/flat-table-head/flat-table-head.component.js
  src/components/flat-table/flat-table-header/flat-table-header.style.js
  src/components/flat-table/flat-table-row/flat-table-row.component.js
  src/components/flat-table/flat-table-row/flat-table-row.spec.js
  src/components/flat-table/flat-table-row/flat-table-row.style.js
  src/components/flat-table/flat-table.spec.js
  src/components/flat-table/flat-table.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#4257 fix(menu): add aria-role to fix accessibility violations - FE-3422
  src/components/link/link.component.js
  src/components/menu/menu-full-screen/menu-full-screen.component.js
  src/components/menu/menu-item/menu-item.component.js
  src/components/menu/menu.component.js
  src/components/pod/__snapshots__/pod.spec.js.snap
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4293 chore(deps): updates to fix npm vulns
  package-lock.json
  package.json
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#4299 docs(package.json): update url for homepage
  package.json
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#4304 docs: document version strategy FE-4254
  README.md
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#4309 feat(sidebar): implement ref forwarding
  src/components/sidebar/index.d.ts
  src/components/sidebar/sidebar.component.js
  src/components/sidebar/sidebar.d.ts
  src/components/sidebar/sidebar.spec.js
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#4308 fix(date-picker): month could not be changed in datepicker - FE-4274
  cypress/features/regression/designSystem/dateInput.feature
  cypress/locators/date-input/index.js
  cypress/locators/date-input/locators.js
  cypress/support/step-definitions/date-input-steps.js
  src/components/date/date-picker.component.js
  src/components/date/date-picker.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4310 docs(translation-keys-table): add util to support rendering translation keys in storybook FE-4159
  .storybook/utils/translation-keys-table.js
  src/components/i18n-provider/i18n-provider.component.js
  src/components/i18n-provider/i18n-provider.d.ts
  src/components/text-editor/__internal__/toolbar/toolbar.component.js
  src/components/text-editor/__internal__/toolbar/toolbar.spec.js
  src/components/text-editor/text-editor.stories.mdx
  src/locales/en-gb.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4311 fix(focus-trap): add mutation observer
  src/__internal__/focus-trap/focus-trap.component.js
  src/__internal__/focus-trap/focus-trap.spec.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4318 docs(menu): alter story to remove aria false positive
  src/components/menu/menu.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4316 fix(select): option not scrolled using keyboard navigation when options are changed (FE-4244)
  src/components/select/select-list/select-list.component.js
  src/components/select/select-list/update-list-scroll.js
  src/components/select/select-list/update-list-scroll.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4305 feat(tooltip-provider): add context and provider component FE-4074
  src/__internal__/tooltip-provider/index.d.ts
  src/__internal__/tooltip-provider/index.js
  src/__internal__/validations/validation-icon.component.js
  src/components/checkbox/checkbox-group.component.js
  src/components/checkbox/checkbox-group.d.ts
  src/components/checkbox/checkbox-group.spec.js
  src/components/checkbox/checkbox-validations.stories.mdx
  src/components/checkbox/checkbox.component.js
  src/components/checkbox/checkbox.d.ts
  src/components/checkbox/checkbox.spec.js
  src/components/date-range/date-range.component.js
  src/components/date-range/date-range.d.ts
  src/components/date-range/date-range.spec.js
  src/components/date-range/date-range.stories.mdx
  src/components/date/date.component.js
  src/components/date/date.d.ts
  src/components/date/date.spec.js
  src/components/date/date.stories.mdx
  src/components/decimal/decimal.stories.mdx
  src/components/grouped-character/grouped-character.stories.mdx
  src/components/icon/icon.component.js
  src/components/icon/icon.spec.js
  src/components/number/number.stories.mdx
  src/components/numeral-date/numeral-date.component.js
  src/components/numeral-date/numeral-date.d.ts
  src/components/numeral-date/numeral-date.stories.mdx
  src/components/radio-button/radio-button-group.component.js
  src/components/radio-button/radio-button-group.d.ts
  src/components/radio-button/radio-button-group.spec.js
  src/components/radio-button/radio-button.component.js
  src/components/radio-button/radio-button.d.ts
  src/components/radio-button/radio-button.spec.js
  src/components/radio-button/radio-button.stories.mdx
  src/components/select/filterable-select/filterable-select.component.js
  src/components/select/filterable-select/filterable-select.d.ts
  src/components/select/multi-select/multi-select.component.js
  src/components/select/multi-select/multi-select.d.ts
  src/components/select/simple-select/simple-select.component.js
  src/components/select/simple-select/simple-select.d.ts
  src/components/switch/switch.component.js
  src/components/switch/switch.d.ts
  src/components/switch/switch.spec.js
  src/components/switch/switch.stories.mdx
  src/components/textarea/textarea.component.js
  src/components/textarea/textarea.d.ts
  src/components/textarea/textarea.spec.js
  src/components/textarea/textarea.stories.mdx
  src/components/textbox/__snapshots__/textbox.spec.js.snap
  src/components/textbox/textbox.component.js
  src/components/textbox/textbox.d.ts
  src/components/textbox/textbox.spec.js
  src/components/textbox/textbox.stories.mdx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4320 chore: remove warning about removing i18n-js dependency - FE-4287
  package-lock.json
  package.json
  postinstall.js
Labels: Passed Review, Passed QA, No QA Required, Squad Front End

#4317 docs(pr template): update pr template checklist to include translations FE-4144
  .github/PULL_REQUEST_TEMPLATE.md
  docs/i18n.stories.mdx
  src/components/action-popover/action-popover.stories.mdx
  src/components/batch-selection/batch-selection.stories.mdx
  src/components/date-range/date-range.stories.mdx
  src/components/date/date.stories.mdx
  src/components/form/form.stories.mdx
  src/components/message/message.stories.mdx
  src/components/numeral-date/numeral-date.stories.mdx
  src/components/pager/pager.stories.mdx
  src/components/pod/pod.stories.mdx
  src/components/select/filterable-select/filterable-select.stories.mdx
  src/components/select/multi-select/multi-select.stories.mdx
  src/components/select/simple-select/simple-select.stories.mdx
  src/components/show-edit-pod/show-edit-pod.stories.mdx
  src/components/switch/switch.stories.mdx
  src/components/text-editor/text-editor.stories.mdx
  src/components/tile-select/tile-select.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4315 refactor(link): convert a class component to a function component - FE-3654
  cypress/locators/link/index.js
  src/components/action-toolbar/action-toolbar.style.js
  src/components/card/__snapshots__/card.spec.js.snap
  src/components/definition-list/definition-list.style.js
  src/components/link/__snapshots__/link.spec.js.snap
  src/components/link/link.component.js
  src/components/link/link.d.ts
  src/components/link/link.spec.js
  src/components/link/link.style.js
  src/components/menu/__internal__/submenu/submenu.style.js
  src/components/menu/menu-item/menu-item.style.js
  src/components/pod/__snapshots__/pod.spec.js.snap
  src/components/pod/pod.style.js
  src/components/table/__snapshots__/table.spec.js.snap
  src/components/table/table-row/__snapshots__/table-row.spec.js.snap
  src/components/table/table.style.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4331 refactor(icon): use design system icon names
  src/components/icon/__snapshots__/icon-unicodes.spec.js.snap
  src/components/icon/icon-unicodes.js
  src/components/icon/icon-unicodes.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4335 feat: add new design system icons - FE-4292
  src/components/icon/__snapshots__/icon-unicodes.spec.js.snap
  src/components/icon/icon-config.js
  src/components/icon/icon-unicodes.js
  src/components/icon/icon.d.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4325 refactor(pill): convert a class component to a function component - FE-3658
  src/components/pill/pill.component.js
  src/components/pill/pill.d.ts
  src/components/pill/pill.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4326 fix(pod): add missing height prop type definition - FE-4278
  src/components/pod/pod.d.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4328 fix(select): stop form submit when enter key is pressed with open list - FE-4206
  src/components/select/select-list/select-list.component.js
  src/components/select/select-list/select-list.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4334 fix(toast): stop blocking interactions with other elements - FE-4273
  src/components/toast/toast.style.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4349 chore(deps): update semantic-release
  package-lock.json
  package.json
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End
