Repository Sage/carbon, pull requests merged in 2021-03, with the labels that each got.

#3744 refactor(action-popover): replace i18n-js with i18next
  src/components/action-popover/action-popover.component.js
  src/components/action-popover/action-popover.spec.js
  src/components/note/__internal__/note.spec.js
  src/components/table/table-row/table-row.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3743 refactor(message): replace i18n-js with i18next
  src/components/icon-button/icon-button.spec.js
  src/components/message/message.component.js
  src/components/message/message.spec.js
Labels: DO NOT MERGE, No UX QA Required, Passed QA, Passed Review, Squad Front End

#3758 ci(workflows): add codeql workflow
  .github/codeql/codeql-config.yml
  .github/workflows/codeql-analysis.yml
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#3761 test: update cypress&cucumber versions
  cypress/support/index.js
  cypress/support/step-definitions/date-input-steps.js
  package-lock.json
  package.json
Labels: Cypress, Passed QA, Squad Front End

#3762 ci(codeql): add master push hook
  .github/workflows/codeql-analysis.yml
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#3769 chore(deps): upgrade vulnerable packages
  package-lock.json
  package.json
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#3759 fix(tabs): fix incorrect large tab alignment - FE-3480/FE-3478/FE-3479
  src/components/tabs/__internal__/tab-title/tab-title.spec.js
  src/components/tabs/__internal__/tab-title/tab-title.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3772 docs(draggable): fix with getOrder callback example - FE-3791
  src/components/draggable/draggable.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3764 refactor(batch-selection): replace i18n-js with i18next
  src/components/batch-selection/batch-selection.component.js
  src/components/batch-selection/batch-selection.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3747 refactor(numeral-date): replace i18n-js with i18next
  src/__experimental__/components/numeral-date/numeral-date.component.js
  src/__experimental__/components/numeral-date/numeral-date.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3774 fix: fix dropdown alignment in split and multi action buttons - FE-3616
  package-lock.json
  package.json
  src/__internal__/popover/popover.component.js
  src/__internal__/popover/popover.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3746 refactor(textarea): replace i18n-js with i18next
  src/__experimental__/components/textarea/textarea.component.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3763 refactor(tile-select): replace i18n-js with i18next
  src/components/tile-select/tile-select.component.js
  src/components/tile-select/tile-select.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3776 fix(focus-trap): update trap to use ref from content container FE-3795
  src/__internal__/focus-trap/focus-trap.component.js
  src/__internal__/focus-trap/focus-trap.spec.js
  src/components/dialog-full-screen/dialog-full-screen.component.js
  src/components/dialog/dialog.component.js
  src/components/sidebar/sidebar.component.js
Labels: No UX QA Required, Passed QA, Pending Review, Squad Front End

#3771 docs(contributing): add typescript style guide
  CONTRIBUTING.md
  docs/typescript-styleguide.md
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#3775 refactor(form-summary): replace i18n-js with i18next
  src/components/form/form-summary.component.js
  src/components/form/form.spec.js
  src/components/table/table-row/table-row.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3793 refactor(button): extracting ButtonTypes to options-helper
  src/components/button/button.d.ts
  src/utils/helpers/options-helper/options-helper.d.ts
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End, Squad Nebula

#3740 feat(sidebar): add styled system to sidebar - FE-3574
  cypress/features/regression/sidebar.feature
  src/components/sidebar/__internal__/sidebar-header/__definition__.js
  src/components/sidebar/__internal__/sidebar-header/index.js
  src/components/sidebar/__internal__/sidebar-header/sidebar-header.component.js
  src/components/sidebar/__internal__/sidebar-header/sidebar-header.spec.js
  src/components/sidebar/__internal__/sidebar-header/sidebar-header.style.js
  src/components/sidebar/index.js
  src/components/sidebar/sidebar.component.js
  src/components/sidebar/sidebar.spec.js
  src/components/sidebar/sidebar.stories.js
  src/components/sidebar/sidebar.stories.mdx
  src/components/sidebar/sidebar.style.js
Labels: No QA Required, Passed QA, Passed Review, Squad Front End

#3788 feat(icon): add additional fontSize and bgSize prop values - FE-3711
  src/components/confirm/confirm.component.js
  src/components/icon/icon-config.js
  src/components/icon/icon.component.js
  src/components/icon/icon.d.ts
  src/components/icon/icon.spec.js
  src/components/icon/icon.stories.js
  src/components/icon/icon.stories.mdx
  src/components/icon/icon.style.js
  src/utils/helpers/options-helper/options-helper.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3782 fix(select): fix onblur fired on option mousedown event - FE-3772
  src/components/select/simple-select/simple-select.component.js
  src/components/select/simple-select/simple-select.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3794 chore(tile): fix errors in tile story
  src/components/tile/tile.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3777 test(flattable,select,actionpopover): add tests to check popover position top or bottom FE-3765
  cypress/features/regression/designSystem/actionPopover.feature
  cypress/features/regression/test/flatTableNoiFrame.feature
  cypress/features/regression/test/simpleSelectNoIFrame.feature
  cypress/fixtures/test/simpleSelect.json
  cypress/locators/flat-table/index.js
  cypress/locators/flat-table/locators.js
  cypress/locators/select/index.js
  cypress/locators/select/locators.js
  cypress/support/step-definitions/action-popover-steps.js
  cypress/support/step-definitions/flat-table-steps.js
  cypress/support/step-definitions/select-steps.js
  src/components/select/simple-select/simple-select.stories.js
Labels: Passed Review, Squad Front End

#3798 refactor(list-action-button): replace i18n-js with i18next
  src/components/select/filterable-select/filterable-select.spec.js
  src/components/select/list-action-button/list-action-button.component.js
  src/components/select/list-action-button/list-action-button.spec.js
  src/components/select/select-list/select-list.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3805 fix(button): add border radius to button styles - FE-3681
  src/components/button/__snapshots__/button.spec.js.snap
  src/components/button/button.style.js
  src/components/dialog-full-screen/__snapshots__/dialog-full-screen.spec.js.snap
  src/components/multi-action-button/__snapshots__/multi-action-button.spec.js.snap
  src/components/select/list-action-button/__snapshots__/list-action-button.spec.js.snap
  src/components/split-button/__snapshots__/split-button.spec.js.snap
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3786 refactor(pager): replace i18n-js with i18next
  cypress/features/regression/test/pager.feature
  cypress/fixtures/test/pager.json
  src/components/pager/__internal__/pager-navigation-link.component.js
  src/components/pager/__internal__/pager-navigation.component.js
  src/components/pager/__internal__/pager-navigation.spec.js
  src/components/pager/pager.component.js
  src/components/pager/pager.spec.js
  src/components/table-ajax/table-ajax.component.js
  src/components/table-ajax/table-ajax.spec.js
  src/components/table/table.component.js
  src/components/table/table.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3768 feat(action-popover-item): support for download button - FE-3760
  cypress/features/regression/designSystem/actionPopover.feature
  cypress/support/step-definitions/action-popover-steps.js
  src/components/action-popover/action-popover-item.component.js
  src/components/action-popover/action-popover-item.d.ts
  src/components/action-popover/action-popover.spec.js
  src/components/action-popover/action-popover.stories.mdx
  src/components/action-popover/action-popover.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3750 refactor(date): replace i18n-js with i18next
  src/__experimental__/components/date-range/date-range.spec.js
  src/__experimental__/components/date/date-picker.component.js
  src/__experimental__/components/date/date-picker.spec.js
  src/__experimental__/components/date/date.spec.js
  src/__spec_helper__/I18next.js
  src/components/table/table-cell/table-cell.spec.js
  src/utils/helpers/date/__spec__.js
  src/utils/helpers/date/date.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3797 refactor(date-picker): replace portal with popper
  cypress/support/step-definitions/date-input-steps.js
  src/__experimental__/components/date/__snapshots__/date-picker.spec.js.snap
  src/__experimental__/components/date/date-picker.component.js
  src/__experimental__/components/date/date-picker.spec.js
  src/__experimental__/components/date/date.component.js
  src/__experimental__/components/date/date.spec.js
  src/__experimental__/components/date/day-picker.style.js
  src/utils/helpers/options-helper/options-helper.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3796 fix(select): fix incorrect textbox behaviour on safari - FE-3788
  src/components/select/select.style.js
  src/components/select/simple-select/simple-select.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3766 feat(tooltip): add support for overriding default flip placements FE-3771
  src/__experimental__/components/label/label.component.js
  src/__experimental__/components/simple-color-picker/simple-color-picker.component.js
  src/__experimental__/components/switch/switch-slider.component.js
  src/__internal__/fieldset/fieldset.component.js
  src/components/button-toggle-group/button-toggle-group.component.js
  src/components/button-toggle-group/button-toggle-group.spec.js
  src/components/help/help.component.js
  src/components/help/help.d.ts
  src/components/help/help.spec.js
  src/components/help/help.stories.js
  src/components/icon/icon.component.js
  src/components/icon/icon.d.ts
  src/components/icon/icon.spec.js
  src/components/icon/icon.stories.js
  src/components/icon/icon.stories.mdx
  src/components/tooltip/tooltip.component.js
  src/components/tooltip/tooltip.d.ts
  src/components/tooltip/tooltip.spec.js
  src/components/tooltip/tooltip.stories.js
  src/components/tooltip/tooltip.stories.mdx
  src/components/tooltip/tooltip.style.js
  src/components/validations/validation-icon.component.js
  src/components/validations/validation-icon.spec.js
  src/utils/helpers/options-helper/options-helper.d.ts
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3789 feat(link): add `isSkipLink` prop - FE-3735
  cypress/features/regression/link.feature
  cypress/locators/link/index.js
  cypress/locators/link/locators.js
  cypress/support/step-definitions/link-steps.js
  src/__experimental__/components/date/__snapshots__/date-picker.spec.js.snap
  src/components/link/link.component.js
  src/components/link/link.d.ts
  src/components/link/link.spec.js
  src/components/link/link.stories.mdx
  src/components/link/link.style.js
  src/style/themes/base/base-theme.config.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3813 refactor(table): replace i18n-js with i18next
  src/__experimental__/components/date-range/date-range.spec.js
  src/__experimental__/components/date/date-picker.component.js
  src/__experimental__/components/date/date-picker.spec.js
  src/__experimental__/components/date/date.spec.js
  src/__experimental__/components/numeral-date/numeral-date.component.js
  src/__experimental__/components/numeral-date/numeral-date.spec.js
  src/__experimental__/components/textarea/textarea.component.js
  src/__spec_helper__/I18next.js
  src/components/action-popover/action-popover-item.component.js
  src/components/batch-selection/batch-selection.component.js
  src/components/batch-selection/batch-selection.spec.js
  src/components/form/form-summary.component.js
  src/components/form/form.spec.js
  src/components/table-ajax/table-ajax.component.js
  src/components/table-ajax/table-ajax.spec.js
  src/components/table/table-cell/table-cell.spec.js
  src/components/table/table-row/table-row.spec.js
  src/components/table/table.component.js
  src/components/table/table.spec.js
  src/components/tile-select/tile-select.component.js
  src/components/tile-select/tile-select.spec.js
  src/utils/helpers/date/__spec__.js
  src/utils/helpers/date/date.js
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#3808 refactor(confirm): replace i18n-js with i18next
  src/__internal__/i18n/i18n.component.js
  src/__internal__/i18n/i18n.spec.js
  src/__internal__/i18n/index.js
  src/components/confirm/confirm.component.js
  src/components/confirm/confirm.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3819 refactor(pod): replace i18n-js with i18next
  src/components/pod/pod.component.js
  src/components/pod/pod.spec.js
  src/components/show-edit-pod/show-edit-pod.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3778 fix(menu): fix search styles
  cypress/features/regression/designSystem/menu.feature
  cypress/features/regression/designSystem/menuDefaultDivider.feature
  cypress/support/step-definitions/menu-steps.js
  src/__experimental__/components/date/__snapshots__/date-picker.spec.js.snap
  src/components/menu/__internal__/submenu/submenu.spec.js
  src/components/menu/__internal__/submenu/submenu.style.js
  src/components/menu/menu-item/menu-item.component.js
  src/components/menu/menu-item/menu-item.style.js
  src/components/menu/menu.stories.mdx
  src/style/themes/base/base-theme.config.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3807 fix(radio-button-group, checkbox-group): disable group behaviour when validation is not on label FE-3779
  src/__experimental__/components/checkbox/checkbox-group.component.js
  src/__experimental__/components/checkbox/checkbox-group.spec.js
  src/__experimental__/components/radio-button/__snapshots__/radio-button-group.spec.js.snap
  src/__experimental__/components/radio-button/radio-button-group.component.js
  src/__experimental__/components/radio-button/radio-button-group.spec.js
  src/__internal__/fieldset/fieldset.component.js
  src/__internal__/fieldset/fieldset.d.ts
  src/__internal__/fieldset/fieldset.spec.js
  src/__internal__/input-behaviour/input-group-behaviour.component.js
  src/__internal__/input-behaviour/useInputBehaviour.js
  src/__internal__/input-behaviour/useInputBehaviour.spec.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3801 fix(pod): fix footer text colour when pod is hovered - FE-3505
  src/components/pod/__snapshots__/pod.spec.js.snap
  src/components/pod/pod.spec.js
  src/components/pod/pod.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3825 refactor(configurable-items): replace i18n-js with i18next
  src/components/configurable-items/configurable-items.component.js
  src/components/configurable-items/configurable-items.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3829 test(menu): add missing cypress tests
  cypress/features/regression/designSystem/menu.feature
  cypress/locators/menu/index.js
  cypress/locators/menu/locators.js
  cypress/support/step-definitions/menu-steps.js
Labels: Cypress, Squad Front End

#3815 feat: add `rel` prop to Link component - FE-3803
  cypress/features/regression/link.feature
  cypress/locators/link/index.js
  cypress/support/step-definitions/link-steps.js
  src/components/link/link.component.js
  src/components/link/link.d.ts
  src/components/link/link.spec.js
  src/components/link/link.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3795 docs: fix some console errors
  src/components/dialog-full-screen/dialog-full-screen.stories.mdx
  src/components/table/table-row/table-row.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End, Squad Nebula

#3827 refactor(table): replace i18n-js with i18next
  src/components/table/table.component.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3824 refactor(action-toolbar): replace i18n-js with i18next
  src/components/action-toolbar/action-toolbar.component.js
  src/components/action-toolbar/action-toolbar.spec.js
  src/components/table/table.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3814 refactor(portal): rewrite as functional
  cypress/features/regression/dialogActions.feature
  src/components/alert/alert.stories.mdx
  src/components/confirm/confirm.stories.js
  src/components/dialog-full-screen/dialog-full-screen.stories.js
  src/components/dialog/dialog.stories.mdx
  src/components/portal/__snapshots__/__spec__.js.snap
  src/components/portal/__snapshots__/portal.spec.js.snap
  src/components/portal/portal.js
  src/components/portal/portal.spec.js
  src/components/sidebar/sidebar.stories.mdx
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3826 refactor(show-edit-pod): replace i18n-js with i18next
  src/components/show-edit-pod/show-edit-pod.component.js
  src/components/show-edit-pod/show-edit-pod.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3783 fix(card): render component with string as the children
  src/components/card/card.component.js
  src/components/card/card.spec.js
  src/components/card/card.stories.mdx
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End, Squad Nebula

#3843 feat(date-picker): auto position pop up
  cypress/features/regression/experimental/dateInput.feature
  cypress/fixtures/experimental/dateInput.json
  cypress/locators/date-input/index.js
  cypress/support/step-definitions/date-input-steps.js
  src/__experimental__/components/date/__snapshots__/date-picker.spec.js.snap
  src/__experimental__/components/date/date-picker.component.js
  src/__experimental__/components/date/date-picker.spec.js
  src/__experimental__/components/date/date.stories.js
  src/__experimental__/components/date/day-picker.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Pending QA, Squad Front End

#3840 fix(flat-table-row): allow null children
  src/components/flat-table/flat-table-row/flat-table-row.component.js
  src/components/flat-table/flat-table-row/flat-table-row.spec.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3821 fix(tabs-header): allow tabs to be scrollable when position is left and they overflow parent FE-3302
  cypress/features/regression/themes/themes.feature
  cypress/support/step-definitions/themes-steps.js
  src/components/drawer/__internal__/drawer.stories.mdx
  src/components/tabs/__internal__/tab-title/tab-title.component.js
  src/components/tabs/__internal__/tab-title/tab-title.spec.js
  src/components/tabs/__internal__/tab-title/tab-title.style.js
  src/components/tabs/__internal__/tabs-header/tabs-header.component.js
  src/components/tabs/__internal__/tabs-header/tabs-header.spec.js
  src/components/tabs/__internal__/tabs-header/tabs-header.style.js
Labels: Passed Review, Passed UX QA, Pending QA, Squad Front End

#3839 feat(duelling-picklist): add grouping option
  cypress/features/regression/accessibility/accessibilityDesignSystem.feature
  cypress/features/regression/designSystem/duellingPicklist.feature
  cypress/locators/duelling-picklist/index.js
  cypress/locators/duelling-picklist/locators.js
  cypress/support/step-definitions/duelling-picklist-steps.js
  src/__experimental__/components/date/__snapshots__/date-picker.spec.js.snap
  src/components/duelling-picklist/duelling-picklist.spec.js
  src/components/duelling-picklist/duelling-picklist.stories.js
  src/components/duelling-picklist/duelling-picklist.stories.mdx
  src/components/duelling-picklist/duelling-picklist.style.js
  src/components/duelling-picklist/index.d.ts
  src/components/duelling-picklist/index.js
  src/components/duelling-picklist/picklist-divider/picklist-divider.component.js
  src/components/duelling-picklist/picklist-divider/picklist-divider.d.ts
  src/components/duelling-picklist/picklist-divider/picklist-divider.style.js
  src/components/duelling-picklist/picklist-group/picklist-group.component.js
  src/components/duelling-picklist/picklist-group/picklist-group.spec.js
  src/components/duelling-picklist/picklist-group/picklist-group.style.js
  src/components/duelling-picklist/picklist-item/picklist-item.component.js
  src/components/duelling-picklist/picklist-item/picklist-item.d.ts
  src/components/duelling-picklist/picklist-item/picklist-item.spec.js
  src/components/duelling-picklist/picklist-item/picklist-item.style.js
  src/components/duelling-picklist/picklist-placeholder/picklist-placeholder.component.js
  src/components/duelling-picklist/picklist-placeholder/picklist-placeholder.d.ts
  src/components/duelling-picklist/picklist/picklist.component.js
  src/components/duelling-picklist/picklist/picklist.d.ts
  src/components/duelling-picklist/picklist/picklist.style.js
  src/style/themes/base/base-theme.config.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3863 ci(cypress): update docker image to use chrome v89
  .github/workflows/cypress-pr.yml
  .github/workflows/cypress-push.yml
Labels: Cypress, Passed Review, Squad Front End

#3849 docs: recommend using a locale object instead of using i18next FE-3983
  rfcs/text/i18n.md
Labels: Final Comments, RFC, Squad Front End

#3841 fix: will update pager after enter key is pressed - FE-3342
  cypress/features/regression/designSystem/flatTable.feature
  cypress/locators/flat-table/index.js
  cypress/locators/flat-table/locators.js
  cypress/support/step-definitions/flat-table-steps.js
  src/components/pager/pager.component.js
  src/components/pager/pager.spec.js
  src/components/select/option/option.component.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End

#3858 refactor(date-picker): remove css file import and add react day picker styles into styled wrapper
  src/__experimental__/components/date/__snapshots__/date-picker.spec.js.snap
  src/__experimental__/components/date/date-picker.component.js
  src/__experimental__/components/date/date-picker.spec.js
  src/__experimental__/components/date/day-picker.style.js
Labels: No UX QA Required, Passed QA, Passed Review, Squad Front End

#3848 feat(drawer): allows to use custom height - FE-3825
  src/components/drawer/__internal__/__snapshots__/drawer.spec.js.snap
  src/components/drawer/__internal__/drawer.component.js
  src/components/drawer/__internal__/drawer.d.ts
  src/components/drawer/__internal__/drawer.spec.js
  src/components/drawer/__internal__/drawer.stories.mdx
  src/components/drawer/__internal__/drawer.style.js
Labels: Passed QA, Passed Review, Passed UX QA, Squad Front End
