Repository Sage/carbon, pull requests merged in 2022-06, with the labels that each got.

#5195 chore(tooltip): hide target, isPartOfInput and inputSize props from prop table
  src/components/tooltip/tooltip.component.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#5184 test: update jest config to ignore lib/ and esm/
  jest.conf.json
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#5213 fix: fix missing type declarations - FE-5204
  scripts/build.js
  src/__internal__/utils/argTypes/specialCharacters.ts
  src/components/alert/alert-test.stories.mdx
  src/components/app-wrapper/app-wrapper-test.stories.mdx
  src/components/badge/badge-test.stories.mdx
  src/components/button-toggle/button-toggle-test.stories.mdx
  src/components/button/button-test.stories.mdx
  src/components/checkbox/checkbox-test.stories.mdx
  src/components/confirm/confirm-test.stories.mdx
  src/components/content/content-test.stories.mdx
  src/components/date-range/date-range-test.stories.mdx
  src/components/detail/detail-test.stories.mdx
  src/components/dialog-full-screen/dialog-full-screen-test.stories.mdx
  src/components/dialog/dialog-test.stories.mdx
  src/components/fieldset/fieldset-test.stories.mdx
  src/components/flat-table/flat-table-test.stories.mdx
  src/components/grouped-character/grouped-character-test.stories.mdx
  src/components/heading/heading-test.stories.mdx
  src/components/help/help-test.stories.mdx
  src/components/inline-inputs/inline-inputs.stories.mdx
  src/components/link/link-test.stories.mdx
  src/components/message/message-test.stories.mdx
  src/components/multi-action-button/multi-action-button-test.stories.tsx
  src/components/navigation-bar/navigation-bar-test.stories.mdx
  src/components/pager/pager-test.stories.mdx
  src/components/pill/pill-test.stories.mdx
  src/components/pod/pod-test.stories.mdx
  src/components/popover-container/popover-container-test.stories.mdx
  src/components/portrait/portrait-test.stories.mdx
  src/components/preview/preview-test.stories.mdx
  src/components/profile/profile-test.stories.js
  src/components/search/search-test.stories.mdx
  src/components/settings-row/settings-row-test.stories.mdx
  src/components/show-edit-pod/show-edit-pod-test.stories.js
  src/components/simple-color-picker/simple-color-picker-test.stories.mdx
  src/components/split-button/split-button-test.stories.mdx
  src/components/step-sequence/step-sequence-test.stories.mdx
  src/components/switch/switch-test.stories.mdx
  src/components/textarea/textarea-test.stories.js
  src/components/textbox/textbox-test.stories.mdx
  src/components/toast/toast-test.stories.mdx
  src/components/tooltip/tooltip-test.stories.mdx
  tsconfig.json
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5194 fix(date): ensure months and days are capitalised and formatted correctly for all locales FE-5197
  src/components/date-range/date-range.spec.js
  src/components/date/__internal__/date-picker/date-picker.component.js
  src/components/date/__internal__/date-picker/date-picker.d.ts
  src/components/date/__internal__/date-picker/date-picker.spec.js
  src/components/date/date.component.js
  src/components/date/date.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5117 feat(dialog, sidebar, menu-full-screen): set focus to dialog container on open
  cypress/integration/common/menu.feature
  cypress/locators/dialog/index.js
  cypress/locators/menu/index.js
  cypress/support/step-definitions/menu-steps.js
  src/__internal__/focus-trap/focus-trap-utils.js
  src/__internal__/focus-trap/focus-trap.component.js
  src/__internal__/focus-trap/focus-trap.spec.js
  src/components/advanced-color-picker/advanced-color-picker.component.js
  src/components/advanced-color-picker/advanced-color-picker.spec.js
  src/components/confirm/confirm.test.js
  src/components/dialog-full-screen/dialog-full-screen.component.js
  src/components/dialog-full-screen/dialog-full-screen.spec.js
  src/components/dialog/dialog.component.js
  src/components/menu/menu-full-screen/menu-full-screen.component.js
  src/components/menu/menu-full-screen/menu-full-screen.spec.js
  src/components/menu/menu-full-screen/menu-full-screen.style.js
  src/components/sidebar/__internal__/sidebar-header/sidebar-header.component.js
  src/components/sidebar/sidebar.component.js
  src/components/sidebar/sidebar.spec.js
Labels: Passed QA, No UX QA Required, Squad Front End

#5215 test(inline-inputs): add cypress tests
  cypress/fixtures/commonComponents/inlineInputs.json
  cypress/integration/common/inlineInputs.feature
  cypress/locators/inline-inputs/index.js
  cypress/locators/inline-inputs/locators.js
  cypress/support/step-definitions/inline-inputs-steps.js
  src/components/inline-inputs/inline-inputs.test.js
Labels: Pending QA, Cypress, Squad Front End

#5167 test(tooltip): add cypress tests
  cypress/fixtures/commonComponents/tooltip.json
  cypress/integration/common/tooltip.feature
  cypress/support/step-definitions/tooltip-steps.js
  src/components/tooltip/tooltip.test.js
Labels: Passed Review, Passed QA, Cypress, Squad Front End

#5189 chore(date): add DateChangeEvent interface and export from index file FE-5195
  src/components/date-range/date-range.d.ts
  src/components/date-range/index.d.ts
  src/components/date/date.d.ts
  src/components/date/index.d.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5186 fix(button-toggle-group): ensure that id prop is passed to FormField
  src/components/button-toggle-group/button-toggle-group.component.js
  src/components/button-toggle-group/button-toggle-group.spec.js
  src/components/flat-table/flat-table-body/flat-table-body.spec.js
  src/components/flat-table/flat-table-cell/flat-table-cell.spec.js
  src/components/flat-table/flat-table-head/flat-table-head.spec.js
  src/components/flat-table/flat-table-header/flat-table-header.spec.js
  src/components/flat-table/flat-table-row-header/flat-table-row-header.spec.js
  src/components/form/form.spec.js
  src/components/pages/pages.spec.js
  src/components/select/filterable-select/filterable-select.stories.mdx
  src/components/select/multi-select/multi-select.stories.mdx
  src/components/select/option-row/__snapshots__/option-row.spec.js.snap
  src/components/select/option-row/option-row.spec.js
  src/components/select/select-list/select-list.spec.js
  src/components/select/simple-select/simple-select.stories.mdx
  src/components/select/utils/with-filter.spec.js
  src/components/show-edit-pod/show-edit-pod.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5232 fix(heading): fix typings - FE-5214
  src/components/heading/index.d.ts
  tsconfig.json
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5209 fix(date): ensure that event contains input name and id when picker is used to change date FE-5206
  src/components/date/__internal__/date-picker/date-picker.component.js
  src/components/date/__internal__/date-picker/date-picker.spec.js
  src/components/date/date.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5230 chore(github): corrects wording on 'Expected behaviour' help text
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: Passed Review, Pending QA, Passed QA, No UX QA Required, third-party

#5214 chore(flat-table-header): add displayName to component FE-5208
  src/components/flat-table/flat-table-cell/flat-table-cell.component.js
  src/components/flat-table/flat-table-checkbox/flat-table-checkbox.component.js
  src/components/flat-table/flat-table-header/flat-table-header.component.js
  src/components/flat-table/flat-table-row-header/flat-table-row-header.component.js
  src/components/flat-table/flat-table-row/flat-table-row.component.js
  src/components/flat-table/flat-table-row/flat-table-row.spec.js
  src/components/flat-table/flat-table.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5228 test(button-toggle): refactor for cypress tests
  cypress/e2e/common/buttonToggle.feature
  cypress/e2e/common/buttonToggleGroup.feature
  cypress/fixtures/commonComponents/buttonToggle.json
  cypress/locators/button-toggle-group/index.js
  cypress/locators/button-toggle-group/locators.js
  cypress/locators/button-toggle/index.js
  cypress/locators/button-toggle/locators.js
  cypress/support/step-definitions/button-toggle-group-steps.js
  cypress/support/step-definitions/button-toggle-steps.js
  src/components/button-toggle-group/button-toggle-group.test.js
  src/components/button-toggle/button-toggle.test.js
Labels: Pending Review, Cypress, Squad Front End, button-toggle-group, button-toggle

#5225 fix(date): ensure that contrast ratio for weekday meets AA standards
  src/components/date/__internal__/weekday/__snapshots__/weekday.spec.js.snap
  src/components/date/__internal__/weekday/weekday.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5221 fix(submenu): make menu open on click even when clickToOpen prop missing
  src/components/menu/__internal__/submenu/submenu.component.js
  src/components/menu/__internal__/submenu/submenu.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5251 chore: rollback version of storybook and its addons
  package-lock.json
  package.json
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#5241 fix(heading): fix axe violations (FE-4979)
  src/components/heading/heading.component.js
  src/components/heading/heading.spec.js
  src/components/help/help.component.js
  src/components/help/help.spec.js
  src/locales/en-gb.ts
  src/locales/locale.ts
  src/locales/pl-pl.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5238 test(icon): add cypress tests
  cypress/e2e/common/icon.feature
  cypress/fixtures/commonComponents/icon.json
  cypress/support/step-definitions/action-popover-steps.js
  cypress/support/step-definitions/icon-steps.js
  src/components/icon/icon.test.js
Labels: Passed Review, Passed QA, Cypress, Squad Front End

#5253 test(date-range): refactor for cypress tests
  cypress/e2e/common/dateRange.feature
  cypress/fixtures/commonComponents/dateRange.json
  cypress/locators/date-range/index.js
  cypress/locators/date-range/locators.js
  cypress/support/step-definitions/date-range-steps.js
  src/components/date-range/date-range.test.js
Labels: Passed Review, Passed QA, Cypress, Squad Front End
