Repository Sage/carbon, pull requests merged in 2022-09, with the labels that each got.

#5425 test(popover-container): refactor for cypress tests
  cypress/e2e/common/popoverContainer.feature
  cypress/fixtures/commonComponents/popoverContainer.json
  cypress/locators/popover-container/index.js
  cypress/support/step-definitions/popover-container-steps.js
  src/components/popover-container/popover-container.test.js
Labels: Passed Review, Passed QA, Cypress, Squad Front End, popover-container

#5373 refactor(textbox): convert to typescript - FE-4840
  cypress/e2e/common/textarea.feature
  cypress/fixtures/commonComponents/textarea.json
  cypress/support/step-definitions/text-area-steps.js
  src/__internal__/character-count/character-count.component.js
  src/__internal__/character-count/character-count.component.tsx
  src/__internal__/character-count/character-count.spec.tsx
  src/__internal__/character-count/character-count.style.ts
  src/__internal__/character-count/index.ts
  src/__internal__/input/index.ts
  src/components/date/date-test.stories.mdx
  src/components/decimal/decimal-test.stories.mdx
  src/components/fieldset/__snapshots__/fieldset.spec.tsx.snap
  src/components/grouped-character/grouped-character-test.stories.mdx
  src/components/number/number-test.stories.mdx
  src/components/numeral-date/numeral-date-context.js
  src/components/numeral-date/numeral-date-context.ts
  src/components/select/multi-select/multi-select-test.stories.tsx
  src/components/select/multi-select/multi-select.component.js
  src/components/textarea/textarea-test.stories.js
  src/components/textarea/textarea.component.js
  src/components/textarea/textarea.d.ts
  src/components/textarea/textarea.spec.js
  src/components/textbox/__internal__/prefix.style.ts
  src/components/textbox/index.d.ts
  src/components/textbox/index.js
  src/components/textbox/index.ts
  src/components/textbox/textbox-test.stories.tsx
  src/components/textbox/textbox.component.tsx
  src/components/textbox/textbox.d.ts
  src/components/textbox/textbox.spec.tsx
  src/components/textbox/textbox.style.ts
  src/hooks/__internal__/useCharacterCount/useCharacterCount.spec.tsx
  src/hooks/__internal__/useCharacterCount/useCharacterCount.tsx
  src/hooks/__internal__/useInputAccessibility/useInputAccessibility.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5367 fix(select): ensure select list always has correct height to fit content
  src/components/select/select-list/select-list.component.js
  src/components/select/simple-select/simple-select-test.stories.js
  src/components/select/simple-select/simple-select.test.js
Labels: Passed Review, Pending QA, No UX QA Required, Squad Front End

#5335 fix(popover-container): remove incorrect role attribute - FE-5249
  src/components/popover-container/popover-container.component.tsx
  src/components/popover-container/popover-container.spec.tsx
  src/components/popover-container/popover-container.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End, Passed a11y Review

#5433 fix(flat-table-row): allow click actions inside interactive row
  cypress/e2e/common/flatTable.feature
  cypress/support/step-definitions/flat-table-steps.js
  src/components/flat-table/flat-table-row/flat-table-row.style.js
  src/components/flat-table/flat-table-test.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5423 docs(dialog): add responsive examples
  src/components/definition-list/dd.component.tsx
  src/components/definition-list/definition-list.stories.mdx
  src/components/definition-list/dl.component.tsx
  src/components/definition-list/dt.component.tsx
  src/components/dialog/dialog.stories.mdx
  src/components/preview/preview.stories.mdx
  src/components/profile/profile.stories.mdx
  src/components/step-sequence/step-sequence.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5442 docs(fieldset): add missing checkbox import
  src/components/fieldset/fieldset.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5438 refactor: convert mockresizeobserver to typescript (FE-5302)
  src/__spec_helper__/mock-resize-observer.ts
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#5448 docs(typography): add more detail about inline elements and the truncate prop
  src/components/typography/typography.stories.mdx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#5329 feat(scrollable-block): add parent prop and fix rendered HTML
  cypress/e2e/common/menu.feature
  cypress/locators/menu/locators.js
  cypress/support/step-definitions/menu-steps.js
  src/components/menu/__internal__/submenu/submenu.component.js
  src/components/menu/__internal__/submenu/submenu.spec.js
  src/components/menu/menu-item/menu-item.component.js
  src/components/menu/menu-item/menu-item.d.ts
  src/components/menu/menu-item/menu-item.style.js
  src/components/menu/menu.stories.mdx
  src/components/menu/scrollable-block/scrollable-block.component.js
  src/components/menu/scrollable-block/scrollable-block.d.ts
  src/components/menu/scrollable-block/scrollable-block.spec.js
  src/components/menu/scrollable-block/scrollable-block.style.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5429 refactor(i18n-provider): convert to TypeScript
  src/__internal__/i18n-context/index.ts
  src/components/i18n-provider/i18n-provider.component.js
  src/components/i18n-provider/i18n-provider.component.tsx
  src/components/i18n-provider/i18n-provider.d.ts
  src/components/i18n-provider/i18n-provider.spec.tsx
  src/components/i18n-provider/index.d.ts
  src/components/i18n-provider/index.js
  src/components/i18n-provider/index.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5354 fix(select): ensure aria-activedescendant is always valid
  cypress/support/step-definitions/select-steps.js
  src/__internal__/popover/popover.component.tsx
  src/__internal__/popover/popover.spec.tsx
  src/__internal__/popover/popover.style.ts
  src/components/select/filterable-select/filterable-select.component.js
  src/components/select/filterable-select/filterable-select.spec.js
  src/components/select/filterable-select/filterable-select.test.js
  src/components/select/multi-select/multi-select.component.js
  src/components/select/multi-select/multi-select.spec.js
  src/components/select/select-list/select-list.component.js
  src/components/select/select-list/select-list.spec.js
  src/components/select/simple-select/simple-select.component.js
  src/components/select/simple-select/simple-select.spec.js
  src/components/select/simple-select/simple-select.test.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5428 feat(search): add validation props (FE-5292)
  src/components/search/search.component.js
  src/components/search/search.d.ts
  src/components/search/search.stories.mdx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5424 refactor(sidebar): covert to typescript - FE-4832
  src/components/sidebar/__internal__/sidebar-header/__definition__.js
  src/components/sidebar/__internal__/sidebar-header/index.ts
  src/components/sidebar/__internal__/sidebar-header/sidebar-header.component.js
  src/components/sidebar/__internal__/sidebar-header/sidebar-header.component.tsx
  src/components/sidebar/__internal__/sidebar-header/sidebar-header.spec.tsx
  src/components/sidebar/__internal__/sidebar-header/sidebar-header.style.ts
  src/components/sidebar/index.d.ts
  src/components/sidebar/index.js
  src/components/sidebar/index.ts
  src/components/sidebar/sidebar-test.stories.tsx
  src/components/sidebar/sidebar.component.tsx
  src/components/sidebar/sidebar.config.ts
  src/components/sidebar/sidebar.d.ts
  src/components/sidebar/sidebar.spec.tsx
  src/components/sidebar/sidebar.stories.mdx
  src/components/sidebar/sidebar.style.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5435 fix(tabs, icon): override behaviour of icon with tooltip when rendered inside tab title
  src/components/icon/icon.component.tsx
  src/components/icon/icon.spec.tsx
  src/components/tabs/__internal__/tab-title/tab-title.component.js
  src/components/tabs/__internal__/tab-title/tab-title.d.ts
  src/components/tabs/__internal__/tab-title/tab-title.spec.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5397 fix(flat-table-header): alternative color not changing according theme
  src/components/flat-table/flat-table-header/flat-table-header-utils.js
  src/components/flat-table/flat-table-header/flat-table-header.component.js
  src/components/flat-table/flat-table-header/flat-table-header.spec.js
  src/components/flat-table/flat-table-header/flat-table-header.style.js
Labels: Passed Review, Passed QA, Passed UX QA, third-party

#5443 feat(icon): 3 new icons, alert_on, palm_tree and tick_thick
  src/components/icon/__snapshots__/icon-unicodes.spec.js.snap
  src/components/icon/fonts/carbon-icons-webfont.woff
  src/components/icon/icon-config.ts
  src/components/icon/icon-type.ts
  src/components/icon/icon-unicodes.js
  src/style/assets/carbon-icons-webfont.woff
Labels: Passed Review, Passed QA, Passed UX QA

#5457 refactor(image): convert to typescript
  src/components/image/image.component.js
  src/components/image/image.component.tsx
  src/components/image/image.d.ts
  src/components/image/image.spec.tsx
  src/components/image/image.style.ts
  src/components/image/index.d.ts
  src/components/image/index.js
  src/components/image/index.ts
Labels: Passed Review, Pending QA, Passed QA, No UX QA Required, Squad Front End

#5439 fix(button): always pass aria-label down to the html element (FE-5279)
  src/components/button/button.component.tsx
  src/components/button/button.spec.tsx
  src/components/multi-action-button/__snapshots__/multi-action-button.spec.tsx.snap
Labels: Pending Review, Passed QA, No UX QA Required, Squad Front End

#5417 refactor(dialog): convert to typescript - FE-4784
  src/components/alert/alert.component.tsx
  src/components/alert/index.ts
  src/components/dialog/dialog-test.stories.tsx
  src/components/dialog/dialog.component.tsx
  src/components/dialog/dialog.config.ts
  src/components/dialog/dialog.d.ts
  src/components/dialog/dialog.spec.tsx
  src/components/dialog/dialog.style.ts
  src/components/dialog/index.d.ts
  src/components/dialog/index.js
  src/components/dialog/index.ts
  src/components/modal/modal.component.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5440 feat(form): add support for full width buttons - FE-4204
  src/components/form/__internal__/form-summary.component.js
  src/components/form/__internal__/form-summary.d.ts
  src/components/form/__internal__/form-summary.style.js
  src/components/form/form.component.js
  src/components/form/form.d.ts
  src/components/form/form.spec.js
  src/components/form/form.stories.mdx
  src/components/form/form.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5455 feat(link): add support for negative and neutral states and better contrast on dark backgrounds FE-5339
  cypress/support/step-definitions/text-area-steps.js
  package-lock.json
  package.json
  src/components/button-bar/button-bar.test.js
  src/components/button-toggle-group/button-toggle-group.test.js
  src/components/card/__snapshots__/card.spec.js.snap
  src/components/checkbox/checkbox.test.js
  src/components/confirm/confirm.test.js
  src/components/date-range/date-range.test.js
  src/components/fieldset/fieldset.test.js
  src/components/heading/heading.style.js
  src/components/link/__snapshots__/link.spec.tsx.snap
  src/components/link/link-test.stories.mdx
  src/components/link/link-test.stories.tsx
  src/components/link/link.component.tsx
  src/components/link/link.config.ts
  src/components/link/link.spec.tsx
  src/components/link/link.stories.mdx
  src/components/link/link.style.ts
  src/components/link/link.test.js
  src/components/menu/menu-item/menu-item.spec.js
  src/components/menu/menu-item/menu-item.style.js
  src/components/message/message.test.js
  src/components/number/number.test.js
  src/components/pod/__snapshots__/pod.spec.js.snap
  src/components/portal/__snapshots__/portal.spec.tsx.snap
  src/components/simple-color-picker/simple-color-picker.test.js
  src/components/text-editor/text-editor.test.js
  src/components/toast/toast.test.js
  src/style/design-tokens/carbon-scoped-tokens-provider/__snapshots__/carbon-scoped-tokens-provider.component.spec.tsx.snap
  src/style/themes/aegean/__snapshots__/aegean-theme.spec.ts.snap
  src/style/themes/mint/__snapshots__/mint-theme.spec.ts.snap
  src/style/themes/none/__snapshots__/none.spec.ts.snap
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5432 feat: add optional list height prop - FE-5313
  src/components/select/filterable-select/filterable-select.component.js
  src/components/select/filterable-select/filterable-select.d.ts
  src/components/select/filterable-select/filterable-select.spec.js
  src/components/select/filterable-select/filterable-select.stories.mdx
  src/components/select/filterable-select/filterable-select.test.js
  src/components/select/multi-select/multi-select.component.js
  src/components/select/multi-select/multi-select.d.ts
  src/components/select/multi-select/multi-select.spec.js
  src/components/select/multi-select/multi-select.stories.mdx
  src/components/select/select-list/select-list-container.style.js
  src/components/select/select-list/select-list.component.js
  src/components/select/select-list/select-list.spec.js
  src/components/select/select-list/select-list.style.js
  src/components/select/simple-select/simple-select.component.js
  src/components/select/simple-select/simple-select.d.ts
  src/components/select/simple-select/simple-select.spec.js
  src/components/select/simple-select/simple-select.stories.mdx
  src/components/select/simple-select/simple-select.test.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5485 test(search): refactor for cypress tests
  cypress/e2e/common/search.feature
  cypress/fixtures/commonComponents/search.json
  cypress/locators/search/index.js
  cypress/locators/search/locators.js
  cypress/support/step-definitions/menu-steps.js
  cypress/support/step-definitions/search-steps.js
  src/components/search/search.test.js
Labels: Passed Review, Pending QA, Cypress, Squad Front End, search

#5487 fix(confirm): update DialogProps import path to ensure interface is extended correctly
  src/components/confirm/confirm.d.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5449 refactor(carousel): convert to typescript
  src/components/carousel/carousel-test.stories.tsx
  src/components/carousel/carousel.component.tsx
  src/components/carousel/carousel.d.ts
  src/components/carousel/carousel.spec.tsx
  src/components/carousel/carousel.stories.mdx
  src/components/carousel/carousel.style.ts
  src/components/carousel/carousel.test.js
  src/components/carousel/index.d.ts
  src/components/carousel/index.js
  src/components/carousel/index.ts
  src/components/carousel/slide.config.ts
  src/components/carousel/slide/index.d.ts
  src/components/carousel/slide/index.js
  src/components/carousel/slide/index.ts
  src/components/carousel/slide/slide.component.tsx
  src/components/carousel/slide/slide.d.ts
  src/components/carousel/slide/slide.style.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5437 test(duelling-picklist): refactor for cypress tests
  cypress/e2e/common/duellingPicklist.feature
  cypress/locators/duelling-picklist/index.js
  cypress/locators/duelling-picklist/locators.js
  cypress/support/step-definitions/duelling-picklist-steps.js
  src/components/duelling-picklist/duelling-picklist.test.js
Labels: Passed Review, Passed QA, Cypress, Squad Front End, duelling-picklist

#5477 feat(tile): add support for active variant styling FE-5355
  src/components/tile/__snapshots__/tile.spec.js.snap
  src/components/tile/tile.component.js
  src/components/tile/tile.config.js
  src/components/tile/tile.d.ts
  src/components/tile/tile.spec.js
  src/components/tile/tile.stories.mdx
  src/components/tile/tile.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5491 test(link-preview): refactor for cypress tests
  cypress/e2e/common/linkPreview.feature
  cypress/locators/link-preview/index.js
  cypress/support/component-helper/common-steps.js
  cypress/support/step-definitions/link-preview-steps.js
  package-lock.json
  package.json
  src/components/link-preview/link-preview.test.js
  src/components/search/search.test.js
Labels: Passed Review, Passed QA, Cypress, Squad Front End, link-preview

#5414 fix(dialog, dialog-full-screen, sidebar, form): ensure focused elements are displayed on screen FE-5236
  src/components/advanced-color-picker/advanced-color-picker.style.js
  src/components/dialog-full-screen/content.style.js
  src/components/dialog-full-screen/dialog-full-screen.component.js
  src/components/dialog-full-screen/dialog-full-screen.spec.js
  src/components/dialog-full-screen/dialog-full-screen.stories.mdx
  src/components/dialog/dialog.component.tsx
  src/components/dialog/dialog.spec.tsx
  src/components/dialog/dialog.stories.mdx
  src/components/dialog/dialog.style.ts
  src/components/form/form.component.js
  src/components/form/form.spec.js
  src/components/form/form.style.js
  src/components/sidebar/sidebar.component.tsx
  src/components/sidebar/sidebar.spec.tsx
  src/hooks/__internal__/useIsStickyFooterForm/index.ts
  src/hooks/__internal__/useIsStickyFooterForm/useIsStickyFooterForm.spec.tsx
  src/hooks/__internal__/useIsStickyFooterForm/useIsStickyFooterForm.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5462 fix(popover-container): fix positioning with renderOpenComponent prop - FE-5356
  src/components/popover-container/popover-container.component.tsx
  src/components/popover-container/popover-container.stories.mdx
  src/components/popover-container/popover-container.test.js
Labels: Passed Review, Passed QA, Squad Front End

#5461 test(pod): add cypress tests
  cypress/e2e/common/pod.feature
  cypress/fixtures/commonComponents/pod.json
  cypress/locators/pod/index.js
  cypress/locators/pod/locators.js
  cypress/support/component-helper/common-steps.js
  cypress/support/step-definitions/pod-steps.js
  src/components/pod/pod.test.js
Labels: Passed Review, Passed QA, Cypress, Squad Front End, pod

#5497 fix(tabs): update type definition for validationStatusOverride prop
  src/components/tabs/tabs.d.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5500 test(pager): refactor for cypress tests
  cypress/e2e/common/pager.feature
  cypress/fixtures/commonComponents/pager.json
  cypress/locators/pager/index.js
  cypress/locators/pager/locators.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/pager-steps.js
  src/components/pager/pager.test.js
Labels: Passed Review, Passed QA, Cypress, Squad Front End, pager

#5499 refactor(tile): convert test story to typescript
  src/components/tile/tile-test.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5471 refactor(preview): refactor code and convert files to typescript (FE-4822)
  src/components/link-preview/link-preview.spec.js
  src/components/link-preview/link-preview.style.js
  src/components/preview/__internal__/preview-placeholder.component.tsx
  src/components/preview/__internal__/preview-placeholder.style.ts
  src/components/preview/__snapshots__/preview.spec.js.snap
  src/components/preview/index.d.ts
  src/components/preview/index.js
  src/components/preview/index.ts
  src/components/preview/preview-test.stories.mdx
  src/components/preview/preview-test.stories.tsx
  src/components/preview/preview.component.js
  src/components/preview/preview.component.tsx
  src/components/preview/preview.d.ts
  src/components/preview/preview.spec.js
  src/components/preview/preview.spec.tsx
  src/components/preview/preview.style.js
  src/components/preview/preview.style.ts
  src/components/preview/preview.test.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5503 ci(cypress): rearrange resources
  .github/workflows/cypress.yml
  src/components/accordion/accordion.test.js
  src/components/batch-selection/batch-selection.test.js
  src/components/loader/loader.test.js
  src/components/toast/toast.test.js
Labels: Pending Review, Passed QA, Cypress, Squad Front End

#5481 feat(progress-tracker): add default value for aria-valuenow
  src/components/progress-tracker/progress-tracker.component.js
  src/components/progress-tracker/progress-tracker.spec.js
  src/components/progress-tracker/progress-tracker.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5430 fix hover dropdown and action popover hover colours so they align with figma implementation
  src/components/action-popover/action-popover.style.ts
  src/components/action-popover/action-popover.test.js
  src/components/select/filterable-select/filterable-select.test.js
  src/components/select/list-action-button/__snapshots__/list-action-button.spec.js.snap
  src/components/select/list-action-button/list-action-button.style.js
  src/components/select/multi-select/multi-select.test.js
  src/components/select/option-row/__snapshots__/option-row.spec.js.snap
  src/components/select/option-row/option-row.spec.js
  src/components/select/option-row/option-row.style.js
  src/components/select/option/__snapshots__/option.spec.js.snap
  src/components/select/option/option.spec.js
  src/components/select/option/option.style.js
  src/components/select/simple-select/simple-select.test.js
Labels: Passed Review, Passed QA, Passed UX QA, action-popover, select

#5479 refactor(heading): convert Heading component to use Typescript
  src/components/heading/heading.component.tsx
  src/components/heading/heading.d.ts
  src/components/heading/heading.spec.tsx
  src/components/heading/heading.style.ts
  src/components/heading/index.d.ts
  src/components/heading/index.js
  src/components/heading/index.ts
  src/components/pages/pages-test.stories.tsx
Labels: Passed Review, Passed QA, Pending UX QA, Squad Front End, heading

#5454 fix(select): reposition the select list after select has changed position - FE-5303
  cypress/support/step-definitions/flat-table-steps.js
  package-lock.json
  package.json
  src/__internal__/popover/popover.component.tsx
  src/__internal__/popover/popover.spec.tsx
  src/components/action-popover/action-popover.test.js
  src/components/date/__internal__/date-picker/__snapshots__/date-picker.spec.js.snap
  src/components/date/__internal__/date-picker/date-picker.component.js
  src/components/date/__internal__/date-picker/date-picker.spec.js
  src/components/date/__internal__/date-picker/day-picker.style.js
  src/components/date/date.test.js
  src/components/popover-container/popover-container.component.tsx
  src/components/popover-container/popover-container.spec.tsx
  src/components/select/filterable-select/filterable-select.component.js
  src/components/select/filterable-select/filterable-select.d.ts
  src/components/select/filterable-select/filterable-select.spec.js
  src/components/select/filterable-select/filterable-select.stories.mdx
  src/components/select/filterable-select/filterable-select.test.js
  src/components/select/multi-select/multi-select.component.js
  src/components/select/multi-select/multi-select.d.ts
  src/components/select/multi-select/multi-select.spec.js
  src/components/select/multi-select/multi-select.stories.mdx
  src/components/select/multi-select/multi-select.test.js
  src/components/select/select-list/select-list-container.style.js
  src/components/select/select-list/select-list.component.js
  src/components/select/select-list/select-list.spec.js
  src/components/select/select-textbox/select-textbox.component.js
  src/components/select/select-textbox/select-textbox.spec.js
  src/components/select/simple-select/simple-select-test.stories.js
  src/components/select/simple-select/simple-select.component.js
  src/components/select/simple-select/simple-select.d.ts
  src/components/select/simple-select/simple-select.spec.js
  src/components/select/simple-select/simple-select.stories.mdx
  src/components/select/simple-select/simple-select.test.js
  src/hooks/__internal__/useFloating/index.ts
  src/hooks/__internal__/useFloating/useFloating.spec.tsx
  src/hooks/__internal__/useFloating/useFloating.ts
Labels: Pending Review, Pending QA, Squad Front End

#5505 fix(menu): ensure submenu closes when enter key is pressed - FE-4919
  src/components/menu/__internal__/submenu/submenu.component.js
  src/components/menu/__internal__/submenu/submenu.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End
