Repository Sage/carbon, pull requests merged in 2022-02, with the labels that each got.

#4791 fix(design-tokens): fix scoped tokens in mfe
  src/__internal__/popover/popover.component.js
  src/__internal__/popover/popover.spec.js
  src/components/menu/menu-full-screen/menu-full-screen.spec.js
  src/components/portal/__snapshots__/portal.spec.js.snap
  src/components/portal/portal.js
  src/components/portal/portal.spec.js
  src/components/tooltip/tooltip.component.js
  src/components/tooltip/tooltip.spec.js
  src/style/design-tokens/carbon-scoped-tokens-provider/__snapshots__/carbon-scoped-tokens-provider.component.spec.js.snap
  src/style/design-tokens/carbon-scoped-tokens-provider/carbon-scoped-tokens-provider.component.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4703 fix: icon buttons accessibility issue - FE-4630
  src/__internal__/tooltip-provider/index.d.ts
  src/__internal__/tooltip-provider/index.js
  src/components/button/__snapshots__/button.spec.js.snap
  src/components/button/button.component.js
  src/components/button/button.spec.js
  src/components/icon-button/icon-button.component.js
  src/components/icon-button/icon-button.spec.js
  src/components/icon-button/icon-button.stories.mdx
  src/components/icon/icon.component.js
  src/components/icon/icon.spec.js
  src/components/tooltip/tooltip.component.js
  src/components/tooltip/tooltip.d.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4709 feat(accordion): describe accordion using design tokens - FE-4501
  cypress/support/step-definitions/accordion-steps.js
  src/components/accordion/accordion.spec.js
  src/components/accordion/accordion.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4778 test: add decorator for tokens and locales
  .github/workflows/cypress.yml
  cypress.json
  cypress/support/component-helper/cypress-mount.js
  src/components/alert/alert.test.js
  src/components/anchor-navigation/anchor-navigation.test.js
  src/components/app-wrapper/app-wrapper.test.js
  src/components/decimal/decimal.test.js
  src/components/detail/detail.test.js
  src/components/grouped-character/grouped-character.test.js
Labels: Passed Review, Passed QA, No UX QA Required, Cypress, Squad Front End

#4718 feat(dialog, dialog-full-screen, confirm): generate IDs dynamically (FE-4700)
  cypress/locators/dialog/locators.js
  src/components/confirm/confirm.component.js
  src/components/confirm/confirm.spec.js
  src/components/dialog-full-screen/dialog-full-screen.component.js
  src/components/dialog-full-screen/dialog-full-screen.spec.js
  src/components/dialog-full-screen/dialog-full-screen.stories.mdx
  src/components/dialog/dialog.component.js
  src/components/dialog/dialog.spec.js
  src/components/dialog/dialog.stories.mdx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4724 feat(tile-select): describe Tile Select component using design tokens (FE-4727)
  src/components/tile-select/tile-select.spec.js
  src/components/tile-select/tile-select.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4735 refactor(draggable): update usages of react dnd
  cypress/support/step-definitions/card-steps.js
  package-lock.json
  package.json
  src/components/card/card-test.stories.mdx
  src/components/card/card.stories.mdx
  src/components/draggable/draggable-container.component.js
  src/components/draggable/draggable-item.component.js
  src/components/draggable/draggable-test.stories.js
  src/components/draggable/draggable.stories.mdx
  src/components/flat-table/flat-table-body-draggable/flat-table-body-draggable.component.js
  src/components/flat-table/flat-table-body-draggable/flat-table-body-draggable.spec.js
  src/components/flat-table/flat-table-row/__internal__/flat-table-row-draggable.component.js
  src/components/flat-table/flat-table.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4738 feat(sidebar): use design tokens to describe sidebar
  src/components/sidebar/sidebar.spec.js
  src/components/sidebar/sidebar.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4732 feat(dialog): describe dialog and dialog full screen with design tokens
  src/components/dialog-full-screen/dialog-full-screen.style.js
  src/components/dialog/dialog.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4754 refactor(loader): replace token colorsYang with proper category token
  src/components/loader/loader-square.spec.js
  src/components/loader/loader-square.style.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad DS Alignment

#4753 refactor(button): replace token colorsYin with proper category token
  src/components/button/button-types.style.js
  src/components/button/button.spec.js
  src/components/split-button/split-button.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad DS Alignment

#4733 fix(navigation-bar): add z-index so NavigationBar stacks just below Modals
  src/components/navigation-bar/navigation-bar.spec.tsx
  src/components/navigation-bar/navigation-bar.style.ts
  src/components/portal/__snapshots__/portal.spec.js.snap
  src/style/themes/base/base-theme.config.js
  src/style/themes/base/index.d.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4750 fix(accessibility): fix incorrect aria-describedby on input (FE-4713)
  src/__internal__/checkable-input/checkable-input.component.js
  src/__internal__/checkable-input/checkable-input.spec.js
  src/__internal__/form-field/form-field.component.js
  src/__internal__/form-field/form-field.d.ts
  src/__internal__/input-icon-toggle/input-icon-toggle.component.js
  src/__internal__/input-icon-toggle/input-icon-toggle.d.ts
  src/__internal__/input-icon-toggle/input-icon-toggle.spec.js
  src/__internal__/label/label.component.js
  src/__internal__/label/label.d.ts
  src/__internal__/label/label.spec.js
  src/__internal__/tooltip-provider/index.js
  src/components/help/help.component.js
  src/components/help/help.d.ts
  src/components/textarea/textarea.component.js
  src/components/textarea/textarea.spec.js
  src/components/textbox/textbox.component.js
  src/components/textbox/textbox.spec.js
  src/hooks/__internal__/useInputAccessibility/index.spec.js
  src/hooks/__internal__/useInputAccessibility/useInputAccessibility.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4757 refactor(app-wrapper): add deprecation warning (FE-3649)
  src/components/app-wrapper/app-wrapper.component.js
  src/components/app-wrapper/app-wrapper.stories.mdx
  src/components/dialog-full-screen/dialog-full-screen.stories.mdx
  src/components/form/form.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4749 docs(design-tokens): update documentation for design tokens provider
  docs/getting-started.stories.mdx
Labels: Passed Review, No QA Required, No UX QA Required, Squad DS Alignment

#4681 fix(menu-full-screen): fix heights and widths and remove horizontal s…
  cypress/integration/common/menu.feature
  cypress/support/step-definitions/menu-steps.js
  src/components/menu/__internal__/submenu/submenu.spec.js
  src/components/menu/__internal__/submenu/submenu.style.js
  src/components/menu/menu-full-screen/menu-full-screen.component.js
  src/components/menu/menu-full-screen/menu-full-screen.spec.js
  src/components/menu/menu-full-screen/menu-full-screen.style.js
  src/components/menu/menu-item/menu-item.style.js
  src/components/menu/menu-test.stories.js
  src/components/menu/menu.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4736 feat: dismissible buttons labels - FE-4154
  src/components/dialog-full-screen/dialog-full-screen.component.js
  src/components/dialog-full-screen/dialog-full-screen.stories.mdx
  src/components/dialog/dialog.component.js
  src/components/dialog/dialog.stories.mdx
  src/components/sidebar/sidebar.component.js
  src/components/sidebar/sidebar.stories.mdx
  src/components/toast/toast.component.js
  src/components/toast/toast.stories.mdx
  src/locales/en-gb.js
  src/locales/locale.d.ts
  src/locales/pl-pl.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4726 feat(anchor-navigation): describe anchor navigation using design tokens, update test - FE-4730
  src/components/anchor-navigation/anchor-navigation-item/anchor-navigation-item.style.js
  src/components/anchor-navigation/anchor-navigation.spec.js
  src/components/anchor-navigation/anchor-navigation.style.js
  src/components/anchor-navigation/anchor-section-divider/anchor-section-divider.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4756 feat(dialog): surface contentPadding prop to allow overriding default padding values dialog content FE-4758
  src/components/dialog/dialog.component.js
  src/components/dialog/dialog.config.js
  src/components/dialog/dialog.d.ts
  src/components/dialog/dialog.spec.js
  src/components/dialog/dialog.stories.mdx
  src/components/dialog/dialog.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4803 chore(deps): upgrade design tokens package to the version 1.91.0
  package-lock.json
  package.json
  src/components/portal/__snapshots__/portal.spec.js.snap
  src/style/design-tokens/carbon-scoped-tokens-provider/__snapshots__/carbon-scoped-tokens-provider.component.spec.js.snap
  src/style/themes/aegean/__snapshots__/aegean-theme.spec.js.snap
  src/style/themes/mint/__snapshots__/mint-theme.spec.js.snap
  src/style/themes/none/__snapshots__/none.spec.js.snap
Labels: Passed Review, No QA Required, No UX QA Required, Squad DS Alignment

#4786 fix(icon): fix tooltip visible logic when disabled
  src/components/icon/icon.component.js
  src/components/icon/icon.spec.js
Labels: Passed Review, Pending QA, No UX QA Required, Squad DS Alignment

#4782 test(batch selection): add refactored tests for batch selection FE-4518
  cypress/fixtures/commonComponents/batchSelection.json
  cypress/integration/common/batchSelection.feature
  cypress/support/step-definitions/batch-selection-steps.js
  src/components/batch-selection/batch-selection.test.js
Labels: Pending Review, Pending QA, Cypress, Squad Front End

#4815 fix(design-tokens): fix scoped tokens in mfe
  src/__internal__/popover/popover.component.js
  src/__internal__/popover/popover.spec.js
  src/components/menu/menu-full-screen/menu-full-screen.spec.js
  src/components/portal/__snapshots__/portal.spec.js.snap
  src/components/portal/portal.js
  src/components/portal/portal.spec.js
  src/components/tooltip/tooltip.component.js
  src/components/tooltip/tooltip.spec.js
  src/style/design-tokens/carbon-scoped-tokens-provider/__snapshots__/carbon-scoped-tokens-provider.component.spec.js.snap
  src/style/design-tokens/carbon-scoped-tokens-provider/carbon-scoped-tokens-provider.component.js
Labels: Passed Review

#4802 docs(draggable): display expected prop types for props in docs
  src/components/draggable/draggable.stories.mdx
  src/components/flat-table/flat-table-body-draggable/flat-table-body-draggable.component.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4780 feat(search): describe search component using design tokens
  cypress/support/step-definitions/search-steps.js
  src/components/search/search.spec.js
  src/components/search/search.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4766 feat(navigation bar): describe navigation bar using design tokens, update tests - FE - 4873
  src/components/navigation-bar/navigation-bar.spec.tsx
  src/components/navigation-bar/navigation-bar.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4819 fix(docs): sort versions by semver in picker
  .storybook/version-picker/index.js
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#4755 fix(toast): make toast position fixed to top of viewport
  cypress/fixtures/commonComponents/toast.json
  cypress/integration/common/toast.feature
  cypress/support/step-definitions/toast-steps.js
  src/components/toast/toast-test.stories.mdx
  src/components/toast/toast.style.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4584 feat(button-toggle): describe ButtonToggle and ButtonToggleGroup components using design tokens (FE-4449)
  cypress/fixtures/themes/themes.json
  src/components/button-toggle-group/__snapshots__/button-toggle-group.spec.js.snap
  src/components/button-toggle-group/button-toggle-group.spec.js
  src/components/button-toggle-group/button-toggle-group.style.js
  src/components/button-toggle/__snapshots__/button-toggle.spec.js.snap
  src/components/button-toggle/button-toggle.spec.js
  src/components/button-toggle/button-toggle.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4807 chore(deps): update dependencies to resolve npm vulns
  .codesandbox/ci.json
  package-lock.json
  package.json
  src/components/profile/profile-test.stories.js
  src/components/profile/profile-test.stories.mdx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#4461 feat(select): block scroll while select is open - FE-4284
  cypress/locators/select/index.js
  cypress/support/step-definitions/select-steps.js
  src/__internal__/popover/index.d.ts
  src/__internal__/popover/popover.component.js
  src/__internal__/popover/popover.d.ts
  src/__internal__/popover/popover.spec.js
  src/__internal__/popover/popover.style.js
  src/components/alert/alert.test.js
  src/components/date/__internal__/date-picker/__snapshots__/date-picker.spec.js.snap
  src/components/dialog/dialog.style.js
  src/components/form/form.stories.mdx
  src/components/modal/__snapshots__/modal.spec.js.snap
  src/components/modal/modal.component.js
  src/components/modal/modal.spec.js
  src/components/modal/modal.style.js
  src/components/portal/__snapshots__/portal.spec.js.snap
  src/components/portal/portal.style.js
  src/components/select/filterable-select/filterable-select.component.js
  src/components/select/filterable-select/filterable-select.spec.js
  src/components/select/multi-select/multi-select.component.js
  src/components/select/multi-select/multi-select.spec.js
  src/components/select/multi-select/multi-select.style.js
  src/components/select/select-list/select-list.component.js
  src/components/select/select-textbox/select-textbox.component.js
  src/components/select/select-textbox/select-textbox.spec.js
  src/components/select/select.style.js
  src/components/select/simple-select/simple-select.component.js
  src/components/select/simple-select/simple-select.spec.js
  src/components/tooltip/tooltip.spec.js
  src/hooks/__internal__/useScrollBlock/index.d.ts
  src/hooks/__internal__/useScrollBlock/index.js
  src/hooks/__internal__/useScrollBlock/scroll-block-manager.js
  src/hooks/__internal__/useScrollBlock/scroll-block-manager.spec.js
  src/hooks/__internal__/useScrollBlock/useScrollBlock.js
  src/hooks/__internal__/useScrollBlock/useScrollBlock.spec.js
  src/style/themes/base/base-theme.config.js
Labels: Passed Review, DO NOT MERGE, Passed QA, Passed UX QA, Squad Front End

#4804 feat(note): describe note using design tokens, update tests
  src/components/note/note.spec.js
  src/components/note/note.style.js
  src/components/portal/__snapshots__/portal.spec.js.snap
  src/style/themes/base/base-theme.config.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4814 chore(deps): upgrade design tokens package to the version 1.92.0
  package-lock.json
  package.json
  src/components/portal/__snapshots__/portal.spec.js.snap
  src/style/design-tokens/carbon-scoped-tokens-provider/__snapshots__/carbon-scoped-tokens-provider.component.spec.js.snap
  src/style/themes/aegean/__snapshots__/aegean-theme.spec.js.snap
  src/style/themes/mint/__snapshots__/mint-theme.spec.js.snap
  src/style/themes/none/__snapshots__/none.spec.js.snap
Labels: Passed Review, No QA Required, No UX QA Required, Squad DS Alignment

#4758 refactor(select): replace token colorsYin and colorsYang with proper …
  src/components/select/option-group-header/__snapshots__/option-group-header.spec.js.snap
  src/components/select/option-group-header/option-group-header.style.js
  src/components/select/select-list/select-list.style.js
  src/components/select/select.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4798 feat(button-bar): describe Button Bar component using design tokens
  src/components/button-bar/button-bar.style.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad DS Alignment

#4832 fix(decimal): fix precision console error firing when no precision prop specified (FE-4941)
  src/components/decimal/decimal.component.js
  src/components/decimal/decimal.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4785 feat(tabs): describe tabs using design tokens, update tests
  src/__internal__/validations/validation-icon.style.js
  src/components/tabs/__internal__/tab-title/tab-title.component.js
  src/components/tabs/__internal__/tab-title/tab-title.spec.js
  src/components/tabs/__internal__/tab-title/tab-title.style.js
  src/components/tabs/__internal__/tabs-header/tabs-header.spec.js
  src/components/tabs/__internal__/tabs-header/tabs-header.style.js
  src/components/tabs/tabs.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4775 feat(portrait, profile): describe portrait and profile using design tokens, update tests
  src/components/portrait/portrait-gravatar.component.js
  src/components/portrait/portrait-gravatar.d.ts
  src/components/portrait/portrait-initials.component.js
  src/components/portrait/portrait-initials.d.ts
  src/components/portrait/portrait.config.js
  src/components/portrait/portrait.stories.mdx
  src/components/portrait/portrait.style.js
  src/components/profile/profile.config.js
  src/components/profile/profile.stories.mdx
  src/components/profile/profile.style.js
Labels: Passed Review, Pending QA, Passed UX QA, Squad DS Alignment

#4790 fix(icon-button): fix background color when component is disabled (FE-4867)
  src/components/icon-button/icon-button.spec.js
  src/components/icon-button/icon-button.stories.mdx
  src/components/icon-button/icon-button.style.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4823 refactor: Add internal `usePrevious` hook (FE-4914)
  src/components/date-range/date-range.component.js
  src/components/decimal/decimal.component.js
  src/components/drawer/drawer.component.js
  src/hooks/__internal__/usePrevious/index.spec.tsx
  src/hooks/__internal__/usePrevious/index.ts
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#4855 fix(icon-button): fix background color when component is disabled
  src/components/icon-button/icon-button.spec.js
  src/components/icon-button/icon-button.stories.mdx
  src/components/icon-button/icon-button.style.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4846 fix(decimal): fix precision console error firing when no precision pr…
  src/components/decimal/decimal.component.js
  src/components/decimal/decimal.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4845 fix(decimal): fix precision console error firing when no precision pr…
  src/components/decimal/decimal.component.js
  src/components/decimal/decimal.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4805 feat(batch-selection): describe batch-selection component using desig…
  src/components/batch-selection/__snapshots__/batch-selection.spec.js.snap
  src/components/batch-selection/batch-selection.spec.js
  src/components/batch-selection/batch-selection.style.js
  src/components/batch-selection/batch-selection.test.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4765 docs(unit-tests): rfc for converting tests to rtl
  rfcs/text/enzyme-to-rtl.md
Labels: Squad Front End, RFC, Final Comments

#4861 fix(date): ensure day value is validated against format with the month value included FE-4963
  src/components/date/__internal__/utils.js
  src/components/date/__internal__/utils.spec.js
  src/components/date/date.spec.js
  src/components/date/date.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4760 refactor(link): replace token colorsYin and colorsYang with proper c…
  src/components/card/__snapshots__/card.spec.js.snap
  src/components/link/link.spec.js
  src/components/link/link.style.js
  src/components/pod/__snapshots__/pod.spec.js.snap
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4852 fix(button-toggle-group): proper style for info variant
  src/components/button-toggle-group/button-toggle-group.spec.js
  src/components/button-toggle-group/button-toggle-group.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4789 feat(date): describe using design tokens (FE-4735)
  src/components/date/__internal__/date-picker/__snapshots__/date-picker.spec.js.snap
  src/components/date/__internal__/date-picker/day-picker.style.js
  src/components/date/__internal__/navbar/__snapshots__/navbar.spec.js.snap
  src/components/date/__internal__/navbar/button.style.js
  src/components/date/__internal__/navbar/navbar.style.js
  src/components/date/__internal__/weekday/__snapshots__/weekday.spec.js.snap
  src/components/date/__internal__/weekday/weekday.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4806 feat(pager): describe pager using design tokens, update tests - FE-4915
  cypress/locators/pager/index.js
  src/components/pager/pager.spec.js
  src/components/pager/pager.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4774 fix: remove border style from input when disabled
  src/__internal__/input/input-presentation.style.js
  src/__internal__/input/input.component.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad SBC Miro, third-party

#4824 feat(full-screen-heading, heading): describe components using design tokens, update tests - FE-4930
  src/__internal__/full-screen-heading/full-screen-heading.style.js
  src/components/heading/heading.spec.js
  src/components/heading/heading.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4764 feat(menu): describe menu using design tokens, update tests - FE-4724
  cypress/integration/common/menu.feature
  cypress/support/step-definitions/menu-steps.js
  src/components/menu/__internal__/submenu/submenu.spec.js
  src/components/menu/__internal__/submenu/submenu.style.js
  src/components/menu/menu-divider/menu-divider.spec.js
  src/components/menu/menu-divider/menu-divider.style.js
  src/components/menu/menu-full-screen/menu-full-screen.spec.js
  src/components/menu/menu-full-screen/menu-full-screen.style.js
  src/components/menu/menu-item/menu-item.spec.js
  src/components/menu/menu-item/menu-item.style.js
  src/components/menu/menu-segment-title/menu-segment-title.spec.js
  src/components/menu/menu-segment-title/menu-segment-title.style.js
  src/components/menu/menu.config.js
  src/components/menu/menu.spec.js
  src/components/menu/menu.style.js
  src/components/menu/scrollable-block/scrollable-block.spec.js
  src/components/menu/scrollable-block/scrollable-block.style.js
  src/components/menu/submenu-block/submenu-block.spec.js
  src/components/menu/submenu-block/submenu-block.style.js
  src/style/design-tokens/carbon-scoped-tokens-provider/__snapshots__/carbon-scoped-tokens-provider.component.spec.js.snap
  src/style/themes/aegean/__snapshots__/aegean-theme.spec.js.snap
  src/style/themes/aegean/aegean-theme.config.js
  src/style/themes/mint/__snapshots__/mint-theme.spec.js.snap
  src/style/themes/mint/mint-theme.config.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4844 fix(flat-table-checkbox): fix incorrect event propagation
  src/components/flat-table/flat-table-checkbox/flat-table-checkbox.component.js
  src/components/flat-table/flat-table-checkbox/flat-table-checkbox.spec.js
Labels: Pending Review, Passed QA, No UX QA Required, Squad Front End

#4817 feat(text-editor): describe text-editor using design tokens
  src/components/text-editor/__internal__/editor-counter/editor-counter.spec.js
  src/components/text-editor/__internal__/editor-counter/editor-counter.style.js
  src/components/text-editor/__internal__/toolbar/toolbar-button/toolbar-button.spec.js
  src/components/text-editor/__internal__/toolbar/toolbar-button/toolbar-button.style.js
  src/components/text-editor/__internal__/toolbar/toolbar.spec.js
  src/components/text-editor/__internal__/toolbar/toolbar.style.js
  src/components/text-editor/text-editor.spec.js
  src/components/text-editor/text-editor.style.js
Labels: Pending Review, Passed QA, Passed UX QA, Squad DS Alignment

#4776 fix(textbox): prevent setting labelId when no label value passed in FE-4710
  src/components/accordion/accordion.component.js
  src/components/dialog-full-screen/dialog-full-screen.component.js
  src/components/dialog-full-screen/dialog-full-screen.d.ts
  src/components/dialog-full-screen/dialog-full-screen.spec.js
  src/components/dialog-full-screen/dialog-full-screen.stories.mdx
  src/components/drawer/__snapshots__/drawer.spec.js.snap
  src/components/drawer/drawer.component.js
  src/components/drawer/drawer.spec.js
  src/components/drawer/drawer.stories.mdx
  src/components/popover-container/popover-container.component.js
  src/components/popover-container/popover-container.spec.js
  src/components/textbox/__snapshots__/textbox.spec.js.snap
  src/components/textbox/textbox.component.js
  src/components/textbox/textbox.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4810 feat(flat-table): describe table using design tokens, update tests - FE-4743
  src/components/flat-table/__snapshots__/flat-table.spec.js.snap
  src/components/flat-table/flat-table-cell/flat-table-cell.spec.js
  src/components/flat-table/flat-table-cell/flat-table-cell.style.js
  src/components/flat-table/flat-table-checkbox/flat-table-checkbox.style.js
  src/components/flat-table/flat-table-header/flat-table-header.spec.js
  src/components/flat-table/flat-table-header/flat-table-header.style.js
  src/components/flat-table/flat-table-row-header/flat-table-row-header.style.js
  src/components/flat-table/flat-table-row/__snapshots__/flat-table-row.spec.js.snap
  src/components/flat-table/flat-table-row/flat-table-row.spec.js
  src/components/flat-table/flat-table-row/flat-table-row.style.js
  src/components/flat-table/flat-table.spec.js
  src/components/flat-table/flat-table.style.js
  src/components/flat-table/sort/sort.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4865 feat(simple-color-picker, advanced-color-picker): describe components using design tokens, update tests - FE-4734
  src/components/advanced-color-picker/advanced-color-picker-cell.style.js
  src/components/advanced-color-picker/advanced-color-picker.style.js
  src/components/simple-color-picker/__snapshots__/simple-color-picker.spec.js.snap
  src/components/simple-color-picker/simple-color-input/simple-color-input.spec.js
  src/components/simple-color-picker/simple-color-input/simple-color-input.style.js
  src/components/simple-color-picker/simple-color-picker.spec.js
  src/components/simple-color-picker/simple-color-picker.style.js
  src/components/simple-color-picker/simple-color/simple-color.style.js
  src/components/simple-color-picker/tick-icon/tick-icon.spec.js
  src/components/simple-color-picker/tick-icon/tick-icon.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4882 chore(deps): update react packages
  package-lock.json
  package.json
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#4801 feat(pod): describe pod using design tokens, update tests
  src/components/pod/__snapshots__/pod.spec.js.snap
  src/components/pod/pod.spec.js
  src/components/pod/pod.style.js
  src/components/portal/__snapshots__/portal.spec.js.snap
  src/components/show-edit-pod/delete-button.style.js
  src/components/show-edit-pod/show-edit-pod.component.js
  src/components/show-edit-pod/show-edit-pod.spec.js
  src/components/show-edit-pod/show-edit-pod.style.js
  src/style/themes/base/base-theme.config.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4763 feat(drawer): describe using design tokens (FE-4738)
  src/__internal__/sticky-footer/sticky-footer.spec.js
  src/__internal__/sticky-footer/sticky-footer.style.js
  src/components/drawer/__snapshots__/drawer.spec.js.snap
  src/components/drawer/drawer.spec.js
  src/components/drawer/drawer.stories.mdx
  src/components/drawer/drawer.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4809 feat(form): describe form using design tokens, update tests
  src/components/form/__internal__/form-summary.style.js
  src/components/form/form.spec.js
  src/components/form/form.style.js
  src/components/portal/__snapshots__/portal.spec.js.snap
  src/style/themes/base/base-theme.config.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4888 ci(pr-template): remove 123 from template comment
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#4879 refactor(anchor-navigation): change background color token category f…
  src/components/anchor-navigation/anchor-navigation-item/anchor-navigation-item.style.js
  src/components/anchor-navigation/anchor-navigation.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad DS Alignment

#4871 refactor(numeral-date): remove unnecessary styles containing theme - FE-4939
  src/components/numeral-date/numeral-date.style.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad DS Alignment

#4835 feat(definition-list,select): describe DefinitionList & rest of selec…
  src/components/definition-list/definition-list.spec.js
  src/components/definition-list/definition-list.style.js
  src/components/portal/__snapshots__/portal.spec.js.snap
  src/components/select/__internal__/select-text/select-text.spec.js
  src/components/select/__internal__/select-text/select-text.style.js
  src/components/select/select-list/select-list-container.style.js
  src/style/themes/base/base-theme.config.js
  src/style/themes/base/index.d.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4874 fix(tab-title): remove additional error border and prevent content jumping when has siblings FE-4943
  src/components/tabs/__internal__/tab-title/tab-title.component.js
  src/components/tabs/__internal__/tab-title/tab-title.spec.js
  src/components/tabs/__internal__/tab-title/tab-title.style.js
  src/components/tabs/tabs.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4788 feat(step-sequence-item): support hiding indicator
  cypress/fixtures/commonComponents/stepSequence.json
  cypress/integration/common/stepSequenceItem.feature
  cypress/support/step-definitions/step-sequence-steps.js
  src/components/step-sequence/step-sequence-item/step-sequence-item.component.js
  src/components/step-sequence/step-sequence-item/step-sequence-item.d.ts
  src/components/step-sequence/step-sequence-item/step-sequence-item.spec.js
  src/components/step-sequence/step-sequence-test.stories.mdx
  src/components/step-sequence/step-sequence.stories.mdx
Labels: Passed Review, Passed QA, Passed UX QA, third-party

#4870 feat(navigation-bar): add position, offset and orientation props to enable fixed or sticky positions FE-4711
  src/components/navigation-bar/navigation-bar.component.tsx
  src/components/navigation-bar/navigation-bar.spec.tsx
  src/components/navigation-bar/navigation-bar.stories.mdx
  src/components/navigation-bar/navigation-bar.style.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4837 feat(icon-button): describe icon-button component using design tokens…
  src/components/batch-selection/__snapshots__/batch-selection.spec.js.snap
  src/components/confirm/confirm.spec.js
  src/components/icon-button/icon-button.spec.js
  src/components/icon-button/icon-button.style.js
  src/components/pod/__snapshots__/pod.spec.js.snap
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4899 fix(card): fix incorrect headers - FE-4964
  src/components/card/card.stories.mdx
Labels: Passed Review, Passed QA, Squad Front End, Pending a11y Review
