Repository Sage/carbon, pull requests merged in 2022-03, with the labels that each got.

#4834 feat(fieldset, field-help): describe fieldset and field-help using design tokens, update tests
  src/__internal__/field-help/field-help.spec.js
  src/__internal__/field-help/field-help.style.js
  src/__internal__/fieldset/fieldset.spec.js
  src/__internal__/fieldset/fieldset.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4881 feat(tile-select, hr): describe components with design tokens
  src/components/hr/hr.style.ts
  src/components/tile-select/__internal__/accordion/accordion.spec.js
  src/components/tile-select/__internal__/accordion/accordion.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4812 fix: incorrect ref behaviour in Button and IconButton - FE-4924
  src/components/button/button.component.js
  src/components/button/button.spec.js
  src/components/icon-button/icon-button.component.js
  src/components/icon-button/icon-button.spec.js
  src/components/select/multi-select/multi-select.component.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4918 refactor(sticky-footer, slide, select-list): replace colorsComponentsNavigation tokens - FE-5002
  src/__internal__/sticky-footer/sticky-footer.spec.js
  src/__internal__/sticky-footer/sticky-footer.style.js
  src/components/carousel/slide/slide.style.js
  src/components/select/select-list/select-list.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4913 chore(deps): upgrade design tokens package to the version 1.93.0
  package-lock.json
  package.json
  src/components/portal/__snapshots__/portal.spec.js.snap
  src/style/design-tokens/carbon-scoped-tokens-provider/__snapshots__/carbon-scoped-tokens-provider.component.spec.js.snap
  src/style/themes/aegean/__snapshots__/aegean-theme.spec.js.snap
  src/style/themes/mint/__snapshots__/mint-theme.spec.js.snap
  src/style/themes/none/__snapshots__/none.spec.js.snap
Labels: Pending Review, No QA Required, No UX QA Required, Squad DS Alignment

#4850 feat(link-preview, preview): describe link-preview & preview using de…
  src/components/link-preview/__internal__/placeholder.component.js
  src/components/link-preview/link-preview.spec.js
  src/components/link-preview/link-preview.style.js
  src/components/preview/__snapshots__/preview.spec.js.snap
  src/components/preview/preview.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4884 feat(help): describe component using design tokens
  src/components/help/help.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4897 feat(grid): add styled-system props (FE-4912)
  src/components/grid/__snapshots__/grid.spec.js.snap
  src/components/grid/grid-container/grid-container.component.js
  src/components/grid/grid-container/grid-container.d.ts
  src/components/grid/grid-container/grid-container.style.js
  src/components/grid/grid-item/grid-item.component.js
  src/components/grid/grid-item/grid-item.d.ts
  src/components/grid/grid-item/grid-item.style.js
  src/components/grid/grid.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4630 fix(help): icon tooltip voice reader issue (FE-979)
  cypress/support/step-definitions/tooltip-steps.js
  src/__internal__/tooltip-provider/index.js
  src/components/help/help.component.js
  src/components/help/help.spec.js
  src/components/help/help.stories.mdx
  src/components/icon/icon.component.js
  src/components/icon/icon.spec.js
  src/components/numeral-date/numeral-date.stories.mdx
  src/components/portal/__snapshots__/portal.spec.js.snap
  src/components/radio-button/radio-button.stories.mdx
  src/components/switch/switch-test.stories.mdx
  src/components/switch/switch.stories.mdx
  src/components/tooltip/tooltip.component.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4923 refactor(color-picker): update design tokens in the color picker component
  src/components/advanced-color-picker/advanced-color-picker.style.js
  src/components/simple-color-picker/__snapshots__/simple-color-picker.spec.js.snap
  src/components/simple-color-picker/simple-color-input/simple-color-input.spec.js
  src/components/simple-color-picker/simple-color-input/simple-color-input.style.js
  src/components/simple-color-picker/tick-icon/tick-icon.spec.js
  src/components/simple-color-picker/tick-icon/tick-icon.style.js
Labels: Passed Review, Pending QA, Passed UX QA, Squad DS Alignment

#4867 feat(setting-row): describe setting-row component using design tokens, update tests
  src/components/settings-row/settings-row.spec.js
  src/components/settings-row/settings-row.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4866 feat(detail): describe detail component using design tokens
  src/components/detail/detail.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4898 feat(date-range, date-input): describe using design tokens (FE-4736)
  src/components/date-range/date-range.spec.js
  src/components/date-range/date-range.style.js
  src/components/date/__internal__/date-picker/__snapshots__/date-picker.spec.js.snap
  src/components/date/__internal__/date-picker/day-picker.style.js
  src/components/date/__internal__/weekday/weekday.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4859 feat(dismissible-box, box, content): describe components using design tokens, update tests
  src/components/box/box.component.js
  src/components/box/box.config.js
  src/components/box/box.spec.js
  src/components/content/content.spec.js
  src/components/content/content.style.js
  src/components/dismissible-box/dismissible-box.component.js
  src/components/dismissible-box/dismissible-box.spec.js
  src/components/dismissible-box/dismissible-box.style.js
  src/components/portal/__snapshots__/portal.spec.js.snap
  src/components/show-edit-pod/show-edit-pod.spec.js
  src/components/show-edit-pod/show-edit-pod.style.js
  src/components/tile/__snapshots__/tile.spec.js.snap
  src/style/themes/base/base-theme.config.js
  src/style/themes/base/index.d.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4933 feat(sidebar-header): describe sidebar-header using design tokens, update tests - FE-5021
  src/components/sidebar/__internal__/sidebar-header/sidebar-header.spec.js
  src/components/sidebar/__internal__/sidebar-header/sidebar-header.style.js
Labels: Passed Review, Pending QA, Passed UX QA, Squad DS Alignment

#4917 test(card): add refactored tests for card component FE-4524
  cypress/integration/common/card.feature
  cypress/locators/card/index.js
  cypress/support/step-definitions/card-steps.js
  src/components/card/card.test.js
Labels: Passed Review, Passed QA, Cypress, Squad Front End

#4795 fix(icon): update icon colors token to match design decisions - FE-4875
  package-lock.json
  src/components/batch-selection/__snapshots__/batch-selection.spec.js.snap
  src/components/icon/icon.spec.js
  src/components/icon/icon.style.js
  src/components/pod/__snapshots__/pod.spec.js.snap
  src/components/portal/__snapshots__/portal.spec.js.snap
  src/components/search/search.spec.js
  src/components/select/option-group-header/__snapshots__/option-group-header.spec.js.snap
Labels: Passed Review, Pending QA, Passed UX QA, Squad DS Alignment

#4895 feat(scrollable-list-item, select-list-container): describe components using tokens
  src/components/scrollable-list/scrollable-list-item.component.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4872 feat(input-presentation, input-icon-toggle, checkable-input, character-count): describe components using design tokens, update tests
  cypress/support/step-definitions/text-area-steps.js
  src/__internal__/character-count/character-count.spec.js
  src/__internal__/character-count/character-count.style.js
  src/__internal__/checkable-input/checkable-input.spec.js
  src/__internal__/checkable-input/checkable-input.style.js
  src/__internal__/input-icon-toggle/input-icon-toggle.style.js
  src/__internal__/input/__snapshots__/input-presentation.spec.js.snap
  src/__internal__/input/input-presentation.style.js
  src/components/radio-button/__snapshots__/radio-button-group.spec.js.snap
  src/components/radio-button/__snapshots__/radio-button-mapper.spec.js.snap
  src/components/radio-button/__snapshots__/radio-button.spec.js.snap
  src/components/textarea/textarea.spec.js
  src/components/textbox/textbox.spec.js
  src/hooks/__internal__/useCharacterCount/index.spec.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad DS Alignment

#4915 test(multi-action-button): refactor multiactionbutton component
  cypress/fixtures/commonComponents/multiActionButton.json
  cypress/integration/common/multiActionButton.feature
  cypress/support/step-definitions/multi-action-button-steps.js
  src/components/multi-action-button/multi-action-button.test.js
Labels: Pending Review, Pending QA, Cypress, Squad Front End

#4910 feat: extend toColor function by design tokens, update storybook and tests
  .storybook/utils/styled-system-props.js
  docs/colors.stories.mdx
  src/components/button/__snapshots__/button.spec.js.snap
  src/components/button/button.component.js
  src/components/card/__snapshots__/card.spec.js.snap
  src/components/dismissible-box/dismissible-box.component.js
  src/components/flat-table/flat-table-cell/flat-table-cell.component.js
  src/components/flat-table/flat-table-row-header/flat-table-row-header.component.js
  src/components/flat-table/flat-table-row/flat-table-row.component.js
  src/components/flat-table/flat-table.stories.mdx
  src/components/icon/icon.component.js
  src/components/icon/icon.spec.js
  src/components/icon/icon.stories.mdx
  src/components/icon/icon.style.js
  src/components/link/link.component.js
  src/components/multi-action-button/__snapshots__/multi-action-button.spec.js.snap
  src/components/pill/pill.component.js
  src/components/pill/pill.stories.mdx
  src/components/pill/pill.style.js
  src/components/portrait/portrait.component.js
  src/components/select/list-action-button/__snapshots__/list-action-button.spec.js.snap
  src/components/tooltip/tooltip.component.js
  src/components/tooltip/tooltip.stories.mdx
  src/style/utils/color.js
  src/style/utils/color.spec.js
  src/style/utils/get-color-value.spec.ts
  src/style/utils/get-color-value.ts
Labels: Passed Review, Passed QA, Squad DS Alignment

#4886 feat(flat-table): add ability to use data-xxx props on flat table com…
  src/components/flat-table/flat-table-body-draggable/flat-table-body-draggable.component.js
  src/components/flat-table/flat-table-body-draggable/flat-table-body-draggable.spec.js
  src/components/flat-table/flat-table-body/flat-table-body.component.js
  src/components/flat-table/flat-table-body/flat-table-body.spec.js
  src/components/flat-table/flat-table-cell/flat-table-cell.spec.js
  src/components/flat-table/flat-table-checkbox/flat-table-checkbox.component.js
  src/components/flat-table/flat-table-checkbox/flat-table-checkbox.spec.js
  src/components/flat-table/flat-table-head/flat-table-head.component.js
  src/components/flat-table/flat-table-head/flat-table-head.spec.js
  src/components/flat-table/flat-table-header/flat-table-header.spec.js
  src/components/flat-table/flat-table-row-header/flat-table-row-header.spec.js
  src/components/flat-table/flat-table-row/flat-table-row.component.js
  src/components/flat-table/flat-table-row/flat-table-row.spec.js
  src/components/flat-table/flat-table.spec.js
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#4889 fix(filterable-select): prevent passing a non-existent label id to children (FE-4917)
  src/components/select/filterable-select/filterable-select.component.js
  src/components/select/filterable-select/filterable-select.spec.js
  src/components/select/filterable-select/filterable-select.stories.mdx
  src/components/select/select-list/select-list.spec.js
  src/components/select/select-textbox/select-textbox.component.js
  src/components/select/select-textbox/select-textbox.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4930 fix(storybook): fix theme selector functionality - FE-5004
  .storybook/theme-selector/register.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4908 feat(base-theme): swap space values for values described by tokens - FE-4973
  src/__internal__/fieldset/fieldset.spec.js
  src/__internal__/form-field/form-field.spec.js
  src/__spec_helper__/test-utils.js
  src/components/accordion/accordion.spec.js
  src/components/button/__snapshots__/button.spec.js.snap
  src/components/button/button.spec.js
  src/components/card/card-row/card-row.spec.js
  src/components/definition-list/definition-list.spec.js
  src/components/dialog/dialog.spec.js
  src/components/dialog/dialog.style.js
  src/components/flat-table/__snapshots__/flat-table.spec.js.snap
  src/components/hr/hr.spec.tsx
  src/components/multi-action-button/__snapshots__/multi-action-button.spec.js.snap
  src/components/portal/__snapshots__/portal.spec.js.snap
  src/components/radio-button/__snapshots__/radio-button-group.spec.js.snap
  src/components/radio-button/__snapshots__/radio-button.spec.js.snap
  src/components/select/list-action-button/__snapshots__/list-action-button.spec.js.snap
  src/components/simple-color-picker/__snapshots__/simple-color-picker.spec.js.snap
  src/components/split-button/__snapshots__/split-button.spec.js.snap
  src/components/tile/__snapshots__/tile.spec.js.snap
  src/style/design-tokens/carbon-scoped-tokens-provider/__snapshots__/carbon-scoped-tokens-provider.component.spec.js.snap
  src/style/themes/aegean/__snapshots__/aegean-theme.spec.js.snap
  src/style/themes/base/base-theme.config.js
  src/style/themes/base/index.d.ts
  src/style/themes/mint/__snapshots__/mint-theme.spec.js.snap
  src/style/themes/none/__snapshots__/none.spec.js.snap
Labels: Pending Review, Passed QA, No UX QA Required, Squad DS Alignment

#4911 chore: rename sage theme
  docs/getting-started.stories.mdx
  src/components/button-toggle/__snapshots__/button-toggle.spec.js.snap
  src/style/themes/sage/index.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad DS Alignment

#4940 refactor(base-theme): remove unused properties - FE-4974
  rfcs/text/design-tokens.md
  src/components/portal/__snapshots__/portal.spec.js.snap
  src/style/themes/aegean/aegean-theme.config.js
  src/style/themes/base/base-theme.config.js
  src/style/themes/base/index.d.ts
  src/style/themes/mint/mint-theme.config.js
Labels: Passed Review, Pending QA, No UX QA Required, Squad DS Alignment

#4941 fix(multi-select): prevent component calling onChange on first render when uncontrolled FE-4884
  src/components/select/multi-select/multi-select.component.js
  src/components/select/multi-select/multi-select.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4906 fix(flat-table-row): update styles to ensure that icon color can be customised via prop FE-4997
  src/components/flat-table/__snapshots__/flat-table.spec.js.snap
  src/components/flat-table/flat-table-row/__snapshots__/flat-table-row.spec.js.snap
  src/components/flat-table/flat-table-row/flat-table-row.style.js
  src/components/flat-table/flat-table.stories.mdx
Labels: Passed Review, Pending QA, No UX QA Required, Squad Front End

#4890 test(badge): cypress refactor
  cypress/fixtures/commonComponents/badge.json
  cypress/integration/common/badge.feature
  cypress/locators/badge/index.js
  cypress/locators/badge/locators.js
  cypress/support/step-definitions/badge-steps.js
  src/components/badge/badge.test.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4958 chore(code-owners): update file to assign ownership of test.js files to carbon qa
  .github/CODEOWNERS
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#4925 docs(select): stop stories from crashing when opening select
  .storybook/preview.js
  cypress/integration/common/simpleSelect.feature
  src/components/select/simple-select/simple-select-test.stories.js
  src/components/select/simple-select/simple-select.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4777 fix(tooltip): fix tooltip repositioning - FE-4749
  src/components/tooltip/__snapshots__/tooltip.spec.js.snap
  src/components/tooltip/tooltip.component.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4914 fix(textbox): prevent axe issue when the validation string is empty (FE-4982)
  src/hooks/__internal__/useInputAccessibility/useInputAccessibility.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4868 feat(flat-table): add width prop
  cypress/locators/flat-table/index.js
  cypress/locators/flat-table/locators.js
  cypress/support/step-definitions/flat-table-steps.js
  src/components/flat-table/__snapshots__/flat-table.spec.js.snap
  src/components/flat-table/flat-table.component.js
  src/components/flat-table/flat-table.d.ts
  src/components/flat-table/flat-table.spec.js
  src/components/flat-table/flat-table.style.js
Labels: Passed Review, Pending QA, Passed UX QA, Squad Front End

#4873 fix(pager): fix incorrect styling when open - FE-4964
  package-lock.json
  package.json
  src/components/navigation-bar/navigation-bar.spec.tsx
  src/components/navigation-bar/navigation-bar.style.ts
  src/components/pager/pager.style.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4770 fix: MultiActionButton and SplitButton tabbing issues - FE-4322
  cypress/integration/common/splitButton.feature
  cypress/locators/split-button/index.js
  cypress/locators/split-button/locators.js
  cypress/support/step-definitions/split-button-steps.js
  src/components/multi-action-button/multi-action-button.component.js
  src/components/multi-action-button/multi-action-button.test.js
  src/components/split-button/split-button.component.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4944 test(test-utils): refactor expectError to catch console warn and rename to expectConsoleOutput FE-5023
  src/__spec_helper__/test-utils.js
  src/components/button-bar/button-bar.spec.js
  src/components/button/button.component.js
  src/components/button/button.spec.js
  src/components/multi-action-button/multi-action-button.component.js
  src/components/multi-action-button/multi-action-button.spec.js
  src/components/pill/pill.spec.js
  src/components/simple-color-picker/color-sample-box/color-sample-box.spec.js
  src/components/simple-color-picker/simple-color-picker.spec.js
  src/components/split-button/split-button.component.js
  src/components/split-button/split-button.spec.js
  src/components/text-editor/text-editor.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4781 fix(action-popover-item): prevent popover staying open when using keyboard nav (FE-4703)
  src/components/action-popover/action-popover-item/action-popover-item.component.js
  src/components/action-popover/action-popover.spec.js
  src/components/action-popover/action-popover.stories.mdx
  src/components/action-popover/action-popover.style.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4965 docs: update roadmap
  docs/development-roadmap.stories.mdx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#4967 test: update test dependencies
  package-lock.json
  package.json
Labels: Pending QA, Cypress, Squad Front End

#4903 fix(select): remove incorrect props (FE-4983)
  src/components/select/filterable-select/filterable-select.component.js
  src/components/select/multi-select/multi-select.component.js
  src/components/select/select-textbox/select-textbox.component.js
  src/components/select/simple-select/simple-select.component.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4902 feat(modal-manager): enable global management of modal lists
  src/components/modal/__internal__/modal-manager.js
  src/components/modal/__internal__/modal-manager.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4912 feat(hidden-checkable-input): surface role prop FE-4348
  src/__internal__/checkable-input/__snapshots__/hidden-checkable-input.spec.js.snap
  src/__internal__/checkable-input/hidden-checkable-input.component.js
  src/__internal__/checkable-input/hidden-checkable-input.d.ts
  src/__internal__/checkable-input/hidden-checkable-input.spec.js
  src/components/switch/switch.component.js
  src/components/switch/switch.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4847 feat(text-inputs): add new validations option to text input components FE-4285
  src/__internal__/form-field/__snapshots__/form-field.spec.js.snap
  src/__internal__/form-field/form-field.component.js
  src/__internal__/form-field/form-field.spec.js
  src/__internal__/input/input-presentation.component.js
  src/__internal__/input/input-presentation.spec.js
  src/__internal__/input/input-presentation.style.js
  src/__internal__/validation-message/index.ts
  src/__internal__/validation-message/validation-message.component.tsx
  src/__internal__/validation-message/validation-message.spec.tsx
  src/__internal__/validation-message/validation-message.style.ts
  src/components/carbon-provider/carbon-provider.component.js
  src/components/carbon-provider/carbon-provider.d.ts
  src/components/carbon-provider/carbon-provider.spec.js
  src/components/date-range/date-range.spec.js
  src/components/date-range/date-range.stories.mdx
  src/components/date-range/date-range.style.js
  src/components/date/date-test.stories.mdx
  src/components/date/date.stories.mdx
  src/components/decimal/decimal-test.stories.mdx
  src/components/decimal/decimal.stories.mdx
  src/components/fieldset/__snapshots__/fieldset.spec.js.snap
  src/components/fieldset/fieldset.component.js
  src/components/grouped-character/grouped-character-test.stories.mdx
  src/components/grouped-character/grouped-character.stories.mdx
  src/components/number/number-test.stories.mdx
  src/components/number/number.stories.mdx
  src/components/numeral-date/numeral-date-context.js
  src/components/numeral-date/numeral-date.component.js
  src/components/numeral-date/numeral-date.spec.js
  src/components/numeral-date/numeral-date.stories.mdx
  src/components/portal/__snapshots__/portal.spec.js.snap
  src/components/select/filterable-select/filterable-select.stories.mdx
  src/components/select/multi-select/multi-select.stories.mdx
  src/components/select/simple-select/simple-select.stories.mdx
  src/components/textarea/textarea.component.js
  src/components/textarea/textarea.spec.js
  src/components/textarea/textarea.stories.mdx
  src/components/textbox/__snapshots__/textbox.spec.js.snap
  src/components/textbox/textbox-test.stories.mdx
  src/components/textbox/textbox.component.js
  src/components/textbox/textbox.d.ts
  src/components/textbox/textbox.spec.js
  src/components/textbox/textbox.stories.mdx
  src/components/textbox/textbox.style.js
  src/style/themes/base/base-theme.config.js
  src/style/themes/base/index.d.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4916 fix(text-editor): fix validation icon accessibility issue - FE-4978
  src/__internal__/validations/validation-icon.component.js
  src/components/icon/icon.component.js
  src/components/icon/icon.d.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4970 test(loader): refactor for component
  cypress/fixtures/commonComponents/loader.json
  cypress/integration/common/loader.feature
  cypress/support/step-definitions/loader-steps.js
  src/components/loader/loader.test.js
Labels: Passed QA, Cypress, Squad Front End

#4946 fix(select): ensure textbox placeholder can be set when passed as prop
  src/components/select/__internal__/select-text/select-text.component.js
  src/components/select/__internal__/select-text/select-text.spec.js
  src/components/select/filterable-select/filterable-select.spec.js
  src/components/select/multi-select/multi-select.spec.js
  src/components/select/select-textbox/select-textbox.component.js
  src/components/select/select-textbox/select-textbox.spec.js
  src/components/select/simple-select/simple-select.spec.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#4962 test(split-button): refactor split-button component
  cypress/fixtures/commonComponents/splitButton.json
  cypress/integration/common/splitButton.feature
  cypress/locators/split-button/index.js
  cypress/support/step-definitions/split-button-steps.js
  src/components/split-button/split-button.test.js
Labels: Pending Review, Pending QA, Cypress, Squad Front End

#4950 fix(tabs): move onclick handler to button element
  src/components/tabs/__internal__/tab-title/tab-title.component.js
  src/components/tabs/__internal__/tab-title/tab-title.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4976 fix(menu-item): prevent setting maxWidth when items are rendered in MenuFullscreen FE-5032
  src/components/menu/menu-full-screen/menu-full-screen.spec.js
  src/components/menu/menu-item/menu-item.component.js
  src/components/menu/menu-item/menu-item.spec.js
  src/components/menu/menu.stories.mdx
Labels: Pending Review, Passed QA, No UX QA Required, Squad Front End

#4980 docs(date): update incorrect information about locale override demo
  src/components/date/date.stories.mdx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#4989 refactor(alert): convert files to typescript
  src/components/alert/alert-test.stories.mdx
  src/components/alert/alert.component.js
  src/components/alert/alert.component.tsx
  src/components/alert/alert.d.ts
  src/components/alert/alert.spec.tsx
  src/components/alert/index.d.ts
  src/components/alert/index.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4927 fix(multi-action-button): fix incorrect hover color - FE-5003
  src/style/design-tokens/carbon-scoped-tokens-provider/__snapshots__/carbon-scoped-tokens-provider.component.spec.js.snap
  src/style/themes/aegean/__snapshots__/aegean-theme.spec.js.snap
  src/style/themes/aegean/aegean-theme.config.js
  src/style/themes/mint/__snapshots__/mint-theme.spec.js.snap
  src/style/themes/mint/mint-theme.config.js
Labels: Passed Review, Passed QA, Pending UX QA, Squad Front End

#4978 fix(scroll-block): fix page scrolling - FE-5041
  src/components/dialog-full-screen/dialog-full-screen.spec.js
  src/hooks/__internal__/useScrollBlock/scroll-block-manager.js
  src/hooks/__internal__/useScrollBlock/scroll-block-manager.spec.js
  src/hooks/__internal__/useScrollBlock/useScrollBlock.js
  src/hooks/__internal__/useScrollBlock/useScrollBlock.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4988 docs(duelling-picklist): update demos to ensure they have valid HTML markup FE-5038
  src/components/duelling-picklist/duelling-picklist.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4993 test(loader): test fix
  src/components/loader/loader.test.js
Labels: Passed QA, Cypress, Squad Front End

#4987 fix(textarea): allow row and expandable props to be used together
  cypress/fixtures/commonComponents/textarea.json
  cypress/integration/common/textarea.feature
  cypress/support/step-definitions/text-area-steps.js
  src/components/textarea/textarea.component.js
  src/components/textarea/textarea.style.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4924 docs(flat-table): add info about children iteration FE-4465
  src/components/flat-table/flat-table.stories.mdx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#4955 fix: remove unused variants from Toast and Message components - FE-4234
  src/components/message/message-content/__snapshots__/message-content.spec.js.snap
  src/components/message/message-content/message-content.component.js
  src/components/message/message.component.js
  src/components/message/message.d.ts
  src/components/message/type-icon/type-icon.component.js
  src/components/message/type-icon/type-icon.style.js
  src/components/toast/toast-test.stories.mdx
  src/components/toast/toast.component.js
  src/components/toast/toast.config.js
  src/components/toast/toast.d.ts
  src/components/toast/toast.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4960 refactor(row, column): remove deprecated components
  cypress/integration/common/row.feature
  cypress/locators/row/index.js
  cypress/locators/row/locators.js
  cypress/support/step-definitions/row-steps.js
  src/components/dialog/dialog.spec.js
  src/components/row/__snapshots__/row.spec.js.snap
  src/components/row/column/column.component.js
  src/components/row/column/column.d.ts
  src/components/row/column/column.spec.js
  src/components/row/column/column.style.js
  src/components/row/index.d.ts
  src/components/row/index.js
  src/components/row/row-test.stories.mdx
  src/components/row/row.component.js
  src/components/row/row.config.js
  src/components/row/row.d.ts
  src/components/row/row.spec.js
  src/components/row/row.stories.mdx
  src/components/row/row.style.js
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#5002 chore(jest): ignore build folders in test coverage
  jest.conf.json
Labels: Passed Review, No QA Required, No UX QA Required

#4982 fix(vertical-divider): render component as li element if it is a child of Menu FE-5039
  src/components/menu/menu-full-screen/menu-full-screen.component.js
  src/components/menu/menu.component.js
  src/components/menu/menu.context.js
  src/components/menu/menu.d.ts
  src/components/vertical-divider/index.d.ts
  src/components/vertical-divider/index.ts
  src/components/vertical-divider/vertical-divider.component.js
  src/components/vertical-divider/vertical-divider.component.tsx
  src/components/vertical-divider/vertical-divider.spec.tsx
  src/components/vertical-divider/vertical-divider.style.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4994 test(content): add refactored tests for content component FE-4528
  cypress/fixtures/commonComponents/content.json
  cypress/integration/common/content.feature
  cypress/support/step-definitions/content-steps.js
  src/components/content/content.test.js
Labels: Pending Review, Pending QA, Cypress, Squad Front End

#4956 fix(select): fix openOnFocus behaviour when clicked
  src/__internal__/popover/popover.component.js
  src/__internal__/popover/popover.spec.js
  src/components/modal/modal.component.js
  src/components/select/__internal__/select-text/select-text.component.js
  src/components/select/__internal__/select-text/select-text.spec.js
  src/components/select/select-textbox/select-textbox.component.js
  src/components/select/simple-select/simple-select.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4977 feat(tile): surface variant prop and add deprecation warning for as prop FE-5029
  src/components/button/button.component.js
  src/components/button/button.spec.js
  src/components/multi-action-button/multi-action-button.component.js
  src/components/multi-action-button/multi-action-button.spec.js
  src/components/split-button/split-button.component.js
  src/components/split-button/split-button.spec.js
  src/components/tile/tile.component.js
  src/components/tile/tile.d.ts
  src/components/tile/tile.spec.js
  src/components/tile/tile.stories.mdx
  src/components/toast/toast.component.js
  src/components/toast/toast.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End
