Repository Sage/carbon, pull requests merged in 2022-07, with the labels that each got.

#5190 feat: upgrade to react 17
  package-lock.json
  package.json
  src/__internal__/focus-trap/focus-trap.spec.js
  src/__internal__/form-field/form-field.spec.js
  src/__internal__/label/label.spec.tsx
  src/__internal__/validations/validation-icon.spec.tsx
  src/__spec_helper__/index.js
  src/components/button-toggle-group/button-toggle-group.spec.js
  src/components/decimal/decimal.spec.js
  src/components/draggable/draggable.spec.js
  src/components/duelling-picklist/duelling-picklist.spec.js
  src/components/grid/grid.spec.js
  src/components/grouped-character/grouped-character.spec.js
  src/components/help/help.spec.js
  src/components/menu/menu-item/menu-item.spec.js
  src/components/modal/modal.spec.js
  src/components/numeral-date/numeral-date.spec.js
  src/components/portrait/portrait.spec.js
  src/components/radio-button/radio-button.spec.js
  src/components/search/search.spec.js
  src/components/simple-color-picker/simple-color-picker.spec.js
  src/components/tabs/tabs.spec.js
  src/components/tile-select/tile-select.spec.js
  src/components/toast/toast.spec.js
  src/hooks/__internal__/useModalManager/useModalManager.ts
Labels: Passed Review, Passed QA, No UX QA Required, third-party

#5258 fix(flat-table): fix border bottom colour in light theme - FE-5198
  src/components/flat-table/flat-table.spec.js
  src/components/flat-table/flat-table.style.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5243 fix(form): fix tabs focus outline not rendering correctly - FE-5184
  src/components/form/form.spec.js
  src/components/form/form.stories.mdx
  src/components/form/form.style.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5244 refactor(focus-trap): prevent act warnings in tests when inputs are focused FE-5218
  src/__internal__/focus-trap/focus-trap.component.js
  src/__internal__/focus-trap/focus-trap.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5237 feat(inline-inputs): add adaptiveLabelBreakpoint prop to component - FE-5187
  src/components/inline-inputs/inline-inputs.component.tsx
  src/components/inline-inputs/inline-inputs.spec.tsx
  src/components/inline-inputs/inline-inputs.stories.mdx
  src/components/inline-inputs/inline-inputs.style.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5279 chore(code-owners): ensure ts spec files are owned by carbon-qa
  .github/CODEOWNERS
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#5249 fix(use-click-away-listener): rewrite ClickAwayWrapper component as a custom hook
  src/__internal__/click-away-wrapper/click-away-wrapper.component.tsx
  src/__internal__/click-away-wrapper/click-away-wrapper.spec.tsx
  src/__internal__/click-away-wrapper/index.ts
  src/components/date/date.component.js
  src/components/date/date.spec.js
  src/components/menu/__internal__/submenu/submenu.component.js
  src/components/menu/__internal__/submenu/submenu.spec.js
  src/components/multi-action-button/multi-action-button.component.tsx
  src/components/popover-container/popover-container.component.tsx
  src/components/popover-container/popover-container.spec.tsx
  src/components/split-button/split-button.component.js
  src/hooks/__internal__/useClickAwayListener/index.ts
  src/hooks/__internal__/useClickAwayListener/useClickAwayListener.spec.tsx
  src/hooks/__internal__/useClickAwayListener/useClickAwayListener.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5281 docs(badge): ensure demos do not render partially offscreen FE-5231
  src/components/badge/badge-test.stories.mdx
  src/components/badge/badge-test.stories.tsx
  src/components/badge/badge.stories.mdx
  src/components/button/button.stories.mdx
  src/components/flat-table/flat-table-expandable.stories.mdx
Labels: Pending Review, Passed QA, No UX QA Required, Squad Front End

#5267 refactor(checkbox-group): remove unused groupName prop (FE-5223)
  src/components/checkbox/checkbox-group.component.js
  src/components/checkbox/checkbox-group.d.ts
  src/components/checkbox/checkbox-group.spec.js
  src/components/checkbox/checkbox-validations.stories.mdx
  src/components/checkbox/checkbox.component.js
  src/components/checkbox/checkbox.stories.mdx
  src/components/checkbox/checkbox.test.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4996 fix(flat-table/sort): fix color of sort arrows
  src/components/flat-table/flat-table.stories.mdx
  src/components/flat-table/sort/sort.component.js
  src/components/flat-table/sort/sort.style.js
Labels: Passed Review, Pending QA, No UX QA Required, Squad Front End

#5262 fix(popover-container): position automatically depending on available space - FE-5175
  src/components/popover-container/popover-container.component.tsx
  src/components/popover-container/popover-container.spec.tsx
  src/components/popover-container/popover-container.style.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5297 ci: add workflow to lint commit messages of pull requests
  .github/workflows/semantic-commit-lint.yml
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#5299 chore: refactor asset loading for storybook
  .storybook/main.js
  package.json
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#5275 feat(pill): add text wrapping and max width support to component
  src/components/pill/index.d.ts
  src/components/pill/index.js
  src/components/pill/index.ts
  src/components/pill/pill-test.stories.tsx
  src/components/pill/pill.component.js
  src/components/pill/pill.component.tsx
  src/components/pill/pill.d.ts
  src/components/pill/pill.spec.tsx
  src/components/pill/pill.stories.mdx
  src/components/pill/pill.style.config.ts
  src/components/pill/pill.style.ts
  src/components/select/multi-select/multi-select.component.js
  src/components/select/multi-select/multi-select.d.ts
  src/components/select/multi-select/multi-select.spec.js
  src/components/select/multi-select/multi-select.stories.mdx
  src/components/select/multi-select/multi-select.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5285 test(button): modify tests to check only one icon type (FE-5229)
  src/components/button/button-test.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5308 ci: update prepublishOnly and babel npm scripts
  package.json
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#5310 ci: remove npm ci from prepublishOnly script
  package.json
Labels: Pending Review, Squad Front End

#5266 fix(button): fix forwardRef type isssues - FE-5220
  src/components/button/button.component.tsx
  src/components/button/button.spec.tsx
  src/components/duelling-picklist/picklist-group/picklist-group.style.js
  src/components/duelling-picklist/picklist-item/picklist-item.style.js
  src/components/multi-action-button/multi-action-button.component.tsx
  src/components/multi-action-button/multi-action-button.spec.tsx
  src/components/split-button/split-button.component.js
  src/components/split-button/split-button.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5256 ci: update dependecies
  cypress.config.js
  cypress/plugins/index.js
  cypress/support/step-definitions/common-steps.js
  cypress/support/step-definitions/dialog-steps.js
  cypress/support/step-definitions/duelling-picklist-steps.js
  cypress/support/step-definitions/fieldset-steps.js
  cypress/support/step-definitions/flat-table-steps.js
  cypress/support/step-definitions/grid-steps.js
  cypress/support/step-definitions/heading-steps.js
  cypress/support/step-definitions/i18n-steps.js
  cypress/support/step-definitions/link-preview-steps.js
  cypress/support/step-definitions/link-steps.js
  cypress/support/step-definitions/menu-steps.js
  cypress/support/step-definitions/navigation-bar-steps.js
  cypress/support/step-definitions/numeral-date-steps.js
  cypress/support/step-definitions/pager-steps.js
  cypress/support/step-definitions/pages-steps.js
  cypress/support/step-definitions/pill-steps.js
  cypress/support/step-definitions/pod-steps.js
  cypress/support/step-definitions/popover-container-steps.js
  cypress/support/step-definitions/portrait-steps.js
  cypress/support/step-definitions/profile-steps.js
  cypress/support/step-definitions/search-steps.js
  cypress/support/step-definitions/select-steps.js
  cypress/support/step-definitions/show-edit-pod-steps.js
  cypress/support/step-definitions/sidebar-steps.js
  cypress/support/step-definitions/simple-color-picker-steps.js
  cypress/support/step-definitions/step-sequence-steps.js
  cypress/support/step-definitions/switch-steps.js
  cypress/support/step-definitions/tabs-steps.js
  cypress/support/step-definitions/text-area-steps.js
  cypress/support/step-definitions/textbox-steps.js
  cypress/support/step-definitions/themes-steps.js
  cypress/support/step-definitions/tile-select-step.js
  cypress/support/step-definitions/tile-steps.js
  cypress/support/step-definitions/toast-steps.js
  package-lock.json
  package.json
Labels: Passed Review, Passed QA, Cypress, Squad Front End

#5315 fix(menu-full-screen): pass onClick to menu item
  src/components/menu/__internal__/submenu/submenu.component.js
  src/components/menu/menu-full-screen/menu-full-screen.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5309 chore: remove invariant messages from bundle (FE-5100)
  babel.config.js
  package-lock.json
  package.json
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#5304 ci(postinstall): prevent scripts from running on Bitrise CI
  .env
  __mocks__/ci-info.js
  package-lock.json
  package.json
  scripts/check_carbon_version/check_carbon_version.js
  scripts/check_carbon_version/check_carbon_version.spec.js
  scripts/check_rfcs/check_rfcs.js
  scripts/check_rfcs/check_rfcs.spec.js
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#5255 fix(use-scroll-block): remove right padding added to the body
  src/hooks/__internal__/useScrollBlock/useScrollBlock.ts
Labels: Passed Review, Passed QA, No UX QA Required, third-party

#5205 refactor(field-help): convert files to typescript
  src/__internal__/field-help/field-help.component.js
  src/__internal__/field-help/field-help.component.tsx
  src/__internal__/field-help/field-help.d.ts
  src/__internal__/field-help/field-help.spec.tsx
  src/__internal__/field-help/field-help.style.js
  src/__internal__/field-help/field-help.style.ts
  src/__internal__/field-help/index.d.ts
  src/__internal__/field-help/index.js
  src/__internal__/field-help/index.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5312 chore: update jest config to support React Testing Library dependencies
  .npmignore
  enzyme.config.js
  jest.config.json
  package.json
  src/__spec_helper__/index.js
  src/__spec_helper__/index.ts
  src/__spec_helper__/mock-match-media.d.ts
  src/__spec_helper__/mock-match-media.js
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#5239 Allow focus to reach a Toast (or other element) from within a dialog, and fix various problems with radio buttons in a FocusTrap
  cypress/e2e/common/toast.feature
  cypress/support/step-definitions/toast-steps.js
  src/__internal__/focus-trap/focus-trap-utils.js
  src/__internal__/focus-trap/focus-trap.component.js
  src/__internal__/focus-trap/focus-trap.spec.js
  src/components/dialog-full-screen/dialog-full-screen.component.js
  src/components/dialog-full-screen/dialog-full-screen.d.ts
  src/components/dialog-full-screen/dialog-full-screen.stories.mdx
  src/components/dialog/dialog.component.js
  src/components/dialog/dialog.d.ts
  src/components/dialog/dialog.stories.mdx
  src/components/sidebar/sidebar.component.js
  src/components/sidebar/sidebar.d.ts
  src/components/sidebar/sidebar.stories.mdx
  src/components/toast/toast.component.js
  src/components/toast/toast.d.ts
  src/components/toast/toast.spec.js
  src/components/toast/toast.stories.mdx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5235 fix(multi-action-button): add new keyboard functionality to component FE-5188
  src/components/multi-action-button/__snapshots__/multi-action-button.spec.tsx.snap
  src/components/multi-action-button/multi-action-button.component.tsx
  src/components/multi-action-button/multi-action-button.spec.tsx
  src/components/multi-action-button/multi-action-button.test.js
  src/components/split-button/split-button-test.stories.js
  src/components/split-button/split-button.component.js
  src/components/split-button/split-button.spec.js
  src/components/split-button/split-button.test.js
  src/hooks/__internal__/useMenuKeyboardNavigation/index.ts
  src/hooks/__internal__/useMenuKeyboardNavigation/useMenuKeyboardNavigation.spec.tsx
  src/hooks/__internal__/useMenuKeyboardNavigation/useMenuKeyboardNavigation.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5177 test(select): add refactored cypress tests FE-4569
  cypress/e2e/common/simpleSelect.feature
  cypress/fixtures/commonComponents/simpleSelect.json
  cypress/locators/select/index.js
  cypress/locators/select/locators.js
  src/components/select/simple-select/simple-select.test.js
Labels: Pending QA, Cypress, Squad Front End

#5264 fix(filterableselect, multiselect): fix filter for nested components
  cypress/e2e/common/filterableSelect.feature
  cypress/locators/select/index.js
  cypress/locators/select/locators.js
  cypress/support/step-definitions/select-steps.js
  src/components/select/filterable-select/filterable-select.stories.mdx
  src/components/select/utils/highlight-part-of-text.js
  src/components/select/utils/highlight-part-of-text.spec.js
  src/components/select/utils/with-filter.hoc.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5271 test(box): refactor for cypress tests
  src/components/box/box.test.js
Labels: Pending Review, Pending QA, Cypress, Squad Front End, box

#5324 test(toast): refactor for cypress tests
  cypress/e2e/common/toast.feature
  cypress/fixtures/commonComponents/toast.json
  cypress/locators/toast/index.js
  cypress/support/step-definitions/toast-steps.js
  src/components/toast/toast.test.js
Labels: Passed Review, Passed QA, Cypress, Squad Front End

#5328 chore: update commitizen dependency to resolve critical vulnerabilities
  package-lock.json
  package.json
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#5318 fix(select): fix column alignment in multi column mode - FE-5238
  src/components/select/select-list/select-list.component.js
  src/components/select/select-list/select-list.spec.js
  src/components/select/select-list/select-list.style.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5317 refactor(split-button): convert to typescript
  src/components/button/button.component.tsx
  src/components/split-button/index.d.ts
  src/components/split-button/index.js
  src/components/split-button/index.ts
  src/components/split-button/split-button-children.style.ts
  src/components/split-button/split-button-toggle.style.ts
  src/components/split-button/split-button.component.tsx
  src/components/split-button/split-button.config.ts
  src/components/split-button/split-button.d.ts
  src/components/split-button/split-button.spec.tsx
  src/components/split-button/split-button.style.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5292 refactor(popover): convert internal popover to typescript - FE-4862
  src/__internal__/popover/index.d.ts
  src/__internal__/popover/index.js
  src/__internal__/popover/index.ts
  src/__internal__/popover/popover.component.tsx
  src/__internal__/popover/popover.d.ts
  src/__internal__/popover/popover.spec.tsx
  src/__internal__/popover/popover.style.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5287 fix(pager): change styles so all items are exposed to accessibility tree
  cypress/locators/pager/locators.js
  src/components/pager/pager.component.js
  src/components/pager/pager.spec.js
  src/components/pager/pager.style.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5321 Add padding interface to Page content FE-5245
  src/__internal__/full-screen-heading/full-screen-heading.component.tsx
  src/__internal__/full-screen-heading/full-screen-heading.style.ts
  src/__internal__/full-screen-heading/index.js
  src/__internal__/full-screen-heading/index.ts
  src/components/box/box.component.tsx
  src/components/box/box.spec.tsx
  src/components/pages/index.d.ts
  src/components/pages/index.ts
  src/components/pages/page/index.ts
  src/components/pages/page/package.json
  src/components/pages/page/page.component.js
  src/components/pages/page/page.component.tsx
  src/components/pages/page/page.d.ts
  src/components/pages/page/page.spec.tsx
  src/components/pages/page/page.style.ts
  src/components/pages/pages-test.stories.tsx
  src/components/pages/pages.component.tsx
  src/components/pages/pages.config.ts
  src/components/pages/pages.d.ts
  src/components/pages/pages.spec.tsx
  src/components/pages/pages.stories.mdx
  src/components/pages/pages.style.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5319 feat(icon-button): convert to typescript - FE-4799
  src/components/icon-button/icon-button.component.js
  src/components/icon-button/icon-button.component.tsx
  src/components/icon-button/icon-button.d.ts
  src/components/icon-button/icon-button.spec.tsx
  src/components/icon-button/icon-button.style.ts
  src/components/icon-button/index.d.ts
  src/components/icon-button/index.js
  src/components/icon-button/index.ts
  src/components/pill/pill.component.tsx
  src/components/popover-container/popover-container.component.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5336 chore: fix bug where vscode debugger cannot load jest tests
  .gitignore
  .vscode/launch.json
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#5330 test(heading): add cypress tests
  cypress/e2e/common/heading.feature
  cypress/fixtures/commonComponents/heading.json
  cypress/locators/heading/index.js
  cypress/locators/heading/locators.js
  cypress/support/step-definitions/heading-steps.js
  src/components/heading/heading.test.js
Labels: Pending Review, Pending QA, Cypress, Squad Front End, heading
