Repository Sage/carbon, pull requests merged in 2022-12, with the labels that each got.

#5623 refactor(textarea): convert textarea to typescript
  src/__internal__/input/input.component.tsx
  src/components/textarea/index.d.ts
  src/components/textarea/index.js
  src/components/textarea/index.ts
  src/components/textarea/textarea-test.stories.tsx
  src/components/textarea/textarea.component.tsx
  src/components/textarea/textarea.d.ts
  src/components/textarea/textarea.spec.tsx
  src/components/textarea/textarea.stories.mdx
  src/components/textarea/textarea.stories.tsx
  src/components/textarea/textarea.style.ts
Labels: Passed Review, Passed QA, Squad Front End

#5634 fix(date-range): update styles so validation and label text wrap if they exceed input width
  src/components/date-range/date-range.spec.js
  src/components/date-range/date-range.stories.mdx
  src/components/date/date.component.js
  src/components/date/date.style.js
  src/components/textarea/textarea.component.tsx
  src/components/textbox/textbox.component.tsx
  src/components/textbox/textbox.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5663 docs(accordion): use stories from tsx file
  src/components/accordion/accordion-test.stories.tsx
  src/components/accordion/accordion.stories.mdx
  src/components/accordion/accordion.stories.tsx
  src/components/accordion/accordion.test.js
Labels: Passed Review, Passed QA, Squad Front End, accordion

#5635 fix: added missing focus trap props to sidebar and full-width-dialog
  src/components/dialog-full-screen/dialog-full-screen.component.js
  src/components/sidebar/sidebar.component.tsx
Labels: Pending Review, Passed QA, No UX QA Required, Squad X3

#5622 feat(textarea, textbox): surface maxWidth prop on components FE-5506
  src/__internal__/input/__snapshots__/input-presentation.spec.tsx.snap
  src/__internal__/input/input-presentation.component.tsx
  src/__internal__/input/input-presentation.spec.tsx
  src/__internal__/input/input-presentation.style.ts
  src/components/date/date.stories.mdx
  src/components/decimal/decimal.spec.tsx
  src/components/decimal/decimal.stories.mdx
  src/components/decimal/decimal.stories.tsx
  src/components/decimal/decimal.test.js
  src/components/grouped-character/grouped-character.spec.tsx
  src/components/grouped-character/grouped-character.stories.mdx
  src/components/grouped-character/grouped-character.test.js
  src/components/number/number.spec.js
  src/components/number/number.stories.mdx
  src/components/number/number.test.js
  src/components/search/search.component.tsx
  src/components/search/search.spec.tsx
  src/components/search/search.stories.mdx
  src/components/search/search.style.ts
  src/components/search/search.test.js
  src/components/select/filterable-select/filterable-select.spec.js
  src/components/select/filterable-select/filterable-select.stories.mdx
  src/components/select/filterable-select/filterable-select.test.js
  src/components/select/multi-select/multi-select.spec.js
  src/components/select/multi-select/multi-select.stories.mdx
  src/components/select/multi-select/multi-select.test.js
  src/components/select/select-textbox/select-textbox.component.js
  src/components/select/simple-select/simple-select.spec.js
  src/components/select/simple-select/simple-select.stories.mdx
  src/components/select/simple-select/simple-select.test.js
  src/components/textarea/textarea-test.stories.tsx
  src/components/textarea/textarea.component.tsx
  src/components/textarea/textarea.spec.tsx
  src/components/textarea/textarea.stories.mdx
  src/components/textarea/textarea.stories.tsx
  src/components/textarea/textarea.test.js
  src/components/textbox/textbox-test.stories.tsx
  src/components/textbox/textbox.component.tsx
  src/components/textbox/textbox.spec.tsx
  src/components/textbox/textbox.stories.mdx
  src/components/textbox/textbox.test.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5660 fix(pager): ensure there is no margin-bottom on page number input
  src/components/pager/pager.spec.js
  src/components/pager/pager.style.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5649 refactor(toast): convert to TypeScript - FE-4843
  src/components/message/message.style.ts
  src/components/portal/index.ts
  src/components/portal/portal.tsx
  src/components/toast/index.d.ts
  src/components/toast/index.js
  src/components/toast/index.ts
  src/components/toast/toast-test.stories.tsx
  src/components/toast/toast.component.tsx
  src/components/toast/toast.config.ts
  src/components/toast/toast.d.ts
  src/components/toast/toast.spec.tsx
  src/components/toast/toast.stories.mdx
  src/components/toast/toast.stories.tsx
  src/components/toast/toast.style.ts
Labels: Passed Review, Passed QA, Squad Front End, toast, typescript

#5676 fix(pager): fix bottom margin of number input when inside a form
  cypress/locators/pager/index.js
  cypress/locators/pager/locators.js
  src/components/pager/pager.spec.js
  src/components/pager/pager.style.js
  src/components/pager/pager.test.js
Labels: Passed Review, Pending QA, No UX QA Required, Squad Front End

#5655 feat(button-toggle-group): surface fullWidth prop to ensure children flex to container width
  src/components/button-toggle-group/button-toggle-group.component.tsx
  src/components/button-toggle-group/button-toggle-group.spec.tsx
  src/components/button-toggle-group/button-toggle-group.stories.mdx
  src/components/button-toggle-group/button-toggle-group.style.ts
  src/components/button-toggle-group/button-toggle-group.test.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5624 Sidebar Header and Form Footer Padding FE-5391
  src/components/dialog/dialog.style.ts
  src/components/form/form.component.tsx
  src/components/form/form.spec.tsx
  src/components/form/form.stories.mdx
  src/components/form/form.stories.tsx
  src/components/form/form.style.ts
  src/components/sidebar/__internal__/sidebar-header/sidebar-header.component.tsx
  src/components/sidebar/__internal__/sidebar-header/sidebar-header.spec.tsx
  src/components/sidebar/__internal__/sidebar-header/sidebar-header.style.ts
  src/components/sidebar/sidebar.component.tsx
  src/components/sidebar/sidebar.stories.mdx
  src/components/sidebar/sidebar.stories.tsx
  src/style/utils/form-style-utils.spec.ts
  src/style/utils/form-style-utils.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5667 docs(checkbox): refactor stories to typescript (FE-5553)
  docs/validations.stories.mdx
  src/components/checkbox/checkbox-validations.stories.mdx
  src/components/checkbox/checkbox-validations.stories.tsx
  src/components/checkbox/checkbox.stories.mdx
  src/components/checkbox/checkbox.stories.tsx
  src/components/radio-button/radio-button.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5636 refactor(dialog-full-screen): convert component to TS - FE-4785
  src/components/dialog-full-screen/content.style.ts
  src/components/dialog-full-screen/dialog-full-screen-test.stories.tsx
  src/components/dialog-full-screen/dialog-full-screen.component.tsx
  src/components/dialog-full-screen/dialog-full-screen.d.ts
  src/components/dialog-full-screen/dialog-full-screen.spec.tsx
  src/components/dialog-full-screen/dialog-full-screen.stories.mdx
  src/components/dialog-full-screen/dialog-full-screen.stories.tsx
  src/components/dialog-full-screen/dialog-full-screen.style.ts
  src/components/dialog-full-screen/index.d.ts
  src/components/dialog-full-screen/index.js
  src/components/dialog-full-screen/index.ts
  src/components/modal/modal.component.tsx
Labels: Passed Review, Passed QA, Squad Front End

#5680 test(action-popover): refactor for accessibility
  cypress/support/accessibility/a11y-utils.js
  src/components/action-popover/action-popover-test.stories.tsx
  src/components/action-popover/action-popover.stories.mdx
  src/components/action-popover/action-popover.stories.tsx
  src/components/action-popover/action-popover.test.js
Labels: Pending Review, Pending QA, Accessibility, Cypress, Squad Front End, action-popover

#5637 feat(tile): add black variant to footer and add border options
  package-lock.json
  package.json
  src/components/portal/__snapshots__/portal.spec.tsx.snap
  src/components/tile/__snapshots__/tile.spec.js.snap
  src/components/tile/tile-footer/tile-footer.component.js
  src/components/tile/tile-footer/tile-footer.d.ts
  src/components/tile/tile-footer/tile-footer.spec.js
  src/components/tile/tile-footer/tile-footer.style.js
  src/components/tile/tile.component.js
  src/components/tile/tile.d.ts
  src/components/tile/tile.spec.js
  src/components/tile/tile.stories.mdx
  src/components/tile/tile.style.js
  src/components/tile/tile.test.js
  src/style/design-tokens/carbon-scoped-tokens-provider/__snapshots__/carbon-scoped-tokens-provider.component.spec.tsx.snap
  src/style/themes/aegean/__snapshots__/aegean-theme.spec.ts.snap
  src/style/themes/mint/__snapshots__/mint-theme.spec.ts.snap
  src/style/themes/none/__snapshots__/none.spec.ts.snap
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End, tile

#5670 feat(card): add height prop (FE-5560)
  src/components/card/card.component.tsx
  src/components/card/card.stories.mdx
  src/components/card/card.stories.tsx
  src/components/card/card.style.ts
  src/components/card/card.test.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End, card

#5678 fix(tab): ensure that validation failures are no longer reported when children unmount FE-5527
  src/__internal__/form-field/form-field.component.tsx
  src/components/tabs/tab/tab.component.js
  src/components/tabs/tab/tab.d.ts
  src/components/tabs/tabs.component.js
  src/components/tabs/tabs.d.ts
  src/components/tabs/tabs.spec.js
  src/components/tabs/tabs.stories.mdx
  src/components/tabs/tabs.test.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End, tabs

#5652 test(loader-bar): accessibility tests for loader-bar
  cypress/support/accessibility/a11y-utils.js
  src/components/loader-bar/loader-bar-test.stories.tsx
  src/components/loader-bar/loader-bar.stories.mdx
  src/components/loader-bar/loader-bar.stories.tsx
  src/components/loader-bar/loader-bar.test.js
Labels: Passed Review, Passed QA, Accessibility, Cypress, Squad Front End, loader-bar

#5684 docs(typography,box): add deprecation message regarding removal of undocumented props
  src/components/box/box.component.tsx
  src/components/typography/typography.component.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5665 feat(icon-button): add padding interface to component FE-5567
  src/components/batch-selection/__snapshots__/batch-selection.spec.js.snap
  src/components/icon-button/icon-button.component.tsx
  src/components/icon-button/icon-button.spec.tsx
  src/components/icon-button/icon-button.stories.mdx
  src/components/icon-button/icon-button.style.ts
  src/components/menu/menu-item/menu-item.component.js
  src/components/menu/menu-item/menu-item.spec.js
  src/components/menu/menu-item/menu-item.style.js
  src/components/navigation-bar/navigation-bar.stories.mdx
  src/components/pod/__snapshots__/pod.spec.js.snap
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5661 feat(multi-action-button): surface width prop to allow width to be set for component
  src/components/multi-action-button/multi-action-button.component.tsx
  src/components/multi-action-button/multi-action-button.spec.tsx
  src/components/multi-action-button/multi-action-button.stories.mdx
  src/components/multi-action-button/multi-action-button.stories.tsx
  src/components/multi-action-button/multi-action-button.style.ts
  src/components/multi-action-button/multi-action-button.test.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5671 fix(pager): correctly associate labels to input fields
  src/components/pager/__internal__/pager-navigation.component.js
  src/components/pager/__internal__/pager-navigation.spec.js
  src/components/pager/pager.component.js
  src/components/pager/pager.spec.js
  src/components/pager/pager.style.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5686 feat(icon): 1 new icon added dashboard
  src/components/icon/__snapshots__/icon-unicodes.spec.js.snap
  src/components/icon/fonts/carbon-icons-webfont.woff
  src/components/icon/icon-config.ts
  src/components/icon/icon-type.ts
  src/components/icon/icon-unicodes.js
  src/style/assets/carbon-icons-webfont.woff
Labels: Passed Review, Passed QA, Passed UX QA, icon

#5691 test(link-preview): refactor for accessibility test
  cypress/support/accessibility/a11y-utils.js
  src/components/link-preview/link-preview-test.stories.tsx
  src/components/link-preview/link-preview.stories.mdx
  src/components/link-preview/link-preview.stories.tsx
  src/components/link-preview/link-preview.test.js
Labels: Pending Review, Pending QA, Cypress, Squad Front End, link-preview

#5662 docs: storybook remove util references (FE-5315)
  .storybook/utils/partial-action.js
  src/__internal__/utils/storybook/partial-action.ts
  src/components/action-popover/action-popover.stories.mdx
  src/components/action-popover/action-popover.stories.tsx
  src/components/alert/alert.stories.tsx
  src/components/button-toggle-group/button-toggle-group-test.stories.tsx
  src/components/button-toggle-group/button-toggle-group.stories.mdx
  src/components/button-toggle/button-toggle.stories.mdx
  src/components/dialog-full-screen/dialog-full-screen.stories.tsx
  src/components/dialog/dialog.stories.tsx
  src/components/dismissible-box/dismissible-box.stories.mdx
  src/components/draggable/draggable.stories.mdx
  src/components/drawer/drawer.stories.mdx
  src/components/pager/pager.stories.mdx
  src/components/popover-container/popover-container.stories.mdx
  src/components/select/filterable-select/filterable-select-test.stories.tsx
  src/components/select/filterable-select/filterable-select.stories.mdx
  src/components/select/multi-select/multi-select-test.stories.tsx
  src/components/select/multi-select/multi-select.stories.mdx
  src/components/sidebar/sidebar.stories.tsx
  src/components/tile/tile.stories.mdx
  src/components/toast/toast-test.stories.tsx
  src/components/toast/toast.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5693 fix(tabs): fix an issue with Tabs infinite rerender - FE-5585
  src/components/tabs/tab/tab.component.js
  src/components/tabs/tabs.component.js
  src/components/tabs/tabs.spec.js
Labels: Pending Review, Passed QA, Squad Front End

#5683 docs: add missing prop tables and prop descriptions (FE-5333)
  src/components/accordion/accordion-group/accordion-group.component.tsx
  src/components/accordion/accordion.component.tsx
  src/components/accordion/accordion.stories.tsx
  src/components/action-popover/action-popover-menu-button/action-popover-menu-button.component.tsx
  src/components/action-popover/action-popover.stories.mdx
  src/components/anchor-navigation/anchor-navigation.stories.mdx
  src/components/button-bar/button-bar.component.tsx
  src/components/carousel/carousel.stories.mdx
  src/components/carousel/slide/slide.component.tsx
  src/components/duelling-picklist/duelling-picklist.component.js
  src/components/duelling-picklist/duelling-picklist.d.ts
  src/components/fieldset/fieldset.component.tsx
  src/components/flat-table/flat-table-cell/flat-table-cell.component.js
  src/components/flat-table/flat-table-cell/flat-table-cell.d.ts
  src/components/flat-table/flat-table-header/flat-table-header.component.js
  src/components/flat-table/flat-table-header/flat-table-header.d.ts
  src/components/flat-table/flat-table-row-header/flat-table-row-header.component.js
  src/components/flat-table/flat-table-row-header/flat-table-row-header.d.ts
  src/components/navigation-bar/navigation-bar.component.tsx
  src/components/vertical-divider/vertical-divider.component.tsx
Labels: Pending Review, Passed QA, No UX QA Required, Squad Front End

#5707 ci: update dependecies
  cypress/support/component.js
  package-lock.json
  package.json
  src/components/accordion/accordion.test.js
  src/components/action-popover/action-popover-test.stories.tsx
Labels: Passed QA, Cypress, Squad Front End

#5702 test(vertical-divider): add cypress tests
  cypress/locators/vertical-divider/index.js
  cypress/locators/vertical-divider/locators.js
  cypress/support/accessibility/a11y-utils.js
  src/components/vertical-divider/vertical-divider-test.stories.tsx
  src/components/vertical-divider/vertical-divider.test.js
Labels: Passed Review, Passed QA, Accessibility, Cypress, Squad Front End, vertical-divider

#5626 refactor(simple-color-picker): ts conversion - FE-4833
  docs/validations.stories.mdx
  src/__internal__/fieldset/fieldset.component.tsx
  src/components/advanced-color-picker/__snapshots__/advanced-color-picker.spec.js.snap
  src/components/advanced-color-picker/advanced-color-picker.spec.js
  src/components/advanced-color-picker/advanced-color-picker.style.js
  src/components/simple-color-picker/__snapshots__/simple-color-picker.spec.js.snap
  src/components/simple-color-picker/color-sample-box/color-sample-box.component.js
  src/components/simple-color-picker/color-sample-box/color-sample-box.spec.js
  src/components/simple-color-picker/color-sample-box/color-sample-box.style.js
  src/components/simple-color-picker/color-sample-box/index.js
  src/components/simple-color-picker/index.d.ts
  src/components/simple-color-picker/index.ts
  src/components/simple-color-picker/simple-color-input/simple-color-input.spec.js
  src/components/simple-color-picker/simple-color-input/simple-color-input.style.js
  src/components/simple-color-picker/simple-color-picker-test.stories.mdx
  src/components/simple-color-picker/simple-color-picker-test.stories.tsx
  src/components/simple-color-picker/simple-color-picker.component.tsx
  src/components/simple-color-picker/simple-color-picker.d.ts
  src/components/simple-color-picker/simple-color-picker.spec.tsx
  src/components/simple-color-picker/simple-color-picker.stories.mdx
  src/components/simple-color-picker/simple-color-picker.stories.tsx
  src/components/simple-color-picker/simple-color-picker.style.ts
  src/components/simple-color-picker/simple-color/checker-board.svg
  src/components/simple-color-picker/simple-color/index.js
  src/components/simple-color-picker/simple-color/index.ts
  src/components/simple-color-picker/simple-color/simple-color.component.js
  src/components/simple-color-picker/simple-color/simple-color.component.tsx
  src/components/simple-color-picker/simple-color/simple-color.d.ts
  src/components/simple-color-picker/simple-color/simple-color.spec.js
  src/components/simple-color-picker/simple-color/simple-color.spec.tsx
  src/components/simple-color-picker/simple-color/simple-color.style.js
  src/components/simple-color-picker/simple-color/simple-color.style.ts
  src/components/simple-color-picker/tick-icon/tick-icon.spec.js
  src/components/simple-color-picker/tick-icon/tick-icon.style.js
Labels: Pending Review, Passed QA, No UX QA Required, Squad Front End

#5694 refactor(number): convert files to typescript (FE-4813)
  src/components/number/index.d.ts
  src/components/number/index.js
  src/components/number/index.ts
  src/components/number/number-test.stories.mdx
  src/components/number/number-test.stories.tsx
  src/components/number/number-validation-test.stories.tsx
  src/components/number/number.component.js
  src/components/number/number.component.tsx
  src/components/number/number.d.ts
  src/components/number/number.spec.tsx
  src/components/number/number.stories.mdx
  src/components/number/number.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End
