Repository Sage/carbon, pull requests merged in 2022-10, with the labels that each got.

#5519 chore: update npm scripts and remove `/scripts` tsconfig
  .eslintrc
  package.json
  scripts/tsconfig.json
  tsconfig.json
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#5482 refactor(content): convert component to typescript - FE-4778
  src/components/content/content-test.stories.mdx
  src/components/content/content.component.js
  src/components/content/content.component.tsx
  src/components/content/content.d.ts
  src/components/content/content.spec.tsx
  src/components/content/content.stories.mdx
  src/components/content/content.stories.tsx
  src/components/content/content.style.ts
  src/components/content/index.d.ts
  src/components/content/index.js
  src/components/content/index.ts
  src/components/typography/typography.component.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5513 ci(check_rfcs, check_carbon_version): prevent api calls when run as part of CI pipeline
  scripts/check_carbon_version/check_carbon_version.js
  scripts/check_carbon_version/check_carbon_version.spec.js
  scripts/check_rfcs/check_rfcs.js
  scripts/check_rfcs/check_rfcs.spec.js
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#5530 test(cypress): udpate the dependency
  .github/workflows/cypress.yml
  package-lock.json
  package.json
Labels: Passed Review, Cypress, Squad Front End

#5495 feat(toast): add notice variant (FE-4402)
  src/components/toast/toast-test.stories.mdx
  src/components/toast/toast.component.js
  src/components/toast/toast.d.ts
  src/components/toast/toast.spec.js
  src/components/toast/toast.stories.mdx
  src/components/toast/toast.style.js
  src/components/toast/toast.test.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5524 test(grid): refactor for cypress tests
  cypress/e2e/common/grid.feature
  cypress/fixtures/commonComponents/grid.json
  cypress/locators/grid/index.js
  cypress/support/step-definitions/grid-steps.js
  src/components/grid/grid.test.js
Labels: Pending Review, Passed QA, Cypress, Squad Front End, grid

#5514 feat(sidebar, drawer and dialogs): adjust background of modal headers to be white instead of grey
  src/__internal__/full-screen-heading/full-screen-heading.style.ts
  src/components/dialog/dialog.style.ts
  src/components/sidebar/__internal__/sidebar-header/sidebar-header.spec.tsx
  src/components/sidebar/__internal__/sidebar-header/sidebar-header.style.ts
Labels: Passed Review, Passed QA, dialog-full-screen, dialog, drawer, sidebar

#5426 test: pill
  cypress/e2e/common/pill.feature
  cypress/fixtures/commonComponents/pill.json
  cypress/support/step-definitions/pill-steps.js
  src/components/pill/pill.test.js
Labels: Pending Review, Pending QA, No UX QA Required, Squad Front End

#5506 test(portrait): add cypress tests
  cypress/e2e/common/portrait.feature
  cypress/fixtures/commonComponents/portrait.json
  cypress/locators/portrait/index.js
  cypress/support/step-definitions/portrait-steps.js
  src/components/portrait/portrait.test.js
Labels: Passed Review, Pending QA, Cypress, Squad Front End, portrait

#5298 test: radiobutton
  cypress/locators/radiobutton/index.js
  cypress/locators/radiobutton/locators.js
  cypress/support/component-helper/constants.js
  src/components/radio-button/radiobutton.test.js
Labels: Pending Review, Pending QA, No UX QA Required, Cypress, Squad Front End

#5512 feat(box): add support for the gap css property when component is displayed flex or inline-flex FE-5357
  .storybook/utils/styled-system-props.js
  src/components/box/box.component.tsx
  src/components/box/box.config.ts
  src/components/box/box.spec.tsx
  src/components/box/box.stories.mdx
  src/components/box/box.test.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5542 docs(loader-bar): ensure prop table displays in docs - FE-5405
  src/components/loader-bar/loader-bar.component.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5538 test(profile): add cypress tests
  cypress/e2e/common/profile.feature
  cypress/fixtures/commonComponents/profile.json
  cypress/locators/profile/index.js
  cypress/locators/profile/locators.js
  cypress/support/step-definitions/profile-steps.js
  src/components/profile/profile.test.js
Labels: Pending Review, Pending QA, Cypress, Squad Front End, profile

#5520 test(accordion): refactor for accessibility tests
  cypress/support/accessibility/a11y-utils.js
  cypress/support/component.js
  src/components/accordion/accordion.stories.tsx
  src/components/accordion/accordion.test.js
Labels: Passed Review, Passed QA, Accessibility, Cypress, Squad Front End, accordion

#5528 update docs for skip link so the menu items are tabbable
  src/components/link/link.stories.mdx
  src/components/link/link.stories.tsx
Labels: Passed Review, Pending QA, No UX QA Required, Squad Front End

#5540 fix(multi-action-button): fix styling bug when a href is passed to a button - FE-5375
  src/components/multi-action-button/__snapshots__/multi-action-button.spec.tsx.snap
  src/components/multi-action-button/multi-action-button.component.tsx
  src/components/multi-action-button/multi-action-button.style.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5552 fix: move cypress preprocessor dependencies to devDependencies
  package-lock.json
  package.json
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#5539 fix(tab): prevent title prop being set as an attribute on the DOM element FE-5403
  src/components/tabs/tab/tab.component.js
  src/components/tabs/tab/tab.spec.js
  src/components/tabs/tabs.component.js
  src/components/tabs/tabs.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5556 chore(tab): make isTabSelected prop private and ignore in prop table docs
  src/components/tabs/tab/tab.component.js
  src/components/tabs/tab/tab.d.ts
Labels: Pending Review, Pending QA, No UX QA Required, Squad Front End

#5518 fix(dialog): add DialogSizes type to component interface (FE-5390)
  .storybook/isChromatic.d.ts
  src/components/dialog/dialog.component.tsx
  src/components/dialog/dialog.config.ts
  src/components/dialog/dialog.stories.mdx
  src/components/dialog/dialog.stories.tsx
  src/components/dialog/dialog.style.ts
  src/components/dialog/index.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5517 refactor(decimal): refactor to typescript - FE-4871
  src/components/decimal/decimal-test.stories.tsx
  src/components/decimal/decimal.component.tsx
  src/components/decimal/decimal.d.ts
  src/components/decimal/decimal.spec.tsx
  src/components/decimal/decimal.stories.mdx
  src/components/decimal/decimal.stories.tsx
  src/components/decimal/index.d.ts
  src/components/decimal/index.js
  src/components/decimal/index.ts
  src/components/textbox/textbox-test.stories.tsx
Labels: Passed Review, Passed QA, Squad Front End

#5554 test(tabs): refactor for cypress tests
  cypress/e2e/common/tabs.feature
  cypress/fixtures/commonComponents/tabs.json
  cypress/support/step-definitions/tabs-steps.js
  src/components/tabs/tabs.test.js
Labels: Pending Review, Pending QA, Cypress, Squad Front End, tabs

#5489 refactor(typography): convert typography components to typescript
  src/components/typography/index.d.ts
  src/components/typography/index.js
  src/components/typography/index.ts
  src/components/typography/list.component.js
  src/components/typography/list.component.tsx
  src/components/typography/list.d.ts
  src/components/typography/typography.component.tsx
  src/components/typography/typography.d.ts
  src/components/typography/typography.spec.tsx
  src/components/typography/typography.stories.mdx
  src/components/typography/typography.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End, typography

#5543 fix: fix typescript errors in declaration files
  package-lock.json
  package.json
  src/__internal__/radio-button-mapper/radio-button-mapper.component.js
  src/__internal__/radio-button-mapper/radio-button-mapper.d.ts
  src/components/date/__internal__/date-formats/index.d.ts
  src/components/date/date.d.ts
  src/components/menu/menu.d.ts
  src/components/search/search.d.ts
  src/components/select/filterable-select/filterable-select.d.ts
  src/components/select/multi-select/multi-select.d.ts
  src/components/select/select-textbox/select-textbox.d.ts
  src/components/select/simple-select/simple-select.d.ts
  src/components/tabs/tabs.d.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5550 refactor(multi-action-button): refactor stories to be tsx
  cypress/e2e/themes/themes.feature
  src/components/multi-action-button/multi-action-button.stories.mdx
  src/components/multi-action-button/multi-action-button.stories.tsx
  src/components/multi-action-button/multi-action-button.style.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5508 refactor(card): convert to typescript (FE-4774)
  src/components/box/box.component.tsx
  src/components/card/card-column/card-column.component.js
  src/components/card/card-column/card-column.component.tsx
  src/components/card/card-column/card-column.d.ts
  src/components/card/card-column/card-column.spec.js
  src/components/card/card-column/card-column.spec.tsx
  src/components/card/card-column/card-column.style.js
  src/components/card/card-column/card-column.style.ts
  src/components/card/card-column/index.d.ts
  src/components/card/card-column/index.js
  src/components/card/card-column/index.ts
  src/components/card/card-footer/__snapshots__/card-footer.spec.tsx.snap
  src/components/card/card-footer/card-footer.component.js
  src/components/card/card-footer/card-footer.component.tsx
  src/components/card/card-footer/card-footer.d.ts
  src/components/card/card-footer/card-footer.spec.tsx
  src/components/card/card-footer/card-footer.style.ts
  src/components/card/card-footer/index.d.ts
  src/components/card/card-footer/index.js
  src/components/card/card-footer/index.ts
  src/components/card/card-row/card-row.component.js
  src/components/card/card-row/card-row.component.tsx
  src/components/card/card-row/card-row.d.ts
  src/components/card/card-row/card-row.spec.js
  src/components/card/card-row/card-row.spec.tsx
  src/components/card/card-row/card-row.style.js
  src/components/card/card-row/card-row.style.ts
  src/components/card/card-row/index.d.ts
  src/components/card/card-row/index.js
  src/components/card/card-row/index.ts
  src/components/card/card-test.stories.mdx
  src/components/card/card-test.stories.tsx
  src/components/card/card-types.d.ts
  src/components/card/card.component.js
  src/components/card/card.component.tsx
  src/components/card/card.config.js
  src/components/card/card.config.ts
  src/components/card/card.d.ts
  src/components/card/card.spec.js
  src/components/card/card.spec.tsx
  src/components/card/card.stories.mdx
  src/components/card/card.stories.tsx
  src/components/card/card.style.ts
  src/components/card/card.test.js
  src/components/card/index.d.ts
  src/components/card/index.ts
  src/components/detail/detail.stories.mdx
  src/components/drawer/__snapshots__/drawer.spec.tsx.snap
  src/components/tile/tile.stories.mdx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5548 fix(tags): update TagProps interface so only the data tag types are exported
  src/__internal__/utils/helpers/tags/tags.ts
  src/components/dialog-full-screen/dialog-full-screen.d.ts
  src/components/dialog/dialog-test.stories.tsx
  src/components/dialog/dialog.component.tsx
  src/components/dialog/dialog.spec.tsx
  src/components/dialog/dialog.stories.tsx
  src/components/sidebar/sidebar.component.tsx
  src/components/sidebar/sidebar.spec.tsx
  src/components/sidebar/sidebar.stories.mdx
  src/components/textbox/textbox.component.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5559 test(pages): refactor for cypress tests
  cypress/e2e/common/pages.feature
  cypress/fixtures/commonComponents/pages.json
  cypress/locators/pages/index.js
  cypress/locators/pages/locators.js
  cypress/support/component-helper/common-steps.js
  cypress/support/step-definitions/dialog-steps.js
  cypress/support/step-definitions/pages-steps.js
  src/components/pages/pages.test.js
Labels: Passed Review, Passed QA, Cypress, Squad Front End, pages

#5474 fix(dialog, sidebar): ensure aria-modal is only added to top modal
  src/components/carbon-provider/carbon-provider.component.tsx
  src/components/carbon-provider/top-modal-context.spec.tsx
  src/components/carbon-provider/top-modal-context.tsx
  src/components/dialog-full-screen/dialog-full-screen.component.js
  src/components/dialog-full-screen/dialog-full-screen.spec.js
  src/components/dialog-full-screen/dialog-full-screen.test.js
  src/components/dialog/dialog.component.tsx
  src/components/dialog/dialog.spec.tsx
  src/components/modal/__internal__/modal-manager.spec.ts
  src/components/modal/__internal__/modal-manager.ts
  src/components/sidebar/sidebar.component.tsx
  src/components/sidebar/sidebar.spec.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5563 fix: upgrade node-fetch dependency to version 3
  package-lock.json
  package.json
  scripts/check_carbon_version/check_carbon_version.js
  scripts/check_carbon_version/check_carbon_version.spec.js
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#5566 test(grid): ensure cypress tests are not dependent on pod component
  cypress/locators/grid/index.js
  src/components/grid/grid.test.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End, grid

#5533 feat(image): add hidden prop
  src/components/image/image.spec.tsx
  src/components/image/image.stories.mdx
  src/components/image/image.stories.tsx
  src/components/image/image.style.ts
  src/components/image/image.test.js
  src/global.d.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5573 test(tabs): update flaky test
  src/components/tabs/tabs.test.js
Labels: Passed QA, Cypress, Squad Front End, tabs

#5578 test(textbox): refactor for cypress tests
  cypress/e2e/common/textbox.feature
  cypress/e2e/common/textboxMultiple.feature
  cypress/fixtures/commonComponents/buttonAsSibling.json
  cypress/fixtures/commonComponents/row.json
  cypress/fixtures/commonComponents/textbox.json
  cypress/locators/textbox/index.js
  cypress/support/step-definitions/textbox-steps.js
  src/components/textbox/textbox.test.js
Labels: Passed Review, Passed QA, Cypress, Squad Front End, textbox

#5078 fix(definition-list): correct font styling of dt and dd elements
  src/components/definition-list/definition-list.spec.tsx
  src/components/definition-list/definition-list.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5583 test(tile): add cypress tests
  cypress/e2e/common/tile.feature
  cypress/fixtures/commonComponents/tile.json
  cypress/locators/tile/index.js
  cypress/locators/tile/locators.js
  cypress/support/step-definitions/tile-steps.js
  src/components/tile/tile.test.js
Labels: Pending Review, Pending QA, Cypress, Squad Front End, tile

#5561 fix(select): fix select list positioning issues - FE-5406 & FE-5494
  cypress/locators/flat-table/index.js
  cypress/locators/select/index.js
  src/components/select/filterable-select/filterable-select.component.js
  src/components/select/select-list/select-list-container.style.js
  src/components/select/select-list/select-list.component.js
  src/components/select/select-list/select-list.spec.js
  src/components/select/select-list/select-list.style.js
Labels: Passed Review, Pending QA, Squad Front End
