Repository Sage/carbon, pull requests merged in 2022-04, with the labels that each got.

#5009 docs: close modals by default - FE-5107
  .storybook/theme-selector/index.js
  src/components/alert/alert.stories.mdx
  src/components/confirm/confirm.stories.mdx
  src/components/dialog-full-screen/dialog-full-screen.stories.mdx
  src/components/dialog/dialog.stories.mdx
  src/components/sidebar/sidebar.stories.mdx
Labels: Pending Review, Pending QA, No UX QA Required, Squad Front End

#5001 test(action-popover): refactor for cypress tests
  cypress/integration/common/actionPopover.feature
  cypress/integration/common/actionPopoverEvents.feature
  cypress/support/helper.js
  src/components/action-popover/action-popover.test.js
Labels: Pending QA, Cypress, Squad Front End

#4931 fix(flat-table): correct cursor when using draggable rows
  package-lock.json
  package.json
  src/components/flat-table/flat-table-body-draggable/flat-table-body-draggable.component.js
  src/components/flat-table/flat-table-body-draggable/flat-table-body-draggable.spec.js
  src/components/flat-table/flat-table-body-draggable/flat-table-body-draggable.style.js
  src/components/flat-table/flat-table-row/flat-table-row.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5008 docs(number): fix bug where the input would be cleared on typing a letter - FE-5105
  src/components/number/number.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4929 test(accordion): refactor cypress tests
  cypress/integration/common/accordion.feature
  cypress/integration/common/accordionGrouped.feature
  cypress/locators/accordion/index.js
  cypress/locators/accordion/locators.js
  src/components/accordion/accordion.test.js
Labels: Passed Review, Pending QA, No UX QA Required, Squad Front End

#5012 build(generate_proptypes): fix missing require default declaration
  scripts/generate_proptypes/inject.ts
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#4997 fix(select): fix incorrect option children prop type definition - FE-5093
  src/components/select/option/index.d.ts
  src/components/select/simple-select/simple-select.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4998 refactor(tooltip): convert to typescript
  package-lock.json
  package.json
  src/__internal__/validations/validation-icon.spec.js
  src/components/help/help.spec.js
  src/components/icon/icon.spec.js
  src/components/tooltip/__snapshots__/tooltip.spec.tsx.snap
  src/components/tooltip/index.d.ts
  src/components/tooltip/index.js
  src/components/tooltip/index.ts
  src/components/tooltip/tooltip-pointer.style.ts
  src/components/tooltip/tooltip.component.tsx
  src/components/tooltip/tooltip.config.ts
  src/components/tooltip/tooltip.d.ts
  src/components/tooltip/tooltip.spec.tsx
  src/components/tooltip/tooltip.style.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5013 refactor: convert theme selector plugin - FE-5114
  .storybook/isChromatic.js
  .storybook/main.js
  .storybook/preview.js
  .storybook/theme-selector/index.js
  .storybook/theme-selector/register.js
  .storybook/withThemeProvider.js
  cypress/support/helper.js
  docs/testing-styleguide.md
  package-lock.json
  package.json
  src/components/alert/alert.stories.mdx
  src/components/button/button-test.stories.mdx
  src/components/confirm/confirm.stories.mdx
  src/components/date/date.stories.mdx
  src/components/dialog-full-screen/dialog-full-screen.stories.mdx
  src/components/dialog/dialog.stories.mdx
  src/components/form/form.stories.mdx
  src/components/navigation-bar/navigation-bar.stories.mdx
  src/components/sidebar/sidebar.stories.mdx
  src/components/toast/toast-test.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5021 test(number input): add refactored tests for number input FE-4554
  cypress/fixtures/commonComponents/numberInput.json
  cypress/integration/common/numberInput.feature
  cypress/locators/index.js
  cypress/locators/locators.js
  cypress/support/component-helper/common-steps.js
  cypress/support/step-definitions/number-input-steps.js
  src/components/grouped-character/grouped-character.test.js
  src/components/number/number.test.js
Labels: Pending Review, Cypress, Squad Front End, number

#5000 feat(multi-action-button, split-button): pass props down to main button
  src/components/multi-action-button/multi-action-button.component.js
  src/components/multi-action-button/multi-action-button.d.ts
  src/components/multi-action-button/multi-action-button.spec.js
  src/components/split-button/split-button.component.js
  src/components/split-button/split-button.d.ts
  src/components/split-button/split-button.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#4992 feat: support new `Sage UI` typeface
  .storybook/assets/fonts/Lato-Black.eot
  .storybook/assets/fonts/Lato-Black.ttf
  .storybook/assets/fonts/Lato-Black.woff
  .storybook/assets/fonts/Lato-Black.woff2
  .storybook/assets/fonts/Lato-BlackItalic.eot
  .storybook/assets/fonts/Lato-BlackItalic.ttf
  .storybook/assets/fonts/Lato-BlackItalic.woff
  .storybook/assets/fonts/Lato-BlackItalic.woff2
  .storybook/assets/fonts/Lato-Bold.eot
  .storybook/assets/fonts/Lato-Bold.ttf
  .storybook/assets/fonts/Lato-Bold.woff
  .storybook/assets/fonts/Lato-Bold.woff2
  .storybook/assets/fonts/Lato-BoldItalic.eot
  .storybook/assets/fonts/Lato-BoldItalic.ttf
  .storybook/assets/fonts/Lato-BoldItalic.woff
  .storybook/assets/fonts/Lato-BoldItalic.woff2
  .storybook/assets/fonts/Lato-Italic.eot
  .storybook/assets/fonts/Lato-Italic.ttf
  .storybook/assets/fonts/Lato-Italic.woff
  .storybook/assets/fonts/Lato-Italic.woff2
  .storybook/assets/fonts/Lato-Regular.eot
  .storybook/assets/fonts/Lato-Regular.ttf
  .storybook/assets/fonts/Lato-Regular.woff
  .storybook/assets/fonts/Lato-Regular.woff2
  .storybook/assets/fonts/OFL.txt
  .storybook/preview-head.html
  .storybook/preview.js
  .storybook/sageTheme.js
  .storybook/style/fonts.css
  .storybook/withThemeProvider.js
  docs/getting-started.stories.mdx
  package-lock.json
  package.json
  src/components/portal/__snapshots__/portal.spec.js.snap
  src/components/portrait/portrait-initials.component.js
  src/components/tile/tile.stories.mdx
  src/style/assets/carbon-icons-webfont.woff
  src/style/design-tokens/carbon-scoped-tokens-provider/__snapshots__/carbon-scoped-tokens-provider.component.spec.js.snap
  src/style/fonts.css
  src/style/global-style.js
  src/style/themes/aegean/__snapshots__/aegean-theme.spec.js.snap
  src/style/themes/mint/__snapshots__/mint-theme.spec.js.snap
  src/style/themes/none/__snapshots__/none.spec.js.snap
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5031 chore: amend withThemeProvider to load three SageUI variants
  .storybook/withThemeProvider.js
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#5039 chore(deps): update package-lock file
  package-lock.json
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#5032 fix(tabs): update background colour to improve contrast for selected Tab in alternate variant FE-5120
  src/components/tabs/__internal__/tab-title/tab-title.spec.js
  src/components/tabs/__internal__/tab-title/tab-title.style.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5058 docs(chromatic): remove webfontloader
  .storybook/withThemeProvider.js
  docs/getting-started.stories.mdx
  package-lock.json
  package.json
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#5060 fix(split-button): ensure prop type definition is exported from index.d.ts file
  src/components/split-button/index.d.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5025 test(message): add refactored tests for message component FE-4551
  cypress/fixtures/commonComponents/message.json
  cypress/integration/common/message.feature
  cypress/locators/message/index.js
  cypress/locators/message/locators.js
  cypress/support/step-definitions/message-steps.js
  src/components/message/message.test.js
Labels: Passed Review, Cypress, Squad Front End, message

#5028 test(draggable): refactor for cypress tests
  cypress/integration/common/draggable.feature
  cypress/support/step-definitions/draggable-steps.js
  src/components/draggable/draggable.test.js
Labels: Passed Review, Cypress, Squad Front End, draggable

#5069 docs: fix story rendering when switching view
  .storybook/withThemeProvider.js
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#5024 refactor(badge): convert to typescript
  src/components/badge/badge.component.tsx
  src/components/badge/badge.d.ts
  src/components/badge/badge.spec.tsx
  src/components/badge/badge.stories.mdx
  src/components/badge/badge.style.ts
  src/components/badge/index.d.ts
  src/components/badge/index.js
  src/components/badge/index.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5071 test(button-bar): add cypress tests
  src/components/button-bar/button-bar.test.js
Labels: Passed Review, Cypress, Squad Front End, button-bar

#5010 refactor(link): convert to typescript
  .eslintrc
  src/components/link/__snapshots__/link.spec.tsx.snap
  src/components/link/index.d.ts
  src/components/link/index.ts
  src/components/link/link.component.tsx
  src/components/link/link.config.ts
  src/components/link/link.d.ts
  src/components/link/link.spec.tsx
  src/components/link/link.style.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5075 fix(decimal): ensure id prop is passed to input FE-5127
  src/components/decimal/decimal.component.js
  src/components/decimal/decimal.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5076 docs(textarea): ensure children arg is not set as an object FE-5125
  src/components/textarea/textarea-test.stories.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5089 chore(deps): run npm audit fix to update some packages
  package-lock.json
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#5067 feat: consume Sage UI font from @sage/design-tokens package
  .storybook/preview-head.html
  docs/getting-started.stories.mdx
  src/style/fonts.css
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5083 test(text-editor): refactor cypress tests
  cypress/integration/common/textEditor.feature
  cypress/integration/common/textEditorWithOptionalCharacterLimit.feature
  cypress/locators/text-editor/index.js
  cypress/locators/text-editor/locators.js
  cypress/support/step-definitions/text-editor-steps.js
  src/components/accordion/accordion.test.js
  src/components/action-popover/action-popover.test.js
  src/components/alert/alert.test.js
  src/components/anchor-navigation/anchor-navigation.test.js
  src/components/app-wrapper/app-wrapper.test.js
  src/components/badge/badge.test.js
  src/components/button-bar/button-bar.test.js
  src/components/button/button.test.js
  src/components/card/card.test.js
  src/components/decimal/decimal.test.js
  src/components/draggable/draggable.test.js
  src/components/grouped-character/grouped-character.test.js
  src/components/message/message.test.js
  src/components/number/number.test.js
  src/components/text-editor/text-editor.test.js
Labels: Passed Review, Cypress, Squad Front End, text-editor

#5022 fix(simple-select): stop key filtering when command/control pressed
  src/components/select/simple-select/simple-select.component.js
  src/components/select/simple-select/simple-select.spec.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5097 test(carousel): refactor for cypress tests
  cypress/fixtures/commonComponents/carousel.json
  cypress/integration/common/carousel.feature
  cypress/locators/carousel/index.js
  cypress/locators/carousel/locators.js
  cypress/support/step-definitions/carousel-steps.js
  src/components/carousel/carousel.test.js
Labels: Pending Review, Cypress, Squad Front End, carousel

#5085 chore(dev-deps): update @sage/design-tokens
  package-lock.json
  package.json
  src/components/portal/__snapshots__/portal.spec.js.snap
  src/style/design-tokens/carbon-scoped-tokens-provider/__snapshots__/carbon-scoped-tokens-provider.component.spec.js.snap
  src/style/themes/aegean/__snapshots__/aegean-theme.spec.js.snap
  src/style/themes/mint/__snapshots__/mint-theme.spec.js.snap
  src/style/themes/none/__snapshots__/none.spec.js.snap
Labels: Pending Review, No QA Required, Pending UX QA, Squad Front End

#5006 fix(modal): resolve findDOMNode deprecation warning in React 17 projects
  .storybook/preview.js
  .storybook/with-portal-provider.js
  cypress/integration/common/confirm.feature
  cypress/integration/common/menu.feature
  src/components/advanced-color-picker/advanced-color-picker.spec.js
  src/components/duelling-picklist/picklist-item/picklist-item.component.js
  src/components/modal/modal.component.js
  src/components/pages/page/page.component.js
  src/components/popover-container/popover-container.component.js
  src/components/portal/__snapshots__/portal.spec.js.snap
  src/components/portal/portal.js
  src/components/portal/portal.spec.js
  src/components/show-edit-pod/show-edit-pod.component.js
  src/components/toast/toast.component.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End
