Repository Sage/carbon, pull requests merged in 2023-12, with the labels that each got.

#6458 test(search): convert tests from cypress to playwright - FE-6152
  cypress/components/menu/menu.cy.tsx
  cypress/components/search/search.cy.tsx
  cypress/locators/menu/index.js
  cypress/locators/menu/locators.js
  cypress/locators/search/index.js
  cypress/locators/search/locators.js
  playwright/components/search/index.ts
  src/components/search/components.test-pw.tsx
  src/components/search/search-test.stories.tsx
  src/components/search/search.pw.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6435 feat(dialog): add greyBackground prop
  src/components/dialog/components.test-pw.tsx
  src/components/dialog/dialog.component.tsx
  src/components/dialog/dialog.pw.tsx
  src/components/dialog/dialog.spec.tsx
  src/components/dialog/dialog.stories.mdx
  src/components/dialog/dialog.stories.tsx
  src/components/dialog/dialog.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6454 test(progress-tracker): convert tests to playwright - FE-6150
  cypress/components/progress-tracker/progress-tracker.cy.tsx
  playwright/components/progress-tracker/index.ts
  playwright/components/progress-tracker/locators.ts
  src/components/progress-tracker/components.test-pw.tsx
  src/components/progress-tracker/progress-tracker.component.tsx
  src/components/progress-tracker/progress-tracker.pw.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6217 Sage/DSY-1746 Button Toggle styling changes
  cypress/components/button-toggle/button-toggle.cy.tsx
  src/components/button-toggle/__snapshots__/button-toggle.spec.tsx.snap
  src/components/button-toggle/button-toggle-group/button-toggle-group.spec.tsx
  src/components/button-toggle/button-toggle-group/button-toggle-group.stories.tsx
  src/components/button-toggle/button-toggle-group/button-toggle-group.style.ts
  src/components/button-toggle/button-toggle.component.tsx
  src/components/button-toggle/button-toggle.spec.tsx
  src/components/button-toggle/button-toggle.stories.mdx
  src/components/button-toggle/button-toggle.stories.tsx
  src/components/button-toggle/button-toggle.style.ts
Labels: Passed QA, Passed UX QA, button, Design System Team, button minor

#6464 test(toast): convert cypress tests to playwright
  cypress/components/toast/toast.cy.tsx
  cypress/locators/toast/index.js
  cypress/locators/toast/locators.js
  src/components/toast/components.test-pw.tsx
  src/components/toast/toast-test.stories.tsx
  src/components/toast/toast.pw.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6445 refactor(toast): Decouple Toast component from Message component - FE-6228
  src/components/message/message-content/message-content.style.ts
  src/components/toast/toast.component.tsx
  src/components/toast/toast.spec.tsx
  src/components/toast/toast.stories.mdx
  src/components/toast/toast.style.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6424 chore: upgrade to node version 20 (FE-6252)
  .codesandbox/ci.json
  .eslintrc
  .github/workflows/chromatic-push.yml
  .github/workflows/chromatic.yml
  .github/workflows/ci.yml
  .github/workflows/cypress.yml
  .github/workflows/playwright.yml
  .github/workflows/semantic-commit-lint.yml
  .github/workflows/semantic-release.yml
  .github/workflows/storybook.yml
  .nvmrc
  cypress/docker-compose.yml
  docs/dev-environment-setup.md
  package-lock.json
  package.json
  playwright/components/anchor-navigation/index.ts
  playwright/components/drawer/index.ts
  playwright/components/global-header/index.ts
  playwright/components/grid/index.ts
  playwright/components/multi-action-button/index.ts
  playwright/components/navigation-bar/index.ts
  playwright/components/pill/index.ts
  playwright/components/split-button/index.ts
  playwright/components/step-sequence/index.ts
  scripts/check_node_version.mjs
  src/__internal__/sticky-footer/sticky-footer.spec.tsx
  src/components/popover-container/popover-container.spec.tsx
  src/components/select/utils/with-filter.spec.tsx
  src/hooks/__internal__/useCharacterCount/useCharacterCount.spec.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6467 test(date-range): convert tests to playwright - FE-6108
  cypress/components/date-range/date-range.cy.tsx
  cypress/locators/date-range/index.js
  cypress/locators/date-range/locators.js
  playwright/components/date-range/index.ts
  playwright/components/date-range/locators.ts
  playwright/support/helper.ts
  src/components/date-range/components.test-pw.tsx
  src/components/date-range/date-range.pw.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6474 fix(textbox): ensure no action is triggered when disabled or readOnly input or input icon is clicked FE-6293
  src/components/date/date.component.tsx
  src/components/select/select-textbox/select-textbox.component.tsx
  src/components/textbox/textbox.component.tsx
  src/components/textbox/textbox.pw.tsx
  src/components/textbox/textbox.spec.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6476 fix(filterable-select): ensure list does not reopen when user clicks option and openOnFocus prop set
  cypress/components/select/filterable-select/filterable-select.cy.tsx
  src/components/select/filterable-select/filterable-select.component.tsx
  src/components/select/filterable-select/filterable-select.spec.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6355 feat: add new file-input component
  playwright/components/file-input/index.ts
  playwright/components/file-input/locators.ts
  src/__internal__/utils/helpers/tags/tags-specs/tags-specs.ts
  src/components/file-input/__internal__/file-upload-status/file-upload-status.component.tsx
  src/components/file-input/__internal__/file-upload-status/file-upload-status.spec.tsx
  src/components/file-input/__internal__/file-upload-status/file-upload-status.style.tsx
  src/components/file-input/__internal__/file-upload-status/index.ts
  src/components/file-input/components.test-pw.tsx
  src/components/file-input/file-input-test.stories.tsx
  src/components/file-input/file-input.component.tsx
  src/components/file-input/file-input.pw.tsx
  src/components/file-input/file-input.spec.tsx
  src/components/file-input/file-input.stories.mdx
  src/components/file-input/file-input.stories.tsx
  src/components/file-input/file-input.style.tsx
  src/components/file-input/index.ts
  src/locales/en-gb.ts
  src/locales/locale.ts
  src/locales/pl-pl.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6466 test(menu): playwright refactor
  cypress/components/menu/menu.cy.tsx
  cypress/locators/menu/index.js
  playwright/components/menu/index.ts
  playwright/components/menu/locators.ts
  src/components/menu/component.test-pw.tsx
  src/components/menu/menu-test.stories.tsx
  src/components/menu/menu.pw.tsx
Labels: Pending Review, Passed QA, No UX QA Required, Squad Front End, menu, playwright

#6472 test(tooltip): add playwright tests
  cypress/components/tooltip/tooltip.cy.tsx
  cypress/locators/tooltip/index.js
  cypress/locators/tooltip/locators.js
  src/components/tooltip/components.test-pw.tsx
  src/components/tooltip/tooltip-test.stories.tsx
  src/components/tooltip/tooltip.pw.tsx
Labels: Passed Review, Passed QA, Squad Front End, tooltip, playwright

#6428 fix(select): ensure re-opening the select resets scroll position the top
  cypress/components/flat-table/flat-table.cy.tsx
  cypress/components/pager/pager.cy.tsx
  package-lock.json
  package.json
  src/__spec_helper__/index.ts
  src/__spec_helper__/mock-element-scrollto.ts
  src/__spec_helper__/select-test-utils.ts
  src/components/pager/pager.spec.tsx
  src/components/select/filterable-select/filterable-select.pw.tsx
  src/components/select/filterable-select/filterable-select.spec.tsx
  src/components/select/multi-select/multi-select.pw.tsx
  src/components/select/multi-select/multi-select.spec.tsx
  src/components/select/select-list/select-list.component.tsx
  src/components/select/select-list/select-list.spec.tsx
  src/components/select/simple-select/simple-select.pw.tsx
  src/components/select/simple-select/simple-select.spec.tsx
Labels: Pending Review, Passed QA, No UX QA Required, Squad Front End
