Repository Sage/carbon, pull requests merged in 2023-10, with the labels that each got.

#6339 docs: update dev environment setup docs
  docs/codebase-overview.md
  docs/dev-environment-setup.md
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#6284 feat(dialog): expose focus method of root dom node via a ref handle (FE-6176)
  src/components/dialog/dialog.component.tsx
  src/components/dialog/dialog.pw.tsx
  src/components/dialog/dialog.spec.tsx
  src/components/dialog/dialog.stories.mdx
  src/components/dialog/dialog.stories.tsx
  src/components/dialog/index.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6329 docs(sidebar): ensure content is not obscured due to new focus styling
  src/components/accordion/accordion-test.stories.tsx
  src/components/accordion/accordion.stories.tsx
  src/components/sidebar/sidebar-test.stories.tsx
  src/components/sidebar/sidebar.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6340 chore(playwright): increase timeout for github actions workflow
  .github/workflows/playwright.yml
  cypress/components/flat-table/flat-table.cy.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6333 fix(multi-action-button): update styling to ensure corrext spacing when child buttons have icons
  src/components/multi-action-button/__snapshots__/multi-action-button.spec.tsx.snap
  src/components/multi-action-button/multi-action-button.stories.mdx
  src/components/multi-action-button/multi-action-button.stories.tsx
  src/components/multi-action-button/multi-action-button.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6338 test(icon): add playwright tests
  cypress/components/dialog-full-screen/dialog-full-screen.cy.tsx
  cypress/components/icon/icon.cy.tsx
  src/components/icon/component.test-pw.tsx
  src/components/icon/icon-test.stories.tsx
  src/components/icon/icon.pw.tsx
Labels: Pending Review, Passed QA, Squad Front End, icon, playwright

#6332 test(confirm): playwright refactor
  cypress/components/confirm/confirm.cy.tsx
  cypress/locators/confirm/index.js
  cypress/locators/confirm/locators.js
  src/components/confirm/components.test-pw.tsx
  src/components/confirm/confirm-test.stories.tsx
  src/components/confirm/confirm.pw.tsx
Labels: Pending Review, Pending QA, No UX QA Required, Squad Front End, confirm, playwright

#6231 fix(textarea, textbox): improve character count accessibility and align with design system
  cypress/components/number/number.cy.tsx
  cypress/components/textarea/textarea.cy.tsx
  cypress/components/textbox/textbox.cy.tsx
  cypress/locators/index.js
  cypress/locators/locators.js
  cypress/locators/textarea/index.js
  cypress/locators/textarea/locators.js
  cypress/locators/textbox/index.js
  cypress/locators/textbox/locators.js
  src/__internal__/character-count/character-count.component.tsx
  src/__internal__/character-count/character-count.spec.tsx
  src/__internal__/character-count/character-count.style.ts
  src/components/date/date.component.tsx
  src/components/date/date.stories.mdx
  src/components/form/form.spec.tsx
  src/components/password/password.stories.tsx
  src/components/textarea/textarea-test.stories.tsx
  src/components/textarea/textarea.component.tsx
  src/components/textarea/textarea.spec.tsx
  src/components/textarea/textarea.stories.mdx
  src/components/textarea/textarea.stories.tsx
  src/components/textbox/textbox-test.stories.tsx
  src/components/textbox/textbox.component.tsx
  src/components/textbox/textbox.spec.tsx
  src/components/textbox/textbox.stories.mdx
  src/components/textbox/textbox.stories.tsx
  src/components/textbox/textbox.style.ts
  src/hooks/__internal__/useCharacterCount/useCharacterCount.spec.tsx
  src/hooks/__internal__/useCharacterCount/useCharacterCount.tsx
  src/hooks/__internal__/useDebounce/index.ts
  src/hooks/__internal__/useDebounce/useDebounce.spec.ts
  src/hooks/__internal__/useDebounce/useDebounce.ts
  src/locales/en-gb.ts
  src/locales/locale.ts
  src/locales/pl-pl.ts
Labels: Passed Review, Passed QA, No UX QA Required

#6342 test(definition-list): migrate tests from cypress to playwright
  cypress/components/definition-list/definition-list.cy.tsx
  src/components/definition-list/components.test-pw.tsx
  src/components/definition-list/definition-list-test.stories.tsx
  src/components/definition-list/definition-list.pw.tsx
Labels: Passed Review, Passed QA, Squad Front End, definition-list, playwright

#6348 fix(link): refactor styles to remove focus-within due to issues with JSDOM FE-6217
  cypress/components/menu/menu.cy.tsx
  src/components/card/card-footer/__snapshots__/card-footer.spec.tsx.snap
  src/components/link/__snapshots__/link.spec.tsx.snap
  src/components/link/link-test.stories.tsx
  src/components/link/link.component.tsx
  src/components/link/link.style.ts
  src/components/menu/menu-item/menu-item.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6360 docs(dialog): update explanation on refocusing
  src/components/dialog/dialog.stories.mdx
Labels: Pending Review, No QA Required, No UX QA Required

#6350 fix(pager): make top corners rounded (FE-6234)
  cypress/components/pager/pager.cy.tsx
  src/components/flat-table/flat-table.spec.tsx
  src/components/flat-table/flat-table.style.ts
  src/components/pager/pager-test.stories.tsx
  src/components/pager/pager.spec.tsx
  src/components/pager/pager.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6370 docs(carbon-provider): typo fix
  src/components/carbon-provider/carbon-provider.stories.mdx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6357 test(profile): add playwright tests
  cypress/components/profile/profile.cy.tsx
  playwright/components/profile/index.ts
  playwright/components/profile/locators.ts
  src/components/profile/component.test-pw.tsx
  src/components/profile/profile.pw.tsx
Labels: Pending QA, Squad Front End, profile, playwright

#6364 test(decimal): refactor cypress to playwright
  cypress/components/decimal/decimal.cy.tsx
  playwright/components/index.ts
  playwright/components/textbox/index.ts
  playwright/components/textbox/locators.ts
  src/components/decimal/components.test-pw.tsx
  src/components/decimal/decimal.pw.tsx
Labels: Pending Review, Passed QA, No UX QA Required, Squad Front End, decimal, playwright

#6358 test(action-popover): convert cypress tests to playwright
  .gitignore
  cypress/components/action-popover/action-popover.cy.tsx
  cypress/locators/action-popover/index.js
  cypress/locators/action-popover/locators.js
  playwright/components/action-popover/index.ts
  playwright/download-test/example.txt
  playwright/support/helper.ts
  src/components/action-popover/action-popover.pw.tsx
  src/components/action-popover/components.test-pw.tsx
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#6376 docs(button): button data- tags doc fix
  src/components/button/button.component.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6349 fix(link): ensure Icon in component has inline display property to respect dimensions of the parent
  cypress/components/link/link.cy.tsx
  src/components/link/link-test.stories.tsx
  src/components/link/link.spec.tsx
  src/components/link/link.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6345 feat(tile): refactor component to support more flexible composition of children FE-5681
  cypress/components/tile/tile.cy.tsx
  cypress/locators/tile/index.js
  cypress/locators/tile/locators.js
  playwright/support/helper.ts
  src/__internal__/utils/helpers/tags/tags-specs/index.ts
  src/__internal__/utils/helpers/tags/tags-specs/tags-specs.ts
  src/components/definition-list/definition-list-test.stories.tsx
  src/components/detail/detail.stories.tsx
  src/components/heading/heading.stories.tsx
  src/components/tile/__internal__/compute-content-padding.ts
  src/components/tile/__internal__/tile-context.ts
  src/components/tile/components.test-pw.tsx
  src/components/tile/index.ts
  src/components/tile/tile-content/index.ts
  src/components/tile/tile-content/tile-content.component.tsx
  src/components/tile/tile-content/tile-content.spec.tsx
  src/components/tile/tile-content/tile-content.style.ts
  src/components/tile/tile-footer/tile-footer.component.tsx
  src/components/tile/tile-footer/tile-footer.spec.tsx
  src/components/tile/tile-test.stories.tsx
  src/components/tile/tile.component.tsx
  src/components/tile/tile.pw.tsx
  src/components/tile/tile.spec.tsx
  src/components/tile/tile.stories.mdx
  src/components/tile/tile.stories.tsx
  src/components/tile/tile.style.ts
  src/components/vertical-divider/vertical-divider.stories.tsx
  src/style/utils/filter-styled-system-padding-props.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6366 test(fieldset): playwright refactor
  cypress/components/fieldset/fieldset.cy.tsx
  cypress/locators/fieldset/index.js
  cypress/locators/fieldset/locators.js
  src/components/fieldset/components.test-pw.tsx
  src/components/fieldset/fieldset-test.stories.tsx
  src/components/fieldset/fieldset.pw.tsx
Labels: Pending Review, Passed QA, No UX QA Required, Squad Front End, fieldset, playwright

#6372 test(playwright): more flaky tests
  src/components/batch-selection/batch-selection.pw.tsx
  src/components/button/button.pw.tsx
  src/components/dialog/dialog.pw.tsx
Labels: Passed QA, No UX QA Required, Squad Front End, batch-selection, button, dialog, playwright

#6377 test(navigation-bar): playwright refactor
  cypress/components/navigation-bar/navigation-bar.cy.tsx
  playwright/components/navigation-bar/index.ts
  playwright/components/navigation-bar/locators.ts
  src/components/navigation-bar/components.test-pw.tsx
  src/components/navigation-bar/navigation-bar-test.stories.tsx
  src/components/navigation-bar/navigation-bar.pw.tsx
  src/components/navigation-bar/navigation-bar.stories.mdx
Labels: Pending Review, Passed QA, No UX QA Required, Squad Front End, navigation-bar, playwright

#6387 chore: update text editor link preview story to prevent previews being added on focus
  src/components/text-editor/text-editor.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6363 fix(textarea, textbox): ensure inputHint and labelHelp props do not render two seperate DOM elements
  src/components/decimal/decimal.stories.mdx
  src/components/decimal/decimal.stories.tsx
  src/components/grouped-character/grouped-character.stories.mdx
  src/components/grouped-character/grouped-character.stories.tsx
  src/components/number/number.stories.mdx
  src/components/number/number.stories.tsx
  src/components/password/password.stories.mdx
  src/components/password/password.stories.tsx
  src/components/textarea/textarea.component.tsx
  src/components/textarea/textarea.spec.tsx
  src/components/textarea/textarea.stories.mdx
  src/components/textarea/textarea.stories.tsx
  src/components/textbox/textbox.component.tsx
  src/components/textbox/textbox.spec.tsx
  src/components/textbox/textbox.stories.mdx
  src/components/textbox/textbox.stories.tsx
  src/components/textbox/textbox.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6379 docs(carousel): deprecation message for docs
  src/components/carousel/carousel.component.tsx
  src/components/carousel/carousel.spec.tsx
  src/components/carousel/carousel.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required

#6388 feat(confirm): make data tag props available on cancel and confirm buttons - FE-6251
  src/components/confirm/confirm.component.tsx
  src/components/confirm/confirm.pw.tsx
  src/components/confirm/confirm.spec.tsx
  src/components/confirm/confirm.stories.mdx
  src/components/confirm/confirm.stories.tsx
Labels: Passed Review, Pending QA, No UX QA Required, Squad Front End

#6400 Fix animation issues pw
  playwright/support/helper.ts
  src/components/dialog/dialog.pw.tsx
  src/components/drawer/__snapshots__/drawer.spec.tsx.snap
  src/components/drawer/drawer.component.tsx
  src/components/drawer/drawer.pw.tsx
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#6396 chore: address various spelling mistakes and some code formatting
  cypress/components/flat-table/flat-table.cy.tsx
  cypress/components/grouped-character/grouped-character.cy.tsx
  cypress/components/menu/menu.cy.tsx
  cypress/components/multi-action-button/multi-action-button.cy.tsx
  cypress/components/number/number.cy.tsx
  cypress/components/pager/pager.cy.tsx
  cypress/components/password/password.cy.tsx
  cypress/components/switch/switch.cy.tsx
  cypress/components/tooltip/tooltip.cy.tsx
  cypress/components/vertical-menu/vertical-menu.cy.tsx
  playwright/components/step-sequence/index.ts
  src/components/action-popover/action-popover.pw.tsx
  src/components/action-popover/action-popover.stories.tsx
  src/components/button-bar/button-bar.spec.tsx
  src/components/button-minor/button-minor.pw.tsx
  src/components/button-toggle/button-toggle.spec.tsx
  src/components/flat-table/flat-table-test.stories.tsx
  src/components/loader/loader.pw.tsx
  src/components/menu/menu.spec.tsx
  src/components/progress-tracker/progress-tracker.spec.tsx
  src/components/text-editor/text-editor.spec.tsx
  src/components/tooltip/tooltip.stories.mdx
  src/components/tooltip/tooltip.stories.tsx
  src/hooks/__internal__/useCharacterCount/useCharacterCount.spec.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End
