Repository Sage/carbon, pull requests merged in 2023-04, with the labels that each got.

#5895 Sage/DSY-2333(FE-5717): ShowEditPod Storybook Update
  src/components/show-edit-pod/show-edit-pod.component.js
  src/components/show-edit-pod/show-edit-pod.spec.js
  src/components/show-edit-pod/show-edit-pod.stories.mdx
Labels: Passed Review, Passed QA, Passed UX QA

#5651 Sage/DSY-1757 Breadcrumbs Component (FE-5562)
  cypress/locators/breadcrumbs/index.js
  cypress/locators/breadcrumbs/locators.js
  src/components/breadcrumbs/breadcrumbs-test.stories.tsx
  src/components/breadcrumbs/breadcrumbs.component.tsx
  src/components/breadcrumbs/breadcrumbs.spec.tsx
  src/components/breadcrumbs/breadcrumbs.stories.mdx
  src/components/breadcrumbs/breadcrumbs.stories.tsx
  src/components/breadcrumbs/breadcrumbs.style.ts
  src/components/breadcrumbs/breadcrumbs.test.js
  src/components/breadcrumbs/crumb/crumb.component.tsx
  src/components/breadcrumbs/crumb/crumb.spec.tsx
  src/components/breadcrumbs/crumb/crumb.style.ts
  src/components/breadcrumbs/crumb/index.ts
  src/components/breadcrumbs/index.ts
  src/locales/en-gb.ts
  src/locales/locale.ts
  src/locales/pl-pl.ts
Labels: Passed Review, Passed QA, Passed UX QA

#5951 test(inline-inputs): add accessibility tests
  cypress/support/accessibility/a11y-utils.js
  src/components/inline-inputs/inline-inputs.test.js
Labels: Pending Review, Pending QA, Accessibility, Cypress, inline-inputs

#5900 fix(advanced-color-picker): add visually hidden description list to describe selected color
  cypress/locators/advanced-color-picker/index.js
  cypress/locators/advanced-color-picker/locators.js
  src/components/advanced-color-picker/advanced-color-picker.component.tsx
  src/components/advanced-color-picker/advanced-color-picker.spec.tsx
  src/components/advanced-color-picker/advanced-color-picker.stories.mdx
  src/components/advanced-color-picker/advanced-color-picker.stories.tsx
  src/components/advanced-color-picker/advanced-color-picker.style.ts
  src/components/advanced-color-picker/advanced-color-picker.test.js
  src/components/definition-list/dl.component.tsx
  src/locales/en-gb.ts
  src/locales/locale.ts
  src/locales/pl-pl.ts
  src/style/utils/visually-hidden.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5934 feat(pager): surface interactivePageNumber prop to ensure selecting page number is optional
  cypress/locators/pager/index.js
  cypress/locators/pager/locators.js
  src/components/pager/__internal__/pager-navigation.component.tsx
  src/components/pager/pager.component.tsx
  src/components/pager/pager.spec.tsx
  src/components/pager/pager.stories.mdx
  src/components/pager/pager.stories.tsx
  src/components/pager/pager.style.tsx
  src/components/pager/pager.test.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5957 docs(alert): fix not showing code example - FE-5739
  src/components/alert/alert.stories.mdx
  src/components/alert/alert.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5956 test(radio-button): add accessibility tests
  cypress/support/accessibility/a11y-utils.js
  src/components/radio-button/radio-button-test.stories.tsx
  src/components/radio-button/radiobutton.test.js
Labels: Passed Review, Passed QA, Accessibility, Cypress, Squad Front End, radio-button

#5948 test(multi-select): add test to cover new validation triggered in a custom onChange function - FE-5324
  src/components/select/multi-select/multi-select.test.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5960 test(tile): add accesibility tests
  cypress/support/accessibility/a11y-utils.js
  src/components/tile-select/tile-select-test.stories.tsx
  src/components/tile-select/tile-select.test.js
  src/components/tile/tile-test.stories.tsx
  src/components/tile/tile.test.js
Labels: Passed Review, Passed QA, Accessibility, Squad Front End, tile-select, tile

#5954 fix(switch): fix styling defect caused by box-sizing border-box css - FE-5738
  src/components/switch/__internal__/__snapshots__/switch-slider.spec.tsx.snap
  src/components/switch/__internal__/switch-slider.style.ts
  src/components/switch/switch.spec.tsx
  src/components/switch/switch.style.ts
  src/components/switch/switch.test.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5961 docs: correct syntax for includeStories param
  src/components/action-popover/action-popover-test.stories.tsx
  src/components/alert/alert-test.stories.tsx
  src/components/anchor-navigation/anchor-navigation-test.stories.tsx
  src/components/box/box-test.stories.tsx
  src/components/breadcrumbs/breadcrumbs-test.stories.tsx
  src/components/button-minor/button-minor-test.stories.tsx
  src/components/button-toggle-group/button-toggle-group-test.stories.tsx
  src/components/button-toggle/button-toggle-test.stories.tsx
  src/components/card/card-test.stories.tsx
  src/components/carousel/carousel-test.stories.tsx
  src/components/checkbox/checkbox-test.stories.tsx
  src/components/confirm/confirm-test.stories.tsx
  src/components/content/content-test.stories.tsx
  src/components/decimal/decimal-test.stories.tsx
  src/components/detail/detail-test.stories.tsx
  src/components/dialog-full-screen/dialog-full-screen-test.stories.tsx
  src/components/dialog/dialog-test.stories.tsx
  src/components/drawer/drawer-test.stories.tsx
  src/components/duelling-picklist/duelling-picklist-test.stories.tsx
  src/components/fieldset/fieldset-test.stories.tsx
  src/components/form/form-test.stories.tsx
  src/components/grouped-character/grouped-character-test.stories.tsx
  src/components/heading/heading-test.stories.mdx
  src/components/heading/heading-test.stories.tsx
  src/components/hr/hr.stories.tsx
  src/components/link-preview/link-preview-test.stories.tsx
  src/components/link/link-test.stories.tsx
  src/components/loader-bar/loader-bar-test.stories.tsx
  src/components/loader/loader-test.stories.tsx
  src/components/multi-action-button/multi-action-button-test.stories.tsx
  src/components/note/note-test.stories.tsx
  src/components/number/number-test.stories.tsx
  src/components/number/number-validation-test.stories.tsx
  src/components/numeral-date/numeral-date-test.stories.tsx
  src/components/pager/pager-test.stories.tsx
  src/components/pages/pages-test.stories.tsx
  src/components/pod/pod-test.stories.tsx
  src/components/portrait/portrait-test.stories.tsx
  src/components/profile/profile-test.stories.tsx
  src/components/search/search-test.stories.tsx
  src/components/settings-row/settings-row-test.stories.tsx
  src/components/sidebar/sidebar-test.stories.tsx
  src/components/simple-color-picker/simple-color-picker-test.stories.tsx
  src/components/step-sequence/step-sequence-test.stories.tsx
  src/components/switch/switch-test.stories.tsx
  src/components/textarea/textarea-test.stories.tsx
  src/components/tile-select/tile-select-test.stories.tsx
  src/components/tile/tile-test.stories.tsx
  src/components/vertical-divider/vertical-divider-test.stories.tsx
Labels: Passed Review, Passed QA, Docs, Squad Front End

#5950 feat(vertical-menu): add default open state to menu item
  src/components/vertical-menu/vertical-menu-item.component.tsx
  src/components/vertical-menu/vertical-menu-item.spec.tsx
  src/components/vertical-menu/vertical-menu.stories.tsx
  src/components/vertical-menu/vertical-menu.test.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5964 chore: update crypto-js to latest version (FE-5748)
  package-lock.json
  package.json
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#5941 chore: deprecation warning for uncontrolled inputs - FE-5331
  src/__internal__/input/input.component.tsx
  src/components/advanced-color-picker/advanced-color-picker.component.tsx
  src/components/advanced-color-picker/advanced-color-picker.spec.tsx
  src/components/button-toggle/button-toggle.component.tsx
  src/components/button-toggle/button-toggle.spec.tsx
  src/components/checkbox/checkbox.component.tsx
  src/components/checkbox/checkbox.spec.tsx
  src/components/decimal/decimal.component.tsx
  src/components/decimal/decimal.spec.tsx
  src/components/grouped-character/grouped-character.component.tsx
  src/components/grouped-character/grouped-character.spec.tsx
  src/components/number/number.component.tsx
  src/components/number/number.spec.tsx
  src/components/numeral-date/numeral-date.component.tsx
  src/components/numeral-date/numeral-date.spec.tsx
  src/components/radio-button/radio-button-group.component.tsx
  src/components/radio-button/radio-button.spec.tsx
  src/components/radio-button/radio-button.style.ts
  src/components/search/search.component.tsx
  src/components/search/search.spec.tsx
  src/components/select/filterable-select/filterable-select.component.js
  src/components/select/filterable-select/filterable-select.spec.js
  src/components/select/multi-select/multi-select.component.js
  src/components/select/multi-select/multi-select.spec.js
  src/components/select/simple-select/simple-select.component.js
  src/components/select/simple-select/simple-select.spec.js
  src/components/simple-color-picker/simple-color-picker.component.tsx
  src/components/simple-color-picker/simple-color-picker.spec.tsx
  src/components/switch/switch.component.tsx
  src/components/switch/switch.spec.tsx
  src/components/textarea/textarea.component.tsx
  src/components/textarea/textarea.spec.tsx
  src/components/textbox/textbox.component.tsx
  src/components/textbox/textbox.spec.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5952 fix(message): add conditional padding based on the showCloseIcon props truth value
  cypress/locators/message/index.js
  cypress/locators/message/locators.js
  src/components/message/message-content/__snapshots__/message-content.spec.tsx.snap
  src/components/message/message-content/message-content.component.tsx
  src/components/message/message-content/message-content.spec.tsx
  src/components/message/message-content/message-content.style.ts
  src/components/message/message.component.tsx
  src/components/message/message.stories.mdx
  src/components/message/message.stories.tsx
  src/components/message/message.test.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5965 test(hr): add accessibility tests
  cypress/support/accessibility/a11y-utils.js
  src/components/hr/hr.test.js
Labels: Passed Review, Passed QA, Cypress, Squad Front End, hr

#5966 test(simple-color-picker): add accessibility tests
  cypress/support/accessibility/a11y-utils.js
  src/components/simple-color-picker/simple-color-picker.test.js
Labels: Passed Review, Passed QA, Accessibility, Cypress, Squad Front End, simple-color-picker

#5969 chore: update node start script to include cross-env to fix windows setups
  package.json
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5967 test(text-editor): add accessibility tests
  cypress/support/accessibility/a11y-utils.js
  src/components/text-editor/text-editor.test.js
Labels: Pending Review, Passed QA, Accessibility, Cypress, text-editor

#5970 test(typography): add cypress tests
  .github/workflows/cypress.yml
  cypress/components/typography/typography.test.js
  cypress/e2e/accessibility/a11y-fifth-part.test.ts
  cypress/e2e/accessibility/a11y-fourth-part.test.ts
  cypress/e2e/accessibility/a11y-sixth-part.test.ts
  cypress/support/accessibility/a11y-utils.ts
  src/components/typography/typography-test.stories.tsx
Labels: Passed Review, Passed QA, Accessibility, Cypress, Squad Front End, typography

#5975 test(icon-button): add accessibility tests
  cypress/components/icon-button/icon-button.test.js
  src/components/icon-button/icon-button-test.stories.tsx
Labels: Pending QA, Accessibility, Cypress, Squad Front End, icon-button

#5958 test(tabs): add accessibility tests
  cypress/components/tabs/tabs.test.js
  cypress/support/accessibility/a11y-utils.ts
  src/components/tabs/tabs-test.stories.tsx
Labels: Pending Review, Pending QA, Accessibility, Cypress, tabs

#5974 feat: add white-space: nowrap CSS property to visually hidden class
  src/style/utils/visually-hidden.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5973 test(tooltip): add accessibility tests
  cypress/components/tooltip/tooltip.test.js
  cypress/support/accessibility/a11y-utils.ts
  src/components/tooltip/tooltip-test.stories.mdx
  src/components/tooltip/tooltip-test.stories.tsx
Labels: Passed Review, Pending QA, Accessibility, Cypress, Squad Front End, tooltip

#5978 test(accessibility): add terminal log
  cypress.config.ts
  cypress/components/badge/badge.test.js
  cypress/support/commands.ts
Labels: Passed Review, Passed QA, Accessibility, Cypress, Squad Front End

#5976 fix(link): ensure button has a type when used - FE-5706
  src/components/form/form-test.stories.tsx
  src/components/link/link.component.tsx
  src/components/pager/__internal__/pager-navigation-link.component.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5962 test(split button): refactor cypress accessibility tests
  cypress/components/split-button/split-button.test.js
  cypress/support/accessibility/a11y-utils.ts
  src/components/split-button/split-button-test.stories.tsx
Labels: Pending Review, Pending QA, Cypress, Squad Front End, split-button

#5977 test(tabs): fix cypress test returning false positive result
  cypress/components/tabs/tabs.test.js
  src/components/tabs/tabs-test.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5971 feat(minor-button): add position: absolute property to icon when component is icon only
  cypress/components/button-minor/button-minor.test.js
  src/components/button-minor/button-minor.spec.tsx
  src/components/button-minor/button-minor.style.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End
