Repository Sage/carbon, pull requests merged in 2023-11, with the labels that each got.

#6382 fix: remove resize observer error
  cypress/components/global-header/global-header.cy.tsx
  cypress/components/menu/menu.cy.tsx
  src/components/global-header/global-header-test.stories.tsx
  src/components/global-header/global-header.spec.tsx
  src/components/navigation-bar/components.test-pw.tsx
  src/components/navigation-bar/fixed-navigation-bar-context.spec.tsx
  src/components/navigation-bar/fixed-navigation-bar.context.tsx
  src/components/navigation-bar/navigation-bar-test.stories.tsx
  src/components/navigation-bar/navigation-bar.component.tsx
  src/components/navigation-bar/navigation-bar.pw.tsx
  src/components/navigation-bar/navigation-bar.spec.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6369 test(icon-button): add playwright tests
  cypress/components/icon-button/icon-button.cy.tsx
  playwright/components/index.ts
  src/components/icon-button/component.test-pw.tsx
  src/components/icon-button/icon-button-test.stories.tsx
  src/components/icon-button/icon-button.pw.tsx
Labels: Passed QA, Squad Front End, icon-button, playwright

#6380 test(duelling-picklist): playwright refactor
  cypress/components/duelling-picklist/duelling-picklist.cy.tsx
  cypress/locators/duelling-picklist/index.js
  cypress/locators/duelling-picklist/locators.js
  playwright/components/search/index.ts
  playwright/components/search/locators.ts
  src/components/duelling-picklist/components.test-pw.tsx
  src/components/duelling-picklist/duelling-picklist-test.stories.tsx
  src/components/duelling-picklist/duelling-picklist.pw.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End, duelling-picklist, playwright

#6405 fix(action-popover): fix issue with stories not rendering in storybook - FE-6264
  src/components/action-popover/action-popover.stories.mdx
Labels: Pending Review, Passed QA, No UX QA Required, Squad Front End

#6362 feat(message): remove role of status - FE-5891
  src/components/message/message.component.tsx
  src/components/message/message.stories.mdx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6368 fix(date): add aria labels to picker navigation buttons and fix other accessibility issues FE-4075
  cypress/components/date/date.cy.tsx
  cypress/support/helper.ts
  src/components/date-range/date-range.stories.mdx
  src/components/date-range/date-range.stories.tsx
  src/components/date/__internal__/date-picker/__snapshots__/date-picker.spec.tsx.snap
  src/components/date/__internal__/date-picker/date-picker.component.tsx
  src/components/date/__internal__/date-picker/date-picker.spec.tsx
  src/components/date/__internal__/date-picker/day-picker.style.ts
  src/components/date/__internal__/navbar/navbar.component.tsx
  src/components/date/__internal__/navbar/navbar.spec.tsx
  src/components/date/date-test.stories.tsx
  src/components/date/date.component.tsx
  src/components/date/date.spec.tsx
  src/components/date/date.stories.mdx
  src/components/date/date.stories.tsx
  src/locales/en-gb.ts
  src/locales/locale.ts
  src/locales/pl-pl.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6375 fix(loaderbar): loaderBar height fix
  src/components/loader-bar/loader-bar-test.stories.tsx
  src/components/loader-bar/loader-bar.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6398 fix(badge): change the position and size of counter
  src/components/badge/badge.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6371 fix(button): correct the width and height of icons inside buttons
  src/components/button-bar/button-bar.pw.tsx
  src/components/button/__snapshots__/button.spec.tsx.snap
  src/components/button/button.spec.tsx
  src/components/button/button.style.ts
  src/components/multi-action-button/__snapshots__/multi-action-button.spec.tsx.snap
  src/components/select/list-action-button/__snapshots__/list-action-button.spec.tsx.snap
Labels: Passed Review, Passed QA, Passed UX QA, Squad Experience Platform

#6381 fix(textarea, textbox): display icon when component is disabled or readOnly
  cypress/components/date/date.cy.tsx
  cypress/components/select/filterable-select/filterable-select.cy.tsx
  cypress/components/select/multi-select/multi-select.cy.tsx
  cypress/components/select/simple-select/simple-select.cy.tsx
  cypress/components/textarea/textarea.cy.tsx
  cypress/components/textbox/textbox.cy.tsx
  src/__internal__/input-icon-toggle/input-icon-toggle.component.tsx
  src/__internal__/input-icon-toggle/input-icon-toggle.spec.tsx
  src/__internal__/input-icon-toggle/input-icon-toggle.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6341 Playwright refactor textbox
  cypress/components/textbox/textbox.cy.tsx
  playwright/components/index.ts
  playwright/components/locators.ts
  playwright/components/textbox/index.ts
  src/components/textbox/components.test-pw.tsx
  src/components/textbox/textbox-test.stories.tsx
  src/components/textbox/textbox.pw.tsx
Labels: Pending Review, Passed QA, No QA Required, No UX QA Required, Squad Front End

#6401 feat(icon): 4 icons added to the icon font
  src/components/icon/__snapshots__/icon-unicodes.spec.js.snap
  src/components/icon/fonts/carbon-icons-webfont.woff
  src/components/icon/icon-config.ts
  src/components/icon/icon-type.ts
  src/components/icon/icon-unicodes.js
  src/style/assets/carbon-icons-webfont.woff
Labels: Passed Review, Passed QA, Passed UX QA, Squad Experience Platform

#6392 fix(multi-action-button, split-button): fix aria role
  cypress/components/multi-action-button/multi-action-button.cy.tsx
  cypress/components/split-button/split-button.cy.tsx
  src/components/button/button.component.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6391 feat(toast): toast vertical align prop
  cypress/components/toast/toast.cy.tsx
  src/components/toast/toast-test.stories.tsx
  src/components/toast/toast.component.tsx
  src/components/toast/toast.spec.tsx
  src/components/toast/toast.stories.mdx
  src/components/toast/toast.stories.tsx
  src/components/toast/toast.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6409 test(global-header): playwright refactor
  cypress/components/global-header/global-header.cy.tsx
  playwright/components/global-header/index.ts
  playwright/components/global-header/locators.ts
  src/components/global-header/component.test-pw.tsx
  src/components/global-header/global-header-test.stories.tsx
  src/components/global-header/global-header.pw.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End, playwright

#6395 feat(select): add selectionConfirmed property to event emitted on change
  cypress/components/select/filterable-select/filterable-select.cy.tsx
  cypress/components/select/multi-select/multi-select.cy.tsx
  cypress/components/select/simple-select/simple-select.cy.tsx
  src/components/select/filterable-select/filterable-select-test.stories.tsx
  src/components/select/filterable-select/filterable-select.component.tsx
  src/components/select/filterable-select/filterable-select.spec.tsx
  src/components/select/filterable-select/filterable-select.stories.mdx
  src/components/select/filterable-select/filterable-select.stories.tsx
  src/components/select/index.ts
  src/components/select/multi-select/multi-select-test.stories.tsx
  src/components/select/multi-select/multi-select.component.tsx
  src/components/select/multi-select/multi-select.spec.tsx
  src/components/select/option/option.component.tsx
  src/components/select/select-list/select-list.component.tsx
  src/components/select/select-list/select-list.spec.tsx
  src/components/select/select-textbox/select-textbox.component.tsx
  src/components/select/simple-select/index.ts
  src/components/select/simple-select/simple-select-test.stories.tsx
  src/components/select/simple-select/simple-select.component.tsx
  src/components/select/simple-select/simple-select.spec.tsx
  src/components/select/simple-select/simple-select.stories.mdx
  src/components/select/simple-select/simple-select.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6390 test(pill): add playwright tests
  cypress/components/pill/pill.cy.tsx
  playwright/components/pill/index.ts
  playwright/components/pill/locators.ts
  src/components/pill/components.test-pw.tsx
  src/components/pill/pill.pw.tsx
Labels: Pending Review, Passed QA, Squad Front End, pill, playwright

#6385 fix(popover-container): ensure that component is closed when Esc key is pressed - FE-6072
  cypress/components/popover-container/popover-container.cy.tsx
  src/components/popover-container/popover-container.component.tsx
  src/components/popover-container/popover-container.spec.tsx
  src/components/popover-container/popover-container.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6328 fix(switch): fix alignment issue with component when no new validation is applied
  src/components/switch/switch.component.tsx
  src/components/switch/switch.spec.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6426 chore(dependencies): remove wait-on package - FE-6272
  package-lock.json
  package.json
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6421 test(loader-bar): playwright refactor
  cypress/components/loader-bar/loader-bar.cy.tsx
  cypress/locators/loader-bar/index.js
  cypress/locators/loader-bar/locators.js
  src/components/loader-bar/component.test-pw.tsx
  src/components/loader-bar/loader-bar-test.stories.tsx
  src/components/loader-bar/loader-bar.pw.tsx
Labels: Pending Review, Passed QA, No UX QA Required, Squad Front End, loader-bar, playwright

#6413 test(grouped-character): playwright refactor
  cypress/components/grouped-character/grouped-character.cy.tsx
  src/components/grouped-character/components.test-pw.tsx
  src/components/grouped-character/grouped-character-test.stories.tsx
  src/components/grouped-character/grouped-character.pw.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End, grouped-character, playwright

#6406 test(form): playwright refactor
  cypress/components/form/form.cy.tsx
  cypress/locators/form/index.js
  cypress/locators/form/locators.js
  playwright/components/pages/index.ts
  playwright/components/pages/locators.ts
  src/components/form/components.test-pw.tsx
  src/components/form/form-test.stories.tsx
  src/components/form/form.pw.tsx
Labels: Pending Review, Pending QA, No UX QA Required, Squad Front End, form, playwright

#6416 docs(dialog-full-screen): address invalid DOM nesting in stories - FE-5025
  src/components/dialog-full-screen/components.test-pw.tsx
  src/components/dialog-full-screen/dialog-full-screen.pw.tsx
  src/components/dialog-full-screen/dialog-full-screen.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6417 fix/feat(multi-action-button, split-button): remove unnecessary aria-label for MultiActionButton and provide aria-label props/support on SplitButton
  src/components/multi-action-button/__snapshots__/multi-action-button.spec.tsx.snap
  src/components/multi-action-button/multi-action-button.component.tsx
  src/components/split-button/split-button.component.tsx
  src/components/split-button/split-button.spec.tsx
  src/locales/en-gb.ts
  src/locales/locale.ts
  src/locales/pl-pl.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6373 feat(portrait, profile): align with design system and reduce code complexity
  playwright/components/profile/index.ts
  playwright/components/profile/locators.ts
  src/components/portrait/portrait-gravatar.component.tsx
  src/components/portrait/portrait-gravatar.spec.tsx
  src/components/portrait/portrait-initials.component.tsx
  src/components/portrait/portrait-initials.spec.tsx
  src/components/portrait/portrait.component.tsx
  src/components/portrait/portrait.config.ts
  src/components/portrait/portrait.pw.tsx
  src/components/portrait/portrait.spec.tsx
  src/components/portrait/portrait.stories.tsx
  src/components/portrait/portrait.style.tsx
  src/components/profile/component.test-pw.tsx
  src/components/profile/profile-test.stories.tsx
  src/components/profile/profile.component.tsx
  src/components/profile/profile.config.ts
  src/components/profile/profile.pw.tsx
  src/components/profile/profile.spec.tsx
  src/components/profile/profile.stories.mdx
  src/components/profile/profile.stories.tsx
  src/components/profile/profile.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6423 fix(crumb): ensure LinkProps are correctly extended so component has the correct interface
  src/components/breadcrumbs/crumb/crumb.component.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6447 chore(ci): remove manual trigger for playwright and cypress workflows (FE-6236)
  .github/workflows/chromatic.yml
  .github/workflows/cypress.yml
  .github/workflows/forked-ci.yml
  .github/workflows/playwright.yml
  .github/workflows/pr.yml
  cypress/README.md
  cypress/components/popover-container/popover-container.cy.tsx
  playwright/README.md
Labels: Passed Review, No QA Required, No UX QA Required

#6412 feat: add support for manually overriding stacking order of modals FE-6259
  cypress/components/sidebar/sidebar.cy.tsx
  cypress/components/toast/toast.cy.tsx
  src/components/alert/alert.component.tsx
  src/components/alert/alert.pw.tsx
  src/components/alert/components.test-pw.tsx
  src/components/confirm/components.test-pw.tsx
  src/components/confirm/confirm.component.tsx
  src/components/confirm/confirm.pw.tsx
  src/components/dialog-full-screen/components.test-pw.tsx
  src/components/dialog-full-screen/dialog-full-screen.component.tsx
  src/components/dialog-full-screen/dialog-full-screen.pw.tsx
  src/components/dialog-full-screen/dialog-full-screen.stories.mdx
  src/components/dialog-full-screen/dialog-full-screen.stories.tsx
  src/components/dialog/components.test-pw.tsx
  src/components/dialog/dialog.component.tsx
  src/components/dialog/dialog.pw.tsx
  src/components/dialog/dialog.stories.mdx
  src/components/dialog/dialog.stories.tsx
  src/components/modal/__internal__/modal-manager.spec.ts
  src/components/modal/__internal__/modal-manager.ts
  src/components/modal/modal.component.tsx
  src/components/modal/modal.spec.tsx
  src/components/modal/modal.style.ts
  src/components/sidebar/sidebar-test.stories.tsx
  src/components/sidebar/sidebar.component.tsx
  src/components/sidebar/sidebar.stories.mdx
  src/components/sidebar/sidebar.stories.tsx
  src/components/toast/toast-test.stories.tsx
  src/components/toast/toast.component.tsx
  src/components/toast/toast.spec.tsx
  src/hooks/__internal__/useModalManager/useModalManager.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6418 fix: ensure any auto-focused element is focused first when a child of a focus trapped component
  cypress/components/select/filterable-select/filterable-select.cy.tsx
  cypress/components/select/multi-select/multi-select.cy.tsx
  cypress/components/select/simple-select/simple-select.cy.tsx
  src/__internal__/checkable-input/hidden-checkable-input.component.tsx
  src/__internal__/focus-trap/focus-trap-utils.ts
  src/__internal__/focus-trap/focus-trap.component.tsx
  src/__internal__/focus-trap/focus-trap.spec.tsx
  src/__internal__/input/input.component.tsx
  src/components/dialog-full-screen/components.test-pw.tsx
  src/components/dialog-full-screen/dialog-full-screen.pw.tsx
  src/components/dialog/components.test-pw.tsx
  src/components/dialog/dialog.pw.tsx
  src/components/select/filterable-select/filterable-select-test.stories.tsx
  src/components/select/filterable-select/filterable-select.component.tsx
  src/components/select/filterable-select/filterable-select.spec.tsx
  src/components/select/multi-select/multi-select-test.stories.tsx
  src/components/select/multi-select/multi-select.component.tsx
  src/components/select/multi-select/multi-select.spec.tsx
  src/components/select/simple-select/simple-select-test.stories.tsx
  src/components/select/simple-select/simple-select.component.tsx
  src/components/select/simple-select/simple-select.spec.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6430 test(pod): playwright refactor
  cypress/components/pod/pod.cy.tsx
  playwright/components/pod/index.ts
  playwright/components/pod/locators.ts
  src/components/pod/components.test-pw.tsx
  src/components/pod/pod-test.stories.tsx
  src/components/pod/pod.pw.tsx
Labels: Passed Review, Passed QA, Squad Front End, pod, playwright

#6404 fix(note): inlineControl button and note content overlap fix
  src/components/note/note-test.stories.tsx
  src/components/note/note.component.tsx
  src/components/note/note.spec.tsx
  src/components/note/note.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6411 fix(tabs): error border partially hidden fix
  src/components/tabs/__internal__/tab-title/tab-title.spec.tsx
  src/components/tabs/__internal__/tab-title/tab-title.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6422 feat(badge): add color prop
  src/components/badge/badge-test.stories.tsx
  src/components/badge/badge.component.tsx
  src/components/badge/badge.pw.tsx
  src/components/badge/badge.spec.tsx
  src/components/badge/badge.stories.mdx
  src/components/badge/badge.stories.tsx
  src/components/badge/badge.style.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6414 fix(menu-full-screen): fix keys in rendering of children
  cypress/components/menu/menu.cy.tsx
  src/components/menu/menu-full-screen/menu-full-screen.component.tsx
  src/components/menu/menu-full-screen/menu-full-screen.spec.tsx
  src/components/menu/menu-test.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6439 fix(input): ensure focus styles removed when becoming inert
  src/hooks/__internal__/useModalAria/useModalAria.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6450 test(image): convert tests to playwright - FE-6129
  cypress/components/image/image.cy.tsx
  src/components/image/components.test-pw.tsx
  src/components/image/image.pw.tsx
Labels: Pending Review, Pending QA, No UX QA Required, Squad Front End

#6431 test(draggable): convert tests from Cypress to Playwright - FE-6115
  cypress/components/draggable/draggable.cy.tsx
  playwright/components/draggable/index.ts
  playwright/components/draggable/locators.ts
  src/components/draggable/components.test-pw.tsx
  src/components/draggable/draggable.pw.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6453 chore: address flaky playwright tests
  playwright/support/helper.ts
  src/components/alert/alert.pw.tsx
  src/components/anchor-navigation/anchor-navigation.pw.tsx
  src/components/checkbox/checkbox.pw.tsx
  src/components/confirm/confirm.pw.tsx
  src/components/decimal/decimal.pw.tsx
  src/components/dialog-full-screen/dialog-full-screen.pw.tsx
  src/components/dialog/dialog.pw.tsx
  src/components/drawer/drawer.pw.tsx
  src/components/duelling-picklist/duelling-picklist.pw.tsx
  src/components/form/form.pw.tsx
  src/components/help/help.pw.tsx
  src/components/icon/icon.pw.tsx
  src/components/portrait/portrait.pw.tsx
  src/components/tile/tile.pw.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6432 test(password): migrate cypress tests to playwright
  cypress/components/password/password.cy.tsx
  src/components/password/components.test-pw.tsx
  src/components/password/password.pw.tsx
Labels: Pending Review, Passed QA, No QA Required, No UX QA Required

#6463 docs(checkbox): add missing import for checkbox group
  src/components/checkbox/checkbox.stories.mdx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End
