Repository Sage/carbon, pull requests merged in 2023-02, with the labels that each got.

#5750 fix(button-bar, button, icon-button): remove invariant and implement context to pass props
  src/components/button-bar/button-bar-test.stories.tsx
  src/components/button-bar/button-bar.component.tsx
  src/components/button-bar/button-bar.spec.tsx
  src/components/button-bar/button-bar.test.js
  src/components/button/button.component.tsx
  src/components/icon-button/icon-button.component.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5782 test(step-sequence): add accessibility tests
  cypress/support/accessibility/a11y-utils.js
  src/components/step-sequence/step-sequence-test.stories.tsx
  src/components/step-sequence/step-sequence.test.js
Labels: Pending Review, Pending QA, Accessibility, Cypress, Squad Front End, step-sequence

#5797 test(button-toggle): add accessibility tests
  cypress/support/accessibility/a11y-utils.js
  src/components/button-toggle/button-toggle-test.stories.tsx
  src/components/button-toggle/button-toggle.test.js
Labels: Pending Review, Pending QA, Accessibility, Cypress, button-toggle

#5799 docs(icon): enable visual test for all icons
  src/components/icon/icon-test.stories.tsx
Labels: Passed Review, Passed QA, Squad Front End, Chromatic, icon

#5789 test(profile): add accessibility tests
  cypress/support/accessibility/a11y-utils.js
  src/components/profile/profile-test.stories.tsx
  src/components/profile/profile.test.js
Labels: Pending QA, Accessibility, Cypress, Squad Front End, profile

#5795 docs(dialog-full-screen): fix storybook docs from hanging on load
  src/components/dialog-full-screen/dialog-full-screen.stories.tsx
  src/components/dialog-full-screen/dialog-full-screen.test.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5798 test(date-range): add accessibility tests
  cypress/support/accessibility/a11y-utils.js
  src/components/date-range/date-range.test.js
Labels: Passed Review, Passed QA, Cypress, Squad Front End, date-range

#5726 Fe 5505 add forwardref
  package-lock.json
  src/__internal__/checkable-input/checkable-input.component.tsx
  src/__internal__/checkable-input/hidden-checkable-input.component.tsx
  src/__internal__/input-behaviour/useInputBehaviour.ts
  src/__internal__/input/input.component.tsx
  src/components/advanced-color-picker/advanced-color-picker.component.js
  src/components/checkbox/checkbox.component.tsx
  src/components/checkbox/checkbox.spec.tsx
  src/components/date-range/date-range.component.js
  src/components/date-range/date-range.d.ts
  src/components/date-range/date-range.spec.js
  src/components/date/date.component.js
  src/components/date/date.spec.js
  src/components/decimal/decimal.component.tsx
  src/components/decimal/decimal.spec.tsx
  src/components/grouped-character/grouped-character.component.tsx
  src/components/grouped-character/grouped-character.spec.tsx
  src/components/menu/menu-item/menu-item.component.js
  src/components/number/number.component.tsx
  src/components/number/number.spec.tsx
  src/components/numeral-date/numeral-date.component.tsx
  src/components/numeral-date/numeral-date.spec.tsx
  src/components/radio-button/radio-button.component.tsx
  src/components/radio-button/radio-button.spec.tsx
  src/components/search/search.component.tsx
  src/components/search/search.spec.tsx
  src/components/select/filterable-select/filterable-select.component.js
  src/components/select/filterable-select/filterable-select.spec.js
  src/components/select/multi-select/multi-select.component.js
  src/components/select/multi-select/multi-select.spec.js
  src/components/select/select-textbox/select-textbox.component.js
  src/components/select/select-textbox/select-textbox.spec.js
  src/components/select/simple-select/simple-select.component.js
  src/components/select/simple-select/simple-select.spec.js
  src/components/switch/switch.component.tsx
  src/components/switch/switch.spec.tsx
  src/components/textarea/textarea.component.tsx
  src/components/textarea/textarea.spec.tsx
  src/components/textbox/textbox.component.tsx
  src/components/textbox/textbox.spec.tsx
  src/components/tile-select/tile-select.component.js
  src/components/tile-select/tile-select.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5792 feat(tab): introduce titleProps for passing props to corresponding title
  src/components/tabs/__internal__/tab-title/tab-title.component.js
  src/components/tabs/__internal__/tab-title/tab-title.d.ts
  src/components/tabs/__internal__/tab-title/tab-title.spec.js
  src/components/tabs/tab/tab.component.js
  src/components/tabs/tab/tab.d.ts
  src/components/tabs/tabs.component.js
  src/components/tabs/tabs.spec.js
  src/components/tabs/tabs.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5803 fix(popover): prevent from crashing when rendered in sidebar - FE-5621
  src/__internal__/popover/popover.component.tsx
  src/__internal__/popover/popover.spec.tsx
Labels: Passed Review, Passed QA, Squad Front End

#5744 DuellingPicklist TypeScript conversion - FE-4789
  src/components/duelling-picklist/duelling-picklist-test.stories.js
  src/components/duelling-picklist/duelling-picklist-test.stories.tsx
  src/components/duelling-picklist/duelling-picklist.component.tsx
  src/components/duelling-picklist/duelling-picklist.context.js
  src/components/duelling-picklist/duelling-picklist.context.ts
  src/components/duelling-picklist/duelling-picklist.d.ts
  src/components/duelling-picklist/duelling-picklist.spec.tsx
  src/components/duelling-picklist/duelling-picklist.stories.mdx
  src/components/duelling-picklist/duelling-picklist.stories.tsx
  src/components/duelling-picklist/duelling-picklist.style.ts
  src/components/duelling-picklist/duelling-picklist.test.js
  src/components/duelling-picklist/index.d.ts
  src/components/duelling-picklist/index.ts
  src/components/duelling-picklist/picklist-divider/picklist-divider.component.js
  src/components/duelling-picklist/picklist-divider/picklist-divider.component.tsx
  src/components/duelling-picklist/picklist-divider/picklist-divider.d.ts
  src/components/duelling-picklist/picklist-divider/picklist-divider.style.ts
  src/components/duelling-picklist/picklist-group/picklist-group.component.tsx
  src/components/duelling-picklist/picklist-group/picklist-group.d.ts
  src/components/duelling-picklist/picklist-group/picklist-group.spec.tsx
  src/components/duelling-picklist/picklist-group/picklist-group.style.ts
  src/components/duelling-picklist/picklist-item/picklist-item.component.tsx
  src/components/duelling-picklist/picklist-item/picklist-item.d.ts
  src/components/duelling-picklist/picklist-item/picklist-item.spec.tsx
  src/components/duelling-picklist/picklist-item/picklist-item.style.ts
  src/components/duelling-picklist/picklist-placeholder/picklist-placeholder.component.tsx
  src/components/duelling-picklist/picklist-placeholder/picklist-placeholder.d.ts
  src/components/duelling-picklist/picklist/picklist.component.tsx
  src/components/duelling-picklist/picklist/picklist.d.ts
  src/components/duelling-picklist/picklist/picklist.style.ts
Labels: Passed Review, Passed QA, Squad Front End, duelling-picklist

#5771 feat(draggable): adds dragged item id to getColumns callback of draggable component
  src/components/draggable/draggable-container.component.js
  src/components/draggable/draggable-container.d.ts
  src/components/draggable/draggable.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, third-party

#5815 docs(step-sequence): fix error with test story not being recognised by storybook
  src/components/step-sequence/step-sequence-test.stories.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#5800 fix(flat-table): fix misaligned pager - FE-5595
  src/components/flat-table/__snapshots__/flat-table.spec.js.snap
  src/components/flat-table/flat-table.component.js
  src/components/flat-table/flat-table.style.js
Labels: Passed Review, Pending QA, Squad Front End

#5818 docs(link): import Link component into stories file
  src/components/link/link.stories.mdx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#5821 chore: update import paths to be relative
  src/__internal__/form-field/form-field.component.tsx
  src/__internal__/label/label.component.tsx
  src/__spec_helper__/test-utils.ts
  src/components/button-bar/button-bar.spec.tsx
  src/components/button/button.spec.tsx
  src/components/button/button.style.ts
  src/components/dialog/dialog.spec.tsx
  src/components/global-header/global-header.component.tsx
  src/components/help/help.spec.tsx
  src/components/link/link.component.tsx
  src/components/menu/menu-item/menu-item.d.ts
  src/components/split-button/split-button.spec.tsx
  src/components/switch/switch.spec.tsx
  src/style/design-tokens/carbon-scoped-tokens-provider/carbon-scoped-tokens-provider.component.ts
  src/style/utils/color.ts
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#5553 Add new component to Carbon: Button Minor
  cypress/support/accessibility/a11y-utils.js
  src/components/button-minor/button-minor-test.stories.tsx
  src/components/button-minor/button-minor.component.tsx
  src/components/button-minor/button-minor.spec.tsx
  src/components/button-minor/button-minor.stories.mdx
  src/components/button-minor/button-minor.stories.tsx
  src/components/button-minor/button-minor.style.ts
  src/components/button-minor/button-minor.test.js
  src/components/button-minor/index.ts
  src/components/button/button-types.style.ts
  src/components/button/button.component.tsx
  src/components/button/button.spec.tsx
  src/components/button/button.stories.mdx
  src/components/button/button.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End, button

#5802 feat(image): add decorative prop to component - FE-5362
  src/components/image/image.component.tsx
  src/components/image/image.spec.tsx
  src/components/image/image.stories.mdx
  src/components/image/image.stories.tsx
  src/components/image/image.style.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5793 fix(icon-button): use onClick instead of onAction to ensure keyboard behaviour is handled by default
  src/components/batch-selection/batch-selection-test.stories.tsx
  src/components/batch-selection/batch-selection.spec.tsx
  src/components/batch-selection/batch-selection.stories.tsx
  src/components/button-bar/button-bar-test.stories.tsx
  src/components/button-bar/button-bar.spec.tsx
  src/components/button-bar/button-bar.stories.mdx
  src/components/card/card.stories.tsx
  src/components/dialog-full-screen/dialog-full-screen.component.tsx
  src/components/dialog-full-screen/dialog-full-screen.stories.tsx
  src/components/dialog/dialog.component.tsx
  src/components/dismissible-box/dismissible-box.component.tsx
  src/components/flat-table/flat-table-expandable.stories.mdx
  src/components/flat-table/flat-table.stories.mdx
  src/components/flat-table/flat-table.test.js
  src/components/icon-button/icon-button.component.tsx
  src/components/icon-button/icon-button.spec.tsx
  src/components/icon-button/icon-button.stories.mdx
  src/components/icon-button/icon-button.test.js
  src/components/link-preview/link-preview.component.tsx
  src/components/menu/menu-full-screen/menu-full-screen.component.js
  src/components/message/message.component.tsx
  src/components/pill/pill.component.tsx
  src/components/pod/pod.component.tsx
  src/components/popover-container/popover-container.component.tsx
  src/components/popover-container/popover-container.spec.tsx
  src/components/sidebar/sidebar.component.tsx
  src/components/toast/toast.component.tsx
  src/components/vertical-menu/vertical-menu-full-screen.component.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5824 test(progress-tracker): add accessibility tests
  cypress/support/accessibility/a11y-utils.js
  src/components/progress-tracker/progress-tracker.test.js
Labels: Passed Review, Passed QA, Accessibility, Cypress, Squad Front End, progress-tracker

#5814 fix(box): ensure z-index is set when sticky or fixed positioned
  src/components/box/box.component.tsx
  src/components/box/box.spec.tsx
  src/components/box/box.test.js
Labels: Passed Review, Pending QA, No UX QA Required, Squad Front End

#5808 fix(multi-select): fix onchange callback being called twice on option select - FE-5332
  src/components/select/multi-select/multi-select-test.stories.tsx
  src/components/select/multi-select/multi-select.component.js
  src/components/select/multi-select/multi-select.spec.js
  src/components/select/multi-select/multi-select.test.js
Labels: Pending Review, Passed QA, Squad Front End

#5829 test(draggable): add accessibility tests
  cypress/e2e/accessibility/a11y-eleventh-part.test.js
  cypress/e2e/accessibility/a11y-ninth-part.test.js
  cypress/e2e/accessibility/a11y-tenth-part.test.js
  cypress/e2e/accessibility/a11y-twelfth-part.test.js
  cypress/locators/progress-tracker/index.js
  cypress/support/accessibility/a11y-utils.js
  src/components/draggable/draggable.test.js
  src/components/progress-tracker/progress-tracker.test.js
Labels: Passed Review, Passed QA, Accessibility, Cypress, Squad Front End, draggable, progress-tracker

#5827 fix(date): update abbreviated day translations in picker component for German locale FE-5660
  src/components/date/__internal__/date-picker/date-picker.component.js
  src/components/date/__internal__/date-picker/date-picker.spec.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5768 feat(anchor-navigation): changed behaviour to improve accessibility
  src/components/anchor-navigation/anchor-navigation.component.tsx
  src/components/anchor-navigation/anchor-navigation.spec.tsx
  src/components/anchor-navigation/anchor-navigation.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5832 test(definition-list): add accessibility tests
  cypress/support/accessibility/a11y-utils.js
  src/components/definition-list/definition-list.test.js
Labels: Passed Review, Passed QA, Accessibility, Cypress, Squad Front End

#5769 fix(menu, submenu): refactor components to remove children iteration and cloning
  src/__internal__/input-icon-toggle/input-icon-toggle.component.tsx
  src/components/link/link.component.tsx
  src/components/menu/__internal__/keyboard-navigation/index.js
  src/components/menu/__internal__/keyboard-navigation/index.spec.js
  src/components/menu/__internal__/keyboard-navigation/index.spec.tsx
  src/components/menu/__internal__/keyboard-navigation/index.ts
  src/components/menu/__internal__/locators.js
  src/components/menu/__internal__/submenu/submenu.component.js
  src/components/menu/__internal__/submenu/submenu.spec.js
  src/components/menu/menu-divider/menu-divider.spec.js
  src/components/menu/menu-full-screen/menu-full-screen.component.js
  src/components/menu/menu-item/index.js
  src/components/menu/menu-item/menu-item.component.js
  src/components/menu/menu-item/menu-item.d.ts
  src/components/menu/menu-item/menu-item.spec.js
  src/components/menu/menu-segment-title/menu-segment-title.spec.js
  src/components/menu/menu.component.js
  src/components/menu/menu.context.js
  src/components/menu/menu.spec.js
  src/components/menu/menu.test.js
  src/components/menu/scrollable-block/scrollable-block.component.js
  src/components/menu/scrollable-block/scrollable-block.spec.js
  src/components/vertical-divider/vertical-divider.spec.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5657 feat(select): add virtual scrolling support - FE-5394
  cypress/locators/select/index.js
  package-lock.json
  package.json
  src/components/select/filterable-select/filterable-select.component.js
  src/components/select/filterable-select/filterable-select.d.ts
  src/components/select/filterable-select/filterable-select.spec.js
  src/components/select/filterable-select/filterable-select.stories.mdx
  src/components/select/filterable-select/filterable-select.test.js
  src/components/select/list-action-button/__snapshots__/list-action-button.spec.js.snap
  src/components/select/list-action-button/list-action-button.style.js
  src/components/select/multi-select/multi-select.component.js
  src/components/select/multi-select/multi-select.d.ts
  src/components/select/multi-select/multi-select.spec.js
  src/components/select/multi-select/multi-select.stories.mdx
  src/components/select/multi-select/multi-select.test.js
  src/components/select/option-group-header/__snapshots__/option-group-header.spec.js.snap
  src/components/select/option-group-header/option-group-header.component.js
  src/components/select/option-group-header/option-group-header.style.js
  src/components/select/option-row/__snapshots__/option-row.spec.js.snap
  src/components/select/option-row/option-row.component.js
  src/components/select/option-row/option-row.style.js
  src/components/select/option/__snapshots__/option.spec.js.snap
  src/components/select/option/option.component.js
  src/components/select/option/option.style.js
  src/components/select/select-list/select-list-container.style.js
  src/components/select/select-list/select-list.component.js
  src/components/select/select-list/select-list.spec.js
  src/components/select/select-list/select-list.style.js
  src/components/select/select-list/update-list-scroll.js
  src/components/select/select-list/update-list-scroll.spec.js
  src/components/select/simple-select/simple-select.component.js
  src/components/select/simple-select/simple-select.d.ts
  src/components/select/simple-select/simple-select.spec.js
  src/components/select/simple-select/simple-select.stories.mdx
  src/components/select/simple-select/simple-select.test.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5838 test(pod): refactor for accessibility tests
  cypress/support/accessibility/a11y-utils.js
  src/components/pod/pod-test.stories.tsx
  src/components/pod/pod.test.js
Labels: Passed Review, Passed QA, Accessibility, Cypress, Squad Front End, pod

#5826 fix(link): change display to inline so that text can wrap
  src/components/card/card-footer/__snapshots__/card-footer.spec.tsx.snap
  src/components/link/__snapshots__/link.spec.tsx.snap
  src/components/link/link.component.tsx
  src/components/link/link.spec.tsx
  src/components/link/link.stories.mdx
  src/components/link/link.stories.tsx
  src/components/link/link.style.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5840 Cypress accessibility box carbon provider
  cypress/support/accessibility/a11y-utils.js
  src/components/box/box-test.stories.tsx
  src/components/box/box.stories.mdx
  src/components/box/box.stories.tsx
  src/components/box/box.test.js
  src/components/carbon-provider/carbon-provider.stories.mdx
  src/components/carbon-provider/carbon-provider.stories.tsx
  src/components/carbon-provider/carbon-provider.test.js
Labels: Passed Review, Passed QA, Accessibility, Cypress, Squad Front End, box, carbon-provider

#5843 test(pill): add accessibility tests
  cypress/support/accessibility/a11y-utils.js
  src/components/pill/pill.test.js
Labels: Pending QA, Accessibility, Cypress, Squad Front End, pill

#5841 test(checkbox): add accessibility tests
  cypress/support/accessibility/a11y-utils.js
  src/components/checkbox/checkbox-test.stories.tsx
  src/components/checkbox/checkbox.test.js
Labels: Pending Review, Pending QA, Accessibility, Cypress, checkbox

#5848 Cypress accessibility textarea textbox
  cypress/support/accessibility/a11y-utils.js
  src/components/textarea/textarea-test.stories.tsx
  src/components/textarea/textarea.test.js
  src/components/textbox/textbox-test.stories.tsx
  src/components/textbox/textbox.stories.mdx
  src/components/textbox/textbox.stories.tsx
  src/components/textbox/textbox.test.js
Labels: Passed Review, Passed QA, Accessibility, Cypress, Squad Front End, textarea, textbox

#5835 fix: resolve issue with multiple execution of onOpen and onFilterChange callbacks - FE-5612
  package-lock.json
  package.json
  src/components/select/filterable-select/filterable-select.component.js
  src/components/select/filterable-select/filterable-select.spec.js
  src/components/select/filterable-select/filterable-select.test.js
  src/components/select/multi-select/multi-select.component.js
  src/components/select/multi-select/multi-select.spec.js
  src/components/select/multi-select/multi-select.test.js
  src/hooks/__internal__/useStableCallback/index.ts
  src/hooks/__internal__/useStableCallback/useStableCallback.spec.ts
  src/hooks/__internal__/useStableCallback/useStableCallback.ts
Labels: Passed Review, Passed QA, Squad Front End, select

#5806 feat(settings-row, heading): surface headingType prop on components
  src/components/heading/heading.component.tsx
  src/components/heading/heading.spec.tsx
  src/components/heading/heading.stories.mdx
  src/components/heading/heading.test.js
  src/components/heading/index.ts
  src/components/settings-row/settings-row.component.js
  src/components/settings-row/settings-row.d.ts
  src/components/settings-row/settings-row.spec.js
  src/components/settings-row/settings-row.stories.mdx
  src/components/settings-row/settings-row.style.js
  src/components/settings-row/settings-row.test.js
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#5842 test(search): refactor accessibility tests
  cypress/support/accessibility/a11y-utils.js
  src/components/search/index.ts
  src/components/search/search-test.stories.tsx
  src/components/search/search.stories.mdx
  src/components/search/search.stories.tsx
  src/components/search/search.test.js
Labels: Pending Review, Pending QA, Accessibility, Cypress, Squad Front End, search

#5790 refactor(advanced-color-picker): convert files to typescript (FE-4762)
  src/__internal__/focus-trap/focus-trap.component.tsx
  src/__internal__/focus-trap/index.ts
  src/components/advanced-color-picker/advanced-color-picker-cell.style.ts
  src/components/advanced-color-picker/advanced-color-picker.component.tsx
  src/components/advanced-color-picker/advanced-color-picker.d.ts
  src/components/advanced-color-picker/advanced-color-picker.spec.js
  src/components/advanced-color-picker/advanced-color-picker.spec.tsx
  src/components/advanced-color-picker/advanced-color-picker.style.ts
  src/components/advanced-color-picker/index.d.ts
  src/components/advanced-color-picker/index.js
  src/components/advanced-color-picker/index.ts
  src/components/dialog-full-screen/dialog-full-screen.component.tsx
  src/components/dialog/dialog.component.tsx
  src/components/simple-color-picker/index.ts
  src/components/simple-color-picker/simple-color-picker.component.tsx
  src/components/simple-color-picker/simple-color-picker.spec.tsx
Labels: Passed Review, Pending QA, No UX QA Required, Squad Front End

#5853 fix(menu-item): maintain focus order when submenu child item is clicked
  src/components/menu/__internal__/submenu/submenu.component.js
  src/components/menu/__internal__/submenu/submenu.spec.js
  src/components/menu/menu-item/menu-item.component.js
  src/components/menu/menu.test.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5862 test(switch): refactor accessibility tests
  cypress/support/accessibility/a11y-utils.js
  src/components/switch/switch-test.stories.tsx
  src/components/switch/switch.test.js
Labels: Passed Review, Passed QA, Accessibility, Cypress, Squad Front End, switch

#5870 chore: update browserslist
  package-lock.json
  package.json
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#5866 test(accordion, flat-table): add helper for testing rotation angle
  cypress/support/helper.js
  src/components/accordion/accordion.test.js
  src/components/flat-table/flat-table.test.js
Labels: Pending Review, Passed QA, No UX QA Required, Squad Front End

#5863 docs(decimal): fix naming error with test story - FE-5695
  src/components/decimal/decimal-test.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#5849 fix(select): resolve issue with Select component closing parent Dialog on escape key press - FE-5624
  src/components/select/filterable-select/filterable-select.test.js
  src/components/select/multi-select/multi-select.component.js
  src/components/select/multi-select/multi-select.test.js
  src/components/select/select-list/select-list.component.js
  src/components/select/select-list/select-list.spec.js
  src/components/select/simple-select/simple-select.component.js
  src/components/select/simple-select/simple-select.test.js
Labels: Pending Review, Passed QA, Squad Front End
