Repository Sage/carbon, pull requests merged in 2024-10, with the labels that each got.

#6974 fix(form): allow form-footer content to be responsive
  src/components/form/__internal__/form-summary.style.ts
  src/components/form/form-test.stories.tsx
  src/components/form/form.component.tsx
  src/components/form/form.stories.tsx
  src/components/form/form.style.ts
  src/components/form/form.test.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6955 fix(date): add callback to be called when component blurs and picker is closed
  src/components/date/__internal__/date-picker/date-picker.component.tsx
  src/components/date/date-test.stories.tsx
  src/components/date/date.component.tsx
  src/components/date/date.test.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6987 fix(badge): investigate failing RTL test
  src/components/badge/badge.component.tsx
  src/components/badge/badge.style.ts
  src/components/badge/badge.test.tsx
Labels: Passed Review, Passed QA, Squad Front End

#6996 fix(select): prevent deprecation warning about uncontrolled textbox from being fired
  src/components/select/__internal__/select-textbox/select-textbox.component.tsx
  src/components/select/__internal__/select-textbox/select-textbox.test.tsx
  src/components/select/filterable-select/filterable-select.component.tsx
  src/components/select/filterable-select/filterable-select.test.tsx
  src/components/select/multi-select/multi-select.component.tsx
  src/components/select/multi-select/multi-select.test.tsx
  src/components/select/simple-select/simple-select.component.tsx
  src/components/select/simple-select/simple-select.spec.tsx
  src/components/select/simple-select/simple-select.test.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6998 fix(textarea): ensure expandable height shrinks when new lines are removed
  src/components/textarea/textarea.component.tsx
  src/components/textarea/textarea.pw.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6993 refactor(useInputBehaviour, input-icon-toggle): convert enzyme tests to RTL
  src/__internal__/input-behaviour/useInputBehaviour.spec.tsx
  src/__internal__/input-behaviour/useInputBehaviour.test.tsx
  src/__internal__/input-icon-toggle/input-icon-toggle.spec.tsx
  src/__internal__/input-icon-toggle/input-icon-toggle.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required

#6992 refactor(simple-select): convert enzyme tests to RTL
  src/components/select/__internal__/select-list/select-list.test.tsx
  src/components/select/simple-select/simple-select.component.tsx
  src/components/select/simple-select/simple-select.spec.tsx
  src/components/select/simple-select/simple-select.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6994 test: tidy up new RTL tests - FE-6549
  src/__internal__/focus-trap/focus-trap.test.tsx
  src/__internal__/sticky-footer/sticky-footer.test.tsx
  src/components/alert/alert.test.tsx
  src/components/breadcrumbs/crumb/crumb.test.tsx
  src/components/button-bar/button-bar.test.tsx
  src/components/button-toggle/button-toggle-group/button-toggle-group.test.tsx
  src/components/file-input/__internal__/file-upload-status/file-upload-status.test.tsx
  src/components/file-input/file-input.test.tsx
  src/components/flat-table/flat-table-body-draggable/flat-table-body-draggable.test.tsx
  src/components/global-header/global-header.test.tsx
  src/components/hr/hr.test.tsx
  src/components/loader-spinner/loader-spinner.test.tsx
  src/components/menu/menu-full-screen/menu-full-screen.test.tsx
  src/components/radio-button/radio-button-group/radio-button-group.test.tsx
  src/components/step-flow/step-flow.test.tsx
  src/components/time/time.test.tsx
  src/hooks/__internal__/useClickAwayListener/useClickAwayListener.test.tsx
  src/hooks/__internal__/useFloating/useFloating.test.tsx
  src/hooks/__internal__/useFormSpacing/useFormSpacing.test.tsx
  src/hooks/__internal__/useLocale/useLocale.test.tsx
  src/hooks/__internal__/useModalAria/useModalAria.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6991 Select list width
  src/components/select/__internal__/select-list/select-list.component.tsx
  src/components/select/__internal__/select-list/select-list.test.tsx
  src/components/select/filterable-select/filterable-select.component.tsx
  src/components/select/filterable-select/filterable-select.mdx
  src/components/select/filterable-select/filterable-select.pw.tsx
  src/components/select/filterable-select/filterable-select.spec.tsx
  src/components/select/filterable-select/filterable-select.stories.tsx
  src/components/select/multi-select/multi-select.component.tsx
  src/components/select/multi-select/multi-select.mdx
  src/components/select/multi-select/multi-select.pw.tsx
  src/components/select/multi-select/multi-select.spec.tsx
  src/components/select/multi-select/multi-select.stories.tsx
  src/components/select/simple-select/components.test-pw.tsx
  src/components/select/simple-select/simple-select-test.stories.tsx
  src/components/select/simple-select/simple-select.component.tsx
  src/components/select/simple-select/simple-select.mdx
  src/components/select/simple-select/simple-select.pw.tsx
  src/components/select/simple-select/simple-select.stories.tsx
  src/components/select/simple-select/simple-select.test.tsx
  src/hooks/__internal__/useFloating/useFloating.test.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#7014 Option comps rtl
  src/components/select/option-group-header/__snapshots__/option-group-header.spec.tsx.snap
  src/components/select/option-group-header/option-group-header.component.tsx
  src/components/select/option-group-header/option-group-header.spec.tsx
  src/components/select/option-group-header/option-group-header.test.tsx
  src/components/select/option-row/__snapshots__/option-row.spec.tsx.snap
  src/components/select/option-row/option-row.component.tsx
  src/components/select/option-row/option-row.spec.tsx
  src/components/select/option-row/option-row.test.tsx
  src/components/select/option/__snapshots__/option.spec.tsx.snap
  src/components/select/option/option.component.tsx
  src/components/select/option/option.spec.tsx
  src/components/select/option/option.test.tsx
  src/components/select/simple-select/components.test-pw.tsx
  src/components/select/simple-select/simple-select.pw.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#7001 Select virtualiser tweaks
  package-lock.json
  package.json
  src/components/select/__internal__/select-list/select-list.component.tsx
  src/components/select/__internal__/utils/with-filter.hoc.tsx
  src/components/select/option/option.component.tsx
  src/components/select/option/option.style.ts
  src/components/select/option/option.test.tsx
  src/components/select/simple-select/components.test-pw.tsx
  src/components/select/simple-select/simple-select-test.stories.tsx
  src/components/select/simple-select/simple-select.mdx
  src/components/select/simple-select/simple-select.pw.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7002 fix(action-popover-menu): investigate focusIndex and setFocusIndex props on ActionPopoverMenu
  src/components/action-popover/action-popover-menu/action-popover-menu.component.tsx
Labels: Passed Review, Passed QA

#6989 feat(storybook): upgrade storybook to 8.3
  .storybook/main.ts
  package-lock.json
  package.json
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7009 refactor(tile): convert tests to RTL
  src/__spec_helper__/__internal__/test-utils.ts
  src/components/tile/flex-tile-container/flex-tile-container.test.tsx
  src/components/tile/tile-content/tile-content.test.tsx
  src/components/tile/tile-footer/tile-footer.spec.tsx
  src/components/tile/tile-footer/tile-footer.test.tsx
  src/components/tile/tile-header/tile-header.spec.tsx
  src/components/tile/tile-header/tile-header.test.tsx
  src/components/tile/tile.spec.tsx
  src/components/tile/tile.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#7012 fix(badge): ensure badge does not appear under child components
  src/components/badge/badge-test.stories.tsx
  src/components/badge/badge.component.tsx
  src/components/badge/badge.style.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7007 fix(switch): fix screen reader announcements with new validation
  src/components/switch/switch-test.stories.tsx
  src/components/switch/switch.component.tsx
  src/components/switch/switch.test.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7020 chore: resolve runtime errors thrown by jest tests
  package-lock.json
  package.json
  scripts/generate_metadata/generate_metadata.mjs
  scripts/generate_metadata/generate_metadata.spec.js
  scripts/generate_metadata/generate_metadata.test.js
  src/__spec_helper__/__internal__/index.ts
  src/__spec_helper__/__internal__/select-test-utils.ts
  src/components/numeral-date/numeral-date.test.tsx
  src/components/select/__internal__/select-list/select-list.component.tsx
  src/components/select/simple-select/simple-select.test.tsx
Labels: Passed Review, Passed QA, No UX QA Required

#7003 fix(action-popover): ensure that opening using the up arrow focuses last focusable element - FE-6793
  src/components/action-popover/__internal__/action-popover-utils.tsx
  src/components/action-popover/action-popover-item/action-popover-item.component.tsx
  src/components/action-popover/action-popover-menu/action-popover-menu.component.tsx
  src/components/action-popover/action-popover-test.stories.tsx
  src/components/action-popover/action-popover.component.tsx
  src/components/action-popover/action-popover.pw.tsx
  src/components/action-popover/action-popover.stories.tsx
  src/components/action-popover/action-popover.test.tsx
  src/components/action-popover/components.test-pw.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#7022 fix(tile-select): remove not allowed aria-expanded from accordion
  src/components/tile-select/__internal__/accordion/accordion.component.tsx
  src/components/tile-select/tile-select.mdx
  src/components/tile-select/tile-select.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7017 Menu fixes
  .storybook/utils/styled-system-props.ts
  src/components/global-header/component.test-pw.tsx
  src/components/global-header/global-header-test.stories.tsx
  src/components/global-header/global-header.stories.tsx
  src/components/menu/__internal__/submenu/submenu.style.ts
  src/components/menu/component.test-pw.tsx
  src/components/menu/menu-item/menu-item.component.tsx
  src/components/menu/menu-item/menu-item.stories.tsx
  src/components/menu/menu-item/menu-item.style.ts
  src/components/menu/menu-item/menu-item.test.tsx
  src/components/menu/menu-test.stories.tsx
  src/components/menu/menu.component.tsx
  src/components/menu/menu.mdx
  src/components/menu/menu.pw.tsx
  src/components/menu/menu.stories.tsx
  src/components/menu/menu.style.ts
  src/components/navigation-bar/components.test-pw.tsx
  src/components/navigation-bar/navigation-bar-test.stories.tsx
  src/components/navigation-bar/navigation-bar.pw.tsx
  src/components/navigation-bar/navigation-bar.stories.tsx
Labels: Passed Review, Pending QA, Passed UX QA, Squad Front End

#6990 fix: resolve layout issues with sticky footer forms inside Carbon modal components (FE-6816)
  .storybook/modes.ts
  .storybook/preview.ts
  playwright/components/alert/index.ts
  playwright/components/select/index.ts
  src/components/advanced-color-picker/advanced-color-picker.pw.tsx
  src/components/advanced-color-picker/advanced-color-picker.style.ts
  src/components/alert/alert.pw.tsx
  src/components/confirm/confirm.pw.tsx
  src/components/date/date.pw.tsx
  src/components/dialog-full-screen/content.style.ts
  src/components/dialog-full-screen/dialog-full-screen-test.stories.tsx
  src/components/dialog-full-screen/dialog-full-screen.mdx
  src/components/dialog-full-screen/dialog-full-screen.pw.tsx
  src/components/dialog-full-screen/dialog-full-screen.stories.tsx
  src/components/dialog-full-screen/dialog-full-screen.style.ts
  src/components/dialog-full-screen/dialog-full-screen.test.tsx
  src/components/dialog/components.test-pw.tsx
  src/components/dialog/dialog-test.stories.tsx
  src/components/dialog/dialog.component.tsx
  src/components/dialog/dialog.config.ts
  src/components/dialog/dialog.stories.tsx
  src/components/dialog/dialog.style.ts
  src/components/dialog/dialog.test.tsx
  src/components/form/form.component.tsx
  src/components/form/form.pw.tsx
  src/components/form/form.stories.tsx
  src/components/form/form.style.ts
  src/components/form/form.test.tsx
  src/components/select/filterable-select/filterable-select.pw.tsx
  src/components/sidebar/sidebar-test.stories.tsx
  src/components/sidebar/sidebar.component.tsx
  src/components/sidebar/sidebar.config.ts
  src/components/sidebar/sidebar.style.ts
  src/components/sidebar/sidebar.test.tsx
  src/components/textarea/components.test-pw.tsx
  src/components/textarea/textarea.pw.tsx
  src/components/toast/components.test-pw.tsx
  src/components/toast/toast.pw.tsx
  src/style/utils/form-style-utils.spec.ts
  src/style/utils/form-style-utils.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#7025 feat(typography): update line heights to align with DS
  src/components/typography/typography.pw.tsx
  src/components/typography/typography.style.ts
  src/components/typography/typography.test.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6986 fix(menu-full-screen, modal): ensure the call to action element is focused on close
  src/components/dialog-full-screen/components.test-pw.tsx
  src/components/dialog-full-screen/dialog-full-screen.mdx
  src/components/dialog-full-screen/dialog-full-screen.pw.tsx
  src/components/dialog-full-screen/dialog-full-screen.stories.tsx
  src/components/dialog/components.test-pw.tsx
  src/components/dialog/dialog.mdx
  src/components/dialog/dialog.pw.tsx
  src/components/dialog/dialog.stories.tsx
  src/components/menu/component.test-pw.tsx
  src/components/menu/menu-full-screen/menu-full-screen.component.tsx
  src/components/menu/menu.mdx
  src/components/menu/menu.pw.tsx
  src/components/modal/modal.component.tsx
  src/components/sidebar/components.test-pw.tsx
  src/components/sidebar/sidebar.mdx
  src/components/sidebar/sidebar.pw.tsx
  src/components/sidebar/sidebar.stories.tsx
  src/hooks/__internal__/useModalManager/useModalManager.ts
Labels: Passed Review, Passed QA, Passed UX QA, Passed a11y Review

#7039 Rename spec files
  scripts/check_rfcs/check_rfcs.test.js
  src/__internal__/filter-object-properties/filter-object-properties.test.ts
  src/__internal__/utils/helpers/tags/tags-specs/index.ts
  src/__internal__/utils/helpers/tags/tags-specs/tags-specs.ts
  src/components/icon/__snapshots__/icon-unicodes.test.js.snap
  src/components/icon/icon-unicodes.test.js
  src/style/style.test.ts
  src/style/themes/none/__snapshots__/none.test.ts.snap
  src/style/themes/none/none.test.ts
  src/style/utils/color.test.ts
  src/style/utils/get-color-value.test.ts
  src/style/utils/merge-deep.test.ts
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#7030 feat(box): adds a deprecation warning to the Box component for tabIndex
  src/components/box/box.component.tsx
  src/components/box/box.test.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7016 refactor(text-editor): covert tests to use react-testing-library
  src/components/text-editor/__internal__/editor-link/editor-link.spec.tsx
  src/components/text-editor/__internal__/editor-link/editor-link.test.tsx
  src/components/text-editor/__internal__/editor-validation-wrapper/editor-validation-wrapper.spec.tsx
  src/components/text-editor/__internal__/label-wrapper/label.spec.tsx
  src/components/text-editor/__internal__/label-wrapper/label.test.tsx
  src/components/text-editor/__internal__/toolbar/toolbar-button/toolbar-button.spec.tsx
  src/components/text-editor/__internal__/toolbar/toolbar.spec.tsx
  src/components/text-editor/__internal__/toolbar/toolbar.test.tsx
  src/components/text-editor/__internal__/utils/utils.test.ts
  src/components/text-editor/text-editor.component.tsx
  src/components/text-editor/text-editor.pw.tsx
  src/components/text-editor/text-editor.spec.tsx
  src/components/text-editor/text-editor.test.tsx
Labels: Pending Review, Passed QA, No UX QA Required, Squad Front End

#7041 chore: replace `toBeFocused` with testing library matcher `toHaveFocus`
  src/__internal__/focus-trap/focus-trap.test.tsx
  src/__internal__/utils/helpers/events/events.test.ts
  src/components/action-popover/action-popover.test.tsx
  src/components/advanced-color-picker/advanced-color-picker.test.tsx
  src/components/anchor-navigation/anchor-navigation.test.tsx
  src/components/heading/heading.test.tsx
  src/components/menu/menu-full-screen/menu-full-screen.test.tsx
  src/components/menu/menu.test.tsx
  src/components/select/__internal__/select-list/select-list.test.tsx
  src/components/simple-color-picker/simple-color-picker.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#7026 fix(multi-action-button, split-button): ensure child buttons are accessible
  src/components/multi-action-button/multi-action-button.component.tsx
  src/components/multi-action-button/multi-action-button.pw.tsx
  src/components/split-button/split-button.component.tsx
  src/hooks/__internal__/useChildButtons/useChildButtons.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End, Passed a11y Review

#7036 refactor(filterable-select): convert unit tests to RTL
  src/components/select/filterable-select/filterable-select.component.tsx
  src/components/select/filterable-select/filterable-select.pw.tsx
  src/components/select/filterable-select/filterable-select.spec.tsx
  src/components/select/filterable-select/filterable-select.test.tsx
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#7015 fix: inline label props have unexpected behavior with new validation
  src/components/date-range/date-range-test.stories.tsx
  src/components/date-range/date-range.component.tsx
  src/components/date-range/date-range.test.tsx
  src/components/numeral-date/numeral-date-test.stories.tsx
  src/components/numeral-date/numeral-date.component.tsx
  src/components/numeral-date/numeral-date.test.tsx
  src/components/radio-button/radio-button-group/radio-button-group.component.tsx
  src/components/radio-button/radio-button-group/radio-button-group.test.tsx
  src/components/radio-button/radio-button-test.stories.tsx
  src/components/textarea/textarea-test.stories.tsx
  src/components/textarea/textarea.component.tsx
  src/components/textarea/textarea.test.tsx
Labels: Passed Review, Passed QA, Squad Front End

#7037 refactor(multi-select): rewrite all enzyme tests with React Testing Library (FE-6693)
  src/components/select/__internal__/select-list/select-list.component.tsx
  src/components/select/__internal__/select-list/select-list.test.tsx
  src/components/select/multi-select/multi-select.component.tsx
  src/components/select/multi-select/multi-select.pw.tsx
  src/components/select/multi-select/multi-select.spec.tsx
  src/components/select/multi-select/multi-select.test.tsx
Labels: Passed Review, Pending QA, No UX QA Required

#7042 chore(select): ensure test stories callbacks work and cleanup controls
  src/components/select/filterable-select/filterable-select-test.stories.tsx
  src/components/select/multi-select/multi-select-test.stories.tsx
  src/components/select/simple-select/simple-select-test.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7024 fix(note): allow title to be a node & fix potential visual regression
  playwright/components/note/index.ts
  src/components/note/note-test.stories.tsx
  src/components/note/note.component.tsx
  src/components/note/note.mdx
  src/components/note/note.stories.tsx
  src/components/note/note.style.ts
  src/components/note/note.test.tsx
Labels: Passed Review, Passed QA, Passed UX QA

#7045 docs(select): document bounding rectangle helper usage
  src/components/select/filterable-select/filterable-select.mdx
  src/components/select/multi-select/multi-select.mdx
  src/components/select/simple-select/simple-select.mdx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End, select
