Repository Sage/carbon, pull requests merged in 2024-05, with the labels that each got.

#6691 fix(text-editor): ensure that clicking editor does not trigger onChange to be called
  src/components/text-editor/text-editor.mdx
  src/components/text-editor/text-editor.pw.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6711 chore: upgrade transitive dependency ejs
  package-lock.json
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#6712 docs(select): increase container height for stories
  src/components/select/filterable-select/filterable-select.stories.tsx
  src/components/select/multi-select/multi-select.stories.tsx
  src/components/select/simple-select/simple-select.stories.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6699 feat(icon): 3 new icons added and tick update
  src/components/icon/__snapshots__/icon-unicodes.spec.js.snap
  src/components/icon/fonts/carbon-icons-webfont.woff
  src/components/icon/fonts/carbon-icons-webfont.woff2
  src/components/icon/icon-config.ts
  src/components/icon/icon-type.ts
  src/components/icon/icon-unicodes.js
  src/style/assets/carbon-icons-webfont.woff
  src/style/assets/carbon-icons-webfont.woff2
Labels: Passed Review, Passed QA, Passed UX QA

#6713 fix: ensure tree-shaking works with date-fns package
  playwright/index.tsx
  playwright/support/date-fns-locales/index.ts
  src/components/date-range/date-range.stories.tsx
  src/components/date/__internal__/date-fns-fp/index.ts
  src/components/date/__internal__/date-picker/date-picker.spec.tsx
  src/components/date/__internal__/utils.ts
  src/components/date/date.spec.tsx
  src/components/date/date.stories.tsx
  src/locales/__internal__/es-es.ts
  src/locales/date-fns-locales/index.ts
  src/locales/en-gb.ts
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End, Squad SBC Miro

#6715 chore: install linting plugins for RTL and jest-dom
  .eslintrc
  jest.config.json
  package-lock.json
  package.json
  scripts/build.js
  tsconfig-build.json
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6697 fix(simple-select): prevent select list from opening via enter key when component is focused
  src/components/flat-table/flat-table.pw.tsx
  src/components/select/simple-select/simple-select.component.tsx
  src/components/select/simple-select/simple-select.spec.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6727 fix(link): ensure styling overrides apply to open button when popover-container renders in menu
  src/components/button/button.component.tsx
  src/components/card/card-footer/__snapshots__/card-footer.spec.tsx.snap
  src/components/link/link.style.ts
  src/components/popover-container/popover-container-test.stories.tsx
  src/components/search/search.component.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6710 fix(loader-spinner): allow components label to extend longer than the svg wrapper
  src/components/loader-spinner/loader-spinner-test.stories.tsx
  src/components/loader-spinner/loader-spinner.config.ts
  src/components/loader-spinner/loader-spinner.mdx
  src/components/loader-spinner/loader-spinner.pw.tsx
  src/components/loader-spinner/loader-spinner.spec.tsx
  src/components/loader-spinner/loader-spinner.stories.tsx
  src/components/loader-spinner/loader-spinner.style.ts
Labels: Passed Review, Passed QA, Passed UX QA

#6701 fix(typography): textOverflow prop has no effect when the truncate prop is set
  src/components/typography/typography-test.stories.tsx
  src/components/typography/typography.component.tsx
  src/components/typography/typography.mdx
  src/components/typography/typography.spec.tsx
  src/components/typography/typography.stories.tsx
  src/components/typography/typography.style.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6708 fix(multi-action-button, split-button): menu covers button focus border & remove open menu on hover
  src/components/carbon-provider/carbon-provider.pw.tsx
  src/components/multi-action-button/__snapshots__/multi-action-button.spec.tsx.snap
  src/components/multi-action-button/multi-action-button.component.tsx
  src/components/multi-action-button/multi-action-button.pw.tsx
  src/components/multi-action-button/multi-action-button.spec.tsx
  src/components/popover-container/popover-container.component.tsx
  src/components/popover-container/popover-container.pw.tsx
  src/components/popover-container/popover-container.spec.tsx
  src/components/split-button/split-button-toggle.style.ts
  src/components/split-button/split-button.component.tsx
  src/components/split-button/split-button.pw.tsx
  src/components/split-button/split-button.spec.tsx
  src/hooks/__internal__/useChildButtons/useChildButtons.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6716 chore(split-button): convert enzyme tests to rtl FE-5551
  src/components/button/button.style.ts
  src/components/split-button/split-button.pw.tsx
  src/components/split-button/split-button.spec.tsx
  src/components/split-button/split-button.test.tsx
Labels: Pending Review, Passed QA, No UX QA Required, Squad Front End

#6680 fix(filterable-select, simple-select): ensure an ellipsis is shown during text overflow
  src/__internal__/input/input.component.tsx
  src/__internal__/input/input.spec.tsx
  src/__internal__/input/input.style.ts
  src/components/pager/pager.style.ts
  src/components/select/__internal__/select-text/select-text.component.tsx
  src/components/select/__internal__/select-text/select-text.spec.tsx
  src/components/select/__internal__/select-text/select-text.style.ts
  src/components/select/filterable-select/filterable-select-test.stories.tsx
  src/components/select/select-textbox/select-textbox-context.ts
  src/components/select/select-textbox/select-textbox.component.tsx
  src/components/select/simple-select/simple-select-test.stories.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6681 fix(action-popover): submenu is left aligned in the 'with submenu aligned right' story
  src/components/action-popover/action-popover.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6717 feat(typography): add support for wordBreak property FE-6531
  src/components/typography/typography.component.tsx
  src/components/typography/typography.spec.tsx
  src/components/typography/typography.style.ts
Labels: Passed Review, Passed QA, No UX QA Required, third-party

#6714 fix(toast): remove default value on isCenter prop, add default value of "center" to align prop FE-6537
  playwright/components/carousel/index.ts
  playwright/components/carousel/locators.ts
  playwright/components/step-sequence/index.ts
  playwright/components/step-sequence/locators.ts
  src/components/carbon-provider/carbon-provider.pw.tsx
  src/components/carousel/carousel-test.stories.tsx
  src/components/carousel/carousel.component.tsx
  src/components/carousel/carousel.mdx
  src/components/carousel/carousel.pw.tsx
  src/components/carousel/carousel.spec.tsx
  src/components/carousel/carousel.stories.tsx
  src/components/carousel/carousel.style.ts
  src/components/carousel/components.test-pw.tsx
  src/components/carousel/index.ts
  src/components/carousel/slide.config.ts
  src/components/carousel/slide/index.ts
  src/components/carousel/slide/slide.component.tsx
  src/components/carousel/slide/slide.stories.tsx
  src/components/carousel/slide/slide.style.ts
  src/components/dialog/components.test-pw.tsx
  src/components/dialog/dialog.pw.tsx
  src/components/portal/__snapshots__/portal.spec.tsx.snap
  src/components/portal/portal.tsx
  src/components/step-sequence/__snapshots__/step-sequence.spec.tsx.snap
  src/components/step-sequence/components.test-pw.tsx
  src/components/step-sequence/index.ts
  src/components/step-sequence/step-sequence-item/index.ts
  src/components/step-sequence/step-sequence-item/step-sequence-item.component.tsx
  src/components/step-sequence/step-sequence-item/step-sequence-item.spec.tsx
  src/components/step-sequence/step-sequence-item/step-sequence-item.stories.tsx
  src/components/step-sequence/step-sequence-item/step-sequence-item.style.ts
  src/components/step-sequence/step-sequence-test.stories.tsx
  src/components/step-sequence/step-sequence.component.tsx
  src/components/step-sequence/step-sequence.config.ts
  src/components/step-sequence/step-sequence.mdx
  src/components/step-sequence/step-sequence.pw.tsx
  src/components/step-sequence/step-sequence.spec.tsx
  src/components/step-sequence/step-sequence.stories.tsx
  src/components/step-sequence/step-sequence.style.ts
  src/components/toast/components.test-pw.tsx
  src/components/toast/toast-test.stories.tsx
  src/components/toast/toast.component.tsx
  src/components/toast/toast.mdx
  src/components/toast/toast.pw.tsx
  src/components/toast/toast.spec.tsx
  src/components/toast/toast.stories.tsx
  src/components/toast/toast.style.ts
  src/components/toast/toast.test.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6733 chore(badge): convert enzyme tests to RTL
  src/components/badge/badge.component.tsx
  src/components/badge/badge.pw.tsx
  src/components/badge/badge.spec.tsx
  src/components/badge/badge.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6726 feat(split-button, multi-action-button): add position prop
  src/components/multi-action-button/multi-action-button-test.stories.tsx
  src/components/multi-action-button/multi-action-button.component.tsx
  src/components/multi-action-button/multi-action-button.config.ts
  src/components/multi-action-button/multi-action-button.mdx
  src/components/multi-action-button/multi-action-button.pw.tsx
  src/components/multi-action-button/multi-action-button.stories.tsx
  src/components/split-button/split-button-test.stories.tsx
  src/components/split-button/split-button.component.tsx
  src/components/split-button/split-button.config.ts
  src/components/split-button/split-button.mdx
  src/components/split-button/split-button.pw.tsx
  src/components/split-button/split-button.stories.tsx
  src/components/split-button/split-button.test.tsx
Labels: Passed Review, Passed UX QA, Squad Front End

#6736 fix(toast): margin-top on notice variant prevents elements being clicked
  src/components/toast/toast-test.stories.tsx
  src/components/toast/toast.style.ts
  src/components/toast/toast.test.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6738 chore(confirm): convert enzyme tests to RTL
  src/components/confirm/confirm.spec.tsx
  src/components/confirm/confirm.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6663 fix(scrollable-block): ensure border-styling is applied when appropriate to do so
  src/components/menu/__internal__/submenu/submenu.component.tsx
  src/components/menu/__internal__/submenu/submenu.spec.tsx
  src/components/menu/__internal__/submenu/submenu.style.ts
  src/components/menu/component.test-pw.tsx
  src/components/menu/menu.pw.tsx
Labels: Pending Review, Passed QA, Pending UX QA, Squad Front End

#6745 chore(date, date-range): update docs for locale imports
  src/components/date-range/date-range.mdx
  src/components/date/date.mdx
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#6728 fix(accordion): ensure disableContentPadding works with subtle variant
  src/components/accordion/accordion-test.stories.tsx
  src/components/accordion/accordion.spec.tsx
  src/components/accordion/accordion.style.ts
  src/components/accordion/components.test-pw.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6735 feat(textarea): remove redundant props
  src/components/textarea/textarea-test.stories.tsx
  src/components/textarea/textarea.component.tsx
  src/components/textarea/textarea.pw.tsx
  src/components/textarea/textarea.spec.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End, textarea

#6751 docs(anchor-navigation): update createRef to useRef in quick start section - FE-6594
  src/components/anchor-navigation/anchor-navigation.mdx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6748 fix(card): ensure that focus outline wraps all card content when `height` prop is set
  src/components/card/card-test.stories.tsx
  src/components/card/card.pw.tsx
  src/components/card/card.style.ts
  src/components/card/components.test-pw.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6737 chore(button-bar): convert enzyme test to rtl
  src/components/button-bar/button-bar.spec.tsx
  src/components/button-bar/button-bar.test.tsx
  src/components/icon-button/icon-button.component.tsx
  src/components/icon-button/icon-button.spec.tsx
Labels: Passed Review, No QA Required, No UX QA Required

#6753 chore(hr): convert tests from enzyme to RTL - FE-6599
  src/components/hr/hr.component.tsx
  src/components/hr/hr.spec.tsx
  src/components/hr/hr.test.tsx
Labels: Pending Review, Pending QA, No UX QA Required, Squad Front End
