Repository Sage/carbon, pull requests merged in 2024-11, with the labels that each got.

#7050 docs(flex-tile-cell): add missing props to FlexTileCell prop table
  src/components/tile/flex-tile-cell/flex-tile-cell.stories.tsx
  src/components/tile/flex-tile-cell/flex-tile-cell.test.tsx
  src/components/tile/tile.mdx
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#7055 fix(text-editor): add aria-pressed attribute to toolbar buttons
  src/components/text-editor/__internal__/toolbar/toolbar-button/toolbar-button.component.tsx
  src/components/text-editor/text-editor.pw.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7021 docs(storybook): fixes a number of accessibility issues in the documentation
  .storybook/main.ts
  .storybook/manager-head.html
  .storybook/preview-head.html
  .storybook/preview.ts
  .storybook/sage-docs-theme.ts
  .storybook/welcome-page/components-demo/component-heading/component-heading.component.js
  .storybook/welcome-page/components-demo/component-heading/component-heading.style.js
  .storybook/welcome-page/components-demo/demo/demo-table/demo-table.component.js
  .storybook/welcome-page/components-demo/demo/demo.component.js
  .storybook/welcome-page/loves-carbon/loves-carbon.component.js
  .storybook/welcome-page/loves-carbon/loves-carbon.style.js
  .storybook/welcome-page/selling-points/selling-point-panel.component.js
  CHANGELOG.md
  src/components/breadcrumbs/breadcrumbs.stories.tsx
  src/components/card/card.stories.tsx
  src/components/definition-list/definition-list.stories.tsx
  src/components/drawer/drawer.stories.tsx
  src/components/flat-table/flat-table.component.tsx
  src/components/flat-table/flat-table.stories.tsx
  src/components/flat-table/flat-table.test.tsx
  src/components/global-header/global-header.stories.tsx
  src/components/icon/icon.stories.tsx
  src/components/link/link.stories.tsx
  src/components/pages/pages.stories.tsx
  src/components/pod/pod.stories.tsx
  src/components/popover-container/popover-container.mdx
  src/components/step-flow/step-flow.stories.tsx
  src/components/vertical-menu/vertical-menu.stories.tsx
Labels: Passed Review, Passed QA, Accessibility, Passed UX QA, Squad Front End

#7023 feat(switch): enhances Switch component to allow inline variant in new validation redesign
  src/__internal__/checkable-input/checkable-input.style.ts
  src/__internal__/label/label.component.tsx
  src/__internal__/label/label.style.ts
  src/__internal__/label/label.test.tsx
  src/__internal__/validation-message/validation-message.component.tsx
  src/__internal__/validation-message/validation-message.style.ts
  src/__internal__/validation-message/validation-message.test.tsx
  src/components/switch/__internal__/switch-slider-panel.style.ts
  src/components/switch/__internal__/switch-slider-panel.test.tsx
  src/components/switch/__internal__/switch-slider.component.tsx
  src/components/switch/__internal__/switch-slider.style.ts
  src/components/switch/__internal__/switch-slider.test.tsx
  src/components/switch/switch.component.tsx
  src/components/switch/switch.mdx
  src/components/switch/switch.stories.tsx
  src/components/switch/switch.style.ts
  src/components/switch/switch.test.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End, switch

#7056 docs(dialog-full-screen): fix complex example so that both groups of tabs work - FE-3672
  src/components/dialog-full-screen/dialog-full-screen.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7040 feat(date, date-range): provides a mechanism that allows consumers to override the format of dates
  src/components/date-range/date-range.component.tsx
  src/components/date-range/date-range.mdx
  src/components/date-range/date-range.stories.tsx
  src/components/date-range/date-range.test.tsx
  src/components/date/__internal__/date-formats/date-formats.test.ts
  src/components/date/__internal__/date-formats/index.ts
  src/components/date/date-test.stories.tsx
  src/components/date/date.component.tsx
  src/components/date/date.mdx
  src/components/date/date.stories.tsx
  src/components/date/date.test.tsx
  src/locales/de-de.ts
  src/locales/en-ca.ts
  src/locales/en-gb.ts
  src/locales/en-us.ts
  src/locales/es-es.ts
  src/locales/fr-ca.ts
  src/locales/fr-fr.ts
  src/locales/locale.ts
Labels: Passed Review, Passed QA, No UX QA Required, date-range, date, Squad Turing

#7060 feat(select): update styles of transparent variant to align with frozen design system
  src/components/select/__internal__/select-textbox/select-textbox.style.ts
  src/components/select/simple-select/simple-select.mdx
  src/components/select/simple-select/simple-select.stories.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#7063 feat(carbon-provider): add deprecation warning for roundedCornersOptOut & focusRedesignOptOut
  src/components/carbon-provider/__internal__/new-validation.context.ts
  src/components/carbon-provider/carbon-provider.component.tsx
  src/components/carbon-provider/carbon-provider.test.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7068 fix(sidebar): ensure that aria-labelledby is applied to the correct piece of content in the header - FE-6891
  src/components/sidebar/__internal__/sidebar-header/sidebar-header.component.tsx
  src/components/sidebar/sidebar.test.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End, Passed a11y Review

#7029 fix(tabs): support for post-rebrand validation pattern
  src/components/tabs/__internal__/tab-title/tab-title.component.tsx
  src/components/tabs/__internal__/tab-title/tab-title.style.ts
  src/components/tabs/__internal__/tabs-header/tabs-header.component.tsx
  src/components/tabs/__internal__/tabs-header/tabs-header.style.ts
  src/components/tabs/tabs.mdx
  src/components/tabs/tabs.stories.tsx
  src/components/tabs/tabs.test.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#7079 chore: upgrade react-dnd to v16
  jest.config.ts
  package-lock.json
  package.json
  src/components/card/card-test.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required

#7075 test(file-input): onchange test windows fix
  src/components/file-input/file-input.pw.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7083 Remove cross-env and replace cross platform environment reading with dotenv
  .env
  .storybook/withThemeProvider.js
  package-lock.json
  package.json
  scripts/build-storybook.js
  scripts/debug-storybook.js
  scripts/start-storybook.js
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7094 chore: build script no longer uses cross-env and args can be passed t…
  scripts/build-storybook.js
  scripts/build.js
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#7087 fix(navigation-bar): convert fixed height to min-height to allow wrapped text to extend correctly
  src/components/global-header/global-header.pw.tsx
  src/components/navigation-bar/navigation-bar-test.stories.tsx
  src/components/navigation-bar/navigation-bar.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#7081 fix(select-list): selected option not scrolled into view
  src/components/select/__internal__/select-list/select-list.component.tsx
  src/components/select/simple-select/simple-select.pw.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#7071 fix(select): ensure that aria-describedby is applied to the select-textbox element - FE-6889
  src/components/select/__internal__/select-textbox/select-textbox.component.tsx
  src/components/select/filterable-select/filterable-select-test.stories.tsx
  src/components/select/multi-select/multi-select-test.stories.tsx
  src/components/select/simple-select/simple-select-test.stories.tsx
  src/components/select/simple-select/simple-select.component.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End, Passed a11y Review

#7103 fix(sidebar): make sidebar-heading element 100% width
  src/components/sidebar/__internal__/sidebar-header/sidebar-header.style.ts
  src/components/sidebar/sidebar-test.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End
