Repository Sage/carbon, pull requests merged in 2024-01, with the labels that each got.

#6449 feat(numeral-date): add date format and update to align with DS
  cypress/components/numeral-date/numeral-date.cy.tsx
  cypress/locators/numeralDate/index.js
  src/components/numeral-date/numeral-date.component.tsx
  src/components/numeral-date/numeral-date.spec.tsx
  src/components/numeral-date/numeral-date.stories.mdx
  src/components/numeral-date/numeral-date.stories.tsx
  src/components/numeral-date/numeral-date.style.ts
  src/locales/en-gb.ts
  src/locales/locale.ts
  src/locales/pl-pl.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6457 test(numeral-date): convert cypress tests to playwright
  cypress/components/numeral-date/numeral-date.cy.tsx
  cypress/locators/numeralDate/index.js
  cypress/locators/numeralDate/locators.js
  playwright/components/numeral-date/index.ts
  playwright/components/numeral-date/locators.ts
  src/components/numeral-date/components.test-pw.tsx
  src/components/numeral-date/numeral-date-test.stories.tsx
  src/components/numeral-date/numeral-date.pw.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6494 test(pages): convert tests to playwright - FE-6142
  cypress/components/pages/pages.cy.tsx
  playwright/components/pages/index.ts
  src/components/pages/components.test-pw.tsx
  src/components/pages/pages-test.stories.tsx
  src/components/pages/pages.pw.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6483 feat(progress-tracker): add inline label and label width prop
  src/components/progress-tracker/progress-tracker-test.stories.tsx
  src/components/progress-tracker/progress-tracker.component.tsx
  src/components/progress-tracker/progress-tracker.pw.tsx
  src/components/progress-tracker/progress-tracker.spec.tsx
  src/components/progress-tracker/progress-tracker.stories.mdx
  src/components/progress-tracker/progress-tracker.stories.tsx
  src/components/progress-tracker/progress-tracker.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6500 docs: replace Formik/Yup example and add explanatory notes
  docs/validations.stories.mdx
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#6497 test(sidebar): convert tests to playwright - FE-6165
  cypress/components/sidebar/sidebar.cy.tsx
  cypress/locators/sidebar/index.js
  cypress/locators/sidebar/locators.js
  playwright/components/index.ts
  playwright/components/sidebar/index.ts
  playwright/components/sidebar/locators.ts
  src/components/sidebar/components.test-pw.tsx
  src/components/sidebar/sidebar-test.stories.tsx
  src/components/sidebar/sidebar.pw.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6501 test(number): refactor number from cypress to playwright
  cypress/components/number/number.cy.tsx
  playwright/components/index.ts
  playwright/components/number/index.ts
  playwright/components/number/locators.ts
  src/components/number/components.test-pw.tsx
  src/components/number/number-test.stories.tsx
  src/components/number/number.pw.tsx
  src/components/textbox/textbox.pw.tsx
Labels: Pending Review, Passed QA, No UX QA Required, Squad Front End, number, playwright

#6509 test(simple-color-picker): convert cypress tests to playwright
  cypress/components/simple-color-picker/simple-color-picker.cy.tsx
  cypress/locators/simple-color-picker/index.js
  cypress/locators/simple-color-picker/locators.js
  playwright/components/advanced-color-picker/index.ts
  playwright/components/simple-color-picker/index.ts
  playwright/components/simple-color-picker/locators.ts
  src/components/advanced-color-picker/advanced-color-picker.pw.tsx
  src/components/simple-color-picker/components.test-pw.tsx
  src/components/simple-color-picker/simple-color-picker-test.stories.tsx
  src/components/simple-color-picker/simple-color-picker.pw.tsx
Labels: Pending Review, No QA Required, Squad Front End

#6503 fix(select): stop list scrolling to selected option unless it has changed
  src/components/select/filterable-select/filterable-select.pw.tsx
  src/components/select/select-list/select-list.component.tsx
  src/components/select/simple-select/simple-select.pw.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6475 chore(card, card-row, card-column, card-footer): add data attribute support FE-4916
  .storybook/locale-selector/index.js
  playwright/components/card/index.ts
  playwright/components/card/locators.ts
  src/components/card/__internal__/card-context/index.ts
  src/components/card/card-column/card-column.component.tsx
  src/components/card/card-column/card-column.spec.tsx
  src/components/card/card-footer/__snapshots__/card-footer.spec.tsx.snap
  src/components/card/card-footer/card-footer.component.tsx
  src/components/card/card-footer/card-footer.spec.tsx
  src/components/card/card-footer/card-footer.style.ts
  src/components/card/card-row/card-row.component.tsx
  src/components/card/card-row/card-row.spec.tsx
  src/components/card/card-row/card-row.style.ts
  src/components/card/card-test.stories.tsx
  src/components/card/card.component.tsx
  src/components/card/card.pw.tsx
  src/components/card/card.spec.tsx
  src/components/card/card.stories.mdx
  src/components/card/card.stories.tsx
  src/components/card/card.style.ts
  src/components/card/components.test-pw.tsx
  src/components/detail/detail.stories.tsx
  src/locales/__internal__/pl-pl.spec.tsx
  src/locales/__internal__/pl-pl.ts
  src/locales/index.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6502 fix(menu-fullscreen): ensure that custom padding is applied to submenu items inside menu fullscreen
  src/components/menu/menu-full-screen/menu-full-screen.spec.tsx
  src/components/menu/menu-test.stories.tsx
  src/components/menu/menu.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6495 test(tabs): convert cypress tests to playwright
  cypress/components/tabs/tabs.cy.tsx
  cypress/locators/tabs/index.js
  playwright/components/tabs/index.ts
  src/components/tabs/components.test-pw.tsx
  src/components/tabs/tabs-test.stories.tsx
  src/components/tabs/tabs.pw.tsx
  src/components/tabs/tabs.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6504 fix(numeral-date): ensure internal validation uses given month and year values where possible
  playwright/index.tsx
  src/components/numeral-date/numeral-date.component.tsx
  src/components/numeral-date/numeral-date.pw.tsx
  src/components/numeral-date/numeral-date.spec.tsx
  src/components/numeral-date/numeral-date.stories.tsx
  src/locales/__internal__/pl-pl.ts
  src/locales/en-gb.ts
  src/locales/locale.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6486 feat(popover-container): add prop to disable animation - FE-5881
  cypress/components/popover-container/popover-container.cy.tsx
  src/__internal__/popover/popover.component.tsx
  src/components/popover-container/popover-container-test.stories.tsx
  src/components/popover-container/popover-container.component.tsx
  src/components/popover-container/popover-container.spec.tsx
  src/components/popover-container/popover-container.stories.mdx
  src/components/popover-container/popover-container.stories.tsx
  src/components/popover-container/popover-container.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6532 test(popover-container): pass disableAnimation prop to component and instead of styled-component - (FE-6336)
  src/components/popover-container/popover-container.spec.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6510 fix(flat-table): ensure that pressing arrow and space keys scroll table when it is scrollable FE-6273
  cypress/components/flat-table/flat-table.cy.tsx
  src/components/flat-table/flat-table-expandable.stories.tsx
  src/components/flat-table/flat-table.component.tsx
  src/components/flat-table/flat-table.spec.tsx
  src/components/flat-table/flat-table.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6520 fix(link): focus underline fix
  src/components/link/link.pw.tsx
  src/components/link/link.style.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6512 test(pager): playwright refactor
  cypress/components/pager/pager.cy.tsx
  cypress/locators/pager/index.js
  playwright/components/pager/index.ts
  playwright/components/pager/locators.ts
  src/components/pager/components.test-pw.tsx
  src/components/pager/pager-test.stories.tsx
  src/components/pager/pager.pw.tsx
Labels: Pending Review, Passed QA, No UX QA Required, Squad Front End, pager, playwright

#6537 chore: upgrade vite
  package-lock.json
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6482 feat(option, option-row): add disabled prop
  src/components/select/filterable-select/components.test-pw.tsx
  src/components/select/filterable-select/filterable-select-test.stories.tsx
  src/components/select/filterable-select/filterable-select.component.tsx
  src/components/select/filterable-select/filterable-select.pw.tsx
  src/components/select/multi-select/components.test-pw.tsx
  src/components/select/multi-select/multi-select-test.stories.tsx
  src/components/select/multi-select/multi-select.pw.tsx
  src/components/select/option-row/option-row.component.tsx
  src/components/select/option-row/option-row.spec.tsx
  src/components/select/option-row/option-row.style.ts
  src/components/select/option/option.component.tsx
  src/components/select/option/option.spec.tsx
  src/components/select/option/option.style.ts
  src/components/select/select-list/select-list.component.tsx
  src/components/select/select-list/select-list.spec.tsx
  src/components/select/simple-select/simple-select-test.stories.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6469 feat(filterable-select): add disableDefaultFiltering prop
  src/components/select/filterable-select/filterable-select.component.tsx
  src/components/select/filterable-select/filterable-select.spec.tsx
  src/components/select/filterable-select/filterable-select.stories.mdx
  src/components/select/filterable-select/filterable-select.stories.tsx
Labels: Passed Review, Passed QA

#6515 feat(inline-inputs): add labelAlign prop
  src/components/inline-inputs/inline-inputs.component.tsx
  src/components/inline-inputs/inline-inputs.pw.tsx
  src/components/inline-inputs/inline-inputs.spec.tsx
  src/components/inline-inputs/inline-inputs.stories.mdx
  src/components/inline-inputs/inline-inputs.stories.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6524 fix(flat-table): ensure that focus size is correctly applied in Safari - FE-6315
  src/components/flat-table/flat-table-row/flat-table-row.component.tsx
  src/components/flat-table/flat-table-row/flat-table-row.spec.tsx
  src/components/flat-table/flat-table-row/flat-table-row.style.ts
  src/components/flat-table/flat-table-test.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6539 feat(preview): add rounded corners styling to component - FE-6056
  src/components/preview/__internal__/preview-placeholder.style.ts
  src/components/preview/preview.pw.tsx
  src/components/preview/preview.spec.tsx
Labels: Passed Review, Passed QA, Pending UX QA, Squad Front End

#6547 chore(playwright): shard test suite in github actions workflow
  .github/workflows/chromatic-push.yml
  .github/workflows/chromatic.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/cypress.yml
  .github/workflows/playwright.yml
  .github/workflows/semantic-commit-lint.yml
  .github/workflows/semantic-release.yml
  .github/workflows/storybook.yml
  .gitignore
  .husky/post-checkout
  playwright-ct.config.ts
  src/components/action-popover/action-popover.pw.tsx
  src/components/action-popover/components.test-pw.tsx
  src/global.d.ts
Labels: Pending Review, Pending QA, No UX QA Required, Squad Front End

#6506 feat(accordion): add subtle variant and update default styles
  src/components/accordion/accordion-test.stories.tsx
  src/components/accordion/accordion.component.tsx
  src/components/accordion/accordion.pw.tsx
  src/components/accordion/accordion.spec.tsx
  src/components/accordion/accordion.stories.mdx
  src/components/accordion/accordion.stories.tsx
  src/components/accordion/accordion.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6540 feat(time): add new component
  playwright/support/helper.ts
  src/__internal__/fieldset/fieldset.component.tsx
  src/__internal__/fieldset/fieldset.spec.tsx
  src/__internal__/fieldset/fieldset.style.ts
  src/__internal__/label/label.component.tsx
  src/components/box/box.component.tsx
  src/components/button-toggle/button-toggle-group/button-toggle-group.component.tsx
  src/components/button-toggle/button-toggle.style.ts
  src/components/time/__internal__/time-toggle/index.ts
  src/components/time/__internal__/time-toggle/time-toggle.component.tsx
  src/components/time/__internal__/time-toggle/time-toggle.style.ts
  src/components/time/components.test-pw.tsx
  src/components/time/index.ts
  src/components/time/time.component.tsx
  src/components/time/time.pw.tsx
  src/components/time/time.spec.tsx
  src/components/time/time.stories.mdx
  src/components/time/time.stories.tsx
  src/components/time/time.style.ts
  src/components/typography/typography.component.tsx
  src/components/typography/typography.style.ts
  src/locales/__internal__/pl-pl.ts
  src/locales/en-gb.ts
  src/locales/locale.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End, Passed a11y Review

#6507 feat(image): add position prop to component - FE-6226
  docs/extending-styles-using-styled-components.stories.mdx
  docs/extending-styles-using-styled-system.stories.mdx
  src/components/box/box.component.tsx
  src/components/image/image.component.tsx
  src/components/image/image.pw.tsx
  src/components/image/image.spec.tsx
  src/components/image/image.stories.mdx
  src/components/image/image.stories.tsx
  src/components/image/image.style.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6522 test(split-button): playwright refactor
  cypress/components/split-button/split-button.cy.tsx
  cypress/locators/split-button/index.js
  cypress/locators/split-button/locators.js
  playwright/components/split-button/index.ts
  src/components/split-button/components.test-pw.tsx
  src/components/split-button/split-button-test.stories.tsx
  src/components/split-button/split-button.pw.tsx
Labels: Pending Review, Passed QA, No UX QA Required, Squad Front End, split-button, playwright

#6508 fix(dialog + icon): fix color for modal and dialog responsive size an…
  src/components/carbon-provider/carbon-provider.pw.tsx
  src/components/dialog/dialog.style.ts
  src/components/icon/__snapshots__/icon-unicodes.spec.js.snap
  src/components/icon/fonts/carbon-icons-webfont.woff
  src/components/icon/icon-config.ts
  src/components/icon/icon-type.ts
  src/components/icon/icon-unicodes.js
  src/components/modal/modal.style.ts
  src/components/tabs/__internal__/tab-title/tab-title.spec.tsx
  src/components/tabs/__internal__/tab-title/tab-title.style.ts
  src/components/tabs/tab/tab.spec.tsx
  src/components/tabs/tab/tab.style.ts
  src/components/tabs/tabs.stories.tsx
  src/style/assets/carbon-icons-webfont.woff
Labels: Passed Review, Passed QA, Passed UX QA, Squad Experience Platform

#6558 ci: remove codesandbox config
  .codesandbox/ci.json
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End
