Repository Sage/carbon, pull requests merged in 2024-02, with the labels that each got.

#6562 fix(numeral-date): ensure it uses static validation when no month value passed
  src/components/numeral-date/numeral-date.component.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6549 test(popover-container): convert tests to playwright - FE-6146
  cypress/components/popover-container/popover-container.cy.tsx
  cypress/locators/popover-container/index.js
  playwright/components/popover-container/index.ts
  playwright/components/popover-container/locators.ts
  src/components/popover-container/components.test-pw.tsx
  src/components/popover-container/popover-container-test.stories.tsx
  src/components/popover-container/popover-container.pw.tsx
Labels: Pending Review, Passed QA, No UX QA Required, Squad Front End

#6542 fix(pages): maintain height of content when page slides in
  src/components/pages/page/page.style.ts
  src/components/pages/pages-test.stories.tsx
  src/components/pages/pages.component.tsx
  src/components/pages/pages.config.ts
  src/components/pages/pages.pw.tsx
  src/components/pages/pages.style.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6551 test(vertical-menu): playwright refactor
  cypress/components/vertical-menu/vertical-menu.cy.tsx
  cypress/locators/vertical-menu/index.js
  playwright/components/vertical-menu/index.ts
  playwright/components/vertical-menu/locators.ts
  src/components/vertical-menu/components.test-pw.tsx
  src/components/vertical-menu/vertical-menu-test.stories.tsx
  src/components/vertical-menu/vertical-menu.pw.tsx
Labels: Pending Review, Passed QA, No UX QA Required, Squad Front End, vertical-menu, playwright

#6573 chore: remove cypress split and cypress mochawesome reporter
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/cypress.yml
  cypress.config.ts
  cypress/support/component.ts
  package-lock.json
  package.json
Labels: Passed Review, Pending QA, No UX QA Required

#6429 feat(pill): add information variant and dark background color variants
  package-lock.json
  package.json
  src/components/pill/components.test-pw.tsx
  src/components/pill/pill-test.stories.tsx
  src/components/pill/pill.component.tsx
  src/components/pill/pill.pw.tsx
  src/components/pill/pill.spec.tsx
  src/components/pill/pill.stories.mdx
  src/components/pill/pill.stories.tsx
  src/components/pill/pill.style.config.ts
  src/components/pill/pill.style.ts
  src/components/portal/__snapshots__/portal.spec.tsx.snap
  src/components/tooltip/tooltip.pw.tsx
  src/style/design-tokens/carbon-scoped-tokens-provider/__snapshots__/carbon-scoped-tokens-provider.component.spec.tsx.snap
  src/style/themes/aegean/__snapshots__/aegean-theme.spec.ts.snap
  src/style/themes/mint/__snapshots__/mint-theme.spec.ts.snap
  src/style/themes/none/__snapshots__/none.spec.ts.snap
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6481 feat(step-flow): add new component
  playwright/components/step-flow/index.ts
  playwright/components/step-flow/locators.ts
  src/components/step-flow/components.test-pw.tsx
  src/components/step-flow/index.ts
  src/components/step-flow/step-flow-test.stories.tsx
  src/components/step-flow/step-flow.component.tsx
  src/components/step-flow/step-flow.pw.tsx
  src/components/step-flow/step-flow.spec.tsx
  src/components/step-flow/step-flow.stories.mdx
  src/components/step-flow/step-flow.stories.tsx
  src/components/step-flow/step-flow.style.ts
  src/components/typography/index.ts
  src/components/typography/typography.component.tsx
  src/locales/__internal__/pl-pl.ts
  src/locales/en-gb.ts
  src/locales/locale.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End, Passed a11y Review

#6565 docs: replace codesandbox references with stackblitz
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  docs/installation.stories.mdx
  docs/usage.stories.mdx
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#6575 chore(github): fix yaml errors in templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: Pending Review, No QA Required, No UX QA Required

#6526 fix(select): maintain option ids according to key when children count changes
  src/components/select/option-group-header/__snapshots__/option-group-header.spec.tsx.snap
  src/components/select/option-group-header/option-group-header.component.tsx
  src/components/select/option-group-header/option-group-header.spec.tsx
  src/components/select/option-row/option-row.component.tsx
  src/components/select/option/__snapshots__/option.spec.tsx.snap
  src/components/select/option/option.component.tsx
  src/components/select/option/option.spec.tsx
  src/components/select/select-list/select-list.component.tsx
  src/components/select/simple-select/components.test-pw.tsx
  src/components/select/simple-select/simple-select.pw.tsx
  src/components/select/simple-select/simple-select.stories.mdx
  src/components/select/simple-select/simple-select.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6556 feat(text-editor): make container of toolbarElements a flex container for responsiveness (FE-6337 and FE-6340)
  cypress/components/text-editor/text-editor.cy.tsx
  src/components/portal/__snapshots__/portal.spec.tsx.snap
  src/components/portal/portal.style.ts
  src/components/portal/portal.tsx
  src/components/text-editor/__internal__/toolbar/toolbar-button/toolbar-button.spec.tsx
  src/components/text-editor/__internal__/toolbar/toolbar-button/toolbar-button.style.ts
  src/components/text-editor/__internal__/toolbar/toolbar.component.tsx
  src/components/text-editor/__internal__/toolbar/toolbar.spec.tsx
  src/components/text-editor/__internal__/toolbar/toolbar.style.ts
  src/components/text-editor/text-editor-test.stories.tsx
  src/components/text-editor/text-editor.spec.tsx
  src/components/text-editor/text-editor.stories.mdx
  src/components/text-editor/text-editor.stories.tsx
  src/components/text-editor/text-editor.style.ts
  src/components/tooltip/__snapshots__/tooltip.spec.tsx.snap
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6566 fix(split-button): fix style when href is passed to a button
  src/components/multi-action-button/multi-action-button.style.ts
  src/components/split-button/split-button-children.style.ts
  src/components/split-button/split-button.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6527 fix(date): prevent dialog from closing if esc is pressed and date picker is open
  src/components/date/__internal__/date-picker/date-picker.component.tsx
  src/components/date/components.test-pw.tsx
  src/components/date/date.component.tsx
  src/components/date/date.pw.tsx
  src/components/date/date.spec.tsx
Labels: Passed Review, Passed QA, Squad Front End

#6560 test(portrait): failing color contrast accessibility tests fix
  src/components/portrait/portrait.pw.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6568 test(tile select): add tests for playwright
  cypress/components/tile-select/tile-select.cy.tsx
  cypress/components/vertical-divider/vertical-divider.cy.tsx
  playwright/components/tileSelect/index.ts
  playwright/components/tileSelect/locators.ts
  src/components/tile-select/components.test-pw.tsx
  src/components/tile-select/tile-select-test.stories.tsx
  src/components/tile-select/tile-select.pw.tsx
Labels: Pending Review, Passed QA, Squad Front End, tile-select, playwright

#6543 feat(portal): add inertOptOut prop to keep the content interactable when a modal opens
  src/components/portal/__snapshots__/portal.spec.tsx.snap
  src/components/portal/components.test-pw.tsx
  src/components/portal/portal.pw.tsx
  src/components/portal/portal.tsx
  src/hooks/__internal__/useModalAria/useModalAria.spec.tsx
  src/hooks/__internal__/useModalAria/useModalAria.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6546 fix: remove unused labelAlign prop from checkable input
  cypress/components/button-toggle/button-toggle.cy.tsx
  src/__internal__/checkable-input/checkable-input.component.tsx
  src/components/button-toggle/button-toggle-group/button-toggle-group.component.tsx
  src/components/button-toggle/button-toggle-group/button-toggle-group.spec.tsx
  src/components/checkbox/checkbox.component.tsx
  src/components/checkbox/checkbox.stories.tsx
  src/components/fieldset/components.test-pw.tsx
  src/components/fieldset/fieldset.stories.tsx
  src/components/form/form-test.stories.tsx
  src/components/radio-button/radio-button.component.tsx
  src/components/switch/switch-test.stories.tsx
  src/components/switch/switch.component.tsx
  src/components/switch/switch.pw.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6576 fix(message): reduce left padding of content for `transparent` variant
  src/components/message/message-content/__snapshots__/message-content.spec.tsx.snap
  src/components/message/message-content/message-content.component.tsx
  src/components/message/message-content/message-content.style.ts
  src/components/message/message.component.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6577 feat(textarea): add new borderRadius prop - FE-6363
  src/__internal__/input/__snapshots__/input-presentation.spec.tsx.snap
  src/__internal__/input/__snapshots__/input.spec.tsx.snap
  src/__internal__/input/input-presentation.component.tsx
  src/__internal__/input/input-presentation.style.ts
  src/__internal__/input/input.component.tsx
  src/__internal__/input/input.style.ts
  src/components/box/box.component.tsx
  src/components/textarea/textarea-test.stories.tsx
  src/components/textarea/textarea.component.tsx
  src/components/textarea/textarea.pw.tsx
  src/components/textarea/textarea.spec.tsx
  src/components/textarea/textarea.stories.mdx
  src/components/textarea/textarea.stories.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6557 docs(portal): add new documentation for component - FE-6322
  src/components/portal/portal.stories.mdx
  src/components/portrait/portrait.stories.mdx
  src/components/preview/preview.stories.mdx
  src/components/progress-tracker/progress-tracker.stories.mdx
  src/components/search/search.stories.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6579 feat(button): add new `gradient-white` and `gradient-grey` buttonTypes
  src/components/button/__snapshots__/button.spec.tsx.snap
  src/components/button/button-test.stories.tsx
  src/components/button/button-types.style.ts
  src/components/button/button.component.tsx
  src/components/button/button.config.ts
  src/components/button/button.pw.tsx
  src/components/button/button.spec.tsx
  src/components/button/button.stories.mdx
  src/components/button/button.stories.tsx
  src/components/button/button.style.ts
  src/components/button/components.test-pw.tsx
  src/components/multi-action-button/__snapshots__/multi-action-button.spec.tsx.snap
  src/components/select/list-action-button/__snapshots__/list-action-button.spec.tsx.snap
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6574 fix(pager): increase margin so focus style does not overlap text
  src/components/pager/__internal__/pager-navigation.spec.tsx
  src/components/pager/pager.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6585 docs: remove duplicate extending styles doc - FE-6376
  docs/extending-styles-using-styled-system.stories.mdx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6580 feat(loader): add gradient color to component
  src/components/loader/loader-square.spec.tsx
  src/components/loader/loader-square.style.ts
  src/components/loader/loader-test.stories.tsx
  src/components/loader/loader.component.tsx
  src/components/loader/loader.stories.mdx
  src/components/loader/loader.stories.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6589 docs(step-sequence): deprecate component
  src/components/step-sequence/step-sequence.component.tsx
  src/components/step-sequence/step-sequence.spec.tsx
  src/components/step-sequence/step-sequence.stories.mdx
Labels: Pending Review, No QA Required, No UX QA Required

#6564 fix(popover-container): ensure styling is correct when rendered as a child of menu
  src/__internal__/popover/popover.component.tsx
  src/components/popover-container/components.test-pw.tsx
  src/components/popover-container/popover-container-test.stories.tsx
  src/components/popover-container/popover-container.component.tsx
  src/components/popover-container/popover-container.pw.tsx
  src/components/popover-container/popover-container.stories.mdx
  src/components/popover-container/popover-container.stories.tsx
  src/hooks/__internal__/useFocusPortalContent/index.ts
  src/hooks/__internal__/useFocusPortalContent/useFocusPortalContent.spec.tsx
  src/hooks/__internal__/useFocusPortalContent/useFocusPortalContent.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6586 fix(checkbox, toast): fix bugs in stories
  src/components/checkbox/checkbox-validations.stories.tsx
  src/components/checkbox/checkbox.stories.tsx
  src/components/toast/toast.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6559 fix(textarea, textbox): ensure enterkeyhint attribute can be set
  src/__internal__/input/index.ts
  src/__internal__/input/input.component.tsx
  src/__internal__/input/input.spec.tsx
  src/components/textarea/textarea.spec.tsx
  src/components/textbox/textbox.spec.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6570 fix(filterable-select): ensure selectionConfirmed is false when enter pressed with no match
  src/components/select/filterable-select/components.test-pw.tsx
  src/components/select/filterable-select/filterable-select.component.tsx
  src/components/select/filterable-select/filterable-select.pw.tsx
  src/components/select/filterable-select/filterable-select.stories.tsx
  src/components/select/select-list/select-list.component.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6555 feat(image): add padding props
  src/components/image/image-test.stories.tsx
  src/components/image/image.spec.tsx
  src/components/image/image.stories.mdx
  src/components/image/image.style.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6534 fix(filterable-select): ensure onchange called when deleting text
  src/components/select/filterable-select/filterable-select-test.stories.tsx
  src/components/select/filterable-select/filterable-select.component.tsx
  src/components/select/filterable-select/filterable-select.spec.tsx
Labels: Passed Review, Pending QA, No UX QA Required, Squad Front End

#6528 fix(icon): bgSize and fontSize bug fix
  src/components/button-toggle/__snapshots__/button-toggle.spec.tsx.snap
  src/components/button-toggle/button-toggle-icon.component.tsx
  src/components/button-toggle/button-toggle.style.ts
  src/components/button/__snapshots__/button.spec.tsx.snap
  src/components/button/button.component.tsx
  src/components/card/card-footer/__snapshots__/card-footer.spec.tsx.snap
  src/components/flat-table/flat-table-cell/flat-table-cell.component.tsx
  src/components/flat-table/flat-table-cell/flat-table-cell.style.ts
  src/components/flat-table/flat-table-row-header/flat-table-row-header.component.tsx
  src/components/flat-table/flat-table-row-header/flat-table-row-header.style.ts
  src/components/icon/icon-test.stories.tsx
  src/components/icon/icon.component.tsx
  src/components/icon/icon.pw.tsx
  src/components/icon/icon.spec.tsx
  src/components/icon/icon.stories.mdx
  src/components/icon/icon.stories.tsx
  src/components/icon/icon.style.ts
  src/components/link/link.component.tsx
  src/components/link/link.spec.tsx
  src/components/link/link.style.ts
  src/components/menu/__internal__/submenu/submenu.style.ts
  src/components/menu/menu-item/menu-item.style.ts
  src/components/multi-action-button/__snapshots__/multi-action-button.spec.tsx.snap
  src/components/select/list-action-button/__snapshots__/list-action-button.spec.tsx.snap
  src/components/split-button/split-button.component.tsx
  src/components/split-button/split-button.spec.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6604 fix(form): remove 4px margin bottom from Textarea FormField
  src/components/form/form.spec.tsx
  src/components/form/form.style.ts
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6594 feat(icon): 2 icons added to the icon font
  src/components/icon/__snapshots__/icon-unicodes.spec.js.snap
  src/components/icon/fonts/carbon-icons-webfont.woff
  src/components/icon/icon-config.ts
  src/components/icon/icon-type.ts
  src/components/icon/icon-unicodes.js
  src/style/assets/carbon-icons-webfont.woff
Labels: Passed Review, Passed QA, Passed UX QA

#6605 fix(tile): ensure borderVariant overrides border color associated to variant prop
  src/components/tile/tile-test.stories.tsx
  src/components/tile/tile.config.ts
  src/components/tile/tile.pw.tsx
  src/components/tile/tile.spec.tsx
  src/components/tile/tile.style.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6583 feat(button-toggle): update styles
  cypress/components/button-toggle/button-toggle.cy.tsx
  src/components/button-toggle/__snapshots__/button-toggle.spec.tsx.snap
  src/components/button-toggle/button-toggle-group/button-toggle-group.component.tsx
  src/components/button-toggle/button-toggle-group/button-toggle-group.spec.tsx
  src/components/button-toggle/button-toggle-group/button-toggle-group.stories.tsx
  src/components/button-toggle/button-toggle-group/button-toggle-group.style.ts
  src/components/button-toggle/button-toggle-test.stories.tsx
  src/components/button-toggle/button-toggle.component.tsx
  src/components/button-toggle/button-toggle.spec.tsx
  src/components/button-toggle/button-toggle.stories.mdx
  src/components/button-toggle/button-toggle.stories.tsx
  src/components/button-toggle/button-toggle.style.ts
  src/components/time/__internal__/time-toggle/time-toggle.component.tsx
  src/components/time/__internal__/time-toggle/time-toggle.style.ts
  src/components/time/time.component.tsx
  src/components/time/time.pw.tsx
  src/components/time/time.spec.tsx
  src/components/time/time.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6606 feat(textarea): add prop to hide borders - FE-6385
  src/__internal__/input/input-presentation.component.tsx
  src/__internal__/input/input-presentation.spec.tsx
  src/__internal__/input/input-presentation.style.ts
  src/components/textarea/textarea-test.stories.tsx
  src/components/textarea/textarea.component.tsx
  src/components/textarea/textarea.pw.tsx
  src/components/textarea/textarea.spec.tsx
  src/components/textarea/textarea.stories.mdx
  src/components/textarea/textarea.stories.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6588 fix(tabs): remove negative margin to resolve scrollbar appearing
  src/components/tabs/__internal__/tabs-header/tabs-header.spec.tsx
  src/components/tabs/__internal__/tabs-header/tabs-header.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End
