Repository Sage/carbon, pull requests merged in 2024-09, with the labels that each got.

#6912 refactor(navigation-bar): convert enzyme tests to RTL
  src/components/global-header/global-header.pw.tsx
  src/components/global-header/global-header.test.tsx
  src/components/navigation-bar/navigation-bar-test.stories.tsx
  src/components/navigation-bar/navigation-bar.spec.tsx
  src/components/navigation-bar/navigation-bar.test.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6916 chore: consume JSDOM fix to enhance performance of `window.getComputedStyle`
  .github/workflows/ci.yml
  coverage-thresholds.json
  jest.config.json
  jest.config.ts
  package-lock.json
  package.json
  src/__internal__/form-field/form-field.spec.tsx
  src/__internal__/sticky-footer/sticky-footer.test.tsx
  src/__internal__/validations/validation-icon.component.tsx
  src/__spec_helper__/__internal__/index.ts
  src/components/box/box.test.tsx
  src/components/breadcrumbs/breadcrumbs.test.tsx
  src/components/button/button.test.tsx
  src/components/date-range/date-range.test.tsx
  src/components/date/__internal__/date-picker/date-picker.test.tsx
  src/components/date/date.test.tsx
  src/components/fieldset/fieldset.test.tsx
  src/components/icon/__snapshots__/icon-unicodes.spec.js.snap
  src/components/menu/__internal__/submenu/submenu.component.tsx
  src/components/menu/__internal__/submenu/submenu.test.tsx
  src/components/menu/menu-item/menu-item.test.tsx
  src/components/numeral-date/numeral-date.test.tsx
  src/components/simple-color-picker/simple-color/simple-color.spec.tsx
  src/components/switch/__internal__/__snapshots__/switch-slider.spec.tsx.snap
  src/hooks/__internal__/useClickAwayListener/useClickAwayListener.test.tsx
  src/hooks/__internal__/useFloating/useFloating.test.tsx
  src/style/design-tokens/carbon-scoped-tokens-provider/__snapshots__/carbon-scoped-tokens-provider.test.tsx.snap
  src/style/themes/none/__snapshots__/none.spec.ts.snap
  svgTransform.js
  svgTransform.mjs
  tsconfig-build.json
  tsconfig.json
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6928 chore: upgrade a transitive dependency
  .npmignore
  .vscode/launch.json
  package-lock.json
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6920 feat(flex-tile-container): add support for overriding the `overflow` styling
  src/components/tile/flex-tile-container/flex-tile-container.component.tsx
  src/components/tile/flex-tile-container/flex-tile-container.test.tsx
  src/components/tile/tile.mdx
  src/components/tile/tile.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6915 refactor(dialog-full-screen): convert tests to react-testing-library
  src/components/dialog-full-screen/dialog-full-screen.component.tsx
  src/components/dialog-full-screen/dialog-full-screen.spec.tsx
  src/components/dialog-full-screen/dialog-full-screen.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6927 refactor(inline-inputs): convert enzyme tests to RTL
  src/components/inline-inputs/inline-inputs.component.tsx
  src/components/inline-inputs/inline-inputs.spec.tsx
  src/components/inline-inputs/inline-inputs.stories.tsx
  src/components/inline-inputs/inline-inputs.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6932 refactor(pager): convert unit tests to react-testing-library
  src/components/pager/__internal__/pager-navigation.component.tsx
  src/components/pager/__internal__/pager-navigation.spec.tsx
  src/components/pager/__internal__/pager-navigation.test.tsx
  src/components/pager/pager.component.tsx
  src/components/pager/pager.spec.tsx
  src/components/pager/pager.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6931 refactor(help): convert enzyme tests to RTL
  src/components/help/help.spec.tsx
  src/components/help/help.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6929 refactor(form): convert tests to use react-testing-library
  src/components/form/__internal__/form-summary.component.tsx
  src/components/form/form-test.stories.tsx
  src/components/form/form.component.tsx
  src/components/form/form.spec.tsx
  src/components/form/form.stories.tsx
  src/components/form/form.test.tsx
  src/components/form/required-fields-indicator/required-fields-indicator.test.tsx
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#6941 refactor(character-count, field-help): convert enzyme tests to RTL
  src/__internal__/character-count/character-count.component.tsx
  src/__internal__/character-count/character-count.spec.tsx
  src/__internal__/character-count/character-count.test.tsx
  src/__internal__/field-help/field-help.spec.tsx
Labels: Pending Review, No QA Required, No UX QA Required

#6926 refactor: convert duelling-picklist tests to RTL
  src/components/duelling-picklist/duelling-picklist.component.tsx
  src/components/duelling-picklist/duelling-picklist.pw.tsx
  src/components/duelling-picklist/duelling-picklist.spec.tsx
  src/components/duelling-picklist/duelling-picklist.test.tsx
  src/components/duelling-picklist/picklist-group/picklist-group.component.tsx
  src/components/duelling-picklist/picklist-group/picklist-group.spec.tsx
  src/components/duelling-picklist/picklist-group/picklist-group.test.tsx
  src/components/duelling-picklist/picklist-item/picklist-item.component.tsx
  src/components/duelling-picklist/picklist-item/picklist-item.spec.tsx
  src/components/duelling-picklist/picklist-item/picklist-item.test.tsx
  src/components/duelling-picklist/picklist/picklist.component.tsx
Labels: Passed Review, No UX QA Required, Squad Front End

#6952 chore: upgrade transitive dependencies
  package-lock.json
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6940 refactor(search): convert tests to react testing library
  src/components/search/search.component.tsx
  src/components/search/search.spec.tsx
  src/components/search/search.test.tsx
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#6935 refactor(pages): convert unit tests to use react-testing-library
  src/components/pages/page/page.spec.tsx
  src/components/pages/page/page.test.tsx
  src/components/pages/pages.component.tsx
  src/components/pages/pages.spec.tsx
  src/components/pages/pages.test.tsx
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#6957 chore: upgrade playwright to v1.47
  .github/workflows/playwright-audit.yml
  .github/workflows/playwright.yml
  package-lock.json
  package.json
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#6919 feat(preview): add `shape` and `disableAnimation` props
  src/components/link-preview/link-preview.style.ts
  src/components/preview/__internal__/preview-placeholder.component.tsx
  src/components/preview/__internal__/preview-placeholder.style.ts
  src/components/preview/preview-test.stories.tsx
  src/components/preview/preview.component.tsx
  src/components/preview/preview.mdx
  src/components/preview/preview.pw.tsx
  src/components/preview/preview.stories.tsx
  src/components/preview/preview.style.ts
  src/components/preview/preview.test.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6946 refactor(popover): rewrite jest tests to use RTL
  src/__internal__/popover/popover.component.tsx
  src/__internal__/popover/popover.spec.tsx
  src/__internal__/popover/popover.test.tsx
  src/components/pages/pages.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6951 refactor(simple-color-picker): convert unit tests to react testing library
  src/components/simple-color-picker/simple-color-picker.spec.tsx
  src/components/simple-color-picker/simple-color-picker.test.tsx
  src/components/simple-color-picker/simple-color/simple-color.spec.tsx
  src/components/simple-color-picker/simple-color/simple-color.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6953 refactor(checkable-input): convert enzyme tests to RTL
  src/__internal__/checkable-input/__snapshots__/hidden-checkable-input.spec.tsx.snap
  src/__internal__/checkable-input/checkable-input.spec.tsx
  src/__internal__/checkable-input/checkable-input.test.tsx
  src/__internal__/checkable-input/hidden-checkable-input.spec.tsx
  src/__internal__/checkable-input/hidden-checkable-input.test.tsx
  src/components/checkbox/checkbox.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6959 refactor(radio-button-mapper): convert enzyme tests to RTL
  src/__internal__/radio-button-mapper/radio-button-mapper.component.tsx
  src/__internal__/radio-button-mapper/radio-button-mapper.spec.tsx
  src/__internal__/radio-button-mapper/radio-button-mapper.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6909 add flat-table enhancements
  src/components/flat-table/flat-table-row/flat-table-row.style.ts
  src/components/flat-table/flat-table-test.stories.tsx
  src/components/flat-table/flat-table-themes.mdx
  src/components/flat-table/flat-table-themes.stories.tsx
  src/components/flat-table/flat-table.component.tsx
  src/components/flat-table/flat-table.mdx
  src/components/flat-table/flat-table.pw.tsx
  src/components/flat-table/flat-table.spec.tsx
  src/components/flat-table/flat-table.stories.tsx
  src/components/flat-table/flat-table.style.ts
Labels: Passed Review, Passed QA, Passed UX QA

#6964 fix(checkbox, radio-button): restore support for `labelHelp` and `fieldHelp`
  src/__internal__/checkable-input/checkable-input.component.tsx
  src/components/checkbox/checkbox-group/checkbox-group.component.tsx
  src/components/checkbox/checkbox-group/checkbox-group.test.tsx
  src/components/checkbox/checkbox-test.stories.tsx
  src/components/checkbox/checkbox.component.tsx
  src/components/checkbox/checkbox.mdx
  src/components/checkbox/checkbox.stories.tsx
  src/components/checkbox/checkbox.style.ts
  src/components/checkbox/validations.stories.tsx
  src/components/numeral-date/numeral-date.mdx
  src/components/radio-button/radio-button-group/radio-button-group.component.tsx
  src/components/radio-button/radio-button-group/radio-button-group.test.tsx
  src/components/radio-button/radio-button-test.stories.tsx
  src/components/radio-button/radio-button.component.tsx
  src/components/radio-button/radio-button.mdx
  src/components/radio-button/radio-button.stories.tsx
  src/components/switch/switch.mdx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6933 fix(form): tabbing in FireFox - focus incorrect
  src/components/dialog/dialog.component.tsx
  src/components/form/form.component.tsx
Labels: Passed Review, Passed QA, Pending UX QA, Squad Front End

#6925 fix(tabs): tab headers jump in width when navigating through them
  src/components/tabs/tabs.spec.tsx
  src/components/tabs/tabs.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6945 fix(toast): ensure closed toasts do not trigger axe warnings
  src/components/toast/components.test-pw.tsx
  src/components/toast/toast-test.stories.tsx
  src/components/toast/toast.component.tsx
  src/components/toast/toast.pw.tsx
  src/components/toast/toast.test.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6938 docs(duelling-picklist): fix storybook docs page not displaying in production
  src/components/duelling-picklist/duelling-picklist.mdx
  src/components/duelling-picklist/duelling-picklist.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6962 refactor(form-field, fieldset): convert enzyme tests to RTL
  src/__internal__/fieldset/fieldset.spec.tsx
  src/__internal__/fieldset/fieldset.test.tsx
  src/__internal__/form-field/form-field.component.tsx
  src/__internal__/form-field/form-field.spec.tsx
  src/__internal__/form-field/form-field.test.tsx
  src/__internal__/label/label.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6960 fix(navigation-bar): move context provider to not wrap parent
  src/components/navigation-bar/components.test-pw.tsx
  src/components/navigation-bar/navigation-bar-test.stories.tsx
  src/components/navigation-bar/navigation-bar.component.tsx
  src/components/navigation-bar/navigation-bar.pw.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6958 refactor(input-presentation, input): convert enzyme tests to RTL
  src/__internal__/input/__snapshots__/input-presentation.spec.tsx.snap
  src/__internal__/input/__snapshots__/input.spec.tsx.snap
  src/__internal__/input/input-presentation.spec.tsx
  src/__internal__/input/input-presentation.test.tsx
  src/__internal__/input/input.spec.tsx
  src/__internal__/input/input.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required

#6967 refactor(accordion): convert test to react-testing-library
  src/components/accordion/accordion.component.tsx
  src/components/accordion/accordion.spec.tsx
  src/components/accordion/accordion.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6977 refactor(content): convert enzyme tests to RTL
  src/components/content/content.component.tsx
  src/components/content/content.spec.tsx
  src/components/content/content.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6972 refactor: convert utils & validations from enzyme to RTL
  src/__internal__/utils/helpers/browser-type-check/browser-type-check.spec.ts
  src/__internal__/utils/helpers/browser-type-check/browser-type-check.test.ts
  src/__internal__/utils/helpers/events/events.spec.ts
  src/__internal__/utils/helpers/events/events.test.ts
  src/__internal__/utils/helpers/guid/guid.spec.ts
  src/__internal__/utils/helpers/guid/guid.test.ts
  src/__internal__/utils/helpers/tags/tags.spec.ts
  src/__internal__/utils/helpers/tags/tags.test.ts
  src/__internal__/utils/logger/logger.spec.ts
  src/__internal__/utils/logger/logger.test.ts
  src/__internal__/validation-message/validation-message.component.tsx
  src/__internal__/validation-message/validation-message.spec.tsx
  src/__internal__/validation-message/validation-message.test.tsx
  src/__internal__/validations/validation-icon.spec.tsx
  src/__internal__/validations/validation-icon.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required

#6984 fix(loader): translations for france (FE-6822)
  src/locales/fr-fr.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Petrus

#6970 Refactor flat-table and flat-table-row to RTL FE-6592
  src/components/flat-table/__internal__/build-position-map.ts
  src/components/flat-table/components.test-pw.tsx
  src/components/flat-table/flat-table-row/flat-table-row.component.tsx
  src/components/flat-table/flat-table-row/flat-table-row.spec.tsx
  src/components/flat-table/flat-table-row/flat-table-row.style.ts
  src/components/flat-table/flat-table-row/flat-table-row.test.tsx
  src/components/flat-table/flat-table-test.stories.tsx
  src/components/flat-table/flat-table.component.tsx
  src/components/flat-table/flat-table.pw.tsx
  src/components/flat-table/flat-table.spec.tsx
  src/components/flat-table/flat-table.test.tsx
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#6976 fix(textarea): ensure that correct height is applied when rows and expandable prop are used together - FE-6810
  src/components/textarea/textarea-test.stories.tsx
  src/components/textarea/textarea.component.tsx
  src/components/textarea/textarea.test.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6981 feat(version-picker): reintroduce the version picker for storybook
  .storybook/manager.ts
  .storybook/version-picker/fetch-data.ts
  .storybook/version-picker/index.tsx
  .storybook/version-picker/mock-data/metadata.json
Labels: Passed Review, No QA Required, No UX QA Required

#6982 refactor(definition-list): convert tests to RTL - FE-6806
  src/components/definition-list/dd/dd.component.tsx
  src/components/definition-list/definition-list-test.stories.tsx
  src/components/definition-list/definition-list.spec.tsx
  src/components/definition-list/definition-list.test.tsx
  src/components/definition-list/dl.component.tsx
  src/components/definition-list/dt/dt.component.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6973 refactor(popover-container): rewrite tests to use RTL instead of Enzyme
  src/components/popover-container/popover-container.component.tsx
  src/components/popover-container/popover-container.spec.tsx
  src/components/popover-container/popover-container.style.ts
  src/components/popover-container/popover-container.test.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End
