Repository Sage/carbon, pull requests merged in 2024-07, with the labels that each got.

#6802 fix(progress-tracker): apply box sizing of border box to the inner styled bar - FE-6672
  src/components/progress-tracker/progress-tracker-test.stories.tsx
  src/components/progress-tracker/progress-tracker.spec.tsx
  src/components/progress-tracker/progress-tracker.style.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6806 feat(progress-tracker): deprecate aria- attribute props
  src/components/progress-tracker/progress-tracker.component.tsx
  src/components/progress-tracker/progress-tracker.spec.tsx
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#6804 refactor(settings-row): convert enzyme tests to rtl
  src/components/heading/heading.component.tsx
  src/components/settings-row/settings-row.component.tsx
  src/components/settings-row/settings-row.spec.tsx
  src/components/settings-row/settings-row.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required

#6800 chore(multi-action-button): convert enzyme tests to RTL
  src/components/multi-action-button/__snapshots__/multi-action-button.spec.tsx.snap
  src/components/multi-action-button/multi-action-button.spec.tsx
  src/components/multi-action-button/multi-action-button.test.tsx
  src/components/split-button/split-button.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6814 chore: prevent duplication of @testing-library/dom package
  package-lock.json
  package.json
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#6809 refactor(portrait): convert enzyme tests to rtl
  src/components/portrait/portrait.spec.tsx
  src/components/portrait/portrait.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required

#6792 fix(character-count): prevent screen reader announcing value when submitting a form
  playwright/components/index.ts
  playwright/components/locators.ts
  playwright/components/textarea/index.ts
  playwright/components/textarea/locators.ts
  src/__internal__/character-count/character-count.component.tsx
  src/__internal__/character-count/character-count.spec.tsx
  src/components/form/form-test.stories.tsx
  src/components/password/components.test-pw.tsx
  src/components/text-editor/components.test-pw.tsx
  src/components/text-editor/text-editor.component.tsx
  src/components/text-editor/text-editor.pw.tsx
  src/components/textarea/components.test-pw.tsx
  src/components/textarea/textarea.component.tsx
  src/components/textarea/textarea.pw.tsx
  src/components/textbox/components.test-pw.tsx
  src/components/textbox/textbox.component.tsx
  src/components/textbox/textbox.pw.tsx
  src/hooks/__internal__/useCharacterCount/useCharacterCount.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6815 refactor(note): convert enzyme tests to RTL
  src/components/note/__internal__/status-icon/status.spec.tsx
  src/components/note/note.spec.tsx
  src/components/note/note.test.tsx
  src/components/vertical-divider/vertical-divider.component.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6805 refactor(anchor-navigation): convert enzyme tests to rtl
  src/components/anchor-navigation/anchor-navigation.component.tsx
  src/components/anchor-navigation/anchor-navigation.spec.tsx
  src/components/anchor-navigation/anchor-navigation.test.tsx
Labels: Pending Review, No QA Required, No UX QA Required

#6813 refactor(textbox): convert enzyme tests to react-testing-library
  src/components/textbox/textbox.spec.tsx
  src/components/textbox/textbox.test.tsx
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#6810 refactor(draggable): convert enzyme tests to RTL and Playwright (FE-6588)
  src/components/draggable/__internal__/drop-target.component.tsx
  src/components/draggable/components.test-pw.tsx
  src/components/draggable/draggable-container.component.tsx
  src/components/draggable/draggable-item/draggable-item.component.tsx
  src/components/draggable/draggable.pw.tsx
  src/components/draggable/draggable.spec.tsx
  src/components/draggable/draggable.test.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6819 refactor(profile): convert enzyme tests to rtl
  src/components/profile/profile.component.tsx
  src/components/profile/profile.spec.tsx
  src/components/profile/profile.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required

#6812 refactor(date-range): convert unit tests to RTL
  src/components/date-range/date-range.component.tsx
  src/components/date-range/date-range.spec.tsx
  src/components/date-range/date-range.test.tsx
  src/components/date/date.style.ts
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6818 refactor(button-minor): convert enzyme tests to RTL
  src/components/button-minor/button-minor.spec.tsx
  src/components/button-minor/button-minor.test.tsx
  src/components/button/button.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6817 chore: remove unnecessary act calls in RTL tests
  src/components/button-toggle/button-toggle-group/button-toggle-group.test.tsx
  src/components/date-range/date-range.test.tsx
  src/components/date/date.test.tsx
  src/components/dialog/dialog.test.tsx
  src/components/menu/menu-item/menu-item.test.tsx
  src/components/menu/menu.test.tsx
  src/components/split-button/split-button.test.tsx
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#6816 refactor(sidebar): convert enzyme tests to RTL
  src/components/dialog/dialog.test.tsx
  src/components/icon-button/icon-button.component.tsx
  src/components/icon-button/icon-button.spec.tsx
  src/components/menu/menu.component.tsx
  src/components/sidebar/__internal__/sidebar-header/sidebar-header.spec.tsx
  src/components/sidebar/sidebar.component.tsx
  src/components/sidebar/sidebar.spec.tsx
  src/components/sidebar/sidebar.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6822 refactor(textarea): convert enzyme tests to rtl
  src/__internal__/input/__snapshots__/input-presentation.spec.tsx.snap
  src/__internal__/input/input-presentation.component.tsx
  src/components/textarea/textarea.spec.tsx
  src/components/textarea/textarea.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6831 fix(link): ensure focus styles are removed when underlying element loses focus
  src/components/breadcrumbs/breadcrumbs-test.stories.tsx
  src/components/breadcrumbs/breadcrumbs.pw.tsx
  src/components/breadcrumbs/components.test-pw.tsx
  src/components/link/link.component.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6830 refactor(icon-button): convert enzyme tests to RTL
  src/components/icon-button/icon-button.spec.tsx
  src/components/icon-button/icon-button.test.tsx
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#6836 fix(file-input): ensure that long file names are truncated correctly - FE-6685
  src/components/file-input/__internal__/file-upload-status/file-upload-status.style.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6797 fix(dialog-full-screen): fix flex title layout
  src/__internal__/full-screen-heading/full-screen-heading.style.ts
  src/components/dialog-full-screen/dialog-full-screen-test.stories.tsx
  src/components/dialog-full-screen/dialog-full-screen.spec.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6827 fix(menu-item): ensure hover styling does not overlap focus outlines
  src/components/menu/component.test-pw.tsx
  src/components/menu/menu-item/menu-item.style.ts
  src/components/menu/menu.pw.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6807 fix(alert): fix data-component for alert component
  playwright/components/alert/index.ts
  playwright/components/alert/locators.ts
  src/components/alert/alert.test.tsx
  src/components/dialog/dialog.component.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6824 refactor(select): convert tests for internal utils to RTL
  src/components/select/__internal__/utils/get-next-child-by-text.spec.tsx
  src/components/select/__internal__/utils/get-next-child-by-text.test.tsx
  src/components/select/__internal__/utils/get-next-index-by-key.spec.ts
  src/components/select/__internal__/utils/get-next-index-by-key.test.ts
  src/components/select/__internal__/utils/highlight-part-of-text.spec.tsx
  src/components/select/__internal__/utils/highlight-part-of-text.test.tsx
  src/components/select/__internal__/utils/highlight-part-of-text.tsx
  src/components/select/__internal__/utils/is-expected-option.spec.tsx
  src/components/select/__internal__/utils/is-expected-option.test.tsx
  src/components/select/__internal__/utils/is-expected-value.spec.ts
  src/components/select/__internal__/utils/is-expected-value.test.ts
  src/components/select/__internal__/utils/is-navigation-key.spec.ts
  src/components/select/__internal__/utils/is-navigation-key.test.ts
  src/components/select/__internal__/utils/with-filter.spec.tsx
  src/components/select/__internal__/utils/with-filter.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6839 refactor(number): convert enzyme tests to RTL
  src/components/number/number.spec.tsx
  src/components/number/number.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6837 fix(numeral-date): ensure that enter key triggers default behaviour FE-6699
  src/components/numeral-date/numeral-date-test.stories.tsx
  src/components/numeral-date/numeral-date.component.tsx
  src/components/numeral-date/numeral-date.spec.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6838 refactor(heading): refactor enzyme tests to RTL
  src/components/heading/heading.component.tsx
  src/components/heading/heading.spec.tsx
  src/components/heading/heading.test.tsx
Labels: Pending Review, No QA Required, No UX QA Required

#6855 chore(jest): address test flakiness related to tooltips
  src/components/date-range/date-range.test.tsx
  src/components/date/date.test.tsx
  src/components/textarea/textarea.test.tsx
  src/components/textbox/textbox.test.tsx
  src/components/tooltip/tooltip.test.tsx
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#6848 refactor(radio-button, radio-button-group): convert enzyme tests to RTL
  src/__internal__/fieldset/fieldset.component.tsx
  src/components/radio-button/radio-button-group/radio-button-group.component.tsx
  src/components/radio-button/radio-button-group/radio-button-group.spec.tsx
  src/components/radio-button/radio-button-group/radio-button-group.test.tsx
  src/components/radio-button/radio-button-svg.component.tsx
  src/components/radio-button/radio-button.spec.tsx
  src/components/radio-button/radio-button.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6856 test(batch-selection): remove enzyme tests
  src/components/batch-selection/batch-selection.spec.tsx
Labels: Pending Review, No QA Required, No UX QA Required, Squad Front End

#6833 fix(button-toggle): long text overflows button and update large icon padding
  src/components/button-toggle/button-toggle-group/button-toggle-group-test.stories.tsx
  src/components/button-toggle/button-toggle-test.stories.tsx
  src/components/button-toggle/button-toggle.mdx
  src/components/button-toggle/button-toggle.pw.tsx
  src/components/button-toggle/button-toggle.stories.tsx
  src/components/button-toggle/button-toggle.style.ts
  src/components/button-toggle/button-toggle.test.tsx
  src/components/time/time.pw.tsx
  src/components/time/time.test.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6851 fix(popover-container): popover position re-renders with controlled MultiSelect
  src/components/popover-container/popover-container-test.stories.tsx
  src/components/popover-container/popover-container.component.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6828 feat(option-group-header): add support for children to be passed to component
  src/components/select/option-group-header/option-group-header.component.tsx
  src/components/select/option-group-header/option-group-header.spec.tsx
  src/components/select/simple-select/simple-select.mdx
  src/components/select/simple-select/simple-select.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#6766 fix(flat-table): sticky column with button - focus border partially covered in expanded rows
  src/components/flat-table/__internal__/use-table-cell.ts
  src/components/flat-table/flat-table-cell/flat-table-cell.component.tsx
  src/components/flat-table/flat-table-row-header/flat-table-row-header.component.tsx
  src/components/flat-table/flat-table-row-header/flat-table-row-header.spec.tsx
  src/components/flat-table/flat-table-row/flat-table-row.style.ts
  src/components/flat-table/flat-table-test.stories.tsx
  src/components/flat-table/flat-table.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6864 chore: update transitive dependencies
  package-lock.json
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6844 refactor(action-popover): convert enzyme tests to rtl
  playwright/components/action-popover/index.ts
  src/components/action-popover/action-popover-item/action-popover-item.component.tsx
  src/components/action-popover/action-popover.component.tsx
  src/components/action-popover/action-popover.pw.tsx
  src/components/action-popover/action-popover.spec.tsx
  src/components/action-popover/action-popover.style.ts
  src/components/action-popover/action-popover.test.tsx
Labels: Pending Review, No UX QA Required, Squad Front End

#6834 chore(modal): convert tests to RTL - FE-6610
  src/components/modal/__internal__/modal-manager.spec.ts
  src/components/modal/__internal__/modal-manager.test.tsx
  src/components/modal/modal.component.tsx
  src/components/modal/modal.spec.tsx
  src/components/modal/modal.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#6795 feat(step-flow): allow component title to be compositional
  src/components/step-flow/__internal__/step-flow.context.ts
  src/components/step-flow/components.test-pw.tsx
  src/components/step-flow/index.ts
  src/components/step-flow/step-flow-title/step-flow-title.component.tsx
  src/components/step-flow/step-flow-title/step-flow-title.test.tsx
  src/components/step-flow/step-flow.component.tsx
  src/components/step-flow/step-flow.mdx
  src/components/step-flow/step-flow.pw.tsx
  src/components/step-flow/step-flow.stories.tsx
  src/components/step-flow/step-flow.test.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6845 fix(flat-table): flat table contents visible behind sticky header/footer
  src/components/flat-table/flat-table-test.stories.tsx
  src/components/flat-table/flat-table.component.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6796 feat(toast): improve component screen reader behaviour
  playwright/components/toast/index.ts
  playwright/components/toast/locators.ts
  src/components/alert/alert.mdx
  src/components/dialog/dialog.pw.tsx
  src/components/select/__internal__/select-textbox/select-textbox.component.tsx
  src/components/toast/components.test-pw.tsx
  src/components/toast/toast.component.tsx
  src/components/toast/toast.mdx
  src/components/toast/toast.pw.tsx
  src/locales/de-de.ts
  src/locales/en-gb.ts
  src/locales/es-es.ts
  src/locales/fr-ca.ts
  src/locales/fr-fr.ts
  src/locales/locale.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#6857 chore(grid): remove enzyme tests - FE-6595
  src/components/grid/__snapshots__/grid.spec.tsx.snap
  src/components/grid/grid-test.stories.tsx
  src/components/grid/grid.spec.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End
