Repository Sage/carbon, pull requests merged in 2025-03, with the labels that each got.

#7232 feat(packages): remove `typescript-to-proptypes` package
  .eslintrc
  babel.config.js
  docs/usage.mdx
  package-lock.json
  package.json
  plugins/generate-proptypes/index.mjs
  plugins/generate-proptypes/inject-prop-types.mjs
  plugins/generate-proptypes/ts-utils.mjs
  src/components/action-popover/action-popover-test.stories.tsx
  src/components/action-popover/components.test-pw.tsx
  src/components/alert/alert-test.stories.tsx
  src/components/button/button.component.tsx
  src/components/content/components.test-pw.tsx
  src/components/textarea/textarea-test.stories.tsx
  src/components/tooltip/tooltip-test.stories.tsx
Labels: Passed Review, Passed QA, Squad Front End, dependencies, typescript

#7236 fix(text-editor): ensure that margin props are applied to component - FE-7104
  src/components/text-editor/text-editor-test.stories.tsx
  src/components/text-editor/text-editor.component.tsx
  src/components/text-editor/text-editor.pw.tsx
  src/components/text-editor/text-editor.style.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7239 fix(date-input): update documentation
  src/components/date-range/date-range.mdx
  src/components/date-range/date-range.stories.tsx
  src/components/date/date.component.tsx
  src/components/date/date.mdx
  src/components/date/date.stories.tsx
Labels: Passed Review, Passed QA, Squad Front End

#7226 feat: support server-side rendering
  .eslintrc
  jest.config.ts
  package-lock.json
  package.json
  src/__internal__/dom/globals.server.test.ts
  src/__internal__/dom/globals.test.ts
  src/__internal__/dom/globals.ts
  src/__spec_helper__/mock-element-scrollto.ts
  src/__spec_helper__/mock-match-media.ts
  src/__spec_helper__/mock-resize-observer.ts
  src/components/flat-table/flat-table-row/flat-table-row.style.ts
  src/components/icon/icon.style.ts
  src/components/menu/menu-full-screen/menu-full-screen.component.tsx
  src/components/modal/__internal__/modal-manager.server.test.tsx
  src/components/modal/__internal__/modal-manager.ts
  src/components/modal/modal.component.tsx
  src/components/vertical-menu/vertical-menu-full-screen/vertical-menu-full-screen.component.tsx
  src/hooks/__internal__/useScrollBlock/scroll-block-manager.server.test.ts
  src/hooks/__internal__/useScrollBlock/scroll-block-manager.ts
Labels: Passed Review, Passed QA, No UX QA Required, third-party

#7246 chore: move nyc and monocart-coverage-reports to be dev dependencies - FE-7120
  package-lock.json
  package.json
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#7204 feat(adaptive-sidebar): Implements adaptive sidebar
  package-lock.json
  src/components/adaptive-sidebar/__internal__/utils.ts
  src/components/adaptive-sidebar/adaptive-sidebar-test.stories.tsx
  src/components/adaptive-sidebar/adaptive-sidebar.component.tsx
  src/components/adaptive-sidebar/adaptive-sidebar.mdx
  src/components/adaptive-sidebar/adaptive-sidebar.pw.tsx
  src/components/adaptive-sidebar/adaptive-sidebar.stories.tsx
  src/components/adaptive-sidebar/adaptive-sidebar.style.ts
  src/components/adaptive-sidebar/adaptive-sidebar.test.tsx
  src/components/adaptive-sidebar/components.test-pw.tsx
  src/components/adaptive-sidebar/index.ts
  src/components/box/box.component.tsx
  src/components/sidebar/sidebar.component.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End, Passed a11y Review

#7247 fix(form): correct pluralisation on form summary when single error and warning
  src/components/form/form-test.stories.tsx
  src/locales/en-gb.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7233 fix(checkbox-group, radio-button-group): ensure right-aligned legend does not extend past the input
  src/components/checkbox/checkbox-group/checkbox-group.component.tsx
  src/components/checkbox/checkbox-test.stories.tsx
  src/components/radio-button/radio-button-group/radio-button-group.component.tsx
  src/components/radio-button/radio-button-test.stories.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#7255 fix(text-editor): fixes the formatting buttons when clicked to toggle without text selections
  src/components/text-editor/__internal__/plugins/ContentEditor/content-editor.component.tsx
  src/components/text-editor/__internal__/plugins/Toolbar/buttons/bold.component.tsx
  src/components/text-editor/__internal__/plugins/Toolbar/buttons/italic.component.tsx
  src/components/text-editor/__internal__/plugins/Toolbar/buttons/list.component.tsx
  src/components/text-editor/text-editor.pw.tsx
  src/components/text-editor/text-editor.test.tsx
Labels: Pending Review, Passed QA, Squad Front End, text-editor

#7258 chore: upgrade @babel/runtime
  .github/workflows/playwright-audit.yml
  package-lock.json
Labels: Passed Review, No QA Required, No UX QA Required

#7241 [Button] additional secondary style
  src/components/button/button-types.style.ts
  src/components/button/button.component.tsx
  src/components/button/button.mdx
  src/components/button/button.pw.tsx
  src/components/button/button.stories.tsx
  src/components/button/button.style.ts
  src/components/button/button.test.tsx
  src/components/button/components.test-pw.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Passed a11y Review, button

#7256 feat(tile): add important highlight variant
  src/components/tile/tile.component.tsx
  src/components/tile/tile.config.ts
  src/components/tile/tile.mdx
  src/components/tile/tile.stories.tsx
  src/components/tile/tile.style.ts
  src/components/tile/tile.test.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#7265 test(decimal): fix failing test due to Node 20.19.0 change
  src/components/decimal/decimal.test.tsx
Labels: Pending Review, No QA Required, No UX QA Required

#7243 fix(form): replace use of context to apply field spacing
  src/__internal__/fieldset/fieldset.component.tsx
  src/__internal__/fieldset/fieldset.style.ts
  src/__internal__/form-field/form-field.component.tsx
  src/__internal__/form-field/form-field.style.ts
  src/__internal__/form-spacing-provider/form-spacing-provider.component.tsx
  src/__internal__/form-spacing-provider/form-spacing.context.ts
  src/__internal__/form-spacing-provider/index.ts
  src/components/checkbox/checkbox-group/checkbox-group.component.tsx
  src/components/checkbox/checkbox.component.tsx
  src/components/checkbox/checkbox.style.ts
  src/components/date-range/date-range.style.ts
  src/components/date/date.component.tsx
  src/components/date/date.style.ts
  src/components/fieldset/fieldset.component.tsx
  src/components/fieldset/fieldset.style.ts
  src/components/form/form-test.stories.tsx
  src/components/form/form.component.tsx
  src/components/form/form.mdx
  src/components/form/form.stories.tsx
  src/components/form/form.style.ts
  src/components/inline-inputs/inline-inputs.component.tsx
  src/components/inline-inputs/inline-inputs.style.ts
  src/components/numeral-date/numeral-date.component.tsx
  src/components/search/search.component.tsx
  src/components/search/search.style.ts
  src/components/select/filterable-select/filterable-select.component.tsx
  src/components/select/multi-select/multi-select.component.tsx
  src/components/select/select.style.ts
  src/components/select/simple-select/simple-select.component.tsx
  src/components/switch/switch.component.tsx
  src/components/switch/switch.style.ts
  src/components/text-editor/text-editor.style.ts
  src/components/textarea/textarea.component.tsx
  src/components/textarea/textarea.style.ts
  src/components/textbox/textbox.component.tsx
  src/components/time/time.component.tsx
  src/hooks/__internal__/useFormSpacing/add-form-spacing/add-form-spacing.test.ts
  src/hooks/__internal__/useFormSpacing/add-form-spacing/index.ts
  src/hooks/__internal__/useFormSpacing/index.ts
  src/hooks/__internal__/useFormSpacing/useFormSpacing.test.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7250 fix(secondary-button): split button additional secondary style
  src/components/button/button-types.style.ts
  src/components/button/button.component.tsx
  src/components/split-button/split-button-toggle.style.ts
  src/components/split-button/split-button.component.tsx
  src/components/split-button/split-button.stories.tsx
  src/components/split-button/split-button.test.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#7262 chore: upgrade storybook to 8.6.7
  package-lock.json
  package.json
Labels: Passed Review, Passed QA, No UX QA Required

#7260 fix(time): onChange event not giving the correct values for hours/minutes
  src/components/time/index.ts
  src/components/time/time-test.stories.tsx
  src/components/time/time.component.tsx
  src/components/time/time.test.tsx
Labels: Passed Review, Passed QA, Squad Front End

#7269 feat(message): add ai variant
  src/__internal__/ai-icon/ai-icon.component.tsx
  src/__internal__/ai-icon/ai-icon.test.tsx
  src/__internal__/ai-icon/index.ts
  src/components/message/__internal__/message-content/message-content.component.tsx
  src/components/message/__internal__/message-content/message-content.style.ts
  src/components/message/__internal__/type-icon/type-icon.component.tsx
  src/components/message/__internal__/type-icon/type-icon.style.ts
  src/components/message/__internal__/type-icon/type-icon.test.tsx
  src/components/message/message-test.stories.tsx
  src/components/message/message.component.tsx
  src/components/message/message.mdx
  src/components/message/message.pw.tsx
  src/components/message/message.stories.tsx
  src/components/message/message.style.ts
  src/components/message/message.test.tsx
  src/components/toast/toast.component.tsx
  src/components/toast/toast.style.ts
  src/locales/en-gb.ts
  src/locales/locale.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#7271 fix(hr): make width 100% - FE-6662
  src/components/adaptive-sidebar/adaptive-sidebar.stories.tsx
  src/components/form/form.stories.tsx
  src/components/hr/hr-test.stories.tsx
  src/components/hr/hr.mdx
  src/components/hr/hr.stories.tsx
  src/components/hr/hr.style.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7270 feat(dialog): add highlight variant prop to dialog
  src/components/dialog/dialog-test.stories.tsx
  src/components/dialog/dialog.component.tsx
  src/components/dialog/dialog.mdx
  src/components/dialog/dialog.stories.tsx
  src/components/dialog/dialog.style.ts
  src/components/dialog/dialog.test.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End, dialog

#7266 feat(vertical-menu-full-screen): add slide in animation on menu open/close
  src/components/vertical-menu/vertical-menu-full-screen/vertical-menu-full-screen.component.tsx
  src/components/vertical-menu/vertical-menu-full-screen/vertical-menu-full-screen.test.tsx
  src/components/vertical-menu/vertical-menu-test.stories.tsx
  src/components/vertical-menu/vertical-menu.pw.tsx
  src/components/vertical-menu/vertical-menu.stories.tsx
  src/components/vertical-menu/vertical-menu.style.ts
  src/components/vertical-menu/vertical-menu.test.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7273 fix(menu-item): ensure that items with a focusable child are styled with no additional padding
  src/components/link/link.component.tsx
  src/components/link/link.test.tsx
  src/components/menu/menu-item/menu-item.component.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7259 feat(use-character-count): make hook public
  src/__internal__/input/input.component.tsx
  src/__internal__/input/input.test.tsx
  src/components/select/__internal__/select-textbox/select-textbox.component.tsx
  src/components/select/simple-select/simple-select.component.tsx
  src/components/textarea/textarea.component.tsx
  src/components/textarea/textarea.test.tsx
  src/components/textbox/textbox.component.tsx
  src/components/textbox/textbox.test.tsx
  src/hooks/useCharacterCount/index.ts
  src/hooks/useCharacterCount/use-character-count.mdx
  src/hooks/useCharacterCount/use-character-count.stories.tsx
  src/hooks/useCharacterCount/useCharacterCount.test.tsx
  src/hooks/useCharacterCount/useCharacterCount.tsx
  src/hooks/useMediaQuery/use-media-query.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7281 docs(message): document recommended call-to-acton programmatic focus pattern
  src/components/message/message.mdx
  src/components/message/message.stories.tsx
Labels: Pending Review, No QA Required, No UX QA Required

#7278 build: upgrade node to v22
  .github/workflows/chromatic-push.yml
  .github/workflows/chromatic.yml
  .github/workflows/ci.yml
  .github/workflows/playwright.yml
  .github/workflows/semantic-commit-lint.yml
  .github/workflows/semantic-release.yml
  .github/workflows/storybook.yml
  .nvmrc
  src/__internal__/dom/globals.ts
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End
