Repository Sage/carbon, pull requests merged in 2025-02, with the labels that each got.

#7160 feat(numeral-date, time): add support for labelAlign on non-inline labels
  src/__internal__/fieldset/fieldset.component.tsx
  src/__internal__/fieldset/fieldset.style.ts
  src/__internal__/fieldset/fieldset.test.tsx
  src/components/checkbox/checkbox-group/checkbox-group.component.tsx
  src/components/form/form.stories.tsx
  src/components/numeral-date/numeral-date-test.stories.tsx
  src/components/numeral-date/numeral-date.component.tsx
  src/components/numeral-date/numeral-date.pw.tsx
  src/components/numeral-date/numeral-date.style.ts
  src/components/numeral-date/numeral-date.test.tsx
  src/components/radio-button/radio-button-group/radio-button-group.component.tsx
  src/components/textbox/textbox-test.stories.tsx
  src/components/time/time-test.stories.tsx
  src/components/time/time.component.tsx
  src/components/time/time.stories.tsx
  src/components/time/time.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#7177 feat(portrait, profile): allow custom background/foregound colours for the Portrait and Profile components
  src/components/portrait/__internal__/utils.test.ts
  src/components/portrait/__internal__/utils.ts
  src/components/portrait/portrait-test.stories.tsx
  src/components/portrait/portrait.component.tsx
  src/components/portrait/portrait.mdx
  src/components/portrait/portrait.pw.tsx
  src/components/portrait/portrait.stories.tsx
  src/components/portrait/portrait.style.tsx
  src/components/portrait/portrait.test.tsx
  src/components/profile/profile.component.tsx
  src/components/profile/profile.mdx
  src/components/profile/profile.stories.tsx
  src/components/profile/profile.test.tsx
  src/components/switch/switch.component.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End, portrait, profile

#7159 feat(hr): add height prop
  src/components/hr/hr.component.tsx
  src/components/hr/hr.mdx
  src/components/hr/hr.pw.tsx
  src/components/hr/hr.stories.tsx
  src/components/hr/hr.style.ts
  src/components/hr/hr.test.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End, Squad Vortex, third-party

#7168 fix(action-popover): aria label has default value despite visible text on open button
  src/components/action-popover/__internal__/action-popover-utils.tsx
  src/components/action-popover/action-popover-menu-button/action-popover-menu-button.component.tsx
  src/components/action-popover/action-popover-test.stories.tsx
  src/components/action-popover/action-popover.component.tsx
  src/components/action-popover/action-popover.test.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#7186 feat(search, menu-item): Search accessibility updates
  src/__internal__/input-icon-toggle/input-icon-toggle.component.tsx
  src/components/menu/menu-item/menu-item.component.tsx
  src/components/menu/menu-item/menu-item.test.tsx
  src/components/menu/menu-test.stories.tsx
  src/components/menu/menu.pw.tsx
  src/components/search/search.component.tsx
  src/components/search/search.pw.tsx
  src/components/search/search.test.tsx
  src/components/textbox/textbox.pw.tsx
Labels: Passed Review, Passed QA, Accessibility, Passed UX QA, Squad Front End, Passed a11y Review, menu, search

#7197 docs(dialog, form): make respective textareas controlled
  src/components/dialog/dialog.mdx
  src/components/dialog/dialog.stories.tsx
  src/components/form/form.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7194 fix(menu): ensure that the correct focus and hover styling is applied to popover-container button - FE-7061
  src/components/menu/menu-item/menu-item.style.ts
  src/components/menu/menu.pw.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7165 fix(heading): maintain layout when title prop is set to null
  src/components/dialog-full-screen/content.style.ts
  src/components/dialog-full-screen/dialog-full-screen.component.tsx
  src/components/dialog-full-screen/dialog-full-screen.style.ts
  src/components/dialog-full-screen/dialog-full-screen.test.tsx
  src/components/pages/page/page.component.tsx
  src/components/pages/pages-test.stories.tsx
  src/components/pages/pages.test.tsx
Labels: Passed Review, Passed QA, Squad Front End

#7190 feat(fieldset): add support for new validation designs
  src/components/fieldset/fieldset-examples.mdx
  src/components/fieldset/fieldset-examples.stories.tsx
  src/components/fieldset/fieldset-test.stories.tsx
  src/components/fieldset/fieldset.component.tsx
  src/components/fieldset/fieldset.mdx
  src/components/fieldset/fieldset.stories.tsx
  src/components/fieldset/fieldset.style.ts
  src/components/fieldset/fieldset.test.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#7201 docs(badge): address spelling issues
  src/components/badge/badge.component.tsx
  src/components/badge/badge.mdx
  src/components/badge/badge.stories.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#7198 fix(switch): margins and alignment
  src/components/switch/switch-test.stories.tsx
  src/components/switch/switch.component.tsx
  src/components/switch/switch.test.tsx
Labels: Passed Review, Passed QA, Pending UX QA, Squad Front End

#7196 feat(message): add `width` prop
  src/components/message/message-test.stories.tsx
  src/components/message/message.component.tsx
  src/components/message/message.style.ts
  src/components/message/message.test.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7205 fix(accordion): ensure custom title is not wrapped in a heading tag when provided
  src/components/accordion/accordion.component.tsx
  src/components/accordion/accordion.mdx
  src/components/accordion/accordion.pw.tsx
  src/components/accordion/accordion.stories.tsx
  src/components/accordion/accordion.test.tsx
Labels: Passed Review, Passed QA, Squad Vortex, accordion

#7200 docs(textarea): unable to apply both rows and minHeight prop values simultaneously
  src/components/textarea/textarea.component.tsx
Labels: Passed Review, Passed QA, Squad Front End

#7213 chore(deps): update several transitive Octokit-related dependencies
  CHANGELOG.md
  __mocks__/ci-info.js
  package-lock.json
  package.json
  scripts/check_rfcs/check_rfcs.js
  scripts/check_rfcs/check_rfcs.test.js
  scripts/check_rfcs/index.js
Labels: Passed Review, No QA Required, No UX QA Required

#7195 feat(radio-button-group, checkbox-group): add `id` prop
  src/__internal__/fieldset/fieldset.component.tsx
  src/__internal__/fieldset/fieldset.test.tsx
  src/components/checkbox/checkbox-group/checkbox-group.component.tsx
  src/components/checkbox/checkbox-group/checkbox-group.test.tsx
  src/components/checkbox/checkbox-test.stories.tsx
  src/components/numeral-date/numeral-date.component.tsx
  src/components/numeral-date/numeral-date.test.tsx
  src/components/radio-button/radio-button-group/radio-button-group.component.tsx
  src/components/radio-button/radio-button-group/radio-button-group.test.tsx
  src/components/radio-button/radio-button-test.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7217 docs(portrait): resolve missing prop table in storybook docs
  src/components/portrait/portrait.component.tsx
Labels: Passed Review, No QA Required, No UX QA Required

#7219 feat(content): reduce margin of content body to 24px when inline
  src/components/content/content.style.ts
Labels: Passed Review, Passed QA, Squad Nebula, content

#7210 chore: rm warning story from new boolean validation
  src/components/checkbox/checkbox.mdx
  src/components/checkbox/validations.stories.tsx
Labels: Passed Review, Passed QA, Squad Front End

#7212 fix(tabs): reposition tab title on focus to prevent content moving on focus
  src/components/tabs/__internal__/tab-title/tab-title.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#7224 docs: update old React v17 import in usage guide
  CHANGELOG.md
  docs/usage.mdx
Labels: Passed Review, No QA Required, No UX QA Required

#7221 docs(sidebar): fix custom width example to prevent incorrect button formatting
  src/components/sidebar/sidebar.stories.tsx
Labels: Passed Review, Passed QA, Docs, sidebar

#7230 fix(packages): re-remove reintroduced octokit dependency
  package-lock.json
  package.json
Labels: Passed Review, No QA Required, No UX QA Required

#7220 fix(accordion): add padding-right to accordion heading container
  src/components/accordion/accordion-test.stories.tsx
  src/components/accordion/accordion.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#7156 FE-6858 - update date-fns from ^2.30.0 to ^4.1.0
  package-lock.json
  package.json
  rfcs/text/refactoring-date-component.md
  src/components/date-range/date-range.test.tsx
  src/components/date/__internal__/date-fns-fp/index.ts
  src/components/date/__internal__/date-formats/index.ts
  src/components/date/__internal__/date-picker/date-picker.component.tsx
  src/components/date/__internal__/date-picker/date-picker.test.tsx
  src/components/date/__internal__/utils.ts
  src/components/date/date-test.stories.tsx
  src/components/date/date.test.tsx
  src/locales/de-de.ts
  src/locales/en-ca.ts
  src/locales/en-gb.ts
  src/locales/en-us.ts
  src/locales/es-es.ts
  src/locales/fr-ca.ts
  src/locales/fr-fr.ts
Labels: Passed Review, DO NOT MERGE, Passed QA, No UX QA Required, third-party

#7225 docs: add guidance on importing compound components
  .assets/context-bound-components-incorrect-usage.svg
  docs/component-dos-and-donts.mdx
  docs/extending-styles-using-styled-components.mdx
  docs/recommended-practices.mdx
Labels: Passed Review, Passed QA, No QA Required
