Repository Sage/carbon, pull requests merged in 2025-10, with the labels that each got.

#7564 chore: add isLarge prop to internal components
  src/__internal__/character-count/character-count.component.tsx
  src/__internal__/character-count/character-count.style.ts
  src/__internal__/character-count/character-count.test.tsx
  src/__internal__/fieldset/fieldset.component.tsx
  src/__internal__/fieldset/fieldset.style.ts
  src/__internal__/fieldset/fieldset.test.tsx
  src/__internal__/hint-text/hint-text.component.tsx
  src/__internal__/hint-text/hint-text.style.tsx
  src/__internal__/hint-text/hint-text.test.tsx
  src/__internal__/label/label.component.tsx
  src/__internal__/label/label.style.ts
  src/__internal__/label/label.test.tsx
  src/__internal__/validation-message/validation-message.component.tsx
  src/__internal__/validation-message/validation-message.style.ts
  src/__internal__/validation-message/validation-message.test.tsx
Labels: Passed Review, No QA Required, Squad Front End

#7563 feat: add relative position to form field wrapper
  src/__internal__/form-field/form-field.style.ts
  src/components/textbox/textbox-test.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required

#7565 fix(multi-action-button): prevent popup closing too early
  src/components/multi-action-button/multi-action-button-test.stories.tsx
  src/components/multi-action-button/multi-action-button.test.tsx
  src/components/split-button/split-button.test.tsx
  src/hooks/__internal__/useChildButtons/useChildButtons.tsx
  src/hooks/__internal__/useMenuKeyboardNavigation/useMenuKeyboardNavigation.test.tsx
  src/hooks/__internal__/useMenuKeyboardNavigation/useMenuKeyboardNavigation.ts
Labels: Passed Review, Passed QA, No UX QA Required

#7569 test(test-utils): adds a helper to replace Logger deprecation checks
  src/__spec_helper__/__internal__/test-utils.ts
  src/components/badge/badge.test.tsx
  src/components/textarea/textarea.test.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End
