Repository Sage/carbon, pull requests merged in 2025-06, with the labels that each got.

#7358 build: install @swc/core and platform binaries
  package-lock.json
  package.json
Labels: Passed Review, No QA Required, No UX QA Required

#7319 build(storybook): configure storybook to use vite instead of webpack
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/vite-env.d.ts
  .storybook/vite.config.js
  .storybook/welcome-page/components-demo/component-heading/component-heading.component.jsx
  .storybook/welcome-page/components-demo/demo/demo-table/demo-table.component.jsx
  .storybook/welcome-page/components-demo/demo/demo.component.jsx
  .storybook/welcome-page/footer/footer.component.jsx
  .storybook/welcome-page/get-started/get-started.component.jsx
  .storybook/welcome-page/header/header.component.jsx
  .storybook/welcome-page/loves-carbon/loves-carbon.component.jsx
  .storybook/welcome-page/selling-points/selling-point-panel.component.jsx
  .storybook/welcome-page/selling-points/selling-points-item.component.js
  .storybook/welcome-page/selling-points/selling-points-item.component.jsx
  .storybook/welcome-page/selling-points/selling-points.component.jsx
  .storybook/welcome-page/welcome.component.js
  .storybook/welcome-page/welcome.component.jsx
  .storybook/welcome-page/welcome.stories.jsx
  .storybook/withThemeProvider.jsx
  package-lock.json
  package.json
  src/components/advanced-color-picker/advanced-color-picker.style.ts
  src/components/image/image.stories.tsx
  src/components/simple-color-picker/simple-color/simple-color.style.ts
  src/components/tile-select/components.test-pw.tsx
  src/components/tile-select/tile-select.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required

#7347 refactor(action-popover): simplify styling logic to reduce amount of internal prop drilling
  src/components/action-popover/__internal__/action-popover.context.ts
  src/components/action-popover/action-popover-item/action-popover-item.component.tsx
  src/components/action-popover/action-popover-menu/action-popover-menu.component.tsx
  src/components/action-popover/action-popover.component.tsx
  src/components/action-popover/action-popover.pw.tsx
  src/components/action-popover/action-popover.style.ts
  src/components/action-popover/action-popover.test.tsx
Labels: Passed Review, Passed QA, No UX QA Required

#7348 Responsive menu updates
  src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu-item/responsive-vertical-menu-item.component.tsx
  src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu-item/responsive-vertical-menu-item.style.ts
  src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu-test.stories.tsx
  src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.context.tsx
  src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.mdx
  src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.pw.tsx
  src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.stories.tsx
  src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.test.tsx
Labels: Pending Review, Passed QA, Passed UX QA, Squad Front End

#7349 refactor: replace polished with custom utils
  package-lock.json
  package.json
  src/components/icon/icon-test.stories.tsx
  src/components/icon/icon.style.ts
  src/components/icon/icon.test.tsx
  src/components/pill/pill-test.stories.tsx
  src/components/pill/pill.mdx
  src/components/pill/pill.pw.tsx
  src/components/pill/pill.stories.tsx
  src/components/pill/pill.style.ts
  src/components/pill/pill.test.tsx
  src/components/portrait/__internal__/get-colors.test.ts
  src/components/portrait/__internal__/get-colors.ts
  src/components/portrait/portrait.style.tsx
  src/components/portrait/portrait.test.tsx
  src/style/utils/get-accessible-foreground-color.test.ts
  src/style/utils/get-accessible-foreground-color.ts
  src/style/utils/get-hex-value.test.ts
  src/style/utils/get-hex-value.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7365 fix(button, heading, icon-button, tab-title): add preventScroll to progrommatic focus
  src/components/button/button.component.tsx
  src/components/heading/heading.component.tsx
  src/components/icon-button/icon-button.component.tsx
  src/components/tabs/__internal__/tab-title/tab-title.component.tsx
Labels: Passed Review, Passed QA, No UX QA Required

#7371 fix(icon): address react 18.3.0 warning regarding spreading keys
  src/components/icon/icon.component.tsx
Labels: Pending Review, No QA Required, No UX QA Required

#7372 fix(popover-container): aria hidden elements must not be focusable
  src/components/popover-container/popover-container.component.tsx
Labels: Passed Review, Passed QA, Squad Front End

#7385 fix(responsive-vertical-menu): fix issue that stopped off-screen menu items from scrolling into view
  src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.style.ts
Labels: Passed Review, Passed QA, Squad Front End, vertical-menu

#7405 feat(password): add de-DE, es-ES, fr-CA and fr-FR show/hide related translations
  src/locales/de-de.ts
  src/locales/es-es.ts
  src/locales/fr-ca.ts
  src/locales/fr-fr.ts
Labels: Passed Review, Passed QA, No UX QA Required

#7373 fix(menu, multi-action-button, split-button): remove focus first list item on menu-popup open
  src/components/menu/__internal__/submenu/submenu.component.tsx
  src/components/menu/menu-item/menu-item.test.tsx
  src/components/menu/menu.pw.tsx
  src/components/multi-action-button/components.test-pw.tsx
  src/components/multi-action-button/multi-action-button.component.tsx
  src/components/multi-action-button/multi-action-button.pw.tsx
  src/components/multi-action-button/multi-action-button.style.ts
  src/components/multi-action-button/multi-action-button.test.tsx
  src/components/split-button/split-button-children.style.ts
  src/components/split-button/split-button.component.tsx
  src/components/split-button/split-button.pw.tsx
  src/components/split-button/split-button.test.tsx
  src/hooks/__internal__/useChildButtons/useChildButtons.tsx
Labels: Passed Review, Passed QA, Squad Front End, Passed a11y Review
