Repository Sage/carbon, pull requests merged in 2025-04, with the labels that each got.

#7257 feat(deps): upgrade styled-components to v5
  .eslintrc
  package-lock.json
  package.json
  src/__spec_helper__/__internal__/test-utils.ts
  src/components/accordion/accordion.style.ts
  src/components/button-toggle/button-toggle-group/button-toggle-group.test.tsx
  src/components/button/button.component.tsx
  src/components/button/button.style.ts
  src/components/date/__internal__/weekday/weekday.style.ts
  src/components/date/date.stories.tsx
  src/components/decimal/decimal.test.tsx
  src/components/dialog-full-screen/content.style.ts
  src/components/draggable/draggable.test.tsx
  src/components/drawer/drawer.mdx
  src/components/drawer/drawer.stories.tsx
  src/components/duelling-picklist/duelling-picklist-test.stories.tsx
  src/components/duelling-picklist/duelling-picklist.stories.tsx
  src/components/flat-table/flat-table-cell/flat-table-cell.test.tsx
  src/components/flat-table/flat-table-row-header/flat-table-row-header.test.tsx
  src/components/grouped-character/grouped-character.test.tsx
  src/components/hr/hr.test.tsx
  src/components/icon-button/icon-button.test.tsx
  src/components/icon/icon.pw.tsx
  src/components/icon/icon.style.ts
  src/components/loader-spinner/loader-spinner.style.ts
  src/components/menu/menu-item/menu-item.test.tsx
  src/components/message/message.pw.tsx
  src/components/multi-action-button/multi-action-button.style.ts
  src/components/navigation-bar/navigation-bar.test.tsx
  src/components/pages/components.test-pw.tsx
  src/components/pages/page/page.test.tsx
  src/components/popover-container/popover-container-test.stories.tsx
  src/components/popover-container/popover-container.test.tsx
  src/components/portrait/portrait.style.tsx
  src/components/preview/preview.style.ts
  src/components/progress-tracker/progress-tracker.style.ts
  src/components/split-button/split-button-test.stories.tsx
  src/components/tabs/__internal__/tab-title/tab-title.style.ts
  src/components/tabs/__internal__/tabs-header/tabs-header.style.ts
  src/components/text-editor/__internal__/plugins/Toolbar/toolbar.test.tsx
  src/components/textarea/textarea.style.ts
  src/components/textbox/textbox.test.tsx
  src/components/tile/tile.test.tsx
  src/components/typography/typography.component.tsx
  src/components/typography/typography.style.ts
  src/components/vertical-divider/vertical-divider.test.tsx
  src/components/vertical-menu/components.test-pw.tsx
  src/components/vertical-menu/vertical-menu-test.stories.tsx
  src/components/vertical-menu/vertical-menu.test.tsx
  src/global.d.ts
  src/hooks/__internal__/useChildButtons/useChildButtons.tsx
  src/style/design-tokens/carbon-scoped-tokens-provider/__snapshots__/carbon-scoped-tokens-provider.test.tsx.snap
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7287 docs(installation): update version of styled-components
  .storybook/welcome-page/header/header.style.js
  .storybook/welcome-page/selling-points/selling-points.style.js
  README.md
  docs/installation.mdx
Labels: Passed Review, Passed QA, No UX QA Required

#7289 build(storybook): introduce command to enable React Strict Mode for all stories
  .storybook/main.ts
  package.json
Labels: Passed Review, No QA Required, No UX QA Required

#7284 fix(dialog, dialog-full-screen): deprecate disableClose and timeout props
  src/components/dialog-full-screen/dialog-full-screen.component.tsx
  src/components/dialog-full-screen/dialog-full-screen.test.tsx
  src/components/dialog/dialog.component.tsx
  src/components/dialog/dialog.test.tsx
  src/components/modal/modal.component.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7283 fix(switch): loses focus when using Loading state
  src/components/switch/__internal__/switch-slider.component.tsx
  src/components/switch/switch-test.stories.tsx
  src/components/switch/switch.component.tsx
  src/components/switch/switch.pw.tsx
  src/components/switch/switch.test.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#7288 feat(text-editor): add support for `onChange` callback also being called with json and html values
  src/components/text-editor/__internal__/index.ts
  src/components/text-editor/__internal__/plugins/Toolbar/buttons/save.component.tsx
  src/components/text-editor/__internal__/plugins/Toolbar/toolbar.component.tsx
  src/components/text-editor/__internal__/read-only-rte.component.tsx
  src/components/text-editor/index.ts
  src/components/text-editor/text-editor-test.stories.tsx
  src/components/text-editor/text-editor.component.tsx
  src/components/text-editor/text-editor.mdx
  src/components/text-editor/text-editor.pw.tsx
  src/components/text-editor/text-editor.stories.tsx
  src/components/text-editor/utils.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7291 chore(github): update carbon version placeholder to request full version number
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#7277 test: enabled eligible accessibility tests in playwright - FE-7118
  playwright/support/constants.ts
  src/components/anchor-navigation/anchor-navigation.pw.tsx
  src/components/dialog-full-screen/dialog-full-screen.pw.tsx
  src/components/form/form.pw.tsx
  src/components/help/help.pw.tsx
  src/components/icon/icon.pw.tsx
  src/components/numeral-date/numeral-date.pw.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7292 fix(grouped-character): ensure Delete key works as expected
  src/components/grouped-character/grouped-character.component.tsx
  src/components/grouped-character/grouped-character.test.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7274 feat(pager): add small screen styling
  playwright/components/pager/locators.ts
  src/components/flat-table/flat-table.stories.tsx
  src/components/pager/__internal__/pager-navigation.component.tsx
  src/components/pager/pager-test.stories.tsx
  src/components/pager/pager.component.tsx
  src/components/pager/pager.mdx
  src/components/pager/pager.pw.tsx
  src/components/pager/pager.stories.tsx
  src/components/pager/pager.style.ts
  src/components/pager/pager.test.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#7293 fix(flat-table-row-header): correct icon size for expandable rows
  src/components/flat-table/flat-table-row-header/flat-table-row-header.style.ts
  src/components/flat-table/flat-table-test.stories.tsx
Labels: Pending Review, Passed QA, Passed UX QA, Squad Front End

#7297 feat(message): add de-DE, es-ES, fr-CA and fr-FR locale support for the ai variant
  docs/i18n.mdx
  src/components/message/message.component.tsx
  src/components/message/message.mdx
  src/components/message/message.test.tsx
  src/hooks/__internal__/useLocale/useLocale.test.tsx
  src/locales/de-de.ts
  src/locales/es-es.ts
  src/locales/fr-ca.ts
  src/locales/fr-fr.ts
  src/locales/locale.ts
Labels: Passed Review, Passed QA, No UX QA Required

#7302 feat(text-editor): add header and footer support and align with DS
  src/components/note/note.component.tsx
  src/components/text-editor/__internal__/plugins/ContentEditor/content-editor.component.tsx
  src/components/text-editor/__internal__/plugins/ContentEditor/content-editor.style.ts
  src/components/text-editor/__internal__/plugins/LinkPreviewer/link-previewer.component.tsx
  src/components/text-editor/__internal__/plugins/LinkPreviewer/link-previewer.style.ts
  src/components/text-editor/__internal__/plugins/Toolbar/toolbar.component.tsx
  src/components/text-editor/__internal__/plugins/Toolbar/toolbar.style.ts
  src/components/text-editor/components.test-pw.tsx
  src/components/text-editor/text-editor.component.tsx
  src/components/text-editor/text-editor.context.ts
  src/components/text-editor/text-editor.mdx
  src/components/text-editor/text-editor.pw.tsx
  src/components/text-editor/text-editor.stories.tsx
  src/components/text-editor/text-editor.style.ts
  src/components/text-editor/text-editor.test.tsx
  src/locales/de-de.ts
  src/locales/es-es.ts
  src/locales/fr-ca.ts
  src/locales/fr-fr.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End, text-editor

#7308 docs(select): document how to use leftChildren prop to display an Icon in the input field
  src/components/select/filterable-select/filterable-select.stories.tsx
  src/components/select/simple-select/simple-select.mdx
  src/components/select/simple-select/simple-select.stories.tsx
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#7307 feat(fieldset, label): add de-DE, es-ES, fr-CA, fr-FR locale support for the optional indicators
  src/__internal__/fieldset/fieldset.component.tsx
  src/__internal__/fieldset/fieldset.style.ts
  src/__internal__/label/label.component.tsx
  src/__internal__/label/label.style.ts
  src/components/fieldset/fieldset.component.tsx
  src/components/fieldset/fieldset.style.ts
  src/locales/de-de.ts
  src/locales/en-gb.ts
  src/locales/es-es.ts
  src/locales/fr-ca.ts
  src/locales/fr-fr.ts
  src/locales/locale.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7304 fix(text-editor, note): ensure links have correct styles
  src/components/note/note.pw.tsx
  src/components/note/note.stories.tsx
  src/components/note/note.style.ts
  src/components/text-editor/text-editor.pw.tsx
  src/components/text-editor/text-editor.stories.tsx
  src/components/text-editor/text-editor.style.ts
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End

#7268 fix: ensure there is no flash of reduce motion text in Loader components when page is reloaded
  src/components/loader-bar/loader-bar.component.tsx
  src/components/loader-bar/loader-bar.test.tsx
  src/components/loader-spinner/loader-spinner.component.tsx
  src/components/loader-spinner/loader-spinner.test.tsx
  src/components/loader-star/loader-star.component.tsx
  src/components/loader-star/loader-star.test.tsx
  src/components/loader/loader-square.style.ts
  src/components/loader/loader-square.test.tsx
  src/components/loader/loader.component.tsx
  src/components/loader/loader.test.tsx
  src/components/switch/__internal__/switch-slider-panel.test.tsx
  src/hooks/useMediaQuery/useMediaQuery.ts
Labels: Pending Review, Passed QA, No UX QA Required, Squad Front End

#7306 feat(icon): 15 new icons added - 2 updated
  src/components/icon/__snapshots__/icon-unicodes.test.js.snap
  src/components/icon/fonts/carbon-icons-webfont.woff
  src/components/icon/fonts/carbon-icons-webfont.woff2
  src/components/icon/icon-config.ts
  src/components/icon/icon-type.ts
  src/components/icon/icon-unicodes.js
  src/style/assets/carbon-icons-webfont.woff
  src/style/assets/carbon-icons-webfont.woff2
Labels: Passed Review, Passed QA, Passed UX QA

#7300 feat(menu): subcomponents log console warning when used outside Menu (FE-7202)
  src/__internal__/utils/createStrictContext.ts
  src/__internal__/utils/logger/index.ts
  src/__internal__/utils/logger/logger.test.ts
  src/components/link/link.test.tsx
  src/components/menu/__internal__/keyboard-navigation/index.test.tsx
  src/components/menu/__internal__/menu.context.ts
  src/components/menu/__internal__/menu.context.tsx
  src/components/menu/__internal__/strict-menu.context.ts
  src/components/menu/__internal__/submenu/submenu.component.tsx
  src/components/menu/__internal__/submenu/submenu.style.ts
  src/components/menu/__internal__/submenu/submenu.test.tsx
  src/components/menu/component.test-pw.tsx
  src/components/menu/index.ts
  src/components/menu/menu-divider/menu-divider.component.tsx
  src/components/menu/menu-divider/menu-divider.style.ts
  src/components/menu/menu-divider/menu-divider.test.tsx
  src/components/menu/menu-full-screen/menu-full-screen.component.tsx
  src/components/menu/menu-full-screen/menu-full-screen.style.ts
  src/components/menu/menu-full-screen/menu-full-screen.test.tsx
  src/components/menu/menu-item/menu-item.component.tsx
  src/components/menu/menu-item/menu-item.style.ts
  src/components/menu/menu-item/menu-item.test.tsx
  src/components/menu/menu-segment-title/menu-segment-title.component.tsx
  src/components/menu/menu-segment-title/menu-segment-title.style.ts
  src/components/menu/menu-segment-title/menu-segment-title.test.tsx
  src/components/menu/menu-test.stories.tsx
  src/components/menu/menu.component.tsx
  src/components/menu/menu.stories.tsx
  src/components/menu/menu.style.ts
  src/components/menu/menu.types.ts
  src/components/menu/scrollable-block/scrollable-block.component.tsx
  src/components/menu/scrollable-block/scrollable-block.style.ts
  src/components/menu/scrollable-block/scrollable-block.test.tsx
  src/components/vertical-divider/vertical-divider.component.tsx
  src/components/vertical-divider/vertical-divider.test.tsx
Labels: Passed Review, Passed QA, No UX QA Required

#7314 Deprecate "optional" prop
  src/__internal__/checkable-input/checkable-input.component.tsx
  src/__internal__/fieldset/fieldset.component.tsx
  src/__internal__/fieldset/fieldset.style.ts
  src/__internal__/fieldset/fieldset.test.tsx
  src/__internal__/form-field/form-field.component.tsx
  src/components/checkbox/checkbox-group/checkbox-group.component.tsx
  src/components/checkbox/checkbox-group/checkbox-group.test.tsx
  src/components/date-range/date-range.component.tsx
  src/components/date-range/date-range.test.tsx
  src/components/fieldset/fieldset.component.tsx
  src/components/fieldset/fieldset.style.ts
  src/components/fieldset/fieldset.test.tsx
  src/components/file-input/file-input.component.tsx
  src/components/file-input/file-input.test.tsx
  src/components/inline-inputs/inline-inputs.component.tsx
  src/components/inline-inputs/inline-inputs.test.tsx
  src/components/numeral-date/numeral-date.component.tsx
  src/components/numeral-date/numeral-date.test.tsx
  src/components/radio-button/radio-button-group/radio-button-group.component.tsx
  src/components/radio-button/radio-button-group/radio-button-group.test.tsx
  src/components/select/__internal__/select-textbox/select-textbox.component.tsx
  src/components/select/filterable-select/filterable-select.component.tsx
  src/components/select/filterable-select/filterable-select.test.tsx
  src/components/select/multi-select/multi-select.component.tsx
  src/components/select/multi-select/multi-select.test.tsx
  src/components/select/simple-select/simple-select.component.tsx
  src/components/select/simple-select/simple-select.test.tsx
  src/components/text-editor/text-editor.component.tsx
  src/components/text-editor/text-editor.test.tsx
  src/components/textarea/textarea.component.tsx
  src/components/textarea/textarea.test.tsx
  src/components/textbox/textbox.component.tsx
  src/components/textbox/textbox.test.tsx
  src/components/time/time.component.tsx
  src/components/time/time.test.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End
