Repository Sage/carbon, pull requests merged in 2025-05, with the labels that each got.

#7299 chore: turn off no await in loop rule - FE-7119
  .eslintrc
  playwright/support/helper.ts
  src/components/batch-selection/batch-selection.pw.tsx
  src/components/dialog-full-screen/dialog-full-screen.pw.tsx
  src/components/drawer/drawer.pw.tsx
  src/components/duelling-picklist/duelling-picklist.pw.tsx
  src/components/flat-table/components.test-pw.tsx
  src/components/flat-table/flat-table.pw.tsx
  src/components/link/components.test-pw.tsx
  src/components/link/link.pw.tsx
  src/components/menu/menu.pw.tsx
  src/components/portrait/portrait.pw.tsx
  src/components/search/components.test-pw.tsx
  src/components/search/search.pw.tsx
  src/components/split-button/split-button.pw.tsx
  src/components/tile-select/components.test-pw.tsx
  src/components/tile-select/tile-select.pw.tsx
  src/components/tooltip/tooltip.pw.tsx
Labels: Passed Review, Passed QA, Research, No QA Required, Squad Front End

#7322 chore: restrict react-day-picker to 9.3 range
  package-lock.json
  package.json
Labels: Passed Review, No QA Required, No UX QA Required, Squad Front End

#7318 chore(dep-devs): bump vite to version 6.3.4
  package-lock.json
  package.json
Labels: Passed Review, No QA Required, No UX QA Required

#7315 fix(button): ensure button focuses on click for Safari compatibility
  src/components/button/button.component.tsx
Labels: Bug, Passed Review, Passed QA, No UX QA Required, Squad Front End

#7312 feat(text-editor): adds onBlur and onFocus support to Text Editor
  src/components/text-editor/__internal__/helpers.ts
  src/components/text-editor/__internal__/plugins/EditorRef/editor-ref.plugin.tsx
  src/components/text-editor/__internal__/plugins/EditorRef/index.ts
  src/components/text-editor/__internal__/plugins/Toolbar/toolbar.component.tsx
  src/components/text-editor/text-editor.component.tsx
  src/components/text-editor/text-editor.mdx
  src/components/text-editor/text-editor.pw.tsx
  src/components/text-editor/text-editor.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required, text-editor, Squad PDS

#7325 docs(file-input): clarify single file upload limitation in tracking u…
  src/components/file-input/file-input.mdx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7298 feat(vertical-menu): implements updates required for Global Nav v2
  playwright/components/vertical-menu/responsive-vertical-menu/index.ts
  playwright/components/vertical-menu/responsive-vertical-menu/locators.ts
  src/components/vertical-menu/index.ts
  src/components/vertical-menu/responsive-vertical-menu/__internal__/depth.context.tsx
  src/components/vertical-menu/responsive-vertical-menu/__internal__/focus.context.tsx
  src/components/vertical-menu/responsive-vertical-menu/components.test-pw.tsx
  src/components/vertical-menu/responsive-vertical-menu/index.ts
  src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu-divider/index.ts
  src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu-divider/responsive-vertical-menu-divider.component.tsx
  src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu-divider/responsive-vertical-menu-divider.stories.tsx
  src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu-divider/responsive-vertical-menu-divider.style.ts
  src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu-item/index.ts
  src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu-item/responsive-vertical-menu-item.component.tsx
  src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu-item/responsive-vertical-menu-item.stories.tsx
  src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu-item/responsive-vertical-menu-item.style.ts
  src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu-test.stories.tsx
  src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.component.tsx
  src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.context.tsx
  src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.mdx
  src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.pw.tsx
  src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.stories.tsx
  src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.style.ts
  src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.test.tsx
Labels: Passed Review, Passed QA, Passed UX QA, Squad Front End, Passed a11y Review, vertical-menu

#7331 fix(switch): correct z-index in switch-slider
  src/components/switch/__internal__/switch-slider.style.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7338 feat(password): add translation keys for Hide/Show button
  src/components/password/password.component.tsx
  src/components/password/password.mdx
  src/locales/en-gb.ts
  src/locales/locale.ts
Labels: Passed Review, Pending QA, No UX QA Required, Squad Front End

#7324 feat(typography): updated font sizes and weights
  src/components/heading/heading.style.ts
  src/components/typography/typography.pw.tsx
  src/components/typography/typography.style.ts
  src/components/typography/typography.test.tsx
Labels: Passed Review, Passed QA, Passed UX QA

#7334 fix(decimal): ensure invariant message is not thrown when using strict mode - FE-7198
  package-lock.json
  package.json
  src/components/decimal/decimal.component.tsx
  src/components/decimal/decimal.test.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7335 fix(text-editor): ensure required and invalid states are semantically conveyed to users
  src/components/text-editor/__internal__/plugins/ContentEditor/content-editor.component.tsx
  src/components/text-editor/text-editor.component.tsx
  src/components/text-editor/text-editor.mdx
  src/components/text-editor/text-editor.test.tsx
Labels: Passed Review, Passed QA, Squad Front End, Passed a11y Review

#7337 test(playwright): output incomplete accessiblity findings to console
  playwright/support/helper.ts
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7344 feat(text-editor): add programmatic focus support for the text editor
  src/components/text-editor/__internal__/plugins/Toolbar/toolbar.test.tsx
  src/components/text-editor/index.ts
  src/components/text-editor/text-editor.component.tsx
  src/components/text-editor/text-editor.mdx
  src/components/text-editor/text-editor.stories.tsx
  src/components/text-editor/text-editor.test.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7332 fix(text-editor): allow custom plugins to be passed to the text editor
  src/components/text-editor/text-editor.component.tsx
  src/components/text-editor/text-editor.mdx
  src/components/text-editor/text-editor.stories.tsx
  src/components/text-editor/text-editor.test.tsx
Labels: Passed Review, Passed QA, Squad Front End

#7323 chore: replace babel build with rollup and swc
  .gitignore
  package-lock.json
  package.json
  rollup.config.mjs
  scripts/build.js
  scripts/copy-files.js
  scripts/copy_svg/index.js
  scripts/generate_package_json_files/index.js
  src/components/action-popover/__internal__/action-popover.utils.tsx
  src/components/action-popover/action-popover-menu/action-popover-menu.component.tsx
  src/components/action-popover/action-popover.component.tsx
  src/components/date-range/index.ts
  src/components/dialog/index.ts
  src/components/link/link.style.ts
  src/components/note/note.style.ts
  src/components/text-editor/__internal__/constants.ts
  src/components/text-editor/__internal__/plugins/Toolbar/buttons/bold.component.tsx
  src/components/text-editor/__internal__/plugins/Toolbar/buttons/common.types.ts
  src/components/text-editor/__internal__/plugins/Toolbar/buttons/italic.component.tsx
  src/components/text-editor/__internal__/style.css
  src/components/text-editor/text-editor.style.ts
  src/index.ts
  src/style/themes/none/none.test.ts
  src/style/themes/test-utils.ts
  tsconfig-build.json
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7346 chore(storybook): install addon interactions, test and pseudo packages
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/utils/user-interaction-pause.ts
  package-lock.json
  package.json
  src/components/action-popover/action-popover-test.stories.tsx
  src/components/button/button-test.stories.tsx
Labels: Passed Review, Passed QA, No UX QA Required, Squad Front End

#7355 fix(icon-button): fixes missing focus styling when using icon buttons in Safari
  src/components/icon-button/icon-button.component.tsx
Labels: Passed Review, Passed QA, Squad Front End, icon-button
